### ISSUE TITLE
Wrong case on filename if outputBy is "NamespacePath"

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#103]
#### bridge.json

``` javascript
{
    output: "Bridge\\output",
    outputBy:  "NamespacePath"
}
```

#### Demo.cs

``` csharp
using Bridge;

namespace Demo.Utils
{
    public class App
    {
        public string Test { get; set; }
    }
}
```

`demo > utils.js` is expected, but `demo > Utils.js` is created.

![screenshot 2015-03-31 21 49 56](https://cloud.githubusercontent.com/assets/62210/6934323/e4f5d4fc-d7ef-11e4-9be5-f5b19b41dfb5.png)

**Comment by fabriciomurta** [comment]
Fixing this will ultimately lead to an inconsistency when absolute paths are used (as explicitly required by issue #57).

When an absolute path is provided, it is not possible to identify what is a FS directory (thus casing should be preserved) and what pertains to the project naming scheme.

Said that, I think the best approach here is to develop a solution that does not perform camel casing conversion when the path is absolute, starting with a drive letter.

**Comment by geoffreymcgill** [comment]
At this point I don't see a problem treating absolute paths as a special scenario. Everything but the final fileName could ignore the casing config. Maybe absolute paths should be removed, and only available to set on the `output` config within **bridge.json**. I'd be fine with that approach.

**Comment by fabriciomurta** [comment]
I'd love to reopen that issue and make absolute paths not an option anymore! (all constrained inside bridge's output directory that's always set on bridge.json)

**Comment by geoffreymcgill** [comment]
Agreed. Let's get ride of that absolute path functionality. It will only exist on the `output` global config.

**Comment by fabriciomurta** [comment]
Misreferenced commit #e41ec5 which applies fix here.
