### ISSUE TITLE
Add way to stop void template functions from generating semi-colons.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1032]
Add way to stop void template functions from generating semi-colons.
Probably add an extra parameter to template so you could do stuff like loops.

**Comment by LeonidVeriga** [comment]
Hi @michaelcheers!

Can you please elaborate your suggestion. Probably a sample in Bridge.Live.
Do you mean `[Template("")]`? http://live.bridge.net/#919774bc66ca95c796bd

**Comment by geoffreymcgill** [comment]
No further information was provided. Closing issue. 

We will re-open if a simplified sample demonstrating how to reproduce is provided by someone.
