### ISSUE TITLE
Bridge.Collections NuGet build isn't working for 4.0

### ISSUE THREAD

**Issue by TinkerWorX** [bridgedotnet/Bridge#1037]
### Expected
Bridge.Collections indicates it works with 4.0 when adding the reference.

### Actual
When building/compiling the following warning comes up.
> The primary reference "Bridge.Collections, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.5" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0".

While not an error, it does prevent the javascript compilation of the project. 

### Steps To Reproduce
Create a .net 4.0 project, add `Bridge` and `Bridge.Collections` the NuGet. Use anything from the `Bridge.Collections` assembly. Compile the project.

**Comment by geoffreymcgill** [comment]
Thanks for the report. Should be an easy fix.

**Comment by LeonidVeriga** [comment]
The problem is fixed as part of [bridgedotnet/Frameworks#32] and requires publishing new Bridge.Collections package
