### ISSUE TITLE
Progress handling with IPromise

### ISSUE THREAD

**Issue by caesay** [bridgedotnet/Bridge#1038]
The `IPromise` interface has a method parameter for a progress handler since [62d73a2](https://github.com/bridgedotnet/Bridge/commit/62d73a22f0409eeda93075d3539ed3633a5f9db8), but no way to assign it from `Task.FromPromise`

### Expected
`Task.FromPromise<>` has an overload with progressHandler support.

### Actual
Not Supported.

### Steps To Reproduce
0. Create class that derives from `IPromise`
0. Try to call it from Task.FromPromise with a result, error, and progress handler.
0. Fail.

**Comment by DaniilVeriga** [comment]
Thank you for the feature request! It is planned to add into 1.12.
