### ISSUE TITLE
Update Decimal.js to the latest version

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#1039]
https://github.com/MikeMcl/decimal.js

The current version is 4.0.2.
The latest available is 5.0.7.

Here is a changelog of Decimal.js versions.
https://github.com/MikeMcl/decimal.js/blob/master/CHANGELOG.md

Actually, Decimal.js has been already updated to 5.0.7 in this commit (**64bit_support** branch):
https://github.com/bridgedotnet/Bridge/commit/05ea3b1f7999a97f873aa3eca5cab946d6eedccd

Just created an Issue as it is worth to have it logged individually.

The **64bit_support** branch (the `long` support - #778) is going to be merged in v1.12.

Most likely, this is going to fix the issue with 15 digits limitation:
http://forums.bridge.net/forum/community/help/1308

**Comment by vladsch** [comment]
Updated in #778
