### ISSUE TITLE
Skip file generation during nuget updates

### ISSUE THREAD

**Issue by strygo** [bridgedotnet/Bridge#1042]
### Expected
Previously removed files like demo.html, README.md and bridge.json are re-added or modified during a nuget package update.

### Actual
During an update, any files that were previously removed from the project shouldn't be re-added.

### Steps To Reproduce
Create a project, remove default files and then upgrade nuget packages.

Update by @DaniilVeriga:

There is a related forum discussion:
http://forums.bridge.net/forum/community/help/311

**Comment by geoffreymcgill** [comment]
This is a process that is controlled by NuGet, not us. 

We're looking into creating a stripped down NuGet package that does not include some of those files, but still... if you install the main **Bridge** NuGet package, NuGet will refresh those files the next time it updates.

**Comment by geoffreymcgill** [comment]
We've added a new **Bridge.Min** NuGet package to the upcoming Bridge 1.13 release.

The **Bridge.Min** package will install only the minimum required references and files needed to compile. 

The **/Bridge/** folder and **bridge.json** file are not added with **Bridge.Min**. If these features are required, you can either manually create, or install the main **Bridge** package (`Install-Package Bridge`).

The **Bridge.Html5** package is not included with **Bridge.Min**. You can install **Bridge.Html5** separately by running the following command in the NuGet Package Manager Console:

```Install-Package Bridge.Html5```

Changes have been made in the main **Bridge** NuGet package as well. The Bridge related files (README.md, LICENSE, etc) that were being added to the **App_Readme** have been moved into the root of the NuGet package and will not be added to your project.

Another important package that's been added is **Bridge.Clean**, which helps clean up the .csproj file by working around the red _Squiggles_ defect in Visual Studio. See Issue #419.

This **Bridge.Clean** package needs to be run manually, and is not included with any other packages. The package only needs to be installed once, and can actually be uninstalled immediately after installing. Once installed the required changes have been set and no further package updates are required. 

```Install-Package Bridge.Clean```

We'll have more to say with the 1.13 blog post. 

If you have any questions, please feel free to ask here and we'll do our best to assist. 

Hope this helps.
