### ISSUE TITLE
Template of setter is ignored in object initialization.

### ISSUE THREAD

**Issue by Dia6lo** [bridgedotnet/Bridge#1052]
### Expected
```javascript
var foo = new Foo();
foo.setBar(true);
var baz = foo.currentBar;
```

### Actual
```javascript
var foo = Bridge.merge(new Foo(), {
    currentBar: true
});
var baz = foo.currentBar;
```

### Steps To Reproduce

```csharp
public class App
{
	[Ready]
	public static void Main()
	{
		var foo = new Foo {
			Bar = true
		};
		var baz = foo.Bar;
	}
}

[External]
[Name("Foo")]
public class Foo
{
	[FieldProperty]
	[Name("currentBar")]
	public bool Bar
	{
		get { return false; }
		[Template("setBar({0})")]
		set { }
	}
}
```

**Comment by vladsch** [comment]
FieldProperty and Template cannot be used at the same time for property
Use Template for getter also
Please see http://live.bridge.net/#efe17cfa8f867af0b25c

**Comment by Dia6lo** [comment]
Sorry, I can't see how your example solves the problem. Let me make it more clear: in Javascript I have a method for setting but not for getting and I want to map it to C# property. If I try to do object initialization in C# code my Javascript code doesn't call setter method and just assigns value to field instead.

**Comment by vladsch** [comment]
Bridge.merge will call setter. It will detect that setBar is function and call it with value as argument

**Comment by Dia6lo** [comment]
Oh, that's great, problem is solved then. I've overlooked that setbar was replaced with currentBar when I used FieldProperty and Template, so your first answer is helpful too. 2 points for Griffindor ;)

**Comment by vladsch** [comment]
Please note, that Bridge.merge will invoke function if name has 'set' prefix (which is default for properties are emitted by Bridge)
In future, we are going to improve it to invoke function if the value is not function (and key is function)

**Comment by Dia6lo** [comment]
Okay, thanks for pointing this out.
