### ISSUE TITLE
Builder is returning 0 exit code when crashed

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#1054]
### Expected

Builder is **not** returning 0 exit code when crashed
A related forum thread:
http://forums.bridge.net/forum/bridge-net-pro/bugs/1799

### Actual

Builder is returning 0 exit code when crashed

### Steps To Reproduce

I would expect that passing any invalid code should reproduce the problem.

**Comment by fabriciomurta** [comment]
The two other issues fixed along with this are slated 1.13 milestone but maybe they can be pulled in 1.12 as well. See related pull request.
