### ISSUE TITLE
Add Builder/Compiler version in a log

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#1055]
The feature request has been stated in this forum thread:
http://forums.bridge.net/forum/bridge-net-pro/bugs/1799

### Expected

`bridge.log` contains product info as following
```
Bridge.Compiler version 1.12.0
[Bridge Framework, version 1.12.0]
Copyright 2008-2016 Object.NET, Inc.
```

### Actual

No version

**Comment by fabriciomurta** [comment]
here's an example (from msbuild):
```
$ "$msbuild"
Microsoft (R) Build Engine version 12.0.31101.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 30/03/2016 5:16:51 PM.
```

From xbuild (linux):
```
XBuild Engine Version 12.0
Mono, Version 4.2.2.0
Copyright (C) 2005-2013 Various Mono authors

Build started 3/30/2016 5:17:20 PM.
```

Bridge should have something similar to this. Both build (task) and Builder (executable) should have this when they are run. This could be printed from translator.translate() for a common place to print the translator/emitter version!
