### ISSUE TITLE
Cast exception if [Name(false)] set on Class

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#1058]
http://bridge.net/kb/attribute-reference/#Name

Live Bridge sample
http://live.bridge.net/#ddce9986f1bff5b28884

### Expected

Not sure, but maybe this can solve the following forum request?

http://forums.bridge.net/forum/general/feature-requests/1815

### Actual

Throws compile time exception:

```// Line 0, Col 0 : Unable to cast object of type 'System.Boolean' to type 'System.String'.```

### Steps To Reproduce

```csharp
public class App
{
    [Ready]
    public static void Main()
    {
        var x =  OverlayType.MARKER;
        var y =  OverlayType.CIRCLE;
    }
}

[Name(false)]
public enum OverlayType
{
    CIRCLE,
    MARKER,
}
```

**Comment by vladsch** [comment]
It is a bug, what about expectation: Name should affect on enum name only (not on enum items)

**Comment by geoffreymcgill** [comment]
I'm not entirely sure this `false` override is required.
