### ISSUE TITLE
Does Bridge.NET work with Mono on Linux?

### ISSUE THREAD

**Issue by wind39** [bridgedotnet/Bridge#106]
Does it?

**Comment by fabriciomurta** [comment]
We have been developing bridge solely on Visual Studio, .NET and Windows, so I can't really say it doesn't. It might need some adjustments in order for it to work on Mono, though. As an open source project, I don't see a huge barrier having it running on mono. It just shouldn't do _out-of-the-box_ yet.

**Comment by wind39** [comment]
Thank you for your response.

I don't think a VS Extension is likely to work on MonoDevelop. So for now I can't use the project template.

I'm going to try to understand what Bridge.NET does when the "Build" button is clicked. Maybe it can be done on Linux too, with simple commands. I'll post here if I find out something.

**Comment by Mimisss** [comment]
@wind39 I think your best bet is our nuget packages. You may want to read this introduction on how to set everything up without the vsix: http://www.codeproject.com/Articles/892443/Build-platform-independent-applications-using-Brid  You probably need to skip all about the optional batch files, too.

**Comment by wind39** [comment]
Thank you, @Mimisss, nice article.

I tried to build the Questionnaire solution on MonoDevelop on Linux. System.Array was conflicting with mscorlib, so I checked "do not reference mscorlib.dll" on the project options.

But now the FormBuilder project still doesn't compile, it fails with error: Questionnaire/packages/Bridge.1.0.0/build/Bridge.targets: Error: Error: Unsupported platform - Unix (FormBuilder)

So I guess even thourgh Nuget, Bridge.NET is still bound to .NET / Windows.

**Comment by fabriciomurta** [comment]
I'd say, for now, only way to get thru and make it go on Mono would be building it from sources. And any heads up regarding changes needed to make it work on Mono would be gladly received!

**Comment by geoffreymcgill** [comment]
I'll try and take a crack at getting Bridge to run on Mono. I'll need a few days as I'm up to my eyeballs in other critical tasks, but we should be able to get this working. Actually, we WILL get this working.

**Comment by wind39** [comment]
Thank you, @geoffreymcgill, I couldn't make Bridge.NET work on Mono, and I'm looking forward for this implementation.

**Comment by fabriciomurta** [comment]
Hello @wind39! We're building Bridge.NET with mono on OS X. Little or nothing takes it to run on linux as well. We're also using it with (Visual Studio Code)[http://code.visualstudio.com/].

We will be releasing soon a step-by-step to run one of our Demos but if you're willing to run it already, you should be able to run on VSCode the demo on https://github.com/bridgedotnet/Demos, under the `VSCode/Demo` directory.

Once you open it on VSCode, go to `View` => `Command Palette`, type in `tasks` and choose `Run Build Task`. Then you'll see the output bridge test if you expand the `output` folder on VSCode. You can see it in action (its just a simple `window.alert()` test) by opening `www/demo.html`.

I'll update this once more when we have the full knowledge base article published.

**Comment by wind39** [comment]
Hi @fabriciomurta, thank you for your response. Good news! :)

At first I tried to build Bridge on Linux, but I couldn't. So I created specific solution files for Linux, and now I'm able to build, as you can se in [PR 268](https://github.com/bridgedotnet/Bridge/pull/268).

With this PR, I also could successfully build and execute the VSCode Demo you mentioned, although I'm not using VSCode itself.

Now I'm going to read all [Bridge.NET Knowledge Base](http://bridge.net/kb/) and see if I can develop, build and execute all Bridge features on Linux by myself :+1: 

But I'll be waiting for your updates on https://github.com/bridgedotnet/Demos.

**Comment by fabriciomurta** [comment]
Cool! That's really awesome, thanks! When I said I was building Bridge on Linux, it was just Bridge application not Bridge itself. In other words, using bridge prebuilt (from NuGet) binaries, making JavaScript out of C# code. :)

I am working on VSCode and Mono/DNX to try and make a very clean demo. Currently I'm studying what could I do to use UsingTasks on a project with just project.json (not .csproj) format. I have to call Bridge.Builder.dll from mono instead of Bridge.Builder.exe; and the DLL one is called as said build task.

Once I have this done, I'll have a simple project with project.json which pulls the NuGet lib, build and makes intellisense work with whatever uses OmniSharp.

Thanks again for your invaluable contribution!

**Comment by fabriciomurta** [comment]
_"With this PR, I also could successfully build and execute the VSCode Demo you mentioned, although I'm not using VSCode itself."_

Yes. The idea in the demo is to be able to pull the NuGet packages and run instead of requiring the user to build all the stuff. On a second moment, a demo which pulls and builds the whole stuff could happen as well.

**Comment by wind39** [comment]
Great, @fabriciomurta! :+1: 

I builded the Window.Alert demo on Linux using builder.sh. But I want to work with Bridge directly on MonoDevelop, because I'm comfortable with this IDE for large projects.

I'll post if I find some issues with MonoDevelop, but it doesn't seem likely.

**Comment by fabriciomurta** [comment]
By the way, I believe @antonmes has already set up things on bridge (the sources, like you did) to build on linux on his fork of the demo project (see #238).

Essentially, to have intellisense working he copypasted all bridge repositories (Bridge, Builder, Frameworks) besides the Demo project and made the demo refer to the side-built Bridge. I didn't get to  the bottom on his approach yet as I am investigating a way for the demo to get from NuGet, build and run without having binary files committed (as Bridge.Builder.exe -- which is not in NuGet package). 

But I'm pretty sure he built all Bridge on *nix as well.

**Comment by wind39** [comment]
Thank you, @fabriciomurta. You point out something very important to me: I need to try to build Frameworks and Bulder repos also. I only managed to build Bridge repo, which seems to be easier.

About intellisense, I created a PR ([#18](https://github.com/bridgedotnet/Demos/pull/18) on Demos repo, with an example of a solution for MonoDevelop. I could use Bridge.Builder.exe, and MonoDevelop provides intellisense by using directly the referenced Bridge DLLs, without the need of copypasting all bridge repositories besides the Demo project.

**Comment by fabriciomurta** [comment]
Alright, I believe #271 and bridgedotnet/Builder#6 improves linux support.
- Bridge.NET solution Fully build-able from xbuild or MonoDevelop/XamarinStudio
- Projects using Bridge.NET will be able to build from `Bridge.Build.dll` (UsingTask)

Pre-requisites are (not thoroughly tested) using Mono 4.x.

When 1.6 version is released, you'll be able to simply get the NuGet package with MonoDevelop and build your project. No more DLL committing will be necessary. 

Your feedback is greatly appreciated. We can re-open this issue or any related to this anytime.
