### ISSUE TITLE
Inconsistent character representations

### ISSUE THREAD

**Issue by t-nelis** [bridgedotnet/Bridge#1061]
### Situation

The `"1".Any(c => char.IsDigit(c))` expression yields false.

### Repro

[Live](http://live.bridge.net/#f8af2f4fcb5f78a9f47e)

```csharp
    public class App
    {
        [Ready]
        public static void Main()
        {
            Contract.Assert(char.IsDigit('1'));
            Contract.Assert("1".Any(c => char.IsDigit(c)));
        }
    }
```
*(The first assertion is a sanity check, which passes.)*

### Understanding

Looking at how the first assertion statement is compiled, we see the `'1'` expression is emitted as a Javascript number literal.

```javascript
Bridge.Contract.assert(4, function () { return Bridge.Char.isDigit(49); });
```

Looking at how the `String` enumerator implementation works:

```javascript
return (index < obj.length) ? this.yieldReturn(obj.charAt(index++)) : false;
```
*([`Bridge\Resources\linq.js` L303 @ 389a585e0d73d2c8397fea9d9df3d15914f0dbd0](https://github.com/bridgedotnet/Bridge/blob/389a585e0d73d2c8397fea9d9df3d15914f0dbd0/Bridge/Resources/linq.js#L303))*

We observe it uses [charAt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charAt) which returns a [Javascript `string`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type).

```javascript
console.assert(typeof '1'.charAt(0) === 'string', 'charAt returns a string');
```

This seems to break the assumption of Bridge's `Char.IsDigit` implementation that characters are internally represented as [Javascript numbers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type).

```javascript
        isDigit: function (value) {
            if (value < 256) {
                return (value >= 48 && value <= 57);
            }

            return new RegExp("[0-9\u0030-\u0039\u0660-\u0669\u06F0-\u06F9\u07C0-\u07C9\u0966-\u096F\u09E6-\u09EF\u0A66-\u0A6F\u0AE6-\u0AEF\u0B66-\u0B6F\u0BE6-\u0BEF\u0C66-\u0C6F\u0CE6-\u0CEF\u0D66-\u0D6F\u0E50-\u0E59\u0ED0-\u0ED9\u0F20-\u0F29\u1040-\u1049\u1090-\u1099\u17E0-\u17E9\u1810-\u1819\u1946-\u194F\u19D0-\u19D9\u1A80-\u1A89\u1A90-\u1A99\u1B50-\u1B59\u1BB0-\u1BB9\u1C40-\u1C49\u1C50-\u1C59\uA620-\uA629\uA8D0-\uA8D9\uA900-\uA909\uA9D0-\uA9D9\uAA50-\uAA59\uABF0-\uABF9\uFF10-\uFF19]").test(String.fromCharCode(value));
        },
```
*([`Bridge\Resources\Char.js` L20 @ 389a585e0d73d2c8397fea9d9df3d15914f0dbd0](https://github.com/bridgedotnet/Bridge/blob/389a585e0d73d2c8397fea9d9df3d15914f0dbd0/Bridge/Resources/Char.js#L20))*

Or a bit worse, you might be using inconsistent representations for characters in different parts of the codebase; hopefully the bug is confined to this part.

### Detail

If it's unclear, the immediate bug here is that Javascript strings of characters representing numbers below 256 will be [converted to primitive Javascript numbers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators).

> For relational abstract comparisons (e.g., <=), the operands are first converted to primitives, then to the same type, before comparison.

Yet, the implementation clearly expects a UTF-16 [code unit](https://en.wikipedia.org/wiki/UTF-16) represented as a Javascript number.

### Tentative resolution

I imagine you might want to standardize on a single representation for C# `char` values everywhere, or at least use some sort of polymorphic representation. I have not scanned or reviewed the rest of the codebase to assess severity, I hope it's a quick fix for you guys (say [`charCodeAt`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt) instead of `charAt` in the string enumerator).

### Suggestions

I'm not 100% on the necessity for the slow paths (using regular expressions after converting back to string) used throughout the `Char` implementation. If I'm missing something, I suggest removing the redundant cases that would be handled by the fast path (e.g. the `0-9` range expression in `isDigit`). If not, then you could forgo the regexes altogether and check the ranges using normal conditional statements (as in the fast paths) which should be quickly jitted and thus more efficient (and more importantly simpler IMO, those regexes look a little daunting at first sight).

### Correctness

[`Char.IsDigit`](https://msdn.microsoft.com/en-us/library/7f0ddtxh) is defined in .NET as matching characters in the `UnicodeCategory.DecimalDigitNumber` category, in turn [defined](https://msdn.microsoft.com/en-us/library/system.globalization.unicodecategory) as:

> Decimal digit character, that is, a character in the range 0 through 9. Signified by the Unicode designation "Nd" (number, decimal digit). [...]

Unicode [calls it `Decimal_Number`](http://www.unicode.org/reports/tr44/#General_Category_Values). As you can see in [the list of "general categories"](http://www.unicode.org/Public/UCD/latest/ucd/extracted/DerivedGeneralCategory.txt), there are code points in the astral planes. Not dismissing the importance of non-western scripts, note that this includes a range of symbols from the [Mathematical Alphanumeric Symbols](Mathematical Alphanumeric Symbols) block, which is more universally relevant.

I mention this since the current code only seems to handle the [BMP](https://en.wikipedia.org/wiki/Plane_%28Unicode%29#Basic_Multilingual_Plane) (even in the slow path) because of the limitations of [`fromCharCode`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode).

You could use [`fromCodePoint`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCodePoint) and say polyfill for <ES6 (or do something more complicated) but again, there doesn't seem to be any real obstacle to just using the `value` arguments directly as in the fast path. Indeed the maximum Unicode codepoint value of 0x10FFFF (end of plane 16) is way below the [maximum value for safe integer representation with Javascript numbers](http://www.ecma-international.org/ecma-262/6.0/#sec-number.max_safe_integer) (2^53-1): log₂ 0x10FFFF = ~20.087461546. So again unless I'm missing something the regex approach seems unnecessarily convoluted and in this case apparently incorrect even if a character is passed in the expected representation.

### Version information

We hit this on 1.11.2. *Warning: The linked files are from master's head at the time of this writing so technically there could have been relevant changes in between.*

**Comment by DaniilVeriga** [comment]
@t-nelis, I am speechless how great the bug report is. Thank you very much.

Yes, that is a bit of the problem. We'll be looking into that.

**Comment by LeonidVeriga** [comment]
Hi @t-nelis,

Yes, `charCodeAt` is the solution.
Thank you for amazing report.

**Comment by t-nelis** [comment]
@LeonidVeriga @vladsch Thank you very much for the patch. This fixes our own immediate bug so I probably won't be tracking this much anymore, but let me note here that the patch, as far as I understand it, still leaves the implementation incorrect with regard to characters outside the BMP. (I could also be wrong about the whole thing of course, I haven't made any extensive tests, but I was reasonably sure from the quick look I gave it two weeks ago.)

It makes sense that you wouldn't want to fix that now, I guess those language systems are not too common within your userbase. Hopefully this thread contains enough keywords that it can be found by users who may encounter the problem in the future. I'll embed the Unicode table for decimal number blocks in the relevant locales below to further improve searchability.

```
104A0..104A9  ; Nd #  [10] OSMANYA DIGIT ZERO..OSMANYA DIGIT NINE
11066..1106F  ; Nd #  [10] BRAHMI DIGIT ZERO..BRAHMI DIGIT NINE
110F0..110F9  ; Nd #  [10] SORA SOMPENG DIGIT ZERO..SORA SOMPENG DIGIT NINE
11136..1113F  ; Nd #  [10] CHAKMA DIGIT ZERO..CHAKMA DIGIT NINE
111D0..111D9  ; Nd #  [10] SHARADA DIGIT ZERO..SHARADA DIGIT NINE
112F0..112F9  ; Nd #  [10] KHUDAWADI DIGIT ZERO..KHUDAWADI DIGIT NINE
114D0..114D9  ; Nd #  [10] TIRHUTA DIGIT ZERO..TIRHUTA DIGIT NINE
11650..11659  ; Nd #  [10] MODI DIGIT ZERO..MODI DIGIT NINE
116C0..116C9  ; Nd #  [10] TAKRI DIGIT ZERO..TAKRI DIGIT NINE
11730..11739  ; Nd #  [10] AHOM DIGIT ZERO..AHOM DIGIT NINE
118E0..118E9  ; Nd #  [10] WARANG CITI DIGIT ZERO..WARANG CITI DIGIT NINE
16A60..16A69  ; Nd #  [10] MRO DIGIT ZERO..MRO DIGIT NINE
16B50..16B59  ; Nd #  [10] PAHAWH HMONG DIGIT ZERO..PAHAWH HMONG DIGIT NINE
1D7CE..1D7FF  ; Nd #  [50] MATHEMATICAL BOLD DIGIT ZERO..MATHEMATICAL MONOSPACE DIGIT NINE
```

**Comment by DaniilVeriga** [comment]
@t-nelis, thank you very much for the confirmation that it helped you.

As well, thank you for the additional information. Yes, it looks like it is not something we would start working on right away. Though, if you (or anybody else) need it at some point, please raise your vote.
