### ISSUE TITLE
{0} doesn't work in a Template for an operator

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1064]
### Expected

Output 7.

### Actual

Crashes

### Steps To Reproduce
[Live Bridge](http://live.bridge.net/#c885c2e988e67a4557da)
```csharp
/// <summary>
/// Creates a simple class
/// </summary>
public class App
{
    public int c ()
    {
        return 7;
    }
    
    [Template("{0}.c()")]
    public static extern explicit operator int (App value);
    // Use the [Ready] attribute to automaically
    // run this method when the page is ready.
    [Ready]
    public static void Main()
    {
        var v = (int)(new App());
    }
}
```

**Comment by DaniilVeriga** [comment]
@michaelcheers, thank you for the report!

The cast operator means into something like `value.Cast(typeof(int))`. And `{0}` is indeed `Bridge.Int`.

To reference `value` you can use two approaches:
 * `[Template("{value}.c()")]`

or

* `[Template("{this}.c()")]`
