### ISSUE TITLE
Support for C# Random class

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#1080]
[MSDN Random](// https://msdn.microsoft.com/en-us/library/system.random(v=vs.110).aspx)

### Steps To Reproduce

```csharp
public class App
{
    [Ready]
    public static void Main()
    {
        Random r = new Random();

        Console.WriteLine(r.Next(10));
        Console.WriteLine(r.Next(10));
        Console.WriteLine(r.Next(10));

        Console.WriteLine(r.Next(5, 10));
        Console.WriteLine(r.Next(5, 10));
        Console.WriteLine(r.Next(5, 10));

        Console.WriteLine(r.NextDouble());
        Console.WriteLine(r.NextDouble());
        Console.WriteLine(r.NextDouble());

        byte[] buffer = new byte[5];

        r.NextBytes(buffer);
        Console.WriteLine(string.Join(",", buffer));

        r.NextBytes(buffer);
        Console.WriteLine(string.Join(",", buffer));
    }
}
```

**Comment by michaelcheers** [comment]
@geoffreymcgill 
I've made a pull request for this: [Pull](https://github.com/bridgedotnet/Bridge/pull/1118)

**Comment by LeonidVeriga** [comment]
Implementation details:

What we did is:
 - Take **.Net** `Random` class;
 - Transpile it using **Bridge.NET**.

Basically, there are four files:
- [MS Random C# source file](http://referencesource.microsoft.com/#mscorlib/system/random.cs), formatted just a little [Random.cs](https://github.com/bridgedotnet/Bridge/blob/Random/Transpiled/System/Random.cs) 
- [Javascript file](https://github.com/bridgedotnet/Bridge/blob/Random/Bridge/Resources/random.js) generated by **Bridge.NET** from [Random.cs](https://github.com/bridgedotnet/Bridge/blob/Random/Transpiled/System/Random.cs) -
  just 141 lines of code, 100% fits the .Net `Random` class functionality
- **Bridge** [Random.cs](https://github.com/bridgedotnet/Bridge/blob/Random/Bridge/System/Random.cs) file with `[External]` attribute applied, some methods have `[Template]` to control their overrides
- [Tests](https://github.com/bridgedotnet/Bridge/blob/Random/Tests/Batch1/RandomTests.cs) taken from [MS corefx tests](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/tests/System/Random.cs) slightly formatted to have text description in assertions.
