### ISSUE TITLE
TimeSpan millisecond format unsupported

### ISSUE THREAD

**Issue by strygo** [bridgedotnet/Bridge#1081]
### Expected
```
00:00.000
```

"f" is unsupported as a formatter. Notably, this is handled for DateTime, but not TimeSpan. Also, escaped characters are not emitted in .NET whereas are here.

[MSDN The"f" Custom Format Specifier](https://msdn.microsoft.com/en-us/library/ee372287(v=vs.110).aspx#fSpecifier)
### Actual
```
00\:00\.fff
```
### Steps To Reproduce

[Deck](http://deck.net/a7ad73a38ccb4b897fa246b3698228f8)

``` csharp
public class App
{
    [Ready]
    public static void Main()
    {
        var s = new TimeSpan(0).ToString(@"mm\:ss\.fff");

        Console.WriteLine(s);
    }
}
```

**Comment by geoffreymcgill** [comment]
Thanks for the report. Marking this as **up-for-grabs** as we're currently bogged down with other priorities.
