### ISSUE TITLE
SharedBridge Template not working as expected

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#1082]
Related to forum thread http://forums.bridge.net/forum/community/help/1759

**Comment by geoffreymcgill** [comment]
Should also follow up with the following forum thread once the template is working as expected:

http://forums.bridge.net/forum/community/help/1796-creating-typescript-poco-definitions

**Comment by DaniilVeriga** [comment]
Updated the SharedBridge template to the latest public Bridge release - 1.12.1.
Added a Bridge output JavaScript folder and a sample .html file as request in the [forum thread](http://forums.bridge.net/forum/community/help/1759).

The SharedBridge template appears to be working now.

Posted follow-ups in the forum threads and waiting any feedback. In no feedback over time, we could close the issue.

**Comment by geoffreymcgill** [comment]
The [SharedBridge](https://github.com/bridgedotnet/Demos/tree/master/Template/SharedBridge) project has been updated to Bridge 15.7.0.
