### ISSUE TITLE
Bridge does not build on mono in Release configuration

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#1108]
Bridge project (main project) does not build on mono when trying to build in Release Mode.

It breaks when the target `BuildPackage` is attempted, and fails by trying to reference assembly `$LIBDIR/mono/xbuild/12.0/bin/Microsoft.Build.Tasks.v4.0.dll`.

The correct should be either:
`$LIBDIR/mono/4.0/Microsoft.Build.Tasks.v4.0.dll`
or
`$LIBDIR/mono/xbuild/12.0/bin/Microsoft.Build.Tasks.v12.0.dll`.

**Comment by LeonidVeriga** [comment]
Fixed in **15.0** by #1719
