### ISSUE TITLE
Dynamic Propery Templates don't work

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1109]
[Dynamic Templates](http://live.bridge.net/#bc35aaf64c417d54840d)

```csharp
/// <summary>
/// Creates a simple class
/// </summary>
public static class App
{
    public static extern dynamic gamedata
        {
            [Template("gamedata")]
            get;
        }
    // Use the [Ready] attribute to automaically
    // run this method when the page is ready.
    [Ready]
    public static void Main()
    {
        Console.Log(gamedata);
    }
}
```
gives error.
Also, in Visual Studio this compiles successfully but when I try to use the object.
eg.gamedata.money
it compiles as gamedataBridge.get(LiveApp.App).money

**Comment by DaniilVeriga** [comment]
Thank you to the report! Though, compilation of the live test case fails for me with

> Cannot compile this dynamic invocation because there are two or more method overloads with the same parameter count. To work around this limitation, assign the dynamic value to a non-dynamic variable before use or call a method with different parameter count

The same happens for me if compile the test case locally in VS.

**Comment by michaelcheers** [comment]
@DaniilVeriga In Visual Studio, this doesn't fail but for me in Bridge Live it does.
Is it supposed to fail?

**Comment by DaniilVeriga** [comment]
I think [the initial test case](http://live.bridge.net/#bc35aaf64c417d54840d) is supposed to fail according to the throwing Exception. I am not sure why it doesn't fail in VS on your side. Please clarify which Bridge version do you use locally?

As for [the second test case](http://live.bridge.net/#8284323f3db158f84ebd), it produces something wrong:
`var val = gamedataBridge.get(Demo.App).gamedata;`

We'll investigate.

**Comment by michaelcheers** [comment]
@DaniilVeriga,  On my VS, it didn't throw an exception (maybe I've got an old version).
Anyway on mine, I just changed it to a function and it worked fine.

**Comment by LeonidVeriga** [comment]
Hi @michaelcheers,

We fixed the issue - it's an ideal case: nice catch and easy fix!
Thank you for reporting this test case.
