### ISSUE TITLE
Allow disabling naming case conversion on a per type base 

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#1112]
http://forums.bridge.net/forum/general/feature-requests/1927
### Expected

```
[ObjectLiteral(ChangeCase = false)]
​public class ServiceResponse
{
    public string Name { get; set; }
    public string Hobby { get; set; }
}
```
### Actual

```
[ObjectLiteral]
​public class ServiceResponse
{
    [Name(false)]
    public string Name { get; set; }

​    [Name(false)]
    public string Hobby { get; set; }
}
```

**Comment by DaniilVeriga** [comment]
We'll review if it is possible to implement in 1.13.

**Comment by geoffreymcgill** [comment]
There's a chance we will revisit this feature in the future, but for now, this will not be implemented.

**Comment by geoffreymcgill** [comment]
This scenario is now supported by using the `[Convention]` attribute.

https://github.com/bridgedotnet/Bridge/wiki/attribute-reference#convention
