### ISSUE TITLE
Drop IE8 support

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#1115]
Basing on the discussion within #1050 and the [poll in Twitter](https://twitter.com/bridgedotnet/status/710717351176617984) decided to drop IE8 support.

Any IE8 hacks are going to be removed. Drop of IE8 support is going to unleash improvements to be done in Bridge getting rid of IE8 hacks and to release resources for new features development.

1.11 is a final IE8 compatible version.

**Comment by LeonidVeriga** [comment]
Cross-browser tests passed https://travis-ci.org/bridgedotnet/Testing/builds/120871022
