### ISSUE TITLE
Make more elegant way of changing types than as.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1124]
[As Example](http://live.bridge.net/#9e2dd29d8482a80595e8af0498988430)
[Cast Example](http://live.bridge.net/#287e1ae36a1d61638809ac9295ebe2f9)
```csharp
object value = new App ();
App val = value as App;
```
translates as 
```javascript
var value = new App();
var val = Bridge.as(value, App);
```

```csharp
object value = new App ();
App val = (App)value;
```
translates as 
```javascript
var value = new App();
var val = Bridge.cast(value, App);
```
which is OK and I understand that getting the original functionality of as and cast is important.
But it would be cool to have some way of not using Bridge.as(value, App) or Bridge.cast(value, App) and instead just value...
anyway I made a function which was kind of that.

```csharp
[Template("{0}")]
public static extern T ChangeType<T> (object value);
```

**Comment by DaniilVeriga** [comment]
I think you are looking for:
`object value = new App();
App val = value.As<App>();`

I would also recommend the [Type Casting](http://bridge.net/kb/type-casting) Knowledge Base article.
