### ISSUE TITLE
Commandline builder: search for project file in current directory by default

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#1132]
Currently `Bridge.Builder.exe` requires an assembly or project file to be specified in the command line arguments in order to build the project.

Both `xbuild` and `msbuild`, if run from a project's root (or solution, in their case!) with no parameters defaults to building the project in the current configuration -- if and only if there's only one .sln or .csproj file in the directory.

If there are two or more eligible files (a .sln and a .csproj, or two .sln or two .csproj), it does not do anything with the message:
```
MSBUILD: error MSBUILD0005: Please specify the project or solution file to build, as more than one solution or project file was found in the current directory
```

Bridge commandline builder could have the same behavior -- but supporting only .csproj files -- in such a manner that having an event with just `build/Bridge.Builder.exe` would suffice, as it will load the current project on the current configuration (it would have to support reading `*.csproj.user` files for current configuration, or maybe reading environment variables if VS makes them available on events/tasks calls).

**Comment by LeonidVeriga** [comment]
The feature is implemented thanks to @Phrohdoh.
