### ISSUE TITLE
Script.ToDynamic() [Template] should not emit anything

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#114]
// cs
    var msg = Script.ToDynamic().data.title;

    // js
    var msg = data.title;

**Comment by vladsch** [comment]
what we should do with such code
`var d = Script.ToDynamic();`

**Comment by vladsch** [comment]
ToDynamic is emitted via Template, Template doesn't support various cases of emitting
If we skip emiting for ToDynamic then above code will be emitted as `var d = ;`

**Comment by geoffreymcgill** [comment]
> what we should do with such code
Throw Exception.
