### ISSUE TITLE
default(<Nullable>) should be null

### ISSUE THREAD

**Issue by HeavenMaster** [bridgedotnet/Bridge#1140]
### Expected

Null

### Actual

0

### Steps To Reproduce

http://live.bridge.net/#991592f4340578efe5bc9f9b0fcca5e7

**Comment by LeonidVeriga** [comment]
Hi @HeavenMaster,

Thank you for reporting this issue.

It appears it's fixed in the current `master` branch code. We could not find the exact commit that fixed the issue but, more important, added the test case to make sure the issue does not come up again.
