### ISSUE TITLE
Inconsistency in null / undefined / equals

### ISSUE THREAD

**Issue by heavenmaster** [bridgedotnet/Bridge#1175]
It was a very good and right that you are treating null and undefined as the same thing in C#. Now my code is more clear and "undefined-error free".  If we would like to find out specific value of our 'null' we have Script.IsDefined. However you need to make the final improvement. I made a live code repro to illustrate what I mean. I think the following scenario is widely error-prone and should be fixed in a coming release.

### Expected

varNull == varUndefined -> True
varNull == null -> True
varUndefined == null -> True

### Actual

varNull == varUndefined -> **False**
varNull == null -> True
varUndefined == null -> True

### Steps To Reproduce

I made a repro / test:
http://live.bridge.net/#f32de5c489a99a5b96c3d358672bd11c

**Comment by geoffreymcgill** [comment]
Thanks for the feedback and code sample demonstrating the issue. We are investigating.

**Comment by geoffreymcgill** [comment]
Hi @danieldegtyarev: Any feedback on the recent changes to null checking since 12.1 or the recent 1.13 releases? Working well for you now?

**Comment by danieldegtyarev** [comment]
Yes, looks good, thank you!
