### ISSUE TITLE
DateTime.MinValue cannot be converted to UTC in DST time zones

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#1181]
### Expected

```js
480
```
### Actual

```js
0 // in DST time zone (tested with Eastern Standard TimeZone): 0
480 // in non DST time zone
```

### Steps To Reproduce

http://dev.deck.net/6cad8e2f400c1889be8c9f79bc69f67a

```c#
public class App
{
    public static void Main()
    {
        var start = DateTime.MinValue;
        var end = start.AddHours(8);
        var difference = (end - start).TotalMinutes; 

        Console.WriteLine(difference);
    }
}
```

## See Also

* #869 
* http://forums.bridge.net/forum/bridge-net-pro/bugs/1457-fixed-869-1-12-subtracting-datetimes-does-not-handle-dst-in-the-same-manner-as-net?p=2020#post2020

**Comment by fabriciomurta** [comment]
A full test over all time zones have been undegone and all looks good, so the fix for this will be available next Bridge release!

It came last in the batch of datetime fixes, yet it works fine to all (windows 10, at least) supported time zones!
