### ISSUE TITLE
Namespace attribute

### ISSUE THREAD

**Issue by MangelMaxime** [bridgedotnet/Bridge#1188]
Hello guys, I'm not sure if it's a bug or not but the attribute `[Namespace(string)]` seems to do nothing.

Here is my code : 

```csharp
    [External]
    [Namespace("photonui")]
    [Name("Base")]
    public class Base
    {
        public extern void Destroy();

        public extern void RegisterCallback(string id, string wEvent, Action callback, object thisArg);

        public extern void RemoveCallback(string id);
    }
```

I am expecting the ouput to be : `photonui.Base` but it's actually `Base`.

What is the goal of the Namespace attribute ?

**Comment by DaniilVeriga** [comment]
Hi @MangelMaxime,

That is right, a `Namespace` attribute is for the class' namespace, but a `Name` attribute overrides it, because it specifies a full name including a namespace (if exists).

So, you can either use
```
[External]
[Name("photonui.Base")]
public class Base
```
or
```
[External]
[Namespace("photonui")]
public class Base
```

**Comment by DaniilVeriga** [comment]
I've revised the [Name](http://bridge.net/kb/attribute-reference/#Name) and [Namespace](http://bridge.net/kb/attribute-reference/#Namespace) sections in the Attribute Reference knowledge base article, mentioning that the Name attributes takes precedence over the Namespace one.

**Comment by MangelMaxime** [comment]
@DaniilVeriga thanks for the answer.
And thanks for letting me know about the Attribute Reference page :)
