### ISSUE TITLE
Bridge.cast() should support casting of plain JavaScript objects to Bridge objects to support AJAX JSON API.

### ISSUE THREAD

**Issue by Blackhex** [bridgedotnet/Bridge#1192]
### Expected
- No run-time error.
- `obj` contains property `Id` instead of `id`

I see two issues with this sample:
- Dynamic objects should respect `preserveMemberCase` configuration property. Sorry to report this together with the other issue but is minor for me and a found it while reproducing the other.
- First of all: I used dynamic object to demonstrate the issue but the actual problem I have is when I receive some data from AJAX JSON API using jQuery in JavaScript code and using the dynamic is just a way how to create plain JavaScript object. Now the issue: Does `Bridge.cast()` method support plain JavaScript object casting? If not it is an issue together with the new long support in 1.12 because if you use `[ObjectLiteral]` for `Foo`'s declaration, you end up with issue that you cannot (for example) compare value of long attribute of `Foo` class with value of long attribute of `Bar` class when commented out code in the demo is active.

BTW Is there an option to disable new long support?
### Actual

```
bridge.js:356 Uncaught Unable to cast type Object to type Foo
```

```
Main: function () {
  var obj = { id: 1 };
  var foo = Bridge.cast(obj, Foo);
}
```
### Steps To Reproduce

``` csharp
public class App {

  //[ObjectLiteral]
  public class Foo {

    //[Name("Id")]
    public long Id;
  }

  public class Bar {

    public long Id;
  }

  public static void Main() {
      var obj = new { Id = 1 };
      var foo = obj.Cast<Foo>();
  }
}
```

```
{
    "outputBy": "Project",
    "fileNameCasing": "CamelCase",
    "autoPropertyToField": false,
    "preserveMemberCase": true
}
```

**Comment by vladsch** [comment]
About "preserveMemberCase", i do not recommend to use that option. We can remove support of that option
https://github.com/bridgedotnet/Bridge/issues/819#issuecomment-181498703

About Cast, if you want just interprete variable as different type then use "As" method 
`obj.As<Foo>()`. It is only interpriting in C#. Javascript object will not be changed/updated, so you should use `As` only if ensure that object is valid for that type. For example, your `obj` has Id Int32 field. If you call `obj.As<Foo>()` then Id will not changed and will be Int32 still but Foo.Id should be long. So, can be errors in Javascript

I am ot sure that I correctly understood your note about comparing Foo.Id and Bar.Id
Here is live sample and it works fine
http://live.bridge.net/#d4afcf1db2f8a228e1efaaaea78ea5db

>BTW Is there an option to disable new long support?
No, why do you use long if no need that functionality?

**Comment by Blackhex** [comment]
I know, I'm just asking if it woudn't be better if `Bridge.Cast()` would try to make a deep copy of a passed plain JavaScript object to target class instance while converting number fields to `Bridge.Long` fields if defined so in the target class? If I use `Bridge.As()` on object with long field then the following produces run time error: http://live.bridge.net/#5831a2cc9eb5c3ec3cb8e4da5bc0ccfa because foo is still plain JavaScript object without `Bridge.Long` field. The same code worked in 1.11 without the long support. That's why disabling long support would be another solution to the problem. Now I have to implement deep copy constructors for every received API object which converts plain JavaScript object to Bridge.define() generated object (which is lot of work) or implement such automatic conversion of plain JavaScript objects to Bridge objects in JavaScript code.

**Comment by DaniilVeriga** [comment]
The `long` type in Bridge 1.11 had the inconsistent and erratic behavior. You are lucky that it somehow worked for you:) Though, it was a time bomb.

I'd like to clarify on the `.As<>` feature. It cannot and is not meant to covert a plain `new { Id = 1 }` object to a Foo class instance.

A helper utility method to parse a Foo class instance from a plain object can be a solution:

[Full Live Sample](http://live.bridge.net/#79d1ce7e42e7cb8aa80648517086fef2)
```csharp
public class Foo
{
    public long Id;

    public static Foo Parse(object obj)
    {
        var f = new Foo();
        var idObj = obj["Id"];

        if (idObj != null && idObj is int)
        {
            f.Id = idObj.As<int>();
        }

        idObj = obj["id"];

        if (idObj != null && idObj is int)
        {
            f.Id = idObj.As<int>();
        }

        return f;
    }
}
```

**Comment by geoffreymcgill** [comment]
The `preserveMemberCase` config is being removed in Bridge 16.0.

Please see Issues #2476 and #2477 for further details.
