### ISSUE TITLE
Incorporate JsDoc product info into generated JavaScript

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#1193]
- `Bridge.assembly` call to have JsDoc comment with description, version, author, copyright and compiler version. This would be the documentation for the assembly:

  ```js
  /**
     * [AssemblyDescription]
     * @version [ProductVersion]
     * @author [AssemblyCompany]
     * @copyright [AssemblyCopyright]
     * @compiler Bridge.NET 15.3.0
     */
  Bridge.assembly(...
);
```
- The source of the `[ProductVersion]` is [FileVersionInfo.ProductVersion](https://msdn.microsoft.com/en-us/library/system.diagnostics.fileversioninfo.productversion(v=vs.110).aspx) that is basically comes from `[AssemblyVersion]`, `[AssemblyFileVersion]` or `[AssemblyInformationalVersion]`;
- If the Attributes do not include a value, that line item is skipped in the comment. For example, if the `[AssemblyDescription]` and `[AssemblyCopyright]` were empty:

  ```js
/**
     * @version 1.2.3.4
     * @author [AssemblyCompany]
     * @compiler Bridge.NET 15.3.0
     */
```
For example, the following sample should render the `InitPosition.Top` at the top of the file [Deck](http://deck.net/7d9735eafd5ea30b9c38d3c1eef0554e);

- New `[Template]` modifier `:version`. This is to ask Bridge Compiler to incorporate string representing a version either of current Assembly or Compiler. A parameter used with modifier `version` can be `0` (requesting Assembly version) or `1` (for Compiler version):

  ```cs
 [Template("{type:version}")]
 public static extern string GetVersion(int type);
```
- New `Bridge.Utils.AssemblyVersionMarker` class to get version's string representation either of the current Assembly or Compiler. **Bridge Compiler** will replace the method call with a version specified by method parameter:

  ```cs
var v1 = AssemblyVersionMarker.GetVersion(VersionType.CurrentAssembly);
var v2 = AssemblyVersionMarker.GetVersion(); // Default is VersionType.CurrentAssembl
var v3 = AssemblyVersionMarker.GetVersion(VersionType.Compiler);
```
  Translated into:
  ```js
var v1 = "1.2.3.4";
var v2 = "1.2.3.4";
var v3 = "15.3.0";
```
- Added XmlDoc descriptions for `Assembly.cs` file.

### Sample
[Deck](http://deck.net/492cf881ea1d91dc5bf7ecc0e439eee2)
```cs
using Bridge;
using Bridge.Utils;
using System;
using System.Reflection;

public class Program
{
    public static void Main()
    {
        // Gets assembly version through Bridge.Utils.AssemblyVersionMarker
        System.Console.WriteLine(AssemblyVersionMarker.GetVersion());
        // Gets assembly version through a user method using version modifier
        System.Console.WriteLine(GetVersion(AssemblyVersionMarker.VersionType.CurrentAssembly));

        // Gets Compiler version through Bridge.Utils.AssemblyVersionMarker
        System.Console.WriteLine(AssemblyVersionMarker.GetVersion(AssemblyVersionMarker.VersionType.Compiler));
        // Gets Compiler version through a user method using version modifier
        System.Console.WriteLine(GetVersion(AssemblyVersionMarker.VersionType.Compiler));
    }

    [Template("{type:version}")]
    public static extern string GetVersion(AssemblyVersionMarker.VersionType type);
}
```

Generates the following output:
```js
/**
 * A sample App created with Deck.NET
 * @version 1.2.3.4
 * @author Object.NET, Inc.
 * @compiler Bridge.NET 15.3.0
 */
Bridge.assembly("Demo", function ($asm, globals) {
     "use strict";

    Bridge.define("Program", {
        $main: function () {
            // Gets assembly version through Bridge.Utils.AssemblyVersionMarker
            Bridge.Console.log("1.2.3.4");
            // Gets assembly version through a user method using version modifier
            Bridge.Console.log("1.2.3.4");

            // Gets Compiler version through Bridge.Utils.AssemblyVersionMarker
            Bridge.Console.log("15.3.0");
            // Gets Compiler version through a user method using version modifier
            Bridge.Console.log("15.3.0");
        }
    });
});
```

**Comment by LeonidVeriga** [comment]
Assembly creation call will include assembly version (value of `[AssemblyVersion]`) and clr version (in this case, Bridge compiler version):
```js
Bridge.assembly({ name: "Bridge.ClientTestHelper", version: "1.2.3.4", clr: "15.2.0" }
```

C# call `System.Reflection.Assembly.FullName` will include assembly version as well.
Current result value:
```
"Bridge.ClientTestHelper"
```
Proposed:
```
"Bridge.ClientTestHelper, Version=1.2.3.4"
```

We can also implement [Assembly.GetName](https://msdn.microsoft.com/en-us/library/y3bk16ya(v=vs.110).aspx):
```cs
public virtual AssemblyName GetName()
``` 
To return [AssemblyName](https://msdn.microsoft.com/en-us/library/system.reflection.assemblyname%28v=vs.110%29.aspx) containing just these properties:
```cs
public string FullName;
public string Name;
public Version Version;
```

To get the clr version (Bridge Compiler version) an assembly was compiled with, we can implement [Assembly.ImageRuntimeVersion Property](https://msdn.microsoft.com/en-us/library/system.reflection.assembly.imageruntimeversion(v=vs.110).aspx):
> Gets a string representing the version of the common language runtime (CLR) saved in the file containing the manifest. By default, ImageRuntimeVersion is set to the version of the CLR used to build the assembly. 

```cs
public virtual string ImageRuntimeVersion { get; }
```

**Comment by geoffreymcgill** [comment]
How about a dedicated `compiler` config instead of the `clr`?

**Example**

```js
Bridge.assembly({ 
    name: "Bridge.ClientTestHelper", 
    version: "1.2.3.4", 
    compiler: {
        name: "Bridge.NET",
        version: "15.2.0",
    }
}, ...

**Comment by geoffreymcgill** [comment]
I guess it's unlikely `compiler.name` would ever be useful.

**Comment by LeonidVeriga** [comment]
Some changes required
