### ISSUE TITLE
Adding handler to event in generic class silently fails

### ISSUE THREAD

**Issue by d-p-y** [bridgedotnet/Bridge#1199]
### Expected
Adding handlers to event exposed by generic class should register that handler within event. 

### Actual
Event is not registered - it silently fails without any Javascript exception. 
Problem lays with naming after translation to JS. Workaround is to make event name follow camel case convention. Pull request will follow.

[Live Bridge](http://live.bridge.net/#6f8e544542dfd7797698a27245fac462)

### Steps To Reproduce

```csharp
public class IssueEvents
    {
        public delegate string SomeDel();

        class NotWorking<T>
        {
            public event SomeDel IsNotWorking;
            public string Validate() {
                return IsNotWorking == null ? "no subscribers": IsNotWorking();
            }
        }
        
        [Ready]
        public static void Main()
        {
            var wrong = new NotWorking<int>();
            wrong.IsNotWorking += () => "somevalue";
            Window.Alert(wrong.Validate()); // in browser gives "no subscribers" instead of "somevalue"
        }
    }
```

**Comment by LeonidVeriga** [comment]
Hi @d-p-y,

Thanks for a nice catch and signing the CLA)
