### ISSUE TITLE
$_ function database doesn't work on init.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1203]
[Try Out](http://live.bridge.net/#014a495ad32a2add3c1610cd58a71682)

This should work:
```csharp
	static class Program
	{
		[Init]
		public static void Main ()
		{
			Program.ForIn("v", new {
				v = 5
			}, v => 
			{
				Global.Alert(v);
			});
		}
		[Template("for (var {left:raw} in {right})\n{body}({left:raw})")]
		public static extern void ForIn (string left, object right, Action<string> body);
	}
```

**Comment by geoffreymcgill** [comment]
We might be able to change the position of the `Bridge.init` call so that it renders after the lifted function declarations. We will investigate. 

Thanks for letting us know about this defect.
