### ISSUE TITLE
Give Exception with C# 6.0 fields

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1211]
It should throw an exception with C# 6.0 fields because it messes up the whole program.
```csharp
/// <summary>
/// Creates a simple class
/// </summary>
public class App
{
    public static int v => 7;
    public static int g
    {
        get;set;
    }
    public static int r
    {
        get;set;
    }
    
    // Use the [Ready] attribute to automaically
    // run this method when the page is ready.
    [Ready]
    public static void Main()
    {
    }
}
```

**Comment by vladsch** [comment]
At this moment, you have to use C# 5 only in Bridge projects (use C# 5 as default language in csproj)
We are going to include C# 6 support in 1.13 release

**Comment by geoffreymcgill** [comment]
C#6 functionality is in the works, so there will be no need to implement this Feature request.
