### ISSUE TITLE
Doubles (using float.MaxValue give you different values) in .net and bridge.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1224]
### Expected

```
1.70141173319264E+38
```

### Actual

```
1.701411735e+38
```

### Steps To Reproduce

```c#
public class App
{
    public static void Main()
    {
        double value = float.MaxValue;
        Console.WriteLine(value / 2);
    }
}
```

http://deck.net/1e65012f86170b974d3b3d5a74319c9f
https://dotnetfiddle.net/rGMdam

**Comment by LeonidVeriga** [comment]
This is the same thing as #1225.

Both `double` and `float` have JavaScript `number` underlying type.

However, Bridge `decimal` has its own implementation and works as .Net `decimal`

**Comment by DaniilVeriga** [comment]
There are other details about the problem stated in [this comment](https://github.com/bridgedotnet/Bridge/issues/1184#issuecomment-214629020) of a related Issue.

**Comment by geoffreymcgill** [comment]
Bridge is now matches the functionality of native .NET.
