### ISSUE TITLE
Floats in Bridge have more precision than in .Net

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1225]
### Expected

```
1.701412E+38
```

### Actual

```
1.701411735e+38
```

### Steps To Reproduce

```c#
public class App
{
    public static void Main()
    {   
        float maxFloat = float.MaxValue;
        Console.WriteLine(maxFloat  / 2);
    }
}
```

**Comment by LeonidVeriga** [comment]
Hi @michaelcheers,

Yes, the underlying type for .Net `float` is JavaScript's `number`:
```
namespace System
{
    [Constructor("Number")]
    [External]
    [Name("Bridge.Single")]
    public struct Single : IComparable, IBridgeClass, IComparable<Single>, IEquatable<Single>, IFormattable
    {
    }
}
```

At the moment we do not consider changing this implementation by introducing a wrapper type to reduce precision and introducing additonal complexity.

**Comment by DaniilVeriga** [comment]
There are other details about the problem stated in [this comment](https://github.com/bridgedotnet/Bridge/issues/1184#issuecomment-214629020) of a related Issue.

**Comment by geoffreymcgill** [comment]
At some point this has been fixed. The test sample now returns the expected results.

http://deck.net/8c32f5a4e1585804456002f973793579

Please let us know if there's still a problem and we will re-open the issue.
