### ISSUE TITLE
Math.Sinh, Math.Cosh and Math.Sinh unsupported

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1226]
| MSDN | MDN |
| --------|-------|
| [Math.Sinh](https://msdn.microsoft.com/en-us/library/system.math.sinh(v=vs.110).aspx) |[sinh](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Math/sinh) |
| [Math.Cosh](https://msdn.microsoft.com/en-us/library/system.math.cosh(v=vs.110).aspx) |[cosh](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/cosh) |
| [Math.Tanh](https://msdn.microsoft.com/en-us/library/system.math.tanh(v=vs.110).aspx) | [tanh](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/tanh)|

**Comment by geoffreymcgill** [comment]
Thanks for requesting this feature. 

For now, I'm marking as [up-for-grabs](https://github.com/bridgedotnet/Bridge/labels/up-for-grabs). Hopefully someone from the community can take this one on and implement a JavaScript equivalent.

**Comment by michaelcheers** [comment]
[Math.sinh](https://msdn.microsoft.com/en-us/library/mt179296(v=vs.94).aspx), [Math.cosh](https://msdn.microsoft.com/en-us/library/mt179292(v=vs.94).aspx) and [Math.tanh](https://msdn.microsoft.com/en-us/library/mt179294(v=vs.94).aspx) are supported by javascript and have simple formulas to perform each.

Math.sinh: (exp(x) - exp(-x))/2
Math.cosh: (exp(x) + exp(-x))/2
Math.tanh: (exp(x) - exp(-x))/(exp(x) + exp(-x))

**Comment by michaelcheers** [comment]
@geoffreymcgill, Pull Request: #1315.

**Comment by LeonidVeriga** [comment]
Implemented with IE support
