### ISSUE TITLE
Use Object initializer and/or Object.defineProperty() for class properties

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1229]

**Comment by vladsch** [comment]
Please provide more details

**Comment by LeonidVeriga** [comment]
Hi @michaelcheers,

Can you please provide a code sample in C# as an input and supposed result in JavaScript as an output.

**Comment by michaelcheers** [comment]
I'm thinking we can use Object.defineProperty for properties.
So, I'm thinking
```csharp
/// <summary>
/// Creates a simple class
/// </summary>
public class App
{
    public static int v
    {
        get
        {
            return 7;
        }
        set
        {
            Global.Alert(value.ToString());
        }
    }
    // Use the [Ready] attribute to automaically
    // run this method when the page is ready.
    [Ready]
    public static void Main()
    {
        Console.WriteLine(v);
    }
}
```
would compile to: 
```javascript
(function (globals) {
    "use strict";

    /** @namespace Demo */
    
    /**
     * Creates a simple class
     *
     * @public
     * @class Demo.App
     */
    Bridge.define('Demo.App', {
        statics: {
            config: {
                init: function () {
                    Bridge.ready(this.main);
                }
            },
properties:{
            v: 
             {
            get: function () {
                return 7;
            },
            set: function (value) {
                Bridge.global.alert(value.toString());
            }}},
            main: function () {
             console.log(v);
            }
        }
    });
    
    Bridge.init();
})(this);

```
then in bridge.js it would use Object.defineProperty on the properties.
[For Reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/__defineGetter__)
[Js Fiddle Example](https://jsfiddle.net/L5ggz6mx/)

**Comment by DaniilVeriga** [comment]
Thank you, @michaelcheers.

An idea of using `Object.defineProperty()` for class properties has already crossed our mind before and we should be able to implement it in one of next releases.

We didn't have a dedicated issue for that, so, I will leave this issue for that.

MDN says that `__defineGetter__` and `__defineSetter__` are deprecated in favor of Object initializer and `Object.defineProperty()`. So, would you mind renaming the Issue title to "Use Object initializer and/or Object.defineProperty() for class properties"?

**Comment by TriEdgeAI** [comment]
Using Object.defineProperty() instead of get/set methods would also fix #1291 as a side-effect. :)
Just tried running this code in the browser:

```javascript
var obj = new Object();

Object.defineProperty(obj, "Test", {
	get: function()
	{
		return 1;
	},
	set: function()
	{
		
	}
});

alert(obj.Test = 2);
```

And the output is indeed `2` just like it would be in C#.

**Comment by geoffreymcgill** [comment]
See also #2289

**Comment by ProductiveRage** [comment]
I suspect that this will require changes to my [ProductiveRage.Immutable](https://github.com/ProductiveRage/Bridge.Immutable) library - if you would give me a mention when this change is ready for testing in the trunk, it would be much appreciated! :)

**Comment by geoffreymcgill** [comment]
This is likely to be implemented in Bridge 16.0. We're still working out the details and have yet to actually do any work on this feature, but our plan is to get started on this right away.

Bridge 16.0 will be first released as a **Beta**, so there will be plenty of time to adjust.

**Comment by LeonidVeriga** [comment]
@ProductiveRage, this is in **master** now. Having any questions or suggestions on the implementation, please let us know.

**Comment by geoffreymcgill** [comment]
@ProductiveRage – The `defineProperty` revisions have been committed to **master** branch, but please do not jump in and start updating your libraries. There are more changes coming and it would be best to wait until we have everything in place. I will let you know when Bridge 16 is stable enough for you to start.
