### ISSUE TITLE
Unable to reset CSS Style properties

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#123]
This does not work on Bridge:
`Document.GetElementById('somethingValid').Style.Visibility = null`

On JavaScript this would just reset the element's CSS (to be inherited from container).

Instead, one option is to:
`Document.GetElementById('somethingValid').Style.Visibility = Visibility.Inherit`

But this wouldn't help on other CSS entities not having a 'inherit' option. JavaScript allows to set null to a style definition like that.

**Comment by vladsch** [comment]
There is `RemoveProperty` method for `Style`
