### ISSUE TITLE
Constructors with "params" behaves incorrectly

### ISSUE THREAD

**Issue by desunit** [bridgedotnet/Bridge#1232]
### Expected

Constructor with "params" should store it as arrays.

### Actual

If constructor invokes another constructor then instead of **array** it passes **array of arrays**. 

### Steps To Reproduce

[Live Url](http://live.bridge.net/#97d9037a54e2789dbaf7a4de14ba61fb)

```csharp
    public class Test
    {
        public string [] A {get; set; }
        
        public Test(int a, params string [] str)
        {
            A = str;
        }
        
        public Test(params string [] str)
         : this(1, str)
        {
        }
    }
    
    [Ready]
    public static void Main()
    {
        var t = new Test("a", "b");
        // displays: [ ["a", "b"] ] instead of ["a", "b"]
        Console.WriteLine(t.A);  
    }
```

**UPD**: [a workaround](http://live.bridge.net/#69012e9083dee211bfa8a13e0fb3be28)

**Comment by geoffreymcgill** [comment]
Thanks for reporting this defect. Should be an easy fix. 

Also related to the following forum thread:

http://forums.bridge.net/forum/bridge-net-pro/bugs/2130-params-incorrectly-handled

**Comment by desunit** [comment]
@geoffreymcgill yeah, it was my post - just helped to input it.
