### ISSUE TITLE
Logging default None option and new settings: timeStamps, maxSize, folder, fileName

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#1237]
### Expected

No `bridge.log` file created and updated by default.

Options to control folder, fileName, whether to print timestamp, max file size

### Actual

The log file created with severity level `Info` (`bridge.json` option 'loggerLevel').

### Solution

Create `loggerLevel` option `None`, use it by default.

Separate `logging` section in `bridge.json`, for example:
```
  "logging": {
    "level": "None",
    "timeStamps": true,
    "maxSize": 1048576,
    "folder": "",
    "fileName" : "bridge.log"
  }
```
`"level"` : `"None|Error|Warning|Info|Trace"`, `None` by default
`"timeStamps"` : `false|true`, `true` by default
`"maxSize"` : `int`, `1Mb` by default
`"folder"` : `"a valid folder name"`, `current output folder` by default, can be relative (from project file location) or absolute
`"fileName"` : `"a valid file name"`, `bridge.log` by default

**Comment by geoffreymcgill** [comment]
Option value should be `None`.
