### ISSUE TITLE
Html Elements cannot have direct inheritance 

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#1238]
Related forum threads:

http://forums.bridge.net/forum/community/help/2153-html-elements-inheritance
http://forums.bridge.net/forum/community/help/2399-not-a-constructor-error
### Expected

Not sure. Ideally would work. Might have to mark Element classes as `sealed`. 
### Actual

Throws JavaScript error.

``` javascript
TypeError: Illegal constructor.
```
### Steps To Reproduce

``` csharp
public class App
{
    public static void Main()
    {
        var li = new Foo();
    }
}

public class Foo : LIElement { }
```

**Comment by vladsch** [comment]
Few useful links:
http://stackoverflow.com/questions/1489738/how-to-inherit-from-the-dom-element-class
http://www.html5rocks.com/en/tutorials/webcomponents/customelements/

**Comment by cassiot** [comment]
The second link shows exactly why I want to inherit from Dom elements.

I disagree that these elements should be sealed. Without inheritance, how can we create an element that is not a td inside a table tr. tr element will not identify any other element as a td. It must be a td and not a wrapper for a td. Am I right?

**Comment by geoffreymcgill** [comment]
Changing to a `question`. This isn't really a limitation or defect of Bridge. 

Maybe there's some way we could automatically handle this scenario, if someone mocks up the JavaScript required in the compiled output. 

Another option is to replicate the inheritance technique used to define **LIElement**, but that doesn't actually add properties to the client-side instances of the object.

https://github.com/bridgedotnet/Bridge/blob/master/Html5/Elements/LIElement.cs

Hope this helps.

**Comment by cassiot** [comment]
I don't know what is the best option. I know that using inheritance was the way I used to do it in Dart. Why avoid inheritance? Is it wrong?

Anyway, I'm just trying to make polymer work with Bridge because I don't want to use Dart anymore, even knowing that Dart has a solid polymer support.

**Comment by geoffreymcgill** [comment]
I don't think there is anything particularly wrong with using inheritance, but it just obviously will not work with the way the JavaScript is currently being emitted. 

If you can propose an option for what the compiled output should look like, then we should be able to offer some suggestions on how to achieve that syntax. There are several [Attributes](http://bridge.net/kb/attribute-reference/) that can be used to control the constructor syntax and rendering of the properties.

**Comment by cassiot** [comment]
I'm really new to Bridge and not that good in JS. I will left this task for you, but I think we can use vladsch second link as a reference and maybe see what is Dart output in these cases.

Don't get me wrong. I'm just anxious to make it work. I'm starting a new project, I don't like JS, JQuery, Angular.... Bridge seems to be what I think Microsoft should have done years ago. Thanks.

**Comment by DaniilVeriga** [comment]
Happy to hear that Bridge is helpful for you. Thank you for sharing!

As for HTML Elements inheritance, I think there is a related issue with `document.registerElement()` feature request - #389.

**Comment by geoffreymcgill** [comment]
All **HTML[Tag]Element** classes have been marked as `sealed`. These classes cannot be inherited. 

Please see Issue #2362 and Pull Request #2364.

**Comment by geoffreymcgill** [comment]
Please see *Support for Custom Elements* in Issue #2580.
