### ISSUE TITLE
Spanish Globalization unsupported

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1239]
[Dot Net Fiddle](https://dotnetfiddle.net/24G35x)
[Bridge Fiddle](http://live.bridge.net/#f98c5017db09ced83cf075e6aec7abb9)
### Expected

Show 1,3

### Actual

Shows "Uncaught Culture is not supported.
Parameter name: name
es-ES is an invalid culture identifier."

### Steps To Reproduce

```csharp
public class App
{
    [Ready]
    public static void Main()
    {
double v =1.3;
        var culture = new CultureInfo("es-ES");
        Console.WriteLine(v.ToString(culture));
    }
}
```

**Comment by vladsch** [comment]
Bridge supports all cultures
https://github.com/bridgedotnet/Bridge/tree/master/Bridge/Resources/Locales

But all of that cultures are not registered in live application
To register require locales in your application please use "locales" global option
http://bridge.net/kb/global-configuration/#locales

**Comment by DaniilVeriga** [comment]
The error messages "is not supported", "is an invalid culture identifier" are confusing. I guess it should be revised to something like "The culture is not attached". I see that Geoffrey has assigned the issue to himself. I assume he has the same thought to revise the message:)

**Comment by DaniilVeriga** [comment]
Raised a dedicated issue to improve the error message: #1288.
