### ISSUE TITLE
Empty source lines are not transcripted into Bridge non-min JavaScript

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#124]
The C# code:
```
namespace LineSkips
{
    public class Skippers
    {
        private static void Main()
        {
            var a = 1;
            // Empty line with comment

            // Above was an empty empty line
            var b = 2;
        }

    }
}
```

Results in the JavaScript:
```
Bridge.define('LineSkips.Skippers', {
    statics: {
        main: function () {
            var a = 1;
            // Empty line with comment
            // Above was an empty empty line
            var b = 2;
        }
    }
});
```

In some situations, the empty lines might be desired in order to separate different code portions. As bridge is now, generated JavaScript does not allow this to be (cleanly) done.

This probably is a side effect of the reviewed (second) fix on issue #63, commit bridgedotnet/Builder@4bc8eee8.

**Comment by geoffreymcgill** [comment]
+1. 

I'd like to see these empty lines maintained as well. Even multiple concurrent empty lines reproduced from the equivalent in C# would be nice to have.

**Comment by fabriciomurta** [comment]
Just reverting commit mentioned on the first post does not address the issue, so the problem might not be related nor side effect of issue #63.

**Comment by vladsch** [comment]
The problem that empty lines are not presented in AST (abstract syntax tree) which is built by NRefactory

**Comment by vladsch** [comment]
Implemented but empty lines are maintained inside methods only

**Comment by geoffreymcgill** [comment]
Very nice to see this implemented.
