### ISSUE TITLE
MarkElement is missing

### ISSUE THREAD

**Issue by Suchiman** [bridgedotnet/Bridge#1241]
### Expected
Getting IntelliSense when typing `MarkElement` that is `<mark>`

### Actual
IntelliSense beating the shit out of you for trying to type something that doesn't exists

### Steps To Reproduce
1. Type MarkElement.
2. Watch out for the IntelliSense paid bully.
3. Show them https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark and still receive no mercy

**Comment by geoffreymcgill** [comment]
Leaving this one open for the community to implement. 

See [up-for-grabs](https://github.com/bridgedotnet/Bridge/labels/up-for-grabs) for others. 

See [CONTRIBUTING.md](https://github.com/bridgedotnet/Bridge/blob/master/.github/CONTRIBUTING.md) for info on contributing.

**Comment by geoffreymcgill** [comment]
The **MarkElement** class has been removed from the **Bridge.Html5** project as of the Bridge 16.0 release. See Issue #2914.
