### ISSUE TITLE
Why is TemplateAttribute sealed?

### ISSUE THREAD

**Issue by Dia6lo** [bridgedotnet/Bridge#1246]
I'm working on Pixi.js bindings and I've faced some duplicating templates:
https://github.com/Dia6lo/Bridge.Pixi/blob/master/Bridge.Pixi/Core/DisplayObject.cs#L187

For example
```csharp
[Template("on('click', {action})")]
public extern DisplayObject OnClick(Action<InteractionEvent> action);
```

Could be replaced with
```csharp
[OnTemplate("click")]
public extern DisplayObject OnClick(Action<InteractionEvent> action);
```

With some sort of this
```csharp
public class OnTemplateAttribute: TemplateAttribute
{
    public OnTemplateAttribute(string eventName)
    {
        // Some initialization code.
    }
}
```

Or even better
```csharp
public class OnTemplateAttribute: TemplateAttribute
{
    public OnTemplateAttribute(EventType eventType)
    {
        // Some initialization code.
    }
}
```

So, why is TemplateAttribute sealed?

**Comment by vladsch** [comment]
Template attribute is just instruction for Bridge compiler. That attribute is implemented inside assembly which uses non standard .NET core library (to have ability to use it inside Bridge libraries). Therefore that attribute cannot contain any logic (Bridge compiler cannot use that logic due different core library). So, any extention of that attribute has no any sense

**Comment by Dia6lo** [comment]
Oh, okay. So, I guess, there will be no point of extension of attributes in the future?

**Comment by vladsch** [comment]
When we add reflection support then you can create own attributes with required logic and analyze attributes using reflection (except Bridge attributes, like Template)
