### ISSUE TITLE
Template Add BridgeClass

### ISSUE THREAD

**Issue by MangelMaxime** [bridgedotnet/Bridge#1247]
Hello guys,

Each Time I add a Class in VisualStudio using the Template Bridge Class, the file name is correct but the class name is always `BridgeClass1`.

The Bridge Extension version is 1.12.0.

**Comment by geoffreymcgill** [comment]
Confirmed. For some reason the class name was hard coded in the template.

I will fix.

**Comment by MangelMaxime** [comment]
Thanks @geoffreymcgill

**Comment by geoffreymcgill** [comment]
The Class Template has been updated and will be available in the 1.13 release. 

I also published our VSIX project as new open-source project:

https://github.com/bridgedotnet/VSIX
