### ISSUE TITLE
Boxed Doubles gives incorrect type names

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1248]
``` csharp
object v = 1.0;
Global.Alert(v.GetType().FullName);
v = 1f;
Global.Alert(v.GetType().FullName);
```

[Live Bridge](http://live.bridge.net/#2c6e355eedc03a78b10f6751cf2c8fcb)
They both say System.Int when they should say System.Double and System.Single.

**Comment by DaniilVeriga** [comment]
Thank you for the problem.

The same/similar problem has been discussed in #1184. There are comments on why it is happening and why it is a difficult problem to resolve.

**Comment by geoffreymcgill** [comment]
Related to #1248, #1292, #1293 and #1294.

**Comment by michaelcheers** [comment]
Related to #1301
