### ISSUE TITLE
Enums marked as bytes don't overflow.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1249]
### Expected

a

### Actual

256

### Steps To Reproduce

```csharp
public class App
{
    enum b : byte
    {
        a,
        b
        
    }

    [Ready]
    public static void Main()
    {
        b v = (b)byte.MaxValue;
        Console.WriteLine(++v);
    }
}
```
[Bridge Fiddle](http://live.bridge.net/#8cd7b17facde482cd0a4b48945b56f59)
[Dot Net Fiddle](https://dotnetfiddle.net/kfTEzQ)

**Comment by DaniilVeriga** [comment]
Thank you for the report!
