### ISSUE TITLE
Failed to initialize HashSet<string> with inline collection when its size > 7

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#1254]
http://forums.bridge.net/forum/bridge-net-pro/bugs/2199

[Live Test Case](http://live.bridge.net/#5dd51df44cf1d8e133190638c65a5656)

The bug is reproducible with Bridge 1.12.1 and Bridge.Collections 1.2.1.

It is not reproducible anymore with the latest code, so this issue is created just to have it logged in GitHub.

**Comment by LeonidVeriga** [comment]
Should be #1231 releated fix.

**Comment by geoffreymcgill** [comment]
I can confirm this defect has been fixed with Bridge.Collections 1.3.0 release, and Bridge 1.13. 

Hope this helps.
