### ISSUE TITLE
Remove `is` from list of reserved words

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#1256]
Reported on the [forum](http://forums.bridge.net/forum/community/help/2188)

### Expected

`is: "test"`

### Actual

`$is: "test"`

### Steps To Reproduce

Example ([Live](http://live.bridge.net/#08ceb93b437eee71948b2ade202457f7))

```csharp
public class App
{
    [Name("is")]
    public string Is = "test";
}
```

**Comment by geoffreymcgill** [comment]
The reserved word list is being updated, see

https://github.com/bridgedotnet/Bridge/issues/1381#issuecomment-263503230
