### ISSUE TITLE
Review keywords list

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#1257]
The list should be reviewed to exclude items that are not keywords in JavaScript
#1256 fixed for `is` keyword. Reported on the [forum](http://forums.bridge.net/forum/community/help/2188)
#1355 You can't create a variable called window
#1344 Fields cannot be named __proto__ 

**UPD**:
- list of TypeScript [reserved words](https://github.com/Microsoft/TypeScript/issues/2536#issuecomment-87194347) **EDIT:** Moved to a separate Issue (#1426);
- #1381 All non-generic types have variable javascript clashes.

**Comment by zspitz** [comment]
@LeonidVeriga @geoffreymcgill See also [PR to create keywords page in the Typescript Handbook](Microsoft/Typescript-Handbook#344).

**Comment by LeonidVeriga** [comment]
@zspitz thank you for the link that is very useful!
