### ISSUE TITLE
Decimal object created without initial value throws an exception during comparison

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#1263]
### Expected

No JavaScript error

### Actual

`Uncaught TypeError: this.value.comparedTo is not a function`

### Steps To Reproduce

[Live Test Case](http://live.bridge.net/#ba0829f2b51aa282e17859885bfec885)
```csharp
public class App
{
    [Ready]
    public static void Main()
    {
        decimal x = new Decimal();
        int y = 1;
        
        Console.WriteLine(x > y);
    }
}
```

**Comment by vladsch** [comment]
Fixed in https://github.com/bridgedotnet/Bridge/pull/1252/commits/da619dcaeab826964f314dadba812bb232a51f9f
