### ISSUE TITLE
Default GetHashCode() is not repeatable

### ISSUE THREAD

**Issue by d-p-y** [bridgedotnet/Bridge#1264]
### Expected
Default GetHashCode() invocations for classes having fields being custom classes should return same values for unchanged object.

### Actual
Actually it returns different values.

### Steps To Reproduce

**UPD**: Example ([Live](http://live.bridge.net/#4d4e1fd1122f7ae823237fa44cbf174c)):
```csharp

	public class Bar {}

	class Foo {
		private object _bck = new Bar();
	}

	public class App
	{
		[Ready]
		public static void Main()
		{	
			var foo = new Foo();
			var h1 = foo.GetHashCode();
			var h2 = foo.GetHashCode();

			Console.WriteLine(h1 != h2 ? "has bug" : "no bug");
		}
	}
```

**Comment by d-p-y** [comment]
Hi,
Solution proposal is in pull request #1265 
I'm not able to tell if it doesn't break anything. This is due to Test\Batch1 and Test\Batch2 projects referencing unknown package "Bridge.Test". Do you have any idea if/when it will be released? Lack of it makes submitting patches uncomfortable... 

Thanks
Dominik

**Comment by DaniilVeriga** [comment]
Thank you for the report and submitting the pull request! We will review.

> Do you have any idea if/when it will be released? Lack of it makes submitting patches uncomfortable... 

Our apologies for the inconvenience. We are getting closer with releasing it. We'll tweet once it gets available.

**Comment by d-p-y** [comment]
Daniil, 
That is good news. 
Thanks!
