### ISSUE TITLE
Gitter room

### ISSUE THREAD

**Issue by listepo** [bridgedotnet/Bridge#1267]
Hi, what do you think about Gitter room for bridge.net?

**Comment by geoffreymcgill** [comment]
Sure, https://gitter.im/bridgedotnet

We'll monitor and see how it goes. No guarantee we'll always be there, or answer questions, but we'll give it a try.

**Comment by listepo** [comment]
@geoffreymcgill thanks, but you did not create a room
![orgs bridgedotnet rooms gitter](https://cloud.githubusercontent.com/assets/2510800/14862495/683b3492-0cba-11e6-9226-a36c0ea627c3.png)

**Comment by geoffreymcgill** [comment]
Fixed. 

[![Gitter](https://badges.gitter.im/bridgedotnet/Bridge.svg)](https://gitter.im/bridgedotnet/Bridge?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by listepo** [comment]
👍
