### ISSUE TITLE
Namespace used as class path breaks generated code

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#127]
The following C#:
```
namespace MyNameSpace
{
    public class UndefinedTrigger
    {
        private static int val = bindValue();
        private static int bindValue()
        {
            return 1;
        }
    }
}
```

Generates the following JavaScript:
```
Bridge.define('MyNameSpace.UndefinedTrigger', {
    statics: {
        $config:  {
            fields: {
                val: MyNameSpace.UndefinedTrigger.bindValue()
            }
        },
        bindValue: function () {
            return 1;
        }
    }
});
```

So far, so nice. Add it to a simple stub HTML file and open it (allow active content to run locally if you just opened the local .html file).
Example HTML:
```
<!DOCTYPE html>
<html>
 <head>
  <title></title>
  <script type="text/javascript" src="bridge.js"></script>
  <script type="text/javascript" src="myNameSpace.js"></script>
 </head>
 <body>
  Hey, world.
 </body>
</html>
```

When you load this page, you'll get an `'MyNameSpace' is undefined` error, originated by the JS line containing:
`val: MyNameSpace.UndefinedTrigger.bindValue()`

**Comment by geoffreymcgill** [comment]
This might be related to change made in #120. We are rolling back out of that change.

**Comment by geoffreymcgill** [comment]
Did this just start happening today?

**Comment by fabriciomurta** [comment]
working on stable and latest stuff
