### ISSUE TITLE
Config to specify a text file to use as a file header

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#1271]
Create a config option that could specify a text file whose content would be injected top of the generated .js file.

Possible options include setting in **bridge.json** or used in conjunction with the `outputBy` global config, see

http://bridge.net/kb/global-configuration/#outputBy

Original feature request:
http://forums.bridge.net/forum/community/help/2241-inject-header-comment-into-generated-js-file?p=2245#post2245

**Comment by LeonidVeriga** [comment]
There is [resources](https://github.com/bridgedotnet/Bridge/issues/1680) **bridge.json** config option:
To use a file header just specify either `remark` or `header`:
```js
"resources": [{
            // A default section (a section with no name setting)
            // Should be one per all resources
            // Values defined here will be applied to all resources (if not overridden)

            // A string with a header content 
            // or a path to a file with header content
            // Supports tokens (data taken from assembly vresion): 
            //     {version}
            //     {date}
            //     {year}
            //     {author}
            //     {copyright}
            "header":  "../header.txt"

            // Specifies if a line will be inserted before each file
            // Supports tokens:
            //     {name}
            //     {path}
            //     \n
            // Default is null
            "remark": "// source @{name}\n"
        }
]
```
