### ISSUE TITLE
Add option for Embedded Resources

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1277]
### Expected

There be an option for embedded resources.

### Actual

There isn't one.

**Comment by DaniilVeriga** [comment]
Generated scripts are being embedded into a .dll by default.
http://bridge.net/kb/global-configuration/#injectScriptToAssembly

Please clarify what else would you like to embed and what options could we provide? Please elaborate.

**Comment by michaelcheers** [comment]
In .Net, you can embed any type of file (.wav, .txt, .csv, .mp3, etc...) into code. In Bridge, I don't think there is a way to do that.

**Comment by DaniilVeriga** [comment]
Thank you for clarifying.

This functionality relates to Reflection - #15. Once Reflection is implemented, it opens a gate for this feature.

**Comment by geoffreymcgill** [comment]
Embedding Resources is now supported in Bridge as of version 15.0. 

We will have to provide some more user friendly samples. See #1793.

The related Unit Tests can provide some insight into how this functionality works:

https://github.com/bridgedotnet/Bridge/blob/master/Tests/Batch1/Reflection/AssemblyTests.cs#L248-L278
