### ISSUE TITLE
"outputBy" configuration option results in an empty filename

### ISSUE THREAD

**Issue by johnwason** [bridgedotnet/Bridge#1284]
When using "outputBy: Project" in the bridge.json file in version 1.13, the filename is empty, ie the output is ".js" and ".min.js" instead of "ProjectName.js" and "ProjectName.min.js" as it was in version 1.11.

**Comment by LeonidVeriga** [comment]
Hi @johnwason,

Thank you for reporting the problem. We are investigating.

As a workaround, could you please use [`fileName`](http://bridge.net/kb/global-configuration/#fileName) configuration option in addition to `outputBy` setting:
```
"outputBy":  "Project",
"fileName":  "ProjectName.js"
```

**Comment by johnwason** [comment]
Yes, that does work

**Comment by geoffreymcgill** [comment]
Related to another forum thread:
http://forums.bridge.net/forum/bridge-net-pro/bugs/2295-bridge-1-13-combinescripts-error

**Comment by geoffreymcgill** [comment]
Please see #1300 for a related problem.
