### ISSUE TITLE
Live Bridge not working

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1286]
### Expected

no error

### Actual

C# Compilation Failed

Microsoft (R) Visual C# Compiler version 4.0.30319.34209

Microsoft (R) Visual C# Compiler version 4.0.30319.34209

for Microsoft (R) .NET Framework 4.5
Copyright (C) Microsoft Corporation. All rights reserved.

error CS0006: Metadata file '\\fs6-n02\stor14wc1ord1\956235\live.bridge.net\web\content\Bridge\Builder\Bridge.jQuery2.dll' could not be found
error CS0006: Metadata file '\\fs6-n02\stor14wc1ord1\956235\live.bridge.net\web\content\Bridge\Builder\Bridge.Bootstrap3.dll' could not be found
error CS0006: Metadata file '\\fs6-n02\stor14wc1ord1\956235\live.bridge.net\web\content\Bridge\Builder\Bridge.WebGL.dll' could not be found

### Steps To Reproduce
Just Visit: [Live Bridge](http://live.bridge.net)

**Comment by geoffreymcgill** [comment]
It's being updated, but the server is fighting back. Should be fixed soon.
