### ISSUE TITLE
[Documentation] bridge.[Release|Debug|Any].json support in Global Configuration KB

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#1289]
Bridge 1.12 introduced [Custom bridge.json Config Files](http://bridge.net/bridge-1-12-released/#custom-bridge-json) support: **bridge.[Release|Debug|Any].json**

It would be great to mention it in the [Global Configuration](https://github.com/bridgedotnet/Bridge/wiki/global-configuration) wiki.

**Comment by geoffreymcgill** [comment]
Done. 

https://github.com/bridgedotnet/Bridge/wiki/Global-Configuration#custom-bridgejson-files
