### ISSUE TITLE
Ready attribute should not be neccessary for Main

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1303]
### Expected

If ready attribute is not used, Main will still initialize.

### Actual

If ready attribute is not used, Main won't initialize.

### Steps To Reproduce

```csharp
public class App
{
    public static void Main()
    {
         Console.WriteLine("Hello World!");
    }
}
```

**Comment by geoffreymcgill** [comment]
Yes, this has been annoying me lately. We will fix this for Bridge 1.14.

**Comment by LeonidVeriga** [comment]
@michaelcheers, can you please clarify - do you suggest:
 - auto calling static `Main` method (a single one)
 - throwing an error if there are more than one static `Main` methods (or calling all)

**Comment by geoffreymcgill** [comment]
Goal is to mimic the .NET behaviour. If multiple Main's are allowed in a .NET Console app, then we should support multiple Main's. If only one is required, and an Exception is thrown if >1, then Bridge should thrown the same Exception under the same conditions. 

I do think any Methods marked with `[Ready]` should be called, even if a Main is configured, but called after Main.

**Comment by michaelcheers** [comment]
@geoffreymcgill @LeonidVeriga I think that it should look for Main methods except if there are any methods marked Ready.  

In .NET you can choose which startup class you want or you can just run auto find. The .NET behaviour, if you ask it to auto-find, is to run the first Main method it finds and no other Main methods.

Also, you could have an option to use Init not Ready if you want.

**Comment by LeonidVeriga** [comment]
The implemetation is:
-  (to mimic .Net), `static Main` method automatically called with `Bridge.ready` (no `[Ready]` attridute required)
- If there are more than one `static Main` methods (**with no** `[Ready]` attribute) then compilation error shown, like `Program has more than one entry point defined - App1.Main, App2.Main`

Example1 ([Live](http://live.bridge.net/#73063853bf41716bcf00e6614bb140b0)) - will call `App.NotMain`, `App.Main`, `App1.NotMain`, `App1.Main` (the latter is with **no** `[Ready]`):
```
    public class App
    {
        [Ready]
        public static void NotMain()
        {
           // will be called
           System.Console.WriteLine("App.NotMain");
        }

        [Ready]
        public static void Main()
        {
           // will be called
           System.Console.WriteLine("App.Main");
        }

    }

    public class App1
    {
        [Ready]
        public static void NotMain()
        {
           // will be called
           System.Console.WriteLine("App1.NotMain");
        }

        public static void Main()
        {
           // will be called
           System.Console.WriteLine("App1.Main");
        }
    }
```

Example2 ([Live](http://live.bridge.net/#289e63bf04116b4b47dfb9eb2c0f0441)) - will show compilation error as there are two `Main` methods - `App.Main` (the first is now with **no** `[Ready]`) and `App1.Main`:
```
    public class App
    {
        [Ready]
        public static void NotMain()
        {
           // would be called
           System.Console.WriteLine("App.NotMain");
        }

        public static void Main()
        {
           // the first Main with no [Ready]
           System.Console.WriteLine("App.Main");
        }

    }

    public class App1
    {
        [Ready]
        public static void NotMain()
        {
           // would be called
           System.Console.WriteLine("App1.NotMain");
        }

        public static void Main()
        {
           // the second Main with no [Ready] causing compilation error
           System.Console.WriteLine("App1.Main");
        }
    }
```
