### ISSUE TITLE
Returning the assignment expression of an awaited task causes invalid codegen

### ISSUE THREAD

**Issue by Suchiman** [bridgedotnet/Bridge#1305]
### Expected
The Task is awaited, the awaited result gets assigned to the CurrentInt variable and the assigned value will be returned.

### Actual
Nuclear power plant exploded, causing mutated, invalid JS code.

### Steps To Reproduce
http://live.bridge.net/#167c71dd0b2e24ba112047c3e1457d18
```csharp
public static class App
{
    private static int CurrentInt;
    public static async Task<int> Test()
    {
        return CurrentInt = await Task.FromResult(0);
    }
}
```

**Comment by geoffreymcgill** [comment]
Looks like there is a missing `)` in the template. Definitely a defect, and we will do our best to fix this right away.

**Comment by Suchiman** [comment]
@geoffreymcgill i thought that at first too but it seems way more broken.
Line 21: `$task1 = Bridge.Task.fromResult(0);` ok the first time
Line 28: `$tcs.setResult($task1 = Bridge.Task.fromResult(0);` what? here it is again and doing something weird too.
Line 35: `(Demo.App.currentInt = $taskResult1, Demo.App.currentInt));` i'm not sure what that's supposed to be but it's certainly not only a brace mismatch 😉

**Comment by geoffreymcgill** [comment]
Thanks for the update. We'll take a close look.
