### ISSUE TITLE
JSON.Parse breaks assumptions about long

### ISSUE THREAD

**Issue by Suchiman** [bridgedotnet/Bridge#1306]
### Expected

I can JSON deserialize ObjectLiterals and work with them.
### Actual

Deserialized ObjectLiterals containing longs fail when used in operations such as comparisons because they don't have member methods like `ne`
### Steps To Reproduce

http://deck.net/195d16ff0c8630adf40d438941b5a22f

``` csharp
public class App
{
    public static void Main()
    {
        var t1 = JSON.Parse<Test>("{\"Id\":5}");
        var t2 = JSON.Parse<Test>("{\"Id\":10}");
        var result = t1.Id != t2.Id;
        Global.Alert(result.ToString());
    }
}

[ObjectLiteral]
public class Test
{
    public long Id { get; set; }
}
```

**Comment by geoffreymcgill** [comment]
Thank you for the report. We have reproduced the problem and are investigating a fix.

**Comment by LeonidVeriga** [comment]
Use `Bridge.JSON.Serialize` and `Bridge.JSON.Deserialize`. See #2418 for more information.
