### ISSUE TITLE
Explicit interface members don't work.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1307]
### Expected

Compile.

### Actual

Doesn't compile.

### Steps To Reproduce
[Example](http://live.bridge.net/#c34d4ea3d10d0be84e105b7fe01e651e)
```csharp
public interface I {
    void Foo ();
}

public class A : I {
    public void Foo () {
        Console.WriteLine("A");
    }
}

public class B : A, I {
    void I.Foo () {
        Console.WriteLine("B");
    }
}

public static class Program {
    [Ready]
    public static void Main (string[] args) {
        I i;

        var a = new A();
        i = a;
        a.Foo(); // expected: "A"
        i.Foo(); // expected: "A"

        var b = new B();
        i = b;
        b.Foo(); // expected: "A"
        i.Foo(); // expected: "B"

    }
}
```

**Comment by geoffreymcgill** [comment]
Confirmed, and thanks for the great test. 

We will try our best to fix this as quickly as possible.

**Comment by vladsch** [comment]
It is the same issue as
https://github.com/bridgedotnet/Bridge/issues/1025

See comment https://github.com/bridgedotnet/Bridge/issues/1025#issuecomment-191752216

**Comment by geoffreymcgill** [comment]
Duplicate. See #1025. 

This issue is being worked on, but will not make it into the 1.14 release.

**Comment by LeonidVeriga** [comment]
#1025 has been fixed.
