### ISSUE TITLE
Booleans stored as objects give incorrect values

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1309]
### Expected

True
### Actual

false
### Steps To Reproduce

[Sample](http://live.bridge.net/#7a491fb975dd209ab6d4b1c985d9c99a)

``` csharp
public class App
{
    [Ready]
    public static void Main()
    {
        object val = false;
        Console.WriteLine(val.ToString() == bool.FalseString);
    }
}
```

**Comment by michaelcheers** [comment]
Enums stored as objects also give incorrect values.
Related #1312 .

**Comment by geoffreymcgill** [comment]
Thanks for the report. We have reproduced and will fix.
