### ISSUE TITLE
Change System.Console class

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1310]
I was thinking that it would be cool to change the System.Console class so instead of printing to the javascript console it would print to a javascript 
```
<p>
```
 by default but it could print to any TextWriter like in C#. I am thinking we keep Bridge.Console the same but change System.Console to a TextWriter with a default of a 
```
<p>
```
.
There are many methods that can't be implemented in the Console.
**For example:**
```csharp
Console.Write // (can only be implemented with Console.Log)
Console.SetOut
Console.SetIn
Console.SetError
Console.CancelKeyPress
Console.SetWindowSize
Console.SetWindowPosition
Console.SetCursorPosition
Console.SetBufferSize
Console.ResetColor
Console.ReadLine // (only with prompt which isn't actually the console)
Console.ReadKey
Console.Read
Console.OpenStandardError
Console.OpenStandardInput
Console.OpenStandardOutput
Console.MoveBufferArea
Console.Clear
```

**Comment by geoffreymcgill** [comment]
Hi @michaelcheers,

Yes, I agree with everything you have noted here. The functionality of **System.Console** has been annoying me lately and we are going to change.

I was thinking almost the exact same thing, that **Bridge.Console** would continue to log to the browser Console, but **System.Console** would log to some kind of new visible output window.

We're going to mock up some ideas and try to implement for the Bridge 15 release.

**Comment by geoffreymcgill** [comment]
We discussed this feature request today and have a plan to implement. Should be available for Bridge 15.

**Comment by geoffreymcgill** [comment]
This issue is going to be closed soon, although only partially implemented with the new Bridge.Console functionality. 

We will continue to expand on the functionality, and track in issue #1763.

**Comment by geoffreymcgill** [comment]
Bridge Console has been merged into the *master* branch.
