### ISSUE TITLE
Interface's default parameters are ignored

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1313]
### Expected

```
1
```

### Actual

```javascript
undefined
```

### Steps To Reproduce
[Bridge Live](http://live.bridge.net/#2987ebc0b90d448e6a506945d309aaa9)
[Dot Net Fiddle](https://dotnetfiddle.net/MLuM0r)
```csharp
public interface IInterface
{
    int function (int v = 1);
}

public class Class : IInterface
{
    public Class ()
    {
        
    }
    
    public int function (int v)
    {
        Console.WriteLine(v);
        return v;
    }
}

public class App
{
    [Ready]
    public static void Main()
    {
        IInterface value = new Class();
        value.function();
    }
}
```

**Comment by geoffreymcgill** [comment]
Thanks for the excellent sample. We really appreciate all the simplified samples you are providing. They are very helpful. 

We are reviewing this defect to determine what is going wrong. We expect to fix for the 1.14 release.
