### ISSUE TITLE
String (+) operator doesn't work on empty string (s).

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1316]
### Expected

Output 0

### Actual

Gives compiler error: 
```
(32,27): error CS0656: Missing compiler required member 'System.String.Concat'
```

### Steps To Reproduce
[Example](http://live.bridge.net/#2fd738a5ded11148549f64572ea0f4e8)
```csharp
public class App
{
    [Ready]
    public static void Main()
    {
        int v = 0;
        Console.WriteLine(v + "");
    }
}
```

**Comment by geoffreymcgill** [comment]
Hi @michaelcheers, 

Thanks for the report and simplified sample. We have reproduced the problem and will fix.
