### ISSUE TITLE
String (+) operator doesn't work on Enums

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1317]
### Expected

```
Language: English
```
### Actual

```
Language: 0
```
### Steps To Reproduce

[Bridge Live](http://live.bridge.net/#2ea7583aba862f63c49971bff204eb75)
[Dot Net Fiddle](https://dotnetfiddle.net/xrObZq)

``` csharp
public class App
{
    [Ready]
    public static void Main()
    {
        Console.WriteLine("Language: " + Enum.English);
    }

    enum Enum
    {
        English
    }
}
```

**Comment by michaelcheers** [comment]
Related to #1312.

**Comment by geoffreymcgill** [comment]
Thanks for the great sample. We have reproduced and will fix.

**Comment by LeonidVeriga** [comment]
This one is hard to fix. We will have an internal discussion.

A workaround is to add `ToString` manually, example([Live](http://live.bridge.net/#b276cb4d55b414b08b8ee1b431c234d7)):
```
public class App
{
    [Ready]
    public static void Main()
    {
        Console.WriteLine("Language: " + Enum.English.ToString());
    }
    
    enum Enum
    {
        English
    }
}
```
