### ISSUE TITLE
Remove public constructor for Any<T1, ..> classes

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#1327]
Related forum thread:
http://forums.bridge.net/forum/bridge-net-pro/bugs/2278-open-1327-any-t1-classes-shouldn-t-have-public-constructors

### Expected

`x3` should not be possible

### Actual

`x1` is an int, which is either-an-int-or-a-string, which is good.
`x2` is a string, which is either-an-int-or-a-string, which is good.
`x3` is not an int or a string, which is bad.

### Steps To Reproduce

```csharp
Any<int, string> x1 = 123;
Any<int, string> x2 = "test";
Any<int, string> x3 = new Any<int, string>();
```

**Comment by LeonidVeriga** [comment]
Made `Any` class constructor protected to allow inheritance (used in Bridge.Angular, for example).
