### ISSUE TITLE
Enhanced support for yield

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#1329]
Related to initial implementation of `yield` in #12.

Related:

 * http://forums.bridge.net/forum/bridge-net-pro/bugs/1955-enumerable-implementation-does-not-match-the-c-implementation
 * #2270 Task.Yield()

**Comment by michaelcheers** [comment]
@geoffreymcgill, I just wanted to say that the type of a yield IEnumerable is not Array. [Dot Net Fiddle](https://dotnetfiddle.net/XlQrqt)

**Comment by TriEdgeAI** [comment]
Please implement this, plspslpslpslpspslpslsplspsl

**Comment by TriEdgeAI** [comment]
Is this being worked on? Would it be possible for me to implement it, because my team is in a need of it?

**Comment by geoffreymcgill** [comment]
Our goal is to review this functionality during the 15.8.0 milestone. 

Our preference is to not implement until 16+, but we're going to and determine if existing logic from **Async** can be reused. If it's an easy port, then we'll attempt to implement for 15.8, maybe 15.9.

**Comment by TriEdgeAI** [comment]
Workaround that we'll be using until the official version comes out:
http://deck.net/3aea0dbd2ac9d027a5b26ffc81cb9e33

:)

**Comment by TriEdgeAI** [comment]
I was looking through Bridge's code for yield and await/async and I believe I can implement the yield to work just like async methods, should I do it and make a PR? It would take me a day or two.

**Comment by geoffreymcgill** [comment]
Hi @TriEdgeAI – If you make a PR, we will would be grateful. We will not be able to get around to adding this functionality any time soon. 

Once your PR has been submitted, we will review and help with testing.

**Comment by TriEdgeAI** [comment]
Messed up the first two PRs. Third one should be OK. I believe the code can be further improved by making a base class ResumableBlock that AsyncBlock and GeneratorBlock both inherit from or something. Goto #1004 should also be very easy to implement at this point.

**Comment by geoffreymcgill** [comment]
Hi @TriEdgeAI – Thanks for the awesome pull request. We are reviewing and testing. Our goal is to merge into **master** this week.
