### ISSUE TITLE
Support Singleline Regex option

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#1332]
Related to the [More .NET Regex support](https://github.com/bridgedotnet/Bridge/issues/1167#issuecomment-217184608) feature list.

Related to the following forum [thread](http://forums.bridge.net/forum/general/feature-requests/2320-please-support-singleline-option-in-regex).

Singleline option ([MSDN](https://msdn.microsoft.com/en-us/library/yd1hzczs(v=vs.110).aspx#Singleline)):

> The RegexOptions.Singleline option, or the s inline option, causes the regular expression engine to treat the input string as if it consists of a single line. It does this by changing the behavior of the period (.) language element so that it matches every character, instead of matching every character except for the newline character \n or \u000A.

Regex option example ([Live](http://live.bridge.net/#8da99b1e93b663880c5c7295770cd7d6)):
```csharp
public class ExampleRegexOption
{
    [Ready]
    public static void Main()
    {
      string pattern = "^.+";
      string input = "This is one line and" + Environment.NewLine + "this is the second.";
      
      foreach (Match match in Regex.Matches(input, pattern))
      {
         Console.WriteLine(Regex.Escape(match.Value));
      }
    
      Console.WriteLine();
      
      foreach (Match match in Regex.Matches(input, pattern, RegexOptions.Singleline))
      {
         Console.WriteLine(Regex.Escape(match.Value));
      }
    }
}
```
<a name="Inline"></a>Inline example ([Live](http://live.bridge.net/#ef8fee7be9dffb9c05353c5de14f6c86)):
```csharp
public class ExampleInline
{
    [Ready]
    public static void Main()
    {      
      string pattern = "(?s)^.+";
      string input = "This is one line and" + Environment.NewLine + "this is the second.";
    
      foreach (Match match in Regex.Matches(input, pattern))
      {
         Console.WriteLine(Regex.Escape(match.Value));
      }
    }
}
```

**Comment by AndreyChechel** [comment]
0bb391be922c82b5a2e7a3e9d628f23f1560128e - Singleline mode; Regex Anchors updated (replacement were simplified);
168f77a71b269ec718d1741c149d12f01cec291d - Regex Inline options support (Multiline, Singleline, IgnoreWhitespace)
