### ISSUE TITLE
Environment.NewLine should return \r\n instead of \n

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#1336]
### Expected

https://dotnetfiddle.net/qkjfKP

```
// \r\n
2
```

### Actual

http://live.bridge.net/#27b5c8dbadc4a476c56ba6cabedbdde9

```
// \n
1
```

### Steps To Reproduce

```csharp
public class App
{
    [Ready]
    public static void Main()
    {
        var s = Environment.NewLine.Length;
        Console.WriteLine(s);
    }
}
```

**Comment by kcudnik** [comment]
According to [https://msdn.microsoft.com/en-us/library/system.environment.newline(v=vs.110).aspx](url)

> A string containing "\r\n" for non-Unix platforms, or a string containing "\n" for Unix platforms.

So this could be configure via options, for me, im developing in mono, so i would expect "\n" :)

**Comment by geoffreymcgill** [comment]
Yes, I've done a lot more research into the issue, and this was a mistake. We're going to switch back to `\n\`, and yes maybe make it configurable. 

I will try to post more later today.

**Comment by geoffreymcgill** [comment]
Using `\n` is correct. 

The **Environment** in this case is the User-Agent, and is separate from any particular OS.

The browsers use `\n` for newline characters. 

We discussed creating a global config, but at this point it doesn't seem necessary.

Closing the issue.

**Comment by geoffreymcgill** [comment]
Another supporting argument for using `\n` is the `document.writeln()` function in JavaScript writes a `\n` to the end of the passed string argument.

https://www.w3.org/TR/2000/WD-DOM-Level-2-HTML-20001113/html.html#ID-35318390

http://www.w3schools.com/jsref/met_doc_writeln.asp
