### ISSUE TITLE
Missing overloaded constructors on StringBuilder

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#134]
https://msdn.microsoft.com/en-us/library/system.text.stringbuilder.stringbuilder%28v=vs.110%29.aspx

    public StringBuilder(int capacity)

**Comment by Mimisss** [comment]
Based on the current implementation is the notion of capacity meaningful?

**Comment by geoffreymcgill** [comment]
If the overload is not available, it makes porting existing C# difficult. That said, I'm not 100% sure what is meant by your statement.

**Comment by Mimisss** [comment]
In C# the implementation is a linked list of type char and capacity plays a role. This overload also introduces the `Capacity` property. We can safely add this overload to initialize the object with an empty string and safely return the length of the internal buffer as the value of the `Capacity` property.
