### ISSUE TITLE
Boolean has incorrect case with Console.WriteLine

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1345]
### Expected

```csharp
True
```
### Actual

``` javascript
true
```
### Steps To Reproduce

http://deck.net/bb9fbc78f53e619673b743f96f573aae
https://dotnetfiddle.net/TjkBwh

``` csharp
public class App
{
    public static void Main()
    {
        string value = "hello world";
        Console.WriteLine(value == "hello world");
    }
}
```

### See Also

* #1309

**Comment by LeonidVeriga** [comment]
Thanks for the report. We have reproduced and will fix.

**Comment by kcudnik** [comment]
This one can be tricky, javascript bool prints "true".
Seems like a candidate for a bridge option, maybe not only this one, but a range of similar cases.

**Comment by geoffreymcgill** [comment]
We're going to create type wrappers for all the C# types. We won't be able to implement this for a while yet, but once we do, we will be able to control the `.toString()` output to exactly match that of the expected value in C#.

**Comment by michaelcheers** [comment]
@geoffreymcgill, Can't you change Console.WriteLine for now?

**Comment by geoffreymcgill** [comment]
If you explicitly call `.ToString()` on a *boolean*, it will correctly return `True|False` vs the default JavaScript `true|false` from `.toString()`.

http://deck.net/d58902593e66d105799c1ac7b441eb34

```csharp
public class App
{
    public static void Main()
    {
        string value = "hello world";
        Console.WriteLine((value == "hello world").ToString());
    }
}
```

We can force a type check in **Bridge.Console**, but we haven't 100% decided on an approach. I'm looking into some options.

**Comment by geoffreymcgill** [comment]
We should be able to add an easy fix to **Bridge.Console** by updating the following `[Template]`:

https://github.com/bridgedotnet/Bridge/blob/master/Bridge/System/Console.cs#L190

```// Old
[Template("Bridge.Console.log({value})")]

// New
[Template("Bridge.Console.log(System.Boolean.toString({value}))")]
```
