### ISSUE TITLE
typeof(void) compiles to void and throws syntax errors.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1348]
### Expected

```
System.RuntimeType
```
### Actual

```
Uncaught SyntaxError: Unexpected token ;
```
### Steps To Reproduce

http://live.bridge.net/#f8d342be282d4a3f6744fbc48e714241
https://dotnetfiddle.net/ahZJV1

``` csharp
public class App
{
    public static void Main()
    {
        object value = typeof(void);
        Console.WriteLine(value.GetType().FullName);
    }
}
```

**Comment by LeonidVeriga** [comment]
PR #1652 fixes:

```cs
object value = typeof(void);
```
generates illegal JS 
```js
var value = void;
```
Now it generates
```js
var value = Object;
```

**Comment by michaelcheers** [comment]
@LeonidVeriga, now reflection is implemented it would be useful to make a distinction between void and Object. Maybe, create a Void type.
