### ISSUE TITLE
Unnecessary code in bridge.js.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1349]
Line 585:
[Bridge Case 1](https://github.com/bridgedotnet/Bridge/blob/master/Tests/Runner/TypeScript/App1/bridge.js#L585).
```javascript
for (i; i < d.length; i++) {
                if (!o) {
                    return null;
                }

                o = o[d[i]];
            }
```
does just as much as:
```javascript
for (; i < d.length; i++) {
                if (!o) {
                    return null;
                }

                o = o[d[i]];
            }
```
Line 4261: [Bridge Case 2](https://github.com/bridgedotnet/Bridge/blob/master/Tests/Runner/TypeScript/App1/bridge.js#L4261).
```javascript
; d.__isLong__;
```
does just as much as:
```javascript
;
```
Line 5045: [Bridge Case 3](https://github.com/bridgedotnet/Bridge/blob/master/Tests/Runner/TypeScript/App1/bridge.js#L5045). Why is there a not operator before 'function' at the beginning of the line?
Line 5782: [Bridge Case 4](https://github.com/bridgedotnet/Bridge/blob/master/Tests/Runner/TypeScript/App1/bridge.js#L5782)
```javascript
for (j; j < format.length; j++) {
                    d = Bridge.Date.parseExact(str, format[j], provider, utc, true);

                    if (d != null) {
                        return d;
                    }
                }
```
does the same as: 
```javascript
for (; j < format.length; j++) {
                    d = Bridge.Date.parseExact(str, format[j], provider, utc, true);

                    if (d != null) {
                        return d;
                    }
                }
```

**Comment by geoffreymcgill** [comment]
Hi @michaelcheers - **Case 2** and **Case 3** are imported 3rd party js libraries that are used for Decimal and Long support. Generally we wouldn't adjust the source of those libraries. Through Unit testing we would ensure compatibility, and if an issue is discovered, we would report to the original author. 

**Case 1** and **Case 4** would provide a tiny optimization. We recently had an internal discussion about the `for` loop syntax that is used in **bridge.js** and the compiler templates. There are some performance improvements that can be made, and syntax optimizations.

These `for` loop revisions to **bridge.js** will come eventually. We need to have time to test properly before committing to the syntax revisions and build a performance test suite.

**Comment by geoffreymcgill** [comment]
I'm going to close this issue. Any `for` loop and other syntax optimizations are going to be explored in an upcoming project.
