### ISSUE TITLE
Missing support for [InternalsVisibleTo] assembly Attribute

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#135]
```
[assembly: InternalsVisibleTo("ProjectName")]
```

https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.internalsvisibletoattribute%28v=vs.110%29.aspx

**Comment by LeonidVeriga** [comment]
Implemented in https://github.com/bridgedotnet/Bridge/issues/2190
