### ISSUE TITLE
You can't create a variable called window

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1355]
I think this should work and it should change the variable name to $window as a solution.

### Expected

What the user types.

### Actual

Uncaught TypeError: Cannot read property 'prompt' of undefined

### Steps To Reproduce
**Example** [Live](http://live.bridge.net/#a50d91b25046ee10d80bd48d6810f1fe)
```csharp
public class App
{
    [Ready]
    public static void Main()
    {
        var window = Window.Prompt();
        Console.WriteLine(window);
    }
}
```

**Comment by LeonidVeriga** [comment]
Thanks for reporting this issue, @michaelcheers.

Yes, the fix would be to include local variable name `window` into reserved keyword list.
I narrowed down the example a bit.

Related #1257
