### ISSUE TITLE
Variable called window breaks html5 window.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1356]
### Expected

What the user typed.

### Actual

Uncaught TypeError: window.prompt is not a function

### Steps To Reproduce
[Live Bridge](http://live.bridge.net/#fbbb51dc2606dd51976faae79359e5fb)
```csharp
public class App
{
    [Ready]
    public static void Main()
    {
        var window = 1;
        Console.WriteLine(Window.Prompt());
    }
}
```

**Comment by LeonidVeriga** [comment]
The same issue as #1355 You can't create a variable called window
