### ISSUE TITLE
String.IndexOf overloads

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#136]
Missing `IndexOf` overloads

https://msdn.microsoft.com/en-us/library/System.String.IndexOf%28v=vs.110%29.aspx

**Comment by Mimisss** [comment]
`public int IndexOf(char searchValue)`
`public int IndexOf(char searchValue, int fromIndex)`
`public int IndexOf(string searchValue)`
`public int IndexOf(string searchValue, int fromIndex)`
`public int IndexOf(char searchValue, int fromIndex, int count)`
`public int IndexOf(string searchValue, int fromIndex, int count)`
