### ISSUE TITLE
Support Multiline Regex option

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#1360]
Related to the [More .NET Regex support](https://github.com/bridgedotnet/Bridge/issues/1167) feature list.

Multiline option ([MSDN] (https://msdn.microsoft.com/en-us/library/yd1hzczs(v=vs.110).aspx#Multiline)):
> The RegexOptions.Multiline option, or the m inline option, enables the regular expression engine to handle an input string that consists of multiple lines. It changes the interpretation of the ^ and $ language elements so that they match the beginning and end of a line, instead of the beginning and end of the input string

Regex option example ([Live](http://live.bridge.net/#fcdde30adec5cc712ece29501957efb6)):
```csharp
public class ExampleRegexOption
{
    [Ready]
    public static void Main()
    {
        string input = "Joe 164\n" + 
                         "Sam 208\n" + 
                         "Allison 211\n" + 
                         "Gwen 171\n"; 
        
        var scores = new Dictionary<int, string>();
        
        var pattern = @"^(\w+)\s(\d+)\r*$";
        
        foreach (Match match in Regex.Matches(input, pattern, RegexOptions.Multiline))
        {
            scores.Add(Int32.Parse(match.Groups[2].Value), (string) match.Groups[1].Value);
        }
        
        foreach (KeyValuePair<int, string> score in scores)
        {
            Console.WriteLine(score.Value + ": " + score.Key);
        }
    }
}
```
<a name="Inline"></a>Inline example ([Live](http://live.bridge.net/#eef236668f856412886934bd77008026)):
```csharp
public class ExampleInline
{
    [Ready]
    public static void Main()
    {
        string input = "Joe 164\n" + 
                         "Sam 208\n" + 
                         "Allison 211\n" + 
                         "Gwen 171\n"; 
        
        var scores = new Dictionary<int, string>();
        
        var pattern = @"(?m)^(\w+)\s(\d+)\r*$";
        
        foreach (Match match in Regex.Matches(input, pattern))
        {
            scores.Add(Convert.ToInt32(match.Groups[2].Value), match.Groups[1].Value);
        }
        
        foreach (KeyValuePair<int, string> score in scores)
        {
            Console.WriteLine(score.Value + ": " + score.Key);
        }
    }
}
```

**Comment by michaelcheers** [comment]
Related to #1332.

**Comment by AndreyChechel** [comment]
0bb391be922c82b5a2e7a3e9d628f23f1560128e - Singleline mode; Regex Anchors updated (replacement were simplified);
168f77a71b269ec718d1741c149d12f01cec291d - Regex Inline options support (Multiline, Singleline, IgnoreWhitespace)
