### ISSUE TITLE
Implement static String.Compare Method

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#137]
https://msdn.microsoft.com/en-us/library/zkcaxw5y%28v=vs.110%29.aspx

With overloads

**Comment by Mimisss** [comment]
`public static int Compare(string strA, string strB)`
`public static int Compare(string strA, string strB, bool ignoreCase)`
`public static int Compare(string strA, int indexA, string strB, int indexB, int length)`
`public static int Compare(string strA, int indexA, string strB, int indexB, int length, bool ignoreCase)`
