### ISSUE TITLE
SVGSVGElement support

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#1372]
https://developer.mozilla.org/en/docs/Web/API/SVGSVGElement

**Comment by liruqi** [comment]
@geoffreymcgill Thanks.
But still something wrong with `Bridge.as`. `SVGSVGElement` inherit from `Element`, Bridge.as should return the passed object. I believe we should investigate `Bridge.is` implementation with this example http://liruqi.github.io/Bridge/test/Bridge-1371.html.

* https://msdn.microsoft.com/en-us/library/ff972122(v=vs.85).aspx
* https://developer.mozilla.org/en-US/docs/Web/API/SVGSVGElement

**Comment by michaelcheers** [comment]
@geoffreymcgill, you could try getting something from lib.d.ts as converted by [TypescriptToCS2](https://github.com/michaelcheers/TypescriptToCS2), [a url to the cs file](https://1drv.ms/u/s!Av0Nwqk2Bg1nhfo40YUDkPClTQ1FGQ).

**Comment by R2D221** [comment]
Given that the new Retyped packages now provide support for SVGElement and friends, should this issue be closed?

**Comment by geoffreymcgill** [comment]
Hi @R2D221 – Thanks for the reminder. Yes, **SVGSVGElement** is now supported in the [Retyped.dom](https://www.nuget.org/packages/retyped.dom) package. **Retyped.dom** is included when you install [Retyped](https://www.nuget.org/packages/retyped) package.

```
install-package retyped
```
