### ISSUE TITLE
Literal Multiplied by BYTES_PER_ELEMENT wrong result

### ISSUE THREAD

**Issue by leirbag4** [bridgedotnet/Bridge#1373]
When you multiply a literal by Float32Array.BYTES_PER_ELEMENT, only literal value is returned.
Also tried casting to int.
### Expected

8
### Actual

2
### Steps To Reproduce

``` csharp
public class App
{
    public static void Main()
    {
        int numb0 = Float32Array.BYTES_PER_ELEMENT;
        //echo -> 4
        int numb1 = 2 * Float32Array.BYTES_PER_ELEMENT;
        //echo -> 2
    }
}
```

**Comment by fabriciomurta** [comment]
Fixed! The fix will be going to the next Bridge release (see attached milestone, currently 16.7.1).
