### ISSUE TITLE
Use map function for Array.ConvertAll

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1374]
### Expected

```javascript
                var array = [1, 3, 5];
                console.log(array.map($_.App.f1));
```
### Actual
```javascript
                var array = [1, 3, 5];
                console.log(Bridge.Array.convertAll(array, ($_.App.f1)));
```
### Steps To Reproduce
[Live Bridge](http://live.bridge.net/#841dd3729d1f718a28a0bdf4b8412c4a)
```csharp
/// <summary>
/// Creates a simple class
/// </summary>
public class App
{
    // Use the [Ready] attribute to automatically
    // run this method when the page is ready.
    [Ready]
    public static void Main()
    {
        int[] array = new[]{1, 3, 5};
        Console.WriteLine(Array.ConvertAll(array, (v => v.ToString())));
    }
}
```

**Comment by LeonidVeriga** [comment]
Thank you for providing this enhancement, @michaelcheers.
We will consider including it in the next releases.

**Comment by michaelcheers** [comment]
I've added it to my pull request: #1369.

**Comment by LeonidVeriga** [comment]
Array's `map()` function is used inside `convertAll()` as an optimization.
Using `map()` instead of `convertAll()` is not recommended as the latter contatins code to check if input array or converter is null with exception throwing.
