### ISSUE TITLE
Support Inline Regex options (in)

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#1375]
Related to #1167

[Inline options](https://msdn.microsoft.com/en-us/library/x044wc7s(v=vs.110).aspx) can be set using `(?imnsx-imnsx)` or `(?imnsx-imnsx:<expression>`) constructions. They enable/disable corresponding options for the subsequent expression within the current Group.

The following options should be supported:
- `i` - Case-insensitive matching
- `n` - Explicit captures only. (Parentheses do not act as capturing groups.)

`(msx)` options supported in #1362

**Comment by AndreyChechel** [comment]
[1375] IgnoreCase inline option is supported 922e270614c7ab1ace30ec0cb78a028ab90b2ab7
