### ISSUE TITLE
Static variable declaration in Bridge doesn't work the same as .Net

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1390]
### Steps To Reproduce

https://deck.net/91435c1daec30a033bbedc12338ca7a5

```c#
public class App
{
    private static int b = a;
    private static int a = 5;

    static void Main(string[] args) 
    {
        // Expected: 0
        Console.WriteLine(b);
    }
}
```

### Expected
https://dotnetfiddle.net/satTuA
```
0
```

### Actual

```
5
```

### See Also
* https://forums.bridge.net/forum/bridge-net-pro/bugs/4062-initializers-for-static-member-not-called-as-expected

**Comment by LeonidVeriga** [comment]
@michaelcheers, yes, that is interesting. Thank you for reporting.
We reproduced the issue and will fix.

**Comment by geoffreymcgill** [comment]
Unfortunately, this functionality is not easy to implement. We will have to try and fix in a future release.

**Comment by vladsch** [comment]
### See Also
https://forums.bridge.net/forum/bridge-net-pro/bugs/4062-initializers-for-static-member-not-called-as-expected

**Comment by geoffreymcgill** [comment]
A PR has been submitted with a fix for this issue. After testing, the PR will be merged into the **master** branch.
