### ISSUE TITLE
Support for Convert class

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#14]
http://forums.bridge.net/forum/general/feature-requests/728
Related to https://github.com/bridgedotnet/Bridge/issues/97
https://msdn.microsoft.com/en-us/library/system.convert(v=vs.110).aspx
https://github.com/bridgedotnet/Bridge2/issues/39

**Comment by DaniilVeriga** [comment]
I guess the [3377b33](https://github.com/bridgedotnet/Bridge/commit/3377b33051a8b4ed746319210fd02951c25c8ab9) commit has been referenced here by mistake. The commit probably closed bridgedotnet/Builder#14.

**Comment by geoffreymcgill** [comment]
```
public static short ToInt16(object value)
public static short ToInt32(object value)
public static double ToDouble(decimal value)
public static decimal ToDecimal(double value)
public static DateTime ToDateTime(object value)
public static string ToString(decimal value, IFormatProvider provider)
public static string ToString(double value, IFormatProvider provider)
```

**Comment by AndreyChechel** [comment]
While implementing the Convert class, I've found that IConvertible interface is not supported. Created a separate issue #822

**Comment by geoffreymcgill** [comment]
Hi @AndreyChechel: At our team meeting today we discussed this feature request and were going to investigate later this week. If you're working on this, link us to your branch and we'll provide some input.

**Comment by AndreyChechel** [comment]
Hi @geoffreymcgill, nice to hear that you are going to handle this issue soon. It's maybe a bit early to share my code as only several methods have been implemented (you can check the code in Convert.cs and Convert.js files):
https://github.com/AndreyChechel/Bridge/tree/Issue14

The last things I've been thinking about are Convert.ToInt64/ToUInt64 methods - they can't be fully implemented as there is no native support of such data types in javascript (there is also the issue #778 about Long type). I personally think it'd better to have these method implemented than not, however, when the converting value is greater that Number.MAX_SAFE_INTEGER I would throw an OverflowException.

**Comment by AndreyChechel** [comment]
Hi team,
`Convert` class is almost done, i.e. there are some methods which can't be implemented at the moment as they require `IConvertible` interface. This could be handled in the nearest future.

What I'd like to do is to cover all these methods with Unit tests to be sure that all of them are correct. However, `master` branch contains not working Unit testing project, and this prevents me from verifying the implemented functionality.

As you guys work on 1.11, the question for you is - do you want to include `Convert` in this release without tests? (in this case I'll provide the tests afterwards, once Unit testing project is fixed). Feel free to check the code, your comments will be much appreciated!
https://github.com/AndreyChechel/Bridge/tree/Issue14

**Comment by LeonidVeriga** [comment]
Hi @AndreyChechel,

Thansk for your time and contribution. The code changes in your branch look great and we are looking forward to include it into our repository.

Yes, we are in a process of enhancing or testing approach. Sorry for the inconvenience. And a good thing is that you can write usual NUnit tests, run them in .Net Framework environment, put in a pull request and... it will be working with no changes (or just with small changes). It also a good approach to get right expected values as **.Net** and **Bridge** results should be the same (at least ideally).

Here is a code snippet you could use 
```
using System;

using NUnit.Framework;

namespace Bridge.ClientTest
{
    [TestFixture]
    public class ConvertTests
    {
        [Test]
        public void FromStringToBooleanWorks()
        {
            Assert.AreEqual(Convert.ToBoolean("false"), false, "\"false\" ToBoolean");
            Assert.AreEqual(Convert.ToBoolean("False"), false, "\"False\" ToBoolean");
            Assert.AreEqual(Convert.ToBoolean("true"), true, "\"true\" ToBoolean");
            Assert.AreEqual(Convert.ToBoolean("True"), true, "\"True\" ToBoolean");

            Assert.Throws<FormatException>(() => { Convert.ToBoolean("some"); }, "\"some\" throws");
            Assert.Throws<FormatException>(() => { Convert.ToBoolean("0"); }, "\"0\" throws");
            Assert.Throws<FormatException>(() => { Convert.ToBoolean("1"); }, "\"1\" throws");
        }
    }
}
```

**Comment by LeonidVeriga** [comment]
There is also **corefx** project on GitHub with **.Net Framework** tests available in `XUnit` format that might be helpful for reference
https://github.com/dotnet/corefx/tree/ac67ffac987d0c27236c4a6cf1255c2bcbc7fe7d/src/System.Runtime.Extensions/tests/System

**Comment by AndreyChechel** [comment]
Hi @LeonidVeriga,
Thanks a lot for the provided example and the reference to .Net Framework unit tests! I'll get back to you once I have these tests implemented.

**Comment by LeonidVeriga** [comment]
@AndreyChechel , thank you for the contribution. It is a huge chunk of code, all well done with 1800+ tests. Amazing!

**Comment by AndreyChechel** [comment]
My pleasure. Do you think we need a separate issue for the rest methods that I listed [here](https://github.com/bridgedotnet/Bridge/pull/973#issue-133988218)?

**Comment by LeonidVeriga** [comment]
@AndreyChechel 

https://github.com/bridgedotnet/Bridge/issues/14#issuecomment-184786684

Yes, I think so. Please link this issue as well.
