### ISSUE TITLE
Code clean up with extern

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#1404]
Review the code to make all `[External]` classes use `extern`.

### Expected
```CSharp
public static extern implicit operator Any<T1, T2, T3, T4>(T1 t);
```

### Actual
```CSharp
public static implicit operator Any<T1, T2, T3, T4>(T1 t)
{
    return null;
}
```

**Comment by michaelcheers** [comment]
This was done for the Bridge Project in [Pull Request](https://github.com/bridgedotnet/Bridge/pull/1369/commits/00e2d642cb6c627a76f36d3419c91a29ed96fc97) but not for Bridge.Html5 and others.

**Comment by LeonidVeriga** [comment]
Hi @michaelcheers,

Yes, I'm working on PR #1369 and created this issue for tracking purposes.

**Comment by LeonidVeriga** [comment]
Due to C#6 features used in the chages (for example, auto-prop with getter only) the Bridge solution compiles in VS2015 only:
```CSharp
public string Name { get; }
```

See https://github.com/dotnet/roslyn/issues/6251 for details

**Comment by michaelcheers** [comment]
@LeonidVeriga, it is not fully complete.

For example, https://github.com/bridgedotnet/Bridge/blob/master/Html5/DOMImplementation.cs#L10

**Comment by michaelcheers** [comment]
@LeonidVeriga, I suggest that it throws a compiler exception if a function with a body is found in an external class as it can be confusing or reduce code quality.
