### ISSUE TITLE
The Ready attribute doesn't work inside generic classes.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1406]
### Expected

Hello World

### Steps To Reproduce
[Live Bridge](http://live.bridge.net/#2d49156feb345aec542bbea79a08a5b9)
```csharp
/// <summary>
/// Creates a simple class
/// </summary>
public class App<T>
{
    // Use the [Ready] attribute to automatically
    // run this method when the page is ready.
    [Ready]
    public static void Main()
    {
        Console.WriteLine("Hello World");
    }
}
```

**Comment by vladsch** [comment]
No, it should not work in generic classes. We have to throw an exception for such case. To access to static member of generic class we have to provide generic argument, like App<object>. Bridge cannot automatically add such argument

**Comment by LeonidVeriga** [comment]
We will throw a compilation error if a generic class' method marked with `[Ready]`.

.Net for `static Main` methods in generic classes shows warning `CS0402 'Program<T>.Main()': an entry point cannot be generic or in a generic type`. Autorun methods should not apply generics as well.
