### ISSUE TITLE
When using typed arrays, an initializer isn't a typed array.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1408]
This issue is about when using typed arrays not about normal circumstances, it is not the same as #1347 (fourth checkbox).
This is not about gettype it's about the type generated by arrays with typed arrays on.
It says:

``` javascript
[1,2,3]
```

not

``` javascript
new Uint8Array([1,2,3])
```
### Expected

```
System.Byte[] (or Uint8Array maybe)
```
### Actual

Array
### Steps To Reproduce

``` csharp
public class App
{
    [Ready]
    public static void Main()
    {
         byte[] array = new byte[]{1, 2, 3};
         Console.WriteLine(array.GetType().FullName);
    }
}
```

**Comment by michaelcheers** [comment]
Is this planning to be fixed?

**Comment by LeonidVeriga** [comment]
The sample https://deck.net/cf59233ddf3230461da042a132c53618 works in Bridge **16.0** - returning `System.Byte[]`
