### ISSUE TITLE
Support for Web Audio API

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#1413]
https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API

Couldn't find any issues mentioning this and it's quite a big thing :)

**Comment by LeonidVeriga** [comment]
Thanks for a feature request, @TriEdgeAI .
Yes, that is a nice and useful thing. There is a related feature request #1299.

We are marking this as `up-for-grabs` for the time being.

**Comment by TriEdgeAI** [comment]
The Web Audio API is part of Saltarelle and since you guys are about to merge them at some point, does that make working on this issue redundant or is it part of the merging process?
I am asking because in-house we've written some stubs for the Audio API and was wondering if it would be helpful if we made a pull-request with what we have or maybe finish them up and then make a pull-request?

**Comment by geoffreymcgill** [comment]
Hi @TriEdgeAI,

Our goal is to integrate the whole Generated project from SaltarelleWeb into Bridge.Html5. 

https://github.com/Saltarelle/SaltarelleWeb/tree/master/Web/Generated

This currently has not been done, but we expect to start within the next few weeks. Shouldn't take long after we start.

**Comment by geoffreymcgill** [comment]
Moving to 16.0 milestone.

**Comment by TriEdgeAI** [comment]
Should this be Bridge.Html5.WebAudio or part of Bridge.Html5?

**Comment by geoffreymcgill** [comment]
We're working on a new project that will provide complete coverage of the **Web Audio API**. Something to test should be available soon(ish).

**Comment by TriEdgeAI** [comment]
Nice!

**Comment by geoffreymcgill** [comment]
The **Web Audio API** is now included in the [Retyped.dom](https://retyped.com) package.

**Comment by Chamberlain91** [comment]
I am unable to find said Web Audi API on Retyped.dom now.
