### ISSUE TITLE
Properties with setter or getter implementation and [FieldProperty] should not compile 

### ISSUE THREAD

**Issue by kcudnik** [bridgedotnet/Bridge#1424]
### Expected

Compiler Error

### Actual

undefined

### Steps To Reproduce

[Live Bridge](http://live.bridge.net/#d1d87fbbb9e1e70b0bc4deb6055ef0ae)
```csharp
public class App
{
    [Ready]
    public static void Main()
    {
        var a = new A();
        
        Console.WriteLine(a.K); // undefined, should print 0 (not 7, see desc)
    }
    
    public class A
    {
        // compiler should fail to compile code where property is 
        // marked as FieldProperty and have implementation of setter
        // and getter, because they will not be used as intended
        [FieldProperty]
        public int K
        {
            get { return 7; } 
            set {}
        }
    }
}
```

**Comment by LeonidVeriga** [comment]
@kcudnik, yes, thank you for this suggestion. It makes sense and we will implement it in `1.14` release.

**Comment by kcudnik** [comment]
Thanks for adding this feature!

**Comment by TriEdgeAI** [comment]
Maybe generate a warning instead, so it wouldn't be a breaking change?

**Comment by LeonidVeriga** [comment]
Thanks for the [suggestion](https://github.com/bridgedotnet/Bridge/issues/1424#issuecomment-223103363) @TriEdgeAI. It makes sense to avoid breaking change. However, Bridge can be used through Console so that warnings can be missed. I think in this case we should throw an exception.

**Comment by LeonidVeriga** [comment]
Implementation details:
- If property has `[FieldPropery]` attribute but has a getter/setter implementation then the Compiler throws error like `[Property TestApp.A.K] is marked with [FieldProperty] attribute but implements getter and setter. To fix the problem either remove [FieldProperty] (swith off bridge.json option `autoPropertyToField`) or add [External]/[Template] attributes`;
- The same thing when bridge.json option `autoPropertyToField` turned on.

**Comment by kcudnik** [comment]
Thanks for addressing this issue!
