### ISSUE TITLE
JSON.Parse<SomeType[]>(jsonText) returns array of plain JS objects instead of Bridge class

### ISSUE THREAD

**Issue by d-p-y** [bridgedotnet/Bridge#1432]
### Expected

JSON.Parse<SomeType[]>(jsonText) should return array of SomeType instances.

```csharp
Deserialized with JSON.Parse<Foo[]>():
    I'm Demo.Foo and my value is 100
```

### Actual

It returns array of plain JS objects. Its properties are copied but without 'Bridge.merge()'-ing it with proper SomeType class instance.

```csharp
Deserialized with JSON.Parse<Foo[]>():
    result[0].someMethod is not a function
```

### Steps To Reproduce

http://deck.net/253736f96c7ddacdbe0c95fcf1383196

``` csharp
public class Foo
{
    public int Value { get; set; }

    public string SomeMethod()
    {
        return "I'm " + this.GetType().FullName + " and my value is " + this.Value;
    }
}

public class App
{
    public static void Main()
    {
        var serialized = JSON.Stringify(new[] { new Foo() { Value = 100 } });

        Console.WriteLine("Deserialized with JSON.Parse<Foo[]>():");
        var result = JSON.Parse<Foo[]>(serialized);
        TestFooInstance(result);
    }

    public static void TestFooInstance(Foo[] result)
    {
        try
        {
            Console.WriteLine("\t" + result[0].SomeMethod());
        }
        catch (Exception ex)
        {
            Console.WriteLine("\t" + ex);
        }
    }
}
```

To work around the issue, use `JSON.Parse<SomeType[]>(jsonText)` (see #1438) that returns array of  Bridge class instances.

**Comment by TriEdgeAI** [comment]
I can provide an implementation for JSON.Parse that will take care of all kinds of trees of objects when those are closed:

https://github.com/bridgedotnet/Bridge/issues/2056
https://github.com/bridgedotnet/Bridge/issues/2055
https://github.com/bridgedotnet/Bridge/issues/2052
https://github.com/bridgedotnet/Bridge/issues/2051
https://github.com/bridgedotnet/Bridge/issues/2050
https://github.com/bridgedotnet/Bridge/issues/2049
https://github.com/bridgedotnet/Bridge/issues/2043

**Comment by LeonidVeriga** [comment]
Use `Bridge.JSON.Serialize` and `Bridge.JSON.Deserialize`. See #2418 for more information.
