### ISSUE TITLE
Support C#6 features

### ISSUE THREAD

**Issue by ljw1004** [bridgedotnet/Bridge#1435]
### Expected

* It should emit method definitions like `int f() => 3` that have expression-bodies. (at the moment they're not emitted at all, so invocations of them result in a JS error that the method f doesn't exist).

* It should likewise emit expression-bodied properties like `int q => 3`. (at the moment they're again not emitted at all).

* It should handle the `?.` operator. At the moment `?.` is emitted identically to `.`, so the code `string s=null; int? len = s?.Length` causes a JS null reference exception.

* It should handle string interpolation `$"..."` the same as String.Format, since that's what string interpolation compiles down to. (unless it's target-typed to something that is or implements IFormattableString). At the moment, interpolated strings are silently ignored.

### Actual

* Expression-bodied methods and functions aren't being emitted. I haven't tested expression-bodied operators but I bet they're the same.

* The `?.` operator isn't being handled.

* All interpolated strings are silently ignored.

### Steps To Reproduce

Install the VSIX. Do File>New>C#>Bridge.NET>ClassLibrary and use the following source code
```csharp
namespace ClassLibrary1
{
    public class App
    {
        [Bridge.Html5.Ready]
        public static void Main()
        {
            string s0 = null;
            string s1 = "hello";
            int? len0 = s0?.Length;
            int? len1 = s1?.Length;
            string s2 = $"f={f()}";
            string s3 = string.Format("f={0} p={1} q={2} len0={3} len1={4}", f(), p, q,len0,len1);
            string s4 = f().ToString();
            System.Console.WriteLine(s1 + s2 + s3 + s4);
        }

        static int f() => 3;
        static int p { get; } = 4;
        static int q => 5;
    }
}
```
Build it.

**Comment by geoffreymcgill** [comment]
Hi @ljw1004 - Thanks for the great sample. We have all this C#6 functionality working, and it will be released after Bridge 1.14.

We copied your sample into our demo project, and the following js code block shows the compiled output. The browsers Console output is below that. 

**Compiled JS**

```js
(function (globals) {
    "use strict";

    Bridge.define('Demo.App', {
        statics: {
            config: {
                properties: {
                    p: 4
                },
                init: function () {
                    Bridge.ready(this.main);
                }
            },
            getq: function () {
                return 5;
            },
            main: function () {
                var s0 = null;
                var s1 = "hello";
                var len0 = s0 != null ? s0.length : null;
                var len1 = s1 != null ? s1.length : null;
                var s2 = Bridge.String.format("f={0}", Demo.App.f());
                var s3 = Bridge.String.format("f={0} p={1} q={2} len0={3} len1={4}", Demo.App.f(), Demo.App.getp(), Demo.App.getq(), len0, len1);
                var s4 = Demo.App.f().toString();
                console.log(s1 + s2 + s3 + s4);
            },
            f: function () {
                return 3;
            }
        }
    });

    Bridge.init();
})(this);
```

**Console Output**

```js
hellof=3f=3 p=4 q=5 len0= len1=53
```

We'll keep this thread open, and close once the functionality has been added to the **master** branch, after the 1.14 release.

Hope this helps.
