### ISSUE TITLE
Uint (s) are equal to int (s).

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1440]
### Expected

False
### Actual

true
### Steps To Reproduce

[Live Bridge](http://live.bridge.net/#8fc7090bdff67b7c6cf8308c0451a122)
[Dot Net Fiddle](https://dotnetfiddle.net/DMWKQW)

``` csharp
/// <summary>
/// Creates a simple class
/// </summary>
public class App
{
    // Use the [Ready] attribute to automatically
    // run this method when the page is ready.
    [Ready]
    public static void Main()
    {
        Console.WriteLine(3.Equals(3u));
    }
}
```

**Comment by LeonidVeriga** [comment]
Related #1301, #1347

**Comment by vladsch** [comment]
Fixed in https://github.com/bridgedotnet/Bridge/issues/2343
