### ISSUE TITLE
Multiple namespaces confuses Bridge

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1441]
### Expected
```
Hello World
```
### Actual

(empty)

### Steps To Reproduce
[Live Bridge](http://live.bridge.net/#cbd0dde7063a8bdc73a0cbf0244d4dfc)
[Dot Net Fiddle](https://dotnetfiddle.net/tEXEly)
```csharp
using Bridge.Html5;
using System;

namespace A
{
    public class ClassB
    {
        
    }
}

namespace B
{
    public class App
    {
        [Ready]
        public static void Main()
        {
            Console.WriteLine("Hello World");
        }
    }
}
```

**Comment by kcudnik** [comment]
Live Bridge probably don't support multiple namespaces, if you remove A then result is as expected, also when compiling in mono with both namespaces.

**Comment by michaelcheers** [comment]
I have the same error in Visual Studio 2015.

**Comment by geoffreymcgill** [comment]
Live Bridge is now combining the .js files into one. The default is to create a separate .js file for each unique namespace. 

http://live.bridge.net/#cbd0dde7063a8bdc73a0cbf0244d4dfc

The following setting was added to the projects **bridge.json**.

```json
"combineScripts": true,
```
