### ISSUE TITLE
Add support for HTML5 WeakMap

### ISSUE THREAD

**Issue by d-p-y** [bridgedotnet/Bridge#1443]
### Expected
It should be possible to use HTML5 WeakMap. It would be nice to have typesafe wrapper around it.

### Actual
Support for this feature is currently missing

### Steps To Reproduce
grepping for weakmap in sources of Bridge yields no result

**Comment by geoffreymcgill** [comment]
Thank for the submission. We will discuss this Issue today.

For reference:

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/WeakMap
