### ISSUE TITLE
[HOWTO] Getting a clean clone of bridge building on a build server [Incomplete]

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#1452]
I thought there was a page on the site about building Bridge ourselves, but I can't find it and our original setup broke a while back with some changes you made. I'm opening this to try and gather info on what needs to be done to build Bridge from a checkout of the repo (all scriptable from a clean checkout; we don't want to maintain a repo with modifications).

I understand there are things that won't currently work (like tests), but I want to see how far we can get. We thing it's really important we're able to switch to nightlies for testing bug fixes and to continue work while waiting for an official release.

I'll add comments to this case as we progress, and try to edit everything into this initial comment so it's in one place for others (and maybe it can become a page on the website/wiki/whatever once it all works).

```
# Clone both repos for Bridge and the Frameworks
git clone https://github.com/bridgedotnet/Bridge
git clone https://github.com/bridgedotnet/Frameworks


pushd Bridge

# Build bridge
nuget restore
msbuild /t:"Bridge\Bridge;Bridge\Bridge_Html5" /p:Configuration=Release /v:q

# Collect NuGets together
pushd .build\packages
.\collect.bat
popd

# TODO: Copy NuGet packages so they can be used by the Frameworks solution
# TODO: Do we need to update any references in Frameworks to make sure we use the packages built above?

popd
pushd Frameworks

# Build Frameworks
nuget restore Frameworks
msbuild /p:Configuration=Release /v:q
popd

# Collect NuGets again (this is all)
pushd Bridge\.build\packages
.\collect.bat
popd

# TODO: Publish all NuGets to local feed
```

**Comment by DanTup** [comment]
Nuget restore will return errors due to missing packages (`Bridge.Collections.Dev`, `Bridge.Testing`) so need to discard error exit codes. `Frameworks` seems to rely on packages that are built by the `Bridge` project so will need to be built at the end.

I presume your internal build is building `Bridge` and stashing the packages in an internal feed before restoring/building `Frameworks`?

```
nuget restore Bridge

### ???

nuget restore Frameworks

```

**Comment by DanTup** [comment]
Calling msbuild will try to build all projects (including the test projects which are missing packages) so we need to pass the projects we're interested in. To complicate things, dots need to be replaced with underscores for msbuild!

```
pushd Bridge
msbuild /t:Bridge\Bridge;Bridge\Bridge_Html5 /p:Configuration=Release
popd

pushd Frameworks
msbuild /p:Configuration=Release
popd
```

**Comment by DanTup** [comment]
`collect.bat` seems to need to be run from inside its own folder:

```
pushd .build\packages
.\collect.bat
popd
```

**Comment by DanTup** [comment]
Things I'm still not sure about:

1. How are version numbers handled? Can we just stamp into `Bridge\.build\common\CommonAssemblyInfo.cs` or is it more complicated?
2. Do we need to update something in `Frameworks` to use the version numbers generated from `Bridge`?

**Comment by geoffreymcgill** [comment]
Hi @DanTup, 

Within the Bridge repo, all the assemblies use the same version number from **CommonAssemblyInfo.cs**. That one version number is applied to all projects in the Bridge repo. 

Within the Framework repo, each project will have a unique version number, set within **AssemblyInfo.cs**.

**Collect.bat** is just a simple utility we run to collect all the **.nupkg** in one location. This makes it easier for testing as you can set a local package source within NuGet.

If you compile any of the projects in **Release** mode, the **.nupkg** should be generated and added to the **/bin/Release/** folder of each project. **Collect.bat** copies all those **.nupkg** files into one common folder.

Yes, the **Bridge/Tests** project(s) should be excluded for now. Those projects require a private **Bridge.Testing** package. That package will will be available very soon. For now you'll need to exclude the projects from the Solution.

I'll have to check what happening with **Bridge.Collections.Dev**.

Hope this helps.

**Comment by DanTup** [comment]
Thanks for the info. I found my issue with the version numbers - I wasn't replacing `AssemblyInformationalVersion` (our buildserver does this, so I wasn't manually inspecting the file).

I think I've practically got the Bridge project working now; just frameworks to work on (I guess this is complicated because I'll need to update the NuGet version numbers to match those I just built). I'll try update the top of this issue once I've get everything working.

**Comment by geoffreymcgill** [comment]
Closing this issue, but can be re-opened in the future if there's a defect. 

For anyone interested in manually building from source, the following wiki doc should help, see
https://github.com/bridgedotnet/Bridge/wiki/Build-From-Source

**Comment by DanTup** [comment]
No worries. Is it possible for us to run the tests now or does that still require private packages? There are a few little things I'd raised that I thought I could have a go at fixing and sending a PR, but I'd feel more comfortable making changes if I was able to add/run the tests.
