### ISSUE TITLE
Console.WriteLine of long as object gives incorrect value.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1458]
### Expected

1

### Actual

→System.Int64

### Steps To Reproduce
[Live Bridge](http://live.bridge.net/#a944f9622239a0926587b12eb2ffc248)
[Dot Net Fiddle](https://dotnetfiddle.net/yEaAoG)
```csharp		
public class Program
{
	public static void Main()
	{
		object v = 1l;
		Console.WriteLine(v);
	}
}
```

**Comment by LeonidVeriga** [comment]
Related #1457

**Comment by LeonidVeriga** [comment]
Added Client (not Compiler as mistankenly stated in the commit message b035989) test for the case.
