### ISSUE TITLE
Anonymous type names incorrectly repeated - causing property mismatches

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#1461]
http://forums.bridge.net/forum/bridge-net-pro/bugs/2386-anonymous-type-names-incorrectly-repeated-causing-property-mismatches-1-14

Scope for anonymous types should be private variable like for lambda functions to avoid conflicts from anonymous types from other assemblies

**Comment by LeonidVeriga** [comment]
Related to #1341
