### ISSUE TITLE
Unable to find version '1.0.0' of package 'Bridge.Testing'

### ISSUE THREAD

**Issue by trelston** [bridgedotnet/Bridge#1464]
### Expected
A buiild success

### Actual
NuGet Package restore failed for project Tests\Batch2: Unable to find version '1.0.0' of package 'Bridge.Testing'.
  https://api.nuget.org/v3/index.json: Package 'Bridge.Testing.1.0.0' is not found on source 'https://api.nuget.org/v3/index.json'.

NuGet Package restore failed for project Tests\Batch1: Unable to find version '1.0.0' of package 'Bridge.Testing'.
  https://api.nuget.org/v3/index.json: Package 'Bridge.Testing.1.0.0' is not found on source 'https://api.nuget.org/v3/index.json'.

NuGet Package restore failed for project Tests\Batch1: Unable to find version '1.3.0' of package 'Bridge.Collections.Dev'.
  https://api.nuget.org/v3/index.json: Package 'Bridge.Collections.Dev.1.3.0' is not found on source 'https://api.nuget.org/v3/index.json'.

### Steps To Reproduce
Well i'm not sure if this is a general issue or just an issue with my system and i am not even sure if this is the right place to raise this issue. However, I downloaded the latest source code and after i try to build i get the above 3 errors. It seems that the build can't find the nuget packages "Bridge.Testing" and "Bridge.Collections.Dev". I did some searching myself and could not find them on Nuget.

**Comment by michaelcheers** [comment]
@trelston, this is a known issue.

**Comment by trelston** [comment]
OK fine. I just thought maybe I was facing an issue. Should  just exclude those files and move along? We can then close this issue.

**Comment by michaelcheers** [comment]
@trelston, Unload the project as suggested [here](https://github.com/bridgedotnet/Bridge/pull/1369/#issuecomment-219686737).

**Comment by LeonidVeriga** [comment]
Hi @trelston,

Yes, as @michaelcheers said, `Bridge.Testing` is a private package and will be released soon.
More details can be found here #1452.

**Comment by LeonidVeriga** [comment]
We are closing the issue. If you have any related questions please feel free to reopen.
