### ISSUE TITLE
Weird template (s) when static

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1466]
### Expected

7

### Actual
```
Uncaught TypeError: Cannot read property 'App' of undefined
```
### Steps To Reproduce
[Live Bridge](http://live.bridge.net/#79911bfe633c0cbbb2ce99d364d1a8d4)
```csharp
/// <summary>
/// Creates a simple class
/// </summary>
public class App
{
    [Template("Demo.App.int()")]
    public extern int Yes ();
    
    public static int Int (){return 7;}
    
    public static void Main()
    {
        new App().Yes();
    }
}
```

**Comment by vladsch** [comment]
It is not bug. For non static members, target is rendered always (if there is no {this} in a template)
In your case, to avoid target just add `&lt;self&gt;` prefix
```
[Template("<self>Demo.App.int()")]
```

**Comment by LeonidVeriga** [comment]
[Liva Bridge](http://live.bridge.net/#f46f95f5a8bbd163f4eec14f7855cf6f) sample with `<self>`

**Comment by LeonidVeriga** [comment]
We updated [Attribute Reference](http://bridge.net/kb/attribute-reference/#Template) with info on `<self>`
