### ISSUE TITLE
Concat returns array not typed IEnumerable<string>

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1468]
### Expected

```
h
h
```

### Actual

```
C# Compilation Failed

Microsoft (R) Visual C# Compiler version 4.0.30319.34209

(8,37): error CS0029: Cannot implicitly convert type 'System.Array'
to 'System.Collections.Generic.IEnumerable<string>'

```
### Steps To Reproduce

http://live.bridge.net/#d8178a7b2a0383d7d389053606f84672
https://dotnetfiddle.net/E1OTje

``` csharp
public class App
{
    public static void Main()
    {
        IEnumerable<string> array = new[] {"h"}.Concat(new[] {"h"});
        foreach (var item in array)
        {
            Console.WriteLine(item);
        }
    }
}
```

## See Also

- https://forums.bridge.net/forum/bridge-net-pro/bugs/6009-toarray-broken-on-some-ienumerables

**Comment by LeonidVeriga** [comment]
Thank you for reporting this issue, @michaelcheers.

**Comment by vladsch** [comment]
You mentioned extension method Concat. The problem that Bridge array contains own Concat method.
If you want to use extension method then define generic type explicitly
`IEnumerable<string> array = new[] { "h" }.Concat<string>(new[] { "h" });`

**Comment by LeonidVeriga** [comment]
@vladsch, the code provided [here](https://github.com/bridgedotnet/Bridge/issues/1468#issue-159500623) compiles fine in VS/ Probably we need to remove array's `concat`?

**Comment by vladsch** [comment]
### See Also
https://forums.bridge.net/forum/bridge-net-pro/bugs/6009-toarray-broken-on-some-ienumerables

**Comment by fabriciomurta** [comment]
The fix submitted to this looks good, and we adapted some very old code to comply to it. This fix will make it to the next Bridge release, in accordance with the assigned milestone to this issue.
