### ISSUE TITLE
NullReferenceException in Bridge.Contract.EmitterException.get_FileName() when using string interpolation

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#1469]
This might be my fault - I've taken an existing WinForms app and I'm trying to convert it to Bridge. Raising it here in case a) it's not my fault or b) it is my fault in case others have the same issue and the details are useful.

I'm using the latest versions of `Bridge` and `Bridge.Collections`:

```
<package id="Bridge.Collections" version="1.3.1" targetFramework="net461" />
<package id="Bridge.Core" version="1.14.0" targetFramework="net461" />
<package id="Bridge.Html5" version="1.14.0" targetFramework="net461" />
<package id="Bridge.Min" version="1.14.0" targetFramework="net461" />
```

### Expected

Build to either succeed, or report build errors.

### Actual

Build crashes:
```
1>------ Rebuild All started: Project: DaChip8JS, Configuration: Debug Any CPU ------
1>  DaChip8JS -> M:\Coding\Applications\DaChip8JS\DaChip8JS\bin\Debug\DaChip8JS.dll
1>M:\Coding\Applications\DaChip8JS\packages\Bridge.Min.1.14.0\build\Bridge.Min.targets(12,5): error MSB4018: The "GenerateScript" task failed unexpectedly.
1>M:\Coding\Applications\DaChip8JS\packages\Bridge.Min.1.14.0\build\Bridge.Min.targets(12,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object.
1>M:\Coding\Applications\DaChip8JS\packages\Bridge.Min.1.14.0\build\Bridge.Min.targets(12,5): error MSB4018:    at Bridge.Contract.EmitterException.get_FileName()
1>M:\Coding\Applications\DaChip8JS\packages\Bridge.Min.1.14.0\build\Bridge.Min.targets(12,5): error MSB4018:    at Bridge.Build.GenerateScript.Execute()
1>M:\Coding\Applications\DaChip8JS\packages\Bridge.Min.1.14.0\build\Bridge.Min.targets(12,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>M:\Coding\Applications\DaChip8JS\packages\Bridge.Min.1.14.0\build\Bridge.Min.targets(12,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

There's build output on AppVeyor if it's useful:

https://ci.appveyor.com/project/DanTup/dachip8js/build/1.0.3

### Steps To Reproduce

Not sure of the cause yet, but it can be repro'd with this revision of my repo..

```
git clone https://github.com/DanTup/DaChip8JS
cd DaChip8JS
git reset --hard 25015d0b42d7588fea993a86a1151e3dbc47beec
nuget restore
msbuild
```

I'm trying to work through it... will update this issue with anything I discover.

**Comment by DanTup** [comment]
Ok, this turned out to be quite simple to reproduce:

```
var s = $"{0}";
```

I was using string interpolation in my desktop version. I'm aware this isn't yet supported.

If this works fine in the Roslyn version there's probably not much value in trying to improve this message. I'll leave this issue open for you to make the call, it won't bother me if you just close!

**Comment by LeonidVeriga** [comment]
Hi @DanTup! Thanks for narrowing it down.

Yes, string interpolation will be supported in 1.15, as well as the other C# 6 features.

However, there is something to fix in this issue - it should not fail in this way to show `task failed unexpectedly.` We will fix this.

**Comment by LeonidVeriga** [comment]
Related #1435

**Comment by LeonidVeriga** [comment]
Hi @DanTup,

It was a good case to check - a classic case of failing at catching exception.
