### ISSUE TITLE
Expression-bodied-functions silently don't compile

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#1470]
I can't actually repro this with a small sample on live.bridge.net (seems to give a compile error!?) but it's happening in the project I'm converting. Again, I don't know if you'll care too much about this if it's already fixed in an upcoming major version (I don't, it's easy enough for me to fix) but I thought I should provide the info for you to decide.

You can build with:

```
git clone https://github.com/DanTup/DaChip8JS
cd DaChip8JS
git reset --hard 021e611891f24e29c5de76252b2641be5784669d
nuget restore
msbuild
```

Then open `DaChip8JS/Html/Index.html`.

It fails because `this.jump` in the `Chip8` class is undefined:

![Error with expression-bodied-members](https://cloud.githubusercontent.com/assets/1078012/15972198/f5ea3e4a-2f34-11e6-869c-de35add8d7a8.png)

Many others are the same (but others work). The only difference I can see is that Jump (and the other missing ones) are expression-bodied-members. Eg, `ClearOrReturn` works but `Jump` is undefined.

```
/// <summary>
/// Handles 0x0... which either clears the screen or returns from a subroutine.
/// </summary>
void ClearOrReturn(OpCodeData data)
{
	// ...
}

/// <summary>
/// Jumps to location nnn.
/// </summary>
void Jump(OpCodeData data) => PC = data.NNN;
```

**Comment by vladsch** [comment]
Expression-bodied functions is part of C# 6
Current Bridge projects must be compiled with C# 5
Easy way to catch such errors to set Language version in the project to C# 5, in this case compilation will fail for C# 6 statements (NRefactory cannot catch all syntax problems therefore we assume that if msbuild compilation is fine then all syntax is correct)

All C# 6 features will be supported since 1.15

**Comment by DanTup** [comment]
> Easy way to catch such errors to set Language version in the project to C# 5

Wow, I didn't even know there was a way to do this! :D

For anyone else reading, it's in the Advanced section under build ([see here](http://www.codeproject.com/Tips/865579/How-to-change-targeted-Csharp-version-in-Visual-St)) (+cc @ProductiveRage).
