### ISSUE TITLE
Is there a better way to get a byte[] from an XmlHttpRequest?

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#1471]
I'm fetching a binary file using `XmlHttpRequest` and need to convert it to a C# `byte[]`. I'm passing it to code I wish to share with real C# so I can't just use the `Uint8Array` directly (though I can use it for converting).

Current code looks like this (which works):

```csharp
static void BeginLoadRom(string rom)
{
	var req = new XMLHttpRequest();
	req.ResponseType = XMLHttpRequestResponseType.ArrayBuffer;
	req.Open("GET", rom);
	req.OnLoad = e => EndLoadRom(ConvertToByteArray(req.Response as ArrayBuffer));
	req.Send();
}

static byte[] ConvertToByteArray(ArrayBuffer buffer)
{
	var data = new Uint8Array(buffer);
	var dataBytes = new byte[data.Length];
	for (var i = 0; i < data.Length; i++)
		dataBytes[i] = data[i];
	return dataBytes;
}
```

Although this works, the ConvertToByteArray looks a bit sucky. I'm creating a new `byte[]` then literally just copying the data into it (there isn't even a cast!). Generated JS looks like this:

```
var data = new Uint8Array(buffer);
var dataBytes = System.Array.init(data.length, 0);
for (var i = 0; i < data.length; i = (i + 1) | 0) {
	dataBytes[i] = data[i];
}
return dataBytes;
```

Two questions:

1. Can I simplify the C# at all? (even if the JS is output the same)
2. Can the output JS be any better? I guess a `Uint8Array` is really just the same as a C# `byte[]`?

**Comment by michaelcheers** [comment]
@DanTup, there is an option for typed arrays  and you can use as. Eg.
```csharp
uInt8Array.As<byte[]>()
```

**Comment by DanTup** [comment]
Excellent, that's much cleaner. Thanks! :-)

```
// ...
req.OnLoad = e => EndLoadRom(GetResponseAsByteArray(req));
// ...

static byte[] GetResponseAsByteArray(XMLHttpRequest req)
{
	return new Uint8Array(req.Response as ArrayBuffer).As<byte[]>();
}
```

**Comment by michaelcheers** [comment]
@DanTup, another option is to use Array.from.
```csharp
[Template("Array.from({value})")]
public static extern byte[] ArrayFrom (Uint8Array value);
```

or if you care about browser support
```csharp
[Template("[].slice.call({value})")]
public static extern byte[] ArrayFrom (Uint8Array value);
```
and use:
```csharp
ArrayFrom(uInt8Array);
```
if you don't want to use typed arrays internally.
