### ISSUE TITLE
Any sample code or build app for ios?

### ISSUE THREAD

**Issue by nvcken** [bridgedotnet/Bridge#1478]

**Comment by fabriciomurta** [comment]
Hello @nvcken!

We don't have an current bridge sample as far as I know, but you shouldn't have much of a problem drawing something in regards to it! Here's a link to a forum thread where we discussed an IOS app with XCode (OS/X) on an early Bridge version: [Using Bridge.Net in iOS Xcode](http://forums.bridge.net/forum/community/help/363).

I believe this can provide you with meaningful insight for drawing your Bridge + IOS application.

**Comment by nvcken** [comment]
okay, thanks @fabriciomurta
