### ISSUE TITLE
HTMLColor is missing colors.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1481]
**List of colors missing:** 

1. Magenta
2. RebeccaPurple
3. Cyan
4. LightGrey
5. DimGrey
6. DarkSlateGrey

**Comment by LeonidVeriga** [comment]
Thanks for narrowing this down, @michaelcheers

**Comment by geoffreymcgill** [comment]
A Pull Request (#1779) has been submitted to fix this issue. The pr will be merged into Bridge 15.0.

@michaelcheers Thanks for pointing out the issue and making the list.
