### ISSUE TITLE
Bring back Console class to Bridge namespace

### ISSUE THREAD

**Issue by kcudnik** [bridgedotnet/Bridge#1483]
Please bring back Console class which contains Log,Info,Warn,Debug,Error methods as in javascript console

**Comment by geoffreymcgill** [comment]
The old **Console** class and members have been moved to the **Bridge.Console** project in the Frameworks repo.

https://github.com/bridgedotnet/Frameworks/tree/master/Console

You can install using NuGet with the following command:

```
install-package bridge.console
```

Hope this helps.

**Comment by kcudnik** [comment]
Ahh missed that, thanks!
