### ISSUE TITLE
Performance problems with constructors

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#1485]
We are developing a project which translates existing Unity games, written in C# to JavaScript and 2D canvas. Previously we were using Saltarelle, but we decided to move on to Bridge.NET, because of the acquisition and all. However once we started testing we saw very low framerates in the resulting builds and we decided to go back to Saltarelle just to see what's going to happen. That increased the framerate 5 to 10 times in all games. After some analysis we discovered that Saltarelle generates much simpler constructors than Bridge.NET and that might be one of the main issues for the way lower performance with Bridge.NET.

Take for example the following test case:

```csharp
public class App
{
    public struct Vector3
    {
        public float x;
        public float y;
        public float z;
        
        public Vector3(float x, float y, float z)
        {
            this.x = x;
            this.y = y;
            this.z = z;
        }
        
        public static Vector3 operator+(Vector3 a, Vector3 b)
        {
            return new Vector3(a.x + b.x, a.y + b.y, a.z + b.z);
        }
    }
    
    public static void Main()
    {
        DateTime start = DateTime.Now;
        
        Vector3 sum = new Vector3(0.0f, 0.0f, 0.0f);
           
        for(int i = 0; i < 1000 * 1000; i++)
        {
            sum += new Vector3(1.0f, 2.0f, 3.0f);
        }
        
        DateTime end = DateTime.Now;
        
        Console.Write((end - start).TotalMilliseconds);
    }
}
```

The generated constructor by Bridge.NET would be:
```javascript
function Class() {
    if (!(this instanceof Class)) {
        var args = Array.prototype.slice.call(arguments, 0),
            object = Object.create(Class.prototype),
            result = Class.apply(object, args);

        return typeof result === "object" ? result : object;
    }

    // All construction is actually done in the init method
    if (!initializing) {
        if (this.$staticInit) {
            this.$staticInit();
        }

        if (this.$initMembers) {
            this.$initMembers.apply(this, arguments);
        }

        this.$$initCtor.apply(this, arguments);
    }
}
```

which involves multiple branches, string operations and so on, while Saltarelle simply generates:

```javascript
$App$Vector3.$ctor1 = function(x, y, z) {
	this.x = 0;
	this.y = 0;
	this.z = 0;
	this.x = x;
	this.y = y;
	this.z = z;
};
```

And here are the average benchmark results for the above snippet on Chrome on my Acer Aspire V3-772G laptop:
Bridge.NET: ~55,000 ms
Saltarelle: ~26 ms

Are you guys perhaps going to consider changing the way objects are constructed with Bridge.NET? I apologize if submitting this issue sounds like a complaint, but it is a major roadblock for moving from Saltarelle to Bridge.NET.

**Comment by vladsch** [comment]
Thanks for report that issue. We will investigate it and try to improve performance before next release

**Comment by geoffreymcgill** [comment]
We will take a close look at this and discuss in detail at our team meeting today.

**Comment by TriEdgeAI** [comment]
Thanks! I appreciate you considering this a lot :)

**Comment by vladsch** [comment]
We found the problem and working on fix. By the way, small tip - apply `[Immutable]` attribute for Vector3 struct to prevent clone of structure when it is passed to overload + operator. It should improve performance also. When the fix will be merged with master branch we will notify you

**Comment by geoffreymcgill** [comment]
Hi @TriEdgeAI, 

We did a quick review and found a couple trouble spots that were easy to fix. We made a local performance test and went from 20 seconds down to 400 milliseconds with the changes. 

We continue to work on the problem and we should be able to squeeze out much better performance still.

These optimizations from today will hit the **master** branch soon.

Thanks for bringing this performance issue to our attention.

**Comment by vladsch** [comment]
By the way, you can mark all fields asreadonly, in this case Bridge will consider that structure like immutable automatically

**Comment by TriEdgeAI** [comment]
Oh, wow, awesome! Much love for you, guys!
@vladsch Possible, but in actuality even though I am not making direct access to the members of the Vector3 in the example above, in actual code the struct should be mutable. :)

**Comment by geoffreymcgill** [comment]
Hi @TriEdgeAI,

Another quick update. We were able to find some more optimizations and now the performance should be excellent. 

Our previous big 20 second test is now finishing in 30 milliseconds. This new code should hit the **master** branch soon.

**Comment by LeonidVeriga** [comment]
@TriEdgeAI, we improved performance and merged the changes into `master` branch.
It would be great if you could check out the changes and give us your feedback.

Instance creation time reduced (a sample creating 10^6 struct instances [Live Bridge](http://live.bridge.net/#4d88e43a28f95fdb1cedb7f22f10ce7d)) - apprx 80ms now vs 20s (250 times faster); marking struct with `[Immutable]` gives apprx 40ms vs 19s (500 times faster).
 
Concomitant changes:
 - Class constructor naming `constructor$1` -> `$constructor1`
 - Constructor call syntax `new Demo.App("constructor", ...)` -> `new Demo.App.$constructor(...)`
 - Each constructor has the following code in the beginning `this.$initialize();`

**Comment by TriEdgeAI** [comment]
I'll run some tests as soon as I give feedback :)
