### ISSUE TITLE
Using (s) break Bridge Live

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1494]
### Expected
Compile fine.

### Actual

C# to JavaScript Compilation Failed

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Bridge.Contract.BridgeTypes.GetNamespaceFilename(ITypeInfo typeInfo, IEmitter emitter)
   at Bridge.Translator.TypeScript.EmitBlock.GetOutputForType(ITypeInfo typeInfo)
   at Bridge.Translator.TypeScript.EmitBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.Emit()
   at Bridge.Translator.Translator.Translate()
   at Live.LiveTranslator.Translate(String& output)
   at Live.TranslateHandler.Translate(String csCode)
```

### Steps To Reproduce

[Live Bridge](http://live.bridge.net/#83035807f2036307f2e410063bf3fc33)

```csharp
using System;

/// <summary>
/// Creates a simple class
/// </summary>
public class App
{
    public static void Main()
    {
    }
}
```

**Comment by geoffreymcgill** [comment]
Live Bridge is looking for the code sample to start with either of two scenarios:

1. Starts with a `using` statement => then assumes any following classes are properly wrapped in a `namespace` by the author.
2. Does not start with a `using` statement => wraps everything in a default namespace template before sending to the compiler. 

With the scenario you presented, the compiler sees a `using` statement, therefore does not wrap in a namespace template. Without the namespace, the compiler is throwing an error. 

Simple work-around is to either remove the `using` statement, or wrap the class in a namespace. 

**Example**

```C#
using System;

namespace Demo
{
	/// <summary>
	/// Creates a simple class
	/// </summary>
	public class App
	{
	    public static void Main()
	    {
	    }
	}	
}
```

More logic checks could be added to the template checks in Live Bridge to enable this scenario. The Exception in this scenario is not a weakness of the Bridge compiler, only Live Bridge.
