### ISSUE TITLE
Fullscreen API

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#1495]
I noticed iframes have IsFullscreenAllowed, but the rest of the Fullscreen API is missing.
Maybe it would be nice to have:
https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

**Comment by michaelcheers** [comment]
[1497](Pull Screen)

**Comment by TriEdgeAI** [comment]
Missing msRequestFullscreen I think?

**Comment by michaelcheers** [comment]
@TriEdgeAI, Added.

**Comment by TriEdgeAI** [comment]
There may be other ms- methods. I haven't checked for a full list of them.

**Comment by michaelcheers** [comment]
@TriEdgeAI, Added all ms- overloads.

**Comment by geoffreymcgill** [comment]
Moving to 16.0 milestone.

**Comment by geoffreymcgill** [comment]
The **Fullscreen API** is now available in the [Retyped.dom](https://retyped.com) package.
