### ISSUE TITLE
Add VB.NET and F# support.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1498]
I would like it if Bridge would work with VB.NET and F#. It doesn't seem that hard to me, you could just decompile the .NET code compiled in that language.

**Comment by geoffreymcgill** [comment]
We do not decompile IL. We [now] use Roslyn to parse the source code.

Ultimately, we will support the languages that are supported by Roslyn. Currently that only includes C#.

**Comment by geoffreymcgill** [comment]
Well, apparently Roslyn does support VB.NET. 

https://github.com/dotnet/roslyn/wiki/Getting-Started-VB-Syntax-Analysis

I did not know. I will keep this in mind.

**Comment by michaelcheers** [comment]
@geoffreymcgill, I think you have misunderstood, you could compile the VB.NET/F# and decompile to C# and then parse that.

**Comment by geoffreymcgill** [comment]
We'll do some experimentation.

**Comment by hardhub** [comment]
I think issue should be opened because it is not solve yet.

https://github.com/bridgedotnet/Bridge/wiki/other-languages

**Comment by geoffreymcgill** [comment]
@hardhub – We will not be supporting VB.NET or F# or decompiling IL. If we re-architect Bridge, there is a chance these could be supported but that would be way off in the future.

**Comment by hardhub** [comment]
> 
> 
> @hardhub – We will not be supporting VB.NET or F# or decompiling IL. If we re-architect Bridge, there is a chance these could be supported but that would be way off in the future.

OK, not a problem. Finally C# will have features like nested interfaces (or something similar).

But probably you need to update information in Bridge.Net wiki.

> Currently Bridge only supports C#.
> In the future we do plan to support compilation from other languages, such as VB.NET and F#.
