### ISSUE TITLE
Use || for ?? operator when not using strict equals.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1499]
### Expected

```javascript
var app = null;
System.Console.log(app || new Demo.App());
```

### Actual

```javascript
var $t;
var app = null;
System.Console.log(($t = app, $t != null ? $t : new Demo.App()));
```

### Steps To Reproduce

```csharp
public class App
{
    public static void Main()
    {
        App app = null;
        Console.WriteLine(app ?? new App());
    }
}
```

PS. On your steps to reproduce in the example when you press "New Issue" it adds a [Ready] attribute to Main.

**Comment by kcudnik** [comment]
Operator || may have different meaning when strict null compare will be set in bridge.json options file.

**Comment by michaelcheers** [comment]
@kcudnik, I mean only when not using strict equals.

**Comment by geoffreymcgill** [comment]
> PS. On your steps to reproduce in the example when you press "New Issue" it adds a [Ready] attribute to Main.

Thanks for the reminder. I have removed from the .github ISSUE_TEMPLATE.
https://github.com/bridgedotnet/Bridge/commit/0477876b7f04eb01f9d975cacead183adbd996f9

**Comment by vladsch** [comment]
|| operator cannot be used for object, like
```csharp
object o1 = "";
object o2 = "test";
var r = o1 ?? o2;
```
if use || then r variable will contain "test" instead ""
Also nullable integer with 0 value also will be compared incorrectly if use ||
