### ISSUE TITLE
Performance.now should be a double not an int?

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#1509]
[Performance.now](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now) is supposed to return a [DOMHighResTimeStamp](https://developer.mozilla.org/en-US/docs/Web/API/DOMHighResTimeStamp):

> The Performance.now() method returns a DOMHighResTimeStamp, measured in milliseconds, accurate to one thousandth of a millisecond.
> 
> The DOMHighResTimeStamp type is a double and is used to store a time value. 

In Bridge it's returned as an `int` which means it's always in milliseconds and trying to measure sub-millisecond code will effectively result in a 0. Performance tuning Bridge code is complicated so I think having the full precision of this value would be really useful.

(I know I can call the code lots of times, but for something like a loop being controlled by `requestAnimationFrame` that's slightly more complicated)

**Comment by LeonidVeriga** [comment]
@DanTup,
Yes, it should be double. Thank you for reporting.

**Comment by fabriciomurta** [comment]
At least firefox 60+ is now returning a number in 1ms steps, so we shouldn't expect it to be a double/float anymore, at least in that browser.

Currently MDN docs states this from firefox in this page: https://developer.mozilla.org/en-US/docs/Web/API/Performance/now

_"The timestamp is not actually high-resolution. To mitigate security threats such as Spectre, browsers currently round the results to varying degrees. (Firefox started rounding to 1 millisecond in Firefox 60.) Some browsers may also slightly randomize the timestamp. The precision may improve again in future releases; browser developers are still investigating these timing attacks and how best to mitigate them."_

So, until browser implementations consistently rely on this, we can't be sure the returned value is necessarily a floating-point one.

Unit tests updated to reflect this change (and ignore failure when the browser is firefox) via commit b1e34bc2cf52c7998e9e815da33c06d47e3e16ec.
