### ISSUE TITLE
DecoratorAttribute(s)

### ISSUE THREAD

**Issue by danieldegtyarev** [bridgedotnet/Bridge#1515]
I propose to add DecorateAttribute(s) to immitate ES6 decorators. 
I think it can be implemented like in TypeScript. See http://blog.wolksoftware.com/decorators-reflection-javascript-typescript

Here, my suggestion about implementation.
We need ClassDecoratorAttribute, PropertyDecoratorAttribute, MethodDecoratorAttribute, ParameterDecoratorAttribute. Each attribute should have a method to override. To declare decorator, user should derive from an attribute and override this method

```csharp
public class LogAttribute : MethodDecoratorAttribute
{
    public override void Decorate(Type type, MethodInfo /*?*/ method)
    {
        Console.WriteLine("Decorator for " + type.Name + "." + method);
    }
}

public class Foo
{
    [Log]
    public void Bar(int n)
    {
          return n * 2;
    }
}
```

**Comment by geoffreymcgill** [comment]
Is this basically an Aspect?

In the C# sample you provided, what would be the expected result? and sequence? 

For example, if you instantiate a `Foo` class, and call `Bar` Method, would you expect the app to Console.WriteLine before or after the call to `Bar`?

**Comment by danieldegtyarev** [comment]
After some time I dont feel that it is a good idea, atleast until ES6/7 decorators standard is ready.
Sorry for the mess, lets close this issue for now

**Comment by geoffreymcgill** [comment]
With the next release of Bridge, you'll be able to write the following:

http://live.bridge.net/#0667b7b377d302cd183c35608261a520

```c#
using System;
using Bridge.Aspect;

namespace Demo
{
    public class App
    {
        public static void Main()
        {
            var foo = new Foo();
            foo.Bar(5);
        }
    }
    
    public class Foo
    {
        [Log]
        public void Bar(int n)
        {
            Console.WriteLine(n * 2);
        }
    }

    public class LogAttribute : MethodAspectAttribute
    {
        public override void OnEntry(MethodAspectEventArgs args)
        {
            // Write to logging system here
            Console.WriteLine("Log: Before {0}", args.MethodName);
        }
        
        public override void OnExit(MethodAspectEventArgs args)
        {
            // Write to logging system here
            Console.WriteLine("Log: After {0}", args.MethodName);
        }
    }
}
```

**Comment by danieldegtyarev** [comment]
This is really cool!
Question, as I understand it will be invoked by each method invokation, it is cool. However I need also OnInitialize or something like that to invoke some code only one time during method / property / field / parameter declaration.

**Comment by vladsch** [comment]
There is `bool RunTimeValidate(string methodName, object scope)` in`MethodAspectAttribute`
You can run own logic there (init logic also) and return false if aspect should not be applied for a method

**Comment by danieldegtyarev** [comment]
That is what I need. Could you, please, add RunTimeValidate in the other *AspectAttributes?

**Comment by vladsch** [comment]
RunTimeValidate is presented in all aspects (just with different set of arguments)

**Comment by danieldegtyarev** [comment]
So nice, looking forward to the next release.

**Comment by geoffreymcgill** [comment]
Here's sample demonstrating use of `RuntimeValidate`.

http://live.bridge.net/#0e088eab2f4ae03ff951fb35aa5cc58c

```c#
using System;
using Bridge.Aspect;

namespace Demo
{
    public class App
    {
        public static void Main()
        {
            new Foo().Bar(5);
            
        }
    }
    
    public class Foo
    {
        [Log]
        public void Bar(int n)
        {
            Console.WriteLine(this.Factor * n);
        }
        
        public int Factor = 2;
    }

    public class LogAttribute : MethodAspectAttribute
    {
        protected override bool RunTimeValidate(string methodName, object scope)
        {
            Console.WriteLine("MethodName: " + methodName);
            Console.WriteLine("Factor: " + ((Foo)scope).Factor);
            
            return true;
        }
        
        public override void OnEntry(MethodAspectEventArgs args)
        {
            // Write to logging system here
            Console.WriteLine("Log: Before {0}", args.MethodName);
        }
        
        public override void OnExit(MethodAspectEventArgs args)
        {
            // Write to logging system here
            Console.WriteLine("Log: After {0}", args.MethodName);
        }
    }
}
```
