### ISSUE TITLE
Document.Body should return an HTMLBodyElement

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1516]
### Expected

Compile fine.

### Actual

Doesn't compile fine.

### Steps To Reproduce
[Live Bridge](http://live.bridge.net/#e4e8609ea2230953b3730d2348671939)
```csharp
/// <summary>
/// Creates a simple class
/// </summary>
public class App
{
    public static void Main()
    {
        HTMLBodyElement body = Document.Body;
    }
}
```

**Comment by LeonidVeriga** [comment]
Right, @michaelcheers, it should be `HTMLBodyElement `. Thanks for reporting.

**Comment by geoffreymcgill** [comment]
When fixing this issue I also discovered the **Document.DocumentElement** property is returning the wrong type. See issue #1771.
