### ISSUE TITLE
Decimal field incorrect initialization

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#1520]
Reported on the forum http://forums.bridge.net/forum/bridge-net-pro/bugs/1273

### Expected

`12`

### Actual
`TypeError: item.value.add is not a function`

### Steps To Reproduce
Sampe:
[Bridge Live](http://live.bridge.net/#5f12eba221708c95761c25426661f86e)
[.Net Fiddle](https://dotnetfiddle.net/sAeijQ)
```csharp
public class App
{
    public static void Main()
    {
        decimal newVal = 12;
        CustomList item = new CustomList();
        item.value += newVal;
        Console.WriteLine(item.value);
    }
}

public class CustomList {
    public List<int> ranges = new List<int>();
    public decimal value = 0;
}
```

**Comment by michaelcheers** [comment]
@LeonidVeriga, Pretty much the same as [this issue](1486).

**Comment by LeonidVeriga** [comment]
@michaelcheers, yes, thanks for pointing this out.
