### ISSUE TITLE
System.Decimal.toInt called twice when casting a decimal

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#1523]
Reported on the forum http://forums.bridge.net/forum/bridge-net-pro/bugs/2471

### Expected
Generated JavaScript has one `System.Decimal.toInt`

### Actual
`x = (x + System.Decimal.toInt(System.Decimal.toInt((System.Nullable.getValue(y).mul(System.Decimal(60.0))), System.Int32), System.Int32)) | 0;`

### Steps To Reproduce
Sample ([Bridge Live](http://live.bridge.net/#17f319663e8831b3f57c38946a62b317)):
```csharp
public class App
{
    public static void Main()
    {
        int x = 0;
        decimal? y = 2;
        x += (int)(y.Value * 60m);
    }
}
```

**Comment by michaelcheers** [comment]
Related to #1230.
