### ISSUE TITLE
Can't compile if using const in Script attribute

### ISSUE THREAD

**Issue by caesay** [bridgedotnet/Bridge#1527]
I'd like to use a constant to specify the name of the config variable that is emitted by my html generator but this generates a compilation error.

### Expected
>Build Success

### Actual
>Build Error
Severity	Code	Description	Project	File	Line	Suppression State
Error		Error: Unable to cast object of type 'ICSharpCode.NRefactory.CSharp.BinaryOperatorExpression' to type 'ICSharpCode.NRefactory.CSharp.PrimitiveExpression'.    at Bridge.Translator.Emitter.GetScriptArguments(Attribute attr)
   at Bridge.Translator.Emitter.GetScript(EntityDeclaration method)
   at Bridge.Translator.VisitorMethodBlock.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
   at Bridge.Translator.VisitorMethodBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
   at Bridge.Translator.MethodBlock.EmitMethodsGroup(List`1 group)
   at Bridge.Translator.MethodBlock.EmitMethods(Dictionary`2 methods, Dictionary`2 properties, Dictionary`2 operators)
   at Bridge.Translator.MethodBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.ClassBlock.EmitStaticBlock()
   at Bridge.Translator.ClassBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.EmitBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.Emit()
   at Bridge.Translator.Translator.Translate()
   at Bridge.Build.GenerateScript.Execute()	ClowdSvc.Scripting	C:\Users\Caelan\Source\Repos\clowd-win\ClowdSvc.Scripting\App.cs	26	Active

### Steps To Reproduce
```csharp
public class App
{
    public const string SomeLiteral = "hello";

    [Script("return " + SomeLiteral + ";")]
    public static dynamic GetConfig() { return null; }
}
```

**Comment by LeonidVeriga** [comment]
Hi @caesay,

Thank you for reporting this issue. We reproduced it and will fix.

I would suggest a workaround by using [[Template]](http://bridge.net/kb/attribute-reference/#Template) attribute.
Sample ([Bridge Live](http://live.bridge.net/#1d737b4dfdd6d9fcf8364b1dc4a3258e)):
```
public class App
{
    public const string SomeLiteral = "hello";

    [Template(SomeLiteral)]
    public static extern dynamic GetConfig1();
    
    void CheckGetConfig()
    {
        var d1 = GetConfig1();
    }
}
```

It outputs:
```
checkGetConfig: function () {
    var d1 = hello;
}
```

Please note the sample uses `extern` modifier to avoid specifying `GetConfig` method body in case of using attributes like `[Template]` or `[Script]`.

I would also suggest having a **stronly typed** (instead of `dynamic`) wrapper for your config variable.
The sample uses [[External]](http://bridge.net/kb/attribute-reference/#External) attribute to specify `MyConfig` class has an external implementation and is not emitted by Bridge ([Bridge Live](http://live.bridge.net/#412dec280f2cee8b72c621b69d6d8037)):
```
public class App
{
    void CheckGetConfig()
    {
        // Accessing strongly typed MyField1 through global variable
        var d1 = MyConfig.Instance.MyField1;
        
        // Getting global variable config as local variable
        var cfg = MyConfig.Instance;
        // Accessing strongly typed MyField1 through local variable
        var d2 = cfg.MyField1;
        // Accessing strongly typed MyField2 through local variable
        var d3 = cfg.MyField2;
    }
}

// Strongly typed wrapper
[External]
public class MyConfig
{
    public const string SomeLiteral = "hello";
    
    // Set up accessing a strongly typed global variable
    [Template(MyConfig.SomeLiteral)]
    public static MyConfig Instance;
    
    // Config fields goes here
    public string MyField1;
    public int MyField2;
    
    // No public constructor to force getting its instance through Instance field
    private extern MyConfig();
}
```

It outputs:
```
checkGetConfig: function () {
    // Accessing strongly typed MyField1 through global variable
    var d1 = hello.myField1;

    // Getting global variable config as local variable
    var cfg = hello;
    // Accessing strongly typed MyField1 through local variable
    var d2 = cfg.myField1;
    // Accessing strongly typed MyField2 through local variable
    var d3 = cfg.myField2;
}
```
