### ISSUE TITLE
String's are by default null not ""

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1533]
### Expected

b

### Actual

nullb

### Steps To Reproduce
[Live Bridge](http://live.bridge.net/#0025131317bb2e5d573bd6ac0aa62430)
[Dot Net Fiddle](https://dotnetfiddle.net/PNV6bt)
```csharp
/// <summary>
/// Creates a simple class
/// </summary>
public class App
{
    public static void Main()
    {
		Console.WriteLine(@string += 'b');
    }
	
	static string @string;
}
```

**Comment by geoffreymcgill** [comment]
Thank you for the report. We will investigate and fix.

**Comment by vladsch** [comment]
Default value for string is null (not empty). Just Console.WriteLine shows null as empty string. So, we need to fix console (not string default value)

**Comment by michaelcheers** [comment]
@vladsch, The problem is the + operator: [This Dot Net Fiddle](https://dotnetfiddle.net/eplHTk) shows  that (null + 'b') is b not nullb.
