### ISSUE TITLE
Bridge changes names to lower case, resulting in different behavior than expected.

### ISSUE THREAD

**Issue by skoncewicz** [bridgedotnet/Bridge#1536]
### Expected

method

### Actual

method
event

### Steps To Reproduce

```csharp
    public class App
    {
        public static void Test()
        {
            Console.WriteLine("method");
        }

        public static event EventHandler test;

        public static void Main()
        {
            test += (sender, args) => Console.WriteLine("event");

            Test();
        }
    }
```

**Comment by geoffreymcgill** [comment]
Thanks for the report. We will investigate.

**Comment by geoffreymcgill** [comment]
We reviewed and it is a bug. We will fix.

Here's a Live Bridge sample demonstrating the defective scenario:

http://live.bridge.net/#75c31fb43aff74db0a5b455b7036da9a

Thanks again for reporting.

**Comment by michaelcheers** [comment]
@geoffreymcgill, I have some code which relies on this kind of functionality with properties and interfaces.
[Live Bridge](http://live.bridge.net/#feb79c291c198067c3bff6197b81d911)

**Comment by geoffreymcgill** [comment]
@michaelcheers - We are adding Method support to ObjectLiteral, so you will not need your work-around with the next release.
