### ISSUE TITLE
Setting PriorityAttribute knocks down order of initialization

### ISSUE THREAD

**Issue by danieldegtyarev** [bridgedotnet/Bridge#1537]
### Expected

Classes should be init in order A -> B -> C -> PlaceMeToTheEnd

### Actual

Wrong order A -> **C -> B** -> PlaceMeToTheEnd
And runtime error

### Steps To Reproduce

http://live.bridge.net/#67693ee29fb8af81803ef5fc044a5278

```csharp
[Priority(-100)]
public class PlaceMeToTheEnd{}

public class A{}
public class B : A {}
public class C : B {}

/// <summary>
/// Creates a simple class
/// </summary>
public class App
{
    public static void Main()
    {
    }
}
```

**Comment by geoffreymcgill** [comment]
Thanks for the report and great sample demonstrating how to reproduce. 

We will investigate and fix.
