### ISSUE TITLE
Array - IsAssignableFrom() for collection interfaces

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#1547]
### Steps To Reproduce

```csharp
public class App
{
    public static void Main()
    {
            Assert.True(typeof(IEnumerable<int>).IsAssignableFrom(typeof(int[])));
            Assert.True(typeof(ICollection<int>).IsAssignableFrom(typeof(int[])));
            Assert.True(typeof(IList<int>).IsAssignableFrom(typeof(int[])));
    }
}
```

**Comment by michaelcheers** [comment]
@LeonidVeriga, the title is a bit confusing, it would be probably be clearer as "Array - Array can't be assigned to the collection interfaces when using IsAssignableFrom." #1238, #1527

**Comment by LeonidVeriga** [comment]
- #1575 
- #1597
- #1603

**Comment by LeonidVeriga** [comment]
Hi @michaelcheers, yes, thanks, we have a couple more similar issues so we use now a common name template for such issues `TypeName- IsAssignableFrom()`
