### ISSUE TITLE
1D array does not throw exception when referenced outside its boundaries

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#156]
For C#, when an array is touched outside its allocated area, and exception is thrown, as it could be touching any unexpected memory address.

For JavaScript, this is not true. Accessing an array beyond its boundaries just returns 'null' if that's actually beyond arrays' defined data. Also returns null when the element has not been set (non-contiguous arrays).

```c#
namespace ClassLibrary1
{
    public partial class Class1
    {
        public static int[] MyArray = new int[5];
        public static int[,] My2DArray = new int[5, 5];

        public static void TriggerError()
        {
            Console.WriteLine("Array value outside its bounds is: " + MyArray[10]);
            Console.WriteLine("Next command will trigger an exception, whereas it should just show 'null'.");
            Console.WriteLine("Breaking array outside its bounds is: " + My2DArray[2, 10]);
        }
    }
}
```

Will result in the JS code:

```js
Bridge.define('ClassLibrary1.Class1', {
    statics: {
        config: {
            init: function () {
                this.myArray = new Array(5);
                this.my2DArray = Bridge.Array.create(0, null, 5, 5);
                Bridge.ready(this.triggerError);
            }
        },
        triggerError: function () {
            console.log("Array value outside its bounds is: " + ClassLibrary1.Class1.myArray[10]);
            console.log("Next command will trigger an exception, whereas it should just show 'null'.");
            console.log("Breaking array outside its bounds is: " + ClassLibrary1.Class1.my2DArray.get([2, 10]));
        }
    }
});
```

And an exception will be triggered once the third command on `triggerError` function is executed on the browser. The exception is thrown from Bridge.Array.get(), corresponding to:

```
Bridge.js:4275                     if (indices[i] < 0 || indices[i] >= arr.$s[i]) {
Bridge.js:4276                        throw new Bridge.ArgumentException("Index " + i + " out of range");
BRidge.js:4277                    }
```

A similar exception should be thrown for the myArray invalid access on the code above.

## See Also

* #2466

**Comment by fabriciomurta** [comment]
As per a chat with @vladsch, the 2D array exception is expected. Then, it turns out that the 1D array is the culprit in this case.

**Comment by LeonidVeriga** [comment]
Closed unintentionally by github; reopening.

**Comment by LeonidVeriga** [comment]
Hi @michaelcheers, thanks for providing the fix.

PR #1369 had already been merged, please create a new one. There is a comment [here](https://github.com/bridgedotnet/Bridge/pull/1369#issuecomment-222305153).

I created a [Live](http://live.bridge.net/#2baeb58d051f76e7da7ff18b455d6f9d) example that could help in testing the fix.
