### ISSUE TITLE
ErrorException - Some constructors and properties do not work

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#1564]
**NOTE:** The **ErrorException** class has been removed, see Issue #2383.

### Actual

JS exception thrown.

### Steps To Reproduce

``` csharp
public class App
{
    public static void Main()
    {
        // Run-time exception
        object d = new ErrorException();

        var ex = new ErrorException("Some message");
        Assert.True(ReferenceEquals(ex.Error, err), "Error");
        Assert.AreEqual(ex.Message, "Some message", "Message");
        Assert.AreEqual(ex.StackTrace, err.Stack, "Stack");

        Error err = null;
        var ex1 = new ErrorException("Overridden message", inner);
        Assert.True(ReferenceEquals(ex1.InnerException, inner), "InnerException");
        Assert.True(ReferenceEquals(ex1.Error, err), "Error");
        Assert.AreEqual(ex1.Message, "Overridden message", "Message");
        Assert.AreEqual(ex1.StackTrace, err.Stack, "Stack");
    }
}
```

## See Also

* #2383
* #941

**Comment by geoffreymcgill** [comment]
The `stack` property is a non-standard Vendor-specific extension and will not be supported.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack

> **Non-standard**
> This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

The non-standard optional constructor overloads with `fileName` and `lineNumber` parameters will not be supported.

**Comment by geoffreymcgill** [comment]
Please use [Retyped](https://retyped.com) for access to JavaScript entities.
