### ISSUE TITLE
Script - support for Delete(object, name)

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#1571]
Implement `static void Delete(object value, string name)` to delete object properties.
Consider having return result `bool` to indicate whether an operation successfull.

The current implementaton `static void Delete(object value)` with one parameter generates invalid JS code.
### Steps To Reproduce
https://deck.net/ca4bc6b0974b42809f603f1ae2627476
``` csharp
public class App
{
    public static void Main()
    {
        var c = new object();
        c["i"] = 42;

        Assert.AreEqual(42, c["i"]);
        Script.Delete(c, "i");
        Assert.AreEqual(null, c["i"]);
        Assert.AreEqual(Script.TypeOf(c["i"]), "undefined");
    }
}
```

**Comment by michaelcheers** [comment]
Related to #1573 and #1572.
