### ISSUE TITLE
Script - support In(object, member)

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#1573]
A simplified helper function to check if the specified property is in the specified object.
Implements JavaScript `in` operator [MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/in).

``` csharp
[Template("{member} in {obj}")]
public static extern bool In(object obj, string member);
```

### Steps To Reproduce
https://deck.net/c96d664ba5a9d827f36b9dad9858bd5c
``` csharp
public class App
{
    public void ScriptInWorks()
    {
        var c = new TestType();
        Assert.True(Script.In(c, "i"));
        Assert.False(Script.In(c, "i1"));
    }
    
    public class TestType
    {
        public int i;
    }
}
```

**Comment by michaelcheers** [comment]
Related to #1572 and #1571.
