### ISSUE TITLE
Decimal - Nullable Decimal to Float/Double

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#1579]
### Expected

`System.Decimal.toFloat(System.Nullable.getValue...`
### Actual

`System.Decimal.toFloatSystem.Nullable.getValue...`
`TypeError: Cannot read property 'Nullable' of undefined`
### Steps To Reproduce

``` csharp
public class App
{
    public static void Main()
    {
        decimal? x1 = 0

        Assert.AreEqual((float)(x1 + 10.5m), 10.5);
        Assert.AreEqual((double)(x1 + 10.5m), 10.5);
    }
}
```

**Comment by michaelcheers** [comment]
Related to #1611 and #1634.

**Comment by LeonidVeriga** [comment]
Verified and added test cases.
