### ISSUE TITLE
Bridge.Testing.dll not found, can't build projects

### ISSUE THREAD

**Issue by Meai1** [bridgedotnet/Bridge#1594]
![capture](https://cloud.githubusercontent.com/assets/1112157/17394684/c64ce41e-5a2a-11e6-9e92-5194ab10a940.PNG)

**Comment by LeonidVeriga** [comment]
Hi @Meai1!

The **Bridge/Tests** project(s) should be unloaded for now. Those projects require a private **Bridge.Testing** package. That package will be available very soon. For now you'll need to exclude the projects from the Solution.

**Comment by geoffreymcgill** [comment]
Please use **Bridge.NoTest.sln** to load the Solution without the Testing projects.

See #1718.
