### ISSUE TITLE
LINQ api 

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#16]

**Comment by geoffreymcgill** [comment]
Related forum thread:
http://forums.bridge.net/forum/general/feature-requests/147-better-list-and-array-support

**Comment by geoffreymcgill** [comment]
Bumping up the priority of this functionality.

**Comment by fabriciomurta** [comment]
This is a big development so I believe it would be best to use this as a directory for the several implementation topics required.

Some might prove unable to be implemented on Bridge.NET (for example, maybe SQL queries).

- System.Linq
  - Enumerable class
  - Queryable class
  - ImmutableArrayExtensions class.
- System.Data.Linq
- System.Xml.Linq

**Comment by DaniilVeriga** [comment]
@vladsch added the LINQ support in [this commit](https://github.com/bridgedotnet/Bridge/commit/9eae583ea85ee57820a2c1a07549d051dda85d12).
