### ISSUE TITLE
Script - support Boolean

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#1619]
A helper function to ensure/convert an object is `boolean`:

``` csharp
[Template("!!{o}")]
public static extern bool ToBoolean(object o);
```

### Steps To Reproduce
https://deck.net/df2064334eaa59f41779ec3ecb267684

``` csharp
public void BooleanWorks()
{
    Assert.AreEqual(Script.Boolean(0), false);
    Assert.AreEqual(Script.Boolean(""), false);
    Assert.AreEqual(Script.Boolean("1"), true);
}
```

**Comment by geoffreymcgill** [comment]
In Saltarelle, the method is called `Boolean`.

https://github.com/Saltarelle/SaltarelleCompiler/blob/roslyn/Runtime/CoreLib/Script.cs#L18-L26
