### ISSUE TITLE
Date - support missing client API

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#1624]
[MDN Date](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date)
- [x] [Date.now()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now) `var timeInMs = Date.now();`. 
  Method returns the number of milliseconds elapsed since 1 January 1970 00:00:00 UTC.
- [x] [Date.UTC()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC) `Date.UTC(year, month[, day[, hour[, minute[, second[, millisecond]]]]])`. Method accepts the same parameters as the longest form of the constructor, and returns the number of milliseconds in a Date object since January 1, 1970, 00:00:00, universal time.
- [x] [Date.parse()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse) `Date.parse(dateString)`. Method parses a string representation of a date, and returns the number of milliseconds since January 1, 1970, 00:00:00 UTC or NaN if the string is unrecognised or, in some cases, contains illegal date values (e.g. 2015-02-31).
- [x] [Date.toLocaleDateString()](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString) missing parameterless overload
- [x] [Date.valueOf()](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date/valueOf) `Date` type should have overload returning `number`

**Comment by geoffreymcgill** [comment]
Related to #2366

**Comment by geoffreymcgill** [comment]
Fixed in #2368
