### ISSUE TITLE
Support IReadOnly interfaces - List, Collection, Dictionary

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#1626]
- [x] [IReadOnlyCollection<T>](https://msdn.microsoft.com/en-us/library/hh881542%28v=vs.110%29.aspx), [Reference](https://referencesource.microsoft.com/#mscorlib/system/collections/generic/ireadonlycollection.cs,7103bd3a82c9f352) represents a strongly-typed, read-only collection of elements.
**array []** should implement it.
```
public interface IReadOnlyCollection<out T> : IEnumerable<T>, IEnumerable
```
- [x] [IReadOnlyList<T>](https://msdn.microsoft.com/en-us/library/hh192385%28v=vs.110%29.aspx) , [Reference](https://referencesource.microsoft.com/#mscorlib/system/collections/generic/ireadonlylist.cs,b040fb780bdd59f4) represents a read-only collection of elements that can be accessed by index.
**List<T>**, **ReadOnlyCollection<T>** and **array []** should implement it.

```
public interface IReadOnlyList<out T> : IReadOnlyCollection<T>, IEnumerable<T>, IEnumerable
```
- [x] [IReadOnlyDictionary<TKey, TValue>](https://msdn.microsoft.com/en-us/library/hh136548%28v=vs.110%29.aspx), [Reference](https://referencesource.microsoft.com/#mscorlib/system/collections/generic/ireadonlydictionary.cs,f786bcc5e7b69c7d) represents a generic read-only collection of key/value pairs.
**Dictionary<TKey, TValue>** should implement it.
```
public interface IReadOnlyDictionary<TKey, TValue> : 
                          IReadOnlyCollection<KeyValuePair<TKey, TValue>>,
                          IEnumerable<KeyValuePair<TKey, TValue>>,
                          IEnumerable
```

## See Also

* #1548

**Comment by FlorianHockmann** [comment]
I just searched way too long why I get the error message `Cannot resolve symbol IReadOnlyDictionary` although the `using System.Collections.Generic` worked. So supporting the IReadOnly interfaces would be great and it would also be very helpful to have a list of supported and not (yet) supported data types and interfaces somewhere in the documentation.

**Comment by geoffreymcgill** [comment]
@FlorianHockmann – Could you share a [Deck.NET](https://deck.net) link with a sample demonstrating a simplified scenario that is failing for you? We will investigate implementing **IReadOnlyDictionary<TKey, TValue>**. 

The others have been implemented, but require further testing.

**Comment by FlorianHockmann** [comment]
Sure, in my case I want to provide a `ToDict` function that can be used to get a dictionary representation of the object. This dictionary can then be used to insert the object into a database easily or for example to display the properties of the object in a web interface. Since it doesn't make sense for the user to modify this dictionary I would like to return an **IReadOnlyDictionary**:

https://deck.net/bfd4c6d3cd3f244b583d622677247028
