### ISSUE TITLE
IFormattable - missing ToString (Format method instead)

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#1633]
[MSDN IFormattable Interface](https://msdn.microsoft.com/en-us/library/system.iformattable(v=vs.110).aspx)

### Expected
[MSDN IFormattable.ToString Method (String, IFormatProvider)](https://msdn.microsoft.com/en-us/library/system.iformattable.tostring(v=vs.110).aspx)
```csharp
string ToString(
	string format,
	IFormatProvider formatProvider
)
```

### Actual
```csharp
public string Format(
	string format,
	IFormatProvider formatProvider
)
```

PS Should be addressed along with #1565

**Comment by calcock** [comment]
Hello,
Here are some  interesting facts that may be useful for you, I think this information could be  helpful, read it  here  <http://support.noisecircuit.net/lnskh/4>

Be well, calcock
