### ISSUE TITLE
Converting type definitions from typescript to Bridge

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1643]
I think that this belongs on [the Bridge Forums](http://forums.bridge.net) but I can't find any way of making posts. I have made a tool called [TypeScriptToCS](http://www.github.com/michaelcheers/TypescriptToCS) for Bridge.

**Comment by geoffreymcgill** [comment]
Hi @michaelcheers 

Are you logged into the forums? Top-right:

<img width="356" alt="screenshot 2016-08-09 10 10 39" src="https://cloud.githubusercontent.com/assets/62210/17523943/ab0a20fc-5e19-11e6-8132-3979ff045bbf.png">

Then you should be able to post in the forums. Probably the [Extensions and Plugins](http://forums.bridge.net/forum/general/extensions-and-plugins) forum would be best for this topic:

<img width="467" alt="screenshot 2016-08-09 10 11 05" src="https://cloud.githubusercontent.com/assets/62210/17523974/cce316c0-5e19-11e6-8822-48415a733a4e.png">

Hope this helps.

**Comment by michaelcheers** [comment]
Well, 
![image](https://cloud.githubusercontent.com/assets/10186738/17644670/b2a92d9e-6184-11e6-8781-33b671f76015.png) I can't find that button.

**Comment by geoffreymcgill** [comment]
That is really strange. I'll check a few things.

**Comment by geoffreymcgill** [comment]
Your forum account was waiting for the email confirmation. Maybe the email was trapped by your spam filter. 

I manually approved your account. You should see the button now.

**Comment by michaelcheers** [comment]
@geoffreymcgill, thank you so much.
