### ISSUE TITLE
Portarelle Client Tests moved into Bridge

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#1672]
| Issue     | Description    | PASS | FAIL | Future | Excluded |
| --------|---------|-------|-------|-------|-------|
|  | Supported in **Bridge 15.0** | 14000 |  |  |  |
|  | Supported in **Bridge Frameworks**  (`Queue` and `Stack` classes )| 36 |  |  |  |
|  | Failing tests should pass once all [portarelle](https://github.com/bridgedotnet/Bridge/labels/portarelle) issues have been closed: [Defects](https://github.com/bridgedotnet/Bridge/issues?q=is%3Aopen+label%3Aportarelle+label%3Adefect) (48) / [Features](https://github.com/bridgedotnet/Bridge/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3Aportarelle%20label%3Afeature) (19) |  | 413 |  |  |
| #1626 | IReadOnlyCollection, IReadOnlyList, IReadOnlyDictionary  |  |  | 79 |  |
| #1623 | Lazy |  |  | 22 |  |
| #1625 | HttpUtility |  |  | 12 |  |
| #1631 | [BindToThisParameter] Attribute |  |  | 2 |  |
| #1675 | [CustomInitialization] Attribute |  |  | 14 |  |
| #1670 | JsDictionary. Covered in Bridge by functionality within **Object**. The JsDictionary class is not required in Bridge.  |  |  | 34 |  |
| #1667 | Excluded tests as Not C# API |  |  |  | 138 |
| #1666 | Excluded tests as Not JS API |  |  |  | 193 |
| **Total** | **Original: 14943** | **14036** | **413** | **163** | **331** |

### Additional Comments

Some tests had to be changed because the original expected result of the Test did not match the .NET expected result. Within Bridge, the expected result should match the .NET expected result. Detailed in #1668.

List of revisions made to Portarelle because the tests and functionality being tested do not reflect C# API - #1667.

List of revisions made to Portarelle because the tests and functionality being tested do not reflect JavaScript API - #1666.

**Comment by LeonidVeriga** [comment]
**Portarelle** migrated into Bridge repo and located at [Batch4](https://github.com/bridgedotnet/Bridge/tree/master/Tests/Batch4).
**Batch4** test runner html file located at [portarelle.html](https://github.com/bridgedotnet/Bridge/blob/master/Tests/Runner/portarelle.html).

36 `Queue` and `Stack` tests [moved](https://github.com/bridgedotnet/Frameworks/commit/f4757ea017e1070dfcd07216f0a28867cb38af3d) into **Bridge.Frameworks** repo.

**Comment by LeonidVeriga** [comment]
We are updating the statistics in the issue description as we go and fix the Portarelle issues.
Once all the Portarelle issues are fixed we will merge the Portarelle tests (Batch4) with Batch1 tests.

**Comment by LeonidVeriga** [comment]
Updated 2017-02-13: additional 100+ tests passed https://github.com/bridgedotnet/Bridge/issues?q=is%3Aissue+label%3Aportarelle+milestone%3A16.0+is%3Aclosed

**Comment by LeonidVeriga** [comment]
9 String tests excluded due to non C# API - #2392

**Comment by hardhub** [comment]
How to convert this?

public static JsDictionary<string, BindingHandler> BindingHandlers {
            get {
                return null;
            }
        }

I do not understand how to use Object in that case.

**Comment by LeonidVeriga** [comment]
@hardhub,

Does .Net **Dictionary** work for your case?
```cs
    public static Dictionary<string, BindingHandler> BindingHandlers
    {
        get
        {
            return new Dictionary<string, BindingHandler>();
        }
    }
```

**Comment by hardhub** [comment]
@LeonidVeriga 

Yes it can be a solution...
I tried to rewrite Saltarelle bindings for Knockout. But migration from JsDictionary is never described.
So I just skipped it and left custom Knockout bindings initialization for JS side.

If dictionary will be converted to the following initialization in JS:
```
bindingHelpers.someKey1 = myBindingHandler1;
bindingHelpers.someKey2 = myBindingHandler2;
```
where bindingHelpers is dictionary, someKey is string, and myBindingHandler is BindingHandler class then it is a solution.

**Comment by LeonidVeriga** [comment]
Four bugs fixed: #1554 #1562 #1591 #1596

**Comment by LeonidVeriga** [comment]
#1571 implemented

**Comment by LeonidVeriga** [comment]
#1616, #1617, #1618, #1619, #1572, #1573 implemented

**Comment by LeonidVeriga** [comment]
#1615 fixed

**Comment by LeonidVeriga** [comment]
Passing Saltarelle tests from merged into main test project **Batch1**.
Failing Saltarelle tests remain in **Batch4**: 116 failing assertions (should add a number of tests related to not implemented functionality - see column **Future** [here](https://github.com/bridgedotnet/Bridge/issues/1672#issue-171278872))

**Comment by LeonidVeriga** [comment]
#1569 fixed

**Comment by LeonidVeriga** [comment]
#1592 fixed
