### ISSUE TITLE
Resource embedding config options

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#1680]
Instruct the Bridge Compiler to:
- Control the embedding of resources (what and where).
- Control the extraction of embedded resources.
- Specifying the output of file types (`*.d.ts` and `*.js`) and exact file names in a certain order- `files` setting.
- Combine the items above into one file with a given `name`. `name` setting can have `#` symbol to specify assembly name the resource name should be applied to: `"3rdPartyAssembly#script.js"`
- Provide header and footer; A header can be specified either in a special `header` setting (path to a file or string content) or as a first item within `files`; if a footer required then it can be last item in `files`.
- Specify a `remark` for each file. Rendered to the top of each file. 
- Exclude existing resources (for example, locales).
- Specify if the composed resources are to be saved as a file  - `extract` setting.
- Specify in output path should be changed (`resources.output` setting).
- Existing config option related to output/resources [injectScriptToAssembly](http://bridge.net/kb/global-configuration/#injectScriptToAssembly) will be moved into `reflection` section and renamed to `inject`.
- If no `resources` section specified then the default behaviour is to inject all the output files as Embedded Resources.

**Example**

```js
{
    "resources": [{
            // A default section (a section with no name setting)
            // Should be one per all resources
            // Values defined here will be applied to all resources (if not overridden)

            // Inject the resource into the Assembly
            // as an Embedded Resource. Default is true.
            "inject": true|false,

            // Specifies if a line will be inserted before each file
            // Supports tokens:
            //     {name}
            //     {path}
            //     \n
            // Default is null
            "remark": "// source @{name}\n"
        }, {
            // The resource name
            "name": "bridge.js",
            
            // A string with a header content 
            // or a path to a file with header content
            // Supports tokens (data taken from assembly vresion): 
            //     {version}
            //     {date}
            //     {year}
            //     {author}
            //     {copyright}
            "header":  "../header.txt"
            
            // The resource will be written as a file as well. 
            // Default is true
            // A combination of name + extract (false) + no files
            // means the Embedded Resource is not extracted
            "extract": true|false,

            // If output location should be different
            // than the bridge.json output setting.
            // Works with extract: true setting
            // I.e. providing a way to control the path 
            // the embedded resources being emitted
            "output": "Resources/final",

            // The files to combine
            // A combination of name + files + inject (true)
            // means to compose files into and inject as Embedded resources.
            "files": [
                  "../Resources/misc/header.js",
                  "file1.js",
                  "subfolder/release.*.js", // use file mask if required
                  "end.js",
                  "finally.js"
            ]
        }, {
            "name": "bridge.d.ts",
            "files": [
                "../Resources/.typescript/bridge.d.ts"
            ]
        }
    ]
}
```
 
Required for #1677.

**Comment by LeonidVeriga** [comment]
@vladsch 
It looks like an extention for the **list** file functionality
```
bridge.js:Bridge.Resources.bridge.js+bridge.d.ts:Bridge.Resources.bridge.d.ts
```
We can also stick with the **list** file approach. **bridge.json** approach looks more consistent to me.

**Comment by vladsch** [comment]
list file is just map for compiler which resources was injected to assembly, it is not instruction what should be injected.
list is generated by compiler automatically and will be used to extract resources in bridge application if the assembly is used as reference
Currently, Bridge project doesn't generate any files therefore list file was created manually

So, bridge.json is not replacement for list. It is additional functionality to declare what resources should be injected. After that list will be generated with injected files names

**Comment by LeonidVeriga** [comment]
Reminder: check a case when two referenced projects hase embedded resources with the same name.
