### ISSUE TITLE
Console.WriteLine reflection not working

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1686]
### Expected
[Dot Net Fiddle](https://dotnetfiddle.net/Tb4fR6)
Hello

### Actual
[Live Deck](http://deck.net/54609471de5c560412ae46b1c6096b6c)
Uncaught TypeError: Cannot convert undefined or null to object

### Steps To Reproduce
```csharp
public class App
{
    public static void Main()
    {
        typeof(System.Console).GetMethod("WriteLine", new[]{typeof(string)}).Invoke(null, new[]{"Hello"});
    }
}
```

**Comment by vladsch** [comment]
By default, metadata (reflection info) is rendered for types from current assembly and if type/member has scriptable attributes

To enable metadata for all types from current assembly you can set attribute
`[assembly:Reflectable]`

or in bridge.json
```
"reflection": {
    "enabled": true
  }
```

if you need to support reflection for types from other assemblies then use filter
`[assembly:Reflectable("System.Console")]`
or
`[assembly:Reflectable("System.*")]`
or in bridge.json
```
"reflection": {
    "filter": "System.*"
  }
```

There is one bug which prevent to use reflection for native javascript object like `console` but we will fix it today

**Comment by LeonidVeriga** [comment]
Related to #1698
