### ISSUE TITLE
HtmlTableElement.InsertRow adds row to <head> in Internet Explorer 11

### ISSUE THREAD

**Issue by mRy0** [bridgedotnet/Bridge#1707]
Im using InsertRow to get a reference to TBody, on Internet explorer this throws an exception

### Table Insert

```c#
_tableElement.InsertRow();
//get tbody -> throws exception
_tableBody = _tableElement.TBodies.First();
```

### InnerHtml of TableElement on Chrome
 ```html
<thead></thead><tbody><tr></tr></tbody>
```

### InnerHtml of TableElement on IE 11
```html
<thead><tr></tr></thead>
```

`

**Comment by LeonidVeriga** [comment]
Hi @mRy0,

Can you please provide a code sample demonstrating the issue.
A [Bridge Live](http://live.bridge.net/) example would be great.

**Comment by mRy0** [comment]
http://live.bridge.net/#63e403cf2fd73698de5a109bc5f78d77

**Comment by geoffreymcgill** [comment]
This doesn't seem like it's a problem with Bridge. This appears to be a browser inconsistency with how they implement the JavaScript spec. The compiled code is raw native JavaScript.  

I'm not sure there is much we can do here.
