### ISSUE TITLE
GetEnumerator with preserveMemberCase: true

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#1710]
``` cs
getEnumerator: function (obj, suffix) {
    if (typeof obj === "string") {
        obj = System.String.toCharArray(obj);
    }

    if (suffix && obj && obj["getEnumerator" + suffix]) {
        return obj["getEnumerator" + suffix].call(obj);
    }

    if (obj && obj.getEnumerator) {
        return obj.getEnumerator();
    }

    if ((Object.prototype.toString.call(obj) === "[object Array]") ||
        (obj && Bridge.isDefined(obj.length))) {
        return new Bridge.ArrayEnumerator(obj);
    }

    throw new System.InvalidOperationException("Cannot create enumerator");
}
```

if I set `preserveMemberCase` to `true` in the `bridge.json`, this won't work, because my method will be called `GetEnumerator`.

**Comment by geoffreymcgill** [comment]
Is it failing on this?

```
obj["getEnumerator" + suffix]
```

Can you link us to a [Live Bridge](http://live.bridge.net) sample that demonstrates how to reproduce this issue?

**Comment by TriEdgeAI** [comment]
I can't do it on Live Bridge, because I cannot set `preserveNameCase` to `true` there. It will fail any time you try to use `foreach` on a class that has `GetEnumerator()`, because the above code will be looking for `getEnumerator`.

**Comment by geoffreymcgill** [comment]
Looks like `preserveNameCasing` is already a controversial setting, see:
https://github.com/bridgedotnet/Bridge/issues/1192#issuecomment-210975095

There has been talk of removing that option.

Can you provide some details on why you are using that options, or what requirements?

**Comment by geoffreymcgill** [comment]
In the next release of Bridge, the `nameof` Method is supported. You will be able to do the following:

```cs
public class App
{
    public static void Main()
    {
        var obj = new { Name = "Frank" };
        var prop = nameof(obj.Name);

        Window.Alert(obj[prop].ToString());
    }
}
```

Maybe using `nameof` can help work-around the issue.

**Comment by TriEdgeAI** [comment]
This is my class which has a `GetEnumerator()` method:

```
	public class CookieCollection
	{
		// .... Other methods ....

		public IEnumerator<KeyValuePair<string, string>> GetEnumerator()
		{
			string[] rawPairs = Document.Cookie.Split(';');

			for(int i = 0; i < rawPairs.Length; i++)
			{
				string[] parts = rawPairs[i].Split('=', 2);

				if(parts.Length == 2)
				{
					yield return new KeyValuePair<string, string>(parts[0].Trim(' '), parts[1].Trim(' '));
				}
			}
		}

		//TODO: Delete this method when https://github.com/bridgedotnet/Bridge/issues/1710 is fixed.
		public IEnumerator<KeyValuePair<string, string>> getEnumerator()
		{
			return GetEnumerator();
		}
	}
```

and then the use case is:

```
			foreach(KeyValuePair<string, string> pair in Application.Cookies)
			{
				Console.Write(pair.Key + " = " + pair.Value);
			}
```

`nameof()` would be a very nice addition that I am looking forward to, but it will not help in this case. The JavaScript snippet provided in the description of this issue is from Bridge's JavaScript code, not ours :)

I am using `preserveMemberCasing`, because I really dislike the idea of changing member names. It can lead to a lot of other problems like:
 - How should two methods `doSomething()` and `DoSomething()` be handled?
 - Reflection.
 - Acronyms start to look ugly: `XMLContent` becomes `xMLContent`.
 - etc.

Also I personally prefer C#'s style where all methods and properties are UpperCamelCase. If you are going to remove `preserveMemberCasing`, please preserve it by default. :( What's the point of not preserving it anyways?

**Comment by geoffreymcgill** [comment]
> The JavaScript snippet provided in the description of this issue is from Bridge's JavaScript code, not ours :)

Okay, that makes more sense now.

Ya, I would say this is a defect. We will investigate.

**Comment by TriEdgeAI** [comment]
Here's an important use-case which will fuck up when name case isn't preserved:
We have a solution with 3 projects:
 - Backend: An ASP.NET project
 - Frontend: A Bridge.NET project
 - Shared: A shared project which only contains a few model classes

Example model class:
```csharp
	public class Person
	{
		public int Id
		{
			get;
			set;
		}

		public string Name
		{
			get;
			set;
		}

		public int Age
		{
			get;
			set;
		}
	}
```

The Backend project uses the model classes with the Entity Framework to store/retrieve data to/from the database, serializes it to JSON and sends it in a response to the Frontend project:
```javascript
{
	"Id": 1337,
	"Name": "Vladimir Angelov",
	"Age": 21
}
```

 The Frontend project attempts to perform JSON.Parse() to deserialize the JSON back into the same model class, but it will NOT work, because Bridge.NET changed the casing of the properties and they are now `id`, `name`, `age` instead of `Id`, `Name` and `Age`. :)

**Comment by geoffreymcgill** [comment]
Thanks for the comments regarding ``. I agree with your points. I'll just respond to each of those scenarios in case anyone in the future is wondering how they would be dealt with in Bridge:

> How should two methods doSomething() and DoSomething() be handled?

Bridge will automatically check for member name collisions during compilation. 

For example, given the following C# class:

```cs
public class App
{
    public static void Main()
    {
        var app = new App();

        app.DoSomething();
        app.doSomething();
    }

    public void DoSomething() { }

    public void doSomething() { }
}
```

Bridge will automatically rename in JavaScript as:

```js
app.doSomething$1();
app.doSomething();
```

> Reflection.

If you're using strings to reference names, then yes this could lead to problems. Whether the `preserveMemberCasing` is `true` or `false`, this would still be an issue. Basically this just comes down to deciding on a naming convention policy for the app. 

> Acronyms start to look ugly: XMLContent becomes xMLContent.

Setting `[Name(false)]` on the member will preserve it's case.

**Example ([Live](http://live.bridge.net/#cd9f769f8229fe9a80436ab2b5c8487d))**

```cs
public class App
{
    [Name(false)]
    public string XMLContent;
}
```

**Comment by geoffreymcgill** [comment]
@TriEdgeAI - I'm trying to reproduce your `JSON.Parse` scenario using the following sample, but was unable. Can you revise the sample to demonstrate the serialize/deserialize issue?

**Example ([Live](http://live.bridge.net/#b748fdb050d72b450cba47a4b265a92f))**

``cs
public class App
{
    public static void Main()
    {
        var json = @"{
    ""Id"": 1337,
    ""Name"": ""Vladimir Angelov"",
    ""Age"": 21
}";

        var person = JSON.Parse<Person>(json);

        Window.Alert(person.Name);
    }
}

public class Person
{
    public int Id
    {
        get;
        set;
    }

    public string Name
    {
        get;
        set;
    }

    public int Age
    {
        get;
        set;
    }
}
```

**Comment by TriEdgeAI** [comment]
Ok, my bad. Apparently property names have their casing preserved, unlike fields and methods. An example with member fields really does mess up though:
http://live.bridge.net/#59d061688202e71ecfdb79f248d12ad3

**Comment by geoffreymcgill** [comment]
We're still coming up with a plan to fix this preserveMemberCase scenario. 

We also create a new Feature Issue to extend the functionality of `[Name]` attribute, see #1729.

**Comment by TriEdgeAI** [comment]
Just curious, why implement the whole changing of naming case in the first place? Not trying to force my personal opinion, just curious about what were the considerations that lead to this decision. Is it to be consistent with the default JavaScript API?

**Comment by geoffreymcgill** [comment]
> Is it to be consistent with the default JavaScript API?

Yes. In C#, the api is following expected C# casing conventions. In JavaScript, the api is following expected JavaScript casing conventions. All this should be handled automatically for you by Bridge. 

You should be able to create a JavaScript api that is consumed by JavaScript developers. One of the original goals of Bridge was to write JavaScript that would be exactly what we would write as JavaScript developers. We wanted the .js to look hand crafted, but machine generated.

**Comment by TriEdgeAI** [comment]
I understand. But in this case, should you not make properties lowerCamelCase by default as well?

Array.length, document.cookie, those are definitely properties and not fields, yet they are lowercase in JavaScript.

**Comment by geoffreymcgill** [comment]
> Array.length, document.cookie, those are definitely properties and not fields, yet they are lowercase in JavaScript.

They are compiled to lowerCamelCase in JavaScript and treated with proper UpperCamelCase casing in C#.

The casing of Properties by Bridge for custom classes (example below) currently has more to do how the `setName` and `getName` accessors are generated. In the JSON.Parse scenario discussed in this thread, it just happens to work because the casing of underlying names have not been changed. That's more of a fluke than anything. In retrospect, I don't feel it should have worked. 

At some point we are going to change how the Properties are emitted. We will move away from `setName` and `getName` syntax, and into real JavaScript setters and getters. 

```js
get name () {
},
set name (value) {
}
```

**Comment by geoffreymcgill** [comment]
We are proposing a few changes to the `[ObjectLiteral]` functionality that are related to this thread. See:

[#1754] Do not change member name case if all alpha chars are UPPERCASE
[#1755] New ObjectInitializationMode for ObjectLiteralAttribute
[#1756] Mark DefaultValueMode as Obsolete
[#1757] ObjectLiteral to initialize with default values
[#1758] New ObjectCreateMode for ObjectLiteralAttribute

**Comment by LeonidVeriga** [comment]
[#1754] _Do not change member name case if all alpha chars are UPPERCASE_ - **implemented**

**Comment by geoffreymcgill** [comment]
The `preserveMemberCase` config is being removed in Bridge 16.0.

Please see Issues #2476 and #2477 for further details.
