### ISSUE TITLE
[C#6] Improve overload resolution

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#1713]
http://stackoverflow.com/documentation/c%23/24/c-sharp-6-0-features/505/improved-overload-resolution

Following snippet shows an example of passing a method group (as opposed to a lambda) when a delegate is expected. Overload resolution will now resolve this instead of raising an ambiguous overload error due to the ability of C# 6 to check the return type of the method that was passed.
```cs
using System;
public class Program
{
    public static void Main()
    {
        Overloaded(DoSomething);
    }

    static void Overloaded(Action action)
    {
       Console.WriteLine("overload with action called");
    }

    static void Overloaded(Func<int> function)
    {
       Console.WriteLine("overload with Func<int> called");
    }

    static int DoSomething()
    {
        Console.WriteLine(0);
        return 0;
    }
}
```
Output in C#6:
```
overload with Func<int> called
```

Output in C#5:
```
error CS0121: The call is ambiguous between the following methods or properties: 'Program.Overloaded(System.Action)' and 'Program.Overloaded(System.Func)'
```

C# 6 can also handle well the following case of exact matching for lambda expressions which would have resulted in an error in C# 5.
```cs
using System;

class Program
{
    static void Foo(Func<Func<long>> func) {}
    static void Foo(Func<Func<int>> func) {}

    static void Main()
    {
        Foo(() => () => 7);
    }
}
```

**Comment by LeonidVeriga** [comment]
Related #1435
