### ISSUE TITLE
Bridge project building on Mac + Linux

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#1719]
Get main [Bridge repo](https://github.com/bridgedotnet/Bridge) building on Mac or Linux using VS Code, Mono Develop and/or Xamarin Studio.

**Comment by LeonidVeriga** [comment]
#1482 related

**Comment by geoffreymcgill** [comment]
**Update:** Ran into an issue with generating the NuGet packages automatically. We are trying to fix.

**Comment by LeonidVeriga** [comment]
We fixed the issue.

And now, in addition to CI build on MS .Net ([App Veyor](https://ci.appveyor.com/project/ObjectDotNet/bridge/build/15.0.762-master)), we have CI build on Mono ([Travis](https://travis-ci.org/bridgedotnet/Bridge/builds/157518858)).
