### ISSUE TITLE
Support decimal values and arithmetic

### ISSUE THREAD

**Issue by BalassaMarton** [bridgedotnet/Bridge#172]
I think this would add huge value to Bridge.NET, since it finally enabled web developers to easily create JavaScript code that correctly handles financial operations.
Bridge should support the .NET `Decimal` type. In the JS output, `Decimal` should be a class, and arithmetic and conversion operations in the C# code should map to static functions of the JS class.

So C# code like this:
```cs
var d1 = 0.1m;
var d2 = 0.2m;
var i = 1;
var d3 = d1 + d2 + i;
if (d3 == 1.3m)
    Window.Alert("hooray");
```
should compile to JS as:
```javascript
var d1 = new Bridge.Decimal("0.1");
var d2 = new Bridge.Decimal("0.2");
var i = 1;
var d3 = Bridge.Decimal.add(d1, Bridge.Decimal.add(d2, new Bridge.Decimal(i)));
if (Bridge.Decimal.equals(d3, new Bridge.Decimal("1.3"))
    window.alert("hooray");
```
The `Bridge.Decimal` constructor should create an object that represents a decimal value, converted from an optional parameter, or 0 if undefined. It may be tremendous work to map all the `System.Decimal` methods to `Bridge.Decimal` counterparts, but I think I will contribute to this, if nobody else takes to job.

UPDATE

Looking into the source, I found the `Decimal` class. Unfortunately, it maps to the `"number"` JavaScript type, and so it not only doesn't support decimal arithmetic, but hides potential errors by converting the decimal values to binary floats.

**Comment by geoffreymcgill** [comment]
Yes, we can certainly do some work to improve Decimal support. We're kinda tied up until end of next week, but we can make this a priority after that. Shouldn't be a problem to make work as expected.

**Comment by fabriciomurta** [comment]
We have more people in need of that fix, according to this recent forum post: [Status of support for the decimal data type?](http://forums.bridge.net/forum/general/open-discussions/335)

**Comment by DaniilVeriga** [comment]
JavaScript Decimal libraries that are candidates to be incorporated to Bridge:
https://www.npmjs.com/package/jsdecimal
https://github.com/MikeMcl/decimal.js

**Comment by DaniilVeriga** [comment]
@BalassaMarton, the decimal support has been added to Bridge. Currently, we are testing and most likely it will be included into the next release.

**Comment by geoffreymcgill** [comment]
Decimal support has been added to Bridge 1.8.0

https://github.com/bridgedotnet/Bridge/issues?q=milestone%3A1.8+is%3Aclosed
