### ISSUE TITLE
Have to change case when putting Bridge result on linux server.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1720]
### Expected

Work fine.
### Actual

Have to change case
### Steps To Reproduce

Compiling Bridge program and uploading result to linux server and requesting www/demo,html. I have to change the case of the script tag.

## See Also

* #2757

**Comment by geoffreymcgill** [comment]
Yes, this is an annoying problem with not being able to modify the .pp Template Parameters.

https://github.com/bridgedotnet/Bridge/blob/master/.build/files/demo.html.pp#L8

Maybe there is a way to pull a custom value that is created somehow in [Bridge.targets](https://github.com/bridgedotnet/Bridge/blob/master/.build/targets/Bridge.targets).

@LeonidVeriga  might have some ideas.

**Comment by geoffreymcgill** [comment]
This issue has been solved with the automatic generation of the **index.html** file. Please see Issue #2757 for more information. Also related to Issue #2755.
