### ISSUE TITLE
Support for DOMParser

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#1728]
https://developer.mozilla.org/en/docs/Web/API/DOMParser

**Comment by geoffreymcgill** [comment]
This is probably best implemented as an extension library with it's own NuGet package, such as **Bridge.DOMParser**.

The api is considered __Experimental__ and at this point is part of the draft spec.

**Comment by TriEdgeAI** [comment]
Two questions:
1. What is the equivalent of the "Document" class in JavaScript here? "DocumentInstance"?
2. Does it need to be a separate package since it's only 1 class with 1 method?

**Comment by geoffreymcgill** [comment]
I don't feel this is something that should be part of the main **Bridge.Html5** library. The **DOMParser** class is Experimental, and would not be supported across the platforms we target.

I still feel this should be separate option NuGet Package that developers can choose to integrate into their projects if required. Something like:

```
Install-Package Bridge.Html5.DOMParser
```

It would be interesting to see many of these NuGet packages wrapped up into a **Super Pack** of useful tools and extensions for Bridge.NET. This would be a good project for someone in the community to take on. 

Related to Pull Request: #1734

**Comment by TriEdgeAI** [comment]
Cool. What do you think about Bridge.Html5.Experimental maybe? 'Cuz Bridge.Html5.DOMParser will be a package that contains only 1 class, which contains only 1 method. What's your final say?

**Comment by geoffreymcgill** [comment]
I would still make a **Bridge.Html5.DOMParser** Package. 

Any *Experimental* Package could then just include all the relevant Packages as `<dependencies>`.

I think it would be best for someone to use their own name for the Package, such as **TriEdge.Bridge.Experimental**, or **Acme.Experimental**, or anything. Using **Bridge** as the start of the Nuget Package name is kinda like trying to add something to the **Bridge** namespace, or **Microsoft** namespace. It's best for the developer stay create within their own namesapce.

Hope this helps.

**Comment by geoffreymcgill** [comment]
Seems like Pull Request 1487 is another candidate for an individual NuGet package, and packed into a collection of useful JavaScript api's that are currently not part of the JavaScript spec but still useful to have available. 

https://github.com/bridgedotnet/Bridge/pull/1497

**Comment by TriEdgeAI** [comment]
Can you please provide an example how to contribute a `Bridge.Html5.DOMParser` package to the project, so I can do it. I'll do the `FileReader` and `requestFullscreen` ones as well.

**Comment by geoffreymcgill** [comment]
You should be able to use any of the Bridge.Frameworks projects as a template to get started. 

The **Collections** or **Html5.Console** project would be very similar. 

https://github.com/bridgedotnet/Frameworks/tree/master/Html5.Console

Hope this helps.

**Comment by TriEdgeAI** [comment]
I can't get around to get the Bridge.Frameworks solution to actually build. Is there a guide somewhere on the proper way to do it? Shouldn't it be as easy as opening the solution in Visual Studio and doing Build All?

**Comment by geoffreymcgill** [comment]
If you update your clone of the *Frameworks* repo, and run the *Bridge.Frameworks.sln* file, it should now build without issue. 

Previously, the .sln required the *Bridge.Test* package, which hasn't been publicly released yet. 

Hope this helps.

**Comment by TriEdgeAI** [comment]
How about now?

**Comment by geoffreymcgill** [comment]
We will be including **DOMParser** to **Bridge.Html5** in version 15.8.0. 

Your related pull request for a separate package will be closed, and just the **DOMParser** class will be added directly to **Bridge.Html5**. 

You can create a new pull request to add the **DOMParser** class, or we will just recreate the class based source [Mozilla](https://developer.mozilla.org/en/docs/Web/API/DOMParser) docs.

**Comment by LeonidVeriga** [comment]
More info at https://w3c.github.io/DOM-Parsing/#the-domparser-interface

**Comment by LeonidVeriga** [comment]
Hi @TriEdgeAI,

We added `DOMParser` into **Bridge.Html5**.
It is basically your implementation; we just added `SupportedType` class with string constants containing allowed MIME types https://github.com/bridgedotnet/Bridge/blob/master/Html5/DOMParser.cs#L33

It is currently in **master** branch and wil be released in **15.8.0**.
Thank you for your contribution.

**Comment by TriEdgeAI** [comment]
Nice! Sorry I was too slow with my PR. Glad you added it :) Very appreciated.
