### ISSUE TITLE
GetClassName returns incorrect value for generic subclass

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#1737]
### Expected
Demo.SomethingOfSomethingElse

### Actual
Demo.Something$1[[Demo.SomethingElse, Bridge.$Unknown]]

http://forums.bridge.net/forum/bridge-net-pro/bugs/2613-change-to-getclassname-behaviour
### Steps To Reproduce

```csharp
public class App
{
    public static void Main()
    {
        var x = new SomethingOfSomethingElse();
        Window.Alert(x.GetClassName() + " vs " + Script.Write<string>("x.$$name"));
    }
}

public class Something<T> { }

public class SomethingElse { }

public class SomethingOfSomethingElse : Something<SomethingElse> { }
```

**Comment by LeonidVeriga** [comment]
#1749 - Marking `GetClassName()` as `[Obsolete]` in `Object` and `Type` classes
