### ISSUE TITLE
Incorrect hash code for numbers

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#1741]
### Expected
HashCode should reuse integer number as hash code
Float number should be converted to exponential string and calcukate code for that string

http://forums.bridge.net/forum/bridge-net-pro/bugs/2633-little-bug-i-guess

**Comment by geoffreymcgill** [comment]
Related to forum thread:
http://forums.bridge.net/forum/bridge-net-pro/bugs/2633-little-bug-i-guess
