### ISSUE TITLE
Wrong method invocation with params

### ISSUE THREAD

**Issue by AndreyZM** [bridgedotnet/Bridge#1744]
### Steps To Reproduce
http://live.bridge.net/#e9b68eca5f7643a5ea7e16bcccb6e210

**Comment by geoffreymcgill** [comment]
Hi @AndreyZM - Thanks for the report and excellent sample demonstrating how to reproduce the issue. 

We will investigate and fix.

**Comment by LeonidVeriga** [comment]
Hi @AndreyZM,

I just created a sample to compare .Net and Bridge behavior:
[Deck](http://deck.net/b7fd6db70dcad5891623cb3a0df3b526)
[.Net Fiddle](https://dotnetfiddle.net/tCKCDD)
```cs
public class App
{
    public static void Main()
    {
        System.Console.WriteLine("Invoke();");
        Invoke();

        System.Console.WriteLine("Invoke(null);");
        Invoke(null);
    }
    
    public static void Invoke(params object[] args)
    {
        if (args == null)
        {
            System.Console.WriteLine("Null");
            return;
        }

        System.Console.WriteLine("Length: " + args.Length);

        for(var i = 0; i < args.Length; i++)
        {
            System.Console.WriteLine(args[0]);
        }
    }
}
```

Both samples give the same result:
```
Invoke();
Length: 0
Invoke(null);
Null
```

**Comment by LeonidVeriga** [comment]
The original code sample run in .Net ([Fiddle](https://dotnetfiddle.net/hbsTow)) also results in exception.

We will add a test and close the issue.
