### ISSUE TITLE
Mark DefaultValueMode as Obsolete

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#1756]
**DefaultValueMode** of `[ObjectLiteral]` Attribute is now marked as `Obsolete` and will be removed in a future major version release of Bridge. 

Please use **ObjectInitializationMode**. See #1755.

```cs
// Old
[ObjectLiteral(DefaultValueMode.DefaultValue)]
public class Config { }

// New
[ObjectLiteral(ObjectInitializationMode.DefaultValue)]
public class Config { }
```

The same enum values still apply.

```cs
Ignore = 0,
Initializer = 1,
DefaultValue = 2
```

**Comment by kcudnik** [comment]
Will this be also a bridge.json config option? In my case i use a lot of object literals, it's simple to add extra  Initialization mode for each class but would be also nice to have default option in bridge.json to not add extra code or keep in mind this all  the time. Should be also easy to add in compiler.

**Comment by LeonidVeriga** [comment]
@kcudnik, we created a feature request #1792 for next release.

**Comment by kcudnik** [comment]
Thanks a lot!
