### ISSUE TITLE
A possibility to emit a regular class instance as an object literal (only properties)

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#177]
The feature request came from this forum thread:
http://forums.bridge.net/forum/community/help/161

**Comment by mac2000** [comment]
It will be nice if there will be something like [ko.toJS()](http://knockoutjs.com/documentation/json-data.html#converting-view-model-data-to-plain-json) in `Bridge` namespace

But still it is yet another call that we should *remember* to do

At least for this moment maby be there is a way to modify jQuery post, ajax, getJSON etc implementations so they will check is given data object instance of class and if so call `Bridge.ToJS`

**Comment by mac2000** [comment]
Also there is same situation when retrieving responses from ajax call.

Suppose we have generic handler like this:

```C#
public class SampleHandler : IHttpHandler {
	public void ProcessRequest(HttpContext context) {
		context.Response.ContentType = "application/json";
		context.Response.Write(JsonConvert.SerializeObject(new Response { Success = true, Message = "OK" }));
	}
}
```

which returns instance of:

```C#
public class Response
{
	public bool Success { get; set; }
	public string Message { get; set; }
}
```

in my ajax call I assume that I can unbox it like this:

```C#
jQuery.Post("/SampleHandler.ashx", new {}, (object obj, string str, jqXHR request) => {
	var model = (Response)obj; // raises: Uncaught Unable to cast type Object to type Core.Response
	Console.Log(model);
}, "json");
```

**Comment by DaniilVeriga** [comment]
Thank you for all the suggestions. Yeah, it is something we are thinking on as well.

As for `(Response)obj`. It is rather an opposite operation. The issue is about converting a class instance to a literal, but `(Response)obj` is opposite - converting a literal to a class instance. There is a possible solution. Please start a new forum thread and we'll discuss in greater details.

**Comment by geoffreymcgill** [comment]
Is this going to be implemented in time for the 1.3 release? If no, please remove the Milestone.

**Comment by DaniilVeriga** [comment]
`JSON.Stringify(person)` and `JSON.Parse(JSON.Stringify(person))` appear to be a solution.

**Comment by geoffreymcgill** [comment]
Seems like there are many options now to solve this issue. Using **ObjectLiteral** is one, and directly calling `Bridge.toPlain()` is another. 

Adding the [`[ObjectLiteral]`](https://github.com/bridgedotnet/Bridge/wiki/attribute-reference#objectliteral) attribute may be an option too. 

```csharp
public class Program
{
    public static void Main()
    {
        var p = new Person();
        
        p.Name = "Frank";
        
        var obj = new ObjectLiteral(p);
        
        Console.WriteLine(obj);
        
        // Directly call Bridge.toPlain
        //@ obj = Bridge.toPlain(p);
        
        Console.WriteLine(obj);
    }
}

public class Person
{
    public string Name { get; set; }
}
```
