### ISSUE TITLE
Script.ToDynamic or jqXHR.ToDynamic causes 'object reference not set...'

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#178]
The following code:
```
            var authType = "myAuthType";

            jQuery.Ajax(new AjaxOptions()
            {
                BeforeSend = delegate(jqXHR xhr, object data)
                {
                    xhr.ToDynamic().SetRequestHeader("Authorization", authType);
                    return true;
                }
            });
```
Causes an `object reference not set to an instance of object`.

The problem is on the line reading:
`xhr.ToDynamic().SetRequestHeader("Authorization", authType);`

Changing it to:
`Script.ToDynamic().xhr.SetRequestHeader("Authorization", authType);`

Also breaks the code. Having other items (like `Success`, `Url` etc) defined in the AjaxOptions() does not fix the problem.

The following construct works, though:
`((XMLHttpRequest)xhr.ToDynamic()).SetRequestHeader("Authorization", authType);`

It thus, forcefully tries to cast the `jqXHR` class to `XMLHttpRequest`, so the user can use code completion on VS. It is not guaranteed to work once the JavaScript code is run. The resulting bridge output of the construct right above is:
`(Bridge.cast(xhr, XMLHttpRequest)).setRequestHeader("Authorization", authType);`

This was reproduced while trying to suggest a solution for the user on forum thread:
[Jquery Ajax call - with basic Authentication](http://forums.bridge.net/forum/community/help/168)

**Comment by vladsch** [comment]
I cannot reproduce it. Please retest with latest code. Also please note that dynamic code is rendered as is, you would need to change `SetRequestHeader` to `setRequestHeader`

**Comment by fabriciomurta** [comment]
Really, I could no longer reproduce the issue. Something else might have fixed it. :)
