### ISSUE TITLE
jQuery.load emits $.load

### ISSUE THREAD

**Issue by Mimisss** [bridgedotnet/Bridge#180]
required selector is missing (should just a call be allowed in the first place?)

**Comment by DaniilVeriga** [comment]
Yes, jQuery load method is non-static method. I think it was initially marked as static by mistake. Removed the static modifier.

It is supposed to be used like this: `new jQuery("#infoDiv").Load("get info URL");`

@Mimisss, if there is any associated forum thread, please update with a message that it is fixed and the fix goes to the next jQuery public release - 2.1, which should probably happen today or tomorrow.

**Comment by DaniilVeriga** [comment]
Bridge.jQuery 2.1.0 has been released with the fix.
