### ISSUE TITLE
Compiler Exception on @new call (Bridge 1.15)

### ISSUE THREAD

**Issue by AndreyZM** [bridgedotnet/Bridge#1802]
### Steps To Reproduce
http://deck.net/52b378460b3cff503c76f415b1ab1618
```csharp
public class Class
{
    static public void Method()
    {
        @new();
    }
    
    static public void @new()
    {
        
    }
}
```

**Comment by geoffreymcgill** [comment]
@AndreyZM - Thanks for the report and excellent sample demonstrating how to reproduce the issue. We are working on a fix and will include in the upcoming Bridge 15.0 release.
