### ISSUE TITLE
Implement indexed collections from the JavaScript standard built-in objects

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#182]
Most of the built-in objects representing indexed collections does not have a representative in Bridge.NET. At least these are not currently on the project:
• Int8Array
• Uint8Array
• Uint8ClampedArray
• Int16Array
• Uint16Array
• Int32Array
• Uint32Array
• Float32Array
• Float64Array

This issue has been logged to track the implementation of these objects. Any other missing object to be created should be assigned to a new issue.

The reference for these and other standad built-in objects can be found at:
[Standard built-in objects - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects)

**Comment by fabriciomurta** [comment]
It will now be possible to use typed references where they are used in WebGL and Canvas2DRenderingContext.

**Comment by MDR-DEV-GIT** [comment]
Perhaps I'm missing something but doesn't there need to be either an inheritance path for Float32Array to ArrayBuffer or a way to cast/convert to this? 

The WebGL Cube3D Sample (Cube.cs) is trying to pass a new Float32Array(double[]) to a parameter that is expecting a ArrayBuffer which is generating a compile-time Cast exception. It does something similar for a UInt16Array to ArrayBuffer also. 

I tried (locally) to do the obvious of having Float32Array inherit from ArrayBuffer which lets the Cube.cs code compile however a "Uncaught TypeError: Cannot read property 'Float32Array' of undefined"

**Comment by DaniilVeriga** [comment]
Thank you very much for the feedback.

Actually, Float32Array doesn't inherit ArrayBuffer. It was done in the Cube sample by mistake before we implemented TypedArrays support in Bridge. Currently, I've reviewed the TypedArrays support and it has unveiled two issues: #548, #549.

Generally speaking, the Cube sample is a little out-dated. We will update once we get the issues above resolved.

**Comment by DaniilVeriga** [comment]
@MDR-DEV-GIT, we were able to fix all the unveiled issues and it will go to the 1.10 release. After the release (most likely, this week) I will update the Cube3D sample. Actually, I'll just remove Cube3D\TypedArray.cs file at all since it is implemented in Bridge and those issues are fixed. Again thank you very much for reporting this issue.

**Comment by DaniilVeriga** [comment]
The WebGL demo has been updated to Bridge 1.10.1 and Bridge.WebGL 1.7.1.
https://github.com/bridgedotnet/Demos/tree/master/WebGL/Cube3D
