### ISSUE TITLE
Rename Bridge.sln files

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#1836]
### Existing

Filename | Description
:---- | :----
**Bridge.sln** | Includes tests
**Bridge.NoTest.sln** | Does not include tests

### Proposed

Filename | Description
:---- | :----
**Bridge.sln** | Does not include tests
**Bridge.Dev.sln** | Includes tests

**Comment by ProductiveRage** [comment]
Makes sense to me (until the testing package is available to all).

**Comment by DanTup** [comment]
Didn't see your email till today but also seems sensible to me 👍
