### ISSUE TITLE
Typo in Exception.js line 44

### ISSUE THREAD

**Issue by Suchiman** [bridgedotnet/Bridge#184]
Looking at [Exception.js line 44](https://github.com/bridgedotnet/Bridge/blob/d11a6bbeadc139bcd3bfbd00e64770d722a3e5c8/Bridge/Resources/Exception.js#L44) i get an error stating that o doesn't exists.
I suppose it should have been ```return new Bridge.ErrorException(error);``` instead.

**Comment by geoffreymcgill** [comment]
Thanks for the report. Looks like it should be `error` instead of `o`.

**Comment by fabriciomurta** [comment]
Thank you, if that's just that typo, it's been fixed now.
