### ISSUE TITLE
Wrong enum type for XmlHttpRequest.ReadyState

### ISSUE THREAD

**Issue by Suchiman** [bridgedotnet/Bridge#185]
[XMLHttpRequest.cs line 23](https://github.com/bridgedotnet/Bridge/blob/b5570ec17f30a17975f04ddc7cbadc46b21812e4/Html5/Ajax/XMLHttpRequest.cs#L23) is using the type ```ReadyState``` which doesn't seems valid for XmlHttpRequest.
Changing it to ```AjaxReadyState``` seems to fix it.

**Comment by fabriciomurta** [comment]
Hello, can you provide us with more details on the test situation you found an error while using it? Seems that, by Mozilla's compilation of Web API interfaces, it is really expected to be 'ReadyState'.

Check here: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest

Maybe that's something taken differently by different browsers so, the test case you used to raise this problem would be greatly appreciated (if any).

**Comment by Suchiman** [comment]
If you have a look at [AjaxReadyState.cs](https://github.com/bridgedotnet/Bridge/blob/b5570ec17f30a17975f04ddc7cbadc46b21812e4/Html5/Ajax/AjaxReadyState.cs) you will see that this one matches the numeric values from mozillas spec.
[ReadyState.cs](https://github.com/bridgedotnet/Bridge/blob/b5570ec17f30a17975f04ddc7cbadc46b21812e4/Html5/ReadyState.cs) on the other hand translates to string variables.
I tested it using
```csharp
public static void Main()
{
    XMLHttpRequest request = new XMLHttpRequest();
    request.Open("GET", "http://some.tld");
    request.OnReadyStateChange = () =>
    {
        switch (request.ReadyState)
        {
            case ReadyState.Complete:
                Window.Alert("Complete");
                break;
            case ReadyState.Interactive:
                Window.Alert("Interactive");
                break;
            case ReadyState.Loading:
                Window.Alert("Loading");
                break;
            default:
                Window.Alert("Not an expected value");
                break;
        }
    };
    request.Send();
}
```
resulting in
```JavaScript
main: function () {
    var request = new XMLHttpRequest();
    request.open("GET", "http://some.tld");
    request.onreadystatechange = function () {
        switch (request.readyState) {
            case "complete": 
                window.alert("Complete");
                break;
            case "interactive": 
                window.alert("Interactive");
                break;
            case "loading": 
                window.alert("Loading");
                break;
            default: 
                window.alert("Not an expected value");
                break;
        }
    };
    request.send();
}
```
which always ended in "Not an expected value" which i've verified using the browser debugging tools which also confirmed that the value is in fact numeric.

**Comment by fabriciomurta** [comment]
Thanks, asking @vladsch to take a look on this to decide whether we fix the javascript output from the ReadyState, or if using AjaxReadyState is really the solution in this case.

**Comment by DaniilVeriga** [comment]
Hello everybody!

I am sure XmlHttpRequest.ReadyState was meant to be AjaxReadyState. Changed. Thank you for reporting this!
