### ISSUE TITLE
Runtime error when class explicitly implements interface method

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#1850]
Reported in the [forum](http://forums.bridge.net/forum/bridge-net-pro/bugs/2728-runtime-error-when-class-explicitly-implements-interface-method).

### Expected
No errors

### Actual
Invalid js code

```js
alias: [
    "getEnumerator",
    "System$Collections$Generic$IEnumerable$1$System$Collections$Generic$KeyValuePair$2$"
    + Bridge.getTypeAlias(T) + "$String"$getEnumerator"
]
```
It is the `"getEnumerator"` alias line that fails since there is a missing "+" operator.

### Steps To Reproduce
Sample ([Deck](http://deck.net/3a98527f1aa7b8b40bfe0ece9d37f94a)):
```csharp
public sealed class LookupOptions<T> : IEnumerable<KeyValuePair<T, string>>
{
    public IEnumerator<KeyValuePair<T, string>> GetEnumerator()
    {
        throw new NotImplementedException();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        throw new NotImplementedException();
    }
}
```

**Comment by LeonidVeriga** [comment]
Related feature #1844
