### ISSUE TITLE
Runtime error with generic interface

### ISSUE THREAD

**Issue by glaanc03** [bridgedotnet/Bridge#1854]
Runtime error with generic interface.

### Expected

No errors

### Actual

`TypeError: Cannot read property '_param' of undefined`

### Steps To Reproduce

[Live Bridge](http://deck.net/63ee2855cc82bd3fb178a23738cb9806)

**Comment by geoffreymcgill** [comment]
This fix has been included in the Bridge 15.1.0 release, which is now available from NuGet and http://bridge.net/download.

**Comment by glaanc03** [comment]
That's great! Thank you for the fast fix!
