### ISSUE TITLE
[ObjectLiteral] Support interfaces with properties

### ISSUE THREAD

**Issue by Zaid-Ajaj** [bridgedotnet/Bridge#1865]
### Expected

To compile with no errors 
### Actual

```
Compile error: ObjectLiteral doesn't support virtual methods
```
### Steps To Reproduce

[Deck](http://deck.net/d45e05d8d0534c415d3166b1c9ec13c2):

``` cs
interface IContract
{
    int Value {get;set;}
}

[ObjectLiteral]
class Contract : IContract
{
    public int Value { get; set; }
}

public class Program
{
    public static void Main()
    {
        var contract = new Contract { Value = 5 };
        Console.WriteLine(contract.Value);
    }
}
```

**Comment by kcudnik** [comment]
ObjectLiteral is simple object reflecting plane JS object, not 100% sure but i does not support fields like in your case, and hence conflict, since interface forces to use properties instead of fields.
Maybe that would be nice feature to request for Bridge team as long as there is no implementation provided for such properties.

Also as workaround you can use other ObjectLiteral class as base class to have those fields in place.

**Comment by samfromdeath** [comment]
I remember seeing this error when making a clone version of AjaxOptions - it had ObjectLiteral and virtual fields, It compiled on bridge 1.1 then it threw exception on bridge 1.5, i just took it out.

**Comment by vladsch** [comment]
The reason why ObjectLiteral is not supported interface members is that you can define two interfaces with same member name

```cs
interface IContract
{
    int Value {get;set;}
}

interface IContract2
{
    int Value {get;set;}
}

[ObjectLiteral]
class Contract : IContract, IContract2
{
	public int Value { get; set; }
    int IContract2.Value { get; set; }
}
```

and if you try to access to member via interface cariable then Bridge cannot resolve member correctly
```cs
IContract2 c2 = new Contract();
c2.Value;
```

May be can allow properties but forbid methods and explicit interface implementation. We will discuss it. Thanks for pointing us to it

**Comment by Zaid-Ajaj** [comment]
Alright, thanks for the clarification. 
Best regards.

**Comment by vladsch** [comment]
Hi,

In Bridge 15.5, your original test case will be supported but interface must be marked as ObjectLiteral also

**Comment by Zaid-Ajaj** [comment]
Thats awesome! thanks @vladsch for the reply
