### ISSUE TITLE
Supporting RPC (client-server interaction)?

### ISSUE THREAD

**Issue by Zaid-Ajaj** [bridgedotnet/Bridge#1866]
Do you guys have plans to support Remote Procedure Calls (RPC)? [Websharper](http://websharper.com/) already has that for F# and recently also for C#! [C# Remoting](http://websharper.com/docs#web_development/remoting_-_c-sharp/heading-1-3). ScalaJs has it as well using [Autowire](https://github.com/lihaoyi/autowire).

**Comment by samfromdeath** [comment]
Hey @Zaid-Ajaj Im not with bridge, but how could they support Websharper as they are in beta??

**Comment by LeonidVeriga** [comment]
Hi @Zaid-Ajaj,

We had discussions within the team about something like this, a great feature.
No firm time frame for this feature, however.
