### ISSUE TITLE
Error comment throws compiler exception

### ISSUE THREAD

**Issue by chenxustu1** [bridgedotnet/Bridge#1871]
### Expected
no error
### Actual
can't compile 

### Steps To Reproduce

```csharp
    public class App
    {
        /// <summary>
        /// </summary>
        ///<param name="args"></param>
        ///<param name="args1"></param>
        public static void Main(string args)
        {
            
        }
    }
```
online version:
http://deck.net/f7fabffb5315682e163b27880bb27888

**Comment by samfromdeath** [comment]
It is because it is expecting 

///<param name="args"></param>

Because it gets the arg type by that param name: 

* @param   {string}    args

**Comment by chenxustu1** [comment]
i debug the compiler,the error is caused by args1  is not defined.

**Comment by samfromdeath** [comment]
It is because they are trying to get that argument type from the name to put against the comments.
