### ISSUE TITLE
Generic class generates invalid name cast in loop

### ISSUE THREAD

**Issue by kcudnik** [bridgedotnet/Bridge#1882]
### Expected

```js
var i = $t.getCurrent();
// or equivalent with correct class name 
```

### Actual
JvaScript exception
`TypeError: Cannot read property 'System$Collections$IEnumerable$getEnumerator' of null`
```js
 Bridge.cast($t1.getCurrent(), Demo.Program.MVCArray$1(System.Int32)); 
```

### Steps To Reproduce

Sample ([Deck](http://deck.net/3d3cc84191def2864b3000bd81f2b884)):
```csharp
public class Program
{
    [External]
    public class MVCArray<T> 
	{
		public extern MVCArray();
    }
    
    public static MVCArray<int>[] GetArray()
    {
        return null;
    }
       
    public static void Main()
    {
        foreach (var i in GetArray())
        {
            // OK: var i = $t.getCurrent();
        }
       
        foreach (MVCArray<int> i in GetArray())
        {
            // Error cast: var i1 = Bridge.cast($t1.getCurrent(), Demo.Program.MVCArray$1(System.Int32)); 
            // there is no MVCArray$1 definition 
        }
    }
}
```

PS. why there is a cast every time here? can have performance impact (i guess i can use var for now)

**Comment by LeonidVeriga** [comment]
@kcudnik,
> PS. why there is a cast every time here? can have performance impact (i guess i can use var for now)

Yes, right, it is better to use `var`  as we generate cast instructions if there is a cast in C# code and type in `var` declaration differs from collection's element type.

**Comment by kcudnik** [comment]
Thanks for info!
