### ISSUE TITLE
Simple regex fails to parse

### ISSUE THREAD

**Issue by zb3** [bridgedotnet/Bridge#1897]
### Expected
This should not throw anything.

### Actual
Pattern fails to parse and throws `Unterminated [] set.`, apparently because `_parseGroupToken` doesn't ignore `)` when used in character class, and always treats it as the end of the group, so then `_parseCharRangeToken` receives wrong `endIndex` and throws... (from what I can see `_parseGroupToken` doesn't even recognize character classess)

### Steps To Reproduce
Sample ([Deck](http://deck.net/d66cd225576eea5361f327eda08bbd2f)):

```csharp
using System;
using System.Text.RegularExpressions;

public class Program
{
    public static void Main()
    {
        MatchCollection x = Regex.Matches(")", @"([)])");
        
        if (x.Count > 0)
        {
            Console.WriteLine(x[0].Value);
        }
        else
        {
            Console.WriteLine("Failure");
        }        
    }
}
```

**Comment by geoffreymcgill** [comment]
Hi @zb3,

Thanks for the report and simple case demonstrating how to reproduce. We have reviewed and this defect will be fixed right away. Somehow this usage scenario slipped through our testing.

The bug fix will be included in the upcoming 15.2 release.

**Comment by AndreyChechel** [comment]
@zb3, thank you for that finding! Meanwhile you can use the workaround with an escaped `)` bracket:
`MatchCollection x = Regex.Matches (")", @"([\)])");`
[Deck sample](http://deck.net/43f0cab7c76320fff945e38c8242066a)

Your suggestion regarding character classes is correct for the current case when we have a not escaped `)` symbol. However, for other cases it should work just fine:
[Character classes in Groups](http://deck.net/ac97fcf42dcf2eac7907f12f8c8700c2)

**Comment by geoffreymcgill** [comment]
A pull-request has been submitted with a fix for this issue. The changes are still being tested.

**Comment by geoffreymcgill** [comment]
Possible regression:
http://forums.bridge.net/forum/bridge-net-pro/bugs/2866-regex-initialization-fails-when-regex-cotnains-string-regression-in-v15-2-0

**Comment by LeonidVeriga** [comment]
The issue reported [here](http://forums.bridge.net/forum/bridge-net-pro/bugs/2866-regex-initialization-fails-when-regex-cotnains-string-regression-in-v15-2-0) is reproducidle in 15.1 and not related to this issue.
