### ISSUE TITLE
Is operator inaccuracy

### ISSUE THREAD

**Issue by yuvaltz** [bridgedotnet/Bridge#1906]
### Expected

Both string and bool are of type object

### Actual

```js
true is object // returns false
"string" is object // returns false
```

### Steps To Reproduce

[Deck](http://deck.net/ccb8ad6b47fb43ba844edec2922951a7)

```cs
public class Program
{
    public static void Main()
    {
        // should be true
        Console.WriteLine(true is object); 
        
        // should be true
        Console.WriteLine("string" is object);
    }
}
```

Output:
```
false
false
```

**Comment by geoffreymcgill** [comment]
Hi @yuvaltz, 

Thanks for submitting this simplified sample demonstrating how to reproduce. We will try to fix right away.
