### ISSUE TITLE
Modify Bridge.hasValue to accept multiple arguments

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#1907]
**Proposal** to add functionality to `Bridge.hasValue` which would allow passing 0 to many argument values. Each value would be checked. If all arguments have a value, then `true` is returned, otherwise `false` is returned.

This change would add a little more logic to the `hasValue` functionality, but would reduce the **.js** size in many places throughout **bridge.js**.

### Expected

```js
Bridge.hasValue(a, b) // all true, or return false
```

### Actual

```js
Bridge.hasValue(a) && Bridge.hasValue(b)
```

No breaking changes would occur. This change would be enhance the functionality of the existing `hasValue` function.

**Comment by geoffreymcgill** [comment]
The existing `hasValue` function is located at:
https://github.com/bridgedotnet/Bridge/blob/master/Bridge/Resources/Nullable.js#L2-L4

```js
// Existing
hasValue: function (obj) {
    return obj !== null && obj !== undefined;
};

// Proposed
hasValue: function (obj) {
    if (arguments.length === 0) {
        return false;
    }

    var i = 0;

    for (i; i < arguments.length; i++) {
        if (arguments[i] === null || arguments[i] === undefined) {
            return false;
        }
    }

    return true;
};
```

I ran some basic performance testing with **100 million** (100,000,000) iterations. 

http://deck.net/f5f848b5064b1eb334cce56e1823c05f/left

1. Slower when one object is passed (approx. 99ms vs 167ms)
2. There would an approximate 200 byte savings in the **bridge.js** file size

With 100 million operations, the `hasValue` function would not be the bottleneck.

Seems like this revision would bring a nice client-side api optimization and reduce the file size of **bridge.js**.

**Comment by kcudnik** [comment]
As for space savings, i remember that this topic was rised already but i can't find it on the forum, to introduce modules in bridge, im not using c#Regex, Decimal, Long, WebSocket, Reflection or Grobalization which is ~250kb off from the bridge.js in my case. Maybe my example is pretty extreeme since i have plain code, didnt imported anything from ouside and i keep in mind js flow writing code.

I already looked into the bridge code and it seems like there is a lot of dependencies of those so it may not be easy to split them to actual modules, but i though about providing skeleton for each not used module on which each member would rise exception (just in case).

**Comment by kcudnik** [comment]
Also for performance testing small methods like this it's common to do loop unrolling to remove loop play in time measurements, in my browser just empty loop takes 25% of total time

**Comment by geoffreymcgill** [comment]
We'll be working on some options for greatly reducing the **bridge.js** file size with dependency checking. 

The majority of **bridge.js** is a concatenation of various _sub-libraries_ required to support various large chunks of the .NET Framework. You listed most of them, including Regex, Decimal, Long, etc. Another is LINQ. If you strip all these libraries out of **bridge.js**, there's not much _**Bridge**_ remaining.

If you're not using a certain .NET feature within your App, then you should have the option to exclude from the compiled output runtime library.

**Comment by LeonidVeriga** [comment]
Instead of
```js
if (arguments[i] === null || arguments[i] === undefined)
```
We can use
```js
if (arguments[i] == null)
```

**Comment by LeonidVeriga** [comment]
The basic performance testing with 100 million (100,000,000) iterations and added optimized existing `hasValue` (to use `if (arguments[i] == null)`):

http://deck.net/aac7c465582442a75f024b95dcd30cc9/left

1. Optimized existing `hasValue` (to use `if (arguments[i] == null)`): **105 ms**
2. Current approach **189 ms**
3. With `arguments` **237 ms**

**Comment by LeonidVeriga** [comment]
**1)** Optimizes existing `Bridge.hasValue` (faster **105 ms** against **189 ms** on your perf test [Deck](http://deck.net/aac7c465582442a75f024b95dcd30cc9/left))
Current:
```js
hasValue: function (obj) {
    return (obj !== null) && (obj !== undefined);
},
```
Revised:
```js
hasValue: function (obj) {
    return obj != null;
},
```
**2)** Adds an overload `Bridge.hasValue$1` to work with function `arguments`, a trade-off to keep the exising fast `hasValue` and save some bytes for **bridge.js** in case of multiple arguments:
```js
hasValue$1: function () {
    if (arguments.length === 0) {
        return false;
    }

    var i = 0;

    for (i; i < arguments.length; i++) {
        if (arguments[i] == null) {
            return false;
        }
    }

    return true;
},
```

Saves 259 bytes in the **bridge.js** file size: 259 bytes = 883'226 - 882'967

**Comment by geoffreymcgill** [comment]
**Nullable.js** needs to be reviewed.
