### ISSUE TITLE
Activator.CreateInstance enum creation

### ISSUE THREAD

**Issue by yuvaltz** [bridgedotnet/Bridge#1909]
### Expected

```js
// should return default enum value (0)
Activator.CreateInstance(typeof(EnumType)) 
```

### Actual

```
// returns false (and cannot be casted to EnumType)
jsActivator.CreateInstance(typeof(EnumType)) is EnumType
```

**Comment by geoffreymcgill** [comment]
Hi @yuvaltz - Thanks for submitting this defect. We will investigate and try to fix right away.

I have a favour to ask... can you link to a [Deck.NET](http://deck.net/) sample demonstrating exactly how to reproduce these problems? This would certainly help us focus on the problem and speed up investigation.

**Comment by yuvaltz** [comment]
Sure, no problem

**Comment by LeonidVeriga** [comment]
Duplicate of #1595
