### ISSUE TITLE
Weird Sequence bug when generating java-script classes...

### ISSUE THREAD

**Issue by nmyvision** [bridgedotnet/Bridge#191]
The following code:

    class m { }

    class a : z { }

    class z { }

    class p { }

generates this javascript:

    Bridge.define('Animal.a', {
       inherits: [Animal.z]
    });

    Bridge.define('Animal.m');

    Bridge.define('Animal.p');
    <-- z should be first -->
    Bridge.define('Animal.z');

However... when there is only:

    class m { }
    
    class a : z { }
    
    class z { }

the proper javascript is generated...

    Bridge.define('Animal.z');

    Bridge.define('Animal.a', {
        inherits: [Animal.z]
    });
    
    Bridge.define('Animal.m');

**Comment by DaniilVeriga** [comment]
Thank you for the report! I see where the problem is. Thinking of a possible fix.

**Comment by vladsch** [comment]
We will fix it soon. At this moment, you can set `[Priority(1)]` attribute for `z` class
