### ISSUE TITLE
Nullable exception in generic type casting

### ISSUE THREAD

**Issue by yuvaltz** [bridgedotnet/Bridge#1910]
### Expected

Casting from object to generic type `T` should be the same as casting to a concrete type

### Actual

Generated code includes a `Nullable.getValue` call which throws an exception

### Steps To Reproduce

http://deck.net/6c5b8f26585d2d16918b531439e410b4

```cs
public class ItemValue
{
}

public class Item<T>
{
    private object value;

    public ItemValue Value1 { get { return (ItemValue)value; } }
    public T Value2 { get { return (T)value; } }

    public Item(T value)
    {
        this.value = value;
    }
}

class Program
{
    static void Main(string[] args)
    {
        var item1 = new Item<ItemValue>(null);

        Console.WriteLine(item1.Value1 == null); // returns true
        Console.WriteLine(item1.Value2 == null); // should return true, Nullable.getValue throws an exception
    }
}
```

Generated code:
```js
getValue1: function () {
    return Bridge.cast(this.value, Demo.ItemValue);
},
getValue2: function () {
    return System.Nullable.getValue(Bridge.cast(this.value, T));
}
```
Both properties should be the same

**Comment by geoffreymcgill** [comment]
@yuvaltz - Thanks for reporting. We will investigate and try to fix this right away. We will plan to include this fix in the 15.3 public release, although it should hit the **master** branch before that release.
