### ISSUE TITLE
Extension method is called with incorrect "this" argument

### ISSUE THREAD

**Issue by yuvaltz** [bridgedotnet/Bridge#1912]
### Expected

A variable or a property name which is used to invoke an extension method shouldn't affect the call arguments

```cs
var Item = new Item();
Item.SetValue();
```
Generated code:
```js
var Item = new Demo.Item();
Demo.ItemExtensions.setValue(Item);
```

### Actual

A class with the same name as the variable is passed as the "this" argument to the extension method

Generated code:
```js
var Item = new Demo.Item();
Demo.ItemExtensions.setValue(Demo.Item); // class is passed
```

### Steps To Reproduce

[Deck](http://deck.net/c369a10b78a790a6e5f8cd2710dca005)

```cs
public class Item
{
}

public static class ItemExtensions
{
    public static void SetValue(this Item item)
    {
    }
}

class Program
{
    static void Main()
    {
        var Item = new Item();
        var Item2 = new Item();

        Item.SetValue(); // extension method first argument is incorrect
        Item2.SetValue();
    }
}
```

**Comment by vladsch** [comment]
The same issue
https://github.com/bridgedotnet/Bridge/issues/483
