### ISSUE TITLE
ReadOnlyCollection doesn't reflect the source collection current state

### ISSUE THREAD

**Issue by yuvaltz** [bridgedotnet/Bridge#1914]
### Expected

Adding or removing items from the source collection should be reflected in the **ReadOnlyCollection**.

### Actual

**ReadOnlyCollection** holds a copy of the source collection and doesn't get updated

### Steps To Reproduce

[Deck](http://deck.net/bd33ca982898a55bbf737dcc0e9fa22e)

```cs
class Program
{
    static void Main(string[] args)
    {
        var list = new List<int>();
        list.Add(1);

        var readOnlyList = new System.Collections.ObjectModel.ReadOnlyCollection<int>(list);
        list.Add(2);

        Console.WriteLine(list.Count == readOnlyList.Count); // should be true
    }
}
```

**Comment by LeonidVeriga** [comment]
Related to #1626 in part of  `IReadOnlyList`
