### ISSUE TITLE
Incorrect generated method name / alias when implementing an interface from another library

### ISSUE THREAD

**Issue by yuvaltz** [bridgedotnet/Bridge#1915]
I have a class library with these interfaces
```csharp
public interface IItem
{
    object Value { get; }
}

public interface IWriteableItem : IItem
{
    bool SetValue(object value);
}
```

And implementation that results in a slightly different methods names
```csharp
public class WriteableItem : IWriteableItem
{
    private object value;
    public object Value { get { return value; } }

    public bool SetValue(object value)
    {
        this.value = value;
        return true;
    }
}
```

From the same class library the generated `SetValue` method name ( / alias) will be
```js
ClassLibrary1$IWriteableItem$setValue$1
```

([Deck](http://deck.net/e62add91aa2d82a8789003826eb7a503))

And from a referencing project it will be
```js
ClassLibrary1$IWriteableItem$setValue
```
(Sorry, no Deck)

The wrong name causes in some cases an "Object doesn't support property or method .." exception.

I've attached a solution with the full configuration:
[BridgeClassLibraryTest.zip](https://github.com/bridgedotnet/Bridge/files/505161/BridgeClassLibraryTest.zip)

**Comment by geoffreymcgill** [comment]
Hi @yuvaltz - This fix has been added to the **master** branch and will be included in the upcoming Bridge 15.3 release. 

Thanks for taking the time to report these defects. We really appreciate your interest in Bridge. 

When you have a moment, could you send me an email (geoff@object.net). I have a few questions for you.
