### ISSUE TITLE
HtmlCanvas.StrokeStyle & HtmlCanvas.FillStyle can accept gradient and pattern

### ISSUE THREAD

**Issue by AndreyZM** [bridgedotnet/Bridge#1917]
https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/strokeStyle
https://developer.mozilla.org/docs/Web/API/CanvasRenderingContext2D/fillStyle

**Comment by geoffreymcgill** [comment]
https://github.com/bridgedotnet/Bridge/blob/master/Html5/Interfaces/CanvasRenderingContext2D.cs#L230-L238

Propose change to use **Any** class. Should not be a breaking change for any existing code.

```cs
/// <summary>
/// Color or style to use inside shapes. Default #000 (black).
/// </summary>
public Any<string, CanvasGradient, CanvasPattern> FillStyle;

/// <summary>
/// Color or style to use for the lines around shapes. Default #000 (black).
/// </summary>
public Any<string, CanvasGradient, CanvasPattern> StrokeStyle;
```

**Comment by LeonidVeriga** [comment]
A sample to demonstrate `StrokeStyle` & `FillStyle` properties [Deck](http://deck.net/a7ba70e0e486e094687983274c1245ed) (for 15.3 release).
