### ISSUE TITLE
Improve generated String Concatenation

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#1920]
Related forum thread:
http://forums.bridge.net/forum/bridge-net-pro/bugs/2719-open-1844-members-on-external-interfaces-are-not-correctly-specified-in-the-javascript?p=2833#post2833

### Expected

```js
"a" + 1 + "b" + "c"
```

### Actual

```js
System.String.concat(System.String.concat(System.String.concat("a", 1), "b"), "c")
```

### Steps To Reproduce

[Deck](http://deck.net/99140249f9d7bf23cff2345070b7c37b)

```cs
public class Program
{
    public static void Main()
    {
        Console.WriteLine("a" + 1 + "b" + "c");
    }
}
```

**Comment by LeonidVeriga** [comment]
1)  `System.String.concat` improved to use multiple arguments:
```js
concat: function () {
    var s = "";
    for (var i = 0; i < arguments.length; i++) {
        var tmp = arguments[i];
        s += tmp == null ? "" : tmp;
    }

    return s;
}
```
2) Constants are not wrapped by `concat`
[Deck](http://deck.net/1325faca472c6d69f770b6cb7dd9fc91)
```cs
var s1 = "a" + 1;
var s2 = 2 + s1 + "b";
```
 **-->**

**15.2**
```js
var s1 = System.String.concat("a", 1);
var s2 = System.String.concat(System.String.concat(2, s1), "b");
```
Revised in **15.3**
```js
var s1 = "a" + 1;
var s2 = System.String.concat(2, s1, "b");
```

**Comment by kcudnik** [comment]
Thanks for simplifying concat :)

**Comment by LeonidVeriga** [comment]
String.Concat is further improved as suggested in #3150.
