### ISSUE TITLE
Bridge String class overloads inconsistent with C# String class

### ISSUE THREAD

**Issue by Porl91** [bridgedotnet/Bridge#1921]
The following sample generates a C# compiler error:
https://dotnetfiddle.net/NuFS5Y

However in Bridge there is an overload of String that takes a single character with no additional arguments, although it produces unexpected results:
http://deck.net/6c2a18f0d1279e150ba61dc9b1210673

This just seems to present problems when attempting to render single characters. The first line in the sample above outputs '60', which is the character decimal value of the specified unicode code point. The second line is similar, except I use the constructor overload that allows the count parameter. In this case it renders as its plain text glyph representation.

Not a critical issue but I thought it was worth raising due to it being inconsistent.

**Comment by geoffreymcgill** [comment]
Hi @Porl91 - Thanks for pointing out this error in the API. We will review and fix. 

I believe the whole **String** class needs a good review. Related to #72.

**Comment by LeonidVeriga** [comment]
Removed not standard C# string constructors
- `public String(object thing);` 
- `public String(char c);`
