### ISSUE TITLE
Linq Min() and Max() do not work on query

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#194]
C# code:
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using Bridge;

namespace Demo
{
    public class App
    {
        [Ready]
        public static void Main()
        {
            int[] data = new int[] { 5 };
            var max= (from n in data select n).Max();
            var min = (from n in data select n).Min();
        }
    }
}
```
Translates to
```javascript
            var data = [5];
            var query1 = null.max();
            var query2 = null.min();
```

**Comment by fabriciomurta** [comment]
I believe, rather LINQ Query Expressions are not implemented. Just the LINQ's Enumerable class.
What is not implemented (AFAIK):
https://msdn.microsoft.com/en-us/library/bb397676.aspx

What is (at least most methods) implemented (AFAIK):
https://msdn.microsoft.com/en-us/library/system.linq.enumerable(v=vs.100).aspx

I have not tried linq query expressions yet to say for sure whether they are working elsewhere -- i.e. if linq query expressions are being interpreted and emitted.

I have noticed several `public static TResult (...)` methods are not implemented on bridge LINQ's Enumerable class though.

**Comment by LeonidVeriga** [comment]
```
var result = (from n in data select n).ToList();
```
Translated successfully into
```
 var result = (Bridge.Linq.Enumerable.from(data).select(function (n) { return n; })).toList();
```

**Comment by fabriciomurta** [comment]
Well, it looks like it does not translate the query expressions at all

Earlier today I noticed Bridge's `Linq.Enumerator` has the following:
`public static List<TSource> ToList<TSource>(this IEnumerable<TSource> source)`

But does not have both:
`public static TSource Max<TSource>(this IEnumerable<TSource> source)`
nor
`public static TResult Max<TSource, TResult>(this IEnumerable<TSource> source, Func<TSource, TResult> selector)`

Which are defined on MS's `Linq.Enumerator`.
