### ISSUE TITLE
Illegal constructor

### ISSUE THREAD

**Issue by Meai1** [bridgedotnet/Bridge#1940]
In bridge.js:2582 it says `Uncaught TypeError: Illegal constructor` here:

```js
prototype = extend ? (extend[0].$$initCtor ? new extend[0].$$initCtor() : new extend[0]()) : new Object();
```

Version: 15.2

I didn't have that problem before.

**Comment by geoffreymcgill** [comment]
Hi @Meai1 - Thanks for posting this defect. 

Can you provide a link to a [Deck.NET](http://deck.net) sample demonstrating how to reproduce? This will help us quickly isolate the problem and provide a fix.

**Comment by Meai1** [comment]
@geoffreymcgill http://deck.net/6ae4ab6f79ab413e5768d9b2ce14eb98
you have to open the console to see the error.

**Comment by geoffreymcgill** [comment]
This is a duplicated of Issue #1238. Let's continue the discussion in that thread.
