### ISSUE TITLE
Linq API help error: XML comment contains invalid XML

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#195]
For example, by mouse over the `Intersect()` method below you get the following help message "XML comment contains invalid XML: Enat tag 'param' does not match the start tag 'T'"
```
using System;
using System.Collections.Generic;
using System.Linq;
using Bridge;

namespace ClientTestLibrary.Linq
{
    class TestLinqSetOperators
    {
        public void Test()
       {
            IEnumerable<int> i;
            i.Intersect();
       }
    }
}
```

**Comment by fabriciomurta** [comment]
Fixed using
`sed -i "/\/\/\/ [^<]/ {s/</\&lt;/g;s/>/\&gt;/g}" Enumerable.cs`
