### ISSUE TITLE
Bridge.fn.bind produce a memory leaks

### ISSUE THREAD

**Issue by AndreyZM** [bridgedotnet/Bridge#1951]
http://deck.net/cb3d8869609e9184beb85ad401227711

Bridge.fn.bind(obj, method) save reference to the "obj" into "method.$$bind" and keep it forever. This can produce huge memory leaks. 

Solution:
```js
#before 
Bridge.fn.bind(obj, obj.method)

#after
(obj.method = Bridge.fn.bind(obj, obj.method))
```

this will replace instance method property with a new bounded function.

**Comment by LeonidVeriga** [comment]
Hi @AndreyZM, it is a nice finding, thank you.

We are going to apply this fix #1952.
