### ISSUE TITLE
ScriptAttribute for extern methods

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1955]
### Expected
Should show Hello on Console.
```js
/**
 * Generated by Bridge.NET 15.3.0
 */

Bridge.assembly({
        name: "Demo",
        compiler: "15.3.0"
    },
    function ($asm, globals) {
        "use strict";

        Bridge.define("Demo.Program", {
            statics: {

            },
            scriptFunc: function() {
                  console.log("Hello");
            }
            $main: function () {
                Demo.Program.scriptFunc();
            }
        });
    }
);

```

### Actual

```js
/**
 * Generated by Bridge.NET 15.3.0
 */

Bridge.assembly({
        name: "Demo",
        compiler: "15.3.0"
    },
    function ($asm, globals) {
        "use strict";

        Bridge.define("Demo.Program", {
            statics: {

            },
            $main: function () {
                Demo.Program.scriptFunc();
            }
        });
    }
);

```

### Steps To Reproduce

[Deck](http://deck.net/75c721282fdee099eb3fdce982ca10e1)

```cs
public class Program
{
    [Script("console.log(\"Hello\")")]
    public static extern void ScriptFunc ();
    public static void Main()
    {
        ScriptFunc();
    }
}```

**Comment by vladsch** [comment]
At this moment, Script should be applied to non extern method
http://deck.net/ea193fccca48f8051c0faee1a9341693

We will review functionality to apply to extern methods also

**Comment by geoffreymcgill** [comment]
@vladsch and @michaelcheers - To me it seems like the current functionality is the expected result. What would be the reason to enable different functionality if the method is marked as `extern`?

Maybe would be better to throw a compiler exception (or warning) if you define a `[Script]` attribute on an `extern` method.

**Comment by vladsch** [comment]
Script attribute means that you don't need method body because body is defined as script inside Script attribute. The single way to avoid method's body is define that method as extern

**Comment by LeonidVeriga** [comment]
`[Script]` is now allowed for `extern` methods.
