### ISSUE TITLE
ReflectableAttribute - Refined filter

### ISSUE THREAD

**Issue by yuvaltz** [bridgedotnet/Bridge#1956]
Reflection metadata tends to get very large (may get to a few hundreds kilobytes), while most of the metadata isn't used at runtime, there isn't an easy way to define which member should have a reflection metadata and which shouldn't
Currently the only way of defining it is to go over the each member and add a `Reflectable(true/false)` attribute.

This is a proposal of having a more refined reflectability configuration by extending the `MemberAccessibility` enum and allowing `ReflectableAttribute` to have multiple `MemberAccessibility` values.

The definition may look like:
```cs
public enum MemberAccessibility
{
    None = 0x0,

    Public = 0x1,
    Private = 0x2,
    Protected = 0x4,
    Internal = 0x8,

    Constructor = 0x10,
    Event = 0x20,
    Field = 0x40,
    Method = 0x80,
    Property = 0x100,

    Instance = 0x200,
    Static = 0x400,

    All = 0xFFF,

    // backward compatibility
    PublicAndProtected = Public | Protected,
    NonPrivate = Public | Protected | Internal,
}

public sealed class ReflectableAttribute : Attribute
{
    ...
    public extern ReflectableAttribute(params MemberAccessibility[] memberAccessibilities);
}
```

Possible usage example:
```cs
[assembly: Reflectable(MemberAccessibility.Public | MemberAccessibility.Instance | MemberAccessibility.Property,
                       MemberAccessibility.Public | MemberAccessibility.Constructor,
                       MemberAccessibility.Static | MemberAccessibility.Field)]
```
This should include all the public properties, public constructors, and static fields (with any accessibility)

Few points:
* The operator between the `ReflectableAttribute` parameters is OR
* When no value is declared from each group  
    Accessibility: `[Public, Private, Protected, Internal]`  
    Type: `[Constructor, Event, Field, Method, Property]`  
    Modifier: `[Instance, Static]`  
    it means any value of that group.
* `MemberAccessibility.None` could only be used without any other parameter: `[Reflectable(MemberAccessibility.None)]`

**Comment by geoffreymcgill** [comment]
Some nice improvements for `[Reflectable]` are coming in Bridge 15.4. The `MemberAccessibility` options are being expanded, and the size of the meta data nodes for each type have been reduced by approximately 30% (varies).

Further improvements are planned for Bridge 16.0.
