### ISSUE TITLE
self-host?

### ISSUE THREAD

**Issue by wizzard0** [bridgedotnet/Bridge#1959]
### Expected

Rebuild Bridge.NET using itself and put to the playground

### Actual

Playground uses server-side Bridge.net

Reasoning: 
1. Will allow integration with pure JS pipelines e.g. Node module loaders
2. Nice integration test
3. It's just cool, even if slow.

**Comment by LeonidVeriga** [comment]
Hi @wizzard0,

Yes, it is an interesting thing to build **bridge.js** from C# code using Bridge.NET itself.
We started this approach in **15.0** - #1677. At the moment, we have several classes (like `Version`, `Guid` and `Random`) translated from C# into JavaScript and included into **bridge.js**.

Nice to hear, we are on the same page for this Bridge-to-Bridge idea.

**Comment by geoffreymcgill** [comment]
This request is covered by #1677. 

As mentioned above, this process has already start, although it will likely take a few major releases until complete.

**Comment by wizzard0** [comment]
Thanks for clarifications!
