### ISSUE TITLE
Support inclusion of non-js/code files within a bridge NuGet package

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#1960]
We're using Bridge with React and would like to build NuGet packages for react components. Components can have styling (and fonts, images, css sprites) in addition to just code and we're evaluating options for the best way to be able to bundle these into a package. Since we may have a package-per-component it could be tedious work to pull in a NuGet package into the Bridge project and then have to do something additional to get the CSS/images/etc..

You already have a mechanism for embedding JS inside the DLL which the Bridge compiler pulls out; it might be a nice feature if we could ship other assets in there too and have them pulled out during compilation (eg. into another folder listed in `bridge.json`). Possibly these could live in a `content` folder to keep some parallel with the way these could be done in normal C#/NuGet-land.

I don't know how common this need is (most people probably edit all their CSS centrally and aren't trying to componentise things the way we are), but I thought it might be worth discussing.

(If you have other suggestions for achieving the same thing, they're welcome too!)

**Comment by LeonidVeriga** [comment]
Hi @DanTup,

I would suggest using #1680 **Resource embedding config options** introduced in **15.0**.

Basically, you can specify **bridge.json** `resource` setting to control what files you need to embed. It can be either file - Bridge generated output or your custom files. You can also combine several files into one `resource` and add a `header` into the `resource` or `remark` for each `file` being included into the `resource`.

For example, your library generates two files **code1.js** and **code2.js**. You need to combine the output files into one file **myLibrary.js** and include a custom css file - **myStyle.css** (located in folder **ProjectRoot\Css**). You would do this in your library's **bridge.json**:
```js
  "resources": [
    {
      "name": "myLibrary.js",
      "header": "// {version} {author}",
      "remark": "// source @{name}\n",
      "files": [
        "Bridge/output/code1.js",
        "Bridge/output/code2.js"
      ]
    },
    {
      "name": "myStyle.css",
      "output": "Css/",
      "files": [ "Lib/myStyle.css" ]
    }
  ]
```

As a result, you would get  **myLibrary.js** (composed of the two files **code1.js** and **code2.js**) and **myStyle.css** embedded into your library assembly resources.

Referencing your library dll in another project (and actually using the library code to force .Net to "use" the assembly), the two files **myLibrary.js** and **myStyle.css** are outputted. The only thing is that they will be placed in the output folder all together. We will try to get a setting to control the resources output folder in **15.4**.

**Comment by ProductiveRage** [comment]
I'm struggling to implement this. I may have understood what is and isn't possible, so here's what I'm trying to do:

I've created a project (a class library with Bridge.Min and Bridge.Html5) called "ExampleComponentWithBridgeResources" which has some C# that defines a component class and that has a "myStyle.css" file that I want to be used anywhere that the component is drawn.

Then I've created a project called "ExampleApplication" (again, a class library with Bridge.Min and Bridge.Html5) which references "ExampleComponentWithBridgeResources". This has a [Ready] method that will draw an instance of the component to Document.Body and has a "bridge.json" configuration file that will combine scripts and build to "../Host/Bridge/output".

Finally, I have a .NET web application project called "Host" that is used to load JavaScript and style sheets.

What I want is for the C# in "ExampleComponentWithBridgeResources" and "ExampleApplication" to be combined and put in "Host/Bridge/output". I also want the "myStyle.css" file from "ExampleComponentWithBridgeResources" to end in up the "Host" folder somewhere.

I added the following bridge.json file to the "ExampleComponentWithBridgeResources" project, which successfully includes the style sheet as a resource in the binary but it doesn't include the JavaScript for the component -

{
  "resources": [
    {
      "name": "myStyle.css",
      "output": "Css/",
      "files": [ "myStyle.css" ]
    }
  ]
}

It also injects that style sheet into the combined JavaScript file.

Do I need to specify a "resources" entry for the "ExampleComponentWithBridgeResources" JavaScript and another for "myStyle.css"?

**Comment by ProductiveRage** [comment]
By changing the bridge.json file in "ExampleComponentWithBridgeResources", I can get both the JavaScript and the style sheet included as resources in the binary -

    {
      "resources": [
        {
          "name": "exampleComponentWithBridgeResources.js",
          "files": [ "bin/Debug/exampleComponentWithBridgeResources.js" ]
        },
        {
          "name": "myStyle.css",
          "output": "Css/",
          "files": [ "myStyle.css" ]
        }
      ]
    }

.. but they are still both being included in the combined script output.

If I disable "combineScripts" then I can see that "myStyle.css" appear in the Host/Bridge/output folder - so I guess that the problem is with the "combineScripts" option? (That, presumably, it should only combine ".js" resources and keep any others separate?)

**Comment by LeonidVeriga** [comment]
@ProductiveRage,

Yes, we will refine `combineScripts` option, thanks for pointing this out.

Using `resources` option, we can just combine the scripts to include **bridge.js** by:
```js
{
  "combineScripts": false,
  "resources": [
    {
      "name": "exampleComponentWithBridgeResources.js",
      "files": [
          "your_output_folder/bridge.js"
          "your_output_folder/exampleComponentWithBridgeResources.js"
      ]
    },
    {
      "name": "myStyle.css",
      "files": [ "myStyle.css" ]
    }
  ]
}
```

**Comment by ProductiveRage** [comment]
I'm afraid that I don't quite follow your example - are you suggesting that that would be one way to workaround the problem? Would I change the bridge.json file in the "ExampleComponentWithBridgeResources" or the "ExampleApplication" project? If it would be in the "ExampleApplication" project then I guess that I'd need to keep track of every other project or dependency that it referenced, which wouldn't scale very easily.. unless there was a way to use wildcards in the "files" entries within resources, so I could just specify "*.js"?

If the "combineScripts" option is going to be refined for 15.4, then I'll just wait for that :) If you need any further clarification on how we'd like to use the feature then please let me know.

**Comment by ProductiveRage** [comment]
After playing around a bit, I've got the "ExampleComponentWithBridgeResources" bridge.json file to be the following:

    {
      "resources": [
        {
          "name": "exampleComponentWithBridgeResources.js",
          "files": [ "bin/Debug/exampleComponentWithBridgeResources.js" ]
        },
        {
          "name": "myStyle.css",
          "files": [ "myStyle.css" ]
        }
      ]
    }

and the "ExampleApplication" bridge.json to be

    {
      "resources": [
        {
          "name": "exampleApplication.js",
          "output": "../Host/Bridge/output",
          "files": [
            "bin/Debug/bridge.js",
            "bin/Debug/bridge.react.js",
            "bin/Debug/productiveRage.immutable.js",
            "bin/Debug/productiveRage.immutable.extensions.js",
            "bin/Debug/cssInject.js",
            "bin/Debug/common.js",
            "bin/Debug/exampleComponent.js",
            "bin/Debug/exampleComponentWithBridgeResources.js",
            "bin/Debug/exampleApplication.js"
          ]
        },
        {
          "name": "myStyle.css",
          "output": "../Host/Bridge/stylesheets",
          "files": [ "bin/Debug/myStyle.css" ]
        }
      ]
    }

This works, in that the "Host" web application gets a combined "exampleApplication.js" file in its "Bridge/output" folder and it gets the "myStyle.css" file in its "Bridge/stylesheets" folder.

However, as you can see, it's very unwieldy. It would be excellent if "myStyle.css" could be specified only in the "ExampleComponentWithBridgeResources" bridge.json and for the "ExampleApplication" bridge.json to not have to specify every file that is required.

I'm also wondering if I'm doing something wrong with including "bin/Debug" each time. What about when I want to build from "bin/Release"? Is it possible to include minified and non-minified versions?

**Comment by geoffreymcgill** [comment]
Hi @ProductiveRage, 

We discussed your `bin/Debug/` configuration and we will be adding support for `$(OutputPath)` tokens. Same syntax that is used in .csproj and .targets files. Your `files` paths could then be updated to the following:

```js
"$(OutputPath)bridge.js",
```

The goal is to have this available for the 15.4 release.

**Comment by LeonidVeriga** [comment]
@ProductiveRage,

Regarding `bin/Debug`, as stated above we will support `$(OutputPath)` token.
Another option is to use to #1033 feature - **bridge.Debug.json**/**bridge.Release.json**.
And one more option would be trying to output and keep scripts in folders not depending on build configuration for all projects.

**Comment by LeonidVeriga** [comment]
@ProductiveRage, we created a branch for this feature implementation. It would be great if you could look at its [description](https://github.com/bridgedotnet/Bridge/pull/1990#issue-185095634), check out the code and provide a feedback. It is a current implementation, `$(OutputPath)` token is in progress.

**Comment by ProductiveRage** [comment]
I have tested the "combineScripts" fix and the change to the resource file specification (apart from the "$(OutputPath)", which I understand you to be saying is not ready yet).

My "ExampleComponentWithBridgeResources" bridge.json file looks like this:

    {
      "resources": [
        {
          "name": "exampleComponentWithBridgeResources.js",
          "files": [ "bin/Debug/exampleComponentWithBridgeResources.js" ]
        },
        {
          "output":  "../stylesheets",
          "name": "MyOtherTextBox.less",
          "files": [ "MyOtherTextBox.less" ]
        }
      ]
    }

and my "ExampleApplication" bridge.json file looks like this:

    {
      "combineScripts": true,
      "output": "../Host/Bridge/output"
    }

And it works!

The combined JavaScript from ExampleApplication (including the JavaScript from "ExampleComponentWithBridgeResources") appears in

/Host/Bridge/output

and the style sheet from "ExampleComponentWithBridgeResources" appears in

/Host/Bridge/stylesheets

which is exactly what I wanted! :)

**Comment by LeonidVeriga** [comment]
@ProductiveRage, thank you for the detailed feedback (especially for a positive one!).

**Comment by LeonidVeriga** [comment]
@ProductiveRage 

> Is it possible to include minified and non-minified versions?

1) Yes, you can include both minified and non-minified versions in **ExampleComponentWithBridgeResources**:
```js
{
  "outputFormatting": "Both",
  "resources": [
    {
      "name": "exampleComponentWithBridgeResources.js",
      "files": [ "bin/Debug/exampleComponentWithBridgeResources.js" ]
    },
    {
      "name": "exampleComponentWithBridgeResources.min.js",
      "files": [ "bin/Debug/exampleComponentWithBridgeResources.min.js" ]
    }
  ]
}
```

2) Or, having embedded just non-minified output in **ExampleComponentWithBridgeResources**:
```js
{
  "outputFormatting": "Formatted",
  "resources": [
    {
      "name": "exampleComponentWithBridgeResources.js",
      "files": [ "bin/Debug/exampleComponentWithBridgeResources.js" ]
    }
  ]
}
```
You can set `"outputFormatting"` to `"Minified"` or `"Both"` in **ExampleApplication** bridge.json:
```js
{
  "outputFormatting": "Minified|Both"
  "combineScripts": true,
  "output": "../Host/Bridge/output"
}
```
Compiling **ExampleApplication**, it will minify **ExampleComponentWithBridgeResources**'s embedded resource output as well (if `"Both"` option being used then it will output both minified and non-minified resources).

3) If only minified version required then in **ExampleComponentWithBridgeResources** use:
```js
{
  "outputFormatting": "Minified",
  "resources": [
    {
      "name": "exampleComponentWithBridgeResources.min.js",
      "files": [ "bin/Debug/exampleComponentWithBridgeResources.min.js" ]
    }
  ]
}
```
Regardless of the `"outputFormatting"` option in **ExampleApplication**, it will have only minified resource version.

**Comment by LeonidVeriga** [comment]
We created three separate issues to manage this request:
- #2008 CombineScripts mixes up js and non-js output
- #2009 Embedding resources output folder specification 
- #2010 OutputPath token for resources.files setting
