### ISSUE TITLE
Project post build event task is called before Bridge GenerateScript task

### ISSUE THREAD

**Issue by yuvaltz** [bridgedotnet/Bridge#1961]
### Expected

Post build event tasks should be called after bridge GenerateScript task.
### Actual

GenerateScript is run at **AfterBuild** which is called after the post build event task.
Post build events that expects Bridge's output are failing.

A test solution
[BridgeBuildEventTest.zip](https://github.com/bridgedotnet/Bridge/files/533853/BridgeBuildEventTest.zip)

**Comment by yuvaltz** [comment]
A further investigation:

The **AfterBuild** tasks (which is where the **GenerateScript** task runs) is called after the **CoreBuild** task:
[Microsoft.Common.CurrentVersion.targets:761](https://github.com/Microsoft/msbuild/blob/master/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L761)

```xml
<PropertyGroup>
  <BuildDependsOn>
    BeforeBuild;
    CoreBuild;
    AfterBuild
  </BuildDependsOn>
</PropertyGroup>
<Target Name="Build" DependsOnTargets="$(BuildDependsOn)" ... />
```

And the **PostBuildEvent** task is called before the **CoreBuild** task:
[Microsoft.Common.CurrentVersion.targets:813](https://github.com/Microsoft/msbuild/blob/master/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L813)

```xml
<PropertyGroup>
  <CoreBuildDependsOn>
    ..
    PreBuildEvent;
    ..
    Compile;
    ..
    PrepareForRun;
    ..
    PostBuildEvent
  </CoreBuildDependsOn>
</PropertyGroup>
<Target Name="CoreBuild" DependsOnTargets="$(CoreBuildDependsOn)" ... />
```

The **Compile** task depends on **AfterCompile** task:
[Microsoft.Common.CurrentVersion.targets:3008](https://github.com/Microsoft/msbuild/blob/master/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L3008)
```xml
<PropertyGroup>
  <CompileDependsOn>
    ...
    BeforeCompile;
    ...
    CoreCompile;
    ...
    AfterCompile;
  </CompileDependsOn>
</PropertyGroup>
<Target Name="Compile" DependsOnTargets="$(CompileDependsOn)"/>
```

So theoretically **GenerateScript** should run at the **AfterCompile** task instead of **AfterBuild** which will make it run before **PostBuildEvent**.

Currently **GenerateScript** must run after the **PrepareForRun** task (which copies assemblies to the target directory), at it tries to load the **Bridge.dll** to get the file version info (when the task fails MSBuild creates an endless process recusion and gets stuck).

Adding the **GenerateScript** task to **PostBuildEventDependsOn** list works too, but it less elegant.

**Comment by LeonidVeriga** [comment]
Hi @yuvaltz,

Thank you for the nice catch, investigation and solution provided.

We will try to resolve this issue in **15.4**.

**Comment by LeonidVeriga** [comment]
Hi @yuvaltz,

We are thinking of this change to 
```xml
<Target Name="AfterBuild">
  <GenerateScript ... />
</Target>
```
Revised
```xml
<PropertyGroup>
   <PrepareForRunDependsOn>$(PrepareForRunDependsOn);BridgeGenerateScript</PrepareForRunDependsOn>
</PropertyGroup>

<Target Name="BridgeGenerateScript">
  <GenerateScript ... />
</Target>
```
