### ISSUE TITLE
Visual Studio 2015 support

### ISSUE THREAD

**Issue by wizzard0** [bridgedotnet/Bridge#1962]
VSIX installation reports:

> This extension is not compatible, will cause stability issues and will not be supported in RC

Bridge 15.2

**Comment by LeonidVeriga** [comment]
An interesting issue... 

Just reinstalled the VSIX to an old VS2013:
> Install to Microsoft Visual Studio Professional 2013 completed successfully. The extension has been installed to ...

Can you provide some more info like OS, Visual Studio details.

**Comment by geoffreymcgill** [comment]
I tested the latest .vsix with Visual Studio 2015 and there were no issues. Everything worked as expected. 

We're going to need specific details on how to reproduce this issue.

**Comment by wizzard0** [comment]
Sorry, not 2015 but "15" previee 5. My bad.

**Comment by geoffreymcgill** [comment]
There's not much we're going to do with this right now. It appears VS "15" currently does not support .vsix installers. I'm not sure why. Once it's out of **preview** we'll take a look.

**Comment by wizzard0** [comment]
They revamped a lot in the core (and minimal install of Preview 5 is really just 500 mb of disk space) and one of consequences is that they're not going to support VSIX 1.x/2.x installers/plugins, only new 3.x (that use new extensibility APIs)
