### ISSUE TITLE
Bridge.OutputByAttribute doesn't have an effect

### ISSUE THREAD

**Issue by yuvaltz** [bridgedotnet/Bridge#1963]
### Expected

Adding an `[assembly: Bridge.OutputBy(Bridge.OutputBy.Project)]` declaration should work the same as having a **bridge.json** configuration file with

``` json
{
    "outputBy": "Project"
}
```
### Actual

Without a **bridge.json** file, the output behavior stays the default (a separate js file for each namespace).

**Comment by geoffreymcgill** [comment]
Thanks for submitting this issue. This feature should work; at least we thought it was working. Obviously did not have any unit tests to confirm. 

We will get this working.
