### ISSUE TITLE
String.IsNullOrWhiteSpace should include line break

### ISSUE THREAD

**Issue by yuvaltz** [bridgedotnet/Bridge#1964]
### Expected
Line break (\r, \n) and tab (\t) should be considered a white space

### Actual
`String.IsNullOrWhiteSpace("\t\r\n")` returns false

### Steps To Reproduce
[Deck](http://deck.net/bbc9be2b694ba1c22a3d221e39f3b77b)
```csharp
public class Program
{
    public static void Main()
    {
        Console.WriteLine(String.IsNullOrWhiteSpace("\t")); // should be true
        Console.WriteLine(String.IsNullOrWhiteSpace("\r")); // should be true
        Console.WriteLine(String.IsNullOrWhiteSpace("\n")); // should be true
    }
}
```

**Comment by LeonidVeriga** [comment]
Yes, a defect. Thank you for reporting, @yuvaltz.

Targeted for **15.4**.
