### ISSUE TITLE
Compilation failed when creating anonymous class without field definition

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#197]
C# code:
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using Bridge;

namespace Demo
{
    public class A
    {
        public int Count { get; set; }
    }

    public class App
    {
        [Ready]
        public static void Main()
        {
            var counts = new[] { new A() { Count = 1 } };
            var a = counts.Select(x => new { x.Count });
        }
    }
}
```
Compilation error:
"Object reference not set to an instance of an object.    at Bridge.Translator.AbstractObjectCreateBlock.WriteObjectInitializer(IEnumerable`1 expressions, Boolean changeCase) in c:\NET\Bridge\Builder\Translator\Emitter\Blocks\AbstractObjectCreateBlock.cs:line 57"

Please note adding field definition will work out:
```
Select(x => new { SomeField = x.Count });
```

**Comment by vladsch** [comment]
Fixed (forgot to mention about it in commit)
