### ISSUE TITLE
RuntimeHelpers.RunClassConstructor support

### ISSUE THREAD

**Issue by yuvaltz** [bridgedotnet/Bridge#1970]
I've noticed that when getting a type by its full name it gets initialized, but getting it by its qualified name doesn't get it initialized.
The exact moment when a type is being initialized may vary between different runtime environments, so supporting `System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor` can help making sure a type is initialized at certain point (right now calling `Type.GetType(type.FullName)` does the job).

[Deck](http://deck.net/622736fe7a0b4713171d698e47e9705c)
```csharp
using System;

namespace Demo
{
    public class Test
    {
        [Bridge.Reflectable(true)]
        public static readonly bool IsInitialized = GetIsInitializedValue();

        static Test()
        {
            Console.WriteLine("** Test class initialized **");
		}

        private static bool GetIsInitializedValue()
        {
            return true;
        }
    }

    public class Program
    {
        public static void Main()
        {
            Console.WriteLine("Get type by assembly qualified name");
            var type1 = Type.GetType("Demo.Test, Demo");
            Console.WriteLine(type1.GetField("IsInitialized").GetValue(null));

            Console.WriteLine("Get type by name");
            var type2 = Type.GetType("Demo.Test");
            Console.WriteLine(type2.GetField("IsInitialized").GetValue(null));
        }
    }
}
```

**Comment by LeonidVeriga** [comment]
`RuntimeHelpers.RunClassConstructor` is implemented.
However it's argument is `Type` (instead of `RuntimeTypeHandle` in .NET).
