### ISSUE TITLE
Implement System.ComponentModel.DataAnnotations classes

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#1974]
## See Also

* http://forums.bridge.net/forum/general/feature-requests/2922-support-for-system-componentmodel-dataannotations

**Comment by HallofFamer** [comment]
umm any updates on this?

**Comment by geoffreymcgill** [comment]
> @HallofFamer - umm any updates on this?

Currently, this feature request is tagged as `up-for-grabs` and would have to be developed by the community (at least started). 

Unfortunately the core development team at Bridge is assigned to other tasks and will not be able to implement in the near future.

**Comment by geoffreymcgill** [comment]
A pull request has been submitted by @Dia6lo implement System.ComponentModel.DataAnnotations classes. The PR is being reviewed and we are likely to accept into the **master** branch.

**Comment by DierkDroth** [comment]
Hmm ... I just updated from latest sources and get this:
https://dev.deck.net/eb0b74a05375e1a57e14f779352ce1ff

Isn't the purpose of this feature that this code should just compile fine? What am I missing?
