### ISSUE TITLE
New Union type - Same as Any

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#1976]
Create a new **Union** type to parallel the use of [Union](https://www.typescriptlang.org/docs/handbook/advanced-types.html) type in TypeScript.

http://deck.net/866aa5b3b64612986370c9e1d6179805

```cs
public class Program
{
    public static void Main()
    {
        Log("test");
        Log(true);
    }
    
    public static void Log(Union<string, bool> value)
    {
        Console.WriteLine(value);
    }
}
```

The **Union** will be exactly the same as the existing **Any** type in Bridge. The **Any** type will be repurposed to inherit from **DynamicObject**, which will allow any type.

Generic **Any<T1, T2>** classes to be marked as `[Obsolete]` and will be removed in Bridge 16.0.

Related to Issue #1531.

**Comment by vladsch** [comment]
> The Any type will be repurposed to inherit from DynamicObject, which will allow any type.
Why not to use `object` type for that purpose (or `dynamic`), it is standard way for .NET
