### ISSUE TITLE
GenerateScript configuration parameters support 

### ISSUE THREAD

**Issue by yuvaltz** [bridgedotnet/Bridge#1984]
* VS is to provide projects settings that we require to compile (no reading **csproj** file in this case)
* These projects settings can be specified for **bridge.exe** console (parameters **--settings|-S**); if some of them are not provided in console mode then it will try to read from **csproj** (note parameters --configuration and --platform is mandatory)
* VS task **BridgeGenerateScript** in **Bridge.Min.targets** has additional parameters:
  - $Compile (i.e. sources)
  - $AssemblyName
  - $CheckForOverflowUnderflow
  - $Configuration
  - $DefineConstants
  - $OutDir
  - $OutputPath
  - $OutputType
  - $Platform
  - $RootNamespace;

##
Currently the **GenerateScript** task gets most of its configuration implicitly by parsing the csproj file.
So there is no way for example, to modify the Compile items list without changing the csproj file.

``` xml
<GenerateScript
  DefineConstants="$(DefineConstants)"
  OutputPath="$(OutputPath)"
  Configuration="$(Configuration)"
  Assembly="@(IntermediateAssembly)"
  AssembliesPath="$(OutputPath)"
  ProjectPath="$(MSBuildProjectFullPath)" />
```

Support of passing some or all the configuration to the **GenerateScript** task by parameters, like it's being passed to the [**Csc** task](https://github.com/Microsoft/msbuild/blob/master/src/XMakeTasks/Microsoft.CSharp.CurrentVersion.targets#L246), could help on some scenarios (like using tasks that auto generate classes at compile time*).
## 

\* WPF (and Granular too), has a task that supports defining classes in xaml (using the `x:Class` directive). The task auto-generates partial classes with the declared elements fields and class initialization implementation. These partial classes are added to the Compile items list at compile time, and are not declared in the csproj file.

### See Also
#2227

**Comment by LeonidVeriga** [comment]
We will support the following additional parameters in GenerateScript task:
- AssemblyName="$(AssemblyName)"
- CheckForOverflowUnderflow="$(CheckForOverflowUnderflow)"
- OutDir="$(OutDir)"
- OutputType="$(OutputType)"
- Platform="$(Platform)"
- RootNamespace="$(RootNamespace)"
- Sources="@(Compile)" />
