### ISSUE TITLE
Console.WriteLine() / Bridge Console breaking external Javacript (Google Identity Platform)

### ISSUE THREAD

**Issue by calcock** [bridgedotnet/Bridge#1993]
This is a bit of a strange one - I'm attempting to integrate some Bridge code with the Google Identity Platform, and have constructed a few classes to represent the types that this API exposes.  In doing so I had a`Console.WriteLine(g.GetType())` in the method prior to calling the `signIn()` methods so I could see what was going on.  This resulted in the callback passed in the .then() method not to be called.  Removing the `Console.WriteLine(g.GetType()`) call results in the call back being fired as expected.
The lines in question are commented in the linked Deck below - labelled `// (A)`.  Similar code also breaks it (labelled `//(B)` )
### Expected

Assuming a valid Google account authenticated, the code in the Action passed to `.then()` should fire which results in a `Console.WriteLine` message being recorded in the Bridge Console
### Actual

With the `Console.WriteLine(g.GetType());` line, the Google Account login works, but the callback action in the `.then()` does not fire
### Steps To Reproduce

This Deck link is as reduced as I can make it to highlight the issue - its still rather long I'm afraid.
[Deck Sample](http://deck.net/85070d3561856b6f38776d26ff5eab56)

Click 'Run Code', and log in with a valid Google Account

**Comment by calcock** [comment]
A little update on this - it seems to be the Bridge Console that is breaking the code - any calls to Console.WriteLine() prior to the `.then()` on the `.signIn()` call seems to be breaking this.
Disabling the console using the following:
```
        [Init(InitPosition.Top)]
        private static void DisableConsole()
        {
            /*@
			Bridge.Console.log = function(message) { console.log(message); };
			Bridge.Console.error = function(message) { console.error(message); };
			Bridge.Console.debug = function(message) { console.debug(message); };
			 */
        }
```
Also fixes the issue, and the log messages are recorded in the Browser console successfully, and the code executes successfully.

This suggests that the implementation of the Bridge Console is interfering with the 3rd party JavaScript in some way.

**Comment by DanTup** [comment]
I noticed a bunch of Console rendering code in bridge.js a while back and wondered what it all was; I guess it was for this (I hadn't seen it in the browser yet).

I think it's good for Deck, but it seems a bit weird having two consoles in other production apps (which are aimed at dev, not end users).. Wouldn't this be better as an optional package or built into Deck to reduce the footprint?

**Comment by geoffreymcgill** [comment]
Hi @calcock - It appears `gapi.auth2` is undefined in your sample. Can you update this [Deck](http://deck.net/4c85bd25790fb6c88af0219f5a17fc1a) to correct.

**Comment by geoffreymcgill** [comment]
There's also the **Bridge.Html5.Console** package if you would like C# access to the native browser developer tool `console`. Using this API would avoid any calls to the **Bridge.Console**.

https://www.nuget.org/packages/bridge.html5.console

You can install the package using the following NuGet command, or by finding the package in the NuGet Package Explorer:

```
install-package bridge.html5.console
```

**Example**

```cs
Bridge.Html5.Console.Log("test");

// output
console.log("test");
```

A good overview of the three **Console** classes is available at:
https://github.com/bridgedotnet/Bridge/issues/984#issuecomment-186102370

Also related to #1483.

We plan to improve the configurability and functionality of **Bridge.Console**. Ideas are being collected in #1994.

**Comment by calcock** [comment]
@geoffreymcgill its defined in the injected Google Script:
```
var ScriptTag = new HTMLScriptElement() { Src = "https://apis.google.com/js/platform.js" };
Document.Body.AppendChild(ScriptTag);
```
It works OK for me as is in Chrome, IE and Firefox

**Comment by DanTup** [comment]
It seems a little strange to me to ship all the console code inside bridge.json and have another package to disable it. A switch to toggle is better, but it does feel a bit bloated to include a dev feature in all production builds that you might not want. Wouldn't it be better to have it in a separate package that you pull in if you want it, but otherwise it's not there?

**Comment by geoffreymcgill** [comment]
As of Bridge 16.0, **Bridge Console** is emitted as a separate **bridge.console.js** which can be added to the applications .html. To prevent **Bridge Console** from rendering, just remove **bridge.console.js**.

More details in #1994.
