### ISSUE TITLE
'is'/'as' operators is slow.

### ISSUE THREAD

**Issue by AndreyZM** [bridgedotnet/Bridge#1995]
In most cases 'is' operator has huge overhead. In cases when type is know and its a c# class js 'instanceof' operator is much faster.

Benchmark:
[Deck](http://deck.net/39ec03ab466545dd135ca99547495be2)

Maybe you can add a optimized "$is"/"$as" methods to compiled prototypes and call them if its exists in type.

**Comment by geoffreymcgill** [comment]
Hi @AndreyZM - Thanks for informing us of the performance issue. We are investigating right now and hope to make some improvements for the 15.4 release.

**Comment by vladsch** [comment]
Related with https://github.com/bridgedotnet/Bridge/issues/1957

**Comment by LeonidVeriga** [comment]
### Bridge 15.3 with #1957
|  | Chrome | FF | Edge |
| --- | --- | --- | --- |
| 1 | 291 | 744 | 1651 |
| 2 | 381 | 971 | 5171 |
| 3 | 166 | 325 | 844 |
| 4 | 421 | 98  | 459 |
| 5 | 520 | 489 | 123 |
| 6 | 92  | 105 | 756 |
| 7 | 53  | 84  | 161 |
| 8 | 55  | 657 | 429 |
| 9 | 342 | 237 | 433 |


### Bridge 15.4 with #1957 and #1995
|  | Chrome | FF | Edge |
| --- | --- | --- | --- |
| 1 | 166 | 84  | 272 |
| 2 | 206 | 740 | 2322|
| 3 | 41  | 59  | 438 |
| 4 | 30  | 67  | 405 |
| 5 | 30  | 68  | 405 |
| 6 | 32  | 74  | 387 |
| 7 | 25  | 68  | 26  |
| 8 | 237 | 79  | 631 |
| 9 | 44  | 116 | 283 |

**Comment by geoffreymcgill** [comment]
<img width="872" alt="screenshot 2016-11-26 23 45 30" src="https://cloud.githubusercontent.com/assets/62210/20646140/730272bc-b432-11e6-99c1-ca27f3cef379.png">
