### ISSUE TITLE
Feature: DOM mutation observer API 

### ISSUE THREAD

**Issue by d-p-y** [bridgedotnet/Bridge#2005]
### Expected

It would be nice to have [DOM mutation observer](https://developer.mozilla.org/en/docs/Web/API/MutationObserver) available in bridgedotnet. It makes it possible to efficiently notice changes to document (elements added or removed, attributes changed). This powerful API permits scenarios such as: element was added deep into document tree and after it is attached one would like to call some "on element attached" code.

### Actual

It currently is not built in, I've developed wrapper and tested it in my personal project.
Pull request will be sent in a while.

**Comment by geoffreymcgill** [comment]
Thanks for the excellent pull-request. We're taking a good look at this and have tagged for possible acceptance into the 15.4 release.
