### ISSUE TITLE
Defect: subscription to event defined in generic interface via extension method silently fails to subscribe

### ISSUE THREAD

**Issue by d-p-y** [bridgedotnet/Bridge#2013]
### Expected

Subscribing to event should work.

### Actual
It silently fails. Using 'Steps to Reproduce' generated code should be 
``js
self.Ev = Bridge.fn.combine(self.Ev,$_.Demo.EvExtension.f1);
``

generated code is:
``js
self["Demo$IEvGen$1$" + Bridge.getTypeAlias(T) + "$Ev"] = Bridge.fn.combine(self["Demo$IEvGen$1$" + Bridge.getTypeAlias(T) + "$Ev"], $_.Demo.EvExtension.f1);
``

Pull request will be submitted in a while

### Steps To Reproduce

[Deck](http://deck.net/c4301542f49f4390a3a6fa4c03f141e4)

```cs

    public interface IEvGen<T>
    {
        event Action Ev;
    }
    
    public class EvGen<T> : IEvGen<T>
    {
        public event Action Ev;
        public bool HasListeners {get {return Ev != null;}}
    }
    
    public static class EvExtension
    {
        public static void AttachViaExtension<T>(this IEvGen<T> self)
        {
            self.Ev += () => {};
        }
    }

    public class Program { 
        
	[Ready]
        public static void Main()
        {
             var sut = new EvGen<int>();
			 
            IEvGen<int> sutIface = new EvGen<int>();
            sutIface.AttachViaExtension();
                        
            Console.WriteLine("bug? " + !sut.HasListeners);
        }
    }
```

**Comment by vladsch** [comment]
Why handler is attached to `sutIface` but you check `sut`? May be need to use `IEvGen<int> sutIface = sut;`?
Also, this test works fine in 15.4 (current master branch). Please note that expected code should be long alias name ("Demo$IEvGen$1$" + Bridge.getTypeAlias(T) + "$Ev", not just "Ev") because it is interface member which can conflicts with another interfaces members. Bridge generates aliases to avoid conflicts
See https://github.com/bridgedotnet/Bridge/issues/1025 issue for more information

I will close the issue. Please open it if you find another similar issue

**Comment by d-p-y** [comment]
Hi vladsch,
Indeed during cleanup of my test I made a mistake. Code should be like you wrote: 
IEvGen<int> sutInterface = sut;
Thanks for explaining use of those aliases. 
Just for the record: it is failing in latest official release 15.3 and also in latest public master a831f6d. I guess that fix is not yet public?

**Comment by vladsch** [comment]
For me it works fine with latest master code. Do you have exactly the same generated javascript code if use master branch and online deck.net?

For me, the following code is generated for `AttachViaExtension`
```
attachViaExtension: function (T, self) {
       self["Demo$IEvGen$1$" + Bridge.getTypeAlias(T) + "$addEv"]($_.Demo.EvExtension.f1);
}
```

**Comment by d-p-y** [comment]
I've change example to be more user friendly: 
[Deck](http://deck.net/42e65e194ce6e22e9dec81abf2419f72)

as you can see there it generates code 
``
            attachViaExtension: function (T, self) {
                self["Demo$IEvGen$1$" + Bridge.getTypeAlias(T) + "$Ev"] = Bridge.fn.combine(self["Demo$IEvGen$1$" + Bridge.getTypeAlias(T) + "$Ev"], $_.Demo.EvExtension.f1);
            }
``

Thing is that code runs BUT listener is not attached to event - you don't see expected "line 2" in console. It silently fails to subscribe listener to event. This is bug. self.Ev should not be null.
I don't argue about you of aliases as you are correct in that aspect.

Original (fixed) example is:
[Deck](http://deck.net/69b5840cafe3dba5d29621547c3b1462)
There code is also generated 
``
            attachViaExtension: function (T, self) {
                self["Demo$IEvGen$1$" + Bridge.getTypeAlias(T) + "$Ev"] = Bridge.fn.combine(self["Demo$IEvGen$1$" + Bridge.getTypeAlias(T) + "$Ev"], $_.Demo.EvExtension.f1);
            }
``
Thing again is that listener is not attached to event

**Comment by vladsch** [comment]
Yes, I see the problem in Deck generated script but Deck uses last public release, not latest code from master. In master, generated code is correct. I tested it and handler is attached. I will add unit test for your test case

**Comment by d-p-y** [comment]
I've checked out latest sources - at the time of writing latest commit is a831f6d. Is this latest "master" that you are referring to?
In Visual Studio I've cleaned up and then recompiled whole Bridge.sln solution. Then I've used those release dlls in the test project and compiled our former example [Deck](http://deck.net/69b5840cafe3dba5d29621547c3b1462). 

Code that was generated is
```js
/**
 * @version 1.0.6151.33205
 * @copyright dominik
 * @compiler Bridge.NET 15.3.0
 */
Bridge.assembly("BridgeNetEval", function ($asm, globals) {
    "use strict";

    Bridge.define("WebClient.EvExtension", {
        statics: {
            attachViaExtension: function (T, self) {
                self["WebClient$IEvGen$1$" + Bridge.getTypeAlias(T) + "$Ev"] = Bridge.fn.combine(self["WebClient$IEvGen$1$" + Bridge.getTypeAlias(T) + "$Ev"], $_.WebClient.EvExtension.f1);
            }
        }
    });

    var $_ = {};

    Bridge.ns("WebClient.EvExtension", $_);

    Bridge.apply($_.WebClient.EvExtension, {
        f1: function () {
        }
    });

    Bridge.definei("WebClient.IEvGen$1", function (T) { return {
        $kind: "interface"
    }; });

    Bridge.define("WebClient.Program", {
        statics: {
            config: {
                init: function () {
                    Bridge.ready(this.main);
                }
            },
            main: function () {
                var sut = new (WebClient.EvGen$1(System.Int32))();

                var sutIface = sut;
                WebClient.EvExtension.attachViaExtension(System.Int32, sutIface);

                Bridge.Console.log("bug? " + System.Boolean.toString(!sut.getHasListeners()));
            }
        },
        $entryPoint: true
    });

    Bridge.define("WebClient.EvGen$1", function (T) { return {
        inherits: [WebClient.IEvGen$1(T)],
        config: {
            events: {
                Ev: null
            },
            alias: [
            "addEv", "WebClient$IEvGen$1$" + Bridge.getTypeAlias(T) + "$addEv",
            "removeEv", "WebClient$IEvGen$1$" + Bridge.getTypeAlias(T) + "$removeEv"
            ]
        },
        getHasListeners: function () {
            return !Bridge.staticEquals(this.Ev, null);
        }
    }; });
});
```

... yet still it gives me "Bug? True" indicating that no listener is attached.
Afterwards I've manually updated generated JS code to have "$addEv" instead of "$Ev" as you've written above that it fixes code:

```
            attachViaExtension: function (T, self) {
                self["WebClient$IEvGen$1$" + Bridge.getTypeAlias(T) + "$addEv"] = Bridge.fn.combine(self["WebClient$IEvGen$1$" + Bridge.getTypeAlias(T) + "$addEv"], $_.WebClient.EvExtension.f1);
            }
```
...but it didn't help. 
Either latest public master doesn't contain fix OR I'm doing something very very wrong here :/
