### ISSUE TITLE
Calling Math.Log with two parameters (both Decimal) generates a javascript error

### ISSUE THREAD

**Issue by Porl91** [bridgedotnet/Bridge#2018]
Example of how to reproduce this issue. If you look in the dev tools console on this demo:
http://deck.net/851b2edffc2198abd30d05859dc10054

It shows: 'Uncaught Error: [DecimalError] Invalid argument: 2' to the console. 

'2' in this case is the base of the logarithm and the expected value is '4'.

I've also noticed there's a slight inconsistency between the accepted parameter types for this method. In C# this method either takes one or two parameters (both of which are doubles) whereas in Bridge the first overload takes one double and the second overload takes two decimals. This doesn't present any issues in my applications although I thought I'd just mention it.

**Comment by Porl91** [comment]
Ah I see this is a duplicate of issue 1566. Closing!

**Comment by LeonidVeriga** [comment]
Duplicate of #1566
