### ISSUE TITLE
Invalid javascript for "this += 1" in structs

### ISSUE THREAD

**Issue by wischi-chr** [bridgedotnet/Bridge#2038]
### Expected

```js
increment: function () {
    (Demo.App.SimpleStruct.op_Addition(this, 1)).$clone(this);
}
```

_...or something like that. FYI: This is the result from compiling_ **`this = this + 1`**

### Actual

_but when compiling_ **`this += 1`** _the resulting javascript is invalid_

```js
increment: function () {
    (= Demo.App.SimpleStruct.op_Addition(this, 1);
}
```

### Steps To Reproduce

[Deck](http://deck.net/1fa43e0f3c70ca6d7b1b66f0f6128c3e)

```cs
public class App
{	
    public struct SimpleStruct
    {
        public static SimpleStruct operator +(SimpleStruct t, int val)
        {
            return t;
        }

        public void Increment()
        {
            this += 1;
        }
    }
}
```

**Comment by geoffreymcgill** [comment]
Hi @wischi-chr - Thanks for submitting this report and for providing the simplified sample demonstrating how to reproduce. 

We are investigating.
