### ISSUE TITLE
Implement Attribute.GetCustomAttributes

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#2043]
As specified here:
https://msdn.microsoft.com/en-us/library/system.attribute.getcustomattributes(v=vs.110).aspx

**Comment by LeonidVeriga** [comment]
**Implemented in PR #2118**:

| Name | Description |
| --- | --- |
| [GetCustomAttributes(Assembly)](https://msdn.microsoft.com/en-us/library/y1375e30(v=vs.110).aspx) | Retrieves an array of the custom attributes applied to an assembly. A parameter specifies the assembly. | 
| [GetCustomAttributes(Assembly, Boolean)](https://msdn.microsoft.com/en-us/library/f2z5sd1c(v=vs.110).aspx) | Retrieves an array of the custom attributes applied to an assembly. Parameters specify the assembly, and an ignored search option. | 
| [GetCustomAttributes(Assembly, Type)](https://msdn.microsoft.com/en-us/library/4ske1977(v=vs.110).aspx) | Retrieves an array of the custom attributes applied to an assembly. Parameters specify the assembly, and the type of the custom attribute to search for. | 
| [GetCustomAttributes(Assembly, Type, Boolean)](https://msdn.microsoft.com/en-us/library/ms130870(v=vs.110).aspx) | Retrieves an array of the custom attributes applied to an assembly. Parameters specify the assembly, the type of the custom attribute to search for, and an ignored search option. | 
| [GetCustomAttributes(MemberInfo)](https://msdn.microsoft.com/en-us/library/bfwhbey7(v=vs.110).aspx) | Retrieves an array of the custom attributes applied to a member of a type. A parameter specifies the member. | 
| [GetCustomAttributes(MemberInfo, Boolean)](https://msdn.microsoft.com/en-us/library/ms130868(v=vs.110).aspx) | Retrieves an array of the custom attributes applied to a member of a type. Parameters specify the member, the type of the custom attribute to search for, and whether to search ancestors of the member. | 
| [GetCustomAttributes(MemberInfo, Type)](https://msdn.microsoft.com/en-us/library/ms130869(v=vs.110).aspx) | Retrieves an array of the custom attributes applied to a member of a type. Parameters specify the member, and the type of the custom attribute to search for. | 
| [GetCustomAttributes(MemberInfo, Type, Boolean)](https://msdn.microsoft.com/en-us/library/ms130871(v=vs.110).aspx) | Retrieves an array of the custom attributes applied to a member of a type. Parameters specify the member, the type of the custom attribute to search for, and whether to search ancestors of the member. | 
| [GetCustomAttributes(ParameterInfo)](https://msdn.microsoft.com/en-us/library/cs58sb90(v=vs.110).aspx) | Retrieves an array of the custom attributes applied to a method parameter. A parameter specifies the method parameter. | 
| [GetCustomAttributes(ParameterInfo, Boolean)](https://msdn.microsoft.com/en-us/library/2fw1se54(v=vs.110).aspx) | Retrieves an array of the custom attributes applied to a method parameter. Parameters specify the method parameter, and whether to search ancestors of the method parameter. | 
| [GetCustomAttributes(ParameterInfo, Type)](https://msdn.microsoft.com/en-us/library/f0kasshf(v=vs.110).aspx) | Retrieves an array of the custom attributes applied to a method parameter. Parameters specify the method parameter, and the type of the custom attribute to search for. | 
| [GetCustomAttributes(ParameterInfo, Type, Boolean)](https://msdn.microsoft.com/en-us/library/cs2dx40d(v=vs.110).aspx) | Retrieves an array of the custom attributes applied to a method parameter. Parameters specify the method parameter, the type of the custom attribute to search for, and whether to search ancestors of the method parameter.


**Skipped**:

| Name | Description |
| --- | --- |
| [GetCustomAttributes(Module)](https://msdn.microsoft.com/en-us/library/3htbchyy(v=vs.110).aspx) | Retrieves an array of the custom attributes applied to a module. A parameter specifies the module. | 
| [GetCustomAttributes(Module, Boolean)](https://msdn.microsoft.com/en-us/library/b64w44ad(v=vs.110).aspx) | Retrieves an array of the custom attributes applied to a module. Parameters specify the module, and an ignored search option. | 
| [GetCustomAttributes(Module, Type)](https://msdn.microsoft.com/en-us/library/wcw872d3(v=vs.110).aspx) | Retrieves an array of the custom attributes applied to a module. Parameters specify the module, and the type of the custom attribute to search for. | 
| [GetCustomAttributes(Module, Type, Boolean)](https://msdn.microsoft.com/en-us/library/ms130872(v=vs.110).aspx) | Retrieves an array of the custom attributes applied to a module. Parameters specify the module, the type of the custom attribute to search for, and an ignored search option. |
