### ISSUE TITLE
Support non-generic IList and IDictionary

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#2050]
[IList](https://msdn.microsoft.com/en-us/library/system.collections.ilist(v=vs.110).aspx)
```cs
public interface IList : ICollection, IEnumerable
```
[IDictionary](https://msdn.microsoft.com/en-us/library/system.collections.idictionary(v=vs.110).aspx)
```cs
public interface IDictionary : ICollection, IEnumerable
```

**Comment by vladsch** [comment]
Related forum thread
http://forums.bridge.net/forum/community/help/3210-check-if-dictionary-or-list
