### ISSUE TITLE
Support Type.GetElementType()

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#2051]
[Type.GetElementType Method](https://msdn.microsoft.com/en-us/library/system.type.getelementtype(v=vs.110).aspx)
> When overridden in a derived class, returns the Type of the object encompassed or referred to by the current array, pointer or reference type.
```cs
public abstract Type GetElementType()
```

### Sample
[Deck](http://deck.net/2c4970fad0524c51be724d9d52ee931d)
```cs
public class Program
{
    public static void Main()
    {
        int[] array = { 1, 2, 3 };
        
        Type t = array.GetType();
        // typeof(int[])
        Console.WriteLine(t);
        
        Type t2 = t.GetElementType();
        // typeof(int)
        Console.WriteLine(t2);

        var newMe = new Program();
        t = newMe.GetType();
        t2 = t.GetElementType();
        
	// null
        Console.WriteLine(t2);
    }
}
```

**Comment by geoffreymcgill** [comment]
This feature has been implemented and a pull request has been submitted. The feature is expected to be included in the Bridge 15.7 release.

**Comment by vladsch** [comment]
HasElementType
https://msdn.microsoft.com/en-us/library/system.type.haselementtype(v=vs.110).aspx

MakeArrayType
https://msdn.microsoft.com/en-us/library/system.type.makearraytype(v=vs.110).aspx

are supported also

**Comment by LeonidVeriga** [comment]
A decsription on what's changes https://github.com/bridgedotnet/Bridge/pull/2201#issue-196869414
