### ISSUE TITLE
Bridge 15.4 Throw Exception in IE9: 'Uint8Array' is undefined

### ISSUE THREAD

**Issue by codeMonkeyAndy** [bridgedotnet/Bridge#2054]
### Steps To Reproduce
 - Build Code with Bridge.net 15.4
 - Open in IE11 running in IE9 mode (using document mode emulated)
 - Encounter Error in Javascript Console, through Developer Tools
     - SCRIPT5009: 'Uint8Array' is undefined

Error Occurs in isArray Method: may be similar to issue #1889, which was closed in 15.2

**Comment by TriEdgeAI** [comment]
IE9 does not have typed arrays at all. Maybe this can be solved using:
https://github.com/substack/typedarray

**Comment by codeMonkeyAndy** [comment]
Hi TriEdgeAI, thanks for your comment.

 I understand that IE9 doesn't contain typed arrays, thats why I'm surprised that Bridge has tried to reference it! I believe that the bug is a result of javascript attempting to reference them in the isArray method without first checking if they exist or not.

Maybe I'm off the mark here but this seems like I'm dealing with a Bridge.isArray method that is broken in IE9 and can be fixed with a simple logic change on the bridge end?

**Comment by codeMonkeyAndy** [comment]
Thanks guys, appreciate it :)
