### ISSUE TITLE
typeof(string) is transpiled as String, instead of System.String

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#2066]
http://deck.net/72e3c5bb086a15969beb44058224ea89
```cs
public class Program
{
    public static void Main()
    {
        Console.WriteLine(typeof(object).FullName);
        Console.WriteLine("abc".GetType().FullName);
    }
}
```

**Comment by michaelcheers** [comment]
Duplicate of #1293.

**Comment by Porl91** [comment]
This is also the case when looking at the 'FullName' property of the Type for String, as shown below:

Actual:
http://deck.net/256af329a7db6d04783a20bf101279fe

Expected:
https://dotnetfiddle.net/qB32TO
