### ISSUE TITLE
Support boxing/unboxing operations

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#2077]
https://msdn.microsoft.com/en-us/library/yz2be5wk.aspx
https://msdn.microsoft.com/en-us/library/ms228597.aspx
https://msdn.microsoft.com/en-us/library/aa691158(v=vs.71).aspx

### [Unbox(bool)] attribute
If class/method is marked as [External] then Bridge will unbox an argument automatically (if parameter type is object) because Bridge assumes that external libraries cannot work with boxed arguments. If such behaviour must be changed for some external classes/methods (if your external method can handle boxed arguments correctly) then apply attribute `Unbox(false)`

### Format of boxed value
```
{
   $boxed: true,
   v: value,
   type: T,
   constructor: T,
   getHashCode: function(),
   equals: function (o),
   valueOf: function(),
   toString: function ()
}
```

Related issues:
- #2077 Support boxing/unboxing operations
- #2065 Boxed enum types are treated as regular numbers
- #2055 GetType() returns wrong type due to lack of proper boxing
- #1514 referenceEquals is used when comparing strings
- #1357 Boxed value types and String(s) should not be equal (numbers only)
- #1347 All base types give incorrect type names
- #1317 String (+) operator doesn't work on Enums
- #1312 string.Format gives enum number(s) not names
- #1309 Booleans stored as objects give incorrect values
- #1301 Ushort (s), short (s), uint (s), byte (s) give incorrect types
- #1292 Char (s) give incorrect types when stored as objects.
- #1290 Chars don't give correct ToString when stored as object
- #1248 Doubles marked as objects don't give good types

**Comment by TriEdgeAI** [comment]
Awesome!
