### ISSUE TITLE
OR assignment operator causes compilation failure when used with class properties

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#2080]
Reported on the [forum](http://forums.bridge.net/forum/bridge-net-pro/bugs/3082-or-assignment-operator-causes-compilation-failure-when-used-with-class-properties).

### Expected
Valid js code

### Actual
Invalid js code
```
SyntaxError: missing ) after argument list
```

### Steps To Reproduce

[Deck](http://deck.net/0e53c9af4bcbe6b5b032ded876047c70)

```cs
public class Program
{
    public static void Main()
    {
        // First check oprator with a simple variable
        bool testVariable = true;
        bool newValue1 = false;
        testVariable |= newValue1;
        Console.WriteLine("Result 1: {0}", testVariable);
        
        // Now check operator with a property on a class
        TestClass myTestClass = new TestClass();
        myTestClass.TestProperty = true;
        bool newValue2 = false;
        myTestClass.TestProperty |= newValue2;
        Console.WriteLine("Result 2: {0}", myTestClass.TestProperty);
    }
    
    class TestClass
    {
        public bool TestProperty { get; set; }
    }
}
```

**Comment by kcudnik** [comment]
Just noticed that this property OR gets property twice:
`myTestClass.setTestProperty(myTestClass.getTestProperty()!!(myTestClass.getTestProperty() | newValue2));`
if get property is doing some more "extra" work inside like increasing get counter etc, this may be impacted

here is example: [netfiddle](https://dotnetfiddle.net/qcOF3E)

**Comment by LeonidVeriga** [comment]
Hi @kcudnik,

Your test case has been added as well - https://github.com/bridgedotnet/Bridge/pull/2090/commits/7d204fd56da76ed3e7dab96f19235e3c0051ddf9
