### ISSUE TITLE
Reflection: Properties of classes marked [ObjectLiteral] exposed in all other reflected class properties

### ISSUE THREAD

**Issue by Porl91** [bridgedotnet/Bridge#2088]
### Expected
The sample output should be `ShouldSeeThis`

### Actual
When using Reflection to get the properties of a class, I've noticed that if there are any other classes in the solution that are marked with the [ObjectLiteral] attribute, the properties of this class will be included in the reflected properties.
It appears that if you have more than one class within the solution with this attribute it will pull in the properties of a single class seemingly arbitrarily.

The sample output is `ShouldNotSeeThis,ShouldSeeThis`

### Steps to reproduce
Here's a sample demonstrating the problem, where the properties of class `T` include `ShouldNotSeeThis`:
[Deck](http://deck.net/9bbf14bcdbff6edff4c05cffd978b91c)
```cs
using System;
using System.Reflection;
using Bridge;
using System.Linq;

[assembly:Reflectable]
namespace ClassLibrary1
{
    public class Class1
    {
        public static void Main()
        {
            var obj = new T();
            var props = obj.GetType().GetProperties();

            Console.WriteLine(props.Select(x => x.Name).ToArray());
        }
    }

    class T
    {
        public int ShouldSeeThis { get; set; }
    }

    [ObjectLiteral]
    class CompletelyUnrelatedClass
    {
        public int ShouldNotSeeThis { get; set; }
    }
}
```

It seems that this is the case because every type derives from Object, which makes sense, although I don't think these properties should be exposed. At the risk of creating a load of noise, here's the javascript that's generated containing the metadata for each class:

```js
var $m = Bridge.setMetadata,
        $n = [System,ClassLibrary4];
    $m($n[1].Class1, function () { return {"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Main","is":true,"t":8,"sn":"main","rt":Object}]}; });
    $m($n[1].T, function () { return {"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"ShouldSeeThis","t":16,"rt":$n[0].Int32,"g":{"a":2,"n":"get_ShouldSeeThis","t":8,"sn":"getShouldSeeThis","rt":$n[0].Int32},"s":{"a":2,"n":"set_ShouldSeeThis","t":8,"pi":[{"n":"value","pt":$n[0].Int32,"ps":0}],"sn":"setShouldSeeThis","rt":Object,"p":[$n[0].Int32]}}]}; });
    $m(Object, function () { return {"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"ShouldNotSeeThis","t":16,"rt":$n[0].Int32,"g":{"a":2,"n":"get_ShouldNotSeeThis","t":8,"rt":$n[0].Int32,"fg":"shouldNotSeeThis"},"s":{"a":2,"n":"set_ShouldNotSeeThis","t":8,"p":[$n[0].Int32],"rt":Object,"fs":"shouldNotSeeThis"},"fn":"shouldNotSeeThis"}]}; });
```

The line starting with `$m(Object, ` has a reference to `ShouldNotSeeThis` , which is only defined on `CompletelyUnrelatedClass` so I suspect this is why all my classes have these properties.

**Comment by LeonidVeriga** [comment]
Hi @Porl91, thanks for informing us of this defect. We have verified that there is a problem.
We will investigate and fix this defect.

**Comment by vladsch** [comment]
At this moment, you can use ObjectLiteral with Constructor create mode
`[ObjectLiteral(ObjectCreateMode.Constructor)]`

I guess we have to skip metadata generation for ObjectLiteral with Plain mode (it is default mode)
