### ISSUE TITLE
VSIX installer for VS2017

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#2095]
Reported on the [forum](http://forums.bridge.net/forum/community/help/3098-bridge-net-and-visual-studio-2017).

> Well the new visual studio 2017 has been released, but unfortunately the .vsix installer for Bridge.NET does not work with Visual Studio 2017 RC. Is there a way to get by this? And will the next version for Bridge.NET be compatible with Visual Studio 2017?

**Comment by michaelcheers** [comment]
Temporary workound

1. Download as vsix
2. Extract as zip
3. Goto extension.vsixmanifest.
4. Change 
```xml
<InstallationTarget Version="[11.0,15.0)" Id="Microsoft.VisualStudio.Pro" />
``` 
to
```xml
<InstallationTarget Version="[11.0,15.0,17.0)" Id="Microsoft.VisualStudio.Pro" />
```

**Comment by geoffreymcgill** [comment]
I've updated the upcoming Bridge 15.5.0 .vsix to support installation into Visual Studio 2017.

Here's an updated .vsix version of the Bridge 15.4.0 release if you want to test installation into Visual Studio 2017. I would recommend uninstalling Bridge from all versions of Visual Studio before testing the .vsix (inside the following .zip file):

[Bridge.NET.15.4.0.vsix.zip](https://github.com/bridgedotnet/Bridge/files/614561/Bridge.NET.15.4.0.vsix.zip)

The installation process is smooth and will prompt to install Bridge into any Visual Studio versions (minimum Visual Studio 2012) you have on your machine.

Installation runs fine, but there is an annoying issue with uninstallation. 

In previous Visual Studio releases, the Extension uninstallation happens immediately. With Visual Studio 2017, the uninstallation does not occur until all instances Visual Studio 2017 are closed and **all related processes** (eg. in the Task Manager) have been terminated (either automatically or manually).

After you close all instances of Visual Studio 2017, the following **VSIX Installer** dialog box might open.

<img width="469" alt="screenshot 2016-11-26 21 28 51" src="https://cloud.githubusercontent.com/assets/62210/20645577/7362c472-b41f-11e6-9fa9-c353099046ba.png">

The dialog lists processes that must be shut down before the vsix will fully uninstall. A note regarding this dialog is also provided in the Visual Studio 2017 Extensibility [documentation](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-migrate-extensibility-projects-to-visual-studio-2017#check-when-all-required-prerequisites-are-installed).

If you click **Cancel** the extension will not be uninstalled. 

On my machine the processes eventually terminated on their own, but it took a while. After one minute, I clicked **Retry**.

<img width="469" alt="screenshot 2016-11-26 21 33 27" src="https://cloud.githubusercontent.com/assets/62210/20645599/4af4d9d4-b420-11e6-8f39-64f0cc1cd65f.png">

I let it sit for about another minute, and clicked **Retry** again. Fewer options, but still waiting... 

<img width="464" alt="screenshot 2016-11-26 21 36 39" src="https://cloud.githubusercontent.com/assets/62210/20645603/7219b2be-b420-11e6-9c09-4fe0b1181a32.png">

I let it sit for another minute, and clicked **Retry**. This time only the **VBCSCompiler.exe (ID 8232)** process remained. This one stuck around for a while. I clicked **Retry** again about every minute.

<img width="472" alt="screenshot 2016-11-26 21 37 53" src="https://cloud.githubusercontent.com/assets/62210/20645609/9f165092-b420-11e6-98dd-91979e76a603.png">

On my machine, after about five minutes, the **VBCSCompiler.exe (ID 8232)** process finally terminated on its own and the uninstallation of the extension was successful. 

<img width="461" alt="screenshot 2016-11-26 22 24 18" src="https://cloud.githubusercontent.com/assets/62210/20645818/1e5cd578-b427-11e6-9a39-56ae902d64da.png">

I'm not sure there's anything we can do to improve the installation experience. Microsoft has changed the vsix uninstallation process and in my opinion the uninstallation process should be improved.

If you're dead set on removing the Bridge vsix extension from Visual Studio 2017 (RC), use the following steps:

1. From within Visual Studio 2017, select **Tools** > **Extensions and Updates...** > **Installed** > Find **Bridge.NET** > click **Uninstall**
2. Close the **Extensions and Updates...** window
3. Close **all** instances of Visual Studio 2017
4. The **VSIX Installer** dialog should automatically open
5. If the uninstaller doesn't uninstall the extension immediately, wait a few moments, then click **Retry**
6. Keep repeating Step 5 until something happens
7. Eventually the processes should terminate and uninstallation of the extension will run

**NOTE:** You can manually terminate the process by jumping into the **Task Manager** by right-clicking on Taskbar, then select **Task Manager**. Find each process in the list and **End task**.

I'll see if we can get the attention of someone from the Visual Studio team to provide feedback on this issue. Starting with the documentation authors: @gregvanl @ghogen. I'll dig around and try to find who has ownership of this functionality.

**Comment by geoffreymcgill** [comment]
Closing this issue and will deal with the uninstallation process in a separate issue.
