### ISSUE TITLE
Improper reuse of generated anonymous type from other namespace

### ISSUE THREAD

**Issue by kosmab** [bridgedotnet/Bridge#2099]
### Expected

displayed "OK"

### Actual

JavaScript runtime error: Object doesn't support this action

### Steps To Reproduce

not possible to reproduce in Deck, since it generates single .js file, and in actual project are 2 files (n1.js, n2.js)

```cs
namespace n1
{
    public class class1
    {
        public class1()
        {
            prop1_in_1 = new
            {
                prop2 = new
                {
                    prop3 = "x"
                },
            };
        }
        public object prop1_in_1 { get; set; }
    }

}
namespace n2
{

    public class class2
    {
        public class2()
        {
            prop1_in_2 = new
            {
                prop2 = new
                {
                    prop3 = "y"
                },
            };
        }
        public object prop1_in_2 { get; set; }
    }
    public class Program
    {
        public static void Main()
        {
            n1.class1 o1 = new n1.class1();
            n2.class2 o2 = new n2.class2();
            System.Console.WriteLine("OK");
        }
    }
}
```

**Comment by geoffreymcgill** [comment]
Thanks for submitting this issue. We are investigating.

**Comment by vladsch** [comment]
Thanks for the report, we are going to fix it. By the way, default output mode is "by namespace" (classes from different namesapces are rendered to different js files). But preferable output mode is "by project" (all classes are rendered to one file). In this case, Bridge can guarantee correct sequence of classes

To change output mode, just use bridge.json
`outputBy: "Project"`

**Comment by kosmab** [comment]
Thanks for info.

We use „by namespace” mode, since it simplifies code sharing among projects.
