### ISSUE TITLE
Firebug Console API support

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#21]
Implement full Firebug Console API support

https://getfirebug.com/wiki/index.php/Console_API

Should this be a separate Bridge.NET package?

    Install-Package Bridge.Console

Maybe only the basic `Console` support should be added to Bridge.NET Foundation, with full `Console` support added to `Bridge.Console` package.

**Comment by DaniilVeriga** [comment]
Just reviewed Console API and decided to add [.DirXml()](https://getfirebug.com/wiki/index.php/Console.dirxml) and [.Table()](https://getfirebug.com/wiki/index.php/Console.table). Although, I think Console API might be considered as of Bridge version 1.0.

**Comment by Mimisss** [comment]
> I guess that almost all Firebug Console methods are presented in HTML5 Console API which is fully implemented already in Bridge (except some none cross browser functions).

I also believe that only cross browser functions should be available. `dirXml` works but `table` does not work in IE.

What's your opinion?

**Comment by DaniilVeriga** [comment]
Well, Console API is not standardized at all. Please read this comment in [Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/API/Console/log) for any Console's method.

>  Non-standard
> This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

So, I would consider it not cross-browser in its origin. If follow the cross-browser policy, should we remove all the Console API? I think we should not. 

As for `.dirxml()` it doesn't work in IE10, for example. It is started supported in IE11. Should we remove it? 

As for `.table()`. Yes, it appears to be not supported even in IE11, but I found this method very cool and it works in Chrome and Firefox, at least. Should we deprive such a possibility from our Chrome and Firefox users? IMO, we should not. I think it is rather a problem in IE.

Moreover, we support IE8+, Safari, Opera. I believe you can find a lot more non cross-browser things if compare all the browsers. Yes, cross-browser is definitely our very high priority, but in my opinion Console API is quite a specific case.

**Comment by geoffreymcgill** [comment]
I've never used `.table()` previously, but that certainly looks like interesting functionality. We should certainly implement if not already available in Bridge.NET.

**Comment by DaniilVeriga** [comment]
`.table()` is in Bridge.NET already.
