### ISSUE TITLE
double.Parse issues

### ISSUE THREAD

**Issue by Zaid-Ajaj** [bridgedotnet/Bridge#2112]
### Expected
```
FormatException: Input string was not in a correct format.
```

### Actual
No run-time error
```
double.Parse("9anything") // evaluates to 9
```

### Steps To Reproduce

[dotnetfiddle](https://dotnetfiddle.net/BOKUyi)
[Deck](http://deck.net/09c281bc981ac8d070151a8d04d92fcf)

**UPD** More cases [added](https://github.com/bridgedotnet/Bridge/issues/2112#issuecomment-264672626)

**Comment by geoffreymcgill** [comment]
For some explanation, behind the scenes, this function is using the native JavaScript **parseFloat** function.

http://www.w3schools.com/jsref/jsref_parsefloat.asp

> This function determines if the first character in the specified string is a number. If it is, it parses the string until it reaches the end of the number, and returns the number as a number, not as a string.

Passing `"9anything"` will return `9`. Passing `"anything9"` will throw an exception.

We need to reproduce the behaviour of the .NET framework, so as you noted, an Exception should be thrown. 

Thanks for reporting, and we'll try our best to include this fix in the upcoming 15.5 release.

**Comment by Zaid-Ajaj** [comment]
From the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat), there seem to be a regex solution, could be helpful

```js
var filterFloat = function (value) {
    if(/^(\-|\+)?([0-9]+(\.[0-9]+)?|Infinity)$/
      .test(value))
      return Number(value);
  return NaN;
}

console.log(filterFloat('421'));               // 421
console.log(filterFloat('-421'));              // -421
console.log(filterFloat('+421'));              // 421
console.log(filterFloat('Infinity'));          // Infinity
console.log(filterFloat('1.61803398875'));     // 1.61803398875
console.log(filterFloat('421e+0'));            // NaN
console.log(filterFloat('421hop'));            // NaN
console.log(filterFloat('hop1.61803398875'));  // NaN
```

**Comment by LeonidVeriga** [comment]
[MSDN](https://msdn.microsoft.com/en-us/library/fd84bdyt(v=vs.110).aspx)  `Double.Parse Method (String)`

### Actual/Expected

`double.Parse()` tests:

```
Test ParseCurrentCultureWorks:

Passed 1. Parsing:"10.0" Result:10
Failed 2. Parsing:" 10,10 " Expected:1010 Actual:10
Failed 3. Parsing:"10,2,10" Expected:10210 Actual:10
Failed 4. Parsing:"10,1,1,1,1,1" Expected:1011111 Actual:10
Failed 5. Parsing:"10,00" Expected:1000 Actual:10
Failed 6. Parsing:"10,10,2.5" Expected:10102.5 Actual:10
Passed 7. Parsing:"NaN" Result:NaN
Passed 8. Parsing:"-Infinity" Result:-Infinity
Passed 9. Parsing:"Infinity" Result:Infinity
Passed 10. Parsing:"-123" Result:-123
Passed 11. Parsing:"123" Result:123
Passed 12. Parsing:" 123 " Result:123
Passed 13. Parsing:"0" Result:0
Passed 14. Parsing:"567.89" Result:567.89
Passed 15. Parsing:"-567.89" Result:-567.89
Passed 16. Parsing:"1E23" Result:1e+23

Test ParseCurrentCultureThrows:

Passed 1. Parsing:"" Result:FormatException
Passed 2. Parsing:"b" Result:FormatException
Failed 3. Parsing:"10a" Expected:FormatException Actual:10
Passed 4. Parsing:"a10" Result:FormatException
Failed 5. Parsing:"10.2.10" Expected:FormatException Actual:10.2
Failed 6. Parsing:"10,2.5,0" Expected:FormatException Actual:10
Failed 7. Parsing:"10,2.5,0.0" Expected:FormatException Actual:10
Failed 8. Parsing:"1e10e" Expected:FormatException Actual:10000000000
Passed 9. Parsing:"null" Result:ArgumentNullException
Passed 10. Parsing:" " Result:FormatException
Passed 11. Parsing:"Garbage" Result:FormatException
Passed 12. Parsing:"(123)" Result:FormatException
Passed 13. Parsing:"$1000" Result:FormatException
```
### Steps To Reproduce

[.Net Fiddle](https://dotnetfiddle.net/kIU7Mn)

[Deck](http://deck.net/b7a3e335ddec6fb754b84421659ab36a)
