### ISSUE TITLE
Class fields with names starting from digits

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#2114]
I was looking a way of naming class fields with names starting from a digit. The following scenarios have been checked:

- Using **Name** attribute
- Using **Template** attribute

The first scenario leads to incorrect JavaScript. The second one creates working JavaScript, however, field initialization is still incorrect.

## 1. Using **[Name]** attribute

**Name** attribute doesn't identify incorrect names and simply pass a provided name into JavaScript.

### Expected

```js
Bridge.define("Demo.TestClass", {
    "0a": 0,
    ctor: function (value) {
        this.$initialize();
        this["0a"] = value;
    }
});
```

### Actual

```js
Bridge.define("Demo.TestClass", {
    0a: 0,
    ctor: function (value) {
        this.$initialize();
        this.0a = value;
    }
});
```

### Steps To Reproduce

[Deck](http://deck.net/128a92971dd0bcdbf3360e9ea1b55d12)

```cs
class TestClass
{
    [Name("0a")]
    public int TestField;
    
    public TestClass(int value)
    {
        TestField = value;
    }
}
```

## 2. Using **[Template]** attribute

**Template** attribute works just fine. However, the class still contains initialization of a field with the original (C#) name.

### Expected

```js
Bridge.define("Demo.TestClass", {
    "0a": 0,
    ctor: function (value) {
        this.$initialize();
        this["0a"] = value;
    }
});
```

### Actual

```js
Bridge.define("Demo.TestClass", {
    testField: 0,
    ctor: function (value) {
        this.$initialize();
        this["0a"] = value;
    }
});
```

### Steps To Reproduce

[Deck](http://deck.net/e6065657e368b3cb5c7cb875ccd847c6)

```cs
class TestClass
{
    [Template("{this}[\"0a\"]")]
    public int TestField;
    
    public TestClass(int value)
    {
        TestField = value;
    }
}
```

**Comment by AndreyChechel** [comment]
The requested feature will be helpful for integration with existing JavaScript libriaries and APIs that use unusial (for C# world) naming of object properties.

**Comment by vladsch** [comment]
Why square brackets is required in expected code (`["0a"]`)?
