### ISSUE TITLE
[15.5] CSharp6 Getter-only auto-properties cause too many closing braces emitted (not const in right-hand)

### ISSUE THREAD

**Issue by patryk9200** [bridgedotnet/Bridge#2137]
**UPD**: Reported on the [forum](http://forums.bridge.net/forum/bridge-net-pro/bugs/3160-c-6-instance-property-initialization-results-in-invalid-js-worked-in-15-4) as well.

After updating bridge nuget package to 15.5 errors appeared in the compiled JS code.

### Expected
```js
No error
```

### Actual
```js
Uncaught SyntaxError: missing ) after argument list
```

Only downgrade to 15.4 fixes errors.

edit:
Just try compile & run this on bridge v15.5.
```cs
using Bridge.Html5;

namespace Test
{
    class Control
    {
        public HTMLElement Element { get; } = new HTMLElement();
    }
}
````
Emited JS have too many closing braces:
```js
/**
 * @version 1.0.0.0
 * @copyright Copyright ©  2016
 * @compiler Bridge.NET 15.5.0
 */
Bridge.assembly("Test", function ($asm, globals) {
    "use strict";

    Bridge.define("Test.Control", {
        config: {
            Element: null
        },
        init: function () {
            Bridge.property(this, "Element", document.createElement('div'));
        }
    } // <= issue- too many closing braces
    });
});

**Comment by vladsch** [comment]
Can you provide test sample which reproduces the issue? Thank you

**Comment by patryk9200** [comment]
I have problem to find te source of the errors.
I could give you access to my source code, but I can't post it here.
Can I send  to you private email with the source code?

**Comment by LeonidVeriga** [comment]
Thanks for submitting this report and for providing the simplified sample demonstrating how to reproduce. We will investigate and fix this defect.

We created a [Deck](http://deck.net/5b0de1c5b02f60c65a30b14ec4241e67) sample to reproduce the issue online.

A workaround is to move element initialization into constructor:
[Deck](http://deck.net/daf87ee89ce3ef05a8184a9b5e03bca6)
```cs
class Control
{
    // public HTMLElement Element { get; } = new HTMLElement();
    public HTMLElement Element { get; private set; }
    
    public Control()
    {
        Element = new HTMLElement();
    }
    
    public static void Main()
    {
        Console.WriteLine(new Control().Element);
    }
}
```

**Comment by LeonidVeriga** [comment]
Reported on the [forum](http://forums.bridge.net/forum/bridge-net-pro/bugs/3160-c-6-instance-property-initialization-results-in-invalid-js-worked-in-15-4).

**Comment by LeonidVeriga** [comment]
Hi @patryk9200,

Fix for the issue merged into **master** branch and will be included into Bridge **15.6.0** release scheduled for the beginning of the next week.

**Comment by patryk9200** [comment]
@LeonidVeriga Thank You!

**Comment by geoffreymcgill** [comment]
Bridge 15.6.0 has been [released](http://bridge.net/download/).
