### ISSUE TITLE
Missing Type.IsAbstract

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#2144]
[Type.IsAbstract Property](https://msdn.microsoft.com/en-us/library/system.type.isabstract(v=vs.110).aspx)
> Gets a value indicating whether the Type is abstract and must be overridden.
```cs
public bool IsAbstract { get; }
```

**Comment by TriEdgeAI** [comment]
Any workaround for this right now?

**Comment by vladsch** [comment]
Unfortunatelly, no
Bridge doesn;t render such information in metadata for a class, We will try to implement it for 15.7 release

**Comment by TriEdgeAI** [comment]
Cool! Looking forward to it :) Worked it around by hard coding a small list of classes for now.
