### ISSUE TITLE
Object initializer code ignored in generic method

### ISSUE THREAD

**Issue by kosmab** [bridgedotnet/Bridge#2157]
### Expected

```js
"2"
```

### Actual

```js
"1"
```

### Steps To Reproduce

[Deck](http://deck.net/895f32d1a9f211dfe19118ad2c4216a4)

```cs
public class Program
{
    public static void Main()
    {
        Console.WriteLine(TestMethod<TestClass>().TestProperty);
    }

    public static TType TestMethod<TType>()
        where TType : TestClass, new()
    {
        return new TType
        {
            TestProperty = 2
        };
    }
}

public class TestClass
{
    public TestClass()
    {
        this.TestProperty = 1;
    }

    public int TestProperty { get; set; }
}
```

**Comment by LeonidVeriga** [comment]
Hi @kosmab,

Thank you for reporting this defect and a sample code demonstrating the issue.
The sample did help to verify and debug a lot; we just changed class and prop names a bit to make it more readable.

It has been fixed in will be included in **15.6** release. Thanks again for reporting.
