### ISSUE TITLE
Bridge.merge wrong behaviour for primitive class members

### ISSUE THREAD

**Issue by kosmab** [bridgedotnet/Bridge#2167]
### Expected

```js
true
true
true
```

### Actual

```js
false
true
true
```

### Steps To Reproduce

[Deck](http://deck.net/0c6c8d4bab5763c4c01007757e993b5b)

```cs
public class Program
{
    public static void Main()
    {
        object o1 = new 
        { 
            p1 = 1
        };

        Data o2 = new Data()
        {
            p1 = 2.0m,
            p2 = 2.0m
        };        
        o2 = Script.Write<Data>("Bridge.merge(o2, o1);");

        decimal o3 = 3.0m;
        object o4 = 1;
        o3 = Script.Write<decimal>("Bridge.merge(o3, o4);");       

        Console.WriteLine(o2.p1.Is<decimal>());
        Console.WriteLine(o2.p2.Is<decimal>());
        Console.WriteLine(o3.Is<decimal>());
      }
}

public class Data
{
    public decimal p1 { get;set; }
    public decimal p2 { get;set; }
}
```
//merging System.Decimal object with plain number behaves differently than merging objects with same property types

**Comment by vladsch** [comment]
Bridge.merge is designed to merge properties of object. It doesn't analyze values of the properties. So, it is responsibility of developer to have correct values inside object

**Comment by kosmab** [comment]
It seems to be inconsistent behaviour.

Condider following (line 680-685 of bridge.js of 15.6.0 release)

 

if (value && value.constructor === Object && to[key]) 

{

toValue = to[key];

       Bridge.merge(toValue, value);

} 

else 
{

to[key] = value;

}


if „to” property is already Bridge class, then merge is called and final „to” property is also Bridge class.

IMHO it would be expected, that for other ‘semi-Bridge’ objects as System.Decimal same action is performed, and plain assignment is executed as last resort.

**Comment by vladsch** [comment]
I am not sure that correctly understood your last post and how it can resolve your original test case
You tried to merge different values (set int to decimal) therefore your test case is failed

Orifinally, Bridge.merge was designed to apply initializers to instance (like you  create c1 instance in test sample) therefore merged properties values of merged objects must be the same

**Comment by kosmab** [comment]
I don't know original design goal, but for me "inconsistency" exists.
Brige.merge "correctly" handles plain decimal with int (variables o3 and o4 in my example, lines 616-618 in source) , but when these values are properties of other objects - it doesnt'. I would expect, that instead of assingment 
l.684
[
to[key] = value;
] 
it would be recursive call, something like this:
[
to[key] =  Bridge.merge(to[key], value);
]

l. 616-618 - merge plain values:
[
 if (to instanceof System.Decimal && Bridge.isNumber(from)) {
return new System.Decimal(from);
 }
]
OR the second - opposite - solution - plain int "merged" into decimal would result in int value, not decimal one (as it happens now).
