### ISSUE TITLE
Move the class representing RegExp into Bridge.Html5

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#2170]
Bridge project currently contains two Regex classes:

- [System.Text.RegularExpressions.Regex](
https://github.com/bridgedotnet/Bridge/blob/master/Bridge/System/Text/RegularExpressions/Regex.cs)
The 1st one (`System.Text.RegularExpressions.Regex`) covers .NET Regex class functionality, so it should be kept as is. 
- [Bridge.Text.RegularExpressions.Regex](https://github.com/bridgedotnet/Bridge/blob/master/Bridge/Bridge/Text/RegularExpressions/Regex.cs)
The 2nd class (`Bridge.Text.RegularExpressions.Regex`) represents JavaScript RegExp API and it'd better to rename it and move into **Bridge.Html5** to avoid confusion between these two classes. Probably the location of `Bridge.Text.RegularExpressions.Regex` should be changed as well.
- Bridge.Text.RegularExpressions.RegexMatch class should be removed at all as there is no matching JS class (`regexp.exec()` returns array of strings in JS not `RegexMatch`)

### Expected

JavaScript `RegExp` is represented by the class named `RegExp`

### Actual

JavaScript `RegExp` is represented by `Regex` class

**Comment by geoffreymcgill** [comment]
The file **Bridge.Text.RegularExpressions.Regex.cs** should be moved to **Bridge.Html5.RegExp.cs** and that would also include moving into the **Bridge.Html5** namespace.

**Comment by Zaid-Ajaj** [comment]
@geoffreymcgill This means that users using Regex inside a Node application, would have to import (`using`) **Bridge.Html5** which does not seem logical. I would suggest to add it to **Bridge** namespace since Regex is used both with browser and node

**Comment by geoffreymcgill** [comment]
We have a **Node** specific package that will be available in conjunction with this **Bridge 16.0** change, and the new package will not require **Bridge.Html5**.

**Comment by Zaid-Ajaj** [comment]
@geoffreymcgill There is a **Node** package coming?! Thats awesome :)
