### ISSUE TITLE
PadLeft is broken for empty string

### ISSUE THREAD

**Issue by yuvaltz** [bridgedotnet/Bridge#2181]
### Expected
**String.PadLeft** (and **String.PadRight**) of an empty string should return a string with the requested character in the requested length.

### Actual
**String.PadLeft** and **String.PadRight** of an empty string returns an empty string.

### Steps To Reproduce
```csharp
public class Program
{
    public static void Main()
    {
        Console.WriteLine("".PadLeft(3,'L')); // Should be LLL
        Console.WriteLine("".PadRight(3,'R')); // Should be RRR
    }
}
```
[Deck](http://deck.net/f9e2a7c9f496bafe99694733129cd325)

**Comment by geoffreymcgill** [comment]
A pull request has been submitted with a fix for this issue. We expect to include the fix in the Bridge 15.7.0 release.
