### ISSUE TITLE
Unused referenced assembly script doesn't get copied to the output directory

### ISSUE THREAD

**Issue by yuvaltz** [bridgedotnet/Bridge#2182]
### Actual
When a referenced assmebly is not used, its generated script doesn't get copied to the output directory (bin\Debug), while its dll and pdb are getting copied.

### Expected
As with dlls and pdbs, referenced assemblies script should always be copied to the output folder regardless of their usage.

### Steps To Reproduce
* **ClassLibrary1**, **ClassLibrary2** are separate assemblies
* **ClassLibrary2** references **ClassLibrary1**, but doesn't use it.

```csharp
namespace ClassLibrary1
{
    public class Class1
    {
    }
}
```

```csharp
namespace ClassLibrary2
{
    public class Class2
    {
    }
}
```

Build of **ClassLibrary2** will result in these files in the `bin\Debug` folder
```
Bridge.dll
bridge.js
bridge.min.js
Bridge.xml
ClassLibrary1.dll
ClassLibrary1.pdb
ClassLibrary2.dll
classLibrary2.js
classLibrary2.min.js
ClassLibrary2.pdb
```
While **ClassLibrary1.dll**, and **ClassLibrary1.pdb** are copied, **ClassLibrary1.js**, **ClassLibrary1.min.js** aren't.

A solution with the above configuration - [BridgeReferenceTest.zip](https://github.com/bridgedotnet/Bridge/files/655767/BridgeReferenceTest.zip)

**Comment by vladsch** [comment]
It is related with .NET compiler
Bridge reads referenced assemblies from main assembly but .NET compiler removes unused references from the assembly therefore Bridge cannot find it
You can repeate such behaviour with standard .NET application

**Comment by vladsch** [comment]
I guess the same problem is discussed in this thread
http://stackoverflow.com/questions/1132243/msbuild-doesnt-copy-references-dlls-if-using-project-dependencies-in-solution

**Comment by yuvaltz** [comment]
I figured that was the reason, I wasn't aware that's a problem in MSBuild too.

Currently it could be worked around by adding an empty attribute that references one of the unused referenced assembly types.

Something like:
```
[assembly: SomeEmptyAttribute(typeof(ClassLibrary1.Class1))]
```
