### ISSUE TITLE
Inheriting from an external class

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#2189]
A class-successor fails to init if its parent class is marked with `[External]` attribute.

### Expected

Bridge Console contains the following output:
> John Doe
   100

### Actual

> null
   100

### Steps To Reproduce

http://deck.net/fa57056dec6fa8c6222b35f9e98b7252

```cs
public class Program
{
    [Init(InitPosition.Top)]
    public static void CreatePersonDefinition()
    {
        /*@
        var Person = (function () {
            function Person(name) {
                this.Name = name;
            }
            return Person;
        }());
        */
    }
    
    public static void Main()
    {
        var employee = new Employee("John Doe", 100);
            
        Console.WriteLine(employee.Name);
        Console.WriteLine(employee.Salary);
    }
    
    public class Employee : Person
    {
        public int Salary;
        
        public Employee(string name, int salary)
            : base(name)
        {
           Salary = salary;        
        }
    }
    
    [External]
    [Name("Person")]
    public class Person
    {
        public string Name;
        public Person(string name)
        {
            Name = name;
        }
    }
}
```

**Comment by vladsch** [comment]
But Person class is not defined anywhere. Type definition must be presented in javascript (even if it is marked as External)

**Comment by vladsch** [comment]
Just see the sample
http://deck.net/eac9bd1b75195f5d88d34495880320f6

I see the problem that base class ctor is ignored but other functionality works fine

**Comment by vladsch** [comment]
Workaraound: to set Template to ctor of External class
http://deck.net/c675fca084c5d4cb968529aac544c32b

**Comment by AndreyChechel** [comment]
> But Person class is not defined anywhere. Type definition must be presented in javascript

Thanks! Indeed, I missed it in my example.

> I see the problem that base class ctor is ignored but other functionality works fine

Yes, this could be an issue when an external entity's ctor has arguments. Is it going to be fixed?

**Comment by vladsch** [comment]
Yes, pull request with a fix is created
