### ISSUE TITLE
Support global:: prefix in attributes

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2191]
### Steps To Reproduce

http://deck.net/76014349ce948dc06695d3b65446e3e2

```cs
[Reflectable(global::Bridge.MemberAccessibility.Instance)]
public class Program
{
    public static void Main()
    {
        Console.WriteLine("Hello World!");
    }
}
```

Originally reported in Saltarelle:
https://github.com/Saltarelle/SaltarelleCompiler/issues/393

**Comment by michaelcheers** [comment]
I don't really think this should be top priority. There is a very easy workaround.

**Comment by michaelcheers** [comment]
@geoffreymcgill, @vladsch, it seems to be fixed now.

**Comment by geoffreymcgill** [comment]
I'm not sure when or how this was fixed, but it is working well now.
