### ISSUE TITLE
Simultaneous use of [Module] and [Init] attributes

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#2198]
When the function marked with `[Init]` attribute is located in a module, it will be called using a wrong reference. It'd be better to call it outside the module initialization function.

There are also connected defects (in the expected code):
- `main` function can't be resolved. However, other name will work fine.
- `Bridge.Console.log` will throw an exception:
>Uncaught TypeError: Cannot read property 'getHashCode2' of undefined
    at ctor.findEntry (bridge.js:10247)
    at ctor.set (bridge.js:10299)
    at ctor.add (bridge.js:10328)
    at ctor.f1 (bridge.js:23682)
    at bridge.js:1201
    at bridge.js:1101
    at ctor.init (bridge.js:23437)
    at new ctor (bridge.js:23431)
    at Function.getInstance (bridge.js:23337)
    at Function.logBase (bridge.js:23344)

### Expected

```js
Bridge.assembly("Demo", function ($asm, globals) {
    "use strict";

    define("Module1", function () {
        var Module1 = { };
        Bridge.define("Demo.Program1", {
            $scope: Module1,
            $main: function () {
                Bridge.Console.log("Hello World!");
            }
        });

        Module1.Demo.Program1.main();
        return Module1;
    });

});
```

### Actual

```js
Bridge.assembly("Demo", function ($asm, globals) {
    "use strict";

define("Module1", function (_) {
    var exports = { };
        Bridge.define("Demo.Program1", {
            $scope: exports,
            $main: function () {
                Bridge.Console.log("Hello World!");
            }
        });

        Demo.Program1.main();
    return exports;
});

});
```

### Steps To Reproduce

http://deck.net/90a630d0f7983f8496c98864afec8903

```cs
[Module("Module1")]
public class Program1
{
    [Init]
    public static void Main()
    {
        Console.WriteLine("Hello World!");
    }
}
```

**Comment by vladsch** [comment]
This issue is fixed in the following commit
https://github.com/bridgedotnet/Bridge/pull/2218/commits/2b8957c9b3435d7701ee10419ab215d87e0de74f
