### ISSUE TITLE
AnEvent<T> do not inherit AnEvent

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#2205]
### Expected

Works

### Actual

Doesn't work

### Steps To Reproduce

http://deck.net/728729214fb5f4b0f944408a9e9216e2

```cs
public class Program
{
    public static void Main()
    {
        new HTMLButtonElement().OnMouseMove = e =>
        {
            Global.Alert("X: " + e.LayerX);
            Global.Alert("Y: " + e.LayerY);
            Global.Alert("X: " + e.As<MouseEvent>().LayerX);
            Global.Alert("Y: " + e.As<MouseEvent>().LayerY);
        };
    }
}
```

**Comment by geoffreymcgill** [comment]
Thanks for reporting and for providing the simplified sample demonstrating how to reproduce. 

We will investigate and fix this defect.

**Comment by LeonidVeriga** [comment]
@geoffreymcgill That is related to https://github.com/bridgedotnet/Bridge/issues/1816#issuecomment-251075624

**Comment by michaelcheers** [comment]
Same with KeyboardEvent.

**Comment by LeonidVeriga** [comment]
List of changed Events according to **Option 1** (but HTMLElement as element type used) https://github.com/bridgedotnet/Bridge/issues/1816#issuecomment-251075624:

- WheelEvent
- TouchEvent
- MouseEvent
- KeyboardEvent
- HashChangeEvent
- FocusEvent
- DragEvent
- CustomEvent
- CompositionEvent
- AnimationEvent
