### ISSUE TITLE
Support inline variable declarations

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#2206]
See [this article](http://odetocode.com/blogs/scott/archive/2014/09/15/c-6-0-features-part-3-declaration-expressions.aspx).

**Comment by geoffreymcgill** [comment]
The article you linked to states:

> **Update**: this feature was dropped from C# 6.0. 

I cannot get a sample using this syntax to compile in native C#.

Best I can tell, this syntax feature is not available (yet) in C#6.

**Comment by michaelcheers** [comment]
it works in Visual Studio 2017

**Comment by geoffreymcgill** [comment]
I can't find documentation on _inline variable declarations_ for C#6. 

@michaelcheers - Could you be using C#7?

**Comment by michaelcheers** [comment]
@geoffreymcgill, You're right, is C# 7.0 supported by Bridge?

**Comment by geoffreymcgill** [comment]
> is C# 7.0 supported by Bridge?

No. When C#7 is finalized, we will support.
