### ISSUE TITLE
Implementing an external interface

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#2216]
Similarly to #2189, a class fails to init if it implements an interface marked with `[External]` attribute. The difference of this case is that the interface implementation may not exist in JavaScript code.

I got it working by applying `[ObjectLiteral]` attribute to the external interface (see C# line 31), but I'm not sure whether it's a correct approach.

### Expected

Output in Bridge Console:

```js
> This is John Smith
> This is John Smith
```

### Actual

```
Uncaught ReferenceError: Demo is not defined
```

### Steps To Reproduce

http://deck.net/11e214476bc001cb5c2cf431d5baaf7b

```cs
public class Program
{
    public static void Main()
    {
        var person = new Person("John Smith");
        person.Introduce();
        
        var iperson = (IPerson)person;
        iperson.Introduce();
    }
}

public class Person : IPerson
{
    [FieldProperty]
    public string Name { get; set; }
    
    public Person(string name)
    {
        Name = name;
    }
    
    public void Introduce()
    {
        var msg = $"This is {Name}";
        Console.WriteLine(msg);
    }
}

[External]
//[ObjectLiteral]    // UNCOMMENT TO GET IT WORKING
public interface IPerson
{
    [FieldProperty]
    string Name { get; set; }
    
    void Introduce();
}
```

**Comment by vladsch** [comment]
Changes to implement this request:
- Add `IsVirtual` bool property to `ExternalInterfaceAttribute`
- Set `[ExternalInterface(IsVirtual = true)]` to `IPerson` interface

Virtual external interface will be accessed in javascript via `Bridge.getInterface` method which will check interface type and create it if is required
`inherits: [Bridge.getInterface("Demo.IPerson")]`

Please note that `ExternalInterfaceAttribute` ctor can accept `nativeImplementation` bool parameter
- if such parameter is absent then Bridge assumes that external interface can be implemented with aliases (native Bridge implementation) or without aliases. In this case, Bridge will check both member names during runtime (`iperson[Bridge.geti(iperson, "Demo$IPerson$introduce", "introduce")]()`)
- if the parameter `true` then it means that implementation of the interface always native and member access will be `iperson.Demo$IPerson$introduce()`
- if the parameter `false` then it means that implementation of the interface always plain (without aliases) and member access will be `iperson.introduce()`

**Comment by geoffreymcgill** [comment]
The `IsVirtual` property on `[ExternalInterface]` is being replaced with a new `[Virtual]` attribute in the final release of Bridge v16. See Issue #2795 for more info.

```csharp
// Old
[ExternalInterface(IsVirtual = true)]

// New
[Virtual]
[ExternalInterface]
```
