### ISSUE TITLE
Module functionality redesign

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#2217]
Redesign module functionality.

Bridge now supports **AMD**, **CommonJS**, **UMD** and **ES6** modules (**AMD** is default).

The `[Module]` attribute can be applied to a class or assembly (in this case all classes belonging to the assembly will be included in the module).

The `[Module]` attribute can accept module type and/or module name. Required module code depends on module type (for example, `define` method is generated for **AMD**).

By default, if application uses a module then Bridge will generate code to load that module (for example, using `require` method). So, all modules will be loaded during application startup.

If you want to load modules manually (for example, bundle it to one file and include it into html) then module loading can be disabled using `loader` object in **bridge.json**.

```js
loader: {
    // loading system, by default AMD
    type: "AMD | CommonJS | ES6"

    // by default, "require"
    loaderFunction : string

    // true to disable automatic modules loading
    manualLoading: bool

    // mask to define which exactly modules should be excluded from auto-loading
    manualLoadingMask: string
    
    // true to disable variables generation if module is disabled then variable is created
    // which will be initialized after loading that module manually if call `Module.Load`
    skipManualVariables: bool
}
```

Module can be loaded manually using `Module.Load`
```js
await Module.Load(typeof (AnotherLibrary.Class1));
AnotherLibrary.Class1.Method();
```

Bridge doesn't include libraries for loading modules, required libraries (like require.js) must be added manually.

### Tasks
 - [ ] Update [Global Configuration](http://bridge.net/docs/global-configuration/) docs
 - [ ] add description `manualLoadingMask` - `[!][regex:][*...][;]`

**Comment by AndreyChechel** [comment]
Please consider also the following case. Since modules are used to isolate their children from global scope, this fact changes the meaning of such attributes as `[Mixin]` and `[GlobalMethods]`. Those attributes should be resolved within the module scope where they are applied.

**Program.cs:**
```cs
namespace Demo
{
    public class App
    {
        [Init]
        public static void Start()
        {
            Module1.GlobalMembers.SayHello("Hello, World!");
            Module1.NS.GlobalMembers.SayHello("Hello, World!");
        }
    }
}
```

**Module1.cs:**
```cs
[assembly: Module(ModuleType.AMD, "Module1")]

namespace Module1
{
    [External]
    [GlobalMethods]
    public static class GlobalMembers
    {
        public static extern void SayHello(string name);
    }

    namespace NS
    {
        [External]
        [Mixin("NS")]
        public static class GlobalMembers
        {
            public static extern void SayHello(string name);
        }
    }
}
```

Currently the **Program** consuming the **Module1** will be converted to:
```javascript
Bridge.assembly("Demo", function ($asm, globals) {
    "use strict";

    require(["Module1"], function (Module1) {
        Bridge.define("Demo.App", {
            statics: {
                start: function () {
                    sayHello("Hello, World!");      // ERROR:  'Module1.sayHello' was expected here.
                    NS.sayHello("Hello, World!");   // ERROR:  'Module1.NS.sayHello' was expected here.
                }
            }
        });
    
        Demo.App.start();
    });
});
```

**Comment by AndreyChechel** [comment]
The suggestion above will make it impossible to emit code accessing entities/objects outside the module. I'll also suggest keeping this ability or at least providing a way to get round this limitation.  

The possible way is to introduce a flag for `[Module]` attribute which can be used to disable automatic module variable name addition when module enities are accessed. If this flas is set, `[Mixin]` and `[GlobalMethods]` will be resolved to global scope as well.

The suggested solution also provides a way to handle JS modules like the one below:
```javascript
define(["require", "exports"], function (require, exports) {
    "use strict";
    return (function () {
        function SomeClass() {
        }
        return SomeClass;
    }());
});
```
