### ISSUE TITLE
A way to convert TypeScript definitions to Bridge definitions

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#2219]
I had an attempt at it [here](https://github.com/michaelcheers/TypescriptToCS) but I was finding it hard so I am hoping members of the communities could do this. I am happy to help but I had a lot of trouble making the parser because I do not have very much experience in that field.

It would help a lot for things like:

- Full dom support
- All typescript library support

You could even integrate into C# projects.
Maybe, if you right click on References.
It has add typescript file reference.
It would be great for bridge.

![smile_80_anim_gif 1](https://cloud.githubusercontent.com/assets/10186738/21754700/3480069a-d5ba-11e6-8c3e-c3eb3f5e3e36.gif)

**Comment by geoffreymcgill** [comment]
Thanks for the suggestion. This feature pops back into our lives a few times a year from the community. Requested in other places as well:

http://forums.bridge.net/forum/general/feature-requests/357-typescript-ts-bridge-net-c-wrapper-bindings-type-safe

http://forums.bridge.net/forum/general/extensions-and-plugins/2625-syncfusion-typescript-ds-bridge-net-c-bindings

This is a very technically challenging project, not to mention time consuming.

We can't promise anything, but this is obviously a good idea and we will discuss.

**Comment by michaelcheers** [comment]
@geoffreymcgill, I have a new project called [TypescriptToCS2](https://github.com/michaelcheers/TypescriptToCS2) you could check out.

**Comment by geoffreymcgill** [comment]
[Retyped](https://retyped.com) is now available and currently supports 2200+ binding libraries. More being added all the time.

Custom package generation is not yet possible with Retyped, but we do hope to provide some options soon. For now, only packages available on [Definitely Typed](definitelytyped.org) and [NPM](https://www.npmjs.com/) are supported. 

Hope this helps.
