### ISSUE TITLE
Support for volatile keyword

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2225]
[volatile keyword](https://msdn.microsoft.com/en-us/library/x13ttww7.aspx)
[IsVolatile Class](https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.isvolatile%28v=vs.110%29.aspx)

Related to forum thread:
http://forums.bridge.net/forum/community/help/3288-volatile-keyword-support

### Expected

```js
// should compile, but be ignored as volatile is not relevant in the JavaScript world. 
```

### Actual

```js
// Compiler error
// Predefined type 'System.Runtime.CompilerServices.IsVolatile' is not defined or imported
```

### Steps To Reproduce

http://deck.net/b3b85f8e79f76a9bdde624dfa81aded8

```cs
class VolatileTest
{
    public volatile int i;

    public void Test(int _i)
    {
        i = _i;
    }
}
```

**Comment by michaelcheers** [comment]
@geoffreymcgill, [We don't have threads yet though](1117).

**Comment by LeonidVeriga** [comment]
@michaelcheers, Yes, we will get code with `volatile` keyword compiled.
