### ISSUE TITLE
Support MSBuild properties within bridge.json

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2227]
Support adding MSBuild macros within the **bridge.json** configuration file. 

https://msdn.microsoft.com/en-us/library/c02as0cs.aspx
```js
{
   "output": "$(OutDir)/wwwroot/js",
   "outputBy": "Project",
}
```

* Supported variables
  - $AssemblyName
  - $CheckForOverflowUnderflow
  - $Configuration
  - $DefineConstants
  - $OutDir
  - $OutputPath
  - $OutputType
  - $Platform
  - $RootNamespace;
* command-line **bridge.exe** has new parameter **--settings** (or short **-S**) that can specify project settings. It may be used in folder mode; in project  mode it can specify the settings to avoid reading csproj file for it.
  Format (comma-delimited list of project settings): --settings|-S <name:value>[,<name:value>]
  Example: `-S "OutputPath:bin\Debug,RootNamespace:MyProject`
  List of allowed settings:
  - AssemblyName
  - CheckForOverflowUnderflow
  - Configuration
  - DefineConstants
  - OutputPath
  - OutDir
  - OutputType
  - Platform
  - RootNamespace

  Note: options **-c** (--configuration), **-P** (--platform) and **-D** (--defineConstants) have priority over those from **-S** (--settings).

### See Also

* http://forums.bridge.net/forum/general/feature-requests/3290-open-2227-output-param-in-bridge-json

**Comment by LeonidVeriga** [comment]
The current implementation is in progress - see #2425

**Comment by geoffreymcgill** [comment]
MSBuild properties added to `output` documentation:
https://github.com/bridgedotnet/Bridge/wiki/Global-Configuration#output
