### ISSUE TITLE
Deploy bridge.js to cdnjs

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2228]
https://cdnjs.com/ ([GitHub](https://github.com/cdnjs/cdnjs))

Currently, Bridge client files are deployed to our [Speed](https://github.com/bridgedotnet/Speed/tree/master/bridge) repo and specific releases can be accessed using the following URL pattern:

```html
http://speed.bridge.net/bridge/{VersionNumber}/bridge.js // bridge.min.js | bridge.d.ts
```

#### Example

* http://speed.bridge.net/bridge/15.7.0/bridge.min.js
* http://speed.bridge.net/bridge/15.7.0/bridge.js
* http://speed.bridge.net/bridge/15.7.0/bridge.d.ts

## See Also

* http://forums.bridge.net/forum/general/feature-requests/3281-please-host-runtime-on-cdnjs

**Comment by hare1039** [comment]
Hi
I am a member from cdnjs, and we also want to add this library into our service.
https://github.com/cdnjs/cdnjs/issues/10225

Would you please tell me which files we should host?
Thank you for any help you can provide!

**Comment by geoffreymcgill** [comment]
Hi @hare1039, 

Thanks for helping us get Bridge added to CDNJS. 

Can you double-check that the following **package.json** is correctly formatted? 

This config is to be added to `ajax/libs/bridge/package.json`.

The .js version history of Bridge is available in our [Speed](https://github.com/bridgedotnet/Speed/tree/master/bridge) repo, which is where the **package.json** points to. 

The **package.json** is based on advice from the follow wiki doc:

https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

#### project.json

```json
{
  "name": "bridge",
  "filename": "bridge.min.js",
  "description": "C# to JavaScript compiler. Write modern mobile and web apps in C#. Run them anywhere in JavaScript with Bridge.NET.",
  "homepage": "http://bridge.net",
  "author": "Bridge.NET <hello@bridge.net>",
  "keywords": [
    "csharp",
    "dotnet",
    "typescript",
    "compiler",
    "c#",
  ],
  "namespace": "Bridge",
  "license": "Apache-2.0",
  "repository": {
    "type": "git",
    "url": "https://github.com/bridgedotnet/Speed.git"
  },
  "autoupdate": {
    "source": "git",
    "target": "git://github.com/bridgedotnet/Speed.git",
    "fileMap": [
      {
        "basePath": "bridge",
        "files": [
          "**/*",
        ]
      }
    ]
  }
}
```

**Comment by hare1039** [comment]
@geoffreymcgill 
We don't need this field in out format.
> "namespace": "Bridge",



Also as our auto-update bot updates library according to git tags (It will fetch each git tags with the files within folder "bridge". If another version comes out, It will fetch the files in that version.), so I'm not sure `autoupdate` field this is valid.
Would you like to send a PR to cdnjs to discuss more or let me handle this?

**Comment by geoffreymcgill** [comment]
Actually, it would be great if you could submit the pull-request. Can you post a link here to the PR once available? I'll review and submit and changes if I see something. 

Thanks again for all the help.

**Comment by hare1039** [comment]
I created the PR => https://github.com/cdnjs/cdnjs/pull/10835

**Comment by geoffreymcgill** [comment]
Bridge has been deployed to [cdnjs](https://cdnjs.com/libraries/Bridge.NET) and will be auto-updated with each new release. 

https://cdnjs.com/libraries/Bridge.NET

Thanks to @hare1039 for all the assistance! 👍
