### ISSUE TITLE
Are references to third party assemblies supported?

### ISSUE THREAD

**Issue by fubar-coder** [bridgedotnet/Bridge#2237]
I'd like to add a third party assembly to my project and use it. The assembly doesn't depend on (probably) problematic things. Is this somehow possible?

When I tried this, the build succeeded, but all code from the third party assembly was missing from the JS file.

**Comment by LeonidVeriga** [comment]
Hi @fubar-coder,

Welcome to Bridge.NET!

Yes, referencing assemblies should work in order to get its script into an output folder.

The only thing is that the assembly being referenced should be a Bridge library (i.e. build with Bridge).

**Comment by fubar-coder** [comment]
Is it planned to support non-Bridge assemblies too?

**Comment by geoffreymcgill** [comment]
> Is it planned to support non-Bridge assemblies too?

At this time it is not possible.
