### ISSUE TITLE
Support bool Element.Hidden

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#2243]
As explained here:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden

**Comment by LeonidVeriga** [comment]
Thanks for the request @TriEdgeAI.

I would add it into [Element](https://github.com/bridgedotnet/Bridge/blob/master/Html5/Elements/Element.cs#L82). I.e. into the class containing `Id` and other global attributes.

**Comment by TriEdgeAI** [comment]
Awesome!
