### ISSUE TITLE
Not recognizing #endregion in case of property with initializers

### ISSUE THREAD

**Issue by rufio620** [bridgedotnet/Bridge#2249]
The Bridge parser creates a parsing error when attempting to compile the referenced deck class. This is the first time I have had any issue with regions. If I move the region to not encapsulate the static field I do not get any error. For some reason the parser is not finding the #endregion

### Expected

C# regions should be handled by the Bridge parser.

### Actual

```
Bridge.Contract.EmitterException: Parsing error in a file \\fs6-n02\stor14wc1ord1\956235\www.deck.net\web\content\UserCode\sfsfgmeni0vqqf5rbkpw03l5.cs (Line 116, Col 1): #endregion directive expected
   at Bridge.Translator.Translator.BuildSyntaxTree()
   at Bridge.Translator.Translator.Translate()
   at Deck.Translator.Translate(String& output)
   at Deck.TranslateHandler.Translate(String csCode, String filter, String pos)
```

### Steps To Reproduce

http://deck.net/bf224adce58c1aeac55e9cbe58a82635/vert

**Comment by LeonidVeriga** [comment]
A test case can be reduced to:
http://deck.net/f49a8878e70af161154e513f549be5d7/vert
```cs
public sealed class StringComparer
{

    #region Static Comparers

    public static StringComparer OrdinalIgnoreCase { get; } = new StringComparer();

    #endregion
}
```
