### ISSUE TITLE
Remove not .Net standard method List<T>.GetRange()

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#2255]
Current implementation of `List<T>` contains not .Net standard method (it will be marked with `[Obsolete]`):
```cs
public extern List<T> GetRange(int index);
```

Please use the standard method:
```cs
public extern List<T> GetRange(int index, int count);
```

**Comment by geoffreymcgill** [comment]
How about add the new Method, and tag the old one with `[Obsolete]`.

**Comment by LeonidVeriga** [comment]
The new Method already exists, the old one will be marked with `[Obsolete]`.
