### ISSUE TITLE
Not recognizing #endregion in case of property with initializer

### ISSUE THREAD

**Issue by kosmab** [bridgedotnet/Bridge#2257]
Following program fails to compile. 
Without initializer it does.

### Expected

<complied code>

### Actual
compiler output:
"C# to JavaScript Compilation Failed
> Bridge.Contract.EmitterException: Parsing error in a file \\fs6-n02\stor14wc1ord1\956235\www.deck.net\web\content\UserCode\hou0qcnv22smxsr0rhubegyp.cs (Line 31, Col 1): #endregion directive expected
   at Bridge.Translator.Translator.BuildSyntaxTree()
   at Bridge.Translator.Translator.Translate()
   at Deck.Translator.Translate(String& output)
   at Deck.TranslateHandler.Translate(String csCode, String filter, String pos)"

### Steps To Reproduce

http://deck.net/75e5c381fd5988de80e0c6262bf68383

```cs
public class c1
{
    #region properties
    public string p1 { get; set; } = "";
    #endregion
}
```

**Comment by LeonidVeriga** [comment]
Related to https://github.com/bridgedotnet/Bridge/issues/2249
