### ISSUE TITLE
Generated Bridge.Html5 (from SaltarelleWeb)

### ISSUE THREAD

**Issue by n9** [bridgedotnet/Bridge#2285]
Issue for https://github.com/bridgedotnet/Bridge/issues/1413#issuecomment-222588041

Or is it tracked in another ticket?

**Comment by geoffreymcgill** [comment]
Hi @n9, 

We're working on a project related to this issue. We will not be re-using the original [SaltarelleWeb](https://github.com/Saltarelle/SaltarelleWeb) source, but similar to SaltarelleWeb, we will be auto-generating the [Bridge] C# project from a similar original JavaScript spec source document.

This new project is close to being ready for release.

Once released, I'll update this thread and we can discuss

**Comment by geoffreymcgill** [comment]
@n9 – Is there a specific class (or more) of the SaltarelleWeb API that you're missing? I just want to make sure that same api has coverage in the new project.

**Comment by n9** [comment]
I am investigating whether it is feasible for me to migrate everything to the Bridge or to the TypeScript. (I have not started the migration to the Bridge.)

**Comment by michaelcheers** [comment]
Try [My typescript to C# converter](https://github.com/michaelcheers/TypescriptToCS2), or if you just want the result [here's the file](https://1drv.ms/u/s!Av0Nwqk2Bg1nhfo4zld9YvWV94Rt7A)

**Comment by n9** [comment]
@michaelcheers Great. (What about a C# to TypeScript converter? :D)

**Comment by michaelcheers** [comment]
@n9, Bridge is making one of those, I think.

**Comment by n9** [comment]
@michaelcheers I thought that Bridge is compiling C# to old JavaScript.

**Comment by geoffreymcgill** [comment]
@n9 – what would be the advantage of compiling to Typescript?

**Comment by n9** [comment]
@geoffreymcgill 
(Disclaimer 1: I was just kidding -- it was a reaction to "Typescript to C#" converter.)  

Now seriously:
(Disclaimer 2: I am not 100% sure about current state of Bridge. I am still using the old Saltarelle.)

The advantage will be support for:
* hot module replacement (react/webpack)
* annotations (mobx, ...)
* better integration TypeScript code

Moreover, I was thinking a bit about the future of a C# to JS compiler/transpiler. There are two reasons why I would still use C# instead of TypeScript:

1. Sharing a code between .NET and JS (especially for algorithms and validations)
2. TypeScript language is just JavaScript with types, it is designed to be compatible with next JS. I am missing nominal typing, extension methods, ?. operator, and more. (Currently, the main reason, why I am also using TypeScript, is JSX.)

It seems to me that Bridge tries hard to implement (nearly 1:1) many .NET Framework features. With arrival of  small .NET Standard/Core, the main functionality is in external packages. It will be really hard to support various versions of various (nuget) packages in order to run C#/.NET program in JS. 

Moreover, it seems to me that [C# is evolving](https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md) faster than C# to JS transpiler can (https://github.com/bridgedotnet/Bridge/issues/2455). 

Supporting both .NET compatibility and up to date C# compatibility is a huge work.  I prefer having an up to date bug free transpiler with small working subset of framework. (Users can easily contribute a framework part than the transpiler part.)

**Comment by geoffreymcgill** [comment]
@n9 – Thanks for the excellent feedback. 

> Moreover, it seems to me that C# is evolving faster than C# to JS transpiler can (#2455).

Regarding C#7 support, it's something we'll be working on right away. There's no particular reason why this isn't supported right now, other than; 1. we haven't received much demand from the Bridge community to support C#7; 2. we've been working on other high-demand features. 

Anyway's, we'll be supporting very soon. The goal was to include into the final 16.0 release, but that might get delayed until 16.1. 

Hope this helps.

**Comment by n9** [comment]
How the demand for various features is compared/evaluated in Bridge?

**Comment by geoffreymcgill** [comment]
Generally, the squeaky wheel will get the grease... if the feature request is in scope for the project.

**Comment by geoffreymcgill** [comment]
The original topic of this issue was regarding automating the generation of the native JavaScript API binding libraries. We have just launched [Retyped](https://retyped.com).

The [Retyepd](https://www.nuget.org/packages/retyped) package would be the functional equivalent of **Bridge.Html5**. 

[Deck](https://deck.net/) has been upgraded to support Retyped, and you can test the base Retyped packages within your Decks. See,

https://deck.net/welcome

Hope this helps.
