### ISSUE TITLE
Add support for get and set when translating properties

### ISSUE THREAD

**Issue by rufio620** [bridgedotnet/Bridge#2289]
C# properties appear are translated into individual getters and setter methods, but for some reason they don't use the native javascript get and set language constructs.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/set

The fact that getters and setters are not translated with the same language semantic causes issues when attempting to share C# classes on both client and server as well as with serialization of data.

The following forum post discusses this and references that perhaps this could be a compilation setting in order to provide backward compatibility for older browsers. Could this be implemented as a new feature or is there someway to accomplish this via the plugin framework?

http://forums.bridge.net/forum/community/help/385-typescript-properties

**Comment by geoffreymcgill** [comment]
Our plan is to implement this change in Bridge 16.0. We agree that it absolutely must be done. 

Also being tracked in #1229.
