### ISSUE TITLE
Calling Add on an array does not produce a runtime error

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#2299]
### Expected
```
Run-time exception (line 9): Collection was of a fixed size.

Stack Trace:

[System.NotSupportedException: Collection was of a fixed size.]
  at Program.Main(): line 9
```
### Actual
```
2
```
### Steps To Reproduce
[Dot Net Fiddle](https://dotnetfiddle.net/tFNf6O)
[Live Bridge](http://deck.net/544eddd66d8d19638b3f00dbfba5b559)

```c#
public class Program
{
    public static void Main()
    {
        int[] array = new[] { 7 };
	((IList<int>)array).Add(5);

	Console.WriteLine(array.Length);
    }
}

**Comment by kcudnik** [comment]
This will be curious to solve, in my case i would still like to have possibility for Push and Pop to work like in JS

**Comment by michaelcheers** [comment]
It doesn't seem that hard.
[Change this line to throw Exception.](https://github.com/bridgedotnet/Bridge/blob/master/Bridge/Resources/Array.js#L273)
