### ISSUE TITLE
Building project?

### ISSUE THREAD

**Issue by XtremePlayzCODE** [bridgedotnet/Bridge#2305]
Is it possible to build Bridge.NET's components (Contract, Builder, Bridge, Html5, Translator) into .dll's and a .exe for Bridge.Builder from this source code?

**Comment by geoffreymcgill** [comment]
Can you post this question in the [forums](http://forums.bridge.net)? We generally like to keep Issues focused on Defect and Feature tracking. General technical support questions are best asked in the forums.

**Comment by XtremePlayzCODE** [comment]
Ok, thanks for the information. I will post this question in the forums.
