### ISSUE TITLE
Incorrect Boolean type name (expected System.Boolean)

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#2308]
Boolean's type FullName should be `System.Boolean` instead of `Boolean`.

### Steps To Reproduce

http://deck.net/0ff74a3385585c866a1860b9db941e85

```c#
public class Program
{
    public static void Main()
    {
        var b = true;
        
        // Expected System.Boolean
        Console.WriteLine(b.GetType().FullName);
    }
}
```

**Comment by LeonidVeriga** [comment]
Duplicate of #2062

**Comment by michaelcheers** [comment]
Didn't I mention that in #1347?

**Comment by LeonidVeriga** [comment]
@michaelcheers , yes #1347 mentioned all the issues. We just split it to easy track as changes go separately step-by-step.
