### ISSUE TITLE
Single module is loaded multiple times

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#2312]
If AMD module is defined in a referenced assembly, the module reference will be emitted as many times as many dependencies from that module are used.

### Steps To Reproduce

```c#
var class1 = new Module1.Class1();
var class2 = new Module1.Class2();
```

### Expected Result

```js
require(["Module1"], function (Module1) {

}
```

### Actual Result

```js
require(["Module1","Module1"], function (Module1,Module1) {

}
```

**Comment by LeonidVeriga** [comment]
Related to #2217 Module functionality redesign
