### ISSUE TITLE
Plotly Bindings

### ISSUE THREAD

**Issue by sirinath** [bridgedotnet/Bridge#2334]
Is it possible to add Plotly (https://plot.ly/) bindings?

**Comment by geoffreymcgill** [comment]
Hi @sirinath – Thanks for the suggestion. We will investigate Plotly. In general, supporting JavaScript frameworks is best provided by the community. Out focus is mostly on supporting the compiler.

**Comment by sirinath** [comment]
OK.

I think there should be some basic charting, widget, dashboard to make life easy.

**Comment by Zaid-Ajaj** [comment]
@sirinath I have binding for [chart.js](http://www.chartjs.org/) in [this repo](https://github.com/Zaid-Ajaj/Bridge.ChartJS) with an example of how to use it.

**Comment by geoffreymcgill** [comment]
Plotly is now supported using [Retyped](https://retyped.com/).

https://retyped.com/?q=plotly#search

Hope this helps.
