### ISSUE TITLE
DateTime.ToString doesn't conform to Custom Date and Time Format Strings

### ISSUE THREAD

**Issue by shadow-cs** [bridgedotnet/Bridge#2337]
`DateTime.ToString(format, provider)` does not conform to [Custom Date and Time Format Strings](https://msdn.microsoft.com/en-us/library/8kb3ddd4(v=vs.110).aspx).

### Steps To Reproduce

http://deck.net/e7851899331080a5240e80f698554ecb/top

```c#
public class Program
{
    public static void Main()
    {
        var date = new DateTime(2017, 2, 6, 10, 42, 52, 1);
        
        Console.WriteLine(date.ToString("yyyy-MM-dd HH:mm:ss.FFFFFFF", CultureInfo.InvariantCulture));
    }
}
```

### Expected Result

```js
2017-02-06 10:42:52.001
```

See https://dotnetfiddle.net/JmJhwW

### Actual Result

```js
2017-02-06 10:42:52.FFFFFFF
```

I know that JS does not hold such precision but replacing with ms should be sufficient I think.

**Comment by vladsch** [comment]
Date object doesn't manage accuracy beyond milliseconds
So, Bridge can support `f{1,3}|F{1,3}` modifiers only (f ff fff F FF FFF)

We will include support of such modifiers

**Comment by shadow-cs** [comment]
.Net truncates the result if the precision cannot be met, it would be great if Bridge supported `FFFFFFF` but always returned truncated result (so current code doesn't generate completely invalid output).
