### ISSUE TITLE
IList vs int[]

### ISSUE THREAD

**Issue by lskyum** [bridgedotnet/Bridge#2345]
I know it's an unlikely and obscure use-case, but just for correctness.

http://deck.net/4f8df795ed0001e39300e6965deca96e
```c#
using System;
using System.Collections;

public static class Program
{
    public static void Main ()
    {
        int[] a = new int[10];
        IList list = a;
        list[0] = null;

        // This prints (null) but that should never be possible from an int[]
        Console.WriteLine("(" + a[0] + ")");
    }
}
```

**Comment by vladsch** [comment]
I guess it is related issues
https://github.com/bridgedotnet/Bridge/issues/2299

**Comment by LeonidVeriga** [comment]
@vladsch, that's a different one - https://dotnetfiddle.net/Wdrd4h
It not throw an exception nor changes the value.
