### ISSUE TITLE
SyntaxError: Unexpected token + 

### ISSUE THREAD

**Issue by danieldegtyarev** [bridgedotnet/Bridge#2351]
The following C# code produces invalid JS.

### Steps To Reproduce

http://deck.net/3c2ebd6218398d0b9f60b3817c2f7a74

```c#
interface IPair<A,B>{
    
}

interface IFoo<T>{
    int X { get;}
}

class Foo<T1,T2> : IFoo<IPair<T1,T2>>{
    int IFoo<IPair<T1,T2>>.X {get{return 0;}}
}
```

### Actual Result

Uncaught SyntaxError: Unexpected token +

**Comment by geoffreymcgill** [comment]
Looks like this issue has already been fixed and will be available in the next release. The fix is in **master**. 

Trying to find the specific issue where this was fixed...

**Comment by vladsch** [comment]
Duplicates with https://github.com/bridgedotnet/Bridge/issues/2278
