### ISSUE TITLE
HTML[TAG]Element classes revised to be sealed

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2362]
HTML[Tag]Element classes cannot be inherited from in JavaScript, so classes should be `sealed` in C#.

This includes the following classes within the **Bridge.Html5** Assembly:

```
HTMLAnchorElement
HTMLAreaElement
HTMLAudioElement
HTMLBaseElement
HTMLBodyElement
HTMLBRElement
HTMLButtonElement
HTMLCanvasElement
HTMLDataListElement
HTMLDivElement
HTMLDListElement
HTMLEmbedElement
HTMLFieldSetElement
HTMLFormElement
HTMLHeadElement
HTMLHeadingElement
HTMLHRElement
HTMLHtmlElement
HTMLIFrameElement
HTMLImageElement
HTMLInputElement
HTMLKeygenElement
HTMLLabelElement
HTMLLegendElement
HTMLLIElement
HTMLLinkElement
HTMLMapElement
HTMLMetaElement
HTMLMeterElement
HTMLModElement
HTMLObjectElement
HTMLOListElement
HTMLOptGroupElement
HTMLOptionElement
HTMLOutputElement
HTMLParagraphElement
HTMLParamElement
HTMLPreElement
HTMLProgressElement
HTMLQuoteElement
HTMLScriptElement
HTMLSelectElement
HTMLSourceElement
HTMLSpanElement
HTMLStyleElement
HTMLTableCaptionElement
HTMLTableColElement
HTMLTableDataCellElement
HTMLTableElement
HTMLTableHeaderCellElement
HTMLTableRowElement
HTMLTableSectionElement
HTMLTemplateElement
HTMLTextAreaElement
HTMLTitleElement
HTMLTrackElement
HTMLUListElement
HTMLUnknownElement
HTMLVideoElement
MarkElement
```

There are three notable exceptions: 

Name | Description
---- | ----
**HTMLElement** | All HTML[Tag]Element classes inherit from **HTMLElement**
**HTMLTableCellElement** | Inherited by **HTMLTableDataCellElement** and **HTMLTableHeaderCellElement**
**HTMLMediaElement** | Inherited by **HTMLVideoElement** and **HTMLAudioElement**

Related to:

* http://forums.bridge.net/forum/bridge-net-pro/bugs/3474-could-html%7Bwhatever%7Delement-classes-be-sealed

**Comment by LeonidVeriga** [comment]
Related to #1238 Html Elements cannot have direct inheritance

**Comment by kcudnik** [comment]
Please unseal html elements or propose workaround for this:

`
    [External]
    [ObjectLiteral]
    public class ExtendedImageElement : HTMLImageElement
    {
        public int Zoom;
        public double Foo;
    }

  ExtendedImageElement img = ownerDocument.CreateElement("img").As<ExtendedImageElement>();

// here we can access img elements and also extra fields (compiler check types) from one variable
// very easy to use
`

**Comment by geoffreymcgill** [comment]
Hi @kcudnik – I'm going to discuss your sample with the team, but my opinion at the moment is that your scenario should not work. The end result creates a [monkey-patched](https://en.wikipedia.org/wiki/Monkey_patch#Pitfalls) `<img>` object, which is bad form.

The **Html*Element** classes need to be sealed to prevent inheritance. Html Elements cannot be inherited, and Bridge shouldn't be providing a hidden way to work around this limitation.

My question back to you would be: How do you implement your scenario using raw JavaScript?

**Comment by kcudnik** [comment]
I'm working with map tiles, and i'm using each map tile image to store extra information like x,y + zoom, and some other data, this way i don't need extra object to track each tile and remap to extra data,
im using "inheritance" here to extend object, not try to create new one, and it's fine in js to add new fields in existing objects like div/img etc in JS, this is maybe not the cleanest solution, but it work's

Of course i already workarounded that using As<> member.

And i completly understand your point on sealing those classes. Thanks for taking this to considerations.

**Comment by geoffreymcgill** [comment]
> and it's fine in js to add new fields in existing objects like div/img etc in JS

Yes, it's possible, but not recommended, especially for native objects. You're just inviting problems if you do this.

**Comment by kcudnik** [comment]
Understood
