### ISSUE TITLE
Clone project build fails on master branch 

### ISSUE THREAD

**Issue by caviles** [bridgedotnet/Bridge#2373]
It's seems that Bridge.Test.Core is not on nuget.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Test' does not exist in the namespace 'Bridge' (are you missing an assembly reference?)	Batch1	C:\Users\...\Source\Repos\Bridge\Tests\Batch1\ArrayTests.cs	2	Active

### Steps To Reproduce

Clone and build Build project from master branch.

**Comment by LeonidVeriga** [comment]
Hi @caviles,

Welcome to **Bridge.NET**!

Please use **Bridge.sln** - it does not require **Bridge.Test**.
We are expecting to release **Bridge.Test** soon.
