### ISSUE TITLE
HashSet Constructor Initializer does not work

### ISSUE THREAD

**Issue by rufio620** [bridgedotnet/Bridge#2384]
HashSet constructor argument for initializing the set does not appear to do anything.

### Steps To Reproduce

http://deck.net/a4656173d475692df4fd7928deb45079

### Expected Result

2
true

### Actual Result

1
false

**Comment by geoffreymcgill** [comment]
Thank you for reporting and providing the simplified sample demonstrating how to reproduce.
We will investigate.

**Comment by vladsch** [comment]
.NET application provides the same result
https://dotnetfiddle.net/yueOlM

**Comment by vladsch** [comment]
Just in your sample, you forgot closing quote
[VAR]"value, count"[/VAR]

should be
[VAR]"value", "count"[/VAR]

**Comment by geoffreymcgill** [comment]
With a corrected sample:

http://deck.net/71d04871713c289fc00a39c67b52a45d

```c#
public class Program
{
    private static readonly HashSet<string> ReservedKeywords = new HashSet<string>(new[] { "value", "count" });
    
    public static void Main()
    {
        var msg = "Hello, World!";
        
        Console.WriteLine(ReservedKeywords.Count);
        Console.WriteLine(ReservedKeywords.Contains("value"));
    }
}
```
