### ISSUE TITLE
nameof Returns Wrong Casing for Properties

### ISSUE THREAD

**Issue by rufio620** [bridgedotnet/Bridge#2385]
When calling nameof on a property the casing is changed. This causes issues accessing properties using an indexer when utilizing nameof.

### Steps To Reproduce

http://deck.net/05126f25744ece3b2749895e6888a21e

### Expected Result
Property name casing should be preserved/reflect the preserveMemberCase compiler setting.

Output should be

Id
IdProp

### Actual Result

Id
idProp

**Comment by vladsch** [comment]
Duplicates with https://github.com/bridgedotnet/Bridge/issues/2375

**Comment by geoffreymcgill** [comment]
This defect has been recently fixed in #2375. The fix has been merged into the **master** branch.
