### ISSUE TITLE
goto statement

### ISSUE THREAD

**Issue by amarinsek** [bridgedotnet/Bridge#2388]
Any chance to implement goto statement?
(I am working with the jay compiler compiler tool that generates an LR parser code using also goto statements...)

**Comment by LeonidVeriga** [comment]
Hi @amarinsek!

Welcome to Bridge.NET!

We do not have a firm timeframe for this feature. We will discuss it on our team miting and update.

There is already GOTO feature request created - #1004. We are marking this issue as duplicate.

**Comment by LeonidVeriga** [comment]
Update on #1004 - GOTO statement support will be included in the next release.
