### ISSUE TITLE
Support Task.Wait Method

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2406]
https://msdn.microsoft.com/en-us/library/system.threading.tasks.task.wait(v=vs.110).aspx

### Steps To Reproduce

http://deck.net/85271e9aa4b48060ce45751998acb622

```c#
using System;
using System.Threading.Tasks;

public class Example
{
    public static void Main()
    {
        Task t = Task.Run(() => 
        {
            Random rnd = new Random();
            long sum = 0;
            int n = 5000000;
            
            for (int ctr = 1; ctr <= n; ctr++) 
            {
                int number = rnd.Next(0, 101);
                sum += number;
            }

            Console.WriteLine("Total:   {0:N0}", sum);
            Console.WriteLine("Mean:    {0:N2}", sum/n);
            Console.WriteLine("N:       {0:N0}", n);   
        });

        TimeSpan ts = TimeSpan.FromMilliseconds(150);
        
        if (! t.Wait(ts))
        {
           Console.WriteLine("The timeout interval elapsed.");
        }
    }
}

// The example displays output similar to the following:
//       Total:   50,015,714
//       Mean:    50.02
//       N:       1,000,000
// Or it displays the following output:
//      The timeout interval elapsed.
```

## See Also

* http://forums.bridge.net/forum/general/feature-requests/3533-task-delay-with-cancellationtoken-support
* #2405
* https://gitter.im/bridgedotnet/Bridge?at=5c87d7fb1fae6423ca732aea

**Comment by hardhub** [comment]
Hopefully it will be implemented soon.

**Comment by geoffreymcgill** [comment]
Another simplified sample that demonstrates using `Task.Wait`.

https://deck.net/0934f68b949c3109145770a819870481

```csharp
using System;
using System.Threading.Tasks;
				
public class Program
{
	public static void Main()
	{
		var result = Task.Run(() =>
        {
            Console.WriteLine("Hello world");
        });

        result.ContinueWith(
            (test) =>
            {
				Console.WriteLine("1");
            }).Wait();

    	Console.WriteLine("2");
	}
}
```

**Comment by vladsch** [comment]
The pull request is created. Timeout is not supported still because the overloads with timeout can be used inside expressions (current implementation correctly handles Wait as a statement only). 

I will try to implement timeout overloads lately (however, timeout is not possible for all cases in JS, only for real async tasks like ajax requests and etc )

**Comment by vladsch** [comment]
Timeout and cancellation are implemented now

**Comment by fabriciomurta** [comment]
This is fully implemented and merged, except with the detail of timeout handling in the original deck here, which has been logged under #3884. Will be included next Bridge release.

**Comment by stgolem** [comment]
Please consider also implement full async - Wait - sync scenario from #3940
