### ISSUE TITLE
bridge.json option to enable named function expressions and 

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#2407]
Our current plan is rename the setting in **bridge.json** to `enableNamedFunctionExpressions`, default is `false`. 

The setting will use named function expressions for functions:
 - Before: `myFunction: function () { /* .. */ ]`
 - Revised: `myFunction: function myFunction() { /* .. */ ]`

The setting will only be available in **bridge.json** and would apply the extra function name to all Methods in the whole assembly. It's an assembly level on|off setting, with the explicit decision to enable.

This allows developers to choose whether they want the extra name to be applied in their generated .js. This feature has no impact on the C# side and no downstream implications for inherited libraries. The only real penalty is maybe a 1-2% increase in .js file size, although as mentioned above, this may be mitigated with gzipping, but we haven't tested to confirm. 

As best we can determine, adding this extra function name is only required to work around a _current_ limitation of Firefox. At some point, I think it's fair to assume, that that limitation will fixed in Firefox, at which point there would be no use for this _feature_ in Bridge. 

We also do not want to enable this extra function name rendering for all libraries, and suffer the inevitable blow-back from those that do not understand the rational for adding the extra name. 

We also do not want to enable rendering this extra function name, then at some point (after Firefox supports) not render.

If a developer (or the library) requires this extra function name added to their generated .js, just explicitly set `"enableNamedFunctionExpressions": true` in your **bridge.json** and you're good to go. 

```js
{
    "enableNamedFunctionExpressions": true
}
```

See https://github.com/bridgedotnet/Bridge/pull/2317#issuecomment-281820339

**Comment by LeonidVeriga** [comment]
**enableNamedFunctionExpressions** option changed in PR #2674: new name is **namedFunctions**.
See more info at https://github.com/bridgedotnet/Bridge/wiki/Global-Configuration#namedfunctions.
