### ISSUE TITLE
Update documentation - bridge.json enableNamedFunctionExpressions option

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#2409]
Add new global option to https://github.com/bridgedotnet/Bridge/wiki/global-configuration

## enableNamedFunctionExpressions

**Type:** `boolean`

True to enable using named function expressions to C# methods. False is default value.

#### Example

C# method example
```cs
public void DoSomething();
```

Generated js code for `false`
```js
doSomething: function () ...
```

Generated code js code for `true`
```js
doSomething: function doSomething() ...
```

#### Example of `bridge.json`
```js
"enableNamedFunctionExpressions": true
```

## See Also

* #2407

**Comment by vladsch** [comment]
This global option is removed from pull request. AnnotatedFunction attribute was introduced

**Comment by LeonidVeriga** [comment]
The related PR #2408 is not closed yet and this functionality may change.

**Comment by geoffreymcgill** [comment]
Documentation has been added, see
https://github.com/bridgedotnet/Bridge/wiki/Global-Configuration#enablenamedfunctionexpressions

**Comment by LeonidVeriga** [comment]
**enableNamedFunctionExpressions** option changed in PR #2674: new name is **namedFunctions**.
See more info at https://github.com/bridgedotnet/Bridge/wiki/Global-Configuration#namedfunctions.
