### ISSUE TITLE
Template functions

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#2414]
If you have a template function:
```csharp
[Template("{a}+{a}")]
static extern int Method (int a);
```
and `a` is a call to a function:
```csharp
static int CallCount ()
{
     callCount++;
     return 1;
}
```
then I think callcount shouldn't be called twice.

**Comment by vladsch** [comment]
Can you provide test case?
I cannot reproduce in 15.7 version.
http://deck.net/1cd4a6f9febcd80b2cd5774b770c8f6b
