### ISSUE TITLE
Bridge.JSON serialization and deserialization 

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#2418]
Enhanced JSON serialize/deserialize functionality in **Bridge.JSON.Serialize** and **Bridge.JSON.Deserialize**.

ObjectLiteral serialization/deserialization is supported partialy because there is no type definition and metadata for such types.

Generic versions of **Bridge.Html5.JSON** methods (like `JSON.Parse<T>`) marked with `[Obsolete]` and then will be removed in next major release.

http://deck.net/3f1be149cb69304476808f8b8e8ff349/top

```cs
public class Program
{
    public static void Main()
    {
        var persons = new[]
        {
            new Person(
                Guid.Parse("{CEADF3CA-0EB4-43F3-A813-1266E16498AC}"),
                "John", "New-York", "Fifth Avenue"
            ),
            new Person(
                Guid.Parse("{64F09E69-39FE-4D9C-BDB3-108CA2CCFAD9}"),
                "Mary", "London", "St Mary Axe"
            )
        };
        
        var serialized = Bridge.JSON.Serialize(persons);
        
        Console.WriteLine("Serialized:");
        Console.WriteLine(serialized);
        
        var deserialized = Bridge.JSON.Deserialize<Person[]>(serialized);
        
        Console.WriteLine("Deserialized:");
        Console.WriteLine(deserialized[0].ToString());
        Console.WriteLine(deserialized[1].ToString());
    }
}

[Reflectable]
class Person
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public Address Address { get; set; }
    
    public Person(Guid id, string name, string city, string street)
    {
        this.Id = id;
        this.Name = name;
        this.Address = new Address()
        {
            City = city,
            Street = street
        };
    }
    
    public override string ToString()
    {
        return string.Format("{0} {1} {2} {3}",
            Id, Name, Address.Street, Address.City);
    }
}

[Reflectable]
public class Address
{
    public string City { get; set; }
    public string Street { get; set; }    
}
```

### See Also

* #98
* #1306
* #1432
* #1438

**Comment by Porl91** [comment]
Hi @LeonidVeriga, I've just been looking at the changes made in commit 8787acbfaa3fca1f8afc9e2e823d9f0ab5a4f4ce to add support for Bridge class serialisation. I've noticed that during serialisation the source type of the object is recorded as the '$type' property. This seems to match the convention of the Newtonsoft JSON serialiser.

Will classes serialised using these new methods deserialise cleanly with Newtonsoft by default?

@DanTup

**Comment by LeonidVeriga** [comment]
@Porl91,

In the final implementation merged into **master** (https://github.com/bridgedotnet/Bridge/commit/67b4799b5ef616863f6f208458408e2ffc4a2797) we removed '$type' property.

**Comment by DanTup** [comment]
@LeonidVeriga Does this mean there will be no support for deserialising into interfaces or subclasses (eg. if I have a `List<SomeThing>` but serialised a `SomeBetterThing` which inherits from `SomeThing`)?

**Comment by vladsch** [comment]
Can you provide test sample with Newtonsoft to demonstrate such functionality?

**Comment by DanTup** [comment]
@vladsch There's some info on this here:

http://www.newtonsoft.com/json/help/html/SerializeTypeNameHandling.htm

The type gets encoded into a property named `$type` and the JSON.NET deserializer reads that values and then constructs the correct type based on it.

I don't know how easily you could be compatible with this (or whether you'd consider it a worthy goal) but serialising on the client then deserialising on the server is a common task and since MS seem to have gone all-in with JSON.NET, it seems like the best option for server code that wants to support .NET Core.

**Comment by LeonidVeriga** [comment]
@DanTup,  @Porl91 

We are including two additional features:
* #2426 Support serialize/deserialize of anonymous types in Bridge.Json
* #2427 Support JsonSettings for Bridge.Json

For instance, #2427 setting **JsonSettings.TypeNameHandling** adds **$type** into serialized output:
* Data structure
```csharp
[Reflectable]
interface INamedEntity
{
    string Name { get; set; }
}

[Reflectable]
class Person : INamedEntity
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public Address Address { get; set; }
}

[Reflectable]
public class Address
{
    public string City { get; set; }
    public string Street { get; set; }
}
```
* A code with serialization including type info (`new JsonSettings { TypeNameHandling = true }`):
```csharp
var persons = new[]
{
    new Person()
    {
        Id = Guid.Parse("{CEADF3CA-0EB4-43F3-A813-1266E16498AC}"),
        Name = "John",
        Address = new Address() {City = "New-York", Street = "Fifth Avenue" }
    },
    new Person()
    {
        Id = Guid.Parse("{64F09E69-39FE-4D9C-BDB3-108CA2CCFAD9}"),
        Name = "Mary",
        Address = new Address() {City = "London", Street = "St Mary Axe" }
    }
};

var serialized = Bridge.Json.Serialize(persons, new JsonSettings { TypeNameHandling = true });
```
* Value of `serialized` would contain:
```json
[  
   {  
      "$type":"Person",
      "Address":{  
         "$type":"Address",
         "City":"New-York",
         "Street":"Fifth Avenue"
      },
      "Id":"ceadf3ca-0eb4-43f3-a813-1266e16498ac",
      "Name":"John"
   },
   {  
      "$type":"Person",
      "Address":{  
         "$type":"Address",
         "City":"London",
         "Street":"St Mary Axe"
      },
      "Id":"64f09e69-39fe-4d9c-bdb3-108ca2ccfad9",
      "Name":"Mary"
   }
]
```
* That is not too far from a **Newtonsoft** example https://dotnetfiddle.net/dNFIed generating:
```json
{
  "$type": "Person[], qaesha05",
  "$values": [
    {
      "$type": "Person, qaesha05",
      "Id": "ceadf3ca-0eb4-43f3-a813-1266e16498ac",
      "Name": "John",
      "Address": {
        "$type": "Address, qaesha05",
        "City": "New-York",
        "Street": "Fifth Avenue"
      }
    },
    {
      "$type": "Person, qaesha05",
      "Id": "64f09e69-39fe-4d9c-bdb3-108ca2ccfad9",
      "Name": "Mary",
      "Address": {
        "$type": "Address, qaesha05",
        "City": "London",
        "Street": "St Mary Axe"
      }
    }
  ]
}
```

* The current output generated by **Bridge.Json** with **TypeNameHandling** cannot be deserialized by **Newtonsoft** https://dotnetfiddle.net/vXd8z9, throwing:
```
Type specified in JSON 'Person' was not resolved. Path '[0].$type'
```
Looks like value of type **$type** should have assembly included if using `TypeNameHandling.All` - `"$type": "Person, qaesha05",`.

* However, **Newtonsoft** sample without `TypeNameHandling` deserialization can deserialize json generated by **Bridge.Json** without **TypeNameHandling** - https://dotnetfiddle.net/8LfGro

**Comment by DanTup** [comment]
The bit we're most interested in requires the types (since the json contains sub-types). Is it possible to have the type name handling add the assembly name?

**Comment by LeonidVeriga** [comment]
@DanTup @Porl91 

We added assembly name into **$type**. It would be great if you pull branch [Issue2418_AssemblyName](https://github.com/bridgedotnet/Bridge/tree/Issue2418_AssemblyName) and check it works as expected for you.

A code sample to serialize with type name included by **Bridge.Json**:
```cs
var c = new SomeClass();

var json = Bridge.Json.Serialize(c, new JsonSettings { TypeNameHandling = true });
```

**Comment by DanTup** [comment]
Thanks! I'll speak with @Porl91 and we'll try and get it tested asap.

**Comment by Porl91** [comment]
Hi @LeonidVeriga,
I've just tested the work done in version 16.0 with our use cases and it works great! Is there a rough date for when we can expect this version will be released? @DanTup

**Comment by LeonidVeriga** [comment]
Thanks for testing, @Porl91!
Just merged it into **master** branch. The plan to release 16.0 - March/April (this year).

**Comment by geoffreymcgill** [comment]
As of Bridge v16, all Json serialization/deserialization support has been moved to the new **Bridge.Newtonsoft.Json** package. 

> install-package bridge.newtonsoft.json -pre

The following Deck demonstrates a basic scenario:

https://deck.net/newtonsoft.json
