### ISSUE TITLE
Cannot use reflection.

### ISSUE THREAD

**Issue by markjackmilian** [bridgedotnet/Bridge#2424]
I try to use reflection to get ctors, methods or properties without success.

### Steps To Reproduce

Example on deck:
http://deck.net/91dc9a15163dcad0e61b4f28740b429f

```c#
public static void Main()
        {
            var typeFoo = typeof(Foo);
            var ctors = typeFoo.GetConstructors();
            
			// no ctors found
            if(ctors != null)
            Console.WriteLine($"Ctors found: {ctors.Length}");
         
         	// no properties found
         	var properties = typeFoo.GetProperties();
         
         	if(properties != null)
            Console.WriteLine($"Properties found: {properties.Length}");
         
         // no methods found
         	var methods = typeFoo.GetMethods();
         
         	if(methods != null)
            Console.WriteLine($"methods found: {methods.Length}");
         
         // no method by name found
         	var sayHello = typeFoo.GetMethod("SayHello");
         
         	Console.WriteLine($"sayHello is null: {sayHello == null}");
         
        }

        public class Foo
        {
            public string Name {get;set;}
            public Foo()
            { }

            public Foo(string name)
            {
                this.Name = name;
            }
            
            public void SayHello()
            {
                Console.WriteLine("Hello!");
            }
        }
```

### Expected Result

```js
Ctors: 2
Methods: 1
Properties: 1
SayHello not null
```

### Actual Result

```js
Ctors: 0
Methods: 0
Properties: 0
SayHello is null
```

**Comment by vladsch** [comment]
Type must be reflectance. By default, Bridge doesn'the generate metadata. Just apply Reflectable attribute to a type (it can be applied to assembly also)

**Comment by markjackmilian** [comment]
Thank you for you quick reply.
Just try it and it work like expected. great!
I cannot see that attribute reference on wiki.. maybe must be update the wiki?
Thanks.

**Comment by vladsch** [comment]
Yes, we will add info about that to wiki

**Comment by markjackmilian** [comment]
Thanks again.
Great Project!

**Comment by geoffreymcgill** [comment]
The [docs](https://github.com/bridgedotnet/Bridge/wiki/Attribute-Reference#reflectable) for the `[Reflectable]` attribute have been added.

**Comment by geoffreymcgill** [comment]
As of Bridge v16, Reflection is now supported by default. Adding the `[Reflectable]` attributes are not required.

https://github.com/bridgedotnet/Bridge/wiki/Upgrading-to-Bridge-v16#reflection-supported-by-default

https://github.com/bridgedotnet/Bridge/wiki/Attribute-Reference#reflectable

Hope this helps.
