### ISSUE TITLE
Bundled CSS files contain byte-order-marks within the combined output file

### ISSUE THREAD

**Issue by Porl91** [bridgedotnet/Bridge#2429]
For a component I'm making I have 2 CSS files, and I've configured the bridge.json file for my project to the following:

```json
{
    "combineScripts": true,
    "resources": [
        {
           "name": "Combined.css",
            "output": "CSS",
            "files": [ "Content/Styles/Style1.css", "Content/Styles/Style2.css" ]
         }
    ]
}
```

This ostensibly does what's expected and the combined input of Style1.css and Style2.css end up top-and-tail in the Combine.css file, although when attempting to link to Combined.css in the browser there appeared to be a syntax error in the CSS file that was causing the parsing to terminate half way into the file. The reason was because Style2.css was saved as a UTF-8 with a byte-order-mark signature and this wasn't removed when concatenating the files together. When viewing this file in the VS binary editor I can see that the file is prefixed with the bytes 'EF BB BF', which seem to be causing the problem.

For the time being I can just work around this by saving the second file without the signature although this appears to be a bug.

### See Also
#1680 Resource embedding config options
[UTF BOM FAQ](http://www.unicode.org/faq/utf_bom.html#bom1)

**Comment by LeonidVeriga** [comment]
Thanks for reporting. We will try to fix it in next release.
