### ISSUE TITLE
JS array passed across frames isn't recognised as an array by Bridge

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#2456]
I can't figure out how to repro this on Deck because it uses an iframe but hopefully I can describe it well enough to explain!

I've written a test framework that spawns browsers, executes tests and collects the results. The way it works is that the browser opens an HTML page which connects a web socket back to the framework runner which allows sending commands (and test results) backwards and forwards. When it gets the instruction to run a test suite, it loads it into an iframe (to ensure the test owns its own document and to make easy teardown etc.).

The problem I'm seeing is that when the outer page passes a JS array into the inner frame, calling `.Contains` on it seems to always return false even when I can see the item in the array.

I stepped through in the debugger and believe the issue is that `.Contains` calls `isArray` which then does:

```js
return Bridge.arrayTypes.indexOf(c) >= 0 || c.$isArray;
```

Inside `arrayTypes` I can see an `Array` function but it's not the same one as the constructor of my array. It seems like an array created in another window has a reference to a different `Array` constructor function and this check fails.

![Array debug](https://cloud.githubusercontent.com/assets/1078012/23852734/29ac52ec-07e1-11e7-9ec9-9b7555d11963.jpg)

I don't know if this is simple (or makes sense) to fix. For now I'm just going to pass it in as JSON and parse it out inside the iframe. If it's not your intention to support calling functions across frames like this it's not a huge problem, I can tweak how this works.

**Comment by DanTup** [comment]
Note: Using `Array.isArray(obj)` returns true if that helps!

**Comment by geoffreymcgill** [comment]
A pull request has been submitted for this issue. After testing and any revisions, the pr will be merged into the **master** branch.

**Comment by LeonidVeriga** [comment]
A deck sample may look like:
https://deck.net/c7619dc03b361cf9fa7a4f418d964b9c
```cs
public class Program
{
    public static void Main()
    {
        var frame = new HTMLIFrameElement();
        Document.Body.AppendChild(frame);

        var xFrame = Window.Frames[Window.Frames.Length - 1];

        object xArray = Script.Get<object>(xFrame, "Array");
        var array = Script.Write<int[]>("new {0}(1,2,3)", xArray);

        Console.WriteLine("Array: " + string.Join(", ", array));

        var contains = array.Contains(3);

        Console.WriteLine("Check if array contains 3: " + contains);
    }
}
```

**Comment by LeonidVeriga** [comment]
@DanTup, thank for a great issue explanation!

**Comment by DanTup** [comment]
Great; thanks!
