### ISSUE TITLE
Add support for Exception.GetBaseException()

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#2458]
In C# there's a method called `GetBaseException` which walks down the `InnerExceptions` to the last one and returns that (returning self if there is no inner exception). This is really useful for getting the real cause of an exception without walking down the tree yourself.

It'd be handy if Bridge supported this too. The implementation is presumably something like:

```cs
public Exception GetBaseException() {
    var ex = this;
    while (ex.InnerException != null)
        ex = ex.InnerException;

    return ex;
}
```

Note:

**Comment by geoffreymcgill** [comment]
Hi @DanTup – Thanks for letting us know about this missing functionality. It shouldn't be a problem to implement.
