### ISSUE TITLE
Array out of bounds to throw IndexOutOfRangeException

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2466]
### Steps To Reproduce

https://deck.net/22d6ce63d0ec81fdbf264ee493c0589b

https://dotnetfiddle.net/WB0HTZ

```c#
public class Program
{
    public static void Main()
    {
        var arr = new int[5] { 0,1,2,3,4 };
        var x = arr[6];
        
        Console.WriteLine(x);
    }
}
```

### Expected Result

```js
System.IndexOutOfRangeException: Index was outside the bounds of the array.
```

### Actual Result

```js
undefined
```

## See Also

* https://forums.bridge.net/forum/community/help/3658-bound-checked-array-access

**Comment by vladsch** [comment]
Duplicates with #156

**Comment by geoffreymcgill** [comment]
Dang... I searched for other instances before creating this new issue. Not sure how I missed #156.
