### ISSUE TITLE
Math E and PI is readonly fields but should be const

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#2473]
In this [Deck](https://deck.net/12a0e8849e2878a8c47686bb3ae8987e), it does not compile (with `The expression being assigned to Program.E2 must be constant`) but natively it does.

```cs
public class Program
{
    public const double E2 = Math.E * 2;
}
```

**Comment by kcudnik** [comment]
variables can't start with numbers, change "2E" to "E2" but even then problem exists [netfiddle](https://dotnetfiddle.net/hDsTaO) [deck](https://deck.net/905cd22c69cc2a7f56626546cc76c1af)

**Comment by vladsch** [comment]
Yes, because `Math.E` is static field in Bridge (not const)
https://github.com/bridgedotnet/Bridge/blob/master/Bridge/System/Math.cs#L10

We will fix it
