### ISSUE TITLE
Runtime Convert c# to js 

### ISSUE THREAD

**Issue by Malanin** [bridgedotnet/Bridge#2479]
Please, explain me. How can I convert string with c# or file with c# code to javascript and how can I get a syntax tree from a string with c# code.
For example:
```
 string code = "int i =5";
string  jscode = BridgeConverter.Convert(code);
Console.WriteLine(jscode); //   output:  var i =5;
```

**Comment by geoffreymcgill** [comment]
Hello @Malanin – We would prefer general help questions be posted in the [Bridge Forums](https://forums.bridge.net), as our GItHub Issues are used primarily to track **Defects** and **Feature Requests**. Can you re-post your question in the forum?
