### ISSUE TITLE
[External], [Namespace] and [Name] do not work together

### ISSUE THREAD

**Issue by preli** [bridgedotnet/Bridge#2480]
When using  [External], [Namespace] and [Name] together on a class the namespace is simply omitted in the compiled JavaScript code when calling a function from that class.

### Steps To Reproduce

https://deck.net/299c0d04622c3826267127d309ae0cbe

**Comment by LeonidVeriga** [comment]
@preli, welcome to **Bridge.NET**!

**[Name]** attribute has a priority over **[Namespace]**, this is as designed.

You can add namespace part right into **[Name]**:
```cs
[External]
[Name("my.classname")]
public static class DummyClass
{
    public static int getNumber()
    {
        return 3;
    }
}
```
