### ISSUE TITLE
Add missing attributes

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#2488]
When trying to port code from Native C#, you sometimes encounter, a lot of attributes. Some of these attributes are just optimizations, debugger code or documentation. Sometimes, you have to remove these from the native c#. For example, [this file](https://raw.githubusercontent.com/MonoGame/MonoGame/develop/MonoGame.Framework/Color.cs) or [this file](https://referencesource.microsoft.com/#mscorlib/system/io/stream.cs,f956b0c07e86df64).
There are lots of attributes:
```csharp
[DataContract]
[DebuggerDisplay("{DebugDisplayString,nq}")]
[CLSCompliant(false)]
[DataMember]
[Serializable]
[ComVisible(true)]
[ContractClass(typeof(StreamContract))]
[NonSerialized]
[Pure]
[HostProtection(ExternalThreading = true)]
```

## See Also

* #2600 
* #1455
* #135

**Comment by michaelcheers** [comment]
Related to #135.

**Comment by LeonidVeriga** [comment]
Basic support added (marked with **NonScriptableAttribute**) - allows compilation of C# code using these new attributes but does not add new functionality like accessing them via reflection.
