### ISSUE TITLE
Support to JavaScript simple alert(), confirm(), prompt()

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#25]
I could find `Console.Log()` with intellisense but couldn't guess how to call javascript's:
- `alert()`
- `prompt()`
- `confirm()`

I did not try anything else. Maybe I am doind a very basic error here as well. :)

So, this issue might be me.

**Comment by geoffreymcgill** [comment]
This syntax request is not possible in C#.
