### ISSUE TITLE
Allow option for Single-Quoted Strings in Output

### ISSUE THREAD

**Issue by artfuldev** [bridgedotnet/Bridge#250]
It is a matter of personal preference. I would love it if there was some option to change the default quoting of strings to single instead of double.

**Comment by fabriciomurta** [comment]
Thanks for sharing your thoughts, we'll take it into consideration, of course. At first, we didn't worry about single quoting because of C# conventions -- for C#, single quoting always encloses a char, while double-quoting, an actual string.

**Comment by geoffreymcgill** [comment]
I'm siding with Crockford on this one; double-quotes only for strings. 

https://youtu.be/NPB34lDZj3E?t=613

**Comment by geoffreymcgill** [comment]
Closing this issue, see https://github.com/bridgedotnet/Bridge/pull/2791#issuecomment-312969248 for reason.
