### ISSUE TITLE
StringBuilder.Chars Property (Int32)

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2508]
Gets or sets the character at the specified character position in this instance.

### Steps To Reproduce

https://deck.net/ae0ed0c5c5b7814421ecf68080d478d5

```c#
public class Program
{
	public static void Main()
	{
		var sb = new StringBuilder();
		
		sb.Append("Hello World");
		
		char c1 = sb[6];
        
		// W		
		Console.WriteLine(c1);
	}
}
```

### Expected Result

```js
6
```

### Actual Result

```js
Argument 1: Cannot convert from 'string' to 'int'
```

## See Also

* #1615 
* #2902

**Comment by michaelcheers** [comment]
@geoffreymcgill, @vladsch, is it appropriate to create a pull request for this because the changes do not work due to #2862, [here](https://github.com/michaelcheers/Bridge/tree/Issue2508) is the branch anyway.
