### ISSUE TITLE
Make Minification Optional

### ISSUE THREAD

**Issue by kenshinthebattosai** [bridgedotnet/Bridge#251]
Because I'm bundling and minifying with MVC, I would not require the minified files. Even if I write a deploy.bat that deletes all *.min.js files in the output directory, bridge.min.js does not get deleted.

**Comment by fabriciomurta** [comment]
Alright, there's really something that I was expecting to be happenning sooner or later. We'll get this functionality working. It will probably be an 'bridge.json' option, something like `outputVersions: minified|beautified|both`

**Comment by fabriciomurta** [comment]
Right, now we will have a `javaScriptOutputType` option to **bridge.json** that could have one of three different values:
- `both`: Will build both minified and beautified versions
- `minified`: only .min.js will be output
- `beautified`: only .js will be output.

This option is project-wide and affects the builder's translator, i.e. the option is used for any output of the related project and only when bridge's builder (Builder.dll or Builder.exe) is called.

**Comment by fabriciomurta** [comment]
Update: @geoffreymcgill wanted a better naming and we come up with this:

Right, now we will have a `outputFormatting` option to **bridge.json** that could have one of three different values:
- `both`: Will build both minified and beautified versions
- `minified`: only .min.js will be output
- `formatted`: only .js will be output.
This was the change of the commit above.
