### ISSUE TITLE
Bridge package and bridge.json Output option configuration

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#2517]
### bridge.json
Default value of **output** option is changed:
- Old - `"bridge/output"`;
- Revised - `"$(OutDir)/bridge/"` (for example, project's `"bin/Debug/bridge/"` folder).

### Bridge package
**bridge.json** is added to project root, instead of **/Bridge/bridge.json**.

The **bridge.json** configuration is not required. By default all output files will be in emitted to `"$(OutDir)/bridge/"`.

The old **Bridge** nuget package's folders **Bridge/output** and **Bridge/www** are not required anymore.

Previous **bridge.json** location (inside **/Bridge/** folder) and settings continue to work as before.

**Comment by geoffreymcgill** [comment]
This should make @DanTup happy.

**Comment by DanTup** [comment]
Woo, all of these make me happy indeed! My colleagues too; only this week I was asked twice about those files coming back!

Does this mean there's no difference between using Bridge vs Bridge.Min anymore?

**Comment by LeonidVeriga** [comment]
Well, we plan to include **bridge.json** in **Bridge** package (**Bridge.Min** does not have any additional files).

**Comment by geoffreymcgill** [comment]
@DanTup – Can you live with a **bridge.json** being added to the project root during the Bridge NuGet package install?

**Comment by DanTup** [comment]
Yeah, definitely! I forgot that file wasn't in Bridge.Min when I asked the question. This all sounds great to me :-)
