### ISSUE TITLE
Two JavaScript files are generated in Folder (Lib) mode

### ISSUE THREAD

**Issue by kcudnik** [bridgedotnet/Bridge#2519]
Two java script files are generated in Bridge/ourput using origin/master branch.
Problem appears when [Namespace(false)] is added

### Steps To Reproduce

https://deck.net/a9393901ad4e01678409a79707c54c93

```c#
[Namespace(false)]
public class MainClass
{
    [Ready]
    public static void Main()
        {
        }
}
```

### Expected Result

```js
Good question, what should be expected result. Probably only one file should be generated.
```

### Actual Result

```js
2 files are generated, one with project directory name and second with csproj name
```

**Comment by geoffreymcgill** [comment]
Thanks for the report. We will investigate and try to reproduce locally.

By the way, use of `[Ready]` is no longer required. By default, the `public static void Main()` will be automatically called as the entry point into your application.

**Comment by LeonidVeriga** [comment]
@kcudnik, can you specify your **bridge.json** please.

**Comment by kcudnik** [comment]
Yes, both generated files have the same timestamp but content is different
i have project located in ~/Test/G/Test.csproj
output files are G.js and Test.js and their minified versions, 
commit im using from master is 10234f6

im attaching entire project
[G.tar.gz](https://github.com/bridgedotnet/Bridge/files/887300/G.tar.gz)

**Comment by LeonidVeriga** [comment]
Thanks for the test project, @kcudnik! The problem is related to the */lib* option in command-line mode. PR #2531 is submitted to fix the problem. Checking it out before merging to **master** branch is greatly appreciated.
