### ISSUE TITLE
Implement Type.IsPrimitive

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#2522]

**Comment by TriEdgeAI** [comment]
Any ETA on this?

**Comment by fabriciomurta** [comment]
Hello @TriEdgeAI!

We've been focusing in fixing bugs and didn't have an opportunity to take on this feature yet, but thanks for the heads up! Unfortunately I can't give you an estimate right now on when we will be able to have it done.

**Comment by fabriciomurta** [comment]
Fixed and merged upstream! The fix will be available next Bridge release (see attached milestone).
