### ISSUE TITLE
Unexpected results of ToLocalTime() / ToUniversalTime()

### ISSUE THREAD

**Issue by danieldegtyarev** [bridgedotnet/Bridge#2524]
The main issue is described below. I would propose:
- [x] Add a constructor with the last parameter `DateTimeKind`. See #2543
- [x] Add property `Kind`. See #2543
- [x] Fix `ToLocalTime()`
- [x] Fix `ToUniversalTime()`

### Steps To Reproduce

https://deck.net/6c14e77cba4c5754b92fcfe9204fe9f3

```c#
public class Program
{
    public static void Main()
    {
        var date = new DateTime(2000, 5, 4, 3, 2, 1 /*  */);
        
        Console.WriteLine(date); // OK Thu May 04 2000 03:02:01
        
        date = date.ToUniversalTime();
        Console.WriteLine(date); // OK Thu May 04 2000 01:02:01 GMT+0200
        
        date = date.ToUniversalTime();
        Console.WriteLine(date); // WRONG: Wed May 03 2000 23:02:01 GMT+0200
                                 // It is already UTC (!)
    }
}
```

### Expected Result

Each second invocation of ToLocalTime() / ToUniversalTime() should not affect DataTime object.

## See Also

* DateTime.ToUniversalTime does not correctly set timezone #2929

**Comment by geoffreymcgill** [comment]
Here's another test case demonstrating how to reproduce:

https://deck.net/c851b72550394e57e342037011ed1d91

https://dotnetfiddle.net/wUIEeK

```csharp
using System;

public class Program
{

    public static void Main()
    {
        var d0 = new DateTime(636318720000000000L);
        Console.WriteLine(d0);
        
        var d1 = new DateTime(636318720000000000L).ToLocalTime();
        Console.WriteLine(d1);
        
        var d2 = new DateTime(636318720000000000L).ToUniversalTime();
        Console.WriteLine(d2);
        
      	Console.WriteLine(d1.Subtract(d2).TotalHours.ToString());
	}
}
```

**Comment by michaelcheers** [comment]
@geoffreymcgill, I think the best solution to these kinds of bugs is to compile microsoft referencesource for DateTime.cs
