### ISSUE TITLE
new T() inside generic class does not work for HtmlElement

### ISSUE THREAD

**Issue by Algorithman** [bridgedotnet/Bridge#2526]
It seems 'new `T()` is not working in generic classes.

### Steps To Reproduce

https://deck.net/99912d1863e760fd50d707b525f5672e

```c#
public class Program
{
    public static void Main()
    {
        Test1<HTMLDivElement> dd = new Test1<HTMLDivElement>();
    }
}

public class Test1<T> where T :  HTMLElement, new()
{
    public HTMLElement testInstance { get; set; }

    public Test1()
    {
        testInstance = new T();
    }
}

```

It also does not work if i use:
```
    public T testInstance { get;set; }
```
The same error.

### Expected Result

No TypeError

### Actual Result
```js
TypeError: Illegal constructor.
bt.createInstance https://deck.net/resources/js/bridge/bridge.min.js:8:2605
```

**Comment by LeonidVeriga** [comment]
Hi @Algorithman, welcome to Bridge.NET!

Yes, there is a problem if an **HTML** element is created through a "constructor". For instance, the following JavaScript sample fails with the same error **TypeError: Illegal constructor**:

https://jsfiddle.net/pbjbzp3p/4/
```js
var d = new HTMLDivElement();
```

Your sample with instanciating **.Net** instances inside a generic class works:
https://deck.net/c36aea80909c583ad8a2066622298bd9
```js
public class Program
{
    public static void Main()
    {
        var dd = new Test1<NotHTMLClass>();
    }

}

public class NotHTMLClass
{

}

public class Test1<T> where T :  NotHTMLClass, new()
{
    public NotHTMLClass testInstance {get;set;}

    public Test1()
    {
        testInstance = new T();
    }
}
```

We will discuss this issue with HTML constructors on our Bridge.NET team weekly meeting.

**Comment by Algorithman** [comment]
Found another thing: 
I tried it with a public static HTMLDivElement and it worked as it should.

https://deck.net/923170a25be3133434447a208adcf2a4

Maybe that helps :)
Trying with a static List<HTMLElement> next :)

**Comment by LeonidVeriga** [comment]
Well, it is a bit different thing.

When you explicitly use contructor in C# like `test2 = new HTMLDivElement();` Bridge.NET knows instance type and how to emit a correct JavaScript code to create element - `test2 = document.createElement('div');`

When instantiating is going through `new T();` then there is now info about the exact type at compile time and Bridge.NET emits instantiating code according to common .Net rules which does not work for HTML elements as they have the "illegal" constructors in JavaScript world.

**Comment by Algorithman** [comment]
> does not work for HTML elements as they have the "illegal" constructors in JavaScript world.

As expected from javascript, lol
I think i can work around that, i just wanted to have generic stuff for sake of code clarity on my side.

Thx for the explanation tho

**Comment by LeonidVeriga** [comment]
Okay!

Yes, the constructor stuff can be workarounded by C# means like:
https://deck.net/550847ca8f8d3066ab13baef4fe8bdb0
```cs
public class Program
{
    public static void Main()
    {
        var dd = Test1.Create(new HTMLDivElement());
    }
}

public class Test1<T> where T :  HTMLElement, new()
{
    public HTMLElement testInstance {get;set;}

    public Test1(T instance)
    {
        testInstance = instance;
    }
}

public class Test1
{
    public static Test1<T> Create<T>(T instance) where T :  HTMLElement, new()
    {
        return new Test1<T>(instance);
    }    
}
```

**Comment by Algorithman** [comment]
You sir, get the 🥇 !

I would've used an approach with interfaces, but this is much more the solution i like :)

Have a nice weekend

**Comment by LeonidVeriga** [comment]
Hi, @Algorithman,

Here is another example of how an **HTMLElement** can be extended:
https://deck.net/afe164197f42ba2952e5c8d1a1cb9d20 - it uses a static extention to get/set a **Person** property in **HTMLElement**.

```cs
public class Program
{
    public static void Main()
    {
        var div = new HTMLDivElement();
        
        var p = new Person()
        {
            Id = 1,
            Name = "Sally"
        };
        
        div.SetPerson(p);
        
        var divPerson = div.GetPerson();
        
        Console.WriteLine(divPerson);
    }
}

public class Person
{
    public int Id { get; set; }
    public string Name { get; set; }
    
    public override string ToString()
    {
        return Id + ": " + Name;
    }
}


public static class DivExtentions
{
    public static Person GetPerson(this HTMLElement div)
    {
        Person p = null;
        
        if (div != null)
        {
            p = div["Person"].As<Person>();
        }
        
        return p;
    }
    
    public static void SetPerson(this HTMLElement div, Person p)
    {
        if (div != null)
        {
            div["Person"] = p;
        }
    }
}
```
