### ISSUE TITLE
Bring back FieldProperty

### ISSUE THREAD

**Issue by kcudnik** [bridgedotnet/Bridge#2529]
Please bring back FieldProperty attribute or add option to ExternalInterface attribute
so access to properties can be from small letter since interfaces can't have fields

PS. tested against origin/master

### Steps To Reproduce
https://deck.net/7d076f293593e4a6c0d66b0d43626b04

```c#
namespace Test
{
    using Bridge;

    [External]
    [ExternalInterface]
    public interface IA
    {
        // i want acces to property via small letter p
        // and not using "name" attribute for each one
        // [FieldProperty] // removed since v16.0
        int Property { get; set; }

        void Method();
    }

    // generated: 
    //
    //alias: [
    //    "Property", "Test$IA$Property",
    //    "method", "Test$IA$method"
    //]

    public class A : IA
    {
        
        public int Property { get; set;}

        public void Method() { }
    }

    public class MainClass
    {
        public static void Main()
        {
            var a = new A();

            a.Property = 1; // in js: a.Property = 1; // i want small "property"

            a.Method(); // in js: a.method(); // ok
        }
    }
}
```

### Expected Result

```js
a[Bridge.geti(map, "Test$IA$Property", "property")] = 1;
```

### Actual Result

```js
a[Bridge.geti(map, "Test$IA$Property", "Property")] = 1;
```

**Comment by geoffreymcgill** [comment]
The new `[Convention]` attribute will take care of this scenario. See Issue #2477.

Bridge will not be re-casing any Members (Properties, Fields, Methods) as of Bridge 16. In your sample the `Method` method will also be emitted as `a.Method();` in the JavaScript. You will be able to use `[Convention]` to change that behaviour.

**Comment by vladsch** [comment]
Also, you can set Name attribute with 'true' argument

**Comment by kcudnik** [comment]
Thanks for explenation!

**Comment by geoffreymcgill** [comment]
The `[Name(true)]` option has been removed as of Bridge 16.0. See issue #2575.

Please use new `[Convention(Notation.LowerCamelCase)]` attribute introduced in issue #2477.
