### ISSUE TITLE
WebSocket.SendAsync ignores offset of byte array

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2537]
## See Also

* https://forums.bridge.net/forum/bridge-net-pro/bugs/3900-websocket-sendasync-not-implemented-correctly
* https://forums.bridge.net/forum/bridge-net-pro/bugs/3917-open-2537-clientwebsocket-sendasync-uint8array-should-be-used-instead-of-int8array

**Comment by geoffreymcgill** [comment]
Hi @Dia6lo – Can you take a look at this issue and proposed fix from @DierkDroth in Pull Request #2533.

https://github.com/bridgedotnet/Bridge/blob/7fc1ed274d44d017c453b0b33f7ff57fc8779f73/Bridge/Resources/ClientWebSocket.js#L95-L131

**Comment by Dia6lo** [comment]
I've played around with .NETs ClientWebSocket and yes, there is definetly a problem with offsets in Bridge's SendAsync. More than that, ReceiveAsync uses ArraySegment as well, so it has pretty much the same problem as with offset and count. @geoffreymcgill, please create new issue about it or change this one, I'll propose a fix shortly.
Also, big thanks to @DierkDroth for uncovering such class of problems 👍

**Comment by geoffreymcgill** [comment]
Once the fix gets closer to being fully resolved, we'll set the milestone. 

The goal is to fix asap and include the fix into the **master* branch before the Bridge 16.0 release.

**Comment by DierkDroth** [comment]
Understand, thanks
