### ISSUE TITLE
Inherits abstract base class with [Name] property override

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2539]
### Steps To Reproduce

https://deck.net/26ef469b11141f3f53bc37604c71dbf9

```c#
public class Program
{
    public static void Main()
    {
        var m = new Model { Name = "Hello" };

        // HelloHello
        Console.WriteLine(m.Test());
    }
}

public abstract class Base
{
   protected internal abstract string Name { get; set; }

   public string Test()
   {
        return this.Name + this.Name;
   }
}

public class Model : Base
{
    [Name("name")]
    protected internal override string Name { get; set; }
}
```

## See Also

* https://forums.bridge.net/forum/bridge-net-pro/bugs/3889-is-compiling-of-abstract-member-buggy

**Comment by vladsch** [comment]
Unfortunately, it cannot be fixed. Name attribute is used by Bridge compiler only (no runtime resolving). But the compiler doesn't have information about any possible subclass with overrides inside Test method.

**Comment by geoffreymcgill** [comment]
Our position is that you are purposely violating the contract between the base class and implementation class. Under those conditions, we cannot tell if you're doing this on purpose or not. It might be a deliberate action on the part of the developer.

The Attributes enable great flexibility to customize the JavaScript generated by Bridge, but those overrides might cause unintended consequences in your application runtime code.

There was a suggestion earlier by @vladsch to throw an Exception if this scenario was encountered. We have discussed the proposal, but we're concerned this would just trigger other intended consequences.

As a general rule, if you're manually (explicitly) overriding entity names, then it's up to the developer to manage.

For now, we cannot provide a solution.
