### ISSUE TITLE
Move Bridge.Html5 project into Frameworks repo

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2540]
Move [Bridge.Html5](https://github.com/bridgedotnet/Bridge/tree/master/Html5) project from [Bridge](https://github.com/bridgedotnet/Bridge/tree/master/) repo in [Frameworks](https://github.com/bridgedotnet/Frameworks) repo.

- [x] Move Html5 to Frameworks

**Comment by michaelcheers** [comment]
This could prevent name overlaps with classes you create and ones from Bridge.

**Comment by geoffreymcgill** [comment]
Done. The change will be published with Bridge 17.0.
