### ISSUE TITLE
CanvasTypes.CanvasCompositeOperationType.DestinationAtop missing dash

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#2546]
```c#
CanvasTypes.CanvasCompositeOperationType.DestinationAtop
```

### Expected Result

```js
"destination-atop"
```

### Actual Result

```js
"destinationatop"
```

It does not work without the dash.

**Comment by geoffreymcgill** [comment]
Looks like several properties were not correctly configured with a `[Name]`.

```
SourceIn > source-in
SourceOut > source-out
DestinationOver > destination-over
DestinationIn > destination-in
DestinationOut > destination-out
DestinationAtop > destination-atop
```

**Comment by geoffreymcgill** [comment]
A pull request has been submitted with these corrections. This fix will be included in the next release of Bridge. 

@TriEdgeAI – Thanks again for reporting the problem.
