### ISSUE TITLE
Implement string[] Environment.GetCommandLineArgs()

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#2553]
Maybe return an empty array just for the sake of easier cross-compiling? Or maybe return an array with GET arguments?

## See Also

- #2224

**Comment by LeonidVeriga** [comment]
@TriEdgeAI, we submitted PR #2572 to support **Environment** class. That would be great if you could have a look at the changes proposed. Your feedback is appreciated.
