### ISSUE TITLE
Console.WriteLine stringifies objects before calling console.debug on it

### ISSUE THREAD

**Issue by Porl91** [bridgedotnet/Bridge#2556]
When calling **Console.WriteLine** on an object, `[object Object]` is printed to both the Bridge console and also the console in the browser Developer Tools.

### Steps To Reproduce

https://deck.net/53772df15304f41c400a1160ab57f97c

```csharp
public class Program
{
    public static void Main()
    {
        Console.WriteLine(new Test());
    }
}

class Test { }
```

### Expected Result

An expandable and inspect-able object in the Google Chrome developer tools.

### Actual Result

`[object Object]` is printed to the console (both in Developer Tools & the Bridge console panel).

I stuck a breakpoint on the 'logBase' method to see how it decided how to print the object to the console and I've attached it below:

![te12](https://cloud.githubusercontent.com/assets/13272784/24866323/b313ecd0-1e01-11e7-9159-6510270f0f66.jpg)

You can see that `messageType` is undefined so it becomes `0`. `value` is an object so it should be run through **console.debug** rather than console.log. On the fourth line of the method you can see that regardless of whether it's an object or a primitive value it always calls toString on it, meaning the value of the object that I'm passing in becomes `[object Object]`.

**Comment by geoffreymcgill** [comment]
Fixed in #1994.
