### ISSUE TITLE
"Value cannot be null. Parameter name: element" when reflecting attributes

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#2558]
The following code works fine on dotnetfiddle but throws in Bridge/Deck.net:

https://dotnetfiddle.net/YYkcrU

https://deck.net/0dfa5632c667489768865c1b6633ca71

```cs
using System;
using System.Linq;

public class Program
{
	public static void Main()
	{
		var a = Status.Item1.GetAttribute<DisplayAttribute>();
	}

	public enum Status
	{
		[Display]
		Item1
	}

	class DisplayAttribute : Attribute
	{
	}
}

public static class EnumExtensions
{
	public static T GetAttribute<T>(this Enum value)
	where T : Attribute
	{
		return value
		.GetType()
		.GetField(value.ToString())
		.GetCustomAttributes(typeof(T), false)
		.FirstOrDefault()
		as T;
	}
}
```

The error is:

> bridge.min.js?15.7.0.1:8 Uncaught 
ctor {message: "Value cannot be null.↵Parameter name: element", innerException: null, errorStack: Error at ctor (https://deck.net/resources/js/bridge/bridge.min.js?15.7.0.1:8:63274) at ctor …, data: ctor, $initialized: function…}

I've tried adding `[Reflectable]` to both the enum and the attribute, but that doesn't seem to make any difference.

Is this a bug or do I need to do something differently?

## See Also

* #2622

**Comment by vladsch** [comment]
The same issue
https://github.com/bridgedotnet/Bridge/issues/2622
