### ISSUE TITLE
Clean up object general functions.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#2562]
Sometimes, having so many built in functions on object is annoying, especially when you don't normally use many of them. I propose that there be built a new class called

- BridgeObject

- JavascriptObject
or something like that with IgnoreCast and move all the bridge specific functions to that because the auto-complete list is long. The only one of those methods that I use usually is As<T>.

**Comment by geoffreymcgill** [comment]
You have good timing. We've been discussing and planning this change for weeks. 

Please see Issue #2564. 

I'm going to close this issue and the discussion will continue in #2564.
