### ISSUE TITLE
IE8 support

### ISSUE THREAD

**Issue by kenshinthebattosai** [bridgedotnet/Bridge#257]
Don't know if IE8 compatibility is supposed to exist, but `bridge.js` doesn't work with IE8. `Object doesn't support property or method 'create'` is the error, denoting the absence of ES5 method `Object.create`. A few lines somewhere about browser support would be helpful, in case I did not just miss seeing it. Would [ES5-shim](https://github.com/es-shims/es5-shim) do it?

**Comment by kenshinthebattosai** [comment]
Perhaps because HTML5 is explicitly stated, I'm asking the wrong question?

**Comment by kenshinthebattosai** [comment]
Reporting that [bridgedotnet](https://github.com/bridgedotnet/Bridge) works in IE8 with the following polyfills: [html5shiv](https://github.com/aFarkas/html5shiv/blob/master/dist/html5shiv.js) (for HTML5 support in IE8), [es5-shim](https://github.com/es-shims/es5-shim/blob/master/es5-shim.js) and [es5-sham](https://github.com/es-shims/es5-shim/blob/master/es5-sham.js) included in that order in the HEAD section of the document.

**Comment by kenshinthebattosai** [comment]
We should include that in the documentation. Maybe someone will find it helpful, though IE8 is legacy.

**Comment by fabriciomurta** [comment]
Thank you very much for the feedback, @kenshinthebattosai.

We didn't really mention IE8 as not supported as we required HTML5 and not all of this is supported on IE8. But really, your directions on overcoming the issue are appreciated.

In the other hand though, other features we have do not as well support IE8. [jQuery2 for example, dropped -- at least at a point -- support for the browser](http://blog.jquery.com/2013/04/18/jquery-2-0-released/). Although there might be workarounds, fixes and patches, the trend now is to get it harder and harder to support without compromising the support of new features.

**Comment by kenshinthebattosai** [comment]
In most `for(var in obj)` loops, `hasOwnProperty` check has to be done.
In the loop in line number 1465,
IE8 does not include 'constructor' in the enumerated properties for the loop,
so an additional check such as 

```javascript
            // IE8 Fix
            if (window.isIE8) {
                if (prop.constructor) {
                    prototype['$constructor'] = prop.constructor;
                    ctorCounter++;
                }
            }

should be added

Just adding comments here if people would find it useful

**Comment by fabriciomurta** [comment]
Hello @kenshinthebattosai!

I'm taking this time to thank you for sharing your solution, this is invaluable for other users which come across the same issue you're encountering and this will be very useful. We'll remember this when someone else raises a question about IE8 support and workarounds.

Thank you very much!

**Comment by geoffreymcgill** [comment]
Your feedback regarding #1050 is appreciated.

IE8 support might be dropped in the next release, milestone 1.12.
