### ISSUE TITLE
using() does not work if your Dispose method is not named "dispose"

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#2579]
`using()` always generates code that attempts to invoke `dispose()` even if your method is not called that way. It could be `Dispose()` because of `[Convention]` or `preserveMemberCase: true` or it could be renamed to something completely diffferent with `[Name]`, but Bridge.NET will still be looking for `dispose()` in the transpiled JavaScript.

### Steps To Reproduce

https://deck.net/0426c98af9ea9f5bde19049e15c229ca

**Comment by geoffreymcgill** [comment]
Hi @TriEdgeAI – Thanks for pointing out this issue and for the excellent sample demonstrating how to reproduce. We will investigate.

Just a quick reminder, the `preserveMemberCase` setting has been removed in Bridge 16, see Issue #2476.

**Comment by vladsch** [comment]
In latest master, Bridge uses an alias to the interface method. So, problem is gone.
https://dev.deck.net/0426c98af9ea9f5bde19049e15c229ca
