### ISSUE TITLE
DateTime.MinValue.Date results in an "Invalid Date"

### ISSUE THREAD

**Issue by dionrhys** [bridgedotnet/Bridge#2582]
Calling DateTime.MinValue.Date results in an "Invalid Date" in JS.

It seems that Bridge's DateTime.MinValue evaluates to "Tue Apr 20 -271821 01:00:00 GMT+0100 (GMT Standard Time)" on my system, whereas I would've expected this to replicate .NET's MinValue of "0001-01-01 00:00:00" instead.

I *think* the reason DateTime.MinValue.Date fails is because it tries to change "-271821-04-20 01:00:00 +01:00" into "-271821-04-20 00:00:00 +01:00" and that fails. (Possibly on a system with a negative timezone would cause DateTime.MaxValue.Date to fail in a similar way)

The results using dev.deck.net are even more bizarre! (I've had a look at #1606 and it doesn't seem to have fixed this particular issue)

### Steps To Reproduce

Release: https://deck.net/eb6f5a3c78694d6c85a911cbc089d92d
Dev: https://dev.deck.net/174b051b0671a29ecb241782e5c2b338

```c#
public class Program
{
    public static void Main()
    {
        Console.WriteLine(DateTime.MaxValue);
        Console.WriteLine(DateTime.MaxValue.Date);
        
        Console.WriteLine(DateTime.MinValue);
        Console.WriteLine(DateTime.MinValue.Date);
    }
}
```

### Expected Result

```
9999-12-31T23:59:59.999Z
9999-12-31T00:00:00.000Z
0001-01-01T00:00:00.000Z
0001-01-01T00:00:00.000Z
```

### Actual Result

**deck.net**
```
Sat Sep 13 275760 01:00:00 GMT+0100 (GMT Standard Time)
Sat Sep 13 275760 00:00:00 GMT+0100 (GMT Standard Time)
Tue Apr 20 -271821 01:00:00 GMT+0100 (GMT Standard Time)
Invalid Date
```

**dev.deck.net**
```
12/31/9999 19:59:59
12/31/9999 00:00:00
12/31/0 23:00:00
12/31/1900 00:00:00
```

**Comment by geoffreymcgill** [comment]
Hi @dionrhys – Thanks for notifying us of this defect.

Nothing is ever straightforward with the DateTime and Date classes.

We will investigate and try to fix right away; with some luck for the 16.0 milestone.

**Comment by geoffreymcgill** [comment]
Hi @dionrhys I think this might have been fixed in **16.0**. Your original Deck samples are now returning the correct results. 

Please confirm this is working as expected. If it is, we'll close this issue.

**Comment by dionrhys** [comment]
`DateTime.MinValue` and `DateTime.MaxValue` now appear to be correct.

However, it looks like it's possible to create `DateTime` that overflow these bounds, but I will note those down in #2980 instead.

**Comment by geoffreymcgill** [comment]
@dionrhys yes, bound checking has not be implemented. We should be able to get to #2980 soon.
