### ISSUE TITLE
Source Map support (debugging of C# sources)

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#259]
To enable Source Map use **sourceMap** option in **bridge.json** (the option is switched off by default):
```json
"sourceMap": false | true
```

## See Also
* http://forums.bridge.net/forum/general/feature-requests/158-source-maps-support
* https://forums.bridge.net/forum/community/help/584-debugging
* http://forums.bridge.net/forum/general/open-discussions/1714-bridge-net-v2-0-in-hiding?p=2830#post2830
* http://forums.bridge.net/forum/general/feature-requests/2517-c-debugging
* https://forums.bridge.net/forum/general/open-discussions/4248-debugging-javascript
* #22 Investigate port to Roslyn parser
* #931  Integrate Chrome debugging into Visual Studio
* #1308 Add option for visual studio debugging
* #2624 Display C# line numbers on stack traces

**Comment by LeonidVeriga** [comment]
#22

**Comment by geoffreymcgill** [comment]
Source Map support should be included in the Bridge 2.0 release, although might need to wait until 2.1.

**Comment by DaniilVeriga** [comment]
Here is a related issue (#931):
"Integrate Chrome debugging into Visual Studio"

**Comment by geoffreymcgill** [comment]
Related to #1308.

**Comment by LeonidVeriga** [comment]
One more request http://forums.bridge.net/forum/general/open-discussions/1714-bridge-net-v2-0-in-hiding?p=2830#post2830

**Comment by caesay** [comment]
+1
I don't really care about the integrated debugging, but emitting source maps for the purposes of navigating large bridge projects would be useful. I have quite a large library that is filled with anonymous methods and it can be quite hard to identify where it lives in javascript. Is there anything specific preventing this from working? I presume Cecil can provide maps from IL back to the original C# source file / line numbers etc.

**Comment by geoffreymcgill** [comment]
There are some changes to the Bridge compiler architecture that are required before source maps can be supported properly. These changes are being worked on right now, and we hope to include source map support in the Bridge 16.0 release.

**Comment by DanTup** [comment]
I've been working on some async code today (a test framework supporting Task-returning tests) and debugging the code is a bit of a nightmare because of the rewriting to support tasks:

![Async](https://cloud.githubusercontent.com/assets/1078012/23860881/2e9ba2a2-0800-11e7-9419-b45d8bd4c16b.jpg)

If source maps would make this easier (I don't know, I've never actually used them) then it definitely gets a big vote from me!

**Comment by rachkoud** [comment]
+1

**Comment by DanTup** [comment]
@geoffreymcgill Do you have any rough estimate on when this might be implemented? I'm working on a test framework and when you double-click a test in Visual Studio I can't jump to the correct file to edit the test currently. I don't want to rush, but if this is a long way off, it might make sense for me to try and workaround this in the meantime (such as trying to infer the filename from the fully qualified type). If this might come next month, I can wait, but if it's 6 months away it's probably worth me trying to come up with something.

**Comment by geoffreymcgill** [comment]
Hi @DanTup – This is one of our highest priority items, although we have to finish up Bridge 16.0 and 16.1 first. That's going to take us at least several months down the road.

The goal is still to include in Bridge 17.0. Unfortunately, we cannot provide a time frame. I'd say six months is a relatively realistic timeframe, although it depends on how smooth Bridge 16.0 and 16.1 go.

I wish we could speed up our progress, but we just don't have the resources required to allocate to Bridge that we wish we had.

**Comment by DanTup** [comment]
Thanks for the info! We understand how things are; it's useful having a rough idea of how far away things are to help us make decisions. It seems like it's probably worth me putting something basic in to try and infer the filename from the type to make it easier to work on.

**Comment by LeonidVeriga** [comment]
**Source Map** feature is implemented, merged into **master** branch and available at [dev.deck.net](https://dev.deck.net).
It will be released with **16.0.0-beta2** as well.

A short [introduction](https://cloud.githubusercontent.com/assets/11466613/26359500/51cb28e0-3fde-11e7-8db6-9490a192ef23.gif) on Source Map in Deck.

**Comment by DanTup** [comment]
@LeonidVeriga This looks great! :) So when do we get beta2? ;)

**Comment by LeonidVeriga** [comment]
@DanTup, no firm date but good chances for this week.

**Comment by geoffreymcgill** [comment]
The **-beta2** release is scheduled for June 5th. There are a few more features we need to get into this release. Unfortunately, we cannot release any sooner. Lots of good stuff coming.

https://dev.deck.net will be updated with the latest **master** branch on May 30th.

**Comment by michaelcheers** [comment]
@DanTup, it might not work very well for async code, see #2812.

**Comment by DanTup** [comment]
@michaelcheers Thanks for the info. I haven't had chance to look at it yet; though my desire was more about fixing up stack traces and making it so you can double-click a test in VS Test Explorer and jump to the correct code, which I don't think should be affected by this.
