### ISSUE TITLE
Wrong stacktraces in exceptions

### ISSUE THREAD

**Issue by danieldegtyarev** [bridgedotnet/Bridge#2592]
Wrong stacktraces in exceptions, what makes debug more complicated.

### Steps To Reproduce

https://deck.net/57a054297fb1413cbdeffd5d9ab240a5

Expected: `MethodThowsException` in the callstack
Actual: No `MethodThowsException`  in the callstack

```
public class Program
{
    public static void MethodThowsException()
    {
    	string nulref = null; 
        
       	var ch = nulref.CharAt(1);
    }
           
    public static void Main()
    {
        try
        {
            MethodThowsException();
        }
        catch(Exception e)
        {
        	Console.WriteLine(e.StackTrace); 
        }        
    }
}
```

**Comment by geoffreymcgill** [comment]
Hi @danieldegtyarev – Thanks for the report. 

A pull request (#2595) has been submitted with a fix. After testing, the fix will be merged into the master branch.

**Comment by geoffreymcgill** [comment]
In addition to the Stack Trace enhancements, **Bridge Console** has been upgraded to catch uncaught Exceptions.

https://dev.deck.net/a736437e47c7c35f3fc76839aeebd3d4

```csharp
public class Program
{           
    public static void Main()
    {
        MethodThowsException();
    }
    
    public static void MethodThowsException()
    {
        throw new Exception("Exceptional!");
    }
}
```

**Comment by LeonidVeriga** [comment]
**enableNamedFunctionExpressions** option changed in PR #2674: new name is **namedFunctions**.
See more info at https://github.com/bridgedotnet/Bridge/wiki/Global-Configuration#namedfunctions.
