### ISSUE TITLE
Enable instantiation of BrowsableAttribute class

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2600]
BrowsableAttribute is marked as `[NonScriptable]`. This prevents instantiation of the class and use during Reflection operations.

### Steps To Reproduce

https://deck.net/0ffaf8dfb69f899a8de1961f8c4a04e9

```c#
public class App
{
    public static void Main()
    {
        Attribute.GetCustomAttributes(typeof(string).GetProperties()[0], typeof(System.ComponentModel.BrowsableAttribute), false);
    }
}
```

### Actual Result

```js
Type System.ComponentModel.BrowsableAttribute is marked as not usable from script
```

## See Also

* #2488

**Comment by DierkDroth** [comment]
@geoffreymcgill I see there is no milestone label assigned to this issue (although it was announced to be addressed with 16.0). Is this on purpose?

**Comment by geoffreymcgill** [comment]
> although it was announced to be addressed with 16.0

Can you link me to where that statement was made?

**Comment by DierkDroth** [comment]
https://forums.bridge.net/forum/bridge-net-pro/bugs/3635-closed-2459-16-0-browsableattribute-not-implemented-correctly
... was my initial report on the Browsable attribute which was addressed (unfortunately only in parts) for 16.0

**Comment by geoffreymcgill** [comment]
At this time, the Bridge dev team is focused on other functionality. The feature request has been logged and we will do our best to implement as soon as possible. 

There are several other (see #2488) native C# attributes that need to be implemented, so these will all likely get batched in the same job.

**Comment by DierkDroth** [comment]
Understand. 

Will #2600 make it into 16.0 or only in a later release? I needed to know since I needed to schedule my team's activities. Thx

**Comment by geoffreymcgill** [comment]
I will have to be a later release. Once we know, we will tag with a milestone.

**Comment by DierkDroth** [comment]
Thx for clarification

**Comment by LeonidVeriga** [comment]
@DierkDroth, the attribute implementation will not be included into **16.0**.
Let us know if there is still great needs in this attribute and we will try to include it into **16.1**

**Comment by DierkDroth** [comment]
Thanks for letting me know. 

Yes, I would need that feature. For now I do have some hack in place to keep me going, but ultimately I needed to see that implemented.

**Comment by DierkDroth** [comment]
@geoffreymcgill your project now is at a stage where I really needed proper support for BrowsableAttribute as discussed above. Reason: in our code base we're using reflection massively and filter properties (for various purposes) by the [Browsable(false)] attribute.

Not having support for that property pretty much would mean a dead end for us ...

Is there anything which could be done?

**Comment by DierkDroth** [comment]
Thx guys for making this happen ... :-)

**Comment by fabriciomurta** [comment]
The fix looks good. It has just been merged to the integration branch and will make it to the Bridge version pointed by the milestone associated to this issue (currently 16.5.1).
