### ISSUE TITLE
Unhelpful error when reflecting non-reflectable code

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#2603]
Deck: https://deck.net/df734ba7af166711e1c2136f1f90ea4f

The following code fails because the type is not marked with `[Reflectable]`:

```cs
var props = type.GetProperty("TestProperty", BindingFlags.Instance | BindingFlags.Static);
Console.WriteLine(props.CanRead);
```

The error is not very useful to help diagnose the problem:

> Cannot read property 'g' of null
> `Bridge.Console.log((!!props.g));`

**Comment by geoffreymcgill** [comment]
This JavaScript error message is a native JavaScript error, not something we're explicitly throwing in Bridge. 

This specific scenario is certainly something we could test for at runtime, although there's always a cost somewhere. For example, more JavaScript code would be required to check types and if a member exists, and a performance penalty by running more checks.

We could include logic in the compiler to attempt to determine when reflection is being performed on an object; then throw a compiler error if `[Reflectable]` is not applied, or even just emit the `metadata` automatically. But, this type of approach is not straightforward and would likely lead to scenarios where extra metadata bloat is being unnecessarily added to the app.js. There is a direct cost associated with this type of approach.

The compromise we have at the moment is that the `[Reflectable]` attribute is required, or more specifically the metadata is required, if you're performing Reflection. The metadata for the object will be emitted by Bridge if the attribute is applied.

To date, we haven't had a chance to implement another solution. I have some ideas, and with some luck, we'll be able to explore those ideas during the 17.0 cycle.

I've never been thrilled with the current approach of leaving the metadata decision up to a manual process. My goal is to automate and have the compiler handle.

Maybe there's an option to run checks in `Bridge.Reflection.getMembers`. We will investigate.

**Comment by DanTup** [comment]
> This specific scenario is certainly something we could test for at runtime, although there's always a cost somewhere. For example, more JavaScript code would be required to check types and if a member exists, and a performance penalty by running more checks.

I understand that, though personally I think a null check before trying to access the `.g` property to provide a useful error is a reasonable tradeoff. I've seen this error message on another two devs machines this week and if it wasn't for having already debugged this once, they'd probably have spent a while trying to understand what was going on.

> We could include logic in the compiler to attempt to determine when reflection is being performed on an object;
> ...
> My goal is to automate and have the compiler handle.

I'm not really sure this could ever be done reliably. For example, in the case the test framework (which is built and distributed in a NuGet) is reflecting over the test library (which was created later). I don't think you could reasonably link all this together at compile time to understand what's required.

I think the current solution is pretty reasonable, as long as if the user forgets to add `[Reflectable]` and then tries to reflect a type, the error message is decent.

**Comment by DanTup** [comment]
I think #2732 somewhat addresses this by including Reflection metadata by default.

**Comment by geoffreymcgill** [comment]
> I think #2732 somewhat addresses this by including Reflection metadata by default.

Agreed. I'm going to close this issue as the new default [reflection](https://github.com/bridgedotnet/Bridge/wiki/global-configuration#reflection) metadata functionality in Bridge 16 should avoid this issue.
