### ISSUE TITLE
XMLHttpRequest.ResponseType is readonly.

### ISSUE THREAD

**Issue by gsmit1996** [bridgedotnet/Bridge#261]
It is not possible to change the ResponseType in XMLHttpRequest since it's readonly.
I've searched on the internet if there is any other way to change the value, but wasn't able to find it.

See https://github.com/bridgedotnet/Bridge/blob/master/Html5/Ajax/XMLHttpRequest.cs#L38

**Comment by fabriciomurta** [comment]
Thank you very much for your report, @gsmit1996. We are already discussing about this behavior, and how/when this should be able to be changed, and we'll return to you soon with the result (and commit if any). This is just a heads up to let you know we are considering your request.

**Comment by fabriciomurta** [comment]
Sorry for the long long delay, our sincere apologies. We have just dropped the 'readonly' flag (as you can see in the referred commit). Next Bridge.NET version will contemplate this review in the code!

By the way, this information was confirmed in [Mozilla's documentation about XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest).
