### ISSUE TITLE
Use automatic catch expressions

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#2613]
Use a try catch around all code and write exceptions to the console for easier debugging of exceptions.
At the moment, sometimes exceptions are hard to read in the JS console and it would be easier to display them in the Bridge console as C# exceptions.

**Comment by geoffreymcgill** [comment]
Hi @michaelcheers – As of 16.0, Bridge Console will catch all JavaScript errors and Exceptions, then display with some client-side stack details.

Can you review the following Deck and let us know if this new error handling process will help with solving this feature request?

https://dev.deck.net/64ff010ee7aa54aa0e1990f63f17d205

```csharp
public class Program
{
    public static void Main()
    {
        throw new Exception("Exceptional!");
    }
}
```

**Comment by DanTup** [comment]
I'm confused by this change - does this mean the browsers debugger will no longer break on exceptions because all exceptions care caught by bridge? If so, I think this is a terrible change. Being able to examine variables and walk up and down the stack in the javascript debugger is a critical part of debugging Bridge apps. Just having exception text will make things significantly harder to debug?

**Comment by geoffreymcgill** [comment]
The native error handling by the user-agent is not interrupted. Whatever happens naturally will continue to happen. You can confirm by testing with https://dev.deck.net.

**Comment by DanTup** [comment]
I tried it with the deck link above, but it doesn't break in the developer debugger (but I wasn't sure if that's because Deck behaves differently)?

**Comment by geoffreymcgill** [comment]
The term _catch_ is probably confusing. Bridge Console will be _notified_ of any errors or exceptions but does not modify the original event.

**Comment by DanTup** [comment]
Then that's probably not so bad :) It was the first line of the original issue here that concerned me - if you add a try/catch, the browser debugger would not break correctly. If you're just subscribing to error notifications, then that doesn't seem like it will interfere :-)

**Comment by geoffreymcgill** [comment]
> then that doesn't seem like it will interfere :-)

It doesn't

**Comment by DanTup** [comment]
Great, thanks for confirming!

**Comment by michaelcheers** [comment]
@geoffreymcgill, yes that satisfies my issue.
