### ISSUE TITLE
Passing enum to method causes it to perform a different type check

### ISSUE THREAD

**Issue by Porl91** [bridgedotnet/Bridge#2622]
When passing a reference to an enum to a method the output JS seems to ignore the value of the enum and just checks against the type. In the example below I pass the enum through with a reference of Enum and when passed as a parameter to Bridge.Reflection.isEnum it seems to return false.

### Steps To Reproduce

Issue reproduced in Deck:
https://deck.net/6d7188cebf7c8830d414a5e5aec805a6
```cs
public sealed class IdAttribute : Attribute
{
    public IdAttribute(string id)
    {
        Id = id;
    }

    public string Id { get; }
}

public enum LinkType
{
    [Id("URL")]
    Url = 0,

    [Id("EMAIL")]
    Email = 1,

   [Id("PRODUCT")]
   Product = 2,

   [Id("UNSUBSCRIBE")]
   Unsubscribe = 3
}

public class Program
{
    public static void Main()
    {
        Console.WriteLine(IsEnum(LinkType.Url));
        
        Console.WriteLine(LinkType.Url.GetType().IsEnum);
    }
    
    public static bool IsEnum(Enum e)
    {
        return e.GetType().IsEnum;
    }
}
```

### Expected Result
What it produces in C# https://dotnetfiddle.net/VQskcr:
True
True

### Actual Result

False
True

If you look at the JS it emits, within the 'IsEnum' method it seems to be ignores the enum parameter and just performs the check against it's type:

```js
Bridge.Reflection.isEnum(System.Enum);
```

**Comment by geoffreymcgill** [comment]
Hi @Porl91 – Thanks for the report and excellent sample demonstrating how to reproduce. We will investigate.

**Comment by vladsch** [comment]
Duplicates with https://github.com/bridgedotnet/Bridge/issues/2558
The PR for that issue is already created

**Comment by LeonidVeriga** [comment]
Unit test added.
