### ISSUE TITLE
For-loop variable is incorrectly captured (inside a closure) within an async method

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#2633]
### Expected Result

Should write **0**
https://dotnetfiddle.net/mTn5WO

### Actual Result
Writes **9**
https://deck.net/d874bd7e3e99314941b810333163c705

```csharp
public class Program
{
    public static async void Main()
    {
        Action[] array = new Action[10];

        for (int n = 0; n < 10; n++)
        {
            var a = new A{Value = n};
            array[n] = () => Console.WriteLine(a.Value);
        }

        array[0]();
    }
}

class A
{
    public int Value;
}
```

**Comment by geoffreymcgill** [comment]
Hi @michaelcheers – Thanks for the excellent sample demonstrating how to reproduce. We will investigate.

**Comment by Zaid-Ajaj** [comment]
How about you call it "For-loop variable is incorrectly captured (inside a closure) within an async method" because if you remove the async keyword, the code works.

 If the `for-loop` variable is accessed from an another scope "outside", it is captured correctly:
```csharp
public class Program
{
    public static async void Main()
    {
        Action[] array = new Action[10];
        for (int n = 0; n < 10; n++)
        {
            Do(n, x => array[n] = () => Console.WriteLine(x));
        } 
        array[0](); // writes 0, as expected
    }
    
    static void Do(int x, Action<int> f) => f(x);
}
```

**Comment by geoffreymcgill** [comment]
@Zaid-Ajaj – Done. Issue title has been updated.
