### ISSUE TITLE
Global.Location.Hash is read only. Should it be?

### ISSUE THREAD

**Issue by Mimisss** [bridgedotnet/Bridge#264]
Or should it be read/write?

**Comment by geoffreymcgill** [comment]
What does the Mozilla spec say?

**Comment by Mimisss** [comment]
> Though Window.location is a read-only Location object, you can also assign a DOMString to it. 

https://developer.mozilla.org/en-US/docs/Web/API/Window/location

**Comment by fabriciomurta** [comment]
As I read, there's kind of a syntax sugar in that, so anything changing the location (would be the same as changing location.href), should force a page reload to the new location so... I guess it really should be made an exception and allow assigning and being used like a string... The side effect would be treated browser-side.

**Comment by DaniilVeriga** [comment]
Well, according to the Mozilla docs all the Location's fields are not read only except `origin`.
https://developer.mozilla.org/en-US/docs/Web/API/Location

In Bridge.NET we currently have all fields read only except `href`. I think it is a defect and going to fix it.

**Comment by geoffreymcgill** [comment]
@DaniilVeriga  - It appears this issue was solved, and should have been closed. Can you investigate?

**Comment by DaniilVeriga** [comment]
@geoffreymcgill, you are right. The fix was included to 1.9.
