### ISSUE TITLE
Allow Json.Deserialize CamelCasing for Fields (ala Properties)

### ISSUE THREAD

**Issue by cojo** [bridgedotnet/Bridge#2641]
When we call `Json.Deserialize` I see that there is an option in JsonSettings for properties to be deserialized from the previous camelCasing style (lowercase for very first letter via `CamelCasePropertyNames`). However looking at the code I see that this is only checked for properties, and that fields are always deserialized under the assumption that they will use the exact casing of the class.

Our data that we deserialize has previously been direct-to-fields, and while we were able to convert all of those data classes to properties to get our codebase working in 16.0-beta, we see a performance hit from the property getter overhead (cfg.get) and it seems like it would be ideal to leave these as fields since are they pure data and the property overhead is unnecessary...

Is there a reason that we are only allowed to specify CamelCase for properties and not similarly for fields? Any chance of us getting that capability before 16.0 goes to final production build?

Thanks in advance!

### See Also

* #2418 Bridge.Json serialization and deserialization 
*  https://forums.bridge.net/forum/community/help/4128-bridge-16-0-question-json-deserialize-camelcasing-for-fields

**Comment by geoffreymcgill** [comment]
Hi @cojo,

Welcome to Bridge.NET!

Thanks for informing us of this issue. We'll do some investigation, but I'm going to consider this a defect. We will try to fix right away. 

You have perfect timing in reporting this issue as we're just about to do some other work related to **Bridge.Json**, so we'll batch it all together.

**Comment by cojo** [comment]
Awesome news, thanks guys!

**Comment by LeonidVeriga** [comment]
The existing **CamelCasePropertyNames** will also control field behavior:

https://deck.net/31297b03c5a69804cddc122354edf06d

```cs
public class Program
{
    public static void Main()
    {
        var c = new Data { Field1 = 1, field2 = 2 };
        
        // CamelCasePropertyNames option
 		var json = Bridge.Json.Serialize(
            c,
            new JsonSettings { CamelCasePropertyNames = true });
        
        Console.WriteLine(json);
        
        var deserialized = Bridge.Json.Deserialize<Data>(
            json,
            new JsonSettings { CamelCasePropertyNames = true });

        Console.WriteLine(deserialized);
        
        // With no CamelCasePropertyNames option
 		json = Bridge.Json.Serialize(
            c,
            new JsonSettings { CamelCasePropertyNames = true });
        
        Console.WriteLine(json);
        
        deserialized = Bridge.Json.Deserialize<Data>(
            json,
            new JsonSettings { CamelCasePropertyNames = true });

        Console.WriteLine(deserialized);
    }
}

[Reflectable]
public class Data
{
    public int Field1;
    public int field2;
}
```
