### ISSUE TITLE
TypeScript definition for interfaces has wrong method names

### ISSUE THREAD

**Issue by GeneralGDA** [bridgedotnet/Bridge#2643]
Bridge in the JS renames interface's methods adding prefixes to them. The prefix looks like this: `Namespace$TypeName$`. But the TS definition file contains plain method name without any prefix.

### Steps To Reproduce

https://deck.net/c6a08e4943da6c3bc3956e9c75509a6d

```c#
interface Zig
{
    void zag();
}

public class Program
{
    public static void Main()
    {
        void fun(Zig zag)
        {
            zag.zag();
        }

        class Zag : Zig
        {
            public void zag()
            {
                Console.WriteLine("yeah!");
            }
        }

        public static void Main()
        {
            new App().fun(new Zag());
        }
    }
}
```

### Expected Result

```js
export interface Zig {
        Zig$zag(): void;
    }
    var Zig: Function;
```

### Actual Result
```js
// in d.ts:
export interface Zig {
        zag(): void; // <== the name!
    }
    var Zig: Function;

// in .js:

Bridge.define("App", {
        $main: function () {
            new App().fun(new App.Zag());
        },
        fun: function (zag) {
            zag.Zig$zag(); // Look at this name!
        }
    });

    Bridge.define("Zig", {
        $kind: "interface"
    });

Bridge.define("App.Zag", {
        inherits: [Zig],
        config: {
            alias: [
            "zag", "Zig$zag" // <== this is not a "zag()"
            ]
        },
        zag: function () {
            Bridge.Console.log("yeah!");
        }
    });
```

**Comment by GeneralGDA** [comment]
If I implement the Zig interface in my TS code than Exception is raised at the call site.

**Comment by geoffreymcgill** [comment]
Hi @GeneralGDA,

Welcome to Bridge!

Thanks for informing us of this issue and for providing an excellent sample reproducing the problem. 

We will investigate and try to fix right away.

**Comment by vladsch** [comment]
If open TypeScript tab of your deck sample then I see
```
interface Zig {
    Zig$zag(): void;
    zag(): void;
}
```

**Comment by vladsch** [comment]
I will close the issue for now

**Comment by GeneralGDA** [comment]
Ok, attempt #2. Check out this Visual Studio solution: https://www.dropbox.com/s/3erz45t8i3fci94/proto.zip?dl=0 . I use Bridge.NET 15.7.0 NuGet package in it. I has 2 projects: 1) C# project, compied into JS and 2) TypeScript project. "2)" has a class implementing interface defined in the "1)". The class instance is passed into JS code, generated from 1) => runtime exception. To reproduce: open the solution, rebuild, view BridgeSandbox/Bridge/www/demo.html in a browser.
