### ISSUE TITLE
uint versions of Math.Max() and Math.Min() should return uint

### ISSUE THREAD

**Issue by stopiccot** [bridgedotnet/Bridge#2644]
uint versions of Math.Max() and Math.Min() should return uint. Following valid C# code fails to compile.
https://docs.microsoft.com/en-us/dotnet/api/system.math.max
https://docs.microsoft.com/en-us/dotnet/api/system.math.min

### Steps To Reproduce

https://deck.net/ad39683e0a55faa5633d844b9f081f33

```c#
public class Program
{
    public static void Main()
    {
        uint uint1 = 10;
        uint uint2 = 20;
        uint1 = Math.Max(uint1, uint2);
        Console.WriteLine(uint1);
    }
}
```
Tested on 16.0.0-beta

**Comment by LeonidVeriga** [comment]
We added Min/Max overloads for all integer types and float/double/decimal.

Its method signatures also changed to match **.Net**. 
For example, `int Min(params int[] values)` -> `int Min(int val1, int val2)`.

The changes merged into **master** branch and will be included into next **Bridge.NET** release.
