### ISSUE TITLE
Support compiling Bridge repo on Visual Studio Mac

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2646]
Might be an issue with the Build Order on Mac. 

The repo should build the same on Visual Studio Mac as it does on Visual Studio Windows, including all **.nupkg** files when compiling in **Release** mode.

**Comment by LeonidVeriga** [comment]
Included into v16.0.1

**Comment by geoffreymcgill** [comment]
I installed the recent [Visual Studio for Mac](https://visualstudio.microsoft.com/vs/mac/) release and was able to create a new **C# Library** project and add [Bridge.NET](https://www.nuget.org/packages/bridge) using **Project** > **Add NuGet Packages...**.

The Bridge NuGet Package was added and the project compiled perfectly. I was then able to open the generated **index.html** file in a browser and it ran correctly. 

<img width="910" alt="Screenshot 2019-04-13 16 19 39" src="https://user-images.githubusercontent.com/62210/56085836-f2097980-5e07-11e9-83b3-5cf19bc7443e.png">

<img width="398" alt="Screenshot 2019-04-13 16 22 55" src="https://user-images.githubusercontent.com/62210/56085860-68a67700-5e08-11e9-9d54-42256f2c364a.png">
