### ISSUE TITLE
Element.QuerySelector returns a Node rather than an Element

### ISSUE THREAD

**Issue by Porl91** [bridgedotnet/Bridge#2660]
The QuerySelector method returns a Node rather than an Element. The issue is the return type for the method defined on the following line:
https://github.com/bridgedotnet/Bridge/blob/master/Html5/Elements/Element.cs#L215
```
public virtual extern Node QuerySelector(string selectors);
```

* The w3 spec specifies that this should be an (**Element?**):
Under the header **6.1. Interface Definitions** https://www.w3.org/TR/selectors-api/
* https://developer.mozilla.org/en/docs/Web/API/Element/querySelector
* https://developer.mozilla.org/en/docs/Web/API/Document/querySelector
* https://developer.mozilla.org/en-US/docs/Web/API/Element

### Expected Result

Element.QuerySelector returns Element

### Actual Result

Element.QuerySelector returns Node

**Comment by LeonidVeriga** [comment]
Changes **QuerySelector** return type to **Element**:
* https://developer.mozilla.org/en/docs/Web/API/Document/querySelector
* https://developer.mozilla.org/en/docs/Web/API/Element/querySelector  
> Returns the first Element within the document that matches the specified selector, or group of selectors.

**QuerySelectorAll** to **NodeList**
* https://developer.mozilla.org/en/docs/Web/API/Document/querySelectorAll
> Returns a list of the elements within the document (using depth-first pre-order traversal of the document's nodes) that match the specified group of selectors. The object returned is a NodeList.

**GetElementsByName** to **NodeList**:
* https://developer.mozilla.org/en/docs/Web/API/Document/getElementsByName
> Returns a NodeList collection with a given name in the (X)HTML document.
