### ISSUE TITLE
String.Format Invalid Formatting of native javascript numbers

### ISSUE THREAD

**Issue by rufio620** [bridgedotnet/Bridge#2665]
A description of the issue.
String.Format is outputting native javascript numbers using the wrong notation. Output seems to work fine with boxed numbers.

### Steps To Reproduce
https://deck.net/4f9742db4a24f835c3dfe62420db46ba

### Expected Result
-9007199254739999

### Actual Result
-9.00719925474E+15

**Comment by vladsch** [comment]
It is not a bug. Value is out of range of int32/uint32 types, it is not 64-bit value (because it is not wrapped by System.Int64 type) therefore Bridge considers that value is double. The output is correct for double

**Comment by rufio620** [comment]
That makes sense. I had another variant that was using Script.Get<long> and was expecting that to box the js value. I can just wrap the get call in a Convert.ToInt64. Thanks for your help.
