### ISSUE TITLE
Bridge 16-beta fails to load in Internet Explorer 11

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#2666]
In IE11, Bridge 16 beta crashes at startup (I've not tried any other IE versions, IE11 is the only version we're interested in).

### Steps To Reproduce

- Load https://deck.net/ in Internet Explorer

The error is:

```text
Cannot modify non-writable property 'name'
```

It occurs on this code:

```js
if (typeof member === "function" && name !== "$main") {
    Object.defineProperty(member, isFF ? "displayName" : "name", { value: className + "." + name, writable: true });
}
```

## See Also

* https://forums.bridge.net/forum/bridge-net-pro/bugs/4171-blackberry-10-browser-bridge-js
* https://forums.bridge.net/forum/bridge-net-pro/bugs/4178-bridge-16-0-0-beta-fails-in-ie11

**Comment by LeonidVeriga** [comment]
**enableNamedFunctionExpressions** option changed in PR #2674: new name is **namedFunctions**.
See more info at https://github.com/bridgedotnet/Bridge/wiki/Global-Configuration#namedfunctions.

**Comment by DanTup** [comment]
Is it a lot of hassle to create a new beta NuGet package with this fix? (Both to fix Deck in IE but also we were going to preview something with a client using 16-beta soon).

We can probably build ourselves if it's not trivial or takes much time, but it avoids some complications if it's an "official" version.

**Comment by LeonidVeriga** [comment]
@DanTup, yes we are going to release a new beta package; this item will be discussed today on Bridge.NET team meeting.

**Comment by DanTup** [comment]
Great, thanks!

**Comment by LeonidVeriga** [comment]
Regarding building packages locally from the sources, yes, it is trivial -
 https://github.com/bridgedotnet/Bridge/wiki/Build-From-Source

**Comment by LeonidVeriga** [comment]
@DanTup, the current plan is to release Beta-2 next week.

**Comment by LeonidVeriga** [comment]
More work required.

**Comment by ProductiveRage** [comment]
I've tested this with a local build of beta2 (I wanted to test an IE11 fix that I had to make to Bridge.React) and this issue still seems to be present.

@LeonidVeriga said that "More work required" but then this issue seems to have been closed from PR #2683.. but that seems to have been merged into master and I'm still having this problem in master. I'm not quite sure if you think that this is resolved or not?

As @DanTup saw, it fails at startup (when it tries to declare the "ctor" function of "System.Reflection.Assembly").

**Comment by LeonidVeriga** [comment]
@ProductiveRage, https://dev.deck.net updated with the code including #2683. Can you please confirm whether it loads for you on IE11?

https://deck.net updated with previous **-beta** (no #2683) does not load on IE11 for me, https://dev.deck.net does.

**Comment by ProductiveRage** [comment]
@LeonidVeriga - https://dev.deck.net/ works for me on IE11. Does this have code that's not in the master branch? I pulled down the latest changes (to this change from yesterday: 6b8258bc82b99b90790860b1ac91db4d4e3ab615) and that build _doesn't_ work in IE11 for me.

**Comment by LeonidVeriga** [comment]
@ProductiveRage, it is not the latest **master** but includes commit 17eba99 (master branch [commits](https://github.com/bridgedotnet/Bridge/commits/master)).
Can it be just script caching that requires **F5**?

**Comment by ProductiveRage** [comment]
@LeonidVeriga hmm... not sure what happened since I am fairly confident that I refreshed everything - but I had to restart my computer earlier and now it works. So guess that it must have been some sort of caching issue!
