### ISSUE TITLE
Error when trying to build two Bridge.NET projects in the same solution

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#267]
When trying to build a solution with two Bridge.NET projects (one of the projects references another Bridge project), errors occur and building fails.

This error was first spotted on May 6th, 2015 and re-questioned yesterday on Bridge.NET forums in [this thread](http://forums.bridge.net/forum/general/feature-requests/241).

While discussing the solution, it seems the problem is related to an attempt to re-extract Bridge's .js files during build. Called once, works fine; called from the second project, triggers errors like below:
```
Error: API restriction: The assembly 'file:///...' has already loaded from a different location. It cannot be loaded from a new location within the same appdomain.    
  at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, 
  ...
 at System.Reflection.Assembly.ReflectionOnlyLoadFrom(String assemblyFile)
  at Bridge.Translator.Translator.ExtractCore(String clrPath, String outputPath, Boolean nodebug)
  at Bridge.Build.GenerateScript.Execute()    ClientTestProject
```

The above error message was provided by @LeonidVeriga as of may 6th, 2015 and may or may not exactly match the forum question.

**Comment by LeonidVeriga** [comment]
Added a step to reproduce - "one of the projects references another Bridge project"

**Comment by fabriciomurta** [comment]
Tested. In used scenario the problem was fixed.

Steps:
1. Create new Web project
2. Create two ClassLibrary projects in the same solution
3. Install current bridge 1.5.0 on both ClassLibrary projects
`Install-Package bridge -Version 1.5.0`
4. Remove references to `System.*` on both ClassLibrary projects (side bug)
5. Try to build. An error should occur.
6. Try to build again, it should be successful this time.
7. Clean solution and rebuild again -- error from step 5 repeats. Another rebuild succeeds.
8. Close Visual Studio (important to free Builder.dll)
9. Load current GitHub Bridge code and build the full solution.
10. Replace .dll's with the newly built ones (helper script below)
11. Re-open Visual Studio with solution
12. Build, clean, rebuild, clean again, no errors. `bridge.js` is emitted on both solutions.

Helper script to replace DLL files from NuGet package to freshly built ones (in bash script format):
```
#!/bin/bash

# Top level directory where the test project is
pjhome="${HOME}/Object.NET/projects/BridgeSolution1"

# Top level directory where all Bridge repositories were cloned into.
cd ${HOME}/Object.NET/Bridge.NET/git

# Directory containing the NuGet package.
brdhome="${pjhome}/packages/Bridge.1.5.0"

#Bridge and Bridge.Html5 DLLs
cd Bridge/Html5/bin/Debug || { echo "Bridge/Debug dir not found."; exit 1; }
for dest in net40 net45; do
 cp *.dll *.xml ${brdhome}/lib/${dest}/.
 cp *.pdb ${brdhome}/lib/${dest}/pdb/.
done
cd -

# Builder DLL and dependencies (non-packed)
cd Builder/Build/bin/Debug || { echo "Builder/Debug dir not found."; exit 1; }
cp *.dll *.xml ${brdhome}/tools/.
cp Bridge.Build.dll ${brdhome}/tools/Bridge.Builder.dll
```
