### ISSUE TITLE
Consider changing interface behavior

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#2684]
The delegate does not invoke. It might be nice if the delegate invoked instead of calling invoke because the original interface has a template definition. I don't know how you want to implement it.

### Steps To Reproduce

[Deck Link](https://deck.net/dd97e9496ba5764fbade7bbb972e5874)
```csharp
public class Program
{
    public static void Main()
    {
        AsDelegate((Action)(() => Global.Alert("Success"))).Invoke();
    }
    
    [Template("{del}")]
    static extern ClassA AsDelegate (Delegate del);
}

public class ClassA : InterfaceA
{
    public extern void Invoke();
}

public interface InterfaceA
{
    [Template("{this}()")]
    void Invoke();
}
```

**Comment by vladsch** [comment]
You applied Template on interface member only. If class member implements interface member then it has to reapply Template (otherwise it means that class member doesn't want to use that Template).
https://deck.net/6635a35e0f4368126610730dcf826f9a

**Comment by michaelcheers** [comment]
@vladsch, yes I understand, this is just an idea for it could work.
