### ISSUE TITLE
How do the versions work?

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#2690]
The last version I've seen going from 1.* is 1.14 and after that it got to 15.0. So, what does this mean for Bridge 2.x. When using this new milestone system will we reach it? This might sound like a bit of a dumb question, _sorry_.

**Comment by LeonidVeriga** [comment]
@michaelcheers, yes we changed versioning approach started from **15.0**.

Regarding Bridge 2.x, [Bridge 15.0](https://github.com/bridgedotnet/Bridge/issues?utf8=%E2%9C%93&q=is%3Aissue%20milestone%3A15.0) was a major release including these key features which can be expressed as Bridge 2.0:
- Reflection
- C#6 syntax support
- System.Linq.Expressions
- Enhanced Regex support
- Migrated Saltarelle tests into Bridge.

The current official **15.7** and upcoming **16.0** (that is now in a beta phase) are even more that initially was considered as Bridge 2.0.

**Comment by michaelcheers** [comment]
@LeonidVeriga, thanks!
