### ISSUE TITLE
Incorrect results caused by variables being lifted outside embedded functions

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#2696]
May have raised this (or something similar) before, but can't find it now :(

Deck: https://deck.net/7b27697dc1f5114d9c1b677a5c3f71ee
.NET Fiddle: https://dotnetfiddle.net/bfGn8S

The code looks like this:

```cs
public static void Main()
{
	foreach(var item in GetDays().ToArray())
		item();
}
    
static IEnumerable<Action> GetDays()
{
	for (int day = 1; day <= 7; day++)
	{
		var date = new DateTime(2001, 1, day);
		yield return () => Console.WriteLine(date);
	}
}
```

In C#, it outputs 7 different dates; however in Bridge they're all the same. The reason seems to be a variable being lifted out of the embedded function, which means all calls get the "last" value:

```js
GetDays: function () {
	return new (Bridge.GeneratorEnumerable$1(Function))(Bridge.fn.bind(this, function ()  {
		var $step = 0,
			$jumpFromFinally,
			$returnValue,
			day,
			date, // <-- this should probably be declared inside the function below?
			$async_e;

		var $enumerator = new (Bridge.GeneratorEnumerator$1(Function))(Bridge.fn.bind(this, function () {
		// (SNIP)
			case 2: {
				date = new Date(2001, 1 - 1, day);
				$enumerator.current = function () {
					System.Console.WriteLine(Bridge.box(date, System.DateTime, $box_.System.DateTime.toString));
				};
				$step = 3;
				return true;
			}
		// (SNIP)

		return $enumerator;
	}));
}
```

**Comment by vladsch** [comment]
Thanks for the report. It is already fixed. See in dev.deck.net.
Related issue: https://github.com/bridgedotnet/Bridge/issues/2633

**Comment by vladsch** [comment]
Also side effect from that fix. 
https://github.com/bridgedotnet/Bridge/issues/2686

It is also fixed (PR https://github.com/bridgedotnet/Bridge/pull/2695).

**Comment by DanTup** [comment]
Great; thanks! :-)
