### ISSUE TITLE
ToLocaleDateString () method returns an incorrect date for a leap-year

### ISSUE THREAD

**Issue by AleXr64** [bridgedotnet/Bridge#2697]
https://deck.net/91ab38f1dc624a7a331bfd346e1b04ff
and work well with regular year https://deck.net/63a2239628a40f1d1d7c753e026a1c0b

**Comment by geoffreymcgill** [comment]
Your samples appear to return the correct result for me. I get the following results with the two samples:

https://deck.net/91ab38f1dc624a7a331bfd346e1b04ff

```02/02/1991
2/2/1991
3/3/1991``

https://deck.net/63a2239628a40f1d1d7c753e026a1c0b

```02/02/1991
2/2/1991
3/3/1992
```

What are the expected results?

**Comment by geoffreymcgill** [comment]
The `ToLocaleDateString` Method should not be available on a **DateTime** object, only a JavaScript **Date** object. We're going to have to fix that.

**Comment by AleXr64** [comment]
![image](https://cloud.githubusercontent.com/assets/26191634/26338276/e214f402-3f8f-11e7-9053-b8eaaa984715.png)
Got this on Win10 machine with settings: RU locale/region/culture, GMT+4.  
And have some strange with Date on same machine. 
![image](https://cloud.githubusercontent.com/assets/26191634/26338436/f9f2e8da-3f90-11e7-9aac-332406d0880d.png)

**Comment by AleXr64** [comment]
Hm... Edge on badWin10 machine works fine...
![image](https://cloud.githubusercontent.com/assets/26191634/26339862/0f4b2386-3f9c-11e7-94d3-26616830e77e.png)

**Comment by AleXr64** [comment]
Itself the fool. The problem was in time zones and the change of time for summer / winter (although it is described everywhere, but in our region it is not applied, however it is included in the time zone), thanks for attention. https://en.wikipedia.org/wiki/Samara_Time

**Comment by geoffreymcgill** [comment]
Closing this issue as `ToLocaleDateString` is not a member of the **DateTime** object.
