### ISSUE TITLE
XMLHttpRequest OnProgress action takes an Event object rather than ProgressEvent

### ISSUE THREAD

**Issue by Porl91** [bridgedotnet/Bridge#2702]
On the following class I would expect the OnProgress action to accept a ProgressEvent rather than a generic Event:

https://github.com/bridgedotnet/Bridge/blob/cbbef06d3a52a3eb0c062310241a5d1631fc8c0e/Html5/Ajax/XMLHttpRequestEventTarget.cs

There does appear to be a ProgressEvent defined here:

https://github.com/bridgedotnet/Bridge/blob/a33afec7fbf18e216363eb87136d256fe61de1fd/Html5/Events/ProgressEvent.cs

I suspect this is just an oversight?

**Comment by geoffreymcgill** [comment]
Hi @Porl91 – Thanks for reporting this issue. Yes, it appears a **ProgressEvent** should be returned. 

We will try to fix this right away and include in the next release.

**Comment by geoffreymcgill** [comment]
A pull request has been submitted with a fix for this Issue. Once the PR is reviewed, the fix will be merged into the **master** branch and included with the next public release.
