### ISSUE TITLE
GetHashCode override making use of float.GetHashCode or double.GetHashCode fails

### ISSUE THREAD

**Issue by jbeshir** [bridgedotnet/Bridge#2703]
In 16.0.0-beta1, the current version on deck.net, and seemingly the current master (https://github.com/bridgedotnet/Bridge/blob/master/Bridge/Resources/Double.js) Double.GetHashCode returns a string rather than the integer that it is declared to return to C#.

If you then use the result in arithmetic, as is common to combine hashes of various fields to provide a hash code for a struct or class, it causes misbehaviour, often with the result always being zero, causing all hash codes to match.

Double.GetHashCode should probably go back to returning an integer so as to conform to what it declares itself as returning to C# code.

(ETA: Double.GetHashCode is also used to provide Single.GetHashCode, which is why my reproduction steps using float show the problem and is where I originally replicated it.)

### Steps To Reproduce

https://deck.net/de0d4660b138fd2f9196c83b7f26a320

```c#
public class Program
{
    public static void Main()
    {
        var msg = "Hello, World!";
        
        var v1 = new Vector2(0f, 0f);
        var v2 = new Vector2(1f, 2f);
        var v3 = new Vector2(76757f, 567567f);
        Console.WriteLine(v1.GetHashCode());
        Console.WriteLine(v2.GetHashCode());
        Console.WriteLine(v3.GetHashCode());
    }
}

public class Vector2
{
    public float X;
    public float Y;
    
    public Vector2(float x, float y)
    {
        X = x;
        Y = y;
    }
    
    public override int GetHashCode()
    {
        return X.GetHashCode() + Y.GetHashCode();
    }
}
```

### Expected Result

Different hash values for the different vectors; not picky what.

### Actual Result

```js
0
0
0
```

**Comment by LeonidVeriga** [comment]
Thanks for excellent bug report, @jbeshir.

The issue has been fixed and will be included into the next Bridge release.
