### ISSUE TITLE
Check that external object literal has no custom constructors

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#2710]
If external object literal has custom constructor then compiler exception should be thrown (like for non-external literal). 

Basically, all the checks applied to non-External ObjectLiteral should applied to External ObjectLiteral:
* "[ObjectLiteral] does not support virtual methods: {0}";
* "[ObjectLiteral] class (plain mode) does not support Bridge.ObjectCreateMode parameter in a custom constructor: {0}";
* "[ObjectLiteral] class (plain mode) does not support custom constructors with parameters other than with ObjectLiteralAttribute properties: {0}";
* "[ObjectLiteral] with Plain mode cannot be inherited from [ObjectLiteral] with Constructor mode: {0}";
* "[ObjectLiteral] with Constructor mode should be inherited from a class with the same options: {0}";
* "[ObjectLiteral] interface does not support overloaded methods: {0}";
* "[ObjectLiteral] interface does not support events: {0}";
* "[ObjectLiteral] does not support explicit interface member implementation: {0}";
* "[ObjectLiteral] should implement an interface which must be object literal also: {0}";

https://deck.net/c359b30daf5f9b5b86def5453dc86123

```c#
public class Program
{
    public static void Main()
    {
        var p = new PersonDetails(1, "one");
        
        Console.WriteLine(p.Key);
        Console.WriteLine(p.Name);
    }
}

[External]
[ObjectLiteral]
public class PersonDetails
{
    public PersonDetails(int key, string name)
    {
        Key = key;
        Name = name;
    }
    public int Key { get; set; }
    public string Name { get; set; }
}
```

### Expected Result
Compiler exception as this **[External]** object literal contains an actual code in the constuctor.

### Actual Result
JavaScript generated:
```js
var p = { key: 1, name: "one" };

System.Console.WriteLine(p.Key);
System.Console.WriteLine(p.Name);
```
Console outputs two empty lines as upper cased properties **Key** and **Name** are not defined by the statement `var p = { key: 1, name: "one" };` using lower cased names.

## See Also

* https://forums.bridge.net/forum/bridge-net-pro/bugs/4203-external-objectliteral-properties-camel-cased-when-they-shouldn-t-be

**Comment by vladsch** [comment]
Alternative for custom constructor can be factory methods
```cs
[External]
    [ObjectLiteral]
    public class PersonDetails
    {
        private PersonDetails()
        {
        }

        [Template("{Key: {key}, Name: {name}}")]
        public static extern PersonDetails Create(int key, string name);

        public int Key { get; set; }
        public string Name { get; set; }
    }
```

**Comment by LeonidVeriga** [comment]
Basically, all the checks applied to non-External ObjectLiteral now are applied to External ObjectLiteral:
* "[ObjectLiteral] does not support virtual methods: {0}";
* "[ObjectLiteral] class (plain mode) does not support Bridge.ObjectCreateMode parameter in a custom constructor: {0}";
* "[ObjectLiteral] class (plain mode) does not support custom constructors with parameters other than with ObjectLiteralAttribute properties: {0}";
* "[ObjectLiteral] with Plain mode cannot be inherited from [ObjectLiteral] with Constructor mode: {0}";
* "[ObjectLiteral] with Constructor mode should be inherited from a class with the same options: {0}";
* "[ObjectLiteral] interface does not support overloaded methods: {0}";
* "[ObjectLiteral] interface does not support events: {0}";
* "[ObjectLiteral] does not support explicit interface member implementation: {0}";
* "[ObjectLiteral] should implement an interface which must be object literal also: {0}";
