### ISSUE TITLE
Incorrect syntax for lambda with captured variables and `this`

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#2712]
Bridge generates incorrect javascript code for lambda with captured variables and `this`

### Steps To Reproduce
https://dev.deck.net/c6ffd00303f0917daf2081cc65973e0f
```c#
public class Program
{
    public void Test()
    {
        for (int i = 0; i < 1; i++)
        {
            var idx = i;

            Action a = () =>
            {
                var idx2 = idx;
                var str = this.ToString();
            };

            Action a1 = () =>
            {
                var idx2 = idx;
            };
        }
    }
}
```

### Actual Result
> SyntaxError: Unexpected token )

## See Also

* https://forums.bridge.net/forum/bridge-net-pro/bugs/4273-latest-build-has-runtime-error

**Comment by DierkDroth** [comment]
@vladsch glad you had been able to isolate :-)
