### ISSUE TITLE
Default value for delegate parameter is not used.

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#2716]
The following code should output value `123` to console.

### Steps To Reproduce

https://deck.net/93ebd7a4bd73caf2356dee6ad2d1ec65

```c#
internal class Program
{
    public delegate void Callback(int context = 123);

    private static void Main(string[] args)
    {
	Callback callback = context =>
	{
            int test = context;

            Console.WriteLine(test);
	};

	callback();
    }
}

```

### Expected Result

```js
Bridge.assembly("Demo", function ($asm, globals) {
    "use strict";

    Bridge.define("Demo.Program", {
        main: function Main(args) {
            var callback = $asm.$.Demo.Program.f1;

            callback();
        }
    });

    Bridge.ns("Demo.Program", $asm.$);

    Bridge.apply($asm.$.Demo.Program, {
        f1: function (context = 123) {
            var test = context;

            System.Console.WriteLine(test);
        }
    });
});

```

### Actual Result

```js
Bridge.assembly("Demo", function ($asm, globals) {
    "use strict";

    Bridge.define("Demo.Program", {
        main: function Main(args) {
            var callback = $asm.$.Demo.Program.f1;

            callback();
        }
    });

    Bridge.ns("Demo.Program", $asm.$);

    Bridge.apply($asm.$.Demo.Program, {
        f1: function (context) {
            var test = context;

            System.Console.WriteLine(test);
        }
    });
});

```

**Comment by vladsch** [comment]
Thanks for the report. We will fix it.

**Comment by hardhub** [comment]
Nice :)

Unfortunately it is only first act of performance...
Template attribute cannot be assigned to method parameter..
I tried to put custom string instead of 123.

Initially I used PageJS but it does not work for some reason with Bridge.NET. 
So I have migrated to PathJS which is old but works fine. And to simplify all I have rewritten these bindings: https://github.com/mattleibow/Saltarelle.PathJs

So in Path.cs of original repo we have the following code:
```C#
public static JsDictionary<string, string> Parameters
{
    [InlineCode("this.params")] get { return null; }
}
```

Which means we need 'this.params' inside current callback function. It is implemented as static property: Path.Parameters["something"].. But calling such code outside of callback is dangerous.
But from point of view of C# calling such static property everywhere is correct (but not for JS).
So static property is not very good and as alternative it could be something like this:
```C#
public delegate void Callback([Template("{this} = this.params")] IReadOnlyDictionary<string, string> context);
```
In this case I will have possibility to get "this.params" with variable:
```C#
Callback callback = context =>
{
     IReadOnlyDictionary<string, string> nice = context;
};
```
I guess it is what was possible with "BindThisToFirstParameterAttribute" in Saltarelle.

So if it is possible to add power for Template attribute then we can move this post to separate issue.

**Comment by hardhub** [comment]
I have found ugly trick to achieve context-based behavior ))

```C#
[External]
public delegate void Callback(Context context);

[External]
[Namespace(false)]
public class Context
{
    public new extern string this[string name] { [Template("({this} = this.params)[{0}]")] get; }
}
```
