### ISSUE TITLE
Include Reflection metadata by default

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2732]
Previous to Bridge 16, the Reflection metadata was only included if the `[Reflectable]` attribute was applied to the class. This approach has lead to much confusion as it's easy to overlook the inclusion of this attribute. If the `[Reflectable]` attribute were not applied, Reflection would not work.

As of Bridge 16, Reflection metadata will be automatically generated and included in a separate **[app-name].meta.js** file. 

For example, if Bridge generates a **CompanyX.js** file for your app, the Bridge compiler will also emit a new **CompanyX.meta.js** file to the same [output](https://github.com/bridgedotnet/Bridge/wiki/global-configuration#output) location.

The following sample demonstrates the *pre* Bridge v16.0 technique of including Reflection metadata by applying the `[Reflectable]` attribute:

https://deck.net/934b6e86babd510fa612909914d8d6f9

```csharp
[Reflectable]
public class Person
{
    public string Name { get; set; }
}
```

The following chunk of metadata would be included at the bottom of your **[app].js** file:

```js
var $m = Bridge.setMetadata,
    $n = [System,Demo];
$m($n[1].Person, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Name","t":16,"rt":$n[0].String,"g":{"a":2,"n":"get_Name","t":8,"rt":$n[0].String,"fg":"Name"},"s":{"a":2,"n":"set_Name","t":8,"p":[$n[0].String],"rt":$n[0].Object,"fs":"Name"},"fn":"Name"}]}; });
```

With Bridge v16+, the `[Reflectable]` attribute can be removed, and the same metadata will be automatically included in a separate **[app].meta.js** file.

This **[app].meta.js** file must be included in your .html page after your **[app].js** file. 

If the **[app].meta.js** is not included, any C# Reflection calls will gracefully degrade, by not throwing errors, but will also not return reflection information regarding the class(es) during runtime.

Automatic generation of the Reflection metadata can be disabled by setting the `reflection.disabled` property to `true` in your projects **bridge.json** configuration file. 

#### Example

```js
reflection: {
    disabled: true|false (default is false)
}
```

Once Reflection metadata generation has been disabled, you can force generation of metadata for specific scenarios by applying the `[Reflectable]` attribute.

If you are confident you do not require the Reflection metadata during the runtime of your app, do not add the **[app].meta.js** file in your .html page.

If you have Bridge combine all .js file by setting `combineScripts: true` ([docs](https://github.com/bridgedotnet/Bridge/wiki/global-configuration#combinescripts)) in your projects **bridge.json**, you can exclude **[app].meta.js** from the combined file by including the following `resources` config in your projects **bridge.json**.

```js
{
  "resources": [
    {
      "name": "demo.meta.js", <-- replace with your .meta.js file name
      "extract": false
    }
  ]
}
```

## See Also

* #2603

**Comment by michaelcheers** [comment]
Related to [this issue comment](https://github.com/bridgedotnet/Bridge/issues/15#issuecomment-221779421).
