### ISSUE TITLE
Incorrect boxing/unboxing when calling methods via reflection invoke

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#2738]
**Edit** The original report was bogus; I was missing `[Reflectable]`. Now seeing the same behaviour as the original issue I had, so updated...

**Edit** Due to #2732 " Include Reflection metadata by default" **[Reflection]** is not mandatory anymore.

https://dev.deck.net/a563ead6396ac52461aef3d168e649b3
https://dotnetfiddle.net/xnfLsm

Code:

```cs
public class Program
{    
    public static IEnumerable<object[]> testDataDates => new[] { new object[] { new DateTime(2017, 1, 1), new DateTime(2018, 1, 1) } };
    
    public static void Main()
    {          
        var method = typeof(Program).GetMethod("LogDates");
        
        foreach (var dates in testDataDates)
        	method.Invoke(null, dates);
    }
    
    public static void LogDates(DateTime a, DateTime b) {
        Console.WriteLine(a.Year);
        Console.WriteLine(b.Year);
    }
}
```

It should output the current year (and does in DotNetFiddle) but fails in Bridge:

```text
Bridge Console
System.Exception: TypeError: a.getFullYear is not a function
    at LogDates (https://dev.deck.net/RunHandler.ashx?h=-1382176977:33:48)
    at https://dev.deck.net/resources/js/bridge/bridge.js?17eba99:1591:45
    at https://dev.deck.net/resources/js/bridge/bridge.js?17eba99:1489:39
    at Function.Main (https://dev.deck.net/RunHandler.ashx?h=-1382176977:16:59)
    at https://dev.deck.net/resources/js/bridge/bridge.js?17eba99:3146:39
    at HTMLDocument.delayfn (https://dev.deck.net/resources/js/bridge/bridge.js?17eba99:459:21)
    at i (https://code.jquery.com/jquery-2.2.4.min.js:2:27151)
    at Object.add [as done] (https://code.jquery.com/jquery-2.2.4.min.js:2:27450)
    at n.fn.init.n.fn.ready (https://code.jquery.com/jquery-2.2.4.min.js:2:29515)
    at n.fn.init (https://code.jquery.com/jquery-2.2.4.min.js:2:24945)
```

Maybe related to boxing - if I examine `a` inside this method, it looks like something that is boxed:
![boxed](https://cloud.githubusercontent.com/assets/1078012/26627004/dc8b32d2-45f0-11e7-85fd-9383eca88b3e.jpg)

**Comment by LeonidVeriga** [comment]
**[Reflectable]** should be added (yes, we are working on #2732):
    https://deck.net/4ae05031cc2bcd3c093c072662ea3da1

And with the attribute it ... gets a meaningfull DateTime related error:
```
TypeError: a.getFullYear is not a function
```

We will look at this issue. Thanks for reporting.

**Comment by DanTup** [comment]
@LeonidVeriga Yeah sorry for the bad report - I fixed that up and then got the real error that I'd have in my production app. The links ot Deck + DNF above should be better samples now :-)

**Comment by LeonidVeriga** [comment]
Looks like a wrong unboxing.

A workaround is to force unboxing in the log method by changing its parameter type. For example, **LogDates1** or **LogDates1**:
https://deck.net/3d5f2e2ca7214a4db802ed740cab7726
```cs
    public static void LogDates1(object a)
    {
        if (a is DateTime)
        {
            var d = (DateTime)a;
            Console.WriteLine(d.Year);
        }
    }
    
    public static void LogDates2(DateTime? a)
    {
        if (a.HasValue)
        {
            Console.WriteLine(a.Value.Year);
        }
    }
```

**Comment by LeonidVeriga** [comment]
Due to #2732 " Include Reflection metadata by default" [Reflection] is not mandatory anymore.
