### ISSUE TITLE
Allow users to choose different bridge.json values on deck.net.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#2744]

**Comment by kcudnik** [comment]
Also, samples "8. Newtonsoft.Json.cs" on deck.net doesen't compile

**Comment by geoffreymcgill** [comment]
> Also, samples "8. Newtonsoft.Json.cs" on deck.net doesen't compile

It will only work with the **16.0.0-beta2** build on https://dev.deck.net for now. Once 16.0.0-beta2 is released to NuGet, the main [Deck.NET](https://deck.net) app will be updated with **Bridge.Newtonsoft.Json**.

**Comment by kcudnik** [comment]
thanks for update

**Comment by michaelcheers** [comment]
@geoffreymcgill, it could also be useful to allow users to alter the Bridge version number as well.

**Comment by LeonidVeriga** [comment]
Created an issue in Deck repo https://github.com/objectdotnet/Deck/issues/27

**Comment by michaelcheers** [comment]
@LeonidVeriga, this link no longer works.

**Comment by LeonidVeriga** [comment]
@michaelcheers, do you mean https://github.com/objectdotnet/Deck/issues/27?
It works for me.

**Comment by geoffreymcgill** [comment]
@michaelcheers The link to Deck [Issue #24](https://github.com/deckdotnet/Deck.NET/issues/24) has been fixed.
