### ISSUE TITLE
Uncaught error on Bridge level with Document.AppendChild()

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#275]
The C# line:

```c#
Document.AppendChild(new SpanElement() { InnerHTML = "Check results on the console log." });
```

Builds just fine, generating the JavaScript code:

``` javascript
document.appendChild(Bridge.merge(document.createElement('span'), {
                innerHTML: "Check results on the console log."
            } ));
```

Which, in turn, results in the error:
![nestedinitappenderror](https://cloud.githubusercontent.com/assets/10730372/8273063/8236943a-1833-11e5-9296-c24ec847568e.png)

**Comment by vladsch** [comment]
What do expect from that code? The exception is not related with Bridge
Try to run that code in console
`document.appendChild(document.createElement('span'));`
and you will get
```
Uncaught DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.
    at Error (native)
    at <anonymous>:2:10
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)
```
So, i guess, it is problem how do you use javascript API

**Comment by fabriciomurta** [comment]
I expected bridge not to allow this to be run but, yes, you have a point.

I was thinking... Isn't there a way to detect this before taking things "live" (to JavaScript)? Or are there situations where this should work?

**Comment by fabriciomurta** [comment]
I assigned it back to me, say, who knows in the future we can think a way to prevent this error from C# side... it would be great, at least. :)

**Comment by geoffreymcgill** [comment]
I added this scenario to a list of Analyzers that could catch this scenario and offer a work-around. 

### See Also

* #2365
