### ISSUE TITLE
Minified bridge.min.js does not load work in MS Edge browser

### ISSUE THREAD

**Issue by tluyben** [bridgedotnet/Bridge#2753]
Create the Bridge.NET web project, build and open in Edge. There will get this error; 

Cannot modify non-writable property 'name' 

in bridge.min.js 

It works on other browser. When I use the full, non minified version, everything works fine on Edge too.

**Comment by geoffreymcgill** [comment]
Duplicate.

https://github.com/bridgedotnet/Bridge/issues/2666
