### ISSUE TITLE
"An item with the same key has already been added" when using beta2 if you still reference the Bridge.Collections package

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#2758]
We've been trying to build from `master` because of blocking issues in `16.0.0-beta` (assemblies sorted incorrectly) and our previous custom build (types within assembly sorted incorrectly). However with the current master code we get this error building some projects:

```text
error : Error: An item with the same key has already been added.    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
error :    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
error :    at Bridge.Translator.Translator.AddNestedTypes(IEnumerable`1 types)
error :    at Bridge.Translator.Translator.ReadTypes(AssemblyDefinition assembly)
error :    at Bridge.Translator.Translator.InspectReferences()
error :    at Bridge.Translator.Translator.Translate()
error :    at Bridge.Build.BridgeCompilerTask.Execute()
```

I've managed to strip it down to a fairly small repro, however it includes a couple of DLLs from components we're working on so I can't really attach it here (I'll email it to @geoffreymcgill now).

The project is very simple, it references 5 other Bridge DLLs and contains a single class like this:

```cs
public sealed class FormEditStoreViewModel
{
	public FormEditStoreViewModel(TextBoxModel title, ListOfModel<TextBoxModel> roles)
	{
	}		
}
```

Removing either of the arguments to this constructor cause the error to disappear; but I just cannot figure out what's going on. I've inspected all 5 referenced DLLs (in the `ext` folder) and ensured they do not have any duplicate namespace/class names (or at least, as far as I can tell).

This issue does not seem to occur using `16.0.0-beta` nor the previous build we'd taken from `master` a week or so ago.

**Comment by DanTup** [comment]
Ok, I wonder if it's this:

```text
The type 'HashSet<T>' exists in both 'Bridge.Collections, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null' and 'Bridge, Version=16.0.0.0, Culture=neutral, PublicKeyToken=null'
```

This occurs as a warning when building our components (but we don't see it when building the project that references them). I wonder if it's because we're got Bridge from master, but still an old Collections, so we have two copies of this type.

We'll see if we can build a copy of Collections from master and see if it goes away using that.

**Comment by DanTup** [comment]
Oh, I misunderstood - the whole of Collections has gone. Removing that NuGet from our project fixed the issue. Doh!

This does mean if anyone adds the Collections package after you push beta2, they'll get the same non-descriptive error.

**Comment by DanTup** [comment]
Ok, so this is caused by having a reference to the Bridge.Collections package using beta2 code (which now contains those classes itself).

I don't know if you can do much about this, but it seems like a bit of a gotcha for people upgrading. I'll leave this Issue in case you want to do something about it, but feel free to close if you don't think it's easily addressable (can you edit the NuGet version constraint on the existing Collections package to stop at `16.0.0-beta`?)

**Comment by geoffreymcgill** [comment]
> can you edit the NuGet version constraint on the existing Collections package to stop at 16.0.0-beta?

It does appear NuGet [permits](https://docs.microsoft.com/en-us/nuget/create-packages/dependency-versions) the setting of a maximum version by adding a version range. I think the following should work with the [Bridge.Collection.nuspec](https://github.com/bridgedotnet/Frameworks/blob/ea75195e922f0c38d4622e8bff1c91827b2d7275/.build/specs/Bridge.Collections.nuspec) file.

```
<dependencies>
  <dependency id="Bridge.Core" version="(,15.7.0]" />
</dependencies>
```

NuGet does not permit editing of released packages, so we'll have to publish a new version of **Bridge.Collections** with this version restriction included. Some confusion during the upgrade process might still occur, but at a minimum, NuGet is going to throw an error during upgrade instead of just letting the package slip through undetected.

All [Breaking Change](https://github.com/bridgedotnet/Bridge/issues?q=is%3Aissue+milestone%3A16.0+label%3Abreaking-change+is%3Aclosed) should be tagged for the release, and Issue #2730 is where **Bridge.Collections** integrated into the Bridge project.

**Comment by geoffreymcgill** [comment]
Issue https://github.com/bridgedotnet/Frameworks/issues/66 has been created to track publishing of a final **Bridge.Collections** package.

The issue (#2758) will be closed once Issue https://github.com/bridgedotnet/Frameworks/issues/66 has been closed.

**Comment by geoffreymcgill** [comment]
The final **Bridge.Collections** with the maximum version on *15.7.0* constraint has been published to NuGet.

https://www.nuget.org/packages/Bridge.Collections/

**Comment by DanTup** [comment]
@geoffreymcgill Maybe it's also worth "unlisting" the older versions of the package to avoid anyone using >= 16.0 from trying to install them (I presume they'll still show up)?

https://docs.microsoft.com/en-us/nuget/policies/deleting-packages

Unlisting a package still allows it to be restored (or installed using a specific version number) but will no longer show up on searches. If you unlist all but the last one, then people should only ever be able to find that one that has the "good" version constraint?

(I've never actually done this so can't say for sure how it works, but there's info about it in the link above).

**Comment by geoffreymcgill** [comment]
I've set the *1.3.5-beta* package as unlisted.

Even with unlisted packages, if you explicitly specify the version number, NuGet will allow installation. Hiding doesn't really prevent much.

The new version constraint on Bridge.Collections 1.3.5 should catch almost all upgrade scenarios.

**Comment by DanTup** [comment]
> Hiding doesn't really prevent much.

Not much, but maybe a little - if I have Bridge 16 installed and search NuGet for "Bridge" in VS, it'll (presumably) show the old versions of Collections (which, if installed, cause this confusing error).

Since there's no great fix for this, maybe it would be worthwhile in future have bounded version constraints for all packages (tied to the major version)? This way when breaking changes are made, there's a way of ensuring NuGet enforces the correct versions (and if you want to roll the major version without breaks, there's no reason you can't re-publish a version to relax them).

**Comment by geoffreymcgill** [comment]
> Since there's no great fix for this, maybe it would be worthwhile in future have bounded version constraints for all packages (tied to the major version)?

Yes, I've been thinking the exact same thing. After **16.0.0-beta2** is published, we'll run some tests with version constraints for future releases.
