### ISSUE TITLE
Error occurs when class has where constraints for types not yet defined in document

### ISSUE THREAD

**Issue by Porl91** [bridgedotnet/Bridge#2759]
Apologies for the long reproduce case, it was difficult to reduce the complexity of the example without eliminating the error. In the example below class `C` has two where constraints on it that relate to types that aren't yet defined in the document. 

When these constraints are removed the source compiles correctly, which suggests that the logic that orders classes based on when they're referenced perhaps doesn't take into account these type parameter constraints? 

Here's a reproduce of the issue:

https://dev.deck.net/7a17cb17d9964099aa38359edd4400cf

If you run this example with the developer tools console open you can see that when defining the class `A` it refers to class `B` that hasn't been defined yet. In fact, the top level namespace `Test1` isn't defined by this point.

In Deck the error in the console is, which suggests that `Test1` itself isn't defined:
`Uncaught ReferenceError: Test1 is not defined`

When I ran this on my local build of the master branch I received a different error, which suggests that `Test1` is defined, but `B` isn't:
`TypeError: Cannot read property 'B$1' of undefined`

**Comment by geoffreymcgill** [comment]
Hi @Porl91,

Thanks for bringing our attention to this issue and for providing the excellent sample demonstrating how to reproduce.

We are investigating this defect right now and will try to fix immediately.
