### ISSUE TITLE
Metadata from dependant libraries not included in output

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#2760]
(I'm using code from `master`, which I believe includes the recent reflection changes)

I have two Bridge libraries, TestFramework and Tests. Tests has a reference to TestFramework. When TestFramework builds, it outputs a `.meta.js` file. However, this file never makes it to the output of Tests:

- `combineScripts: true` - Tests.js ends up with the reflection metadata for  the Tests project, but not for the TestRunner project.
- `combineScripts: false` then Tests.meta.js has the reflection metadata for the Tests project, but there is no TestRunner.meta.js

So it seems that no matter what I do, I am unable to get the reflection metadata for the referenced project.

Is this a bug, or is there something else I need to do?

**Comment by geoffreymcgill** [comment]
This is likely the defect we discovered that I was mentioning in [gitter](https://gitter.im/bridgedotnet/Bridge?at=59363789cf9c13503c599b8c).

The fix is being worked on in the [Html2](https://github.com/bridgedotnet/Bridge/tree/Html2) branch and should be merged into **master** soon.

**Comment by LeonidVeriga** [comment]
@DanTup, can you provide a list of projects with its config, outputs and required results.
Is it something like:
 - ProjectA 
    - { "combineScripts": false }
    - bridge.js, A.js , A.meta.js
 - ProjectB references ProjectA
    - { "combineScripts": true }
    - B.js (including bridge.js, A.js, A.meta.js, B.js, B.meta.js)

**Comment by DanTup** [comment]
@geoffreymcgill I thought it might and found that branch after posting (though it mentioned source maps so I then wasn't sure).

@LeonidVeriga Give me 10 mins and I'll strip this project down and attach it. It does have some custom config to control the output that might be related.

**Comment by DanTup** [comment]
@LeonidVeriga Ok, upon stripping it down it seems to be caused by my Bridhe.json in TestRunner being like this:

```js
{
  "fileName": "TestRunner.js",
  "resources": [
    {
      "output": "./",
      "name": "TestRunner.js",
      "files": [ "$(OutputPath)/Bridge/TestRunner.js" ]
    },
    {
      "name": "TestRunner.html",
      "files": [ "Client/TestRunner.html" ]
    }
  ]
}
```

My guess is that including the resources section means that I need to also list the `.meta` file to ensure it's included? I figured it would work like the `.min` file and not need including, however that could be because you're re-minifying from the original rather than it's being embedded.

So I can probably fix it by doing:

```js
      "files": [ "$(OutputPath)/Bridge/TestRunner.js", "$(OutputPath)/Bridge/TestRunner.meta.js" ]
```

Can you confirm if that's expected?

**Comment by DanTup** [comment]
@geoffreymcgill Confirmed this is expected behaviour with the metadata changes, so this is not a bug. Adding the file to the resource list has solved my issue.

**Comment by LeonidVeriga** [comment]
@DanTup, Yes, if there is a **resources** section in you config then Compiler embeds the files listed in the resources (the only files). If there is no any resource items then Compiler applies the default behavior (embedding all the outputs).
