### ISSUE TITLE
Request to implement missing Uri class members

### ISSUE THREAD

**Issue by Porl91** [bridgedotnet/Bridge#2768]
The implementation of the System.Uri class appears to be missing a few members. For reference:

https://github.com/bridgedotnet/Bridge/blob/038c48ccde0ab3685599ff8c63dd0afbac1e0c6e/Bridge/System/Uri.cs

C# System.Uri class:
https://msdn.microsoft.com/en-us/library/system.uri(v=vs.110).aspx

This will be a framework class that we'll be using extensively to ensure that we're passing around valid URIs. Would it be possible to implement these missing members?

**Comment by geoffreymcgill** [comment]
Seems this is covered by #2185.
