### ISSUE TITLE
System.Uri class is not reflectable

### ISSUE THREAD

**Issue by Porl91** [bridgedotnet/Bridge#2769]
When sending URIs over the wire we'd prefer to send them as serialized `System.Uri` objects to ensure that they're valid, although they don't currently appear to be reflectable.

Example here:
https://dev.deck.net/65c665a8eb9ae0f60279a98f632552f2

This appears to generate an error because `System.Uri` isn't reflectable. Is there a way we can make framework classes reflectable or would it be possible to make this class reflectable?

**Comment by Porl91** [comment]
Hi @vladsch, do you know if the fix for this will be in the next pre-release?

**Comment by vladsch** [comment]
Hi,

Yes, we will add Reflectable attribute to that class.

**Comment by michaelcheers** [comment]
You should just use:
```csharp
[assembly: Reflectable(true)]
```
to avoid such bugs.

**Comment by DanTup** [comment]
@michaelcheers The `Uri` class isn't defined in our assembly, it's in Bridge, so I'm not sure that'll work?

Also, if I understood correctly assemblies default to being reflectable in v16 (though based on @vladsch's comment, I presume that's not the case for the core Bridge assemblies).

**Comment by vladsch** [comment]
By default, only non-external classes are reflectable.
System.Uri is marked as External (external implementation), that's why Reflectable attribute is required

**Comment by Porl91** [comment]
Hi @LeonidVeriga, I see that in beta3 the `[Reflectable]` attribute's been added to the `System.Uri` class, although it appears to be throwing an exception when I attempt to serialise a class that has a `System.Uri` as a property. Here's a quick repo:

https://deck.net/8a5ee9dfc27641cf91ce568d172bbb5f

Should I stick a separate issue in for this?

**Comment by michaelcheers** [comment]
@vladsch, there are many very similar problems:
See #2843.

**Comment by Porl91** [comment]
I'll create a separate issue about the last point because it's related more to serialisation than making the class reflectable.
