### ISSUE TITLE
New {@} and {$} tokens for [Template] and [Name] attributes

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2794]
* A new `{@}` token to be used within `[Template]` and `[Name]` attributes ([docs](https://github.com/bridgedotnet/Bridge/wiki/Attribute-Reference#template)). The token is replaced with the name of the member to which the attribute is applied. 
```
{@} -> [name]
```

* A new `{$}` token to be used within `[Template]` and `[Name]` attributes ([docs](https://github.com/bridgedotnet/Bridge/wiki/Attribute-Reference#template)). The token is replaced with `{this}` concatenated with the name of the member to which the attribute is applied. 
```
{$} -> {this}.{@}
```

Previously, the name of the member was hard coded inside the Template or Name string. Hard coding the names in a string creates potential leaks where defects could be introduced, such as when methods are renamed but updating the attribute value is missed, or simple typos. 

With `{@}` and `{$}` the name of the member is now by reference. 

#### Example

```csharp
// Existing
[Template("{this}.DoSomething({msg})")]
public void DoSomething(string msg) { }

// New with {@}
[Template("{this}.{@}({msg})")]
public void DoSomething(string msg) { }

// New with {$}
[Template("{$}({msg})")]
public void DoSomething(string msg) { }
```

If a `[Convention]` attribute ([docs](https://github.com/bridgedotnet/Bridge/wiki/attribute-reference#convention)) applies to the member, Bridge will automatically apply the `[Convention]` rules to the `{@}` token value. Previously, this was not possible when the member name was hardcoded in the `[Template]` string.

**Comment by michaelcheers** [comment]
@geoffreymcgill, this is an amazing idea!!!

**Comment by geoffreymcgill** [comment]
We'll be adding `{@}` token support to the `[Name]` Attribute as well.
