### ISSUE TITLE
[TypeScript] Module name case is different in declaration and using

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#280]
```C#
using Bridge;

namespace TypeScriptTest
{
    class A
    {
        public void DoSomething(A m)
        {
        }
    }
}
```

bridge.json
```
{
    outputBy: "Project",
    generateTypeScript: "true"
}
```

Error appears: Could not find symbol 'TypeScriptTest'.
In generated d.ts module name is `typeScriptTest` but in method declaration it is `TypeScriptTest`
```
declare module typeScriptTest 
{
    export interface A {
        doSomething(m: TypeScriptTest.A): void;
    }
    export interface AFunc extends Function {
        prototype: A;
        new (): A;
    }
    var A: AFunc;
}
```

**Comment by Mimisss** [comment]
Yes, I can confirm that, too. First letter of module name is lowercase, while every class or interface is declaration is starting with an uppercase letter.

**Comment by Mimisss** [comment]
**Quick fix**
Use the following global configuration:

`"fileNameCasing":  "None"`
