### ISSUE TITLE
DateTime.TryParseExact returns 1am for 13.00 for cultures that don't use AM/PM designators

### ISSUE THREAD

**Issue by wellers** [bridgedotnet/Bridge#2802]
The following code outputs a time of 1am but we'd expect 1pm:

```cs
var culture = new CultureInfo("nb-NO");
culture.DateTimeFormat.TimeSeparator = ".";
DateTime textValue;
if (DateTime.TryParseExact("13.00", $"H{culture.DateTimeFormat.TimeSeparator}mm", culture, out textValue))
{
	// 01/01/1900 01:00:00
	Console.WriteLine(textValue.ToString());
}
```

The nearest equiv we can run in C# requires `DateTimeStyles` to be passed, but correctly returns 1pm (and also uses todays date instead of 01/01/1900?):

```cs
var culture = new CultureInfo("nb-NO");
culture.DateTimeFormat.TimeSeparator = ".";
DateTime textValue;
if (DateTime.TryParseExact("13.00", $"H{culture.DateTimeFormat.TimeSeparator}mm", culture, DateTimeStyles.None, out textValue))
{
	// 6/14/2017 1:00:00 PM
	Console.WriteLine(textValue.ToString());
}
```

**Comment by wellers** [comment]
I have changed the title of this case as I have found the same issue occurs in other cultures such as "es-ES". The issue seems to only occur for cultures that don't use AM/PM designators.

**Comment by DanTup** [comment]
Here's a much simpler repro:

```cs
Assert.Equal(13, DateTime.Parse("13:00", new CultureInfo("en-GB")).Hour); // Pass
Assert.Equal(13, DateTime.Parse("13:00", new CultureInfo("nb-NO")).Hour); // Fail: Expected 13, actual 1
Assert.Equal(13, DateTime.Parse("13:00", new CultureInfo("es-ES")).Hour); // Fail: Expected 13, actual 1
```

This seems to affect at least Spanish and Norwegian (which are both cultures we require!).

**Comment by DanTup** [comment]
And this repro shows that the AM/PM is being reversed:

```cs
Assert.Equal(13, DateTime.Parse("13:00", new CultureInfo("nb-NO")).Hour); // Fail: Expected 13, actual 1
Assert.Equal(1, DateTime.Parse("01:00", new CultureInfo("nb-NO")).Hour); // Fail: Expected 1, actual 13
```

Could the empty string as the `amDesignator` be confusing things?

![Time](https://user-images.githubusercontent.com/1078012/27794458-2b93d19a-5ffa-11e7-8a60-f02d33801e8e.jpg)

**Comment by LeonidVeriga** [comment]
@DanTup, it appeared we had two issues:
1. Locales without AM/PM designators handled incorrectly
2. Some locales has incorrect AM/PM designators 
   * like **nb-NO** - https://dotnetfiddle.net/CBvr6R
3. `DateTime.Parse("13:00", culture)` throws exception for locales having `DateTimeFormat.TimeSeparator != ":"`
   * https://deck.net/33f07f0748067da5c8ff26dad0cb8efd
   * https://dotnetfiddle.net/Mepy8u
