### ISSUE TITLE
Custom variable name for an imported module

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#2806]
Currently Bridge outputs the following JavaScript when a module was imported:

https://deck.net/1103fc5ce7bacf61ed2a123180877cee
```js
require(["Module1"], function (Module1) {
   // ...
}
```
**Module1** in the sample above was mentioned two times:

- `["Module1"]` - as an actual name of the module. The loader will look up the module by this name.
- `function (Module1)` - as a function parameter (or an alias) to be representing the module in the current context.

In some cases it's worth having an ability to specify a custom name for the module alias. A good example is when Bridge loads a UMD module that can be loaded as a regular module or as just a script. Let's review those two cases for a simple UMD module described with the next TypeScript declaration:

**Module1.d.ts**
```ts
namespace Module1 {
     class Class1 {
     }
}
export = Module1;
export as namespace GlobalModule1;
```

## UMD module loaded as a script

When a UMD module was loaded as a script, entities of that module should be accessed through a global variable. To do that, some additional Bridge settings are required:

**Consumer - bridge.json**
```json
"loader": {
  "manualLoading": "true",
  "skipManualVariables": "true"
}
```
Below are a fragment of C# code that consumes the module, and the expected JavaScript output where **Class1** is accessed through a global variable **GlobalModule1**

**Consumer.cs**
```cs
var c = new Module1.Class1();
```
**Consumer.js**
```js
var c = new GlobalModule1.Class1();
```

## UMD module loaded as a module

When a UMD module was loaded as a regular module, Bridge wraps **Consumer** with **require** function. In this case **Class1** should be accessed through the argument **Module1**.
```js
require(["Module1"], function (Module1) {
    var c = new Module1.Class1();
}
```

## Proposal

The samples above have demonstrated an issue - the same entity of the same module should be emitted as different pieces of JavaScript code:
-  `GlobalModule1.Class1`
-  `Module1.Class1`

`[Template]` attribute can be used to get the needed output, but again, only one of the scenarios  (at a time) would be supported. The idea of the proposal is to allow renaming a module variable (alias) in order to make it the same as the global variable, thus for the case **UMD loaded as a module** we would have:
```js
require(["Module1"], function (GlobalModule1) {
    var c = new GlobalModule1.Class1();  // Pay attention that now outputs the same, 
                                         // whereas the contexts are different. 
                                         // Here 'GlobalModule1' is just the module alias,
                                         // not the global variable
}
```

The described proposal can be implemented as an optional parameter/property for **ModuleAttribute**.

**Comment by geoffreymcgill** [comment]
For the scenario you outline above, what would be the value passed to ModuleAttribute?

**Comment by geoffreymcgill** [comment]
Would something like the following be helpful?

```csharp
[Module(ExportAsNamespace = "GlobalModule1")]
public class Module1
{
}
```

The JavaScript with and without `ExportAsNamespace` would be:

```js
// Without ExportAsNamespace
require(["Module1"], function (Module1) {
    var c = new Module1.Class1();
}

// With ExportAsNamespace
require(["Module1"], function (GlobalModule1) {
    var c = new GlobalModule1.Class1();
}
```

**Comment by AndreyChechel** [comment]
Yes, almost like that. We'd still have to specify the original module name, so the module declaration would look like:
```cs
[Module("Module1", ExportAsNamespace = "GlobalModule1")]
// ...
```

**Comment by geoffreymcgill** [comment]
Better to pass Module name in that scenario by setting the property:

```
[Module(Name = "Module1", ExportAsNamespace = "GlobalModule1")]
```
