### ISSUE TITLE
Proposal: [Skip] Attribute

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2807]
Any calls for methods with `[Skip]` attribute applied would not be output to JavaScript.

We're not sure if this attribute would be useful, but documenting the feature request here to encourage further discussion. 

#### Example

https://deck.net/0f47e9ed37bd2f28fec01f3f4bd27103

```csharp
public class Program
{
    public static void Main()
    {
        var p = new Person();
        
        p.DoSomething();
    }
}

public class Person
{
    // If [Skip] is added, any calls
    // to DoSomething will be skipped
    // [Skip]
    public void DoSomething()
    {
        Console.WriteLine("Skipped");
    }
}
```

```js
// Without [Skip]
Bridge.define("Demo.Program", {
    main: function Main () {
        var p = new Demo.Person();

        p.DoSomething();
    }
});

// With [Skip]
Bridge.define("Demo.Program", {
    main: function Main () {
        var p = new Demo.Person();
    }
});
```

### Questions?

* [ ] What if Method has a return value?
* [ ] Would it be better to use `#if` compiler statements?

**Comment by michaelcheers** [comment]
@geoffreymcgill, an intresting idea might be having the Skip attribute with a default value to return of a function.

```csharp
[Skip(true)]
public extern bool TrueValue();
```

**Comment by michaelcheers** [comment]
### See also

* #887

**Comment by geoffreymcgill** [comment]
Seems like the answer here is to use the `[Conditional("SOME_CONDITION")]` attribute. 

The `[Conditonal]` attribute can only be applied to `void` Methods. Applying to a Method with a return type is not permitted. 

The following sample demonstrates a simple scenario of applying the attribute which instructs the Bridge compiler to skip emitting the method call. 

https://deck.net/ad866e77621ee1896cd972fbcf9c5b04

```csharp
public class Program
{
    public static void Main()
    {
        var p = new Person();
        
        p.DoSomething();
        
    }
}

public class Person
{
	[Conditional("SKIP_ALWAYS")]
    public void DoSomething()
    {
        Console.WriteLine("Skipped");
    }
}
```
