### ISSUE TITLE
What's the goal with backwards compatibility?

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#2810]
I just realized that there a lot of changes that would break old code and was wondering if there were any rules about [backward compatibility](https://github.com/bridgedotnet/Bridge/labels/breaking-change).

**Comment by geoffreymcgill** [comment]
Any Breaking Changes are to be introduced in Major releases only, following the [SemVer](http://semver.org/) policies.

```
1. MAJOR version when you make incompatible API changes,
2. MINOR version when you add functionality in a backwards-compatible manner, and
3. PATCH version when you make backwards-compatible bug fixes.
```

**Comment by michaelcheers** [comment]
@geoffreymcgill, So like 15.0 and 16.0 could be incompatible but not 16.0 and 16.1, OK, thanks for the explanation.
