### ISSUE TITLE
Improve async source maps.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#2812]
For me, async is the really good thing about source maps but in some cases it doesn't seem to work properly in [this async sample](https://dev.deck.net/c0b39126e1f156c700378a605fec46bb). If you put a breakpoint on the first line of Main and try to step over it, it steps over the whole function.

**Comment by geoffreymcgill** [comment]
Thanks for the report. We will investigate.

**Comment by geoffreymcgill** [comment]
Source map support within the browser developer tools is managed by the browser vendors, and in general, source maps are just buggy. For the most part, they do work, but there are scenarios where they don't. 

Over time we will do our best to refine what we can in Bridge to improve the source map rendering in the browser developer tools.
