### ISSUE TITLE
Uri.TryCreate and other static methods are missing.

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#2824]
There are some static methods in Uri class. They allow to check validity of URI and some other actions.
For example TryCreate is single way to create URI with validation of user input. It also allows us to validate if path is absolute.

These methods are not available in Bridge.Net for now:
https://deck.net/cd0454cdef7a6c57acbeb993eb1cde03

Do you have plans to implement it?

**Comment by michaelcheers** [comment]
Duplicate of #2185, fixed in #2813.

**Comment by hardhub** [comment]
Strange it is not available in beta2...

**Comment by michaelcheers** [comment]
@hardhub, the pull request has not been merged yet.
