### ISSUE TITLE
Array $set seems to be pointlessly cloning the input indexes (which makes it slow)

### ISSUE THREAD

**Issue by Tilps** [bridgedotnet/Bridge#2830]
Doing some more performance profiling for TwistNTurn - I see that $set in Array.js is calling slice on its input indicies.  This causes an allocation while just trying to set a value in an array.  My javascript skills are weak, but the slice call does appear pointless at first glance...
I've tried removing it locally to good effect.

**Comment by michaelcheers** [comment]
@Tilps, Can you give a line number for this and a reference to the file as a link?

**Comment by Tilps** [comment]
https://github.com/bridgedotnet/Bridge/blob/master/Bridge/Resources/Array.js#L59

**Comment by michaelcheers** [comment]
@Tilps, can you give a C# sample using that function

**Comment by michaelcheers** [comment]
@Tilps, I think it is unnecessary and that you are right.

**Comment by Tilps** [comment]
TwistNTurn is committed to github so I can easily point you at my source - https://github.com/Tilps/TwistNTurn/blob/master/TwistNTurnBridge/Mesh.cs#L867 is one of the many lines which generates a call to the $set implementation. (Which gets made a member method called set.)

**Comment by michaelcheers** [comment]
@Tilps, it does not look like it could have been written by accident, so I do not know what to think.

**Comment by geoffreymcgill** [comment]
Thanks for pointing out the issue. We'll take a look.
