### ISSUE TITLE
Objects don't serialise with all properties intact if properties share the same reference

### ISSUE THREAD

**Issue by Porl91** [bridgedotnet/Bridge#2846]
If you have a class with more than one property and they share a single reference between them, the properties with repeated references aren't emitted in the JSON output.

### Steps To Reproduce

https://deck.net/e67d70e3634a181dac3c0cbf845e04c0

Here I have a class `ClassWithMissingProperty` with `Prop1` and `Prop2` as properties that are identical in definition, apart from name. I've new'd up one object and passed this to the `ClassWithMissingProperty` constructor and called `JsonConvert.SerializeObject` on it directly.

The javascript looks like the following:

```js
{"$type":"ClassWithMissingProperty, Demo","Prop1":{"$type":"System.Object, mscorlib"}}
```

Note that `Prop2` is missing. What I would expect is:

```js
{"$type":"ClassWithMissingProperty, Demo","Prop1":{"$type":"System.Object, mscorlib"},"Prop2":{"$type":"System.Object, mscorlib"}}
```

I've tried this with more complicated classes and it still produces the problem, so I don't believe this is just because I'm using the base object class, which I suspect have no serializable properties. This example is just to demonstrate that the `Prop2` itself is missing.

**Comment by vladsch** [comment]
It is Bridge.Newtonsoft.Json issue. This issue will be closed.
Reference: https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/issues/10

**Comment by LeonidVeriga** [comment]
@Porl91, bridgedotnet/Bridge.Newtonsoft.Json#10 has been fixed in **Bridge.Newtonsoft.Json** repo.
