### ISSUE TITLE
[bridge.json] afterBuild config accepts nothing but absolute paths with double slashes 

### ISSUE THREAD

**Issue by Mimisss** [bridgedotnet/Bridge#285]
For example, 

`"afterBuild" : "Bridge/build/deploy.bat"`

causes error:

`exception level: 0 - Error: Unable to run afterBuild event command: The specified file 'Bridge\build\deploy.bat' couldn't be found.`

**Comment by fabriciomurta** [comment]
Couldn't reproduce the issue. Another commits might have fixed this already since the error was reported.
