### ISSUE TITLE
Add deck.net support for Assert.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#2850]
This would be useful for reporting bugs to be able to provide unit tests on deck.net.

**Comment by geoffreymcgill** [comment]
Hi @michaelcheers – Thanks for the feature request. Could you re-post this issue in the Deck.NET [Issues repo](https://github.com/deckdotnet/Deck.NET/issues). It will be better to track within the Deck repo.

https://github.com/deckdotnet/Deck.NET/issues

**Comment by michaelcheers** [comment]
@geoffreymcgill, created as deckdotnet/Deck.NET#21
