### ISSUE TITLE
New console config for bridge.json

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2851]
A **bridge.json** `console` config to modify the functionality of the **Bridge Console**.

Name | Type | Description
---- | ---- | ----
enabled | bool | Set to `true` to include **Bridge Console**. Default is `false`.

#### Example

```js
{
  "console": {
    "enabled": true
  }
}
```

## See Also

* #1994
* https://forums.bridge.net/forum/bridge-net-pro/bugs/4434-combinescripts-and-resources-bridge-console-js-extract-false-doesn-t-exclude
* https://forums.bridge.net/forum/general/feature-requests/2781-open-1994-option-to-disable-bridge-console-does-this-already-exist

**Comment by michaelcheers** [comment]
@geoffreymcgill, wouldn't this be better as an attribute?

**Comment by DanTup** [comment]
I think it's best in `bridge.json`; it's the sort of thing you almost certainly want disabled in a production app (it *never* makes sense for that console to pop up in front of an end user) and swapping config files for dev/prod builds seems more convenient than making code changes.

**Comment by geoffreymcgill** [comment]
@DanTup – Just in case you didn't know, you can create separate **bridge.json** config files for different build modes:

https://github.com/bridgedotnet/Bridge/wiki/global-configuration#custom-bridgejson-files

Enables you to create **bridge.Debug.json** and **bridge.Release.json** files, both of which could inherit from a common **bridge.json** file with shared configs. 

Hope this helps.

**Comment by DanTup** [comment]
> Just in case you didn't know, you can create separate bridge.json config files for different build modes:

I didn't know this; I'm sure this will come in useful! 👍

**Comment by LeonidVeriga** [comment]
The console config option has been changed 
```json
  "console": {
    "disabled": false
  }
```
->
```json
  "console": {
    "enabled": false
  }
```
