### ISSUE TITLE
Error while compiling with sourceMap enabled in 16-beta3

### ISSUE THREAD

**Issue by ddaspit** [bridgedotnet/Bridge#2853]
I receive the following error when compiling with sourceMap enabled:
```
error : 2017-06-23T13:08:02:462 	Error		Bridge.Translator.TranslatorException: Could not get ParsedSourceFile for SourceMap. Exception: System.InvalidOperationException: Sequence contains no matching element
error :    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
error :    at Bridge.Translator.Translator.<>c__DisplayClass268_0.<GenerateSourceMap>b__0(String sourceRelativePath); projectPath: C:\develop\BridgeTest\src\BridgeTest.JS; sourceRelativePath: red\SharedClass.cs; path: C:\develop\BridgeTest\src\BridgeTest.JS\red\SharedClass.cs.
error :    at Bridge.Translator.Translator.<>c__DisplayClass268_0.<GenerateSourceMap>b__0(String sourceRelativePath)
error :    at Bridge.Translator.SourceMapGenerator.Generate(String scriptFileName, String basePath, String& content, Action`1 beforeGenerate, Func`2 sourceContent, String[] names, IList`1 sourceFiles, Nullable`1 forceEols, ILogger logger)
error :    at Bridge.Translator.Translator.GenerateSourceMap(String fileName, String content, Action`1 before)
error :    at Bridge.Translator.Translator.Save(String projectOutputPath, String defaultFileName)
error :    at Bridge.Translator.TranslatorProcessor.PostProcess()
error :    at Bridge.Build.BridgeCompilerTask.Execute()
```
The project I was compiling has a reference to a shared project. According to the stack trace, the sourceRelativePath variable has an incorrect path to a class file in the shared project. It is "C:\develop\BridgeTest\src\BridgeTest.JS\red\SharedClass.cs", but it should be "C:\develop\BridgeTest\src\BridgeTest.Shared\SharedClass.cs".
### Steps To Reproduce

1. Create a Bridge.NET Class Library project.
2. Create a Shared Project.
3. Add some code to the shared project.
4. Add a reference to the shared project from the Bridge.NET project.
5. Build the Bridge.NET project.

**Comment by vladsch** [comment]
Can you provide a link to public git repository with test project which reproduces the issue?

**Comment by ddaspit** [comment]
I attached a simple VS2017 solution that reproduces the problem. [BridgeTest.zip](https://github.com/bridgedotnet/Bridge/files/1099421/BridgeTest.zip)
