### ISSUE TITLE
OuterHtml readonly

### ISSUE THREAD

**Issue by ericpreisig** [bridgedotnet/Bridge#2854]
Hello,
I have noticed that OuterHTML property is read-only, is it normal?
Because in plain javascript I can write something like : "element.outerHTML='hello'"

Thank you

**Comment by michaelcheers** [comment]
# See also

* #318

Here is the [specification](https://msdn.microsoft.com/en-us/library/ms534311(v=vs.85).aspx) and [here](2857) is a pull request fixing the issue.
