### ISSUE TITLE
[bridge.json] afterBuild does not work

### ISSUE THREAD

**Issue by Mimisss** [bridgedotnet/Bridge#286]
When a batch file (`.bat`) is set as the value, it is not executed properly. Maybe, somehow related to #285 ?

**Comment by fabriciomurta** [comment]
Couldn't reproduce the issue.

Created two .bat files into project's `Bridge/build` directory:
clean.bat
```
@echo off
echo %DATE% %TIME%: Clean script run. >> log.txt
```
deploy.bat
```
@echo off
echo %DATE% %TIME%: Deploy script run. >> log.txt
```

Added the following lines on `bridge.json`:
```
    beforeBuild: "Bridge/build/clean.bat",
    afterBuild: "Bridge/build/deploy.bat"
```

The result was a `log.txt` file in the project's root (where the `.csproj` file is) containing:
```
09/08/2015  1:07:07,46: Clean script run. 
09/08/2015  1:07:07,53: Deploy script run. 
```

So as the related issue (#285), this might have already been fixed.
