### ISSUE TITLE
Chained-assignment of structs after property getter skips a $clone()

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#2871]
### Steps To Reproduce

https://deck.net/4cc8a491b7c1bf5c040361db565bfefe

### Expected Result

```
false
false
```

### Actual Result

```
true
false
```

**Comment by TriEdgeAI** [comment]
Can you please fix this one asap or give me a hint on how to fix it myself :S

**Comment by geoffreymcgill** [comment]
Setting `[Immutable]` on the Struct will get it working for now, but there is still an issue that needs to be fixed. 

```csharp
[Immutable]
public struct Vector3
{
    public float x;
    public float y;
    public float z;
}
```

**Comment by TriEdgeAI** [comment]
Won't work. It needs to be mutable. A workaround won't suffice in this case :( Any tips on which files/methods I need to look at in order to give you a PR with a fix?

**Comment by LeonidVeriga** [comment]
See code like [AssigmentBlock.cs L436](https://github.com/bridgedotnet/Bridge/blob/master/Compiler/Translator/Emitter/Blocks/AssignmentBlock.cs#L436) - `JS.Funcs.CLONE` is used for structs and nullables.
