### ISSUE TITLE
Chaining assigment with the same variable gets illegal JS

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#2872]
### Steps To Reproduce

https://dev.deck.net/8fc6f5bb353fdf36ce092f2dc1b43c43

```c#
public class Program
{
    public static void Main()
    {
        TestType o = o = new TestType();
        
        Console.WriteLine(o);
    }
}

class TestType
{
    
}
```

### Actual Result
Illegal JavaScript code generated causing:
> SyntaxError: Unexpected identifier
```js
 var o = ($t = new Demo.TestType(), [UnknownIdentifierResolveResult o] = $t, $t);
```

**Comment by fabriciomurta** [comment]
Looks good now! Implemented and will make it to the next Bridge release (see attached version milestone).
