### ISSUE TITLE
Convert.ToString(new object()) shows Object not System.Object.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#2887]
Convert.ToString(new object()) shows Object not System.Object.

### Steps To Reproduce

https://deck.net/fd3e53dc5a2bd366fd57ce6feb090939/third
https://dotnetfiddle.net/d3y1f1

```c#
public class Program
{
    public static void Main()
    {
        Console.WriteLine(Convert.ToString(new object()) == "System.Object" ? "Passed" : "Failed");
    }
}
```

**Comment by fabriciomurta** [comment]
Pull request #3414 also fixes this.

**Comment by fabriciomurta** [comment]
This issue has just been fixed by the above pull request that's been merged upstream. The fix will make it to the next Bridge release (see attached milestone).

**Comment by fabriciomurta** [comment]
"Passing" on dev.deck.net: https://dev.deck.net/fd3e53dc5a2bd366fd57ce6feb090939/third
