### ISSUE TITLE
Formatting of output JavaScript

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#29]
It might be most actual for jQuery, at least. For example, the following code in the Demo project:

```
var alert = new jQuery("<div>")
    .AddClass("alert alert-info col-md-4")
    .Attr("role", "alert")
    .Attr("style", "display: block; position: relative;")
    .Html(message)
    .AppendTo(Document.Body);
```

produces this JavaScript code:

```
var alert = $("<div>").addClass("alert alert-info col-md-4").attr("role", "alert").attr("style", "display: block; position: relative;").html(message).appendTo(document.body);
```

in one line.

Well, it is not a critical issue for sure, but it would be nice to keep the formatting of C#.

@geoffreymcgill, what do you think?

**Comment by geoffreymcgill** [comment]
Closing this issue as we won't be adding this feature. We may revisit the idea in the future.
