### ISSUE TITLE
StringBuilder indexer should accept an int

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2902]
https://dotnetfiddle.net/NI0z8x

https://deck.net/e30b2fe9c6717475f42c251fa71ad41b

```csharp
using System;
using System.Text;

public class Program
{
    public static void Main()
    {
        StringBuilder sb = new StringBuilder("Test");

        sb[0] = sb[0];
		
        Console.WriteLine(sb[0]);
    }
}
```

**Comment by hardhub** [comment]
Title sounds strange... int.. not string :) Because it accepts string from default object implementation.

https://forums.bridge.net/forum/bridge-net-pro/bugs/4113-open-2902-stringbuilder-indexer-is-wrong

**Comment by michaelcheers** [comment]
@geoffreymcgill, I thought that the indexer hadn't been implemented yet. See #2508.
