### ISSUE TITLE
Invoking IList<T>.this[int] results in a boxed object, which sometimes causes a crash

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#2909]
https://deck.net/b9606b106da8ea41d40d9062db847c1a

**Comment by TriEdgeAI** [comment]
I think this issue is resolved. At least there doesn't appear to be a crash in the deck.net example anymore. Close?

**Comment by vladsch** [comment]
Yes, it is resolved, now generic version of IList should not produce boxed result.
