### ISSUE TITLE
Remove MarkElement class

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2914]
The **MarkElement** class should not have been added to the **Bridge.Html5** namespace as the class does not exist within the native JavaScript API. 

## See Also

* [2911] Html generic classes should have [IgnoreGeneric] #2912
* MarkElement is missing #1241

**Comment by michaelcheers** [comment]
@geoffreymcgill, MarkElement is useful because of its constructor also shouldn't it be called HTMLMarkElement?

**Comment by geoffreymcgill** [comment]
There is no **HTMLMarkElement** in JavaScript., just like there is no **HTMLH1Element**.
