### ISSUE TITLE
[TypeScript] Optional parameter becomes mandatory

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#292]
```C#
using Bridge;

namespace Demo
{
    public class App
    {
        public DoSomething(int i = 5)
        {
        }
    }
}
```

Generated d.ts:
```JavaScript
    export interface App {
        doSomething(i: Number): void;
    }
```

Expected d.ts:
```JavaScript
    export interface App {
        doSomething(i?: Number): void;
    }
```

**Comment by vladsch** [comment]
At this moment, Bridge generates javascript which doesn't have checks for optional parameters. 
The js method looks like
`doSomething: function (i) { }`

Optional paramaters are inserted by Bridge to invocation declaration during translation. May be we need to generate js code to check that parameter has no value (check during runtime)

I will close this issue and need to create an issue to replace current functionality for optional parameters (generates value inside method body instead adding it invocation during translation)

**Comment by LeonidVeriga** [comment]
Yes, TypeScript generates htis kind of check:
```JavsScript
function DoSomething (i: number = 5): void  {
}
```
```JavsScript
function DoSomething(i) {
    if (typeof i === "undefined") { i = 5; }
}
```

Let's keep this issue open because generated d.ts should have that parameter optional and after implementing generating js code to check parameters we would still need to implement TypeScript syntax for this case.

**Comment by fabriciomurta** [comment]
If this is implemented it will fix the issue with the whole CanvasRenderingContext2D which relies on default values.  (issue #411)

**Comment by DaniilVeriga** [comment]
A related forum thread.
http://forums.bridge.net/forum/bridge-net-pro/bugs/680-optional-arguments-not-in-js-output

**Comment by DaniilVeriga** [comment]
Created an individual issue for pure JavaScript (not TypeScript) - #477.

**Comment by vladsch** [comment]
It is implemented already
