### ISSUE TITLE
Char.IsUpper Method (String, Int32) overload is missing

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2926]
The Bridge **System.Char** implementation is missing the **Char.IsUpper** static Method overload.

https://github.com/bridgedotnet/Bridge/blob/master/Bridge/System/Char.cs#L48-L49

https://github.com/bridgedotnet/Bridge/blob/master/Bridge/Resources/Core.js#L1437-L1441

https://docs.microsoft.com/en-us/dotnet/api/system.char.isupper?view=netframework-4.7#System_Char_IsUpper_System_String_System_Int32_

https://github.com/bridgedotnet/Bridge/blob/d39b1ada00235d42d7df5f7ff89458c8d0d4dc67/Bridge/Resources/Core.js#L1437-L1441

https://referencesource.microsoft.com/#mscorlib/system/char.cs,dcc502a91d0927c3

https://github.com/dotnet/coreclr/blob/7c197b63914af560d467e8a95c04177495f160d9/src/mscorlib/shared/System/Char.cs#L843-L863

## TODO

* [x] Implement IsUpper overload
* [x] Revise argument names for all members in **Char.cs** to be the same as native, for example `char s` instead of `char ch`

### Steps To Reproduce

https://deck.net/f9980c8d03da60f37da715c3f330fe27

```c#
public class Program
{
    public static void Main()
    {
    	Console.WriteLine(char.IsUpper("Hello World!", 0));
    }
}
```

### Expected Result

```js
True
```

### Actual Result

```js
Exception is thrown:
No overload for 'IsUpper' takes 2 arguments
```

## See Also

* Implement missing Char Methods #132

**Comment by michaelcheers** [comment]
@geoffreymcgill, IsLower has the same problem and as for a more complete comparison:

```
.ctor() - Bridge only
ConvertFromUtf32(System.Int32) - .NET only
ConvertToUtf32(System.Char, System.Char) - .NET only
ConvertToUtf32(System.String, System.Int32) - .NET only
Format(System.String) - Bridge only
Format(System.String, System.IFormatProvider) - Bridge only
GetNumericValue(System.Char) - .NET only
GetNumericValue(System.String, System.Int32) - .NET only
GetType() - .NET only
GetTypeCode() - .NET only
GetUnicodeCategory(System.Char) - .NET only
GetUnicodeCategory(System.String, System.Int32) - .NET only
ToLower(System.Char, System.Globalization.CultureInfo) - .NET only
ToLowerInvariant(System.Char) - .NET only
ToString(System.Char) - .NET only
ToString(System.IFormatProvider) - .NET only
ToString(System.String) - Bridge only
ToString(System.String, System.IFormatProvider) - Bridge only
ToUpper(System.Char, System.Globalization.CultureInfo) - .NET only
ToUpperInvariant(System.Char) - .NET only
TryParse(System.String, System.Char&) - .NET only
```

**Comment by geoffreymcgill** [comment]
@michaelcheers yes, noticed that as well. Char.cs was very poorly implemented early on in Bridge. I plan on fixing this sometime soon.

I might be able to add `IsLower` later today.
