### ISSUE TITLE
Bridge.Html5.Console.Warn gets transpiled as "console.Warn" with a capital W

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#2936]
Oops.

**Comment by geoffreymcgill** [comment]
I'm assuming you're using the [Bridge.Html5.Console](https://www.nuget.org/packages/bridge.html5.console) package?

If yes, it looks like that package has not been updated to use Bridge 16.0.

Should be an easy fix for us to update the package.

**Comment by TriEdgeAI** [comment]
Is there an alternative to the Bridge.Html5.Console package? Why did you guys decide to keep it separate and not part of the standard Bridge.Html5?

**Comment by geoffreymcgill** [comment]
There's a namespace conflict with **System.Console**, and it's generally not required anyways.

**Comment by LeonidVeriga** [comment]
Created an issue in **Frameworks** repo - https://github.com/bridgedotnet/Frameworks/issues/69
