### ISSUE TITLE
Javascript imprecision causes serious bugs in ints

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#2949]
Javascript imprecision causes serious bugs in ints.

### Steps To Reproduce

https://dev.deck.net/dc52e1a8e05591d1e267219085423b8b/third
https://dotnetfiddle.net/UOxG6B

```c#
public class App
{
    public static void Main()
    {
        int a = int.MaxValue / 3;
        a *= a;
        Console.WriteLine(a == -477218588 ? "Passed" : "Failed");
    }
}
```

**Comment by vladsch** [comment]
I don't think that we can do much with that (only if add own implementation of all arithmetic operations)
I can suggest to use long type for all sensitive calculations
https://dev.deck.net/4603cb41b36318eeac34fdc2394a6787/three

**Comment by michaelcheers** [comment]
@vladsch, it is only multiplication that is the problem, so won't have to override the other operators but you have already overridden divide so I don't think it is such a big strech.

**Comment by michaelcheers** [comment]
@vladsch, looks like you could use asm.js and a fallback for older browsers.

**Comment by michaelcheers** [comment]
@vladsch, actually looks like that is not possible, you cannot request a true integer multiplication.

**Comment by michaelcheers** [comment]
@vladsch, here is a short [jsfiddle](https://jsfiddle.net/xrrqLqzt/1/) that produces the correct answer. I got it from [here](https://stackoverflow.com/questions/6232939/is-there-a-way-to-correctly-multiply-two-32-bit-integers-in-javascript).

**Comment by vladsch** [comment]
Pull request is committed - https://github.com/bridgedotnet/Bridge/pull/2953

I run your test and here is my local result in Chrome
```
Normal: 585 ms
New: 333 ms
```

Bridge uses [Math.imul](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Math/imul) function (or polyfill if it is not defined)

**Comment by michaelcheers** [comment]
@vladsch, why does the mul function check for null, an integer can never be null. If you removed that check, you could use Math.imul directly, which I think would be cleaner.

**Comment by vladsch** [comment]
Because that function is used for nullable integer also

**Comment by michaelcheers** [comment]
@vladsch, for me, this problem still persists. I have updated to beta5. I made sure that `Bridge.Int.mul` exists but it still uses `(a * b) | 0` anyway.

**Comment by vladsch** [comment]
Please provide test sample, i checked your original test case and it works correctly

**Comment by michaelcheers** [comment]
@vladsch, my bad, I messed it up.

**Comment by michaelcheers** [comment]
@vladsch, you have to use an unchecked block, see [this](https://dev.deck.net/11f521d6c1ecdd49c83ae522d2aac642/third) to reproduce my problem.

**Comment by michaelcheers** [comment]
@vladsch, please fix for unchecked and checked.

**Comment by geoffreymcgill** [comment]
@michaelcheers What is the expected result in your sample at https://github.com/bridgedotnet/Bridge/issues/2949#issuecomment-317128648?

Is this still an issue in 16.2.x?

**Comment by michaelcheers** [comment]
@geoffreymcgill, I can confirm it works now.
