### ISSUE TITLE
DateTime.MinValue is not UTC

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#2952]
I suspect this may have the same underlying cause as #2929..

DateTime.MinValue is supposed to be `00:00:00.0000000 UTC, January 1, 0001` however when you serialise it with your computer set in different timezones you get strange results:

```cs
Console.WriteLine(JsonConvert.SerializeObject(DateTime.MinValue));
// London time: 0001-01-01T00:00:00.000Z
// Amsterdam time: "0000-12-31T23:00:00.000Z"
```

This means if you serialise a DateTime.MinValue in Bridge, it'll fail to deserialise later (eg. in .NET) as being an invalid date if you're in a positive time offset (and presumably the wrong value if in a negative offset).

>  Could not convert string to DateTime: 0000-12-31T23:00:00.000Z. Path 'DeliveryDateUtc.Value',

**Comment by geoffreymcgill** [comment]
This has been fixed in branch [Issue2929](https://github.com/bridgedotnet/Bridge/tree/Issue2929) and pull request #2945.

Would be very helpful if you could test the **Issue2929** branch with your apps.

**Comment by DanTup** [comment]
@geoffreymcgill Done some testing of this in the PR branch; all seems to be working fine to me!

**Comment by LeonidVeriga** [comment]
@DanTup, the changes in **DateTime** done in PR #2945 (in **master** already) are being integrated into **Bridge.Newtonsoft.Json** - this Json update is described here https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/pull/20#issue-243528005.
