### ISSUE TITLE
When are you pushing beta 5?

### ISSUE THREAD

**Issue by angelsix** [bridgedotnet/Bridge#2969]
There are a lot of issues with beta4 and json beta 4. I see in source beta5 has been tagged, but nothing is on nuget.org yet?

**Comment by LeonidVeriga** [comment]
Hi @angelsix,

Release of **beta5** is related to the additional scope we (and the community of course) would like to include into **16.0**.

We are planning **16.0.0-beta5** release this week. Please note that we tag a release (i.e. tagging a commit in Github on **master** branch) only after it is on NuGet.

There is our **Bridge** channel on Gitter where you can ask questions as well - https://gitter.im/bridgedotnet/Bridge.

**Comment by geoffreymcgill** [comment]
These types of Questions are best asked in the [forums](https://forums.bridge.net/) or [GItter](https://gitter.im/bridgedotnet/Bridge). Let's keep the Issues for actual Issues.
