### ISSUE TITLE
Template problem with bedmas.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#2973]
Template problem with bedmas from [here](https://github.com/bridgedotnet/Bridge/issues/2963#issuecomment-315589344).

### Steps To Reproduce

https://dev.deck.net/10d69a156c35e2d9171e83c04752838c/third

```c#
public class Program
{
    public static void Main()
    {
        bool Neg = false;
        Console.WriteLine(((R(Neg ? -1 : 1) * 2) == (R2(Neg ? -1 : 1) * 2)) ? "Passed" : "Failed");
    }
    
    [Template("1 + {0}")]
    public static extern int R (int a);
    public static int R2(int a) => a + 1;
}
```

**Comment by vladsch** [comment]
Bridge doesn't parse template's javascript to understand if a code is valid. So, at this moment, it is your responsibility to provide the correct template. You have to wrap `{0}` by braces.

**Comment by geoffreymcgill** [comment]
For now, we will not be parsing the Template values. We may be able to implement this functionality in a future release, but for now, I'm closing the issue.

**Comment by michaelcheers** [comment]
@geoffreymcgill, couldn't just wrap every template with parentheses?
