### ISSUE TITLE
Equality checking does not work properly for values returned from indexer of IList<T>

### ISSUE THREAD

**Issue by ddaspit** [bridgedotnet/Bridge#2983]
Equality checking doesn't seem to work properly for values returned from the indexer of an IList<T> object. This seems to occur with value types, such as int, bool, etc. I think this might be related to issue #2909.

### Steps To Reproduce

https://deck.net/ad157a75721efe6c3a242cb8cc12aff4

```c#
public class Program
{
    public static void Main()
    {
        IList<int> list = new List<int> {0};
        int num = list[0];
        Console.WriteLine(num);
        if (num == 0)
            Console.WriteLine("Good");
        else
            Console.WriteLine("Bad");
    }
}
```

### Expected Result

The first item in the list is equal to 0, so "Good" should be printed out to the console.

### Actual Result

The equality checking doesn't seem to work properly, so "Bad" is printed instead.

**Comment by michaelcheers** [comment]
### See Also

* #1357
