### ISSUE TITLE
CultureInfo.CurrentCulture returning invariant culture

### ISSUE THREAD

**Issue by FasettoAndrew** [bridgedotnet/Bridge#2996]
When using the CultureInfo.CurrentCulture property to determine what culture the current thread is using it allways returns invariant culture.

In the follow code I have used on deck.net and in our own application, I have seen the same results across 2 different PC's, both using a en-GB (UK) culture version of windows.

### Steps To Reproduce

https://deck.net/352d4cca4c39dbf0618060c633740121

```c#
public class Program
{
    public static void Main()
    {        
        var dt = DateTime.Now;
        
        Console.WriteLine("Original DateTime: " + dt);
        Console.WriteLine("ToLocaleString: " + dt.ToLocaleString()); 
        Console.WriteLine("ToLocalTime: " + dt.ToLocalTime());
        Console.WriteLine("ToStringWithCulture: " + dt.ToString("MM/dd/yyyy", CultureInfo.CurrentCulture));
        Console.WriteLine("ToShortDate: " + dt.ToShortDateString());
                
        var culture = CultureInfo.CurrentCulture;
        
        Console.WriteLine(culture);
    }
}
```

### Expected Result
Note: I'm not 100% sure that ToLocalTime should affect the date formating of the date time, but I have changed here to match others.
```js
Original DateTime: 07/26/2017 09:06:23
ToLocaleString: 26/07/2017, 09:06:23
ToLocalTime: 26/07/2017 09:06:23
ToStringWithCulture: 26/07/2017
ToShortDate: 26/07/2017
{
  "name": "en-GB",
  "englishName": "English (United Kingdom)",
  "nativeName": "English (United Kingdom)".
...
```
### Actual Result

```js
Original DateTime: 07/26/2017 09:06:23
ToLocaleString: 26/07/2017, 09:06:23
ToLocalTime: 07/26/2017 09:06:23
ToStringWithCulture: 07/26/2017
ToShortDate: 07/26/2017
{
  "name": "iv",
  "englishName": "Invariant Language (Invariant Country)",
  "nativeName": "Invariant Language (Invariant Country)",
...
```

**Comment by FasettoAndrew** [comment]
As an update to this, CultureInfo.GetCultures() is only returning a single culture:

https://deck.net/629e67c1d6a0375f6c1d44522188fd86

**Comment by vladsch** [comment]
Please use `locales` config property to attach required locales
https://github.com/bridgedotnet/Bridge/wiki/global-configuration#locales

**Comment by vladsch** [comment]
Discussion about current locale
https://forums.bridge.net/forum/community/help/4241-default-cultureinfo

**Comment by FasettoAndrew** [comment]
Cool cheers :)
