### ISSUE TITLE
Add Delegate counterparts of Action and Func type properties

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#30]
For example, there is the following property in the Bridge.NET\Core\Html5\WindowInstance.cs

```
public Action<Event> OnFocus;
```

It doesn't allow to set an arbitrary handler, for example, an Action without parameters. So, it might be worth to have a Delegate counterpart on the onFocus property, like:

```
public Delegate OnFocusDelegate;
```

We might be able to come up with a better name.

Slated for the future.

**Comment by michaelcheers** [comment]
## See Also
 #2767.

**Comment by geoffreymcgill** [comment]
Closing this issue as we will not be implementing this feature. All Html5 functionality is moving to [Retyped](https://github.com/Retyped/Retyped).
