### ISSUE TITLE
Problem with 1.60 and VS2012 Pro SP3 (Windows 7x64u)

### ISSUE THREAD

**Issue by g40** [bridgedotnet/Bridge#301]
Hello.

Installed using the ```bridge.net.1.6.0.vsix``` file apparently without any issues*. Open VS2012 and create a new Bridge.net project with the provided template. During compilation I get the problem show below:

Nuget claims installation is completely up to date. Any thoughts?

* P.S. The VSIX installer did not find my VS2013 Pro installation which I'd expect it too. Is this a known problem?

P.P.S. Really good to see this and Saltarelle going somewhere. Used the latter to great effect earlier this year. Looking to repeat same! *Thanks* to all.

```
NuGet package restore started.
Restoring NuGet packages for solution R:\src\lucit\Bridge2\Bridge2.sln.
NuGet Package restored finished for solution R:\src\lucit\Bridge2\Bridge2.sln.
Restoring NuGet packages for project Bridge2.
Skipping NuGet package Bridge 1.6.0 since it is already installed.
NuGet Package restored finished for project Bridge2.
All packages are already installed and there is nothing to restore.
NuGet package restore finished.
1>------ Build started: Project: Bridge2, Configuration: Debug Any CPU ------
1>Build started 11/07/2015 18:20:55.
1>R:\src\lucit\Bridge2\Bridge2.csproj(65,5): error : This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Bridge.1.6.0\build\Bridge.targets.
1>
1>Build FAILED.
1>
1>Time Elapsed 00:00:00.00
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by geoffreymcgill** [comment]
Hi @g40,

Thanks for this report. We are investigating.

We will be releasing v1.7.0 on Monday, so we will focus on reproducing this NuGet issue and fix before 1.7.0 is published.

**Comment by geoffreymcgill** [comment]
@DaniilVeriga Can you investigate why the VS2013 install was not found.
> The VSIX installer did not find my VS2013 Pro installation which I'd expect it too. Is this a known problem?

**Comment by fabriciomurta** [comment]
Just tried here, and I could install and build on Visual Studio 2013. I don't have VS2012 here to test though.

**Comment by g40** [comment]
Just tried the same on a Windows 8.1x64 machine with only VS2013 SP4 Pro installed. Installation seems OK but encountered a similar problem at build. No sign of the ```failure.txt``` file either.

```
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
NuGet package restore canceled.
1>------ Build started: Project: bridge, Configuration: Debug Any CPU ------
1>  bridge -> R:\src\dotnet\bridge\bridge\bin\Debug\bridge.dll
1>MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in the temporary files directory named MSBuild_*.failure.txt.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by fabriciomurta** [comment]
Alright, don't use 'Bridge' as the project name. It will conflict with Bridge.* namespace. In the other example I noticed you used `Bridge2`, which would not be a problem. In this case, you used `Bridge` as both project and solution, and that's what broke it.

Can you try again with another project name on the win8 machine?

**Comment by fabriciomurta** [comment]
Output I get from VS2013 on fresh project creation is:
```
1>------ Build started: Project: Bridge2, Configuration: Debug Any CPU ------
1>  Bridge2 -> A:\devel\Object.NET\projects\Bridge2\Bridge2\bin\Debug\Bridge2.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

I'm not really sure why your VS tries to restore NuGet packages. As you can see, my output log has no NuGet package restore attempt. This is the output of creating an empty bridge project.
Steps:
1. download and install bridge 1.6.0 .vsix from VS Gallery
    during install, ensure Visual Studio 2013 box is checked
2. Open visual studio, File > New > Project > Search Bridge > Bridge.NET Empty Application
3. Name it Bridge2 (ensure local directory does not exist before proceeding) -- keeping the suggested default name is a safe bet
4. Right-click the project on the Solution Explorer > Add > New file > Code File (blank .cs file)
5. Add this content to the file: ```
using Bridge;
using Bridge.Html5;
namespace Bridge2
{
 class ClassBridge2
 {
  public static void main() {
   Console.Log("Hello World");
  }
 }
}
```
6. Build (F6).

**Comment by DaniilVeriga** [comment]
@g40, just checked VSIX with my VS 2013 and it finds the installation for that. Also asked one of my colleague to check and it is also okay for him. I am pretty sure most of Bridge + Visual Studio developers use VS 2013 and this issue has not reported before. Well, I don't mean that there is no issue, I just feel it is probably related to a specific Visual Studio (and, maybe, Windows) setup that you have on your machine. Our Bridge VSIX doesn't have any specific requirements to Visual Studio or Windows, but may you, please, ensure all the updates is installed for Visual Studio? Maybe, there was a bug in VS at some point and it has been fixed already.

**Comment by g40** [comment]
Hi Daniil. It's not a showstopper at the moment. If you are going to have a new release tomorrow I will try that.

**Comment by g40** [comment]
@fabriciomurta. Fair point. With a project named T1 and using VS2013SP4 on Windows 8.1 I get the following. Note that NuGet updates *are* enabled. There is nothing at all unusual about the installation either.

```
Error	1	This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Bridge.1.6.0\build\Bridge.targets.	R:\src\dotnet\t1\t1.csproj	65	5	t1
Warning	2	The referenced component 'Bridge.Html5' could not be found. 	t1
Warning	3	The referenced component 'Bridge' could not be found. 	t1
```

**Comment by g40** [comment]
Here's a snap of a completely vanilla default project:

![image](https://cloud.githubusercontent.com/assets/812250/8639313/21901b8c-28ce-11e5-955f-9ef91be90f05.png)

**Comment by fabriciomurta** [comment]
Strange, your vanilla default project don't really look like a vanilla default project to me...
Might be something on VS2012 but, look how it looks when I create a project following the steps in the [comment above](https://github.com/bridgedotnet/Bridge/issues/301#issuecomment-120665924):
![vanilla_solution](https://cloud.githubusercontent.com/assets/10730372/8639973/3896fae0-28be-11e5-8c62-65c9515ad633.png)

The only additional thing here is the code file (named after 'Class1.cs'). Your scenario looks very different if using the .vsix installation and project templates.

**Comment by fabriciomurta** [comment]
Additionally, using the `.vsix`'s templates, there is absolutely no NuGet package reference nor packages directory in the `solution`'s root. Could that be possible that you are mixing the two possible Bridge.NET installation approaches together, that is:
1. installing Bridge using `.vsix` and using the project templates
2. installing Bridge using the NuGet packages

Those two are independent installation scenarios, one does not require the other, they're mutually exclusive.

You can, for example, install the `.vsix` and create a project using the NuGet packages -- but you will not be using whatever is contained in the `.vsix`.

Sorry if I sounded rude, it was not the intent, I am just trying to guess what could lead you to a scenario like what you printed if you were using `.VSIX` installation.

**Comment by DaniilVeriga** [comment]
@g40's vanilla project looks correct to me.

@g40, please ensure that the "Create directory for solution" checkbox is ticked when you create the project. If it is not, then it is probably the reason of the problem that you ran into.

**Comment by g40** [comment]
@fabriciomurta. At last. Success with VS2013. Thanks for the input here.

One final gremlin remains:

```
1>------ Clean started: Project: T2, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(4438,5): warning MSB3061: Unable to delete file "R:\src\dotnet\T2\T2\bin\Debug\Bridge.dll". Access to the path 'R:\src\dotnet\T2\T2\bin\Debug\Bridge.dll' is denied.
========== Clean: 1 succeeded, 0 failed, 0 skipped ==========
```

**Comment by g40** [comment]
OK. Back to VS2012. Default project named T1 with 'create directory for solution' checked'. The default configuration fails as the build option is unchecked. See snap below. 
```
1>------ Skipped Build: Project: T1, Configuration: Debug Any CPU ------
1>Project not selected to build for this solution configuration 
========== Build: 0 succeeded or up-to-date, 0 failed, 1 skipped ==========
```


![image](https://cloud.githubusercontent.com/assets/812250/8647387/73ed4d2e-294f-11e5-999c-896a0d133ea9.png)

**Comment by g40** [comment]
@fabriciomurta Yes, completely get the mutually exclusive installation options. Here's a snap I managed to get though on my VS2012 installation which was done purely via the VSIX file. The only change here was to tick the checkbox in the Configuration Manager dialog and to then build ...

![image](https://cloud.githubusercontent.com/assets/812250/8647479/3541289c-2950-11e5-9b51-9306898b1893.png)

**Comment by DaniilVeriga** [comment]
I could not reproduce the problem with VS 2012. The build option is checked to me and it builds well. Hmm, what could be the reason why the build option is unchecked for you? I don't quite have any ideas at the moment.

**Comment by g40** [comment]
Hi Daniil. It's no showstopper either. Just adding it for completeness OK :) Let me know when 1.7 is released and I'll try that out on both installations. Thanks.

BTW think it worth adding a note about needing to create a project sub-directory to the FAQ. If not checked it really does break things.

**Comment by fabriciomurta** [comment]
Sorry, I was the wrong one, and I didn't notice (somehow) how old was my screenshot. I was the one needing to uninstall the old extension and install the new one. :) My bad!

**Comment by DaniilVeriga** [comment]
> BTW think it worth adding a note about needing to create a project sub-directory to the FAQ. If not checked it really does break things.

This issue has been fixed in the repo and it will go online with a new 1.8 release which, most likely, will be out this week. Then it is released, we will appreciate your feedback if any issues that you mentioned is still reproducible for you. For now, I will keep this thread closed.

**Comment by g40** [comment]
Hi Daniil. Yes, makes perfect sense. I will check out the latest as soon as possible. Thank you all for Bridge.
