### ISSUE TITLE
JsonConvert.Deserialize doesn't throw when unable to read JSON

### ISSUE THREAD

**Issue by Porl91** [bridgedotnet/Bridge#3014]
When a string is provided to JsonConvert.Deserialize that isn't a valid JSON string I would expect it to throw an exception, whereas it just returns a null response and allows the calling code to continue executing.

### Steps To Reproduce

**Bridge**
https://deck.net/40350fdb12783fe82e18a2b977bebe07

**C#**
https://dotnetfiddle.net/Al1Jhz

### Expected Result
JsonReaderException should be thrown.

### Actual Result

BEFORE
null
AFTER

This just means that we have to ensure that our calling code null guards as well as exception handling, which makes it a bit clunky.

**Comment by geoffreymcgill** [comment]
Hi @Porl91 – I don't want to be a bother, but could you recreate this Issue in the [Newtonsoft.Json](https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/issues) repo? That will help us better track the defect.

**Comment by Porl91** [comment]
@geoffreymcgill Done :)
