### ISSUE TITLE
NuGet Bridge DLLs do not build using .NET 4.0

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#303]
NuGet packages comes with directories:
`lib/net40`
`lib/net45`

Which suggests bridge has DLLs dedicated for .NET framework v4.0 and v4.5. Presumably, v4.5.1 projects will use v4.5 libraries from `lib/net45`.

Creating a project or changing an existing one to .NET v4.0 results in a correct reference to `lib/net40` but the built DLLs are for .NET v4.5. Trying to build will then result in:
```
1>...\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3274: The primary reference "Bridge" could not be resolved because it was built against the ".NETFramework,Version=v4.5" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0".
1>...\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3275: The primary reference "Bridge.Html5" could not be resolved because it has an indirect dependency on the assembly "Bridge, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null" which was built against the ".NETFramework,Version=v4.5" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0".
1>...\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3274: The primary reference "Bridge.Html5" could not be resolved because it was built against the ".NETFramework,Version=v4.5" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0".
1>CSC : error CS0518: Predefined type 'System.Object' is not defined or imported
```

Probably it would be a good idea just to remove `lib/net40` directory from the NuGet package to save on space for the package.

**Comment by geoffreymcgill** [comment]
I am changing the `<TargetFrameworkVersion>` to `v4.0` for all Bridge projects.

Only one Framework version will be available in the NuGet package `lib` directory, which will install to all .NET projects version from .NET 4.0 to vNext.

**Comment by erik-kallen** [comment]
There used to be a problem causing spurious references to be unconditionally added if targeting framework >2.0 (some system.linq assemblies). I saw this in VS2010, don't know if the problem has been fixed

**Comment by geoffreymcgill** [comment]
I should have clarified that I was changing the `<TargetFrameworkVersion>` from `v4.5` to `v4.0`. We've been running >4 since release and to the best of my knowledge have not run into any wonky VS referencing issues. 

Certainly doesn't mean they're not out there. I will create a few VS test projects using .NET40 before final release of v1.8.0.
