### ISSUE TITLE
Issues with Source maps

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#3034]
I don't have a good repro of this yet (everything seems ok in a small project), but source maps are behaving strangely in our main project.

Example, check out this code:

![sourcemaps](https://user-images.githubusercontent.com/1078012/29114484-6412cada-7cec-11e7-8ca8-5d2d05a51ae4.jpg)

Line 78 and 79 are "disabled" for breakpoints, even though 76 and 77 are enabled. Trying to add breakpoints by clicking on the line numbers has strange behaviour:

- Clicking line 67 puts a breakpoint on line 67
- Clicking line 68 puts a breakpoint on line 69
- Clicking line 70 puts a breakpoint on line 71
- Clicking line 72 puts a breakpoint on line 82
- Breaking on line 67 and then pressing Step jumps to `labelText` on line 82

~Additionally, I think that the source maps aren't working for related projects (even when sourcemap is enabled both on the referencing and referenced project), since I only see the `.cs` files from the main "app" and not our components.~ (#3035 covers this issue).

I'll keep trying to get a small repro I can share, but if you have any tips for helping track it down in the meantime, let me know. If I can't get a repro I can share publicly, I might be able to share something privately for you to investigate.

**Comment by Zaid-Ajaj** [comment]
> Additionally, I think that the source maps aren't working for related projects (even when sourcemap is enabled both on the referencing and referenced project), since I only see the .cs files from the main "app" and not our components.

Yup, same here.

**Comment by DanTup** [comment]
Here's a (relatively small) repro:

[SourceMapsIssues.zip](https://github.com/bridgedotnet/Bridge/files/1211381/SourceMapsIssues.zip)

Build this and open Index.html in your browser. Open the dev tools and open `DatePickersPageContainer.cs`. Note that some of the lines in the `ReactStyle` section are disabled while others not and adding brekpoints in this method to various lines results in them jumping to other lines. Stepping through the coed shows similarly confusing behaviour.

**Comment by geoffreymcgill** [comment]
We believe this result of clicking on one line and the browser tools setting a debugger on another line is just a quirk of Chrome developer tools. Source Map support is still not perfect. 

Firefox seems to handle setting breakpoints better.

We are unaware of a way to fix the Chrome Developer Tools breakpoint setting issue.

Closing this issue, but we can always re-open.
