### ISSUE TITLE
Source maps are not available for referenced class library projects

### ISSUE THREAD

**Issue by Zaid-Ajaj** [bridgedotnet/Bridge#3035]
When project `A` references project `B` and project `A` has source maps enabled, no source maps will be available for the referenced project `B`. Related to #3034 

### Steps To Reproduce
- Clone the [Cable](https://github.com/Zaid-Ajaj/Cable) repo
- Build the whole solution
- Open `solution-root\Cable.Bridge.Tests\Bridge\index.html` to see the output of the `Cable.Bridge.Tests` project that references `Cable.Bridge`
- Open browser console, sources/debug tab 
- See only source files of `Cable.Bridge.Tests` and no source files for `Cable.Bridge`

### Expected Result

Source files are generated for the referenced project (`Cable.Bridge` is this case) 
### Actual Result

No source maps available for the referenced project

**Comment by vladsch** [comment]
As I see, `Cable.Bridge` project doesn't activate source map option. You should add `"sourceMap": true` to `bridge.json` of `Cable.Bridge`

**Comment by geoffreymcgill** [comment]
We believe the solution is that the referenced project must enable sourceMaps because the metadata is created during original source compilation.
