### ISSUE TITLE
Bridge constructor overloads not emitted in generated .d.ts file

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#3040]
Bridge is not generating constructor overloads in the generated .d.ts file.

### Steps To Reproduce

https://deck.net/c45a36d71f2361720f45a11e1f68b239

```c#
public class Program
{
    public class Player
	{
		public string id;

        public Player() { }
        
		public Player(Player player)
		{
			if (player != null)
			{
				id = player.id;
			}
		}
	}
    
    public static void Main()
    {
        var p = new Player(new Player() { id = "123" });
        Console.WriteLine(p.id);
    }
}
```

### Expected Result

```js
export interface PlayerFunc extends Function {
    prototype: Player;
    new (): Player;
    new (player: Demo.Program.Player): Player; // <-- Missing!!
    ctor: {
        new (): Player
    };
    $ctor1: {
        new (player: Demo.Program.Player): Player
    };
}
```

### Actual Result

```js
export interface PlayerFunc extends Function {
    prototype: Player;
    new (): Player;
    ctor: {
        new (): Player
    };
    $ctor1: {
        new (player: Demo.Program.Player): Player
    };
}
```
## See Also

* https://gitter.im/bridgedotnet/Bridge?at=598cbc29c101bc4e3a07a0ff

**Comment by vladsch** [comment]
It is expected the result. Bridge generates a unique name for each constructor ($ctor*) like for any overloaded method. A default constructor is presented in d.ts as 'new' but we cannot use the same `new` method with different arguments. As you see, $ctor1 is generated.

**Comment by geoffreymcgill** [comment]
For the scenario provided, the overloaded constructor would be accessed using `$ctor1`. 

#### Example

```ts
let p1 = new Demo.Program.Player();

p1.id = "abc123";

let p2 = new Demo.Program.Player.$ctor1(p1);
```
