### ISSUE TITLE
Use Math.imul calls on checked and unchecked math.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#3047]
Upgrade of #2949, #1092.

### Steps To Reproduce

https://dev.deck.net/11f521d6c1ecdd49c83ae522d2aac642/third

```c#
public static class Program
{
	public static void Main(string[] args)
	{
		unchecked
		{
			int x = (int.MaxValue / 3);
			x = x * x;
			Console.WriteLine(x);
		}
	}
}
```

### Expected Result

```
-477218588
```

### Actual Result

```
-477218560
```

**Comment by vladsch** [comment]
Duplicates https://github.com/bridgedotnet/Bridge/issues/3009
