### ISSUE TITLE
Clone of assignmentExpression.Left in Preconverter is changing runtime behavior

### ISSUE THREAD

**Issue by PaulDiakov** [bridgedotnet/Bridge#3063]
In case when left part of assignment expression has "side effects", expression like
`data[i++] += 1` is translated to something like `data[i++] = data[i++] + 1` and can cause weird runtime errors.

### Steps To Reproduce

https://deck.net/8fcea6a0ad63ef4caeeda143580f3feb

```c#
public class Program
{
    public static void Main()
    {
        int[] data = {10,20,30};
        int i = 0;
        data[i++] += 1;
        
        Console.WriteLine("data[0] = " + data[0]);
        Console.WriteLine("data[1] = " + data[1]);
        Console.WriteLine("i = " + i);
    }
}
```

### Expected Result

```js
data[0] = 11
data[1] = 20
i = 1
```

### Actual Result

```js
data[0] = 21
data[1] = 20
i = 2
```

**Comment by geoffreymcgill** [comment]
Hi @PaulDiakov,

Thanks for the excellent sample demonstrating how to reproduce. We appreciate you bringing this to our attention. 

We will investigate and try to fix right away.
