### ISSUE TITLE
ObjectInitializationMode ignored when ObjectLiteral object is instantiated by a referencing project

### ISSUE THREAD

**Issue by ddaspit** [bridgedotnet/Bridge#3064]
If you mark a class as `ObjectLiteral` with the `ObjectInitializationMode.DefaultValue` setting and you instantiate the class in a referencing project, the generated JS does not set the object's properties to the default values.

### Steps To Reproduce

I have attached a solution that reproduces the problem.
[BridgeTest.zip](https://github.com/bridgedotnet/Bridge/files/1233834/BridgeTest.zip)

`ObjectLiteral` class:
```c#
[ObjectLiteral(ObjectInitializationMode.DefaultValue)]
public class ObjectLiteralClass
{
    public int Number { get; set; }
}
```
Object instantiation in a separate project:
```c#
public class Program
{
    public static void Main()
    {
        var obj = new ObjectLiteralClass();
        Console.WriteLine($"App: {obj.Number}");
    }
}
```

### Expected Result

```js
App: 0
```

### Actual Result

```js
App:
```

**Comment by geoffreymcgill** [comment]
Hi @ddaspit Thanks for the excellent report. We apologise that this defect found it's way into Bridge. 

We will investigate and fix right away.
