### ISSUE TITLE
Support `System.Globalization.TextInfo` class (properties)

### ISSUE THREAD

**Issue by dionrhys** [bridgedotnet/Bridge#3065]
In order to support Right-to-Left (RTL) languages, we can make use of `cultureInfo.TextInfo.IsRightToLeft` in .NET to determine whether we need to apply things like `dir` attributes in HTML for content.

Bridge doesn't support this class currently, but we are developing Bridge.React components that need to support internationalisation and handling RTL cultures is one of our goals.

Here is an example of how we're trying to incorporate a culture's `IsRightToLeft` property on one of our components (a date picker):
![image](https://user-images.githubusercontent.com/844245/29455688-0b5e20b8-840a-11e7-8c79-4c0226d3d8b8.png)

Currently, our only workaround would be to hard-code the specific RTL cultures we know we need to handle.

I'm not sure where the current locales are sourced from, so I'm not sure where the data for IsRightToLeft would come from (I'm guessing it's just scraped from CultureInfo in .NET though). All the `DateTimeFormatInfo` and date formatting in general is very useful for this component right now though!

**Comment by geoffreymcgill** [comment]
Hi @dionrhys Thanks for the request to include `IsRightToLeft` **Textinfo**. 

I will investigate, but it should be very easy to add support for this property.

**Comment by geoffreymcgill** [comment]
PR #3069 has been submitted with the new **TextInfo** class support. 

We have to do some more testing, but once complete **TextInfo** will be included in the next release.

**Comment by dionrhys** [comment]
Thanks for the quick turnaround on this!

**Comment by geoffreymcgill** [comment]
Bridge 16.2.0 has been released and includes **TextInfo** support. 

Hope this helps.

**Comment by dionrhys** [comment]
It works exactly as expected, thank you :)
