### ISSUE TITLE
Improve compilation time

### ISSUE THREAD

**Issue by AndreyZM** [bridgedotnet/Bridge#3095]
Hi. After some performance measurements, I have noticed that half of compilation process is spent into SharpSixRewriter.Rewrite. It very looks like a case for parallel execution. It's takes immutable SyntaxTree and return the rewritten code. 

So running it parallel gave this results 
**Rewrite: 00:01:03.7732088(CPU Time) / 00:00:28.6653381(Actual Time)**
Total: 00:02:1.6932611(CPU Time) / 00:01:38.3699835(Actual Time)

**Comment by geoffreymcgill** [comment]
Hi @AndreyZM 

Thanks for the awesome pull request! 

We are reviewing in detail and will let you know if there we have any questions.
