### ISSUE TITLE
Issue after upgrading to Bridge 16.1

### ISSUE THREAD

**Issue by stopiccot** [bridgedotnet/Bridge#3100]
After I've upgraded my project to Bridge 16.1 I'm getting error message in Xamarin Studio (6.3 build 863):
```
.../packages/Bridge.Min.16.1.0/build/Bridge.Min.targets: error : Command '...' exited with code: 126.
```
but running command in terminal with `mono` directly gives no error for me. Settings logging level to Trace also does not help because when build is executed in Xamarin Studio even output folder is not created. Any help on this?

## See Also

* #2646

**Comment by geoffreymcgill** [comment]
Hi @stopiccot,

Which version of Bridge did you upgrade from?

Bridge 16 is only going to be supported with Mono5.

**Comment by stopiccot** [comment]
From 15.7. My main concern is that everything seems to be working manually from terminal but fails to work when I build project in Xamarin Studio.

**Comment by geoffreymcgill** [comment]
I'm not sure. There were a lot changes on Mono side that happened between Mono4 and Mono5. 

We're still running into issues, but at this point Bridge 16+ is likely to only work with Mono5 and Visual Studio Mac. The old Xamarin Studio will not be supported with Bridge 16+. 

The old Bridge 15.7 and related packages should still work with Mono4, Xamarin Studio, and Mono Develop. 

I apologise for the issues. It's still something we're trying to sort out but we're spread a little thin right at the moment, so the focus on Mono/Mac/Linux support has been a lower priority.

**Comment by LeonidVeriga** [comment]
@stopiccot, may I ask you perform a couple of experiments in your environment and let us know the results. I would ask you locate **Bridge.Min.targets** file at your project's **../packages/Bridge.Min.16.1.0/tools** folder and:
1) Modify [line 46](https://github.com/bridgedotnet/Bridge/blob/master/.build/files/Bridge.Min.targets#L46)  to have `mono` prefix:
```
 <BridgeUtilCommand>&quot;mono $(BridgeUtilWorkDir)bridge.exe&quot; -p ...
```
2) Revert back **Bridge.Min.targets** after experiment **1** and modify [line 15](https://github.com/bridgedotnet/Bridge/blob/master/.build/files/Bridge.Min.targets#L15) to be:
```
<BridgeNetCompilerTarget Condition="$(OnWin) != true">BridgeNetCompilerTask</BridgeNetCompilerTarget>
```

**Comment by stopiccot** [comment]
1. First experiment still produces `exited with code 127` error
2. Second one gives me
```
CSC: error CS0518: The predefined type `System.Object' is not defined or imported
CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
CSC: error CS0518: The predefined type `System.Single' is not defined or imported
CSC: error CS0518: The predefined type `System.Double' is not defined or imported
CSC: error CS0518: The predefined type `System.Char' is not defined or imported
CSC: error CS0518: The predefined type `System.Int16' is not defined or imported
CSC: error CS0518: The predefined type `System.Decimal' is not defined or imported
CSC: error CS0518: The predefined type `System.Boolean' is not defined or imported
CSC: error CS0518: The predefined type `System.SByte' is not defined or imported
CSC: error CS0518: The predefined type `System.Byte' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt16' is not defined or imported
CSC: error CS0518: The predefined type `System.String' is not defined or imported
CSC: error CS0518: The predefined type `System.Enum' is not defined or imported
CSC: error CS0518: The predefined type `System.Delegate' is not defined or imported
CSC: error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
CSC: error CS0518: The predefined type `System.Void' is not defined or imported
CSC: error CS0518: The predefined type `System.Array' is not defined or imported
CSC: error CS0518: The predefined type `System.Type' is not defined or imported
CSC: error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
CSC: error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
CSC: error CS0518: The predefined type `System.IDisposable' is not defined or imported
CSC: error CS0518: The predefined type `System.IntPtr' is not defined or imported
CSC: error CS0518: The predefined type `System.UIntPtr' is not defined or imported
CSC: error CS0518: The predefined type `System.RuntimeFieldHandle' is not defined or imported
CSC: error CS0518: The predefined type `System.RuntimeTypeHandle' is not defined or imported
CSC: error CS0518: The predefined type `System.Exception' is not defined or imported
```
Btw maybe it's better to get Bridge 15.7 working on Mono5 than Bridge 16.x on Mono4. Thing is that our bridge project in final stages of development and it's generally bad idea to update Bridge. On the other side I need fresh mono and Xamarin Studio for iOS 11 development.

**Comment by cra0zy** [comment]
This is likely related to xbuild/msbuild, for me the project compiles fine with msbuild, but has the exact same crashes with xbuild.

**Comment by fabriciomurta** [comment]
I have hit this same problem here on my mac as well, I'll send a pull request with a solution that works for me. It would be nice to have some feedback on it from the community using mono.

**Comment by fabriciomurta** [comment]
According to the description of this thread, the fix just merged will fix it. Fix merged and will make it to the next release (currently 16.5.1, but refer to current milestone attached to this issue).
