### ISSUE TITLE
Using Bridge.Merge & Knockout - Runtime error

### ISSUE THREAD

**Issue by joaommvsoares** [bridgedotnet/Bridge#3113]
After doing a merge of data from json with my class (generated from Bridge.NET)
data = Bridge.merge(new Master(), data);
then I try to 
self.CurrentEntity = ko.mapping.fromJS(data, { copy: self.myMetaData.ToCopyProperties });
 I get a runtime error:
0x800a138d - JavaScript runtime error: **String** expected. 

Original message in Portuguese: Erro de runtime de JavaScript: **Cadeia** esperada. 
Cadeia translation can be: Chain? String? Object?

Thanks,
João Miguel

**Comment by geoffreymcgill** [comment]
Hi @joaommvsoares I think this would be best to post in the Bridge [forums](https://forums.bridge.net/). We're going to try and keep the GitHub issues focused on verified defects and feature requests.
