### ISSUE TITLE
DateTime comparison operator functions not validating correctly

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#3138]
The `lt`, `lte`, `gt`, and `gte` functions should be comparing the `.ticks` value.

### Steps To Reproduce

https://deck.net/92a7c1a5989926c215928471c3ba84fa

```c#
public class Program
{
    public static void Main()
    {
        DateTime now = DateTime.Now;
        DateTime utcNow = now.ToUniversalTime();
        
        // Run from UTC- location,
        // otherwise reverse the operator
        if (now < utcNow)
            Console.WriteLine("Pass");
        else
            Console.WriteLine("Fail");
    }
}
```

### Expected Result

```js
Pass
```

### Actual Result

```js
Fail
```

## See Also

* #3098 
* https://forums.bridge.net/forum/bridge-net-pro/bugs/4697-closed-3098-16-3-datetime-comparison-and-utc?p=4737#post4737

**Comment by hardhub** [comment]
.Net / Core app is also Fail if you have UTC+N:NN timezone. And Pass if you have UTC-N:NN. And equal if your time is UTC.

If you need test case then this one is absolutely not appropriate.
