### ISSUE TITLE
Unable to use Enumerable.Aggregate?

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#315]
I'm porting some Dart code over to Bridge as a test. I had a call to `fold`, which I changed to `Enumerable.Aggregate`, but I get two compile errors.

Code:
```
// string input;
// Func<char, char, char> scoreChar;
input.ToUpperCase().Split("").Aggregate(null, scoreChar);
```

Errors:

> The type 'Func<,,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
> 
> The type 'IEnumerable<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

I can easily change the code; but I'm curious to know if this should work and I'm doing something wrong (I can't add a reference to mscorlib, it says it's added automatically).

I'm using VS 2015 RC and a Console App targetting .NET 4.5.2 with the NuGet package pulled in.

**Comment by vladsch** [comment]
Did you add `using System.Linq` in your source code?
The following sample instranslated without any problem for me
```
using Bridge;
using Bridge.Html5;
using System.Linq;

namespace Demo
{
    public class App
    {
        [Ready]
        public static void Main()
        {
            var q = "".ToUpperCase().Split("").Aggregate("", (workingSentence, next) => next + " " + workingSentence);
        }
    }
}
```

**Comment by DaniilVeriga** [comment]
This compiles on [Live Bridge](http://live.bridge.net/#bcb2af6675c980cc9fef) as well.

**Comment by DanTup** [comment]
Er, that would be embarrassing... :)

Will check it out when back in the office Monday. Hope it's something that silly; I often make this mistake (though in C# the compile error is different). Thanks!

**Comment by DanTup** [comment]
I did indeed have `using System.Linq` in my code. Without that, the compile error is:

> 'string[]' does not contain a definition for 'Aggregate' and no extension method 'Aggregate' accepting a first argument of type 'string[]' could be found (are you missing a using directive or an assembly reference?)

But with `using System.Linq`, there are these two:

> The type 'Func<,,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
>
> The type 'IEnumerable<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

Not sure if this might be specific to VS 2015 RC (Roslyn compilers). Here's what I just did to repro in a clean project:

- Create new Class Library project (C# -> Windows -> Class Library, .NET 4.5.2)
- Add Bridge NuGet package
- Paste in the below code and press build

```
using System;
using System.Linq;

namespace A
{
    public class B
    {
		void C()
		{
			Func<char, char, char> scoreChar = null;
			"abc".ToUpper().Split("").Aggregate(null, scoreChar);
		}
	}
}
```

**Comment by fabriciomurta** [comment]
Hello,

We do not have a signature for aggregate like you are trying to use. If you use like @vladsch suggestion, it would work on your case. I tried on VS2013 with the same error, pointed at intellisense level (before trying to build, red-underlined).

I tried also on both VS2013 and VS2015, both refuses to accept the code as well with original CLR and also with Bridge (although for different reasons).

What is the behavior you expected that to have with scoreChar?

**Comment by DanTup** [comment]
> We do not have a signature for aggregate like you are trying to use

This is the overload I was trying to use:

https://msdn.microsoft.com/en-us/library/vstudio/bb549218(v=vs.100).aspx

In my case, both `TSource` and `TAccumulate` are both the same (`char`). However looking back, I see I'm passing `null` as the seed which seems incorrect given the type is `char`. I think this is an error (a hangover from the Dart version, where null is valid).

I'll check this in the morning and see if changing the `null` seed value to something of type `char` solves the issue.

As for why some things work on the Live Bridge and not in VS, I think the bridge might not be running the real C# compiler, butthe IDE is? A colleague showed me another error where the CS compiler reported an error, but the Live Bridge worked fine (I can't remember the details; I'll post them if it comes to me).

**Comment by DanTup** [comment]
Ok, I re-tested this, and the error is not related to me passing null. I copy/pasted the sample posted by @vladsch and it doesn't work either; it gives exactly the same issue. This doesn't surprise me, as I don't see any difference in his code to mine, the sig is the same - [`Aggregate<TSource, TAccumulate>(this IEnumerable<TSource>, TAccumulate, Func<TAccumulate, TSource, TAccumulate>)`](https://msdn.microsoft.com/en-us/library/vstudio/bb549218(v=vs.110).aspx)).

I've only tested in VS 2015 (both RC and RTM).

Here's the exact code I'm using (coped from @vladsch's comment):

```
var q = "".ToUpperCase().Split("").Aggregate("", (workingSentence, next) => next + " " + workingSentence);
```

I get the exact same red squiggle and error in the error window:

> The type 'Func<,,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
> 
> The type 'IEnumerable<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

**Comment by LeonidVeriga** [comment]
@DanTup  An interesting issue. I use the exact code below on VS 2015 RTM against the latest code from github. It translates with no issues. I tried both creating a NuGet package and just in the Bridge.Frameworks.Builder.Testing.sln. The output is like:
```JavaScript
main: function () {
            var q = Bridge.Linq.Enumerable.from("".toUpperCase().split("")).aggregate("",
                    function (workingSentence, next) {
                        return next + " " + workingSentence;
            });
        }
```

Can you please check it against the latest code in Bridge.Frameworks.Builder.Testing.sln.

```C#
using Bridge.Html5;
using System.Linq;

namespace Demo
{
    public class App
    {
        [Ready]
        public static void Main()
        {
            var q = "".ToUpperCase()
                      .Split("")
                      .Aggregate("", (workingSentence, next) => next + " " + workingSentence);
        }
    }
}
```

**Comment by DanTup** [comment]
I'm still seeing the same issue with the latest code :(
![error](https://cloud.githubusercontent.com/assets/1078012/8877954/3df30608-3220-11e5-8da2-b46880798e87.jpg)
![references](https://cloud.githubusercontent.com/assets/1078012/8877958/3fe9dc48-3220-11e5-8353-5ec0765dcfaa.jpg)
![target](https://cloud.githubusercontent.com/assets/1078012/8877961/41c2e10e-3220-11e5-9697-3f42892e43b9.jpg)

What do your references look like? Are you able to send a zip of your project that I can use to compare? I can mail you my project if you want?

**Comment by LeonidVeriga** [comment]
@DanTup  Oh, it looks like the case - can you please remove all non-bridge references like `System.*` and `Microsoft.*`.

**Comment by DanTup** [comment]
Doh!

I thought the Bridget NuGet had removed a bunch of references at install time, and assumed what was left was correct. Removing the MS/System references indeed solves the issue.

Thanks!

**Comment by vladsch** [comment]
Also please note that System reference is automatically added by VS when you modify a project (for example, add/remove files). It is what we did not solve yet
