### ISSUE TITLE
Mixin attribute does not work.

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#3156]
In correspondence with [documentation](https://github.com/bridgedotnet/Bridge/wiki/attribute-reference#mixin):

> Mixin
Allows a prefix to be specified for the generated methods.
```cs
[Mixin("$.fn")]
public static class MyStaticMethods
{
    public static void MyMethod()
    {
    }
} 

is compiled to:

js
$.fn.MyMethod = function() { };
```

But it does not work...
I think the reason that Mixin works only on bridged classes (creates methods property). But in deck even that does not work.

### Steps To Reproduce

https://dev.deck.net/6200e4fe9e46da85d592dd9022f17155

```csharp
[Mixin("_$.fn")]
public static class MyStaticMethods
{
    // Emulation of some $.fn instance
    // that will be used as a prefix
    [Init(InitPosition.Top)]
    private static void GlobalInit()
    {
        Script.Write("var _$ = { fn: { } };");
    }
    
    public static void MyMethod()
    {
        Console.WriteLine("MyMethod");
    }
} 

public class Program
{
    public static void Main()
    {
        MyStaticMethods.MyMethod();
    }
}
```

### Expected Result
Generated JavaScript:
```js
    Bridge.apply(_$.fn, {
        MyMethod: function () {
            System.Console.WriteLine("MyMethod");
        }
    });
```
Console shows:
```
MyMethod
```

### Actual Result
Generated JavaScript:
```js
    Bridge.apply(_$.fn, {
        methods: {
            MyMethod: function () {
                System.Console.WriteLine("MyMethod");
            }
        }
    });
```
Throws an exception:
```
TypeError: _$.fn.MyMethod is not a function
```

**Comment by geoffreymcgill** [comment]
@hardhub – Thanks for reporting this issue. We will investigate right away.

**Comment by geoffreymcgill** [comment]
We have confirmed there is a problem. This defect will be fixed immediately.

**Comment by geoffreymcgill** [comment]
This issue has been fixed and a pull request has been submitted. After further testing and final review, the PR will be merged into the **master** branch and included in the next public release of Bridge.

**Comment by hardhub** [comment]
Nice work! :)

**Comment by LeonidVeriga** [comment]
@hardhub, 

We changed a bit the sample in **Steps To Reproduce** to create an instance that is used as a prefix (Bridge does not create it in case of Mixin):
```cs
    // Emulation of some $.fn instance
    // that will be used as a prefix
    [Init(InitPosition.Top)]
    private static void GlobalInit()
    {
        Script.Write("var _$ = { fn: { } };");
    }
```
