### ISSUE TITLE
Invalid code emit in Parenthesized Block

### ISSUE THREAD

**Issue by tluyben** [bridgedotnet/Bridge#3158]
### Bridge.NET Version

16.0.0.0

### Steps To Reproduce

https://deck.net/4eebb52c66c0e5153598c91b35b81760

```csharp
public class Program
{
    public static void Main()
    { 
        var CurrentLeft = 40;
        
        var x = ((int)(CurrentLeft % 60)).ToString().PadLeft(2, '0');
        
        Console.WriteLine(x);
    }
}
```

### Expected Result

```js
x = System.String.alignString((this.Data.CurrentLeft % 60).toString(), 2, 48);
```

### Actual Result

```js
x = System.String.alignString(this.Data.CurrentLeft % 60.toString(), 2, 48);
```

**Comment by geoffreymcgill** [comment]
Hello @tluyben – Thanks for reporting this issue. Can you share a [Deck](https://deck.net/) demonstrating how to reproduce the issue?

**Comment by tluyben** [comment]
Added!

**Comment by geoffreymcgill** [comment]
Perfect. Thanks for the sample. I have reproduced the defect. 

We will investigate and try to fix this right away.

**Comment by tluyben** [comment]
My workaround currently; https://deck.net/eebd297ffc47b1695c6be345d6fc7b59
