### ISSUE TITLE
Make `string` enumerable

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#317]
In C#, you can enumerate a string to get the characters:

```
foreach (var c in "abc")
{
	Console.WriteLine(c);
}
```

However in Bridge, `string` is not enumerable:

> foreach statement cannot operate on variables of type 'string' because 'string' does not contain a public definition for 'GetEnumerator'

I don't know if the plan is to try and support everything that C# does like this; if not, let me know, so I know whether it's worth raising issues like this (the important thing is that there are compile errors where this isn't supported, which is the case here :))

**Comment by DanTup** [comment]
This does compile:

```
foreach (var c in "abc".ToCharArray())
{
    Console.WriteLine(c);
}
```

**Comment by geoffreymcgill** [comment]
Hi @DanTup,

Thanks for notifying us of this inconsistency between the JavaScript and C# API's.

I will discuss the issue with the team and get back to you with an update right away. I think it should be easy to get this working, although I'm not 100% sure at this point without checking a few things.

**Comment by Mimisss** [comment]
Working on it : https://github.com/bridgedotnet/Bridge/commit/fa25cf0
reveals the need for `IndexerNameAttribute`

**Comment by DanTup** [comment]
I just tried this in the latest code, but it seems that the enumerator on string is not typed. If you use `var`, you'll get an `object` instead of `char`:

```
foreach (var c in "danny")
{
    char a = c; // Cannot implicitly convert type 'object' to 'char'. An explicit conversion exists (are you missing a cast?)
}
```

**Comment by LeonidVeriga** [comment]
@DanTup Thanks for letting us know about not typed enumerator on string.
It should work now.

**Comment by DanTup** [comment]
Yep, looks good now. Thanks!
