### ISSUE TITLE
Auto-properties should be implemented as if they are regular fields

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#3177]
We were profiling our engine today and noticed "cfg.get" was all over the place. I ended up replacing our auto-properties with normal fields and this resulted in our code becoming 4.5 times faster!

**Comment by vladsch** [comment]
If implement auto property as field then can be a problem with access to such properties via `base` keyword. But we will think about such possibility.

**Comment by ddaspit** [comment]
I recently did the same thing (replaced auto-properties with normal fields), because of performance issues.

**Comment by TriEdgeAI** [comment]
So maybe implement them as regular fields only in cases where they are not virtual/abstract? :)

**Comment by vladsch** [comment]
At this moment, you can use Field attribute which can be applied to property/class/assembly

**Comment by geoffreymcgill** [comment]
Please see the new AutoProperty rule that will be included with the upcoming Bridge 16.4 release. 

https://github.com/bridgedotnet/Bridge/issues/3182
