### ISSUE TITLE
Implement AutoPropertyRule

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#3182]
New [Rule](https://github.com/bridgedotnet/Bridge/wiki/attribute-reference#rules) to control how auto properties are emitted

Name | Options | Description
---- | ---- | ----
AutoProperty | `Managed` or `Plain` | Set to `Plain` to generate as simple field, or `Managed` to create as a JavaScript property with getter and setter. Default is `Managed`.

## See Also

* #3110
* #3177 
* `[Rules]` attributes [docs](https://github.com/bridgedotnet/Bridge/wiki/attribute-reference#rules)
* **bridge.json** [docs](https://github.com/bridgedotnet/Bridge/wiki/global-configuration#rules)

**Comment by TriEdgeAI** [comment]
<3

**Comment by fabriciomurta** [comment]
The associated pull request has just been merged in. The feature will be available to Bridge 16.4.0.
