### ISSUE TITLE
"abc".ToUpperCase() throws TypeError

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#319]
This code compiles fine, but throws a `TypeError` at runtime:

`"a".ToUpperCase();`

> Uncaught TypeError: String.toUpperCase is not a function

**Comment by DanTup** [comment]
Note: There's also a `.ToUpper()` method which does work.

**Comment by DaniilVeriga** [comment]
Besides `.ToUpperCase()` the same happened with `.ToLocaleUpperCase()`, '.ToLowerCase()' and `ToLocaleLowerCase()`. It has been fixed. Also the unit tests have been added for each method.

Thank you for pointing the problem out.

**Comment by DanTup** [comment]
Thanks! :+1:
