### ISSUE TITLE
String.Format fails with Exception if first argument is an array (wrong overload picked)

### ISSUE THREAD

**Issue by d-p-y** [bridgedotnet/Bridge#3192]
String.Format guesses which overload is called by checking first parameter. It incorrectly detects _(string format, params object[])_ leading to exceptions being thrown.

It seems that String.js implementation of _format_ assumes that it can differentiate between _(string format, params object[])_ and other overloads by checking its first argument to see if it is an array. It fails when first parameter just happens to be an array as shown in test cases below.

First case could be fixed if String.js is changed from 
```js
        format: function (format, args) {
            return System.String._format(System.Globalization.CultureInfo.getCurrentCulture(), format, !Array.isArray(args) ? Array.prototype.slice.call(arguments, 1) : args);
        },
```
to
```js 

        format: function (format, args) {
            var p;
            
            if (Array.isArray(args) && arguments.length > 2) {
                //first arg just happens to be an array
                p = Array.prototype.slice.call(arguments, 1)
            } else if (Array.isArray(args) && arguments.length === 2) {
                p = args;
            }  else if (!Array.isArray(args)) {
                p = Array.prototype.slice.call(arguments, 1)
            }
            return System.String._format(System.Globalization.CultureInfo.getCurrentCulture(), format, p);
        },
```

Second case - I think it has to be solved differently. Code would really need to know if 'params' overload was used. In that case proper fix for second case would include fix for first case as well.

### Steps To Reproduce

https://deck.net/836ca3552a8f7e74da2cfe12bef4b9d1

```csharp
    
public class Program
{
    public static void Main()
    {
        int[] i = new int[] {};
        int[] j = new int[] {};
        
        try {
            string.Format("{0}", i, j);    
        } catch(Exception) {
            Console.WriteLine("non params case A failed");
        }
                
        object cpy = i;
        try {
            string.Format("{0}", cpy);
        } catch(Exception) {
            Console.WriteLine("non params case B failed");       
        }
    }
}
```

### Expected Result

Should not print two messages in test.
### Actual Result

Prints two messages in test.

**Comment by fabriciomurta** [comment]
The associated pull request has just been merged in. The fix will be available to Bridge 16.4.0.
