### ISSUE TITLE
List constructor with complex enumerable fails

### ISSUE THREAD

**Issue by kosmab** [bridgedotnet/Bridge#3199]
`List<TType>(IEnumerable<TType>)` constructor fails for complex enumerable
`TType[] a1 = oEnumerable.ToArray()` works fine

constructed List/array is further used for Linq.Select(s) and everything is inside async operations

### Steps To Reproduce

cannot reproduce in deck - but our code is similar to presented in deck.
problem is probably input objects, but they are regular Bridge objects

https://deck.net/d775723f29b4656b47b9293ce248a7db

JavaScript reports `Operation not supported` error in line where constructor is invoked

**Comment by geoffreymcgill** [comment]
Hi @kosmab – We were not able to reproduce the issue. Can you link us to a [Gist](https://gist.github.com/) or a GitHub project that would demonstrate the scenario? Or adjusting the Deck to make it fail.

**Comment by kosmab** [comment]
Unfortunately, we can’t provide access to source code.

Problem started to exist with 16.x.x version – this code worked flawlessly when generated by older Bridge compiler

 

In real code IEnumerable<c4.c0> x() is method called in async context, calling itself other Linq/enumerable/convertion operations.

 

When data_sets is data_set[] it works:

            ctor: function (collColumns) {

                this.$initialize();

                this.data_sets = System.Linq.Enumerable.from(collColumns).toArray();

            }



When data_sets is List<data_set> if fails:

     ctors: {

            ctor: function (collColumns) {

                this.$initialize();

                this.data_sets = new (System.Collections.Generic.List$1(nxm_core_web.chart_query_results.data_set)).$ctor1(System.Linq.Enumerable.from(collColumns).toArray());

            }

        },

**Comment by geoffreymcgill** [comment]
okay, no problem. Thanks for the update. 

I'm going to close the thread for now because we cannot reproduce, but if you can narrow down the problem to a reproducible [Deck](https://deck.net), we'll re-open and investigate further.
