### ISSUE TITLE
[Feature Request] May object.Keys() method be renamed to something less generic

### ISSUE THREAD

**Issue by cra0zy** [bridgedotnet/Bridge#3203]
Keys is very generic and very often used as an Enum in game engines/frameworks or UI toolkits, might this method be renamed to something less generic so it does not conflict with the possible enums?

https://github.com/bridgedotnet/Bridge/blob/f9f8ccda5433847f68ca73f67e34f4eb0a6f6978/Bridge/System/Object.cs#L47

**Comment by geoffreymcgill** [comment]
Yes, I agree this is a problem. This `Keys` property should never have been added to the **Object** class. We cannot remove in the Bridge 17.0 release.

**Comment by michaelcheers** [comment]
Related to #2564.

**Comment by geoffreymcgill** [comment]
The **Object.Keys()** method has been removed. We will include this change in the Bridge 17.0 release.

**Comment by fabriciomurta** [comment]
Merged upstream! Fix available in next Bridge release already published in dev.deck.net.
