### ISSUE TITLE
AutoProperty rules config in bridge.json does not work

### ISSUE THREAD

**Issue by ddaspit** [bridgedotnet/Bridge#3207]
I set the "autoProperty" rule in the bridge.json file to "Plain". It did not change the auto-properties to fields as expected. When I added a "Rules" attribute to the AssemblyInfo.cs that sets "AutoProperty" to "Plain", it worked. Am I doing something wrong?

### Steps To Reproduce

bridge.json
```js
{
  "rules": {
    "autoProperty": "Plain"
  }
}
```

### Expected Result

All auto-properties should be compiled to fields.

### Actual Result

All auto-properties remained as properties.

**Comment by geoffreymcgill** [comment]
@ddaspit – Thanks for the report. We will investigate and fix right away.

**Comment by fabriciomurta** [comment]
The fix has just been merged upstream and will be available to Bridge version 16.4.1.
