### ISSUE TITLE
generated typescript for modules is not a module

### ISSUE THREAD

**Issue by lidermanrony** [bridgedotnet/Bridge#3208]
The **d.ts** file doesn't generate a valid module since it does not contain a top-level export.

this makes it impossible to import a bridge.net generated library from typescript code.

My goal is to generate an npm package from the output of Bridge.NET project that has a Module attribute (on the entire assembly), and then install the package on my typescript project and use typescript import statement to use that library.

Right now getting the following error from ts:

```
[ts] File 'c:/projects/testBridge/node_modules/test-bridge/test-bridge.d.ts' is not a module.
```

### Steps To Reproduce

https://deck.net/cd409cfda8617388a3a9f1e26f9beae3

```csharp
[Module("testBridge")]
public class Program
{
    public static void Main()
    {
        var msg = "Hello, World!";
        
        Console.WriteLine(msg);
    }
}
```

### Expected Result

```ts
/// <reference path="./bridge.d.ts" />

declare module testBridge.Demo {
    export interface Program {
    }
    export interface ProgramFunc extends Function {
        prototype: Program;
        new (): Program;
        Main(): void;
    }
    var Program: ProgramFunc;
}
export = testBridge.Demo;
```

### Actual Result

```ts
/// <reference path="./bridge.d.ts" />

declare module testBridge.Demo {
    export interface Program {
    }
    export interface ProgramFunc extends Function {
        prototype: Program;
        new (): Program;
        Main(): void;
    }
    var Program: ProgramFunc;
}
```

**Comment by geoffreymcgill** [comment]
Hi @lidermanrony, 

Thanks for taking the time to notify us of this issue. We have discussed the problem and have figured out a fix. The fix is being developed right now and we plan to include in the 16.5.1 release of Bridge.

**Comment by fabriciomurta** [comment]
With the fix being applied, from this C# code:

```csharp
using Bridge;

[Module("testBridge")]
public class Program
{
    public static void Main()
    {
        var msg = "Hello, World!";
        
        Console.WriteLine(msg);
    }
}
```

The final output would be actually:

```typescript
/// <reference path="./bridge.d.ts" />

declare module "testBridge" {
    interface Program {
    }
    interface ProgramFunc extends Function {
        prototype: Program;
        new (): Program;
        Main(): void;
    }
    declare var Program: ProgramFunc;


}
```

Notice in this case, the only difference is the `testBridge` module name quoted. This is per AMD/CommonJS standard.

If you require the `export =` concept, it is necessary to specify the module as a UMD module. The C# code would become:

```csharp
using Bridge;

[Module(ModuleType.UMD, "testBridge")]
public class Program
{
    public static void Main()
    {
        var msg = "Hello, World!";
        
        System.Console.WriteLine(msg);
    }
}
```

That will then output this:

```typescript
/// <reference path="./bridge.d.ts" />

declare namespace testBridge {
    export interface Program {
    }
    export interface ProgramFunc extends Function {
        prototype: Program;
        new (): Program;
        Main(): void;
    }
    var Program: ProgramFunc;

}

declare module "testBridge" {
    export = testBridge;
}
```

Let us know if you don't agree with this approach and we can discuss about it.

**Comment by fabriciomurta** [comment]
The fix proposed above was just merged in, it will go to the next Bridge release (see milestone). If you do not agree with the approach just let us know and we'll consider your arguments for changing it.
