### ISSUE TITLE
Reference declaration files originated from Retyped packages

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#3209]
A Retyped package holds the declaration files, that were used to generate C# bindings. They can be copied to the output folder when [generateTypeScript](https://github.com/bridgedotnet/Bridge/wiki/global-configuration#generatetypescript) option is set to `true`.

The problem is that the **d.ts** files generated by Bridge for C# code does not reference Retyped **d.ts** files.

### Steps To Reproduce

```csharp
// Requires 'Retyped.knockout' package

namespace Program
{
    using static Retyped.knockout;

    public class App
    {
        public void Foo(KnockoutComponents arg)
        {
        }
    }
}
```

### Expected Result (Program.d.ts)

```ts
/// <reference path="./bridge.d.ts" />
/// <reference path="./knockout/index.d.ts" />

declare module Program {
    export interface App {
        Foo(arg: KnockoutComponents): void;
    }
    export interface AppFunc extends Function {
        prototype: App;
        new (): App;
    }
    var App: AppFunc;
}
```

### Actual Result (Program.d.ts)

```ts
/// <reference path="./bridge.d.ts" />

declare module Program {
    export interface App {
        Foo(arg: KnockoutComponents): void;
    }
    export interface AppFunc extends Function {
        prototype: App;
        new (): App;
    }
    var App: AppFunc;
}
```

**Comment by fabriciomurta** [comment]
Merged upstream. It will be available on version 16.4.2.

**Comment by fabriciomurta** [comment]
The fixed version is generating more references that what would be expected by the expected result above:
![image](https://user-images.githubusercontent.com/10730372/31953750-800d30ce-b8c2-11e7-983f-ab903a6ef72c.png)

**Comment by AndreyChechel** [comment]
It's okay - at least one reference for the each Retyped packaged added to the solution (except **Retyped.Core** since it doesn't contain any typescript declarations).

**Comment by fabriciomurta** [comment]
Thanks for the confirmation, @AndreyChechel!
