### ISSUE TITLE
[VS2015] Errors building from source

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#321]
Apologies if this already exists; I can't find it :(

I've cloned the four repos that seem to be referenced from the various sln files in the Bridge repo (Bridge, Testing, Frameworks, Builder) and I've tried compiling them all; but none seem to have product a new `bridge.js` file that appears to have all the latest committed changes (and the .Testing one gave some compile errors).

Is it possible to document how to build from source?

**Comment by LeonidVeriga** [comment]
http://bridge.net/kb/build-from-source/

**bridge.js** is generated by **Bridge.csproj** and can be located at `..\Bridge\Bridge\Resources`

Can you please specify the compile errors in the .Testing.

**Comment by DanTup** [comment]
Doh! Thanks :) I looked under the "Contributing" section in the KB, didn't spot that. Thanks :)

I'm building in VS 2015 RC which may be interfering with this, but the errors I get building .Testing are:

```
exception level: 0 - Index was outside the bounds of the array.	typeScriptBridge	C:\Work\Source\Bridge\Testing\tests\typeScriptBridge\EXEC	

Missing compiler required member 'System.String.Format'	client	C:\Work\Source\Bridge\Testing\tests\client\CSC	

The command ""C:\Work\Source\Bridge\Testing\tests\typeScriptBridge\..\..\..\Builder\Builder\bin\Debug\Bridge.Builder.exe" -p "C:\Work\Source\Bridge\Testing\tests\typeScriptBridge\typeScriptBridge.csproj" -b "C:\Work\Source\Bridge\Testing\tests\typeScriptBridge\bin\Debug\Bridge.dll"" exited with code -1.	typeScriptBridge
```

**Comment by DanTup** [comment]
Btw, from the KB:

> At this point, the full Bridge Solution should compile without errors, and fresh .dll’s will be available from the projects /bin directory.

It's not clear which directory this means. There are lots of bin/Debug folders with bridge.dll, but not the .js file. Should these be taken from different locations? Is the code that packages the NuGet file available in the repo (this would be the easiest way for us to reference the self-built version?)

**Comment by DanTup** [comment]
I tried to replace the Bridge.dll/Bridge.html5.dll from the NuGet I'm referencing (a birty dirty, I know), but it then failed to compile with:

```
1>C:\Work\Source\DMS\ScrabbleTests\Bridge\packages\Bridge.1.7.0\build\Bridge.targets(12,5): error : Error: Index was outside the bounds of the array.    at Mono.Cecil.Mixin.ParseRuntime(String self)
1>C:\Work\Source\DMS\ScrabbleTests\Bridge\packages\Bridge.1.7.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.PE.ImageReader.ReadMetadata()
1>C:\Work\Source\DMS\ScrabbleTests\Bridge\packages\Bridge.1.7.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.PE.ImageReader.ReadImage()
1>C:\Work\Source\DMS\ScrabbleTests\Bridge\packages\Bridge.1.7.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.PE.ImageReader.ReadImageFrom(Stream stream)
1>C:\Work\Source\DMS\ScrabbleTests\Bridge\packages\Bridge.1.7.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
1>C:\Work\Source\DMS\ScrabbleTests\Bridge\packages\Bridge.1.7.0\build\Bridge.targets(12,5): error :    at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
1>C:\Work\Source\DMS\ScrabbleTests\Bridge\packages\Bridge.1.7.0\build\Bridge.targets(12,5): error :    at Bridge.Translator.Translator.LoadAssembly(String location, List`1 references)
1>C:\Work\Source\DMS\ScrabbleTests\Bridge\packages\Bridge.1.7.0\build\Bridge.targets(12,5): error :    at Bridge.Translator.Translator.InspectReferences()
1>C:\Work\Source\DMS\ScrabbleTests\Bridge\packages\Bridge.1.7.0\build\Bridge.targets(12,5): error :    at Bridge.Translator.Translator.Translate()
1>C:\Work\Source\DMS\ScrabbleTests\Bridge\packages\Bridge.1.7.0\build\Bridge.targets(12,5): error :    at Bridge.Build.GenerateScript.Execute()
```

My guess is that the `tools\Bridge.Builder.dll` is out of sync with the other DLLs. However, it doesn't look like a new `Bridge.Builder.dll` was generated as part of the build.

I think it would valuable to include some additional info on the build-from-source page about how best to use the build (the ideal would definitely be a script to build a new nupkg that's the same format as the one on nuget.org).

**Comment by LeonidVeriga** [comment]
> There are lots of bin/Debug folders with bridge.dll, but not the .js file.

`bridge.js` can be referenced from `..\Bridge\Bridge\Resources\bridge.js` It is just for your reference as `bridge.js` is embedded into `Bridge.dll` Assemblies are referenced from corresponding projects. I.e. `Bridge.dll` from `..\Bridge\Bridge\bin`; `Bridge.Html5.dll` from `..\Bridge\Html5\bin`; jQuery from `Frameworks\jQuery2\bin`.

> Is the code that packages the NuGet file available in the repo (this would be the easiest way for us to reference the self-built version?
> My guess is that the tools\Bridge.Builder.dll is out of sync with the other DLLs. However, it doesn't look like a new Bridge.Builder.dll was generated as part of the build.

No, the code is not available. At least at the moment...
You can look at the the testing project https://github.com/bridgedotnet/Testing/blob/master/tests/client/client.csproj. Please note the `PostBuildEvent` how it references `Bridge.Builder.exe` and `Bridge.dll` (a custom way of using Bridge without NuGet packages).

> I'm building in VS 2015 RC which may be interfering with this, but the errors I get building.

Yes, this appears to be VS 2015 related issues; we will have a look.

> I think it would valuable to include some additional info on the build-from-source page about how best to use the build (the ideal would definitely be a script to build a new nupkg that's the same format as the one on nuget.org).

Agree)

**Comment by DanTup** [comment]
@LeonidVeriga Thanks for the info; I'll give it a go!

Worth raising a case requesting a script to build the nupkg so it doesn't get lost?

**Comment by geoffreymcgill** [comment]
We have an internal project for building the NuGet packages, and this is high on my list of items to refactor. While what we have works well, there is a better process that we need to move to. 

I will expedite this NuGet package project.

Created Issue #323 to track this work.

**Comment by DanTup** [comment]
@geoffreymcgill Great, thanks!

**Comment by fabriciomurta** [comment]
Hello,

I am currently using the script below (cygwin/linux/os x) when I want to overwrite the .DLLs of a NuGet package (attached on a project) with the latest, freshly built Bridge binaries:
```
#!/bin/bash

pjhome="${HOME}/Object.NET/projects/BridgeSolution1"
if [ ! -z "${1}" ]; then
 pjhome="$(realpath ${1})"
fi

brdhome="${pjhome}/packages/Bridge.1.7.0"
cd ${HOME}/Object.NET/Bridge.NET/git
#Bridge-main
cd Bridge/Html5/bin/Debug || { echo "Bridge/Debug dir not found."; exit 1; }
for dest in net40 net45; do
 cp *.dll *.xml ${brdhome}/lib/${dest}/.
 cp *.pdb ${brdhome}/lib/${dest}/pdb/.
done

# Builder
cd -
cd Builder/Build/bin/Debug || { echo "Builder/Debug dir not found."; exit 1; }
cp *.dll *.xml ${brdhome}/tools/.
cp Bridge.Build.dll ${brdhome}/tools/Bridge.Builder.dll

cd -
```

Although it's not a native windows script, it can help understanding how the NuGet package core files are distributed on an installed project.

Notice also the catch on the script about your observation:
_"My guess is that the  tools\Bridge.Builder.dll  is out of sync with the other DLLs. However, it doesn't look like a new  Bridge.Builder.dll  was generated as part of the build."_

I guess we should open a FAQ entry with _"I've built Bridge but there's no Bridge.Builder.dll"_. :)
(I'm going to find a topic that I stressed this subject and share it here)

**Comment by fabriciomurta** [comment]
Here are the additional information about the "Bridge.Builder.dll vs Bridge.Build.dll" dillema:
[Comment on jun 12th, issue #238](https://github.com/bridgedotnet/Bridge/issues/238#issuecomment-111484187)

**Comment by DanTup** [comment]
> cp Bridge.Build.dll ${brdhome}/tools/Bridge.Builder.dll

Aha, this name might be what I missed. I searched for a dll of the same name. Will check this out next week. Thanks for the script!

**Comment by fabriciomurta** [comment]
Just installed VS2015 Community preview here and...
`========== Build: 10 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========`

No problems at all...

**Comment by DanTup** [comment]
I didn't replace any DLLs in the repos I cloned, only in a test project I was trying to update.

I was using VS 2015 Enterprise RC. RTM came out today, so I will upgrade over the next few days and retry from a clean clone, and see how I get on.

**Comment by DaniilVeriga** [comment]
@fabriciomurta, I see "10 succeeded" in your comment. I think @DanTup tested with **Bridge.Frameworks.Builder.Testing.sln**, but you did with **Bridge.Frameworks.Builder.sln**.

Those errors are reproducible with **Bridge.Frameworks.Builder.Testing.sln** only and it happens with the **client** and typeScriptBridge projects.
https://github.com/bridgedotnet/Bridge/issues/321#issuecomment-122295956

**Comment by fabriciomurta** [comment]
Yes, I didn't use the solution with the Testing project, following the guide to Build Bridge on http://bridge.net/kb/build-from-source/.

**Comment by DanTup** [comment]
Yeah, sorry, I picked the testing one as I was hoping to run tests too. We'd like to ensure we can build the whole of Bridge and run tests in case we want to send PRs, or patch our own bug fixes in if required.

**Comment by DaniilVeriga** [comment]
We have to get the Testing solution working on V 2015 as well and we are working on that. To be more specific, @LeonidVeriga is taking on that.

**Comment by LeonidVeriga** [comment]
There are several differences in VS2015 compared to VS2013:

 1) msbuild14 produces `NoStdLib` assemblies that cannot be read by Mono.Cecil. The following error comes up:
   `System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Mono.Cecil.Mixin.ParseRuntime(String self)
   at Mono.Cecil.PE.ImageReader.ReadMetadata()
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImageFrom(Stream stream)
   at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly(Object state)
   at System.Threading.Tasks.Task'1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()`
The problem appears when reading RuntimeVersion field, it gets empty that is not handled by the Mono.Cecil code.

2)  The following error appears when a "user's" project uses Bridge: `Missing compiler required member 'System.String.Format' client C:\NET\Bridge\Testing\tests\client\CSC`

3) *Release* configuration build fails with 
`ILMerge.Merge: ERROR!!: Duplicate type 'Mono.Security.Cryptography.CryptoConvert' found in assembly 'ICSharpCode.NRefactory.CSharp'. Do you want to use the /alllowDup option?	Bridge.Build`

**Comment by LeonidVeriga** [comment]
@DanTup can you please pull the changes and confirm the solution builds from source with no errors?

**Comment by DanTup** [comment]
@LeonidVeriga Yep; all builds without issue on VS 2015 RTM now :+1:
