### ISSUE TITLE
Ignore [IgnoreGeneric] attribute when generating TypeScript declarations

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#3213]
External libraries does not support Bridge-specific logic for generics. So all types created for external generic entities get `[IgnoreGeneric]` attribute. This leads to correct JavaScript output generated.

However, Bridge behaves similarly (ignores generics) when generating a TypeScript d.ts file. Especially for Retyped packages, that prevents embedded declaration files from being used - they do have generic entities declared, but Bridge references them as non-generic ones.

### Steps To Reproduce

https://deck.net/a2634bd2e79571405b5672890b5dda7b

```csharp
public class Program
{
    public Optional<string> Str;
}

[External]
[IgnoreGeneric]
public class Optional<T>
{
}
```

### Expected Result (TypeScript)

```ts
/// <reference path="./bridge.d.ts" />

declare module Demo {
    export interface Program {
        Str: Demo.Optional<string>;
    }
    export interface ProgramFunc extends Function {
        prototype: Program;
        new (): Program;
    }
    var Program: ProgramFunc;
}

```

### Actual Result (TypeScript)

```ts
/// <reference path="./bridge.d.ts" />

declare module Demo {
    export interface Program {
        Str: Demo.Optional;
    }
    export interface ProgramFunc extends Function {
        prototype: Program;
        new (): Program;
    }
    var Program: ProgramFunc;
}
```

**Comment by vladsch** [comment]
AllowInTypeScript property should help
```
[IgnoreGeneric(AllowInTypeScript = true)]
```

**Comment by AndreyChechel** [comment]
Thanks, that's exactly what I need.
