### ISSUE TITLE
Support for: var x = x ?? throw new ArgumentNullException("x");     

### ISSUE THREAD

**Issue by danieldegtyarev** [bridgedotnet/Bridge#3218]
Please, support modern way to check for null

```
public class Foo
{
    object x;
    
    public Foo(object x)
    {        
        this.x = x ?? throw new ArgumentNullException(nameof(x));               
    }
}
```

**Comment by geoffreymcgill** [comment]
C#7 syntax support is being tracked in #2455.

Support for [Throw Expressions](http://structuredsight.com/2016/09/01/c-7-additions-throw-expressions/) will be included in that issue.

We will post an update here once Throw Expressions are supported, but I'm going to close this issue as support will be tracked in #2455.
