### ISSUE TITLE
devicePixelRatio missing

### ISSUE THREAD

**Issue by PluginIO** [bridgedotnet/Bridge#3219]
The property devicePixelRatio seems to be missing from the Bridge.HTML5 Window definitions.

https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

**Comment by AndreyChechel** [comment]
You'd probably want to try **Retyped.dom** package.  the property `devicePixelRatio` is available there:

- https://retyped.com/?q=Retyped.dom#search
- [lib.dom.d.ts (see line 13123)](https://github.com/Microsoft/TypeScript/blob/1a579d929f1d0ee4d45de7cee505970a24a40cc7/lib/lib.dom.d.ts#L13123)
