### ISSUE TITLE
Rework NuGet Package building process

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#323]
Remove dependency on separate Packaging process.
#744

**Comment by DanTup** [comment]
For now, it's possible to overwrite the contents of the packages to get a recent build (though this doesn't update the nupkg) using the script in #321. For Windows, you can create a `.cmd` file with the following (you may need to update paths)

```
copy .\Bridge\Html5\bin\Debug\*.dll .\..\MyBridgeProject\packages\Bridge.1.7.0\lib\net40
copy .\Bridge\Html5\bin\Debug\*.xml .\..\MyBridgeProject\packages\Bridge.1.7.0\lib\net40
copy .\Bridge\Html5\bin\Debug\*.pdb .\..\MyBridgeProject\packages\Bridge.1.7.0\lib\net40\pdb

copy .\Bridge\Html5\bin\Debug\*.dll .\..\MyBridgeProject\packages\Bridge.1.7.0\lib\net45
copy .\Bridge\Html5\bin\Debug\*.xml .\..\MyBridgeProject\packages\Bridge.1.7.0\lib\net45
copy .\Bridge\Html5\bin\Debug\*.pdb .\..\MyBridgeProject\packages\Bridge.1.7.0\lib\net45\pdb

copy Builder\Build\bin\Debug\*.dll .\..\MyBridgeProject\packages\Bridge.1.7.0\tools
copy Builder\Build\bin\Debug\*.xml .\..\MyBridgeProject\packages\Bridge.1.7.0\tools
copy Builder\Build\bin\Debug\Bridge.Build.dll .\..\MyBridgeProject\packages\Bridge.1.7.0\tools\Bridge.Builder.dll
```

**Comment by fabriciomurta** [comment]
now that you mentioned it, we have an issue with the net40 folder logged here: #303. So if you have your project running, you don't really need to mind replacing the files on the net40 folder. :)

**Comment by geoffreymcgill** [comment]
NuGet package during `Release` build has been added. 

We're still running some tests, but marking as Closed.
