### ISSUE TITLE
BinaryReader.ReadChar problem and casting Arrays from base type to an array of a derived type throws an exception 

### ISSUE THREAD

**Issue by dmitsov** [bridgedotnet/Bridge#3234]
Hello, 
in our project in older versions of Bridge.NET we implemented our own BinaryReader class to serve our purposes, but switched to the Bridge.NET one after it was released. We use BinaryReader to read a serialized data file for our application, but we recently discovered that ReadChar only reads one byte for chars and chars are serialized in two bytes in our data file as it was serialized with the C# BinaryWriter class. We've come up with a work around but it's a good idea to report this issue. 

Second we also cast an array of a Base type to an array of a derived type.  I wasn't able to reproduce the bug in Deck.NET. I understand this is a vague description of the problem and will try to get some additional information for the cast issue.

**Comment by geoffreymcgill** [comment]
Hi @dmitsov – Thanks for the report. We'll look forward to your simplified sample(s) demonstrating how to reproduce the issue.

**Comment by dmitsov** [comment]
Hi, I was able to come up with a simplified test issue for the cast problem:
---------------------------------------------------------------

public class Program
{
    public class Base
    {
        public int z;
    }
    
    public class Foo: Base
    {
        public int x;
    }
    
    public class Bar: Foo
    {
        public int y;
    }
    
    public static Foo[] GetFoos()
    {
        return new Bar[4];
    }
    
    public static T[] CastTest<T>() where T: Base
    {
        
        return (T[])GetFoos();
    }
    
    public static void Main()
    {
        var msg = "Hello, World!";
        
        Foo[] foos = new Bar[3];
        Bar[] bars = CastTest<Bar>();
        
        Console.WriteLine(msg);
    }
}

**Comment by dmitsov** [comment]
Also this example works without a problem:
----------------------------------------------
public class Program
{
public class Base
{
public int z;
}

public class Foo: Base
{
    public int x;
}

public class Bar: Foo
{
    public int y;
}

public static Foo[] GetFoos()
{
    return new Bar[4];
}

public static T[] CastTest<T>() where T: Foo
{
    
    return (T[])GetFoos();
}

public static void Main()
{
    var msg = "Hello, World!";
    
    Foo[] foos = new Bar[3];
    Bar[] bars = CastTest<Bar>();
    
    Console.WriteLine(msg);
}
}

-----------------------------------------------

**Comment by dmitsov** [comment]
Actually I've just realised that the error we have is a runtime exception. We get an InvalidCastException with a message "Unable to cast T1[] to T2[]"

-------------------------
public class Program
{

    public class Base
    {
        public int z;
    }

    public class Foo: Base
    {
        public int x;
    }

    public class Bar: Foo
    {
        public int y;
    }

    public static Base[] GetFoos()
    {
        List<Base> bases = new List<Base>();
        
        for(int i = 0; i < 4; i++)
        {
            bases.Add(new Bar());
        }
        
        return bases.ToArray();
    }

    public static T[] CastTest<T>() where T: Base
    {

        return (T[])GetFoos();
    }

    public static void Main()
    {
        var msg = "Hello, World!";

        Foo[] foos = new Bar[3];
        Bar[] bars = CastTest<Bar>();

        Console.WriteLine(msg);
    }
}

**Comment by vladsch** [comment]
In .NET you will get the same InvalidCastException
https://dotnetfiddle.net/qpFMB5

**Comment by dmitsov** [comment]
I apologise. We didn't have that problem with past versions of Bridge.NET and I didn't think that it was like that in .NET
