### ISSUE TITLE
Missing BinaryReader.Position and potentially other properties/methods

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#3238]

**Comment by vladsch** [comment]
BinaryReady has no Position property
https://msdn.microsoft.com/ru-ru/library/system.io.binaryreader(v=vs.110).aspx

**Comment by geoffreymcgill** [comment]
@TriEdgeAI – Do you mean [Stream.Position](https://msdn.microsoft.com/en-us/library/system.io.stream.position(v=vs.110).aspx) property?

**Comment by TriEdgeAI** [comment]
My bad.
