### ISSUE TITLE
Implicit operator bypassed for [ObjectLiteral] types

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#3242]
If I have a class with an implicit operator that converts it into a string and then assign an instance of that class to a string variable then I expect the implicit operator to be called. For a class without `[ObjectLiteral]` this works but it does not for classes with `[ObjectLiteral]`.

### Steps To Reproduce

https://deck.net/5b041fe9f93f052aa697e4fa055a3bae

```csharp
public class Program
{
    public static void Main()
    {
        string msg = new MyString("Hello, World!");

        Console.WriteLine(msg);
    }
}

[ObjectLiteral(ObjectCreateMode.Constructor)]
public class MyString
{
    public MyString(string value)
    {
        Value = value;
    }

    public string Value { get; }

    public static implicit operator string(MyString value)
    {
        return (value == null) ? null : value.Value;
    }
}
```

### Expected Result

```js
Hello, World!
```

### Actual Result

```js
{
    "Value": "Hello, World!"
}
```

## See Also

* https://forums.bridge.net/forum/bridge-net-pro/bugs/4945-implicit-operator-bypassed-for-objectliteral-types

**Comment by fabriciomurta** [comment]
This has been merged to integration branch and will make it to next Bridge release (16.5.0).
