### ISSUE TITLE
TimeSpan.Equals throws when passed value

### ISSUE THREAD

**Issue by Porl91** [bridgedotnet/Bridge#3249]
When you pass any value that isn't another **TimeSpan** to `TimeSpan.Equals` it throws a JS error.

Reproduced here: https://deck.net/c801d809d6c8f68ef82213c1ab14f290

### Expected Result
```
false
```

### Actual Result
JS error

**Comment by fabriciomurta** [comment]
The issue has been fixed and merged upstream. It will make it to Bridge 16.5.0!
