### ISSUE TITLE
ObjectCreateMode.Constructor with struct fails

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#3251]
### Steps To Reproduce

https://deck.net/f43d0205abaa2e0e0871d79dcaff9147

```csharp
[ObjectLiteral(ObjectCreateMode.Constructor)]
public struct PlaceKey 
{
      public PlaceKey(int i)
      {
      }
}
```

### Actual Result

```js
[ObjectLiteral] with Constructor mode should be inherited from a class with the same options
```

## See Also

* https://forums.bridge.net/forum/bridge-net-pro/bugs/4938-objectcreatemode-constructor-with-struct-fails

**Comment by fabriciomurta** [comment]
Pull request merged to our integration branch and working fine. It made it to Bridge 16.5.0!

**Comment by fabriciomurta** [comment]
The fix applied for this issue triggers a unit tests' failure in Bridge.Newtonsoft.Json at [JsonConstructorTests.cs:95](https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/blob/dev/Tests/Newtonsoft.Json.Tests/Tests/JsonConstructorTests.cs#L95)

**Comment by fabriciomurta** [comment]
@vladsch fixed directly in the newtonsoft json branch, at this commit:
bridgedotnet/Bridge.Newtonsoft.Json~7e81481716cf772dc20a36a84671be98d4b0008b
