### ISSUE TITLE
"CanWrite" of GetProperty returns True when should be False

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#3253]
In .NET, when the `CanWrite` property of a read-only auto-property returns False but in Bridge code it returns True - eg.

### Steps To Reproduce

https://deck.net/20da1af33b518a35b9ec06c4ea698218

```csharp
public class Program
{
    public static void Main()
    {
        var person = new Person(123, "Dan");
        var idProperty = typeof(Person).GetProperty("Id");
        Console.WriteLine("CanWrite: " + idProperty.CanWrite);
    }
}

public class Person
{
    public Person(int id, string name)
    {
        Id = id;
        Name = name;
    }
    public int Id { get; }
    public string Name { get; }
}
```

## See Also

* https://forums.bridge.net/forum/bridge-net-pro/bugs/4932-canwrite-of-getproperty-returns-true-when-should-be-false

**Comment by fabriciomurta** [comment]
Fix merged upstream, will make it to Bridge 16.5.0!
