### ISSUE TITLE
Nrefactory ? Roslyn 

### ISSUE THREAD

**Issue by beyaz** [bridgedotnet/Bridge#3266]
Do you have any plan for replace Nrefactory tree with Roslyn ?
for better syntax tree and support c# 7.x future?

**Comment by fabriciomurta** [comment]
Hello!

We already use roslyn but obviously we still base some thing in NRefactory. We do have plans on replacing it for Roslyn and we're gradually moving code to Roslyn as we can, so we're walking towards a 100% roslyn based approach. I can't exact you how far we are from it without a chat with @vladsch or @geoffreymcgill and @AndreyChechel, but I know we are going for it.
