### ISSUE TITLE
Decimal arguments are not translated correctly.

### ISSUE THREAD

**Issue by alexkates** [bridgedotnet/Bridge#3267]
A C# method with decimal arguments does not produce a javascript method with those decimals wrapped in System.Decimal

### Steps To Reproduce

https://deck.net/88ff64cb03e8ec29ba6475d9e1264a67 <-- Replace with a link to your Deck

```csharp
public class Program
{
    public static decimal Demo(decimal a, decimal b)
    {
        return a * b;
    }
}
```

### Expected Result

```js
/**
 * @compiler Bridge.NET 16.5.0
 */
Bridge.assembly("Demo", function ($asm, globals) {
    "use strict";

    Bridge.define("Demo.Program", {
        statics: {
            methods: {
                Demo: function (a, b) {
                    return System.Decimal(a).mul(System.Decimal(b));
                }
            }
        }
    });
});
```

### Actual Result

```js
/**
 * @compiler Bridge.NET 16.5.0
 */
Bridge.assembly("Demo", function ($asm, globals) {
    "use strict";

    Bridge.define("Demo.Program", {
        statics: {
            methods: {
                Demo: function (a, b) {
                    return a.mul(b);
                }
            }
        }
    });
});
```

**Comment by vladsch** [comment]
It expected the result. Demo method expects decimal arguments (already wrapped values), it should not wrap inside own body.

**Comment by alexkates** [comment]
@vladsch Imagine the Demo method is part of a public API, perhaps an NPM package. How would a consumer use this method?

**Comment by vladsch** [comment]
In this case, developer who uses the method should create decimal values and pass it to the method
```cs
Demo.Program.Demo(System.Decimal(1), System.Decimal(2));
```

The same logic as for any other public api method. What difference if method accepts string or any another type? You have to provide instances of correct type.

**Comment by alexkates** [comment]
That would imply that the developer needs to know about bridge.js. Is that the intended use?

**Comment by vladsch** [comment]
What difference between bridge and any other public api? Before using any API you need to know about its contract.

**Comment by vladsch** [comment]
For example, you have method
```cs
public static bool Demo(string a, int b);
```

Will you use such method as
```cs
Demo({}, false);
```

If yes then your method signature should use `object` instead `string` and check type during invocation

**Comment by alexkates** [comment]
No of course not. I wouldn't expect the client of an API to call `Demo(decimal a, decimal b)` as `Demo(System.Decimal(1), System.Decimal(2))` either. I think those details should be hidden from the user.

Along with my example mentioned earlier about `int` types, here is an example with mixed types. The decimal conversion is being handled in the body as expected. https://deck.net/0d31fe3caa906912bcb04d564de441ae

**Comment by vladsch** [comment]
Just as I understood you correctly, you worried if a developer pass simple number to Demo method
```js
Demo.Program.Demo(1,2);
```

But it is a violation of contract. Demo accepts decimal only, not any other numbers.

**Comment by vladsch** [comment]
>  I wouldn't expect the client of an API to call Demo(decimal a, decimal b) as Demo(System.Decimal(1), System.Decimal(2)) either.
Why not? Is decimal type something known for javascript developers? Why will simple numbers be used instead of special type for invocation? Demo expects decimal, not integer or string.

**Comment by alexkates** [comment]
If you could please take a look at the few examples I've linked and comment on the consistency. In some cases such as int, bridge will do the conversion but in other cases such as decimal, bridge expects the consumer to do the conversion.

**Comment by vladsch** [comment]
Bridge doesn't do any conversion, just javascript decimal library was designed to accept any number to own methods. But Bridge always converts one type to expected

If you have method
```cs
public static decimal Demo(decimal a, decimal b)
```

and try to use it as
```cs
Demo(1,2);
        
int i = 1;
Demo(i, i);
```

then Bridge will produce the following js code
```js
emo.Program.Demo(System.Decimal(1), System.Decimal(2));

var i = 1;
Demo.Program.Demo(System.Decimal(i), System.Decimal(i));
```

**Comment by vladsch** [comment]
Decimal is not integer or double. It is another type. Why do you want to allow accepts integers instead decimal? Why don't you expect float values if a method accepts integers?

```cs
public static decimal Demo(int a, int b)
```

Is it expected in javascript? Should developer know that method accepts integers only or Demo method should converts float to int automatically?
```js
Demo.Program.Demo(Math.PI, 0.33333);
```

**Comment by vladsch** [comment]
Another point, please note that Demo method returns decimal result. So, developer should know about bridge.js to use the result.

**Comment by fabriciomurta** [comment]
Maybe if Decimal had an implicit cast implementation from Int, Double and other base types, this would just work? Probably the cast should throw an exception in case the passed value exceeds maximum decimal base (according to https://msdn.microsoft.com/en-us/library/a69w9ca0(v=vs.110).aspx).

**Comment by vladsch** [comment]
I guess the question that should Bridge supports any other types which can be converted to decimal (the same question for long types). If yes then special conversion code should be emitted to begin of method's body with decimal/long parameters.

**Comment by alexkates** [comment]
If I'm using bridge to generate javascript that will then be published as an npm package, I don't think it's reasonable to force consumers of that package to have to know bridge. I can get around this by adding a facade in front of the generated javascript, but after seeing that some value handle this already and decimal did not, I thought it was worth bringing up.

**Comment by vladsch** [comment]
In this case, what do you think about return result? It will be decimal (wrapped by System.Decimal class) and such value cannot be used in native math operations (like +-*/). So, in any way consumer of that package should know about bridge.

**Comment by alexkates** [comment]
I would expect the value to be returned.

**Comment by vladsch** [comment]
What kind of value? Decimal or native javascript number?

**Comment by geoffreymcgill** [comment]
There are a couple things we might be able to do help this scenario, but automatically converting the **number** type into **System.Decimal** type is not one of them.

First and easiest for us to implement is improving the accuracy of the generated **.d.ts**. Regarding your original sample, the `Demo` method is declared by Bridge as accepting and returning a **number** type. I consider this a defect.

Here's the original **.d.ts** statement for `Demo`:

```ts
Demo(a: number, b: number): number;
```

This defect could easily lead to the scenario you describe where an end user of the API passing in a native JavaScript **number** value. 

The **.d.ts** should be corrected in the Bridge compiler to accept and return **System.Decimal** types:

```ts
Demo(a: System.Decimal, b: System.Decimal): System.Decimal;
```

The second item that we might be able to implement is a new feature for automating the insertion of Type Guards. We might be able to implement a [Rule](https://github.com/bridgedotnet/Bridge/wiki/attribute-reference#rules) to cover this scenario.

The TypeGuard Rule would only run some extra checks to ensure the incoming values are of the correct type. The Rule would not convert a numeric type into Decimal as passing in the correct object type to a Method is the expected result, just like in native .NET.

**Comment by geoffreymcgill** [comment]
The **Number** type is also available if you include [Retyped](https://retyped.com) into your project.

The following sample demonstrates creating an overload on the `Demo` method that accepts either a **Number** or **Decimal** type argument. 

https://deck.net/e254292bb803bab3a0c08335066216c6

```csharp
using System;
using Bridge;
using Retyped.Primitive;

public class Program
{
    public static void Main()
    {
        Number a = 2; 
        Number b = 4;
        
        var val1 = Demo(a, b);
        
        Console.WriteLine(val1);
        
        decimal c = 2;
        decimal d = 4;
        
        var val2 = Demo(c, d);
        
        Console.WriteLine(val2);
    }
    
    public static Number Demo(Number a, Number b)
    {
        return a * b;
    }
    
    public static decimal Demo(decimal a, decimal b)
    {
        return a * b;
    }
}
```

Maybe using the **Retyped.Primitive.Number** type can help with your scenario?

**Comment by geoffreymcgill** [comment]
Here's another option using a generic `Demo<T>` with some internal type checks. 

https://deck.net/cfcfbfbd0095251460cb8b2ef6da6604

```charp
using System;
using Bridge;
using Retyped.Primitive;

public class Program
{
    public static void Main()
    {
        Number a = 2; 
        Number b = 4;
        
        var val1 = Demo(a, b);
        
        Console.WriteLine(val1);
        
        decimal c = 2;
        decimal d = 4;
        
        var val2 = Demo(c, d);
        
        Console.WriteLine(val2);
    }
    
    public static T Demo<T>(T a, T b)
    {
        if (typeof(T) == typeof(decimal))
        {
            return (a.As<decimal>() * b.As<decimal>()).As<T>();
        } 
        else if (typeof(T) == typeof(Number))
        {
            return (a.As<Number>() * b.As<Number>()).As<T>();
        }
        
        throw new Exception("no work");
    }
}
```

Hope this helps.

**Comment by geoffreymcgill** [comment]
Issue #3276 has been opened to track the non-specific .d.ts types defect.

**Comment by geoffreymcgill** [comment]
Closing this issue as no further responses have been received. Please feel free to comment again in the future if there is a need to re-open.
