### ISSUE TITLE
Type inference on generic interface generates invalid javascript "SyntaxError: Unexpected token ?"

### ISSUE THREAD

**Issue by badcommandorfilename** [bridgedotnet/Bridge#3269]
The compiler seems to output a '?' as a typename when a method doesn't explicitly specify the type arguments for a generic interface. I'm not sure if this is related to the type constraints on the interface and method, but that's how I encountered the problem.

Most confusingly, this outputs invalid javascript code and doesn't raise a compiler error or a warning, but instead emits bad JS. This causes a NullReferenceException during minification (if enabled), so it's hard to track down the problem - see #3039 

Note that there is a workaround - if you manually specify the generic type on the method it will output the correct type and minify fine.

### Steps To Reproduce

https://deck.net/41faaf30032ce40e5efd7aef359725b4

```csharp
public class Program
{
        [Ready]
        public static void Start()
        {
            ///To introp with a library, we have to register a function to construct objects
            ///As an example, AlloyEditor and CKEditor seem to use this pattern to register plugins
            var registry = Script.Get("ThirdPartyJSLib").ToDynamic(); 

            ///Type inference of the factory interface causes a compiler error
            RegisterFactory(new CavyFactory(),registry);

            ///Manually specifying the type works
            //RegisterFactory<Cavy>(new CavyFactory(), registry);
        }

        public static void RegisterFactory<T>(IFactory<T> factory, dynamic registry) where T : Animal
        {
            dynamic ctor = factory.Builder();

            registry[factory.FactoryName] = Script.ToPlainObject(ctor);
        }
}
```
 Thanks for all your hard work - this is the first problem we've had with Bridge.Net and it has otherwise been an excellent experience so far!

**Comment by geoffreymcgill** [comment]
Hi @badcommandorfilename – Thanks for reporting this issue. We will investigate and try to fix right away. Looks like this should be an easy fix.

**Comment by fabriciomurta** [comment]
A clearer test case for this issue would be this:
https://deck.net/08602ce50a0a3fa2dba0d872cea933de

C#
```csharp
public class App
{
    public static void Main()
    {
        dynamic x = 5.ToDynamic();
        Instantiate(x);
    }
    
    public static void Instantiate<T>(dynamic trigger)
    {
    }
}
```

Which, in Bridge 16.5.0, generates:
```javascript
/**
 * @compiler Bridge.NET 16.5.0
 */
Bridge.assembly("Demo", function ($asm, globals) {
    "use strict";

    Bridge.define("Demo.App", {
        main: function Main () {
            var x = (5);
            Demo.App.Instantiate(?, x);
        },
        statics: {
            methods: {
                Instantiate: function (T, trigger) { }
            }
        }
    });
});
```

**Comment by fabriciomurta** [comment]
The fix has been merged to the integration branch and will make it to the next Bridge release (at the moment, 16.5.1 -- or whatever the issue milestone points to).
