### ISSUE TITLE
[User Request] NuGet package: Move license file to package root instead of project

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#327]
The discussion is within this thread: [Disable re-pulling of NuGet package files (such as deploy.bat) when updating?](http://forums.bridge.net/forum/community/help/311).

In short, the users don't think that the files not directly used by the project should not be pulled in every NuGet package update. In Bridge.NET case, the license file, and the two sample .bat files (clean and deploy). Probably also the README file.

This issue is for dealing with the License file, either:
- move it out of the folders that are copied into the project upon installation/upgrade
- provide users on the thread above a feedback about why Bridge.NET is not moving the file out of the project's files.

**Comment by geoffreymcgill** [comment]
The .bat files have been removed from the NuGet package, see issue #308.

**Comment by geoffreymcgill** [comment]
The **README.txt** and **LICENSE.txt** files are already being deployed to the recommended **/App_Readme/** location.
