### ISSUE TITLE
More specific types for generated .d.ts

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#3276]
Given the following sample, the generated .d.ts is specifying a `number` type, but it should be a `System.Decimal` type.

There may be other scenarios, especially where integer types are used, that should be updated to output specific types instead of `number`. A general review is required.

### Steps To Reproduce

https://deck.net/88ff64cb03e8ec29ba6475d9e1264a67

```csharp
public class Program
{
    public static decimal Demo(decimal a, decimal b)
    {
        return a * b;
    }
}
```

### Expected Result

```js
Demo(a: System.Decimal, b: System.Decimal): System.Decimal;
```

### Actual Result

```js
Demo(a: number, b: number): number;
```

## See Also

* #3267

**Comment by fabriciomurta** [comment]
Issue fixed and merged upstream. The fix will make it to 16.5.1 or newer (check issue milestone).
