### ISSUE TITLE
Bridge.Test unable to install from NuGet

### ISSUE THREAD

**Issue by PluginIO** [bridgedotnet/Bridge#3279]
I am unable to install the Bridge.Test package from NuGet either by the UI or console interfaces. Following the steps found at: https://github.com/bridgedotnet/Bridge/wiki/Bridge.Test-Overview#installation

### Steps To Reproduce

```
PM> Install-Package Bridge.Test
Install-Package : Unable to find package 'Bridge.Test'
At line:1 char:1
+ Install-Package Bridge.Test
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
```

### Expected Result

The expected result would be a successful installation of the Bridge.Test package into the project.

### Actual Result

Missing package error from Nu-Get package manager.

**Comment by fabriciomurta** [comment]
Hi! The Bridge.Test package is not available publicly yet! For now, just ignore those wiki documents, soon we'll release the packages!

**Comment by geoffreymcgill** [comment]
The **Bridge.Test** package is now available on NuGet. 

https://www.nuget.org/packages/bridge.test

Hope this helps.
