### ISSUE TITLE
Implement generic EventHandler<T> class 

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#328]
http://forums.bridge.net/forum/community/help/326-system-eventargs?p=338#post338

**Comment by fabriciomurta** [comment]
Duplicate of #326.

**Comment by geoffreymcgill** [comment]
Similar to #326. Just add the generic <T> member too.

**Comment by fabriciomurta** [comment]
Yes, my mistake. Was trying to keep one issue per forum thread but they are really different things I overlooked while reviewing this.

**Comment by fabriciomurta** [comment]
Pushed the fix in branch `328-eventHandlerSupport`. Will merge its implementation is what we need.
