### ISSUE TITLE
Using C++ in Bridge.Net

### ISSUE THREAD

**Issue by xa4atur** [bridgedotnet/Bridge#3280]
Hi!

I have C++ framework which I would like to use in my Bridge.NET project. Is it possible? Is there any restrictions?

Thanks!

**Comment by geoffreymcgill** [comment]
I don't think this would be possible. Bridge can only support parsing C# libraries.

**Comment by xa4atur** [comment]
What about managed C++/CLI? Is it possible to refer to C++/CLI project in Bridge.NET project?

**Comment by xa4atur** [comment]
Are you going to support parsing C++ libraries?

**Comment by samuelGrahame** [comment]
Hey @xa4atur you might be interested in http://webassembly.org/ - maybe when webassembly is production ready, you could link your javascript libraries to web assembly, just like c# com visible to c++/c

**Comment by xa4atur** [comment]
@samuelGrahame thank you, but unfortunately webassembly is not suitable for me

**Comment by samuelGrahame** [comment]
technically, if you had the source code of the c++ library you could convert it to c#

**Comment by xa4atur** [comment]
@samuelGrahame I can convert C++ code to C# using SWIG or wrap it using C++/CLI, but I need t o link source C++ classes in that cases. And how Bridge.NET will convert SWIG or C++/CLI code to JavaScript?

**Comment by xa4atur** [comment]
Some C++ libraries should not be converted  to JavaScript, beacuse I am going to use them on server side. I hope I can create C++/CLI project and refer to it from Server project, can I?

**Comment by fabriciomurta** [comment]
I don't see a problem in running the c++ libraries from server side, but I believe you'll have a binary wrapper on the server. So they will be pretty much two separate/built projects.

Bridge could build from C# the client-side code, and maybe some server-side nodejs code, but then at some point a call will have to happen to your binary server/side code, linked to the c++ libraries.

But there's no linking from javascript to DLLs, is there?
By current Bridge implementation, it is based on Roslyn, which is a C# and VB analyzer. But can't say it is impossible, just not implemented currently.

So in summary:
- bridge can build javascript code out of c# code
- it can't from vb, but shouldn't be too far from supporting it, just not tested
- there's no implementation to support c++ in bridge currently, but that would be a matter of mapping the roslyn calls to a c++ code analyzer and wiring things up (the challenge here is uncertain)
- there's a list of code analyzers and their github project pages from microsoft here: http://microsoft.github.io/CodeAnalysis/ (but I see the c++ part says "it will be placed here", so stay tuned!)
- bridge can't build javascript from binaries from any platform -- so we can't just link built DLLs -- that would be a very neat feature, but very low-level-ish and a lot of abstraction like loops, objects, would have to be "guessed" from assembly instructions
- it is possible to have Bridge interact with other projects not built by bridge, for example, with server-side calls, ajax and async requests (being a project a Bridge.NET project and then the other, a server-side or web service project

I hope this helps you understand the scenario. I think your goal is very interesting and can be currently attained with what Bridge has to offer -- just not in the same "Visual Studio project", but in the same VS solution. :)

**Comment by xa4atur** [comment]
@fabriciomurta thank you for detailed answer. 

The point is that I have 3D webgl viewer which has written in C++. I use emscripten to convert it to JavaScript. I thought that I can use Bridge.NET to develop frontend using C# instead of JavaScript.
And I assumed that I can convert my C++ viewer to C# via SWIG or C++/CLI in order to use in client side.
