### ISSUE TITLE
Missing Type.IsPrimitive

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#3283]

**Comment by fabriciomurta** [comment]
[System.Type.IsPrimitive](https://docs.microsoft.com/en-us/dotnet/api/system.type.isprimitive?view=netframework-4.5#System_Type_IsPrimitive) on docs.microsoft.com.

Thanks for this one!

**Comment by TriEdgeAI** [comment]
Just realized I already submitted this one before :)

Duplicate of #2522. Closing.
