### ISSUE TITLE
Remove System.DateTime.$is checks on gte, gt, lte, and lt operators

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#3285]
Performance penalty on `System.DateTime.$is` type checking. Remove is unnecessary. 

## See Also 

* https://forums.bridge.net/forum/bridge-net-pro/bugs/5012-massive-performance-problem-on-datetime-comparison-functions

**Comment by vladsch** [comment]
$is is absolutely required because in C# we use System.DateTime but on client side just Date. I will replace code inside $is by instanceof, it should gain the performance.

**Comment by fabriciomurta** [comment]
Vlad pull request has been merged `dev` and made it to bridge 16.5.1!
