### ISSUE TITLE
problems with comparisons with DateTime.MaxValue

### ISSUE THREAD

**Issue by bktv** [bridgedotnet/Bridge#3293]
DateTime.Now is not less than DateTimeMax

### Steps To Reproduce

https://deck.net/a8ee5cc48040240fed516dd0d0cf503a

```csharp
public class Program
{
    public static void Main()
    {
        if ( DateTime.Now < DateTime.MaxValue )
        {
            Console.WriteLine("now is smaller than DateTime.MaxValue");
        }
        else
        {
            Console.WriteLine("now is bigger than DateTime.MaxValue");
        }

The js generated looks fine.  The lt operator returns the wrong result as the program prints out
"now is bigger than DateTime.MaxValue"

**Comment by fabriciomurta** [comment]
Thanks for reporting the issue! We've reproduced it, and are undergoing tests on a possible fix that may just make it to the next Bridge release.

**Comment by fabriciomurta** [comment]
The fix has just been merged in our integration branch, it will make it to the Bridge version corresponding to the milestone attached to this issue (16.5.1 at the time of this comment).
