### ISSUE TITLE
Idea: Script.IsDefined() overload that accepts a delegate

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#3296]
With an overload like that we'll be able to write code like this:
```csharp
if(Script.IsDefined(Window.RequestAnimationFrame))
{
    //...
}
```

**Comment by vladsch** [comment]
The problem that there are few methods `Window.RequestAnimationFrame` with different parameters.
You have to define which exact method you need and compiler will be happy after that
```cs
if(Script.IsDefined((Func<Action,int>)Window.RequestAnimationFrame)) 
```

Overload will not help (and not required) without such cast.

**Comment by TriEdgeAI** [comment]
Got it, thanks!
