### ISSUE TITLE
Exceptions originated from plugins

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#3297]
The following commit transformed an error message displayed in Error List for an exception thrown by a Bridge Plugin. Instead of showing an actual error message, a generic message is always shown.

https://github.com/bridgedotnet/Bridge/pull/3233/commits/350de4136b20aeccf31aedb2e0c6324d2ef02892#diff-ae4d6e9ddce0cb68f020138f6847237cL176

```cs
// before:
this.Log.LogError(null, null, null, ee.FileName, ee.StartLine + 1, ee.StartColumn + 1, ee.EndLine + 1, ee.EndColumn + 1, "Error: {0} {1}", e.Message, e.StackTrace);

// after:
this.Log.LogError(null, null, null, ee.FileName, ee.StartLine + 1, ee.StartColumn + 1, ee.EndLine + 1, ee.EndColumn + 1, ee.ToString());
```

Looks like a misprint - `ee.ToString()` should be corrected to `ex.ToString()`.

- `ee` here is **EmitterException** having a generic error message;
- `ex` is the original exception containing the message explaining the actual reason of failure;

### Expected Result

For a Bridge Plugin containing `throw new Exception("Expected Error Description.");`, the following error appears in Visual Studio Error List panel:

```
Error Description:
Expected Error Description.
```

### Actual Result

For a Bridge Plugin containing `throw new Exception("Expected Error Description.");`, the following error appears in Visual Studio Error List panel:

```
Error Description:
Bridge.Contract.EmitterException: Exception of type 'Bridge.Contract.EmitterException' was thrown.
```

**Comment by AndreyChechel** [comment]
Actually I'd vote for returning to the original approach:
```cs
... "Error: {0} {1}", ex.Message, ex.StackTrace);
```

Because `ex.ToString()` adds an exception type name at the very beginning of the message and that could make no sense for end users if the exception is not common one and its type is declared in a Plugin.

**Comment by fabriciomurta** [comment]
Your implementation has been merged to the integration branch and will make it to Bridge 16.6.0. It affected the Bridge.Test project that needed to include the implementation demanded by the change in the interface.
