### ISSUE TITLE
NullReferenceException calling CultureInfo constructor

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#330]
While trying to parse some dates (which led to #329), we noticed that we get errors when trying to use the `CultureInfo` constructor. [Live example here](http://live.bridge.net/#b2a88e44d05088157ac7).

```
public class App 
{ 
    [Ready] 
    public static void Main() 
    {
        new CultureInfo("en-US");
    }
}
```

Reports `Finished with error(s)`:

```
// Line 0, Col 0 : Object reference not set to an instance of an object.
```

Seems like an error during compilation?

**Comment by DaniilVeriga** [comment]
Thank you for the report. Not a bug in Bridge, just an issue in the live compiler.

To fix I added `using System.Globalization;` to the live compiler.

**Comment by DaniilVeriga** [comment]
The colleague just said me that there is another problem as well. I am reopening the issue.

**Comment by DanTup** [comment]
> Thank you for the report. Not a bug in Bridge, just an issue in the live compiler.

We actually had an issue trying to find this in our project. We just tried the same code in the live compiler and had an issue too (assumed it was the same).

If you need more info on the original issue, let me know and we'll get an isolated repro.

**Comment by vladsch** [comment]
>If you need more info on the original issue, let me know and we'll get an isolated repro.

**Comment by DanTup** [comment]
@vladsch Thanks for this, the latest code works as expected for supported cultures.

We could do with some additional cultures (en-GB, Spanish, and the Scandinavian areas); would you accept a PR? Is it just a case of creating extra .js files in that Locales folder?

Is it worth making the `CultureInfo` constructor throw if an unknown culture is provided? Currently it will silently do something different to what the user expects - if we had a calendar control (which we do!) and are en-GB and the dates come back as mm/dd/yyyy, then when we send them to the server, we will parse the wrong incorrectly. I think it would be better to fail early, so it's less likely to be an obscure bug down the line? (of course, the ideal would be to support all cultures that server-side .NET does)

**Comment by vladsch** [comment]
We will appreciate if anyone contribute locales.
At this moment, yes, it is need to create locale js file. Such file should be attached manually to your html page. I guess we will change process of locales attaching to more convenient case

About constructor exception, yes, we should repeat .NET functionality as much as possible

**Comment by DanTup** [comment]
Is it worth re-opening this case as a request to handle invalid/not-loaded cultures better (fail immediately, instead of returning an invalid `CultureInfo`)? This will also make it easier if people don't realise they need to explicitly pull the culture files in.

**Comment by LeonidVeriga** [comment]
Created a separate issue as this one is marked as live in 1.8
