### ISSUE TITLE
Uri.ToString() returns "[Object object]"

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#3301]
This code behaves differently in .NET/Bridge:

```cs
Console.WriteLine(new Uri("https://deck.net/").ToString());
```

.NET outputs `https://deck.net/` but Bridge outputs `[object Object]`. A workaround is to use `.AbsoluteUri`.

DotNetFiddle: https://dotnetfiddle.net/wLkrNq
Deck: https://deck.net/c401a826ae10dadcd131b6c61bbe71c5

**Comment by michaelcheers** [comment]
# See Also:  #

   - #1457

**Comment by fabriciomurta** [comment]
System.Uri is actually just a stub and there's well, just everything to be done in it in order for it to be considered and expected to match .NET. Issue #2185 is tracking its full support implementation.

**Comment by fabriciomurta** [comment]
The fix is implemented, but please notice the class has limited functionality still, which is being tracked by the issue mentioned above.
