### ISSUE TITLE
Bridge.ready is implemented incorrectly

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#3303]
```javascript
if (typeof Bridge.global.jQuery !== "undefined") {
    Bridge.global.jQuery(delayfn);
} else {
    if (typeof Bridge.global.document === "undefined" || Bridge.global.document.readyState === "complete" || Bridge.global.document.readyState === "loaded") {
        delayfn();
    } else {
        Bridge.on("DOMContentLoaded", Bridge.global.document, delayfn);
    }
}
```

This is part of the implementation of `Bridge.ready`. If you look closely you'll notice that the check is for `readyState === "complete"`, however `DOMContentLoaded` actually gets raised once the state becomes `interactive`, which is before it becomes `complete`.

Therefore it is possible to have the following situation:
1. Page begins loading
2. readyState = interactive
3. `DOMContentLoaded` is raised
4. I add a dynamic `<script>` tag to the page, pointing to some transpiled code
5. The script loads and attempts to initialize a Bridge assembly
6. The script contains a Main method
7. The Main method gets passed to `Bridge.ready`
8. `Bridge.ready` checks the readyState and since it's not equal to `complete` it goes into the `else`
9. The Main method is now subscribed to `DOMContentLoaded`, however we were already past that, so it will NEVER be invoked
10. I am sad

**Comment by TriEdgeAI** [comment]
Basically just make it check for `interactive` instead.

**Comment by vladsch** [comment]
Can you create test case in deck which is demonstrated the described situation?

**Comment by TriEdgeAI** [comment]
Not possible, I need to give you one javascript file that dynamically loads a javascript file made by Bridge.NET.

**Comment by TriEdgeAI** [comment]
Actually I was able to make a Deck.NET example. There you go:
https://deck.net/862aeb3a9b22c783a52ff79e875832b4

# Current Output
During Demo.Main: interactive
Right before introducing Demo2: interactive

# Expected Output
During Demo.Main: interactive
Right before introducing Demo2: interactive
During Demo2.Main: interactive

You can achieve the expected output by removing `//@ jQuery = undefined;` which will allow Bridge.NET to rely on jQuery for it's `ready` method. However when jQuery is not present, Bridge.NET will rely on it's own implementation of the `ready` method which is incorrect, as explained above.

**Comment by TriEdgeAI** [comment]
I'd say that's a `defect` not a `feature` :P

**Comment by fabriciomurta** [comment]
The issue has been fixed and merged, it will make it to the next bridge release, pointed by this issue's milestone (currently 16.6.0)!
