### ISSUE TITLE
Adjusting a DateTime and then calling 'new DateTime(ticks, kind)' returns wrong time

### ISSUE THREAD

**Issue by yctri** [bridgedotnet/Bridge#3306]
When adding time to an existing UTC DateTime and then using the DateTime(ticks, kind) constructor to reconstruct the same DateTime, the new instance no longer appears to reflect UTC time.

### Steps To Reproduce

https://deck.net/3f7aea2477c59ccd77b658b0016f9752

```csharp
public class App
{
    public static void Main()
    {
        DateTime dt = DateTime.UtcNow;
        
        Console.WriteLine(dt);    // Outputs 12/11/2017 22:57:38
        
        dt = dt.AddMinutes(1);
        dt = new DateTime(dt.Ticks, dt.Kind);
        
        Console.WriteLine(dt);    // Outputs 12/11/2017 14:58:38 
    }
}
```

### Expected Result

12/11/2017 22:57:38
12/11/2017 22:58:38

### Actual Result

12/11/2017 22:57:38
12/11/2017 14:58:38

**Comment by fabriciomurta** [comment]
The issue got closed by an issue's side effect message and I missed posting the feedback here! Glad I added the "in progress" tag to the issue. :)

Anyways, it is already live in latest published Bridge, 16.6.1! Thanks for the fix!
