### ISSUE TITLE
array.GetType().Name returns wrong name

### ISSUE THREAD

**Issue by danieldegtyarev** [bridgedotnet/Bridge#3318]
Should return Foo[], returns Foo instead

### Steps To Reproduce

Please compare
https://deck.net/2b53a4e73b8881e66b5136f1f00515c8
https://dotnetfiddle.net/aB0q7l

```csharp
public class Foo{   
}

public class Program
{
    public static void Main()
    {
        var array = new Foo[10];
        System.Console.WriteLine(array.GetType().Name);
    }
}
```

### Expected Result

```js
Foo[]
```

### Actual Result

```js
Foo
```

**Comment by fabriciomurta** [comment]
Fixed! This will be part of our next Bridge release (refer to the milestone attached to this issue).
