### ISSUE TITLE
Structs don't copy while used as objects.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#3320]
Structs don't copy while used as generics.
**EDIT:**  It is actually generic which has the problem, not objects.

### Steps To Reproduce

https://dotnetfiddle.net/3H9Qng
https://deck.net/3c8662adc2c3d840a8064cfacb874036/third

```csharp
public static class Program
{	
    public struct A { }
    public static void Function<T>(T obj)
    {
        var obj2 = obj;
	Console.WriteLine(object.ReferenceEquals(obj, obj2) + " should equal False.");
    }	
    public static void Main() => Function(new A());
}
```

**Comment by vladsch** [comment]
Packed structure shouldn't be copied on assignment because it is already object. .Net sample is provided by you gives true for ReferenceEquals.

**Comment by michaelcheers** [comment]
@vladsch, sorry generic.

**Comment by geoffreymcgill** [comment]
@michaelcheers - It's best to use https://deck.net for samples.
