### ISSUE TITLE
Cloning 2D arrays and casting back doesn't work

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#3321]
Cloning 2D arrays and casting back doesn't work.

### Steps To Reproduce

https://deck.net/5e95b5d06c9bce30483606e5321877d4/third

```csharp
public class Program
{
    public static void Main()
    {
        var n = (int[,])new int[0, 0].Clone();
    }
}
```

Should not show error.

**Comment by fabriciomurta** [comment]
Done! Just merged to our next version branch! Thanks for the straightforward report!
