### ISSUE TITLE
'is' throws exception on non-nullable

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#3323]
`is` throws exception on non-nullable.

### Steps To Reproduce

https://deck.net/0483b993ab9e338a588fe48f590f5427/third
https://dotnetfiddle.net/ppxbRV

```csharp
public class Program
{
    public static void Main()
    {
        int? val = null;
        Console.WriteLine(val is int);
    }
}
```

should show no error.

**Comment by fabriciomurta** [comment]
We've just merged in the fix for this issue in our development branch! It will make it to the next Bridge release (see milestone, version 16.7.0 at the time this message was sent).
