### ISSUE TITLE
GetType doesn't throw exception on null

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#3324]
GetType doesn't throw exception on null.

### Steps To Reproduce

https://deck.net/a2b9050ca543182d63cf105bd5f24dbd/third
https://dotnetfiddle.net/BYjLfl

```csharp
public class Program
{
    public static void Main()
    {
        float? v = null;
        Console.WriteLine(v.GetType().FullName);
    }
}
```

should throw exception.

**Comment by fabriciomurta** [comment]
Fixed and merged upstream! The fix will make it to the next Bridge release (see attached milestone).
