### ISSUE TITLE
Support for Type.IsValueType

### ISSUE THREAD

**Issue by DierkDroth** [bridgedotnet/Bridge#3329]
Appears [Type.IsValueType](https://docs.microsoft.com/en-us/previous-versions/windows/apps/k1by9z3f(v=vs.105)?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Type.IsValueType)%3Bk(DevLang-csharp)%26rd%3Dtrue) is not supported in Bridge.NET 16.6.0.

Any chance to get this added?

**Comment by fabriciomurta** [comment]
Thanks for the heads up, @DierkDroth! The idea is to support everything, and we gradually do, whenever feasible. We'll update here as soon as we develop support for this in Bridge!

**Comment by fabriciomurta** [comment]
This feature has been just merged to Bridge's integration branch! It will make it to Bridge 16.7.0 (or whatever milestone attached to this issue).

**Comment by DierkDroth** [comment]
Thanks @fabriciomurta
