### ISSUE TITLE
InvalidCharacterError in Microsoft Edge

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#3331]
Iteration through an HTML element's attributes causes **InvalidCharacterError** exception in Microsoft Edge, starting from the version 41.16299.15.0 (Microsoft EdgeHTML 16.16299). The issue is not reproducible in older versions and in other browsers.

The root cause of the issue is enforced validation in EdgeHTML for attribute names. If provided value is not correct, **InvalidCharacterError** is thrown. The sample below fails to get an enumerator for [NamedNodeMap](https://dom.spec.whatwg.org/#namednodemap) (see [bridge.js](https://github.com/bridgedotnet/Bridge/blob/9cffa0be5546053ea11f13001f304825bdd1734b/Bridge/Resources/Core.js#L1041)).

### Steps To Reproduce

https://deck.net/9792d8735b8bbd70e032022410de0603

```csharp
public class Program
{
    public static void Main()
    {
        var el = Document.CreateElement("input");
        el.SetAttribute("name", "test name");
        el.SetAttribute("value", "test val");
        
        foreach (var attr in el.Attributes)
        {
            Console.WriteLine(attr.NodeName);
        }
    }
}
```

### Expected Result

Console output:
```
name
value
```

### Actual Result

Console output:
```
System.Exception: InvalidCharacterError
```

### See Also
- [[Forums]: InvalidCharacterError in Edge](https://forums.bridge.net/forum/premium/premium-help/5061-invalidcharactererror-in-edge)

**Comment by fabriciomurta** [comment]
Merged! The fix will make it to next Bridge version indicated by the milestone attached to this issue (currently 16.6.1).
