### ISSUE TITLE
Contribution Guidelines: Code Style and Architectural Cleanup

### ISSUE THREAD

**Issue by Danielku15** [bridgedotnet/Bridge#3333]
I would like to know if there are some sort of official (basic) coding guidelines for code contribution to Bride.net. My Visual Studio (and Resharper) are crying about many code style things which I'd like to get clean. They mainly complain about: 
- The usage of unneeeded `this.` qualifiers which seems to be common. 
- Potential usage of new C#7 features. 

Also I'd like to know if it is safe to cleanup the Bridge codebase. e.g. 
- Remove I detect dead code (even if it is part of the contracts IEmitter, IValidator etc.) 
- Move code to more common places (e.g. use extension methods instead of having them part of the contracts). 

A little bit background to my question: 

I am currenly working on some bigger rework of the Bridge.net compiler. The rework is mainly driven by the issues #394 and #2002. I started implementing the fluent API configuration and as part of this I needed to get rid of Mono.Cecil as part of the compilation process. I am making very good progress but fear a bit that my changes are too big to be accepted as such.

**Comment by geoffreymcgill** [comment]
Hi. I added our [C# Coding Style Guide](https://github.com/bridgedotnet/Bridge/wiki/C%23-Coding-Style-Guide) to the wiki.

The use of `this.` is not required from the compiler perspective, but preferred as it provides an obvious declaration on whether a member is `instance` or `static`.

Thanks for the contribution. We're excited to see your modifications.
