### ISSUE TITLE
Invalid module handling if module is defined in bridge.json

### ISSUE THREAD

**Issue by Danielku15** [bridgedotnet/Bridge#3335]
It appears that in case you define your module in the bridge.json the output is different than if you define the module via ModuleAttribute. The types within the assembly are then not implicitely in the module and therefore lack of the required $scope. 

I detected this bug during one of my current Bridge.net code cleanups. I "broke" the existing IntegrationTest 7 by "correctly" handling the module definitions. This integration test defines a module in the bridge.json but the types are not included in the module causing a different output. 

### Steps To Reproduce

Deck: Not possible because assembly level attributes and bridge.json cannot be specified on deck. 

#### Module in Assembly

```csharp
[assembly:Bridge.Module("MyModule")]
namespace TestProject
{
    public class N3334
    {
    }
}
```
#### Module in Json

```json
{
  "output": "Bridge\\output",
  "cleanOutputFolderBeforeBuildPattern": "*.*",
  "outputBy": "namespace",
  "module": {
    "name": "MyModule"
  },
  "outputFormatting": "Formatted",
  "generateDocumentation": "Full"
}
```

```csharp
namespace TestProject.Issues 
{
    public class N3334
    {
    }
}
```

### Expected Result

```js
/**
 * @compiler Bridge.NET 16.6.1
 */
Bridge.assembly("TestProject", function ($asm, globals) {
    "use strict";

    define("MyModule", function () {
        var MyModule = { };
        /** @namespace TestProject */

        /**
         * @public
         * @class MyModule.TestProject.N3334
         */
        Bridge.define("TestProject.N3334", {
            $scope: MyModule,
            statics: {
                methods: {
                    $metadata : function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"}]}; }
                }
            }
        });
        return MyModule;
    });

});

```
#### Module in Assembly

```js
/**
 * @compiler Bridge.NET 16.6.1
 */
Bridge.assembly("TestProject", function ($asm, globals) {
    "use strict";

    define("MyModule", function () {
        var MyModule = { };
        /** @namespace TestProject */

        /**
         * @public
         * @class MyModule.TestProject.N3334
         */
        Bridge.define("TestProject.N3334", {
            $scope: MyModule,
            statics: {
                methods: {
                    $metadata : function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"}]}; }
                }
            }
        });
        return MyModule;
    });

});
```

#### Module in JSON

```js
/**
 * @compiler Bridge.NET 16.6.1
 */
Bridge.assembly("TestProject", function ($asm, globals) {
    "use strict";

    define("MyModule", function () {
        var MyModule = { };
    /** @namespace TestProject */

    /**
     * @public
     * @class TestProject.N3334
     */
    Bridge.define("TestProject.N3334");
        return MyModule;
    });

});
```

### Hints for fix

The `Validator.CheckModule` does not consider the `AssemblyInfo.Module`. https://github.com/bridgedotnet/Bridge/blob/9cffa0be5546053ea11f13001f304825bdd1734b/Compiler/Translator/Inspector/Validator.cs#L727

This in a result causes the module to be missing in the `EmitBlock.DoEmit`:

https://github.com/bridgedotnet/Bridge/blob/9cffa0be5546053ea11f13001f304825bdd1734b/Compiler/Translator/Emitter/Blocks/EmitBlock.cs#L289

I fear this bug also has an impact on the other `ITypeInfo` properties like `FileName` and `Dependencies`.

**Comment by fabriciomurta** [comment]
Thanks for providing the pull request. I just added another integration test to check whether two equal projects make the same output if their difference is just the setting via the assembly attribute or bridge.json setting. Should work better than the other integration tests as it does not rely in "reference" files.

Anyway, you change has been merged. It will be available next Bridge release, indicated by the milestone attached to this issue (currently, 16.6.1).
