### ISSUE TITLE
Int32.ToString("##") doesn't work

### ISSUE THREAD

**Issue by SoptikHa2** [bridgedotnet/Bridge#3338]
Int32.ToString("##") normally does this:

```csharp
0.ToString("##"); // "00"
1.ToString("##"); // "01"
102.ToString("##"); // "102"
// ...
```

When I do it in Bridge.NET, it's like I've done nothing:

```csharp
0.ToString("##"); // "0"
1.ToString("##"); // "1"
102.ToString("##"); // "102"
```
[Proof](https://deck.net/35e763963936e89c2bbd0b89d55e84ce)

Do you plan adding this into Bridge? 

Thanks, Peter

**Comment by fabriciomurta** [comment]
Have you tested your code in native .NET?.. According to this dotnet fiddle, Bridge is doing right: https://dotnetfiddle.net/aBPsEj

**Comment by SoptikHa2** [comment]
Whoops, I messed up the code, it should be `.ToString("00");` and it works in bridge correctly. Sorry for stealing your time, I though, it was # instead of 0.

You can close this. And btw, thanks for Bridge, it's great project :)

**Comment by fabriciomurta** [comment]
Great! Thank you for your interest in Bridge as much as taking your time to report an issue you found. Next time, remember [dotnet fiddle](https//dotnetfiddle.net/) is (also) your friend while validating Bridge output. A great tool to quickly support a functionality that should be mirrored in Bridge.
