### ISSUE TITLE
Enum.TryParse nulls the out parameter if unable to parse

### ISSUE THREAD

**Issue by Porl91** [bridgedotnet/Bridge#3346]
In C# when calling `Enum.TryParse` on a `string`, the out parameter is set to default(TEnum) if it's unable to parse the `string` out into a `TEnum`. In Bridge this parameter appears to be nulled if it fails to parse correctly, even thought it's a value type, meaning we have to perform a null check, which creates a compiler warning.

### Steps To Reproduce

Bridge: https://deck.net/5e92dbcd35cb6a440f7502b51af78e52
C#: https://dotnetfiddle.net/3TtYBB

Notice that in the C# example that `i` returns the default value **One**.

### Expected Result
One

### Actual Result
null

**Comment by geoffreymcgill** [comment]
@Porl91 – Thanks for the report. We are reviewing.

**Comment by fabriciomurta** [comment]
Fixed! This is going to make it to the next bridge release according to the attached milestone (currently, 16.7.0).
