### ISSUE TITLE
Metadata initialization problem

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#3348]
Creating a separate issue for that. However, it's quite related to #3347.

### Problem

When a program uses modules, all entities will be wrapped with `require(["Module"], function(m) { .... } );` to resolve all dependencies first. The problem is that metadata must be initialized _after_ entities are created. The `require` function changes normal flow of initialization and leads to errors.

As it's shown in #3347 - inline metadata initialization problem can be solved by writing it in the correct location. But the problem still exists for metadata written to separate files. There is no way to specify when the metadata initialization from a file should be executed.

### Solution

A possible solution is making metadata initialization lazy, i.e. executed by a request. Initialization could be requested by **Bridge.init()** or another function placed right after entity definitions inside `require` function callback.

### See Also
- [#3347] - Inline metadata location and Modules
- [Retyped/Retyped#39] usage of Retyped.React breaks bridge reflection

**Comment by fabriciomurta** [comment]
Fix just merged upstream! Will be available to next Bridge release (currently: 16.7.0).
