### ISSUE TITLE
Wrong DateTime kind for DateTime.Date value

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#3349]
A description of the issue.

### Steps To Reproduce

https://dev.deck.net/a151f2f3e3e7bb9cf47fbcd03f952221

dotnetfiddle is down.. so console application output (.Net 4.7):
```
01/01/2018 00:00:00
Utc

01/01/2018 00:00:00
Utc
Press any key to continue . . .
```

```csharp
public class Program
{
    public static void Main()
    {
        DateTime time = new DateTime(2018, 1, 1, 0, 0, 0, DateTimeKind.Utc);
            
        Console.WriteLine(time.ToString());
        Console.WriteLine(time.Kind.ToString());
        
        Console.WriteLine();
        
        Console.WriteLine(time.Date.ToString());
        Console.WriteLine(time.Date.Kind.ToString());
    }
}
```

### Expected Result

```
01/01/2018 00:00:00
Utc

01/01/2018 00:00:00
Utc
```

### Actual Result

```
01/01/2018 00:00:00
Utc

12/31/2017 21:00:00
Utc
```

**Comment by geoffreymcgill** [comment]
This might be fixed in PR #3325.

**Comment by fabriciomurta** [comment]
It is very likely yes. I've just tested with to-be-released Bridge 16.6.1 and the result is:

```
01/01/2018 00:00:00
Utc
01/01/2018 00:00:00
Utc
```

We'll soon publish the updated deck and you'll be able to check it out. Thanks for the report!

**Comment by fabriciomurta** [comment]
Just pushed 16.6.1 to dev deck net. Check out the result: https://dev.deck.net/6ff6b5638951e07ec5232884f8d3fb81

Anyway, soon the original deck will have the fix.

**Comment by hardhub** [comment]
Just updated to 16.6.1 removed all workarounds and all tests are passed.
It looks fixed... Thanks!

**Comment by fabriciomurta** [comment]
Cool! Thanks for your feedback!
