### ISSUE TITLE
Typescript Definitions Broken - Missing definitions for primitive.net types

### ISSUE THREAD

**Issue by rufio620** [bridgedotnet/Bridge#3351]
.NET primitives types such as long used to be generated as number instead they use the System.Int64. The bridge.d.ts file contains no definitions for these system types which results in the typescript compiler flagging them as errors. This makes any typescript generation completely unusable. I am I missing a file that contains these definitions?

See attached repro.
[BridgeTypescriptTest.zip](https://github.com/bridgedotnet/Bridge/files/1609528/BridgeTypescriptTest.zip)

### Expected Result

Definitions for .NET primitive types should be included in bridge.d.ts 

### Actual Result

Typescript files are generated but are missing definitions for .NET mscorelib primitives.

**Comment by fabriciomurta** [comment]
We've just merged the fix to our integration branch! This will make it to next release of Bridge (refer to milestone, currently 16.7.0).

**Comment by rufio620** [comment]
I just attempted to integrate this into my existing code base. All the primitives are there but it appears like there is still a missing definition for System.IO.Stream.
