### ISSUE TITLE
TimeSpan? is compared wrong with null

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#3352]
System.TimeSpan.eq(result, null) does not work as expected.

### Steps To Reproduce

https://dev.deck.net/063fee510810ce042b99b4931293cf53
https://dotnetfiddle.net/Widget/a3UQ2N

It is interesting but opposite comparison works fine:
https://dev.deck.net/1b40bb4caa9e00f2058c89615bf1888e

```csharp
public class Program
{
    public static void Main()
    {
        TimeSpan? result = null;
        
        if (result == null)
           Console.WriteLine("null!");
        else
           Console.WriteLine(result.Value);
    }
}
```

### Expected Result

```
result == null should be true
```

### Actual Result

```
null (not boolean), so finally it will raise exception on result.Value
```

**Comment by fabriciomurta** [comment]
Fixed! This will make it to the next Bridge release (see milestone -- currently 16.7.0). Thanks for the report!
