### ISSUE TITLE
Bridge considers two equiv Uris different (but .NET considers them the same)

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#3357]
```csharp
Console.WriteLine(new Uri("https://deck.net") == new Uri("https://deck.net"));
```

Outputs True in .NET, but False in Bridge.

**Comment by geoffreymcgill** [comment]
Issue has been fixed and we're in the process of final review and testing.

**Comment by DanTup** [comment]
@geoffreymcgill @vladsch Worth nothing that `.absoluteUri` in Bridge doesn't currently normalise casing of the host like .NET does, so I think the PR doesn't handle this:

```cs
Console.WriteLine(new Uri("https://GOOGLE.com/test").AbsoluteUri == new Uri("https://google.com/test").AbsoluteUri);
```

In .NET, this is true. In Bridge, currently it's false (and I don't think the PR fixes that). I had a quick look at the [Uri code](https://referencesource.microsoft.com/#System/net/System/URI.cs,991565dd25f47c90) and it looks somewhat complicated :-(

**Comment by fabriciomurta** [comment]
Nice point, @DanTup!

By the way, any reason you're using `.AbsoluteUri`? I don't seem to see any change in results with or without it.
https://dotnetfiddle.net/USgxce

**Comment by fabriciomurta** [comment]
Actually... Current System.Uri is but a simplified stub and should be actually developed. In fact, issue #2185 is tracking its development.

So probably this casing (and a lot other stuff) should go to that issue.

**Comment by DanTup** [comment]
> By the way, any reason you're using `.AbsoluteUri`?

I'm not, I just looked at the PR to fix this and saw the fix was to use AbsoluteUri for equality check and the idea of case sensitivity popped into my head so I thought I'd test it.

Though until this is released, we'd actually have to use AbsoluteUri as the equality on Uri isn't there yet?

**Comment by fabriciomurta** [comment]
Hello again, @DanTup!

We're going to merge in the fix applied which gives a bare minimum functionality to comparisons using System.Uri. But as far as the full functionality as well as more partial functionality related to the class, it will all be concentrated within the #2185 issue. So we will be closing this one to keep all in a same place.

Don't worry about the missing tests, we added comments to the main issue with a set of tests that ensures those checks will not go unnoticed when it is implemented.

**Comment by DanTup** [comment]
Sounds reasonable to me; the original PR still fixes the original issue we had (we're not likely to end up with different cases and then expect equality, since the source of any uris we expect to be equal will be the same) 👍
