### ISSUE TITLE
double.TryParse different behaviour from .Net

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#3360]
JS is greedy to parse wrong double values.

### Steps To Reproduce

https://dev.deck.net/8a3f5e3449c4d6f675f830cb54031517
https://dotnetfiddle.net/Widget/97XAWE

```csharp
public class Program
{
    public static void Main()
    {
	double test;
        var result = double.TryParse("2/1", out test);
	
	Console.WriteLine(result);
    }
}
```

### Expected Result

```
False
```

### Actual Result

```
True
```

**Comment by fabriciomurta** [comment]
Fixed upstream! The fix is going to make it to the next Bridge release (see attached milestone).
