### ISSUE TITLE
Int64/UInt64 values should be serialized as string if the value > Number.MAX_SAFE_VALUE

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#3361]
If 64bit value is outside javascript safe number range (-(2^53 - 1)..(2^53 - 1)) then need to serialize it as string instead of number otherwise value during deserialization in javascript will be different

**Comment by vladsch** [comment]
Required for https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/issues/82

**Comment by fabriciomurta** [comment]
Implemented successfully! Will make it to next Bridge release!
