### ISSUE TITLE
Bridge Name attribute overwrites generic parameter in Typescript definition

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#3365]
A description of the issue.

### Steps To Reproduce

```csharp
using Bridge;

namespace TestBridge
{
    public class App
    {
        public static void Main()
        {
            var named = new GenericNamed<int>();
            var unnamed = new Generic<int>();
        }
    }

    [Name("GenericNamed")]
    public class GenericNamed<T>
    {
        public T Item;
    }
    public class Generic<T>
    {
        public T Item;
    }
}
```

Incorrect typescript definition is generated

### See Also
https://forums.bridge.net/forum/community/help/5103-bridge-name-attribute-overwrites-generic-parameter-in-typescript-definition-bug

**Comment by fabriciomurta** [comment]
Done! This will be part of next Bridge release (see milestone, currently 16.7.0).
