### ISSUE TITLE
Review typescript definitions in bridge.d.ts

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#3367]
Definitions in bridge.d.ts (like System.String) have no prototype property which makes it impossible to use such types as generic type arguments.

### See Also
https://forums.bridge.net/forum/community/help/5097-generic-type-usage-using-bridge-net-output-from-typescript

**Comment by fabriciomurta** [comment]
We've just merged the fix to our integration branch! This will make it to next release of Bridge (refer to milestone, currently 16.7.0).
