### ISSUE TITLE
Why does default bridge.json override "anonymousType" and "lambda" rules from default of "Managed" to "Plain"?

### ISSUE THREAD

**Issue by ProductiveRage** [bridgedotnet/Bridge#3374]
I was trying to show an example of "[lifted functions](https://forums.bridge.net/forum/general/feature-requests/1515-closed-921-lift-simple-anonymous-functions-into-named-functions-for-performance-wins)" on Deck.NET and it wasn't working (see https://deck.net/6797e1b898ee21cf92e9efd1fcee39e6) and so I tried reproducing in VS with a fresh solution and it wasn't working there either.

It's because the bridge.json file that is added with the Bridge NuGet package sets "rules" / "lambda" to "Plain", overriding the default value of "Managed" (a comment in bridge.json says that "Managed" is the default for all of these). It does the same with "anonymousType" as well.

If wondered why they were being set to "Plain" in the bridge.json that I imagine most people will get if the default is "Managed". If you think that it's better for the default to be "Plain" then maybe the default _should_ be "Plain" instead of "Managed"?

I was looking into this specifically while reading this SO answer about using JSX and how there is a cost to anonymous functions 

https://stackoverflow.com/a/36677798/3813189

.. and I thought "ah, but Bridge avoids that with lifted functions" but that behaviour seems to be disabled for most people (people who install the Bridge NuGet package and then never find reason to change the "rules" / "lambda" value in it).

I presume that Deck.NET uses the same bridge.json configuration, which is why the lifting of functions is disabled there too?

**Comment by vladsch** [comment]
It was made for simple clean syntax only. We thought that lambda lifting optimization can confuse anyone who just investigates Bridge generated code.

If you need Managed mode for lambda then just use Rules attribute
https://deck.net/34ce975ec63e5b16c0d3083cb4cdad93

**Comment by ProductiveRage** [comment]
Ok. It's useful to know about that attribute, for demonstration purposes. Thanks.
