### ISSUE TITLE
Embedded resources do not work outside of main function.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#3378]
```csharp
static class Program
{
    static int Resources => Assembly.GetExecutingAssembly().GetManifestResourceNames().Length;
    static void Main ()
    {
        Console.WriteLine((Assembly.GetExecutingAssembly().GetManifestResourceNames().Length == Resources) ? "Passed" : "Failed");
    }
}
```

* Only passes with an embedded resource.

**Comment by fabriciomurta** [comment]
Hello @michaelcheers!

Am I supposed to be able to reproduce this [in a Deck](https://deck.net/b1e56bf4d9202a4eb517ce29ddef597c)? Currently getting "Passed".

As this is pretty old an issue, I'll mark it as invalid and close it, believing it is fixed now by some other fix in the path from January to now.

Let us know if this still bugs for you and provide a little more information that we may have missed while trying to reproduce it.

Thanks for taking your time to report it, and sorry for the long long delay in posting a feedback!
