### ISSUE TITLE
Double.NaN is not a compile-time constant

### ISSUE THREAD

**Issue by pnjeffries** [bridgedotnet/Bridge#3386]
The double.NaN in Bridge.Net is not a compile-time constant and thus cannot be used in cases that require such (for example, optional property default values).  This appears to be because in Bridge.Net it is implemented as a static readonly field, while in .NET it is const.

### Steps To Reproduce

https://deck.net/31bda8154321b27bab6c15b886c9096c

**Comment by geoffreymcgill** [comment]
Thanks for pointing out this defect. This will be an easy fix. We will correct and make sure it gets into the next release.

**Comment by fabriciomurta** [comment]
Fixed! Going to make it to next bridge release (see milestone, 16.7.1 at the time of this message).
