### ISSUE TITLE
Two excplicit implementations of generic interface are indistinguishable 

### ISSUE THREAD

**Issue by nix21** [bridgedotnet/Bridge#3388]
Hi,
when I have a generic interface and ....  Who cares about text description when an example is much better way of description:

### Steps To Reproduce

https://deck.net/dcfbd181768de167d401304dc80c670c

this C# code
```
void IFace<T>.Method() => Console.WriteLine("single");
void IFace<List<T>>.Method() => Console.WriteLine("list");
```
produces this JS code
```
Demo$Program$IFace$1$Method: function () {
    System.Console.WriteLine("single");
},
Demo$Program$IFace$1$Method: function () {
    System.Console.WriteLine("list");
}
```
Both methods have the same name. Calling the first and then the second method produces incorrect output.
```
((IFace<int>)c).Method();
((IFace<List<int>>)c).Method();
```

### Expected Result

single
list

### Actual Result

list
list

**Comment by geoffreymcgill** [comment]
Hi @nix21, 

Thanks for pointing out this issue. We will investigate and try to fix right away.

**Comment by fabriciomurta** [comment]
The pull request with fixes resolving this issue has just been merged upstream! The fix will be available next Bridge version (see attached milestone).
