### ISSUE TITLE
Ternary operator with assignment on the same line as the declaration doesn't work

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#3390]
https://deck.net/050e112eb605a610b7abfe75841978ad

Apparently that's actually valid C# code:
http://rextester.com/MMWV49398

Don't make this task Premium.

**Comment by geoffreymcgill** [comment]
@TriEdgeAI – Thanks for the report. Interesting scenario.

**Comment by vladsch** [comment]
Duplication
https://github.com/bridgedotnet/Bridge/issues/2872

**Comment by fabriciomurta** [comment]
Running like a charm now! Fixed with the issue this duplicates and will make it to the next Bridge release! (see attached version milestone).
