### ISSUE TITLE
Using Equals() on the same boxed enum returns false

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#3391]
## Actual
https://deck.net/bf075d4e798bc3fbbd313bde5a0ecae7

## Expected
http://rextester.com/HIV90065

**Comment by fabriciomurta** [comment]
Done! This has been fixed upstream and will make it to next Bridge version (currently 16.7.1, see milestone).

**Comment by fabriciomurta** [comment]
Test case looks alright now: https://dev.deck.net/bf075d4e798bc3fbbd313bde5a0ecae7
