### ISSUE TITLE
Extension method for decimal with additional string parameter produces invalid code.

### ISSUE THREAD

**Issue by nix21** [bridgedotnet/Bridge#3404]
When I define an extension method for decimal with additional string parameter, Bridge.NET compiler tries to create a decimal object out of string.

### Steps To Reproduce

https://deck.net/2815a2eef9f46c143d23bc1305fb029d

```csharp
decimal a = 0;
a.M("text");
```
```csharp
public static class Ex
{
    public static void M(this decimal a, string b) { }
}
```

### Expected Result

```js
var a = System.Decimal(0);
Demo.Ex.M(a, "text");
```

### Actual Result

```js
var a = System.Decimal(0);
Demo.Ex.M(a, System.Decimal("text"));
```
This code leads to System.FormatException: Invalid format.

**Comment by fabriciomurta** [comment]
The pull request with fixes resolving this issue has just been merged upstream! The fix will be available next Bridge version (see attached milestone).
