### ISSUE TITLE
Dictionary<T, _>.Values.CopyTo NotImplemented

### ISSUE THREAD

**Issue by nix21** [bridgedotnet/Bridge#3408]
Hi,
when I create a System.Collections.Dictionary<TKey, TValue> with TKey other than string or primitive type (I.E. any custom struct, nullable, DateTime or any custom class), you cannot use Values.CopyTo - it is not implemented inside System.Array.copyTo JS method. As a consequence is you cannot pass dictionary values into a List<T> collection in its constructor (pretty common use case). Dictionary with primitive keys works fine.

### Steps To Reproduce

https://deck.net/72b08c9e860dd1710473527bdce646f3

```csharp
public static void Main()
{
    var dic = new Dictionary<C, int>() ;
    dic.Add(new C(), 0);
    dic.Values.CopyTo(new int[1], 0);
    new List<int>(dic.Values);
}
class C { }
```

### Expected Result

Elements are copied without error.

### Actual Result

System.Exception: Uncaught System.NotImplementedException: copyTo

**Comment by fabriciomurta** [comment]
Fixed! This will make it to the next Bridge version (see attached milestone).
