### ISSUE TITLE
Convert.ToString returning type when ToString method is available

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#3415]
Convert.ToString currently returns an object's type rather than calling its ToString method.

A similar issue logged under #2887 has just been fixed by pull request #3414, but the behavior reported here is still not addressed.
### Steps To Reproduce

https://deck.net/f1e618d16a662f5d7679b68facd6667c

With test case (thrid assertion) for issue #2887 below:
https://deck.net/a4ca8bde2174382a4c7ec9cfdde6acd3
https://dotnetfiddle.net/IDwe5k

### Expected Result

```
Success: t.ToString() is t.Value.
Success: Convert.ToString(t) is t.Value.
Success: Convert.ToString() returns 'System.Object'.
```

### Actual Result

```
Success: t.ToString() is t.Value.
Failure: Convert.ToString(t) is t.Value.
Success: Convert.ToString() returns 'System.Object'.
```

### See also
- Bridge.NET forum thread: [Convert.ToString returning type when ToString method is available](https://forums.bridge.net/forum/bridge-net-pro/bugs/5191)

**Comment by DierkDroth** [comment]
@fabriciomurta thanks for taking care.

**Comment by fabriciomurta** [comment]
Fixed! The fix will make it to the next Bridge version (see attached milestone).

**Comment by DierkDroth** [comment]
@fabriciomurta thanks. Appreciated
