### ISSUE TITLE
Cannot cast Task<int> from Task to Task<int>

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#3420]
Cannot cast `Task<int>` from `Task` to `Task<int>`.

### Steps To Reproduce

https://deck.net/f83adba7c5b9d58ff67c9ba73a520ad4
https://dotnetfiddle.net/NCkhfV

```csharp
public class Program
{
    public static async void Main()
    {
        Task t = Task.FromResult(3);
        Task<int> t2 = (Task<int>)t;
        Console.WriteLine(await t2);
    }
}
```

Should show 3 on deck like dot net fiddle.

**Comment by fabriciomurta** [comment]
I hit a boulder while coming up with a solution to this issue, so @vladsch will handle it. :)

**Comment by fabriciomurta** [comment]
Fixed! Next Bridge release will include this correction in the code.
