### ISSUE TITLE
Retyped library missing from Index.html

### ISSUE THREAD

**Issue by rafael-aero** [bridgedotnet/Bridge#3425]
JS libraries from Retyped are not included in the final index.html file - I have to manually reference them from i.e. a CDN - but this is overwritten when the index.html file is regenerated.

From [here](https://github.com/Retyped/Retyped/issues/30), it seems like it's a known issue - I just want to confirm that's the case, or am I missing something?

**Comment by geoffreymcgill** [comment]
Currently, the .js files are not embedded in the Retyped assemblies. They have to be included in your index.html manually. 

We do plan to add this functionality to Retyped and are tracking the feature with Issue https://github.com/Retyped/Retyped/issues/50.

You can disable the auto-generation of the **index.html** file by using the `html` config of **bridge.json**, see

https://github.com/bridgedotnet/Bridge/wiki/global-configuration#html

I'm going to close this issue in the Bridge repo as we'll track the feature request in the Retyped [repo](https://github.com/Retyped/Retyped/).

Hope this helps.
