### ISSUE TITLE
override method not work correctly

### ISSUE THREAD

**Issue by chenxustu1** [bridgedotnet/Bridge#3440]
override method not work correctly

### Steps To Reproduce

https://deck.net/69335d245c525361a707f982e64f49ff

```csharp
public class Program
{
    public static void Main()
    {
        System.IO.TextWriter Writer = new System.IO.StringWriter();
        Writer.ToString();
        
 	System.IO.StringWriter Writer1 = new System.IO.StringWriter();
        Writer1.ToString();
    }
}
```

### Expected Result

```js
Bridge.assembly("Demo", function ($asm, globals) {
    "use strict";

    Bridge.define("Demo.Program", {
        main: function Main () {
            var Writer = new System.IO.StringWriter.ctor();
            Writer.ToString();

            var Writer1 = new System.IO.StringWriter.ctor();
            Writer1.ToString();
        }
    });
});
```

### Actual Result

```js
Bridge.assembly("Demo", function ($asm, globals) {
    "use strict";

    Bridge.define("Demo.Program", {
        main: function Main () {
            var Writer = new System.IO.StringWriter.ctor();
            Bridge.toString(Writer);

            var Writer1 = new System.IO.StringWriter.ctor();
            Writer1.ToString();
        }
    });
});
```

**Comment by fabriciomurta** [comment]
Hello, although that's an issue, I don't think the output will be the way you expect it to. But the issue can be fixed elsewhere.

Here's a deck expanding on the issue and exploring the code that fails in the scenario described: https://deck.net/9b93217df2478dca0c60856724ecc137

**Comment by fabriciomurta** [comment]
In fact, without any fix, any scenario that would break in v16 is already working in Bridge v17, so changes already made in Bridge 17 address this issue.

Deck with issues passing (at the time of the writing): https://dev.deck.net/9b93217df2478dca0c60856724ecc137

If you find any test case of this issue that still breaks in Bridge v17 (currently available in deck via dev.deck.net), please let us know!
