### ISSUE TITLE
Numeric types get promoted to Int64

### ISSUE THREAD

**Issue by exelix11** [bridgedotnet/Bridge#3459]
Sometimes numeric types are promoted to Int64, this slows down the code if calculations are needed.
In a loop with various modulus and integer divisions I noticed a major slowdown in MS Edge, and a noticeable one in Firefox and Chrome on my machine.

### Steps To Reproduce

https://deck.net/c926eeb957cb9e5ca2e2f8186846f4d2

```csharp
public class Program
{
    public static void Main()
    {
        Int32 x = 50;
	UInt32 y = 100;
	if (x > y) {...}
                
        UInt32 a = 100;
        if (x / a > y) {...}
    }
}
```

### Expected Result

```js
            var x = 50;
            var y = 100;
            if (x > y) {...}

            var a = 100;
            if (Bridge.Int.div(x, a) > y ) {...}
```

### Actual Result

```js
            var x = 50;
            var y = 100;
            if (System.Int64(x).gt(System.Int64(y))) {...}

            var a = 100;
            if (System.Int64(x).div(System.Int64(a)).gt(System.Int64(y))) {...}

```

**Comment by vladsch** [comment]
It is expected result. In .Net, you will get 64 bit numeric value if divide signed and unsigned 32 bit values.

**Comment by exelix11** [comment]
Does this apply to the comparison as well ?
I expected this to be handled by the browser when integer is set to plain.

**Comment by vladsch** [comment]
Yes, it is applied to comparison also. According C# specification, left and right expressions should be converted to most common type before comparison.

**Comment by exelix11** [comment]
Ok thanks, sorry for bothering you.
