### ISSUE TITLE
DateTime.UtcNow returning wrong time

### ISSUE THREAD

**Issue by yctri** [bridgedotnet/Bridge#3478]
I think the deck below (showing that DateTime.UtcNow displays the wrong time) may be a symptom of another problem under the hood. 

Given a previously-saved UTC time without timezone information, I believe we can usually reconstruct its .NET representation using:

```csharp
    // set DateTimeKind to be UTC.
    DateTime myUTCTime = DateTime.SpecifyKind(myTimeWithoutTimeZoneInfo, DateTimeKind.Utc);
```

The above used to work fine until updating to 16.8.2. Now, comparisons between myUTCTime and DateTime.UTCNow are returning a timezone offset. I noticed the issue below when attempting to reproduce this problem in Deck.

### Steps To Reproduce

https://deck.net/9a65e5cb6b9b80fe4f69d1bf9b3c69dd

```csharp
public class Program
{
    public static void Main()
    {
        Console.WriteLine("UTC time: " + DateTime.UtcNow);
        Console.WriteLine("Local time: " + DateTime.Now);
        Console.WriteLine("Local - UTC: " + (DateTime.Now - DateTime.UtcNow));
    }
}
```

### Expected Result

```js
UTC time: 03/21/2018 09:23:14
Local time: 03/20/2018 14:23:14
Local - UTC: -07:00:00
```

### Actual Result

```js
UTC time: 03/21/2018 04:23:14
Local time: 03/20/2018 14:23:14
Local - UTC: -07:00:00
```

**Comment by geoffreymcgill** [comment]
Hi @yctri – Thanks for the report. We are investigating. 

We're looking into the Deck Share feature too. Looks like GitHub changed something with their Gist API that is now causing a failure in Deck.

**Comment by geoffreymcgill** [comment]
@yctri – This issue has been fixed and pull-request has been submitted. Once testing and final review are complete, the pr will be merged into `v17` and will be included in the Bridge 17.0 release.

The problem was related to the timezoneoffset being added twice to the DateTime object.

If this is a supercritical defect for you, we might be able to make 16.8.3 release, or at least merge this pr into the `dev` branch (currently 16.8.3) which would allow you to build local packages.

Deck share links are still failing because GitHub changed something in their API, but appears to be undocumented. We have submitted a technical support ticket with GitHub.

**Comment by fabriciomurta** [comment]
This expected result does not make sense to me:
```
UTC time: 03/21/2018 09:23:14
Local time: 03/20/2018 14:23:14
Local - UTC: -07:00:00
```

Wouldn't that be, rather,
```
UTC time: 03/20/2018 21:23:14
Local time: 03/20/2018 14:23:14
Local - UTC: -07:00:00
```
?

**Comment by geoffreymcgill** [comment]
@yctri – shouldn't your UTC offset be `+05:00:00` given those UTC vs Local times?

**Comment by yctri** [comment]
@geoffreymcgill @fabriciomurta Yes, sorry the expected UTC time should have read 21:23:14 (forgot to convert to 24h clock).

What's the ETA on 17.0?

**Comment by geoffreymcgill** [comment]
Deck sharing is working again.

Once we know a release date, the due date on the [17.0](https://github.com/bridgedotnet/Bridge/milestone/38) milestone will be set. We're working hard on 17.0, and hope to have a `-beta` available within 2 weeks.

**Comment by fabriciomurta** [comment]
The pull request was merged upstream! The fix will be available on Bridge v17!

**Comment by geoffreymcgill** [comment]
The dev.deck instance has been updated and your original sample should now be working correctly. 

https://dev.deck.net/9a65e5cb6b9b80fe4f69d1bf9b3c69dd

Hope this helps.

**Comment by yctri** [comment]
Awesome, thanks.
