### ISSUE TITLE
Virtual properties in external classes

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#3485]
When an external class' property is referenced from a derived class, we won't get a proper value if the property has `virtual` modifier. The reason is that `Bridge.ensureBaseProperty` function looks for the property descriptor in internal dictionaries and doesn't find it, because obviously external entities do not use Bridge initialization and do not fill those internal dictionaries.

If the issue can't be fixed, I'd suggest throwing a compilation error for virtual properties declared in external types.

### Steps To Reproduce

https://deck.net/62de561505191a56ee83f1dea4369324

```csharp
public class Program
{
    [Init(InitPosition.Top)]
    public static void Init()
    {
        /*@
var A = (function () {
    function A() {
        this.V1 = "value1";
        this.V2 = "value2";
    }
    return A;
}());
        */
    }
    
    public static void Main()
    {
        var v1 = new B().GetV1();
        var v2 = new B().GetV2();
        
        Console.WriteLine("V1: " + v1);
        Console.WriteLine("V2: " + v2);
    }
}

[External]
[Namespace(false)]
public class A
{
    public string V1 { get; }
    public virtual string V2 { get; }
}

public class B : A
{
    public string GetV1() => base.V1;
    public string GetV2() => base.V2;
}
```

### Expected Result

Console output 
```js
V1: value1
V2: value2
```

### Actual Result

Console output 
```js
V1: value1
V2: 
```

**Comment by vladsch** [comment]
We cannot throw an exception because external class can be defined via Bridge.define in JavaScript, like many external classes in Bridge assembly.

**Comment by AndreyChechel** [comment]
@vladsch, do you think it's feasible to get value directly from an object, if the property was not found by `Bridge.ensureBaseProperty`?

**Comment by vladsch** [comment]
Yes, May be. I will review different scenarios.

**Comment by fabriciomurta** [comment]
This has just been merged upstream! Now available in `dev` branch.
