### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'amDesignator' of undefined" when using ru-RU culture

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#349]
When trying to use the Russian culture (I read in another case it was available), I get this error:

```
DateTime date;
var culture = new CultureInfo("ru-RU");
Global.Alert(DateTime.TryParse("22/22/2222", culture, out date).ToString());
```

> Uncaught TypeError: Cannot read property 'amDesignator' of undefined

**Comment by LeonidVeriga** [comment]
@DanTup  We decided not to include cultures into `bridge.js` file to keep its size smaller. Can you please try to include the locale into your page manually - https://github.com/bridgedotnet/Bridge/blob/master/Bridge/Resources/Locales/ru-RU.js

**Comment by DanTup** [comment]
Understood. It might be good to have an option to include them (or always include them?) on live.bridge.net to aid troubleshooting (eg. we've seen differences between browsers, so being able to link to repros there would be handy).

**Comment by LeonidVeriga** [comment]
@Mimisss Can you please add references to the locales into Live App.

**Comment by Mimisss** [comment]
@LeonidVeriga  @DanTup 

Live updated. Make sure you clean the cache of your browser before testing. Issue closed by https://github.com/bridgedotnet/Live/commit/3a2df6598b8c6eab1ebf5327dcf5e1c2f6d8967b

**Comment by DanTup** [comment]
Looks good to me (as does fix for #350). Thanks!

**Comment by LeonidVeriga** [comment]
We now support all .Net cultures #399

**Comment by DanTup** [comment]
Great; thanks!

What's the best way to include these files currently? (Pulling them from GitHub feels a bit weird).

Is there value in a `bridge.json` option that lets you specific cultures and they can be copied into the bridge output folder alongside `bridge.js`? (Or maybe even rolled into it?)

**Comment by DaniilVeriga** [comment]
@DanTup, apologies for a delay in answering and thank you for the request. Currently, there is the only way to manage locale files - manually. We should definitely have a better way. Actually, we had an internal discussion a week ago or so after your request, but forgot to answer you. Created an individual feature request with all the details - #431. If you think that something important is missed in the issue's description, please let us know. Also you are welcome with related suggestions if any.

**Comment by DanTup** [comment]
That issue looks good to me, and I see you've already started work on it. Thanks!

**Comment by vladsch** [comment]
New functionality was implemeneted (allow to specify which cultures should be extracted to output)
Please see the following pull request
https://github.com/bridgedotnet/Bridge/pull/437

**Comment by DanTup** [comment]
I saw that :)

It's easiest for us to test once it's merged but if you're after feedback before merging, let us know and we'll build from the branch and give it a go.

**Comment by LeonidVeriga** [comment]
The Pull Request has been merged.

**Comment by DanTup** [comment]
I just tried `new CultreInfo("ru-RU")` on live.bridge.net and it fails with "Culture is not supported" (so does `en-US`). One of the comments above suggests the cultures should be included?

**Comment by DaniilVeriga** [comment]
@DanTup, here is a related issue.

**Comment by geoffreymcgill** [comment]
Currently Live Bridge does not load additional Culture files. This is something we're going to work on for the next release of the Live Bridge app.

**Comment by DanTup** [comment]
Ok, thanks for clarifying!
