### ISSUE TITLE
Dictionary.Values crashes

### ISSUE THREAD

**Issue by bktv** [bridgedotnet/Bridge#3499]
A dictionary mapping Guid keys to instances of a class crashes when .Values is called on our dictionary.  In this example, a dictionary with two entries does not crash when .Values is called.  The dictionary with three items does crash when .Values is called.

### Steps To Reproduce

https://deck.net/bddc9f3887adfe2cc43a88e1b76cc952

**Comment by fabriciomurta** [comment]
Hello @Bktv! Thanks for the report. You'll notice your second element in the dictionary will do break it as far as the difference in the GUID is after the 22nd digit (26th character) of the GUID.

https://dev.deck.net/b12f24d551eebf1c387b091679db4799

**Comment by fabriciomurta** [comment]
The fix for this issue has just been merged upstream. It will be available next Bridge release (see issue's milestone).
