### ISSUE TITLE
NodeList and ElementList (and possibly other collections) do not implement add/insert/remove operations

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#35]
`ElementList` and `NodeList`, defined on `Bridge.Html5`, are instances of `IEnumerable`.

Thus, they do not (directly) accept `IList`'s basic operations like .Add(). This could be inconvenient if one wants to build, for example a list of nodes/elements to batch-append on a container (like a div).

So, would it be a good idea to have this level of service (add/remove entries) for the element lists?

**Comment by geoffreymcgill** [comment]
Closing this issue as we will not be implementing this feature. All Html5, DOM, ES5 and related JavaScript core functionality is moving to [Retyped](https://github.com/Retyped/Retyped).
