### ISSUE TITLE
New ExternalCast Rule

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#3516]
Add a new **ExternalCast** [rule](https://github.com/bridgedotnet/Bridge/wiki/global-configuration#rules) to configure how Bridge treats casting of external classes.

Name | Options | Description
---- | ---- | ----
externalCast | `"Managed"` or `"Plain"` | Set to `Plain` to ignore casting external entities during run-time. See also `[IgnoreCast]` attribute. Compile-time type checking still occurs in both `Managed` and `Plain` modes. Default is `Managed`.

The **ExternalCast** rule can be configured in [**bridge.json**](https://github.com/bridgedotnet/Bridge/wiki/global-configuration#rules) or within the [`[Rules]`](https://github.com/bridgedotnet/Bridge/wiki/Attribute-Reference#rules) attribute. 

This rule does not apply to any classes within the **Bridge** or **System** namespaces. 

#### Example

https://deck.net/e4df0f2dcdb47964263c149ee4d79671

```csharp
public class Program
{
    public static void Main()
    {
        var el = (HTMLDivElement)document.createElement("div");
    }
}
```

### Expected Result

```js
// Managed
var el = Bridge.cast(document.createElement("div"), HTMLDivElement);

// Plain
var el = document.createElement("div");
```

**Comment by fabriciomurta** [comment]
Merged upstream! The feature will make it to Bridge 17!
