### ISSUE TITLE
Add method `GetInvocationList` in `Delegate` class

### ISSUE THREAD

**Issue by colderlord** [bridgedotnet/Bridge#3531]
Class `MulticastDelegate` have method `GetInvocationList`, but parent class `Delegate` haven't.
https://msdn.microsoft.com/ru-ru/library/system.delegate.getinvocationlist(v=vs.110).aspx

In `MulticastDelegate` method `GetInvocationList` should override method.
https://referencesource.microsoft.com/#mscorlib/system/multicastdelegate.cs,461

**Comment by colderlord** [comment]
Oh, i'm really sorry for that :)
You link is correct, thank you.

**Comment by fabriciomurta** [comment]
I couldn't really figure out a test case that would miss this method in the current Bridge implementation but alas, the method prototype has been moved to the right place and it should now no longer be a problem wherever it was.

That said, the "fix" will make it to the forthcoming  Bridge release!
