### ISSUE TITLE
ScriptAttribute doesn't support completely changing the constructor

### ISSUE THREAD

**Issue by emumanu** [bridgedotnet/Bridge#3532]
Using a ScriptAttribute in a constructor still calls the constructor of the base class. While this is usally the right thing to do, please add a parameter to the ScriptAttribute to replace ALL the generated code, or even better an enum with the options:
* leave this.$initialize() and the base call
* leave this.$initialize() only
* replace all the code, 

### Steps To Reproduce

https://deck.net/77a5d5b2f553345ccfe0ae3523ecb280

Thank you

**Comment by vladsch** [comment]
It is expected behavior because Script is designed to define a body of a method.
To achieve what you want just use Template.

**Comment by emumanu** [comment]
@vladsch. ok. But AFAIK there's no way from the template to get the fully qualified name of the class using a token to simulate a "new my.full.class.Name()" from the constructor.  Also, as I plan to use the same code in a lot of classes... is there any reason that your attributes are sealed? I'd like to inherit from TemplateAttribute and put my CustomConstructorAttribute without having to repeat the template code everywhere.
