### ISSUE TITLE
Type.GetConstructor does not work if the constructor is set to internal

### ISSUE THREAD

**Issue by cra0zy** [bridgedotnet/Bridge#3538]
```c#
internal class Test
{
    internal Test()
    {
    }
}

// This fails
typeof(Test).GetConstructor(new Type[0]);
```

And yes, I know, setting constructor as public in this case makes no difference to its access level, I just wanted to report an error I found.

**Comment by vladsch** [comment]
It is not bug, .NET gives the same result
https://dotnetfiddle.net/z2TP0m

**Comment by cra0zy** [comment]
> It is not bug, .NET gives the same result
> https://dotnetfiddle.net/z2TP0m

Interesting, did not realize that, change my request to allowing to pass `BindingFlags` when fetching the constructor than: https://msdn.microsoft.com/en-us/library/0h6w8akb(v=vs.110).aspx

**Comment by fabriciomurta** [comment]
I believe the issue here is clarified, right? Let us know if otherwise.

**Comment by cra0zy** [comment]
As stated above, change my request to allow to pass BindingFlags when fetching the constructor than: https://msdn.microsoft.com/en-us/library/0h6w8akb(v=vs.110).aspx
