### ISSUE TITLE
Loading Bridge as a module using RequireJS

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#3539]
When trying import Bridge as a module, an incorrect module is returned (decimal.js). The reason is the following lines in [decimal.js](https://github.com/MikeMcl/decimal.js/blob/45eec0b8631758e0fc709c3a8ecfe5775e984e2c/decimal.js#L4776-L4778):
```js
define(function () {
   return Decimal;
});
```

The problem here is that **decimal.js** code gets merged into **bridge.js** - and using `define` without providing a module name just sets `Decimal` as an exported entity for the module `"bridge"`. So the following code exporting `Bridge` is just ignored:
https://github.com/bridgedotnet/Bridge/blob/db9eca33c0c5ef97321be50744cb766eef58469c/Bridge/Resources/.auxiliary/End.js#L4

### Steps To Reproduce

**Test.html**
```html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>RequireJS test</title>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.5/require.js" 
            data-main="bin/Debug/bridge/Test.js"></script>
</head>
<body>
</body>
</html>
```

**Test.js**
```js
require(["bridge"], function(Bridge) {
    Bridge.assembly("Test", function ($asm, globals) {
    });
});
```

### Expected Result

`Bridge` argument is properly initialized and contains all members like `Bridge.assembly`, `Bridge.define` etc. No errors in the console.

### Actual Result

Error is printed to the console:
```
Uncaught TypeError: Bridge.assembly is not a function
    at Test.js:2
    at Object.execCb (require.js:1696)
    at Module.check (require.js:883)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.enable (require.js:1176)
```

### See also
-  https://forums.bridge.net/forum/community/retyped/5174-runtime-error-when-using-retyped-three-a-webgl-library

**Comment by fabriciomurta** [comment]
The feature has been merged and will make it to next Bridge release!
