### ISSUE TITLE
Creating class instances of HTML elements inside template methods

### ISSUE THREAD

**Issue by ChrML** [bridgedotnet/Bridge#3540]
When making a template method that can instantiate HTML elements.
Error is thrown in runtime at bridge.js:450 due to 'new type();' where type = HTMLDivElement.
HTMLDivElement as a native browser object is an Illegal constructor.

When invoking new HTMLDivElement() directly without template method, it translates to the following JS code: `document.createElement("div");`.
Thus issue only reproducable with template methods.

### Steps To Reproduce

https://deck.net/b7ce309fb4258993ab69b12d5b6585b4

```csharp
using Retyped;
using static Retyped.dom;

public class Program
{
    static void Main(string[] args)
    {
        // Built with Retyped
        // https://retyped.com
        
        // Create the Button the normal way
        var ButtonOK = new HTMLButtonElement();
        ButtonOK.innerText = "This button works";
        document.body.appendChild(ButtonOK);
        
        // Create the button using Template method
        // (ERROR generated here)
        var ButtonCrash = TemplateMethod<HTMLButtonElement>();	
        ButtonCrash.innerText = "This button would crash";
        document.body.appendChild(ButtonCrash);
    }
    
    static T TemplateMethod<T>() where T:class,new()
    {
        return new T();
    }
}
```

### Actual Result

```js
Same result as expected, issue is inside Bridge.createInstance(T);
```

**Comment by fabriciomurta** [comment]
Hello! Thanks for reporting the issue!

**Comment by ChrML** [comment]
Happy to help 😄

**Comment by vladsch** [comment]
Fixed in https://github.com/bridgedotnet/Bridge/pull/3660
There is one important restriction: class with templated ctor must have metadata (should be reflectable). For example, for retyped libraries, you should activate metadata generation in bridge,json because by default, metadata is not generated for extern classes.

**Comment by fabriciomurta** [comment]
Fixed! The fix will make it to the next Bridge release! See milestone bound to this for the version it will be in.
