### ISSUE TITLE
External module reference is not prefixed with the module name

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#3542]
A reference to a renamed class located under an external entity marked with `[Module]` attribute is not prefixed with the module name (the name of variable representing the loaded module).

Module name prefix should be always emitted unless `Module.preventModuleName` is set to `true`.

The logic described above works fine for non-external modules, only external ones are affected.

### Steps To Reproduce

https://deck.net/1931f513e4ffb4cbe0b10db85dbf273c

```csharp
public class Program
{
    public static void Main()
    {
        var b = new test.A();
    }
}

[External]
[Bridge.Module(Name = "test")]
public static class test
{
    [Bridge.Name("B")]
    public class A : Retyped.IObject
    {
    }
}
```

### Expected Result

```js
Bridge.assembly("Demo", function ($asm, globals) {
    "use strict";

    require(["test"], function (test) {
        Bridge.define("Demo.Program", {
            main: function Main () {
                var b = new test.B();
            }
        });
   
    // ...
```

### Actual Result

```js
Bridge.assembly("Demo", function ($asm, globals) {
    "use strict";

    require(["test"], function (test) {
        Bridge.define("Demo.Program", {
            main: function Main () {
                var b = new B();
            }
        });
   
    // ...
```

**Comment by fabriciomurta** [comment]
The fix has just been merged in! It will be available next Bridge release (see attached milestone).
