### ISSUE TITLE
JsonConvert.DeserializeObject calls non default constructor and adds values to list

### ISSUE THREAD

**Issue by kcudnik** [bridgedotnet/Bridge#3548]
JsonConvert.DeserializeObject calls non default constructor.

Not sure whether this is a feature or a bug, but i would expect that when there is no default constructor ether deserialization should fail or none of the constructors should be called. Current scenario adds "null" to the list since non default constructor is called with default parameters which for string is null. Or maybe list should be entirely replaced in that scenario instead of merge ?

### Steps To Reproduce

https://deck.net/c3b12c197292f2c81e72c4b4782044f1

```csharp
public class B
{
    public B(string foo)
    {
        Console.WriteLine("ctr: {0}", foo ?? "null");
        
        list = new List<string>{foo};
    }
    
    public List<string> list;
}

public class Program
{
    public static void Main()
    {
        var b = new B("foo");
        
        b.list.Add("baz");
       
        string s = JsonConvert.SerializeObject(b);

        Console.WriteLine(s);

        var bb = JsonConvert.DeserializeObject<B>(s);
        
        foreach(var item in bb.list)
        {
            // null is on list
            Console.WriteLine("{0}", item ?? "null");
        }            
    }
}
```

### Expected Result

```js
ctr: foo
{"list":["foo","baz"]}
foo
baz
```

### Actual Result

```js
ctr: foo
{"list":["foo","baz"]}
ctr: null
null
foo
baz
```

**Comment by fabriciomurta** [comment]
Hi! This looks like something that should be logged here: [Bridge.Newtonsoft.Json issues](https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/issues).

If you don't mind reopening the issue there, we could add something more (I'm getting the `ctr: null` but not the `null` empty line if I run the code in dotnet fiddle).

**Comment by kcudnik** [comment]
Moved to https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/issues/107
