### ISSUE TITLE
Support bridge code in NuGet packages without having to reference all dependencies in web app

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#355]
I started a discussion [here](http://forums.bridge.net/forum/community/help/342-how-do-i-include-code-from-a-nuget-package), but I think it's worth adding here as a feature request.

Currently there doesn't seem to be a good solution to sharing code via NuGet packages. Even if JS is included in NuGet packages for Bridge libraries; the output JS will not be copied to the correct location in the Web project unless the NuGet package is explicitly referenced there.

It's not practical to have all web projects have direct NuGet references to the entire tree of NuGet dependencies from the Bridge code projects. Nor is it practical to have all code in a single solution.

I'm not really sure what a good solution would be, but if the JS for a project could be included in its assembly, then maybe it could be pulled out and dumped into the Bridge output folder during build?

I'm guessing you must already have something similar to this for bridge.js?

**Comment by LeonidVeriga** [comment]
Yes, it is a right place for feature requests)

And yes, bridge.js is in bridge.dll and unpacked during transpilation. We will think about facilitating this process for Bridge libraries.

Will setting up the Bridge project referencing NuGet to copy the NuGet's JS into the Web project?

**Comment by DanTup** [comment]
> Will setting up the Bridge project referencing NuGet to copy the NuGet's JS into the Web project?

While our projects are small, this (or something similar) will work fine. But once our NuGets packages have dependencies on other NuGet packages, I think it'll break down quickly (in order to copy them all the way down, we'd need to be committed all JS files at every level, to include them in all NuGets that reference any given NuGet).

It's not urgent there's some solution now, but I do think there's great value in having some solution that allows nested NuGets easily.

**Comment by fabriciomurta** [comment]
I will just share some thoughts about your feature request here. Hope this helps in anything.

A problem in such approach would be naming conflicts. Although not likely to happen when `outputBy` bridge.json setting is 'Namespace', it would most likely happen if `outputBy` is class-based for example, and the user would have no control over it, as even two NuGet packages could conflict between themselves.

Other issue would be to identify between the project references which ones should be or should be not used as targets for Bridge Builder.

Otherwise, it sounds pretty straightforward to have Bridge builder, from a Bridge.DLL, output the correct JavaScript.

What seems more feasible in my opinion is, having the NuGet packages deploy not DLL files, but the .cs source files in a separate directory. This way you can both guarantee and give user control over name conflicts. Also conflicts with `outpubBy='class'` would not happen as instead of overwriting the files they will be appending (as it is the same single DLL being processed).

After all, the code is meant to be readable as the target product is a readable code, right?

**Comment by DanTup** [comment]
> A problem in such approach would be naming conflicts.

I don't think conflicts is a big issue. If people build packages with vague names, that's their fault and people will avoid their packages. That's not a million miles different to NuGets having same namespace/classes. It would be acceptable to me to fail a build if this happens.

> Other issue would be to identify between the project references which ones should be or should be not used as targets for Bridge Builder.

I'm not entire sure what this means, but Id' say that any project being built by Bridge should have all of its dependencies checked for bridge embedded resource, and have them pulled out. I don't think it makes sense to reference a bridge-built NuGet/DLL and not have the scripts from it?

> What seems more feasible in my opinion is, having the NuGet packages deploy not DLL files, but the .cs source files in a separate directory.

This sounds like it could work; though does mean committing the .cs files at all levels down to source control (since I don't think package-restore puts back content files). I don't think it's an ideal solution, but might be the best current option.

I'll try it out this afternoon and see if it works well.

**Comment by LeonidVeriga** [comment]
Hi @DanTup !
We have implemented feature #413:
> Translator should inject generated script to an assembly and if the assembly is referenced inside another project then extract embedded script to output folder

Please let us know if this works for you.

**Comment by DanTup** [comment]
Excellent! One of my colleagues actually got some of this working using your plugin API; though I didn't get chance to thoroughly test it. Native support is even better!

I'll try to test this out next week and let you know if it's all working. I need to figure out what's changed in your repo that has broken our build server first! =D

**Comment by DaniilVeriga** [comment]
> I need to figure out what's changed in your repo that has broken our build server first!

Builder and Testing repos have been merged into Bridge - #405. Maybe, it is a case.

**Comment by DanTup** [comment]
> Builder and Testing repos have been merged into Bridge - #405. Maybe, it is a case.

That sounds likely - I saw the error was failing to find a dll in the build output, but didn't get chance to dig into it. Thanks!

**Comment by LeonidVeriga** [comment]
@DanTup Sorry for buzzing, did you have a chance to try this new feature? We would very appreciate a feedback from you... )

**Comment by DanTup** [comment]
@LeonidVeriga Sadly, not yet. Really busy at work this week (mostly our Bridge/React time is limited to Friday while we're prototyping). I'll do my best to find a little spare time, but if not it might have to be Friday.

If you can easily build a nupkg and mail it to me, that'd save me having to fix up Bridge on our buildserver and I might be able to get to it a little quicker (email is firstname @ lastname .com).

**Comment by LeonidVeriga** [comment]
@DanTup I sent the package.
There is no rush, please take your time. We are targeting next Monday to release 1.9. Looking forward to your feedback.

**Comment by DanTup** [comment]
Ok, I've managed to have a quick test of this; and it all seems to work as expected :) We now can build NuGets that don't directly bring the .cs files into our projects, but do output the required JS during builds :)

However, the version you emailed to me does seem to have a serious bug, I'll raise a separate case about that in case it's present in the current code (I'm hoping to get our buildserver building again today, so I'll be able to test this with latest code).

**Comment by LeonidVeriga** [comment]
That is great! Thanks for testing and providing the feedback.
