### ISSUE TITLE
UnknownIdentifierResolveResult in self-referencing local function

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#3560]
Local function calls itself recursively and is emitted with `UnknownIdentifierResolveResult` refernece.

### Steps To Reproduce

https://deck.net/346bedf88cf0a2b9f15263aeb351c25a

```csharp
public class App
{
    public static void Main()
    {
        F(10);
        
        void F(int x)
        {
            if (x > 0)
                F(x - 1);
        }
    }
}
```

### Expected Result

```js
var F = function (x) {
    if (x > 0) {
        F((x - 1) | 0);
    }
};
F(10);
```

### Actual Result

```js
var F = function (x) {
    if (x > 0) {
        [UnknownIdentifierResolveResult F](((x - 1) | 0));
    }
};
F(10);
```

## See Also

* https://github.com/bridgedotnet/Bridge/issues/3557#issuecomment-387518007
* https://github.com/bridgedotnet/Bridge/issues/3558

**Comment by fabriciomurta** [comment]
Fixed! The fix is going to make it to next Bridge release (see attached milestone)!
