### ISSUE TITLE
Review default bridge.json file and add new rules

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#3563]
The sample **bridge.json** that is installed with Bridge should be updated to include the new `inlineComment` and `externalCast` [rules](https://github.com/bridgedotnet/Bridge/wiki/global-configuration#rules). See [docs](https://github.com/bridgedotnet/Bridge/wiki/global-configuration).

https://github.com/bridgedotnet/Bridge/blob/dev/.build/files/bridge.json

The other configs within the sample **bridge.json** should also be reviewed.

**Comment by fabriciomurta** [comment]
Merged in! This feature will make it to the next bridge release.
