### ISSUE TITLE
Calling CancellationTokenSource.Dispose() throws NullReferenceException

### ISSUE THREAD

**Issue by ddaspit** [bridgedotnet/Bridge#3570]
In Bridge.NET 17, when I try to call the `Dispose` method of `CancellationTokenSource`, a `NullReferenceException` is thrown. It looks like the generated JS is trying to call `dispose` which does not exist. It should be calling `Dispose`.

### Steps To Reproduce

https://deck.net/8e2b87ac3498763ae85fb572e064fbce/three

```csharp
public class Program
{
    public static void Main()
    {
        try
        {
            var cts = new CancellationTokenSource();
            cts.Dispose();
            Console.WriteLine("Dispose() successful.");
        }
        catch (NullReferenceException ex)
        {
            Console.WriteLine("Dispose() unsuccessful.");
        }
    }
}
```

### Expected Result

```
Dispose() successful.
```

### Actual Result

```
Dispose() unsuccessful.
```

**Comment by fabriciomurta** [comment]
Hello! Thanks for the report!We've fixed this a few days ago and now reviewed the fix, finally merging it up mainstream. The fix will make it out to the next Bridge release (issue's milestone reflects the version it should get to).
