### ISSUE TITLE
Incorrect message in exception thrown by IList for read-only collections

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#3585]
The message thrown by `IList` for modification attempts of a read-only collection should be corrected.

### Steps To Reproduce

https://deck.net/752836565d7c92511823db09cb8903cc

https://dotnetfiddle.net/077OGB

```csharp
public class Program
{
    public static void Main()
    {
        var list = new List<int> { 1, 2, 3 };
        var roList = list.AsReadOnly();
        var ilist = (IList)roList;
		
        try
        {
            ilist.Insert(0, 0);
            Console.WriteLine("No Exception");
        }
        catch (Exception ex)
        {
            Console.WriteLine("[Error]: " + ex.Message);
        }
    }
}
```

### Expected Result

Console output:
```
[Error]: Collection is read-only.
```

### Actual Result

Console output:
```
[Error]: Collection was of a fixed size.
```

**Comment by fabriciomurta** [comment]
Fixed and ensured the right message goes to the exception depending on the base type of list, discerning between fixed-length array and read-only lists.
The fix will make it to next Bridge release (see milestone).
