### ISSUE TITLE
Metadata error when parent class is marked with [GlobalMethods]

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#3587]
Bridge generates metadata containing an error for classes nested in a `[GlobalMethods]` class. This error prevents usage of metadata for a lot of Retyped entities, because it's pretty common for Retyped to generate a top level entity marked with `[GlobalMethods]` attribute.

For the sample below the following metadata string is generated:
```js
var $m = Bridge.setMetadata,
$n = [];
$m("Test", function () { return {"td":,"att":1048578,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"}]}; });
```

The error is in `td` property, which doesn't have any value:
```js
"td":,
```

### Steps To Reproduce

https://deck.net/a197fc5861aedbaccb49037cfcfd63ca

```csharp
[Reflectable]
[GlobalMethods]
public static class Global
{
    public class Test
    {
    }
}
```

### Expected Result

No error.

### Actual Result

Console output:
```
System.Exception: SyntaxError: Unexpected token ,
```

**Comment by fabriciomurta** [comment]
The fix was just merged upstream! Will be available next Bridge release (see milestone).
