### ISSUE TITLE
The predefined type `System.Threading.Interlocked' is not defined or imported

### ISSUE THREAD

**Issue by txdv** [bridgedotnet/Bridge#359]
When I try to compile something with IEnumerable on mono/ubuntu I get this following message:

```
/home/bentkus/Projects/Web/CSC: Error CS0518: The predefined type `System.Threading.Interlocked' is not defined or imported (CS0518) (Web)
```

I don't know what to think about this, might it be a compiler error?

**Comment by vladsch** [comment]
Bridge has no Interlocked implementation because javascript is one thread enviroment
So, most Thread stuff is missed in Bridge due impossibility to use it in javascript

**Comment by txdv** [comment]
I do understand that, but this error occurs when I try to compile something containing the IEnumerable<T> which sould be not related to System.Threading/Interlocked whatsoever?

```csharp
public class ExampleClass
{
    IEnumerable<int> Times()
    {
        yield break;
    }
}
```
Compiling this with mono creates the error.

My workaround currently is just to do this:
```csharp
namespace System.Threading
{
	class Interlocked
	{
		public static int CompareExchange(ref int location1, int value, int comparand) {
			int original = location1;
			if (location1 == comparand) {
				location1 = value;
			}
			return original;
		}
	}
}
```

I don't know whether the implementation is used at all, but I just made sure it is correct.

**Comment by vladsch** [comment]
ah, I see what you mean now. Can you describe your enviroment where you tried to build? Just for reproducing the issue

**Comment by txdv** [comment]
```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
64 bit
```

**Comment by fabriciomurta** [comment]
Hello, I could also reproduce the issue on OS X and Mono 4.x.
