### ISSUE TITLE
Use .apply() for constructors with 'params' argument taking an array

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#3590]
When `params` argument is declared in a method, Bridge uses `Function.prototype.apply` to invoke the method for array argument. The same approach should be used for constructors (case **2.2**).

Fix proposal (see **fix** variable):
https://deck.net/9a30c0c025c9747eec51d3d264fcd063

More info about the used approach can be found here:
https://stackoverflow.com/questions/1606797/use-of-apply-with-new-operator-is-this-possible

## 1. Methods

Below are examples of `Array.push(params T[] items)` method.

### 1.1. Arguments list

**C#**
```cs
var works1 = new Array<string>();
works1.push("one", "two", "three");
Console.WriteLine(works1.slice(0, 2));    // OK: "one, two"
```

**JavaScript**
```js
var works1 = new Array();
works1.push("one", "two", "three");
System.Console.WriteLine(works1.slice(0, 2));
```

### 1.2. Array

`.apply()` is used here

**C#**
```cs
var works2 = new Array<string>();
works2.push(new[]{"one", "two", "three"});
Console.WriteLine(works2.slice(0, 2));     // OK: "one, two"
```

**JavaScript**
```js
var works2 = new Array();
works2.push.apply(works2, System.Array.init(["one", "two", "three"], System.String));
System.Console.WriteLine(works2.slice(0, 2));
```

## 2. Constructors

Below are examples of `Array(params T[] items)` constructor.

### 2.1. Arguments list

**C#**
```cs
var works = new Array<string>("one", "two", "three");
Console.WriteLine(works.slice(0, 2));   // OK: "one, two"
```

**JavaScript**
```js
var works = new Array("one", "two", "three");
System.Console.WriteLine(works.slice(0, 2));
```

### 2.2. Array

`.apply()` **should be** used here, like it's done in **1.2**.

**C#**
```cs
var fails = new Array<string>(new[] { "one", "two", "three"});
Console.WriteLine(fails.slice(0, 2));    // ERR: "one, two, three"
```

**JavaScript**
```js
var fails = new Array(System.Array.init(["one", "two", "three"], System.String));
System.Console.WriteLine(fails.slice(0, 2))
```

**Comment by vladsch** [comment]
@AndreyChechel, such functionality is already implemented in Bridge. To activate it, you have to apply ExpandParams attribute to constructor

**Comment by AndreyChechel** [comment]
Thanks for pointing to that attribute. 
I was misled by the fact that `[ExpandParams]` is assumed to be implicit on methods in external types. Probably that should have been conforming to external type constructors.

**Comment by AndreyChechel** [comment]
@vladsch, `[ExpandParams]` appears to be not working with external type constructors:

https://deck.net/47c05231917ca8b2d24c8a6c7bb098f3

```cs
public class Program
{
    [Init(InitPosition.Top)]
    public static void Init()
    {
/*@
var Test = (function () {
    // ...
}());
*/
    }
    
    public static void Main()
    {
        var arr = new[] {1,2,3};
        
        var test = new Test(arr);
        
        test.Foo(arr);
    }
}

[External]
[Namespace(false)]
public class Test
{
    [ExpandParams]
    public extern Test(params int[] arr);
    
    [ExpandParams]
    public extern void Foo(params int[] arr);
}
```

**Output**
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Bridge.Translator.MemberResolver.ResolveNode(AstNode node, ILog log)
   at Bridge.Translator.ObjectCreateBlock.VisitObjectCreateExpression()
   at Bridge.Translator.ObjectCreateBlock.EmitConversionExpression()
   at Bridge.Translator.ConversionBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitObjectCreateExpression(ObjectCreateExpression objectCreateExpression)
   at
```

**Comment by fabriciomurta** [comment]
The fix to the issue found later here was just merged upstream and will be available next Bridge release.
