### ISSUE TITLE
Debugger.Break strange changes

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#3592]
Version 16 of Bridge has this code:  

```C#
[Bridge.Template("debugger")]
public static extern void Break();
```

New one this code:  

```C#
public static void Break()
{
    Bridge.Script.Write("debugger");
}
```

I think new code is not good idea.  
Browser debugger stops inside Debugger.Break method and not in the place where Debugger.Break() called.

**Comment by geoffreymcgill** [comment]
@hardhub Good point. I will investigate.

**Comment by fabriciomurta** [comment]
The fix submitted has just been merged upstream and will be available next Bridge release! Thanks for reporting the issue, it will not work as it did back in Bridge v16.
(next Bridge release reflects the milestone bound to this issue)
