### ISSUE TITLE
StartsWith method does not compare strings correctly

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#3593]
Check sample:

### Steps To Reproduce

https://deck.net/3c0a66eae87385cde73a43f5cc5a433b
https://dotnetfiddle.net/Lg7R3U

```csharp
public class Program
{
    public static void Main()
    {
        Console.WriteLine("V".StartsWith("v", StringComparison.InvariantCultureIgnoreCase));
    }
}
```

### Expected Result

```
True
```

### Actual Result

```
False
```

**Comment by fabriciomurta** [comment]
Hello! Thanks for reporting the issue! The fix has just been merged upstream and will make it to our next Bridge release (see milestone bound to the issue).
