### ISSUE TITLE
Bridge.Html5 container elements do not provide a bulk insert method

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#36]
There's no way to directly append a list of elements/nodes inside an Html5 element when that element accepts children elements.

For example, if you make a div, you don't have a method to either:
- add a `Bridge.NodeList` or `Bridge.ElementList`
- assign the list after the class has been instantiated.
  The only method to add items, one by one, is `AppendChild()`. There's also `RemoveChild()` to remove them and `InsertBefore()` to insert a child in a given position.

Example:

```
var buttonList = new ElementList();
var btn1 = new ButtonElement { Value = "btn1" };
var btn2 = new ButtonElement { Value = "btn2" };

buttonList.Add(btn1); // error, does not exist
buttonList.AppendChild(btn2); // similar 'add' operation to element container attempt: does not exist
```

**Comment by geoffreymcgill** [comment]
This functionality is not directly part of the JavaScript api, so we will not be adding extensions to the api in Bridge. 

I think everyone can agree that these helper functions would be nice, but as we're [trying to] strictly following the JavaScript api, we will not be adding in Bridge.

As discussed in #37, helpers are best implemented in a _"3rd party"_ extension library.
