### ISSUE TITLE
Implement BitArray support

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#360]
Related forum discussion:
http://forums.bridge.net/forum/community/help/422-overview-of-what-is-currently-supported

**Comment by geoffreymcgill** [comment]
Possible .js library to implement BitArray:

https://github.com/bramstein/bit-array

**Comment by vladsch** [comment]
Implemented here
https://github.com/bridgedotnet/Frameworks/commit/8f5a261886fc4c072cd76d90a492f470d9f08dac
