### ISSUE TITLE
Implement HashTable and HashSet support

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#361]
Related forum discussion:

http://forums.bridge.net/forum/community/help/422-overview-of-what-is-currently-supported

**Comment by geoffreymcgill** [comment]
Possible .js library for HashTable implementation:

https://github.com/timdown/jshashtable

**Comment by erik-kallen** [comment]
Probably better to write from scratch since it 1) is not very much code, and 2) custom code we will find on the Internet will most likely not work very well with .net stuff eg. overriding Equals() and using IEqualityComparer<T> variants of methods.

**Comment by geoffreymcgill** [comment]
Another forum request:

http://forums.bridge.net/forum/general/feature-requests/551-hashset-support

**Comment by vladsch** [comment]
Implemented in 
https://github.com/bridgedotnet/Frameworks/commit/8f5a261886fc4c072cd76d90a492f470d9f08dac
