### ISSUE TITLE
Task.Start raises exception in IE and Edge.

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#3617]
I cannot start Task.

### Steps To Reproduce

https://deck.net/1cb083deb0fac7a5a23e8272ca55efa6
https://dotnetfiddle.net/dgq1og

```csharp
public class Program
{
    public static void Main()
    {
        var task = new Task(() =>
        {
        });
                            
        task.Start();              
    }
}
```

### Expected Result

```
Normal task execution
```

### Actual Result

```
System.Exception: TypeError: Invalid calling object
   at statics.schedule
```

**Comment by fabriciomurta** [comment]
Fixed! The correction will be available next Bridge release (see attached milestone for exact version).
