### ISSUE TITLE
Errors in minified js file when check generic interface

### ISSUE THREAD

**Issue by colderlord** [bridgedotnet/Bridge#3618]
I've got error in **MINIFIED** js when i check generic interface `IsAbstract`.
Remark: interface should have any method.

### Steps To Reproduce

https://deck.net/9570be2d6d201044d28c6e761f851737

```csharp
public class Program
{
    public static void Main()
    {
        var isAbstract = typeof(IGenericInterface<>).IsAbstract; // Error
        Console.WriteLine(isAbstract);
    }
}

public interface IGenericInterface<T>
{
	long MyMethod();
}
```

I've got error in **MINIFIED** js when i try to get custom attributes from generic interface.
Remark: interface should have any method.

### Steps To Reproduce

https://deck.net/3c42aa72209f9389c4c6bb41e95b6351

```csharp
public class Program
{
    public static void Main()
    {
        var arttrs = typeof(IGenericInterface<>).GetCustomAttributes(true); // Error
    }
}

public interface IGenericInterface<T>
{
	long MyMethod();
}
```

**Comment by fabriciomurta** [comment]
Thanks for reporting the issue! We have just fixed this and merged upstream! The fix will make it to the next  Bridge release (see attached milsetone).
