### ISSUE TITLE
DateTime.Date() returns different results if only the seconds field differs in UTC times

### ISSUE THREAD

**Issue by bktv** [bridgedotnet/Bridge#3621]
DateTime.Date() returns different results if the seconds field differs

### Steps To Reproduce

https://deck.net/93a9d3ed52d8a5949d7216fc697f7c8c

Source of the error is here:

https://github.com/bridgedotnet/Bridge/blob/master/Bridge/Resources/Date.js#L1148-L1164

```js
$clearTime: function (d, isUTC) {
    var dt = new Date(d.getTime());

    if (isUTC === true) {
        dt.setUTCHours(0);
        dt.setUTCMinutes(0);
        dt.setUTCMinutes(0);
        dt.setUTCMilliseconds(0);
    } else {
        dt.setHours(0);
        dt.setMinutes(0);
        dt.setSeconds(0);
        dt.setMilliseconds(0);
    }

    return dt;
},
```

**Comment by geoffreymcgill** [comment]
Thanks for pointing out this defect. Looks like the first `dt.setUTCMinutes(0);` should have been `dt.setUTCSeconds(0);`.

**Comment by fabriciomurta** [comment]
Fixed! The issue's fix has just been merged upstream and will make it next Bridge release! See issue's milestone for the version it will be in; at the time of the writing of this response, 17.2.0.
