### ISSUE TITLE
Inheriting from an external class (no base() call case)

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#3622]
A class-successor has to call a default constructor of an external base class even when `base()` call is not specified explicitly.

Related to #2735 and #2189.

### Steps To Reproduce

https://deck.net/abf6fe87cb3641732d977c0f8543788b

```csharp
public class Program
{
    [Init(InitPosition.Top)]
    public static void Init()
    {
        /*@
var A = (function () {
    function A() {
        System.Console.WriteLine("A initialized.");
    }
    return A;
}());
        */
    }
    
    public static void Main()
    {
        var b = new B(); 
    }
}

[Virtual]
[Namespace(false)]
public class A 
{
}

public class B : A
{
    public B()
    	// : base()   // Uncomment to fix
    {
    }
}
```

### Expected Result

Console output:
```
A initialized.
```

### Actual Result

Nothing was written to output.

**Comment by fabriciomurta** [comment]
Fixed! The merged code went to Bridge upstream `dev` branch and will be part of next Bridge release!
