### ISSUE TITLE
Problem with Composite String when having { characters in the format- string

### ISSUE THREAD

**Issue by ChrML** [bridgedotnet/Bridge#3626]
**When using composite string formatting in code to generate a string value and you need brace characters in the result string:**
Normally you would specify that by escaping them like this {{ and }} in the format string. Escaping like this causes wrong output when formatting certain strings in Bridge .NET 17.1.

I've tested this code in a Win32 Console application, where output is consistent with expected results.

### Steps To Reproduce

https://deck.net/3ac6a790bac78782876a526e07352456

```csharp
// Bug report by Christian "ChrML" Lundheim
public class Program
{
    public static void Main()
    {
        // Format a string
        string TestVariable = "Hey";
        var Result = $"{{TEST:{TestVariable}HelloWorld}}";
        Console.WriteLine(Result);
        
        // Expected output:  {TEST:HeyHelloWorld}
        // Actual output:    {TEST:{0}HelloWorld}
    }
}
```

### Expected Result

```
{TEST:HeyHelloWorld}
```

### Actual Result

```
{TEST:{0}HelloWorld}
```

**Comment by geoffreymcgill** [comment]
Hi @ChrML, 

Thanks for the report and excellent sample demonstrating how to reproduce. We will investigate and fix to match the expected native .NET result.

**Comment by fabriciomurta** [comment]
The fixed issue has just been merged upstream! It will be available next Bridge release! (see issue's milestone)
