### ISSUE TITLE
Bridge.Translator error while trying to close the project file under Linux and OS X on Mono + msbuild

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#3632]
Bridge Translator's OpenProject() and CloseProject() calls to `msbuild` that attempts to load and unload projects fails during Bridge Build time.

### Steps To Reproduce

- Reproducible at least on VS for mac (possibly on linux as well)
- Install Visual Studio for Mac
- Create a new project/solution under .NET > Library (ClassLibrary)
- Install Bridge 17.1.0 NuGet packages

#### Scenario 1: all from VS4Mac
- Try to build the project from VS4Mac (you may close and re-open the solution to ensure bridge settings kicks in)

#### Scenario 2: project created from VS4Mac, built from Bridge CLI
- Open a console
- install bridge 17.1.0 from homebrew if not installed (`brew install bridgedotnet/cli/bridge`)
  (update it if already exists: `brew update bridge`)
- Change directory to the project's root (not solution's)
- run `bridge build`

### Expected Result

Build is successful in either scenario.

#### Scenario 1:
Error during Bridge build:
`The project file "<project path>" cannot be unloaded because at least one project "<same project path>" is still loaded which references that project XML.`
From: Microsoft.Build package's `UnloadProject()` call made by `Translator.CloseProject()`.

#### Scenario 2:
Error during bridge build:
`[ERROR] FATAL UNHANDLED EXCEPTION: Could not load type of field from assembly `System.Threading.Tasks.Dataflow`, initiated from `Translator.OpenProject()`. (message not exactly what shows up on the mac output for simplicity).

**Comment by fabriciomurta** [comment]
It was also noticed building Bridge CLI becomes no longer possible after installing VS for Mac on OS X. The same problem from Scenario 1 occurs.

**Comment by fabriciomurta** [comment]
This is most likely a side effect of the new csproj format support which references Microsoft.Build.* packages, and uses it to handle project files. For some reason under linux it "shares" the open project with other instances.

**Comment by fabriciomurta** [comment]
@hardhub opened the related issue above, so marking this as premium.

**Comment by hardhub** [comment]
Maybe this comment will be helpful:

https://github.com/bridgedotnet/Bridge/issues/3638#issuecomment-397366645

**Comment by fabriciomurta** [comment]
@hardhub, by your report, you been using 17.1.0, right? This makes sense as I suspect it may be related to the new csproj format support (pr #3591), which introduced `Microsoft.Build.*` package referencing from the Bridge Translator to parse project files.

**Comment by hardhub** [comment]
@fabriciomurta yes... Bridge.17.1.0. I am trying to use always latest version because it often offers some fixes.

**Comment by fabriciomurta** [comment]
The main issue has just been fixed. Building from VS4Mac or `msbuild` (on mac/osx) should work fine now.

But building those projects with Bridge CLI should break due to other problems, related to lacking support from the Microsoft.Build.Framework official NuGet packages regarding mono.

To fix that other part, it will probably be necessary to investigate how mono has made `msbuild` working on their own. Mono has a fork from Microsoft's `msbuild` repository where they have been applying patches that ultimately made it work under linux.

Using `xbuild` might just work as well (as it will remove bridge translator's need to open the project itself).

This side issue should probably be logged under bridgedotnet/CLI repository, as it is specific to using Bridge Translator from Bridge CLI.
