### ISSUE TITLE
Incorrect string interpolation for char

### ISSUE THREAD

**Issue by d-p-y** [bridgedotnet/Bridge#3642]
Hi,
It seems that string interpolation operator treats 'char' as 'int' resulting in incorrect System.String.format parameter.

### Steps To Reproduce

https://deck.net/8203d3976e7b6e35c2a5b43e4aaee3cc

```csharp
public class Program
{
    public static void Main()
    {        
        Console.WriteLine($"expected 'Y' but got: {'Y'}");
    }
}
```

### Expected Result

In C# interactive it returns
```js
expected 'Y' but got: Y
```

### Actual Result

In deck it returns:
```js
expected 'Y' but got: 89
```

**Comment by vladsch** [comment]
It is Deck problem. Online transpiler uses the following transpiler rule
```json
"rules": {
    "boxing": "Plain"
  }
```

So, boxing functionality is deactivated. If you create a project and install Bridge package then boxing will be active by default and your sample will work correctly.

**Comment by geoffreymcgill** [comment]
Here's an updated sample on Deck with a `BoxingRule` override. 

https://deck.net/a073f276d4146e2ca3c706836a4593cb

```csharp
using System;

public class Program
{
    [Bridge.Rules(Boxing = Bridge.BoxingRule.Managed)]
    public static void Main()
    {        
        Console.WriteLine($"expected 'Y' but got: {'Y'}");
    }
}
```

Within your **bridge.json** file, you can revise the `rules` section by setting `"boxing": "Managed"` instead of `"Plain"`. 

```json
"rules": {
    "boxing": "Managed"
  }
```

Hope this helps.
