### ISSUE TITLE
Simple implementation of SemaphoreSlim

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#3648]
I know JS single threaded. But modern browsers support web workers.

Though that even does not matter. We also can get race condition for any async code related to XHR or setTimeout callbacks.

So if you start some async code multiple times and check some variable for null before making real initialization then you cannot be sure that this variable will be initialized only once. And it is exactly the case where SemaphoreSlim will be optimal solution.

```C#
    // It is just an idea, not completed...
    public class SemaphoreSlim
    {
        #region Constructors
        public SemaphoreSlim(int initialCount, int maxCount)
        {
            if (initialCount < 0 || initialCount > maxCount)
                throw new ArgumentOutOfRangeException(nameof(initialCount));

            if (maxCount <= 0)
                throw new ArgumentOutOfRangeException(nameof(maxCount));

            this.initialCount = initialCount;
            this.maxCount = maxCount;
        }
        #endregion

        #region Fields
        // TODO: Implement it later.
        private readonly int initialCount;
        private readonly int maxCount;

        private readonly Queue<TaskCompletionSource<bool>> queue = new Queue<TaskCompletionSource<bool>>();
        #endregion

        #region Methods
        public Task WaitAsync()
        {
            TaskCompletionSource<bool> completion = new TaskCompletionSource<bool>();

            this.queue.Enqueue(completion);

            if (this.queue.Count == 1)
                completion.SetResult(true);

            return completion.Task;
        }

        public void Release()
        {
            TaskCompletionSource<bool> completion = this.queue.Dequeue();

            if (completion.Task.IsCompleted == false &&
                completion.Task.IsCanceled == false &&
                completion.Task.IsFaulted == false)
                throw new InvalidOperationException("Failed to release wrong semaphore.");

            if (this.queue.Count > 0)
                this.queue.Peek().SetResult(true);
        }
        #endregion
    }
```

**Comment by geoffreymcgill** [comment]
This looks very cool. Might be better to post this in the forums and share a Deck link to a sample. 

I'm going to close this issue as it's better to share demos in the [forums](https://forums.bridge.net).

**Comment by hardhub** [comment]
@geoffreymcgill 
I have created this issue to ask if it is possible to finish this code (or maybe implement new) and make it a part of Bridge? It is important class for synchronization in case of async/await pattern - [Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/api/system.threading.semaphoreslim?view=netframework-4.7.2)

**Comment by otabekgb** [comment]
Web workers don't share data, the data are copied and marshalled, so there is no need for locks. In order to share same code base the locks should be ignored by bridge compiler

**Comment by hardhub** [comment]
> Web workers don't share data, the data are copied and marshalled, so there is no need for locks. In order to share same code base the locks should be ignored by bridge compiler

It is not related to web workers. It is related to async pattern. SemaphoreSlim allows to be in specific section of code only by one (or N - not actual for JS) thread(s). In case of timer or XHR callbacks it is very actual.
