### ISSUE TITLE
Documentation ?

### ISSUE THREAD

**Issue by matantsu** [bridgedotnet/Bridge#365]
Is there documentation for Bridge.NET?

**Comment by DaniilVeriga** [comment]
Hello @matantsu,

As for code base, we try doing our best writing inline XML doc comments, but it is not organized as documentation yet. Currently, the best learning source is [Knowledge Base](http://bridge.net/kb). [Blog](http://bridge.net/blog) is also worth to read.  And you are always very welcome on the [forums](http://forums.bridge.net).

I should say that documentation and learning sources is in priority and a subject to be constantly improved.

**Comment by matantsu** [comment]
I find the Knowledge Base to be very superficial , it's good for getting started but does not offer enough info for creating a library , or contributing.

Is it possible to generate a documentation viewer for those XML comments ?

**Comment by geoffreymcgill** [comment]
The Bridge.Html5 library is built off the ES5 documentation at [Mozilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference).

Bridge.jQuery2 is built off the [jQuery 2](https://api.jquery.com/jquery-2/) documentation.

**Comment by kuashe** [comment]
+1 , I really agree with @matantsu  , the "Knowdlege Base" is insufficient, and their should be a full API documentation using a documentation generator and more examples .

**Comment by fabriciomurta** [comment]
Hello, as a pre-requisite to this, we already have #42. And as this issue seems more a general approach to documentation, I've just created issue #398 to implement the API Documentation support so we can make available online a version for (at least) latest public version and allow users building on their own to compile also this documentation pages.

What @geoffreymcgill said above about jQuery2 and Html5 as well as other frameworks' support is still actual: we won't mean to duplicate the whole Framework documentation, just what bridge directly maps, as the API documentation. Details on usage would always need referencing the original framework's documentation. So in the API docs we expect to see partial documentation about jQuery2 functions as well as LINQ extensions, for example.

**Comment by TechnikEmpire** [comment]
I need documentation sufficient enough to teach me how to build my own third-party frameworks for this tool. Not trying to be too critical, but the tool being open source doesn't do anything other than some cheap PR if nobody knows how to go about extending it. This is where the power and community traction is going to come from with this being open source, people contributing frameworks.

**Comment by geoffreymcgill** [comment]
Hello @TechnikEmpire,

Check out the [Frameworks](https://github.com/bridgedotnet/Frameworks) project, especially jQuery. Use these projects as examples to start from.

The [Attribute Reference](http://bridge.net/kb/attribute-reference/) knowledgebase article should also be reviewed. 

If you have questions or comments, please feel free to post in the [forums](http://forums.bridge.net) and we will be happy to assist.

**Comment by DaniilVeriga** [comment]
The Knowledge Base [Building A Definition Library](http://bridge.net/kb/building-a-definition-library) article has been published. If you look for implementing Bridge support for 3rd party JavaScript framework, reading this article is a nice start point.

**Comment by gunescancapanoglu** [comment]
So i have to for example learn jquery to be able to use Bridge.Jquery2 library?
This sounds weird.
it gets weirder; i have to learn jquery and write some code then i have to convert it to Bridge and Bridge converts it back to js?
And i was so happy that i found a library i was looking for which would save me from godforsaken js.

**Comment by geoffreymcgill** [comment]
@gunescancapanoglu: There is no requirement to use jQuery in a Bridge application. You should be able to write whatever you want in C#, but you are running your application in a browser, so accessing some of the JavaScript API's and other frameworks might be helpful.

Including **Bridge.Html5** in your app would likely be the minimum necessary for a browser app, although when you get right down to the essentials, even **Bridge.Html5** is not required.

**Comment by geoffreymcgill** [comment]
The knowledge base articles we had on http://bridge.net have been moved into the wiki (https://github.com/bridgedotnet/Bridge/wiki) and permits community contributions.

We have a goal to improve the API docs for all Bridge libraries, but this will take some time to implement.

Closing this issue for now, but obviously the documentation can always be improved.
