### ISSUE TITLE
Error in UMD js module when using generic class or interface

### ISSUE THREAD

**Issue by SteamUpdate** [bridgedotnet/Bridge#3652]
I've got error when i try to add compiled js file on html page
Remark: example with interface, but when i using abstract class a error is same

### Steps To Reproduce

https://deck.net/d4717c7dbc08f308beaf8e2bd5f59207

```csharp
[Module(ModuleType.UMD, "TestUmdJs")]
public class App
    {
        public static void Main()
        {
            var entity = new Entity();
            Console.WriteLine(entity.Main());
        }
    }

[Module(ModuleType.UMD, "TestUmdJs")]
    public interface IEntity<T>
    {
        T Main();
    }
    
[Module(ModuleType.UMD, "TestUmdJs")]
    public class Entity : IEntity<long>
    {
        public long Main()
        {
            return 123;
        }
    }
```

### Expected Result

`123` in bridge console

### Actual Result

Error: 
```
TestCommonJs.js:35 Uncaught TypeError: TestUmdJs.TestCommonJs.IEntity$1 is not a function
    at TestCommonJs.js:35
    at TestCommonJs.js:15
    at TestCommonJs.js:17
    at Object.Bridge.assembly (bridge.js:3294)
    at TestCommonJs.js:6
```

**Comment by fabriciomurta** [comment]
Hello, @SteamUpdate! Thanks for reporting the issue! We've just fixed it, and merged upstream.

The fix will make it to the next Bridge release, and it is already available from github, `dev` branch, if you build from sources. The version it will be released in should match this issue's milestone, which was 17.2.0 at the time of the writing of this follow up.
