### ISSUE TITLE
File index.html is generated even if disabled in config

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#3654]
I have used the following in accordance to [docs](https://github.com/bridgedotnet/Bridge/wiki/global-configuration#html):

```
   "html": {
      "disabled": true
   },
```

But file is generated and copied to output.

**Comment by geoffreymcgill** [comment]
I ran a couple tests and was unable to reproduce. The **index.html** was not generated with the **bridge.json** setting you specified above.

**Comment by hardhub** [comment]
I have removed all Bridge nuget packages and then added it back again.  
Now all works fine. It looks like an issue with updating of Bridge packages (first time they added to solution many time ago). Or maybe it is issue with migration from one VS version to another.  
Let's close issue for now.
