### ISSUE TITLE
Issue when copy a nullable struct value to a new struct variable

### ISSUE THREAD

**Issue by ChrML** [bridgedotnet/Bridge#3658]
Seems like there could be an issue with copying a struct from a Nullable.Value property to a new struct variable. Somehow the new struct variable references the original Nullable.Value, even though it should be an entirely new copy.

Copying a normal non-nullable struct seems to work as it should, this only seem to happen when copying from nullable struct values.

### Steps To Reproduce

https://deck.net/415130dd3fcf83fce1ed68983a77c112

```csharp
// Bug report by: Christian "ChrML" Lundheim
// 08.07.2018

// Example struct for this demo
public struct Point
{
    public float X {get;set;}
    public float Y {get;set;}
}

public class Program
{
    public static void Main()
    {
        // Initialize a nullable struct variable
        Point? A = new Point{X = 10, Y = 20};
        Console.WriteLine($"A: X={A.Value.X}, Y={A.Value.Y}");
        Console.WriteLine($"******************************");
        
        // Copy the struct and modify the copy. Observe that the original struct variable is also modified.
        Point B = A.Value;
        B.X = 100;
        B.Y = 200;
        Console.WriteLine($"A: X={A.Value.X}, Y={A.Value.Y}");
        Console.WriteLine($"B: X={B.X}, Y={B.Y}");
    }
}
```

### Expected Result
Actual output from a Win32 Console test application:

```
A: X=10, Y=20
******************************
A: X=10, Y=20
B: X=100, Y=200
```

### Actual Result
Actual output from current Deck.net:

```
A: X=10, Y=20
******************************
A: X=100, Y=200
B: X=100, Y=200
```

**Comment by fabriciomurta** [comment]
Fixed! The fix will make it to the next Bridge release!
