### ISSUE TITLE
Inheriting Element ?

### ISSUE THREAD

**Issue by matantsu** [bridgedotnet/Bridge#366]
```
class MyElement : Element
{
}

public class App
{
        [Ready]
        public static void Main()
        {
            Document.Body.AppendChild(new MyElement());
        }
}
```

giving me:
`Uncaught TypeError: Illegal constructor`
`Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.`

**Comment by fabriciomurta** [comment]
Yes, you would rather do this like below:
```csharp
    [Ignore]
    [Name("HTMLMyElement")]
    class MyElement : Element
    {
        [Template("document.createElement('myelement')")]
        public MyElement()
        {
        }
    }
```
Reference: [BR element definition on Bridge](https://github.com/bridgedotnet/Bridge/blob/master/Html5/Elements/BRElement.cs)

You can see that your element tag was created by your browser's debug tools' DOM explorer after running the script.

**Comment by matantsu** [comment]
does that also register the element with `document.registerElement('HTMLMyElement')` ?

**Comment by fabriciomurta** [comment]
No, it doesn't. It just allows you to use an element (like BR, LI, UL, BUTTON and so on) assuming it is already registered. You can try the example I provided above and check what it does output in the DOM and how the page is affected with the addition. The hidden class for the element must contain stubs for any specific attribute/method the element might support in javascript.

If you have the opportunity, please browse the source code for other defined elements to see how they've been defined in Bridge.

In the code we would not have any user-registered elements as far as I know -- as the pointed directory is for the HTML5 module, all elements there are expected to be supported by an html5-aware browser.

**Comment by DaniilVeriga** [comment]
It looks like we missed [document.registerElement()](https://developer.mozilla.org/en-US/docs/Web/API/Document/registerElement) method to be added to the Document API. Though, it might be not added for reason - the method is not supported in IE and Safari. I will try to clarify.

**Comment by DaniilVeriga** [comment]
Created a dedicated issue for `document.registerElement()` support - #389.

@matantsu, I am closing this issue if you don't mind.
