### ISSUE TITLE
Comparer<string>.Default not using System.String.compare

### ISSUE THREAD

**Issue by Triogap** [bridgedotnet/Bridge#3672]
Comparer<string>.Default.Compare(str1, str2) gives a different result the str1CompareTo(str2).

The first case calls Bridge.compare, and seems to perform char sorting.
The second case calls System.String.compare and seems to correctly sort text.

https://deck.net/42fe359ec3524e6024107106ec9c9386

I would expect that Comparer<string>.Default would call System.String.compare as System.String implements IComparer<System.String>.

**Comment by fabriciomurta** [comment]
Thanks! Here the reviewed code runs for Deck and Dotnet Fiddle with a simple Assert class implementation (to make it easier to integrate to Bridge unit tests):
- Deck: https://deck.net/b8787436140a0c269d17465e80294bd3
- Dotnet fiddle: https://dotnetfiddle.net/C9DJwq

**Comment by fabriciomurta** [comment]
Fixed! The fix will make it to the next Bridge release (refer to the milestone).
