### ISSUE TITLE
Inheriting to DOM Objects like HTMLElement or CSSDeclaration causes browser console errors?

### ISSUE THREAD

**Issue by Mercurial** [bridgedotnet/Bridge#3673]
I can't seem to inherit HTMLELement or CSSDeclaration classes to create something like pure C# css or making custom HTMLElements with specific behaviors

I think its a bug in Bridge or something I am doing wrong?

**Comment by samuelGrahame** [comment]
Hey, This is because HTMLElement class' don't exist and are converted into the raw javascript operation's.

for instance:

```csharp
var x = new HTMLDivElement();
```

```csharp
var x = document.createElement("div");
```

**Comment by fabriciomurta** [comment]
Closing this as there has not been any feedback from the reply provided for some time now.
