### ISSUE TITLE
File name not provided by error descriptors

### ISSUE THREAD

**Issue by dukc** [bridgedotnet/Bridge#3677]
When the compilation fails, the CLI compiler is helpful enough to provide a colon number in addition to line number. But, something more important is missing: It does not tell the file name! Often, you'll be able to figure it out quickly, but that's not always the case.

### Steps To Reproduce

-Try to compile any file with .cs extension that contains something that's not legal C# with the command-line compiler.

### Expected Result

```
(foo.cs, 132,12): CS0246: The type or namespace name 'DrawSource' could not be found (are you missing a using directive or an assembly reference?)
```

### Actual Result

```
(132,12): CS0246: The type or namespace name 'DrawSource' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by fabriciomurta** [comment]
Thanks for the report, @dukc! This may be an easy fix, but we should take a look whether that's something Bridge CLI could handle, something purely from Bridge Translator, or both should "inter-work" to know what is being built.

I could reproduce it by (on OS X):
```
bridge new
sed -E -i '' "s/\(msg/\(msg; break/" Program.cs
bridge build
```

**Comment by fabriciomurta** [comment]
Actually, this has already been repored in bridgedotnet/CLI#19, so there's not much point in keeping the issue here. So let's follow the issue there, right?

**Comment by dukc** [comment]
Agreed.
