### ISSUE TITLE
Nested using()s in a yield resumable method result in malformed JavaScript

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#3678]
https://deck.net/727898f58f3398e0b471f10a57db257c

**Comment by fabriciomurta** [comment]
Hello @TriEdgeAI ! thanks for reporting the issue!

Here's a dotnet fiddle showing the code should work in native .NET: https://dotnetfiddle.net/hsF4G0

**Comment by fabriciomurta** [comment]
The fix looks just right. Will be available next Bridge release.
