### ISSUE TITLE
Code generation for function getter/setters

### ISSUE THREAD

**Issue by txdv** [bridgedotnet/Bridge#368]
Hey guys, I have a function like year() which works as a getter/setter depending on whether you provide an argument or not.

Now I want to map it to C# getter/setters, so I thought of something like this:

```csharp
        // http://momentjs.com/docs/#/get-set/month/
        public int Month
        {
            [Template("month()")] get;
            [Template("month({0})")] set;
        }
```

The getter works fine, but the setter generates code like this:

```js
var mom = moment();
mom.month({0}) = 10;
console.log(mom);
```

for

```csharp
var mom = new Moment();
mom.Month = 10;
Console.WriteLine(mom);
```

Also if I try to do some constructor magic, like this:

```csharp
var mom = new Moment() { Month = 10 };
```

I get some weird stuff which doesn't work:

```js
var mom = Bridge.merge(moment(), {
    setMonth: 10
} );
console.log(mom);
```

**Comment by vladsch** [comment]
interesting, i will review how to make it work

**Comment by vladsch** [comment]
Yes, Template in accessors can be a real problem at this moment. We committed a fix to git. Now you can use the following code to achieve your requirement
```
public int Month
        {
            [Name("month")] get;
            [Name("month")] set;
        }
```

**Comment by LeonidVeriga** [comment]
Fixed in eb727d - [Name] attribute can be used
