### ISSUE TITLE
Strange error with preprocessor directives

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#3681]
Unfortunately I cannot reproduce the error in deck.net, so I am attaching two screenshots:

Error:
![image](https://user-images.githubusercontent.com/12459664/43892046-91cb62dc-9bd3-11e8-8c86-39f84f3d893e.png)

No Error:
![image](https://user-images.githubusercontent.com/12459664/43892100-b7cbf424-9bd3-11e8-831a-7a7e0a4a7b90.png)

**Comment by geoffreymcgill** [comment]
Hi @TriEdgeAI – Thanks for the report. We will try to reproduce and figure out what's going wrong. With some luck we should be able to fix and have available for the next release.

**Comment by vladsch** [comment]
Tried to reproduce with the following sample but all is fine (no errors)
https://deck.net/62c441ed4b4e795bdaf6be189ea63788

Let us know if you reproduce the error on simple sample

**Comment by geoffreymcgill** [comment]
Hi @TriEdgeAI – Any follow up on the comments by @vladsch? We're hoping to either fix or close this issue before the end of the week.

**Comment by TriEdgeAI** [comment]
I can't reproduce it on deck.net. Maybe it has something to do with line endings?

**Comment by vladsch** [comment]
Maybe you can create test solution with a minimal amount of code which reproduces the issue and place that solution to some public place (for example, create a repository on github)

**Comment by TriEdgeAI** [comment]
Alright. Will do.

**Comment by TriEdgeAI** [comment]
[ClassLibrary1.zip](https://github.com/bridgedotnet/Bridge/files/2316545/ClassLibrary1.zip)

Couldn't even reproduce it as a separate project. This is the project from the screenshot.

**Comment by TriEdgeAI** [comment]
Is this helpful?

**Comment by vladsch** [comment]
Unfortunately, the project is not compilable therefore Bridge translator is not run (the project fails on C# compiler)

**Comment by geoffreymcgill** [comment]
Closing this issue for now. In the future, if we run into a sample that demonstrates how to reproduce we will re-open the issue and attempt to fix the defect.
