### ISSUE TITLE
typeof(Type).IsAbstract returns false instead of true

### ISSUE THREAD

**Issue by ChrML** [bridgedotnet/Bridge#3683]
Reading the property IsAbstract on the typeof(Type) class returns false in Bridge .NET.
In a Win32 .NET Console application this returns true.

This may cause issues when presented with a Type object, and trying to determine whether that type is possible to create using Activator.CreateInstance. IsAbstract=false, IsInterface=false and IsClass=true makes it seem like the type Type actually can be created.

### Steps To Reproduce

https://deck.net/0135276e6f2133c0f0822b8011182f48

```csharp
public class Program
{
    public static void Main()
    {
        Type type = typeof(Type);
        Console.WriteLine($"Type.IsAbstract = {type.IsAbstract}");
    }
}
```

### Expected Result

```
Type.IsAbstract = true
```

### Actual Result

```
Type.IsAbstract = false
```

**Comment by geoffreymcgill** [comment]
Hi @ChrML – Thanks for letting us know about this issue. We will investigate and attempt to fix right away.

**Comment by fabriciomurta** [comment]
Fixed! The corrected functionality will be available next Bridge release!
