### ISSUE TITLE
IList.IsFixedSize always returns true

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#3685]
https://deck.net/39eed000da719a3a239f9069407f2795

```csharp
public class Program
{
    public static void Main()
    {
        IList arr = new int[10];
        IList list = new List<int>();
        
        Console.WriteLine(arr.IsFixedSize);
        Console.WriteLine(list.IsFixedSize);
    }
}
```

**Comment by geoffreymcgill** [comment]
Hi @TriEdgeAI – Thanks for the report and excellent sample demonstrating how to reproduce. We will investigate and try to fix right away.

**Comment by fabriciomurta** [comment]
Fixed! The implementation will be available next Bridge release.
