### ISSUE TITLE
Invalid Operation Exception: Task is not yet completed when awaiting a Task.Delay

### ISSUE THREAD

**Issue by ymitis** [bridgedotnet/Bridge#3698]
I'm getting an exception when testing async / await on Deck.NET.

### Steps To Reproduce

https://deck.net/28471af430c0880c88c76b96a5847aba

```csharp
using System.Threading.Tasks;
using System;

public class Program
{
    public static void Main()
    {
        var f = DoAsync().Result;
        Console.WriteLine(f);
    }
    
    static public async Task<string> DoAsync() {
        await Task.Delay(1);
        var foo = "bar";

        return foo;
    }
}
```

### Working Example

Here is a link to the same code running as the C# version on repl.it

https://repl.it/@yannify/SimpleAsyncAwaitExample

### Expected Result

Prints "bar" to the console

### Actual Result
```
Bridge Console
System.Exception: Uncaught System.InvalidOperationException: Task is not yet completed.
Error: Task is not yet completed.
    at $ctor1.ctor (https://deck.net/resources/js/bridge/bridge.min.js?17.3.0:7:91742)
    at $ctor1 (https://deck.net/resources/js/bridge/bridge.min.js?17.3.0:7:92840)
    at new $ctor1 (https://deck.net/resources/js/bridge/bridge.min.js?17.3.0:7:651031)
    at ctor._getResult (https://deck.net/resources/js/bridge/bridge.min.js?17.3.0:7:298258)
    at ctor.getResult (https://deck.net/resources/js/bridge/bridge.min.js?17.3.0:7:298368)
    at Function.Main (https://deck.net/RunHandler.ashx?h=-1408684951:9:39)
    at https://deck.net/resources/js/bridge/bridge.min.js?17.3.0:7:42613
    at HTMLDocument.i (https://deck.net/resources/js/bridge/bridge.min.js?17.3.0:7:6515)
    at i (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27151)
    at Object.add [as done] (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27450)

```

Thanks!

**Comment by fabriciomurta** [comment]
Got it. Deck with Assert: https://deck.net/967218212d30776809e266958dfc6496
repl.it with Assert: https://repl.it/repls/HatefulCelebratedAudacity

Thanks for reporting, and sorry for the delay posting a feedback!

**Comment by miladsadeghi72** [comment]
in fact this exception is natural
this is not like c# in applications, we have't direct thread in JavaScript
so now you must run doAsync just in Async Function
something like:

[in Dect.net ](https://deck.net/2bbcf1a36662b9e811dad8f717b5d803)

```csharp
using System.Threading.Tasks;
using System;


public class Program
{
    public async static void Main()
    {
        Console.WriteLine(await DoAsync());
    }
    
    static public async Task<string> DoAsync() {
        await Task.Delay(1);
        var foo = "bar";

        return foo;
    }
}
```

**Comment by vladsch** [comment]
Yes, an async function must be invoked through await in Bridge.Net to get the correct result.

**Comment by miladsadeghi72** [comment]
@vladsch please bro don't cancel this
i think it can happen, this is too hard and need change a lot
but this is so important, because this stop the last async and sync that
if we unable to convert async programs to sync then coding is very hard
otherwise we made backward async on our products
![untitled](https://user-images.githubusercontent.com/36438725/53051423-18b6ce00-34b1-11e9-91a9-d9baf79e2383.png)

we write actions directly on events
how ever think about this option, don't cancel it for ever
