### ISSUE TITLE
Bridge.is not working with System.Array.type(System.Object) in multiproject solution

### ISSUE THREAD

**Issue by kosmab** [bridgedotnet/Bridge#3699]
Multiproject issue, cannot be reproduced in deck.

We have a class c1 defined in project 'core'
  public class c1
    {
        public object p1 { get; set; }
        public object p2 { get; set; }
    }

and  method m1 also in project 'core'

public void m1(object o2)
{
if(o2 is object[])
{
//its ok do something
object[] o3 = (object[]) o2;
//...
}
}

When instance of c1 is created in project 'app' (referencing 'core') in following way:
 c1 o1 = new c1
    {
        p2 = new object[]
        {
            "a",
            new
            {
                x = 1,
                y = "b"
            }
        }
    };

then call from 'app' project to method m1(o1.p2)  fails.
When everything is in single project - it works.

Following test works always
 o2.GetType() == typeof(object[])
but casting o2 to object[] fails in multiproject case.

the problem is in Bridge.is or below.

**Comment by vladsch** [comment]
I created a test solution with two projects as described and couldn't reproduce the issue. It works fine for me (tested under Bridge 17.3.0)

**Comment by kosmab** [comment]
OK, there is a problem at our side - we clone objects, where target is created as
oTarget = new object();
and source as
oSource = new object[];
After copying properties (using GetOwnPropertyNames enumeration), resulting object mimics array, but isn't
