### ISSUE TITLE
Bridge.Html5 inconsistency among basic collection operations

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#37]
Elements that may contain other elements (like DIV) have some level of inconsistency among the names of the operations bound to them.

For example, you can't get a div and `.Add()` items to it, as one would expect. Instead, you have to `.AppendChild()`. This is ok, as you just have to memorize it thru time. But everyone learning to use the tool will likely try an `.Add()` method first.

Additionally, having in mind Add, Delete, Insert operations:
- You have no `Add`. You have `AppendChild`
- You have no `Del`. You have `RemoveChild`. 
- You have `Remove` that does something likely to be unexpected.
- You have no `Insert`. You have `InsertBefore`, which requires you to point an instance of the object in the position you want to insert the element on.
- There's no `insert` which you can provide the position index in the elements list.

This will probably generate some confusion and difficulty for people to learn the tool. Maybe there should be a common interface for all elements which accept children items so they all inherit the same set of methods.

The same should apply to the other modules (BootStrap, jQuery) as long as they have element items in the same container concept.

**Comment by geoffreymcgill** [comment]
Should be implemented in an Extension library, likely a 3rd party library.
