### ISSUE TITLE
Treat warnings as errors for all projects

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#370]
It is a very good practice to check all compiler warnings. The only way to always look for warnings is to use TreatWarningsAsErrors.

**Comment by fabriciomurta** [comment]
Linux builds are broken due to this setting. I will investigate and provide feedback for it. Please don't close this issue in the meanwhile.

**Comment by DaniilVeriga** [comment]
Interesting, how could this happen if the change is made after Bridge 1.8.0? Seems that developer said that he faced the problem after upgrading to 1.8.0, no? Or he is building from the sources?

**Comment by vladsch** [comment]
I guess from source,
>And when I try to build Bridge and all it dependencies, I now get a lot of errors, did someone turn on error on warning?

**Comment by fabriciomurta** [comment]
Interesting. `Bridge.Contract.Helpers.ToTypeDefinition()` has a `key` variable that is defined and never used. Yet, on windows no warning is emitted. Were warnings for unused variables suppressed?

**Comment by fabriciomurta** [comment]
The last commit above (bridgedotnet/Builder@e87a7f1) was sent to the [issue370 branch on the Builder repository](https://github.com/bridgedotnet/Builder/tree/issue370).

It changes sensitive code in Bridge's translator and must be carefully tested.

**Comment by LeonidVeriga** [comment]
There is a difference between Mono and VS in how it throw warnings. Handling only VS warnings is enough. So we enable TreatWarningsAsErrors in VS only:
```
  <PropertyGroup Condition="$(OS) != Unix">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
```
