### ISSUE TITLE
Proposal: New [Optional] Attribute

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#3702]
New `[Optional]` Attribute modifies the generated .d.ts to include the TypeScript `?` optional modifier. 

**Applies to:** `Property` and `Field`

### Steps To Reproduce

https://deck.net/f50b252e4ff7c9479019fdac5955693e

```csharp
public class Person
{
    [Optional]
    public string Name { get; set; }
    
    public string Company;
}
```

### Expected Result

```ts
declare namespace Demo {
    interface Person {
        Company?: string | null;
        Name?: string | null;
    }
    interface PersonFunc extends Function {
        prototype: Person;
        new (): Person;
    }
    var Person: PersonFunc;
}
```

### Actual Result

```ts
declare namespace Demo {
    interface Person {
        Company: string | null; // add ?
        Name: string | null; // add ?
    }
    interface PersonFunc extends Function {
        prototype: Person;
        new (): Person;
    }
    var Person: PersonFunc;
}
```

## See also

* https://forums.bridge.net/forum/community/help/5660-typescript-generator-nullable-optional-properties

**Comment by FlowIT-JIT** [comment]
+1

**Comment by fabriciomurta** [comment]
Implemented! The feature will be fully available the coming Bridge release (see milestone).

**Comment by FlowIT-JIT** [comment]
Seems documentation has not been updated with details on this feature.
