### ISSUE TITLE
Failed to use ValueType.

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#3713]
Casting to ValueType allows to work with enums as integer types in generic extension methods.  
But Bridge does not allow to compile any such code. Simplified example is provided:  

### Steps To Reproduce

https://deck.net/5fbf72b2471c45ad967e5463acc4c475
https://dotnetfiddle.net/eMfulK

```csharp
public class Program
{
    public static void Main()
    {
        int test = 123;

        ValueType vt = (ValueType)test;
        
        Console.WriteLine(vt);
    }
}
```

### Expected Result

```
123
```

### Actual Result

```
C# to JavaScript Compilation Failed

Bridge.Contract.EmitterException: Type System.ValueType is marked as not usable from script
```

**Comment by fabriciomurta** [comment]
Thanks for reporting this missing feature, @hardhub!

**Comment by fabriciomurta** [comment]
`ValueType` has been implemented! It will make it to the next Bridge release (see milestone).
