### ISSUE TITLE
Missing implicit conversion in base constructor call

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#3714]
The base constructor has a decimal parameter. If you pass 0, the value does not get converted to a decimal, leading to problems. Passing 0m does work.

### Steps To Reproduce

https://deck.net/8e74410d4c10713072c51b7ad4139356

```csharp
public class App
{
    public static void Main()
    {
        var test = new SubClass();
        Console.WriteLine(test.Value + test.Value);
    }
    
    public class SubClass : BaseClass
    {
        public SubClass() : base(0)
        {
            
        }
    }
    
    public class BaseClass
    {
        public BaseClass(decimal value)
        {
            this.Value = value;
        }
        
        public decimal Value { get; set; }
    }
}
```

### Expected Result
No exception

### Actual Result
System.Exception: TypeError: test.Value.add is not a function

### See Also
https://forums.bridge.net/forum/bridge-net-pro/bugs/5878-open-3714-missing-implicit-conversion-in-base-constructor-call

**Comment by fabriciomurta** [comment]
Fixed! The implicit cast will work next Bridge release!
