### ISSUE TITLE
Latest Nuget Package Embedds Jquery into Output

### ISSUE THREAD

**Issue by groogiam** [bridgedotnet/Bridge#3722]
The latest version of either bridge or the bridge.jquery package seems to embedd a version of jquery into the output. Is there a way to prevent this? I have a specific version of jquery that kendo ui needs and this causes jquery to be double included breaking kendo ui.

**Comment by fabriciomurta** [comment]
Hello @groogiam! thanks for the report.

To do so would, according to [Global Configuration documentation](https://github.com/bridgedotnet/Bridge/wiki/global-configuration#resources) would be:

```javascript
  "resources": [
    {
      "name": "Bridge.jQuery2#jquery-2.2.4.js",
      "extract": false
    },
    {
      "name": "Bridge.jQuery2#jquery-2.2.4.min.js",
      "extract": false
    }
  ]
```

In your Bridge.json. Notice if you just rebuild the project you may still see the jquery files in the folder, you may need to manually remove it once it was generated. But once this setting is set, it should stop dumping those files.

Hope this helps!

**Comment by groogiam** [comment]
Thanks.
