### ISSUE TITLE
Script error on reflection: [namespace] is not defined

### ISSUE THREAD

**Issue by coddoge** [bridgedotnet/Bridge#3724]
I think this error cause by metadata handling woring.

### Steps To Reproduce

deck.net can not use retyped library, this time i installed package `Retyped.ace`

```csharp
public class Program
{
    private static Retyped.ace.AceAjax.Editor editor;

    public static void Main()
    {
        var members = typeof(App).GetMembers(); // Script error in myproject.meta.js: AceAjax is not defined
    }
}
```

But i got a workaround:

```csharp
public class App
{
    private static object editor; // define the member as object

    public static void Main()
    {
        var member = typeof(App).GetMembers(); // reflection is working fine

        var div = new dom.HTMLDivElement();
        dom.window.document.body.appendChild(div);
        editor = ace.ace2.edit(div); // boxing it
    }

    public void SomeMethod()
    {
        var input = ((ace.AceAjax.Editor)editor) // and unbox everywhere (so terrible)
            .getValue();
    }
}
```

**Comment by samuelGrahame** [comment]
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using static Retyped.dom;
using Retyped;
using static Retyped.ace.AceAjax;

namespace ClassLibrary1
{
    public class App
    {
        private static Editor editor; // define the member as object

        public static void Main()
        {
            var member = typeof(App).GetMembers(); // reflection is working fine

            var div = new HTMLDivElement();
            window.document.body.appendChild(div);            
            editor = ace.ace2.edit(div); // boxing it
        }

        public void SomeMethod()
        {
            var input = editor // and unbox everywhere (so terrible)
                .getValue();
        }
    }
}
```

**Comment by samuelGrahame** [comment]
Did you include the Ace editor js file?

**Comment by coddoge** [comment]
Yes, i download [lastest version](https://github.com/ajaxorg/ace-builds/tree/8f460a7c7204fb5695bf4c9906fc307f30e5430e) from its github and included in to html file.

I checked in chrome console and not found `AceAjax.Editor` or `ace.Editor` in global.
But still found `ace.Range` and more defined class in global.
The `Retyped.ace` version is `0.1.6733`, maybe lost sync from original classes define.

Sorry for wasted you time, seem i in a wrong way.
Its not failure of bridge.net , most possible cause by retyped class define library.

After figuring out the problem, get a beautiful workaround(patch) again.
Before retyped library sync to original classes define ,just add below path script into html after `ace.js`

```js
if (window.AceAjax === undefined) window.AceAjax = {};
if (window.AceAjax.Editor === undefined) window.AceAjax.Editor = function () { };
```

So, where are the github of `Retyped.ace`? I think i should post this issue to there :)

**Comment by fabriciomurta** [comment]
Hello, issues related to retyped packages may go to different places, depending on what's the cause.

If that's something that retyped didn't build well from the typescript definition files (e.g. the code is correct in the original typescript definition file, but goes wrong on retyped), it should go to [retyped/Retyped](https://github.com/retyped/Retyped).

But if the error is actually coming from the ts definition file, then the issue should be filled in the definitely typed repository. Most (if not all) NuGet packages from retyped come from the [DefinitelyTyped typescript definition database repository](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ace).

You may find more useful information if you check the [retyped/Retyped](https://github.com/retyped/Retyped) repository's readme.

**Comment by samuelGrahame** [comment]
@coddoge 

something else you might want to do is:
This will allow you to write raw javascript in the c# library
```csharp
/*@
if (window.AceAjax === undefined) window.AceAjax = {};
if (window.AceAjax.Editor === undefined) window.AceAjax.Editor = function () { };
*/
```

**Comment by coddoge** [comment]
@fabriciomurta
OK got it, thanks! I'll post this issue to `DefinitelyTyped` later.

**Comment by coddoge** [comment]
@samuelGrahame
Nice guidance! Beautiful coding!

But i got a little off topic question: How to delay execute main entry until document load fully?
I need a loading ui during download scripts and clear it after document fully loaded, then go Main.

I got a way but not enough beautiful:
Add `defer` attribute in all script tag.In `App` Main class:
Define a `LazyMain` to instead of the main entry,and the `Main` keep it empty code block for trigger.
In static ctor put the raw patch script and add a `load` event listener to window,to execute `LazyMain`.

This coding is a bit dirty, any better suggestion?

```C#
internal class App
{
    static App()
    {
        //A path of retyped.ace type define
        /*@
            if (window.AceAjax === undefined) window.AceAjax = {};
            if (window.AceAjax.Editor === undefined) window.AceAjax.Editor = function () { };
        */

        Window.AddEventListener(EventType.Load, () =>
        {
            Window.Document.Body.InnerHTML = ""; // clear loading ui
            LazyMain(); // real main entry
        });
    }

    private static void Main(string[] args)
    {
        //empty code block main is required for trigger static ctor.
    }

   //...
```

**Comment by samuelGrahame** [comment]
I would use Retyped.dom instead of bridge.HTML5 - (as bridge.HTML5) will be removed (I think)

Then use : [Bridge.Init(InitPosition.Top)] to init that function.

```csharp
using Bridge;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using static Retyped.dom;

namespace TestInit
{
    public class Program
    {
        [Bridge.Init(InitPosition.Top)]
        public static void Start()
        {
            //A path of retyped.ace type define
            /*@
                if (window.AceAjax === undefined) window.AceAjax = {};
                if (window.AceAjax.Editor === undefined) window.AceAjax.Editor = function () { };
            */
            window.addEventListener("load", (Event obj) =>
            {
                window.document.body.innerHTML = ""; // clear loading ui
                LazyMain(); // real main entry
            });
        }

        public static void LazyMain()
        {
            LazyMain();
        }
    }    
}
```

**Comment by samuelGrahame** [comment]
> The way innerHTML = "" to clear children elements is got from Stackoverflow too, its working fine and beautiful, any problem i should to be careful? -
It's okay to clear using that method, but the fastest way is using javascript as the example.

I like Bridge.Html5 - but as the developers stated, (Correct if I am wrong) they said it will be removed from bridge. as Retyped.dom is a 1 to 1 translation of the Type Definition's. (makes it a lot easier to support all the new changes) - nothing forcing you to stop uisng bridge.html5 as it works.

Regarding encodeURI and encodeURIComponent

```csharp
Bridge.Script.EncodeURI
EncodeURIComponent
```

**Comment by fabriciomurta** [comment]
Hello, while we are not just going to "delete Bridge.HTML5 for good", we say it is in an "Archived State".

At least while version 17 lasts, we are still maintaining it and publishing new releases every Bridge release. But from the point Bridge 18 is releases (currently no solid date for that to happen), we **may** no longer actively update the Bridge.HTML5 framework and re-publish the NuGet package every minor update at all.

But as a public project, anyone is welcome to fork the project and maintain it, and we'd be glad to review pull requests submitted to the repo fixing or implementing further functionality to it.

If nobody from the community steps in to maintain it, it may stop working at some point after next major version update.
