### ISSUE TITLE
Support SortedList<T> and LinkedList<T>

### ISSUE THREAD

**Issue by bktv** [bridgedotnet/Bridge#3725]
Feature request. 
We are in need of these classes from System.Collections and System.Collections.Generic
Thanks!

**Comment by otabekgb** [comment]
We need SortedSet<T> too, please

**Comment by fabriciomurta** [comment]
Hello @bktv, and thanks for the feature request! Sorry, we took so long to notice and bind it. We're reviewing untagged issues now.

**Comment by fabriciomurta** [comment]
The classes' implementation will make it to the upcoming Bridge release!
