### ISSUE TITLE
Output resource file names in alternative ways to the current index.html

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#3735]
When a Bridge project is built, it is output a sample index.html with the required resources. While it is useful, not always it is how projects would want to include the resources. So other custom ways should be implemented.

Details and discussions in this forum thread: [Output a top-level Javascript file instead of html](https://forums.bridge.net/forum/general/feature-requests/5908)

**Comment by geoffreymcgill** [comment]
The `report` config of **bridge.json** serves this purpose. 

https://github.com/bridgedotnet/Bridge/wiki/Global-Configuration#report
