### ISSUE TITLE
Ensure JavaScript Strict Mode for bridge.js

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#374]
Currently **bridge.js** does not validate in JavaScript `strict mode`. 

A related forum thread:
http://forums.bridge.net/forum/general/feature-requests/524

**Comment by fabriciomurta** [comment]
[Documentation on strict mode from w3schools](http://www.w3schools.com/js/js_strict.asp).

**Comment by LeonidVeriga** [comment]
Opening to add the strict instruction to each generated js file
