### ISSUE TITLE
Is there a way to create a self-contained module in bridge.net?

### ISSUE THREAD

**Issue by lidermanrony** [bridgedotnet/Bridge#3741]
Right now I have to include `bridge.js` in my html as a <script> tag in order for my bridge.net code to work (even if the code is in a module).

Is there a way to 'bundle' bridge.js into that module as well so i can have  a 'clean' way to import the module without polluting global namespace?

**Comment by SirUppyPancakes** [comment]
If you set the `combineScripts` option to `true` in `bridge.json`, it bundles all of the code into a single file for you:
https://github.com/bridgedotnet/Bridge/wiki/global-configuration#combinescripts

**Comment by fabriciomurta** [comment]
It's been a while since the question was asked and a response posted from the community, yet no feedback from @lidermanrony, so I'm assuming this one is handled and closing the issue. Let us know if otherwise.
