### ISSUE TITLE
Script.Apply (Bridge.apply), doesn't convert number to System.Decimal

### ISSUE THREAD

**Issue by dosh1974** [bridgedotnet/Bridge#3744]
Repro case: 
https://deck.net/bcd62e571aad68d75c585c1bfd3831b8

This is related to my question here:
https://forums.bridge.net/forum/community/help/5941-casting-js-object-to-net-object

**Comment by fabriciomurta** [comment]
We (and yourself) have responded with solutions to your question on the thread, so I am assuming this is no longer needed, right?
