### ISSUE TITLE
Wrong assembly name in arrays

### ISSUE THREAD

**Issue by colderlord** [bridgedotnet/Bridge#3746]
A description of the issue.

### Steps To Reproduce

https://deck.net/57bdad2d881bd818c8ffd1500d93a682

https://dotnetfiddle.net/l38B6t //Right assembly name

```csharp
public class Program
{
    public static void Main()
    {
        Console.WriteLine(typeof(Object).Assembly.FullName); // Sould be mscorelib
        Console.WriteLine(typeof(MyClass).Assembly.FullName); // Sould be Demo
        Console.WriteLine(typeof(MyClass[]).Assembly.FullName); // Sould be Demo
    }

    public class MyClass
    {
    }
}
```

### Expected Result
```
typeof(MyClass[]).Assembly.FullName == "Demo"
```

### Actual Result

```
typeof(MyClass[]).Assembly.FullName == "mscorelib"
```

**Comment by fabriciomurta** [comment]
Hello @colderlord! Thanks for reporting the issue! It is probably wrapping the System.Array off the brackets in that case.

**Comment by fabriciomurta** [comment]
Fixed! The fix will make it to the next Bridge Release!
