### ISSUE TITLE
Invalid JS generated in very specific case

### ISSUE THREAD

**Issue by d-p-y** [bridgedotnet/Bridge#3762]
When namespace and main class name are the same AND 'using Bridge' is present on the import list then invalid JS is generated - it contains '?' instead of proper types in method calls. What is interesting it happens only in 'fluent like' methods where type is not provided directly (it is inferred from passed System.Func<_>).

### Steps To Reproduce

https://dotnetfiddle.net/0e05XV

when 'using Bridge' it fails
https://deck.net/c4b6a1659644d4e448512e87ef75ffa1

when not 'using Bridge' it works:
https://deck.net/7ea8bf27d4121674a22bf2c9d1b224d4

```csharp
using Bridge;
using System;
using System.Collections.Generic;
using System.Linq;

namespace SomeName {
    public class A {
        public string P {get; set; }
        
        public A() {
            P = ""; //dotnetfiddle doesn't support property initializer
        }
        
        public override string ToString() 
        {
            return P;
        }
    }
    
    public class B {
        public static string Fail<T>(T v, Func<T,string> transform)  {
            return transform(v);
        }

        public static string Fail2<T>(Func<T,string> transform)  {
            return transform(default(T));
        }

        public static string Fine<T>(T v) {
            return v.ToString();
        }

        public static A Helper(A aaa) 
        {
            return aaa;
        }
    }

    public class SomeName {
        private static void AssertEquals(object exp, object fact) {
            if (!exp.Equals(fact)) {
                throw new Exception("AssertEquals failed");
            }
        } 
 
        [Ready]
        public static void Main() {
            AssertEquals("123456", B.Fail(new A {P = "123"}, x => x.P+"456")); //this fails in 17.4.0
            AssertEquals("678", B.Fail2((A x) => x+"678")); //this fails in 17.4.0
 
            AssertEquals("123456", B.Fail<A>(new A {P = "123"}, x => x.P+"456")); //workaround for 17.4.0
            AssertEquals("678", B.Fail2<A>((A x) => x+"678")); //workaround for 17.4.0

            AssertEquals("13", B.Fine(new A {P = "13"}));
             
            var lst = new List<A> {new A {P = "22"} };
            var lstFail = lst.Select(z => {
                    return B.Helper(z);
                }).ToList(); //this fails in 17.4.0

            AssertEquals(1, lstFail.Count);
            AssertEquals("22", lstFail[0].P);

            var lstWorkaround = lst.Select<A,A>(z => {
                return B.Helper(z);
            }).ToList(); //workaround for 17.4.0

            AssertEquals(1, lstWorkaround.Count);
            AssertEquals("22", lstFail[0].P);
            Console.WriteLine("done");
    }
    }
}
```

### Expected Result

printed 'done' on console
### Actual Result

generated javascript contains question marks instead of parameter types

**Comment by fabriciomurta** [comment]
As you probably could notice when you remove the 'use bridge' line, the namespace is turned into `Demo.SomeName` instead of `SomeName`. So if you craft the class path, you still get the same issue if the name matches (now to *Demo.SomeName*).

https://deck.net/fe7d918d9f279d3eac775cf0481b64f2

Still true if you remove all namespacing and just call the class `Demo`.

So the thing is that the issue is always there. Try completely removing the `//using Bridge;` line, or leaving it below, so that the code *starts* with an `using` line.

That's just because, if the first line does not start with `using`, Deck assumes it should resolve all using terms, wraps the code within `namespace Demo { }`, and adds the using lines atop.

So, the issue always happens when the namespace matches the class path. I'm just not sure this is a known issue/limitation, looked around and didn't find anything, but I feel this is a known limitation.

Anyway, thanks for the report; it is actual and we'll update here as soon as we get news with the feasibility to fix it (or maybe with the fix, if possible).

**Comment by d-p-y** [comment]
I definitely think it is a low priority bug as 'same namespace and same class' is a poor project naming decision. It would be nice if either bridgedotnet had some clear limitations wiki page (with link from main README.md) OR even better if it caused compiler error with issue number. Currently this bug manifests itself in a very peculiar way that caused lot of head scratching on my side :)

**Comment by fabriciomurta** [comment]
Thanks, for the suggestion, that's really something that would be useful.

Currently we rely on github issues; open issues and issues (open/closed) with the *question*, *wontfix* or *invalid* tags, basically. But grouping all in one place would be really helpful.

As I said on my previous thread, I searched for this here and didn't find it -- it was probably just yet not reported (so not yet known) limitation.

The "known limitation" came from an old issue we once had somebody who tried to build Bridge in a fresh project called *Bridge*. This of course meant a namespace conflict and the project couldn't be built. I am probably just recalling that issue, that should be an obvious limitation for any .NET project.

**Comment by stopiccot** [comment]
Started to get the same error after upgrading to 17.4.0 from 17.0.0

**Comment by fabriciomurta** [comment]
Looks like this issue was worth being fixed at once. The fix will make it to the next Bridge release!
