### ISSUE TITLE
ObjectLiteral classes emit values for all properties even for those which are without explicit values

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#377]
http://forums.bridge.net/forum/bridge-net-pro/bugs/495

First of all, it is a breaking change in 1.8.0. In my opinion, the previous behavior should be reverted back. Having a class/filled attribute to optionally emit default values would be good to have as well.

I will create a unit test for that issue later.

**Comment by vladsch** [comment]
Fixed in https://github.com/bridgedotnet/Builder/commit/2b7d49f33e3ad4b8eb8209cfa3136c98fa9b3aad
