### ISSUE TITLE
Compare method not scoped to comparer i.e. BinarySearch

### ISSUE THREAD

**Issue by Triogap** [bridgedotnet/Bridge#3775]
https://deck.net/81f0287ca221a10777930dba7d3db6df

### Expected Result
No exception

### Actual Result
UndefinedReference exception

**Comment by Triogap** [comment]
I'm unable to create a branche so unable to create a pull request (maybe my understanding of Git is not yet up to scratch)

But the issue can be fixed by adding .bind(obj) calls to the System.Collections.Generic.Comparer$1.get function in Resources/Collections/Comparer.js

    System.Collections.Generic.Comparer$1.get = function (obj, T) {
        var m;

        if (T && (m = obj["System$Collections$Generic$IComparer$1$" + Bridge.getTypeAlias(T) + "$compare"])) {
            return m.bind(obj);
        }

        if (m = obj["System$Collections$Generic$IComparer$1$compare"]) {
            return m.bind(obj);
        }

        return obj.compare.bind(obj);
    };

**Comment by fabriciomurta** [comment]
Hello! Thanks not only for reporting the issue but also suggesting a fix! That's very smart already, we'll take it in consideration for our next Bridge release.

Here's a repl.it fiddle showing [the same code works for Native .NET](https://repl.it/repls/SiennaTealPrintablecharacter).

**Comment by fabriciomurta** [comment]
Fixed! The fix for this will make it to the next Bridge release! The actual fix was very much like what you suggested, good job!
