### ISSUE TITLE
No way found to create javascript function object using new

### ISSUE THREAD

**Issue by chaudhariharshal2010** [bridgedotnet/Bridge#3776]
I searched for creating javascript function object using new but, no way found to do this.
I have function like this in my javascript file -
function DesktopLauncher(useLineShaft) {
    this.useLineShaft = useLineShaft;
    this.isWebSocketUsed = true;
}

I want to create object in C# as follows -
var obj = new DesktopLauncher(false);
obj.isWebSocketUsed = false;

Unbale to do the above way.

**Comment by fabriciomurta** [comment]
Hello, this should get you started:

https://deck.net/2f24ca683be1dbbd227725a113505bc1

Hope this helps!
