### ISSUE TITLE
[C#6] Support nameof()

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#378]
Not sure if this will already work in v2, but it'd be nice to support `nameof()`:

```
if (value == null)
    throw new ArgumentNullException(nameof(value));
```

Currently this compiles, but outputs weird invalid javascript like this:

```
[UnknownMethodResolveResult MyThing.Components.MyComponent+Props.nameof](value)
```

**Comment by geoffreymcgill** [comment]
Hi @DanTup,

Thanks for the report. We are investigating and should be able to easily add support for `nameof`.

**Comment by DanTup** [comment]
Great :)

There are some other C# 6 features I've been trying to use and failing (eg., expression-bodied methods). Is there value in me creating issues for them? I'm not sure if you get them "for free" using Roslyn, or still need to code specifically for them (even if the compile the same, I guess the syntax trees might be different?)

**Comment by vladsch** [comment]
`nameof` is C#6 feature. v1 will not support it because NRefactory doesn't support C#6
Bridge v2 already supports all C#6 features

**Comment by DanTup** [comment]
Great; thanks for confirming! :+1:

**Comment by geoffreymcgill** [comment]
The **nameof expressions** syntax support is planned for Bridge 1.15.

As well as all other C#6 syntax expressions will be supported in Bridge 1.15.

**Comment by DanTup** [comment]
@geoffreymcgill I'm curious how you're doing this - is this just a NRefactory upgrade, or will 1.15 use Roslyn?

**Comment by geoffreymcgill** [comment]
Roslyn. We will have more details available as the release gets closer.

**Comment by LeonidVeriga** [comment]
Related #1435
