### ISSUE TITLE
Premium support is deprecated?

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#3787]
I have received notice that premium accounts are not available anymore.  

Can you explain what exactly does it mean?

**Comment by geoffreymcgill** [comment]
Unfortunately, we just didn't get much interest in Bridge Premium from the community, so we decided to discontinue the offering. That said, our commitment to the existing Bridge Premium members has not changed and we will continue fully supporting, although it will not be possible to renew after expiration.

**Comment by hardhub** [comment]
But I am worried about project future.   
I have invested a lot of time to use it into production.  
Can you tell about your future plans regarding Bridge framework?  
Will we get any support? Will it still be free or/and open source? And so on...

**Comment by geoffreymcgill** [comment]
At this point, there are no plans to change the direction of Bridge, although the pace of new feature development has slowed significantly. Our primary focus has moved to supporting Bridge Premium members with technical support and bug fixes. Bridge 17.5.0 was just released this week.

[Bridge](https://github.com/bridgedotnet/Bridge) is an open-source project and freely available on Github, so nothing will ever change from that perspective.
