### ISSUE TITLE
Need sample code for MutationObserver

### ISSUE THREAD

**Issue by zydjohnHotmail** [bridgedotnet/Bridge#3792]
I have a HTML file, running from localhost: http://localhost/index.html
<!DOCTYPE html>
<html>
<head>
    <title>index1</title>
</head>
<body>
    <div class="counters">
        <div>
            <span class="single" id="single"></span>
        </div>
        <div>
            <span class="double" id="double"></span>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            crossorigin="anonymous"></script>
    <script type="text/javascript">
        $(document).ready(function count1() {
          var counter = 1;
          setInterval(function() { $(".single").text(counter++); }, 1000);
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function count2() {
          var counter = 200;
          setInterval(function() { $(".double").text(counter+=2); }, 2000);
        });
    </script>
</body>
</html>

Setup a HTML with two JavaScript functions.  The first one, count1() shows an increasing number from 1 with step of 1, but sleep one second each time.  The second JavaScript function called count2(), shows an increasing number from 200 with step of 2, but sleep two seconds each time.
The both functions generate dynamic text inside different <div> elements, but they are both children from their parent <div> node.
I can use JavaScript codes to catch the dynamic text generated by the JavaScript, the following codes work in DevTools of Chrome.
const numbers = document.querySelector('div.counters');
const config ={characterData: true, childList: true, subtree: true };
var observer = new MutationObserver(function(mutations){
  for (var i=0; i < mutations.length; i++)
  { console.log(mutations[i].innerText); } })
observer.observe(numbers, config);

I want to know if I can use C# project to do the same in Bridge.NET.
If so, please show me some C# sample code.  I think Bridge.NET should be able to do MutationObserver things like in JavaScript.
I am using Visual Studio 2017 Version 15.9.3, C# 7.3 on Windows 10.
Thanks,

**Comment by hardhub** [comment]
It works exactly as in JS. Simplified sample from real project:

```C#
            this.Observer = new MutationObserver(this.ChangedCallback);

            MutationObserverInit options = new MutationObserverInit();
            options.ChildList = true;
            options.Subtree = true;
            options.CharacterData = true;

            this.Observer.Observe(element, options);
```

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply, as I am new to Bridge.net, I don't quite understand how to run this.
Please give me a link for the underlying .NET project so I can get the big picture.
Thanks,

**Comment by fabriciomurta** [comment]
I don't think we already have a sample on exactly this on Bridge... We got some demos at:
- [bridgedotnet/Demos](https://github.com/bridgedotnet/Demos)
- [retyped/Demos](https://github.com/retyped/Demos)

Maybe some of them could be useful to help you figure out the rest of the `MutationObserver` concept you want to achieve.
