### ISSUE TITLE
To browse a web site and get dynamic text by launching a web browser using Bridge.net class

### ISSUE THREAD

**Issue by zydjohnHotmail** [bridgedotnet/Bridge#3793]
I have spent some time to learn Bridge.NET, I can see it is a good tools to run some JavaScript from C#.  However, I want to know if I can build a C# project (WinForm or WPF), which actively launch a web browser and visit some web site and inject some JavaScript to the web site and return the result from the JavaScript.

I have a simple HTML file, running from local web server:
http://localhost/index.html

`<!DOCTYPE html>
<html>
  <head>
    <title>index</title>
  </head>
<body>
   <div class="counters">
    <div>
      <span class="single" id="single"></span>
    </div>
    <div>
      <span class="double" id="double"></span>
    </div>
    </div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" crossorigin="anonymous"></script> 
<script type="text/javascript"> $(document).ready(function count1() 
{ var counter = 1; setInterval(function() { $(".single").text(counter++); }, 1000); }); 
</script> 
<script type="text/javascript"> $(document).ready(function count2() 
{ var counter = 200; setInterval(function() { $(".double").text(counter+=2); }, 2000); }); 
</script>
</body>
</html>
`

This setups a HTML file with two JavaScript functions. The first one, count1() shows an increasing number from 1 with step of 1, sleeps one second each time. 
The second one, count2(), shows an increasing number from 200 with step of 2, and sleeps two seconds each time.
The both functions generate dynamic text inside different elements, but they are both children from their parent node.

I can use JavaScript codes to catch the dynamic text generated by the JavaScript, the following codes work in DevTools of Chrome.
const numbers = document.querySelector('div.counters');
const config ={characterData: true, childList: true, subtree: true };
var observer = new MutationObserver(function(mutations){
for (var i=0; i < mutations.length; i++)
{ console.log(mutations[i].innerText); } })
observer.observe(numbers, config);

What I have seen in Bridge.NET documents is: write a class library with JavaScript/C# code, and open a browser to view a html file and see the output in the screen by hand.
What I want to do is: C# program launches a web browser (Chrome is better, as VS 2017 doesn't have other real web browsers) in C# project and visits http://localhost/index.html
And uses Bridge.NET to get the dynamic text from C#.
Please advice if it is possible.  To open a built-in html file by hand using open with web browser is not an option.  Since my final target is use this project to visit a real web site, and use Bridge.NET to detect the dynamic text generated by the JavaScript on that web site, which is totally out of my control.
If possible, please provide rather detailed steps, or refer to a working C# project (WinForm or WPF) which I can download from internet.
I am using VS 2017 Version 15.9.3 on Windows 10.
PS: some html formatting strings are missing, like "</body> and </html>" when posted here.
Thanks,

**Comment by geoffreymcgill** [comment]
What you want to do is not possible with Bridge.

**Comment by zydjohnHotmail** [comment]
OK.  Thanks,
