### ISSUE TITLE
Activator.CreateInstance doesn't work when you have a static constructor

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#3794]
https://deck.net/7bd4fb9a40a0c667b112afd67d2c7423

**Comment by fabriciomurta** [comment]
Dotnet fiddle sample: https://dotnetfiddle.net/hEk4rd
Corresponding deck: https://deck.net/853b312bbb6ccc9825698d5dec4865a3 (just changes the sample to run an assertion)

**Comment by fabriciomurta** [comment]
Fixed! This will be included in the next Bridge release.
