### ISSUE TITLE
Slow project compilation

### ISSUE THREAD

**Issue by colderlord** [bridgedotnet/Bridge#3805]
I have simple project with 1 class.
I wrote own `Translator` and ran it on compiled dll. The compile time is ~3sec. It's too long, because i build many projects in runtime.

**Comment by colderlord** [comment]
https://github.com/bridgedotnet/Bridge/pull/3806

**Comment by fabriciomurta** [comment]
Thanks for the neat improvement in Translator! We've just merged and the cache feature will make it to the next Bridge release!
