### ISSUE TITLE
typeof(HTMLElement).IsAssignableFrom(typeof(HTMLDivElement)) returns false

### ISSUE THREAD

**Issue by TriEdgeAI** [bridgedotnet/Bridge#3809]
https://deck.net/28630f9d8bc4101a1acb6f20ecef14f6

**Comment by TriEdgeAI** [comment]
Any comments here guys? `defect`?

**Comment by geoffreymcgill** [comment]
Hi. I'll mark as a defect and we will investigate further.

**Comment by fabriciomurta** [comment]
Fixed! The fix will be available next Bridge release (see attached milestone).
