### ISSUE TITLE
string.Join does not work as expected

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#381]
In my Bridge project in VS the `string` class appears to have no `Join` method. This code fails to compile:

```
var s = string.Join("", new[] { "a", "b" });
```

> 'string' does not contain a definition for 'Join'

Strangely, if I [try it on live.bridge.net](http://live.bridge.net/#029f86e0e7470ff1bf5b) the code compiles, but the results are not as expected. This code:

```
var s = string.Join("", new[] { "a", "b" });
Global.Alert(s);
```

produces this JS:

```
var s = Bridge.Linq.Enumerable.from(String).join("", ["a", "b"], null, null);
Bridge.global.alert(s);
```

which alerts `[object Object]` instead of `ab`.

**Comment by geoffreymcgill** [comment]
A defect or a feature? ;)

**Comment by geoffreymcgill** [comment]
Five overloads are required:

`(String)` - https://msdn.microsoft.com/en-us/library/dd783876(v=vs.110).aspx
`(String, IEnumerable<T>)` - https://msdn.microsoft.com/en-us/library/dd992421(v=vs.110).aspx
`(String, Object[])` - https://msdn.microsoft.com/en-us/library/dd988350(v=vs.110).aspx
`(String, String[])` - https://msdn.microsoft.com/en-us/library/57a79xd0(v=vs.110).aspx
`(String, String[], Int32, Int32)` - https://msdn.microsoft.com/en-us/library/tk0xe5h0(v=vs.110).aspx

**Comment by LeonidVeriga** [comment]
Hi @DanTup, we have reviewed string implementation and fixed this issue. Thanks for reporting!
