### ISSUE TITLE
is possible compile a function at RunTime

### ISSUE THREAD

**Issue by miladsadeghi72** [bridgedotnet/Bridge#3812]
hi 
i have project that must convert a delegate to a javascript code
for example: c sharp
```cs
js.Compile(()=>
{
    console.write(" this must convert to javascript ");
}
```
is that possible?

**Comment by geoffreymcgill** [comment]
Hi. Based on the sample you provided, your requirements are not clear. 

You can run arbitrary JavaScript code using `Script.Write`. Here's a basic sample:

https://deck.net/902963f9a42dee14b1af4738ed2127ce

```cs
public class Program
{
    public static void Main()
    {
        Script.Write("console.log(\"this must convert to javascript\")");
    }
}
```

**Comment by miladsadeghi72** [comment]
thanks but no
i need something to compile delegate at run time

**Comment by geoffreymcgill** [comment]
Original issue by @miladsadeghi72:

hi 
i have project that must convert a delegate to a javascript code
for example: c sharp
```cs
js.Compile(()=>
{
    console.write(" this must convert to javascript ");
}
```
is that possible?
