### ISSUE TITLE
Warning CS0114 when using custom indexer.

### ISSUE THREAD

**Issue by serge-shaldanov** [bridgedotnet/Bridge#3819]
Hello for everyone!

I was unable to find an issue like this, so sorry if it's a duplicate.

I have some class ```Strings```. It has overriden class indexer ```this[string key]``` that is used to get specific text by some key (like it's used in dictionaries).

When I trying to convert this class with Bridge.net I'm get the following warning from compiller:
```
warning CS0114: 'Strings.this[string]' hides inherited member 'object.this[string]'. To make the current method override that implementation, add the override keyword. Otherwise add the new keyword.
```

I'm undestand that such issue can be related with internal implementation of JS where each object can be indexed by some key.

My question is: how can I avoid such warning without using #pragma warning disable / #if #else directives?

### Steps To Reproduce

https://deck.net/17c92b50fb7720c3019801960ac450cc

```csharp
public class Strings
{
    public string this[string key]
    {
        get { return "dummy"; } 
    }
}

public static class Program
{
    public static void Main()
    {
        Strings strs = new Strings();
        Console.WriteLine(strs["key"]);
    }
}
```

### Expected Result

No warnings from compiller.

### Actual Result

```
warning CS0114: 'Strings.this[string]' hides inherited member 'object.this[string]'. To make the current method override that implementation, add the override keyword. Otherwise add the new keyword.
```

I'm use visual studio 2017 to build the broject.
Bridge.Net version 17.6.0.

**Comment by geoffreymcgill** [comment]
Hi @serge-shaldanov – You can suppress the compiler warnings with a configuration in your project settings. I believe the following docs should help:

https://docs.microsoft.com/en-us/visualstudio/ide/how-to-suppress-compiler-warnings?view=vs-2017

Another inline code option is demonstrated at the following location:

https://github.com/bridgedotnet/Bridge/blob/693a8e68269f806b1dea4695317d713e74337dc9/Tests/Batch3/BridgeIssues/3100/N3151.cs#L14-L16

```csharp
            private Action action;
#pragma warning disable CS0114 // Member hides inherited member; missing override keyword
            public Action this[string key]
#pragma warning restore CS0114 // Member hides inherited member; missing override keyword
            {
                get
                {
                    return action;
                }
                set
                {
                    action = value;
                }
            }
        }
```

Hope this helps.
