### ISSUE TITLE
Intermittent/failing tests in IE8

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#382]
When I load this page in IE10, I get completely different numbers of passing+failed assertions on each load. Seems like the whole test suite is not being run (I don't know if this is caused by the failures).

http://testing.bridge.net/

I suspect this is an issue with the test scripts/framework rather than bugs in Bridge but I thought it was worth raising for investigation.

At first I thought maybe the run hadn't finished; but it doesn't how the totals until it's done, and says "Tests completed" in both screenshots.

**Comment by DanTup** [comment]
![run1](https://cloud.githubusercontent.com/assets/1078012/9411992/472dbd28-4821-11e5-80fd-427c20e37a74.png)
![run2](https://cloud.githubusercontent.com/assets/1078012/9411993/47311e14-4821-11e5-8aa1-6d04fd7e056c.png)

**Comment by LeonidVeriga** [comment]
Hi Danny!
Thanks you for finding this out. Yes, it  looks at least strange and we are investigating this issue.
By the way, we are going to use automatic testing against multiple browsers and platforms.

**Comment by LeonidVeriga** [comment]
@DanTup We cannot reproduce the issue in IE10 10.0.9200.17414, update 10.0.29 (KB3065822) on Win7 x64. In IE it loads with some delay at apprx.200-700 tests and then loads the rest in 3-4 secs but always with a constant test numbers - 3508 assertions of 3511 passed, 3 failed. And yes, there are three failed tests in IE10 relates to string .indexOf() and .compare() methods (IE11 works fine).

Can you please confirm there is no errors in console.

**Comment by DanTup** [comment]
Ok, will test again tomorrow and check the console (and also get the exact version etc.).

**Comment by DanTup** [comment]
Ok, this was user error!

I mistyped the hostname of the IE10 test machine I was using, but because of the wildcard DNS I ended up connecting to a different server to the one I expected. I was running in IE8!

So, if you're not supporting IE8, then there's no issue. If you are, then this issue exists in IE8, not IE10!

Sorry for the confusion!

**Comment by DaniilVeriga** [comment]
I can reproduce this in IE8.
```
Tests completed in 49621 milliseconds.
2431 assertions of 2791 passed, 360 failed.
```
As for:
> I get completely different numbers of passing+failed assertions on each load

Please clarify are you waiting for awhile before IE8 is done? I see it shows some results at first (same to me as it is on your first screenshot). But IE8 is not finished its job yet. It just hangs up for awhile. As I posted above the first run took 49 seconds. The second run took 20 seconds on my side. So, the amount of tests is just too heavy for IE8. Btw, sometimes such temporary results (before all the tests are done) might be visible in other browsers as well. So, I am pretty sure the result is always the same if wait till it is done. 

As for IE8 support. At least, the testing results says something about the level of that support. We actually try to support it as much as we can, but it is a very complicated - balancing on the edge of modern technologies and trying to support legacy IE.

**Comment by DanTup** [comment]
We're not bothered about IE8 support, I was just pointing out my error, so don't consider it a vote for IE8 support from us! :-)

If you're interested, here's the results from a few page loads. Whenever the results were not 2431/360, I left the page several minutes to see if it updated, but it did not appear to. No errors in console. It does seem intermittent here, but who knows the origins of this server I accidentally connected to to run these! :)

(numbers are passed/failed/time)
1. 137/20/125ms
2. 137/20/172ms
3. didn't seem to finish (see screenshot; left this for several minutes, didn't seem to update/finish)
4. 2431/360/13078ms
5. 137/20/125ms
6. 2431/360/13078ms
7. 137/20/125ms

IE version is 8.0.6001.18702

![ie8_failed](https://cloud.githubusercontent.com/assets/1078012/9488088/3efdcd9e-4bcf-11e5-9843-071488aab961.png)

If you're not all that interested in IE8 support, feel free to close this. I only raised it because I thought it was IE10!

**Comment by geoffreymcgill** [comment]
If anyone requires IE8 support, your feedback regarding #1050 is appreciated.

IE8 support might be dropped in the next release, milestone 1.12.

**Comment by DanTup** [comment]
We're on the verge of dropping IE8/9/10 support from our live products and we're still some way off deploying Bridge code to production; so it really wouldn't affect/bother us :)

**Comment by LeonidVeriga** [comment]
IE8 support ... dropped #1115
