### ISSUE TITLE
Bug at using Ref Returns

### ISSUE THREAD

**Issue by miladsadeghi72** [bridgedotnet/Bridge#3820]
hi
this is fine at c# but handle an exception in bridge.net

```csharp
public delegate ref result GetRef<result>();
```

[The Code at Deck](https://deck.net/42c1f4fefe02d13e0f56b76c3175e990)

```csharp
public delegate ref result GetRef<result>();
        public static c1 a = new c1();

        public class c1
        {
            public string[] a = new string[] { "a", "b" };
        }

        public static void Main()
        {
            try
            {
                GetRef<c1> refa = () => ref a;
                refa().a[0]="c";
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
```

**Comment by miladsadeghi72** [comment]
@vladsch What Can i do?

**Comment by miladsadeghi72** [comment]
am i ignored?

**Comment by geoffreymcgill** [comment]
Hi @miladsadeghi72 – Thanks for letting us know about this issue. I have tagged as a defect. We will investigate and try to fix as soon as possible.

**Comment by miladsadeghi72** [comment]
Thank you for attention, now i working on ORM database which can use in normal c# and bridge
that is completed, but have just one bug, this is the bug i talking about.
so when this bug fixed, i share the database with you
thanks a lot for humility.

**Comment by geoffreymcgill** [comment]
I get the same NullReferenceException when I run your code in native .NET. 

https://repl.it/repls/NoxiousGenerousPetabyte

Are you sure your code should work in .NET?

**Comment by miladsadeghi72** [comment]
i test this code in console application
work fine, see the logic
why you don't test it in real project? are you try?

**Comment by miladsadeghi72** [comment]
this maybe come from compiler, i use msbuild, the code work fine in that
may mono compiler have bug, i will test this code in android emulator and tell you result

**Comment by geoffreymcgill** [comment]
Confirmed. Your code sample does work in a new .NET Core test project. 

This issue is marked as a defect and we will try to fix.

**Comment by miladsadeghi72** [comment]
aaahhh just thanks

**Comment by fabriciomurta** [comment]
Fixed! The fix is going to make it to the next Bridge release (see attached milestone for version number).

**Comment by geoffreymcgill** [comment]
Original issue by @miladsadeghi72:

hi
this is fine at c# but handle an exception in bridge.net

```csharp
public delegate ref result GetRef<result>();
```


[The Code at Deck](https://deck.net/42c1f4fefe02d13e0f56b76c3175e990)

```csharp
public delegate ref result GetRef<result>();
        public static c1 a = new c1();

        public class c1
        {
            public string[] a = new string[] { "a", "b" };
        }

        public static void Main()
        {
            try
            {
                GetRef<c1> refa = () => ref a;
                refa().a[0]="c";
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
```
