### ISSUE TITLE
task suspend at websocket

### ISSUE THREAD

**Issue by miladsadeghi72** [bridgedotnet/Bridge#3821]
hi bridge.net team
I use websocket and try to connect to any server
why when server is not exist or refuse connection I don't get any exception?
is this a bug or just your logic?
 [stackoverflow.com tell : The WebSocket's connection-time error causes a dispatched event, not a thrown value. This is because throw operations must be synchronous ](https://stackoverflow.com/questions/31002592/javascript-doesnt-catch-error-in-websocket-instantiation/31003057)
but I use await

[Test In Deck](https://deck.net/3e18bace545c8e38f8a56b8ef95c2978)

```csharp
public class Program
{
    
        public async static void Main()
        {
            try
            {
                var sc = new System.Net.WebSockets.ClientWebSocket();
                Console.WriteLine("connecting...");
                await sc.ConnectAsync(new Uri("wss://NotExistServer/NotExist"), System.Threading.CancellationToken.None);
                Console.WriteLine("connected");
            }
            catch(Exception ex)
            {
                Console.WriteLine("Error >>>");
                Console.WriteLine(ex);
            }
        }
}
```

### Expected Result in console
connecting...
Error >>>

### Actual Result in console
connecting...

**Comment by miladsadeghi72** [comment]
in fact I expect like this:

[Fine Example in Dect](https://deck.net/f48b83d98c2b73d928e7b602984f1863)

```csharp
public class Program
{
    
        public static void Main()
        {
            Console.WriteLine("connecting...");
            var sc = new WebSocket("wss://NotExistServer/NotExist");
            sc.OnError += (e) =>
              {
                  Console.WriteLine("Error >>>");
              };

            sc.OnOpen += (e) =>
              {
                  Console.WriteLine("connected...");
              };
                
            
        }
}
```

**Comment by geoffreymcgill** [comment]
I'm not sure why this is happening and it will require some investigation. Please feel free to submit a pull request if you can determine the cause of the defect within Bridge and wish to fix.

**Comment by miladsadeghi72** [comment]
this is because websocket just count on OnOpen event not OnError event
i designed new socket in our web service, i will review the websocket on bridge and pull a solution if i can do
tnx for response

**Comment by fabriciomurta** [comment]
Implemented! The implementation will be available next Bridge release (according to attached milestone).

**Comment by miladsadeghi72** [comment]
Nice work
Tnx

**Comment by geoffreymcgill** [comment]
Original issue by @miladsadeghi72:

hi bridge.net team
I use websocket and try to connect to any server
why when server is not exist or refuse connection I don't get any exception?
is this a bug or just your logic?
 [stackoverflow.com tell : The WebSocket's connection-time error causes a dispatched event, not a thrown value. This is because throw operations must be synchronous ](https://stackoverflow.com/questions/31002592/javascript-doesnt-catch-error-in-websocket-instantiation/31003057)
but I use await

[Test In Deck](https://deck.net/3e18bace545c8e38f8a56b8ef95c2978)

```csharp
public class Program
{
    
        public async static void Main()
        {
            try
            {
                var sc = new System.Net.WebSockets.ClientWebSocket();
                Console.WriteLine("connecting...");
                await sc.ConnectAsync(new Uri("wss://NotExistServer/NotExist"), System.Threading.CancellationToken.None);
                Console.WriteLine("connected");
            }
            catch(Exception ex)
            {
                Console.WriteLine("Error >>>");
                Console.WriteLine(ex);
            }
        }
}
```

### Expected Result in console
connecting...
Error >>>

### Actual Result in console
connecting...
