### ISSUE TITLE
Checking if an object is decimal always results as true

### ISSUE THREAD

**Issue by BojidarStanchev** [bridgedotnet/Bridge#3823]
https://deck.net/3b219c3202f275e7bbd6cf19272ce72d

**Comment by TriEdgeAI** [comment]
Can we tag this one as `premium`?

**Comment by geoffreymcgill** [comment]
Thanks for the report and excellent sample demonstrating how to reproduce the issue. We will investigate and try to fix as soon as possible.

**Comment by fabriciomurta** [comment]
The fix has just been merged upstream, and will be available next Bridge release (see attached milestone).
