### ISSUE TITLE
Wrong array Len!

### ISSUE THREAD

**Issue by miladsadeghi72** [bridgedotnet/Bridge#3826]
hi bridge.net team
we found a Bug at bridge.js file
we hard worked and have Very Very BAD days to find this, so please ,  just please attention 

the Array.getlen function return wrong length 

this the buggy code
```javascript
getLength: function (arr, dimension) {
            if (dimension < 0 || dimension >= (arr.$s ? arr.$s.length : 1)) {
                throw new System.IndexOutOfRangeException();
            }

            **return arr.$s ? arr.$s[dimension] : arr.length;**
        }
```

i fact we expected this:
 ```javascript
getLength: function (arr, dimension) {
            if (dimension < 0 || dimension >= (arr.$s ? arr.$s.length : 1)) {
                throw new System.IndexOutOfRangeException();
            }

            **return arr.$s ? arr.$s[dimension]+1 : arr.length;**
        }
```
attention

 ```javascript
            ** arr.$s[dimension]+1**
```

sorry if my describe is not enough good, but we fix this and now work fine in our projects,
Milad sadeghi & hole monsajem team
thanks a lot

**Comment by geoffreymcgill** [comment]
Original issue by @miladsadeghi72:

hi bridge.net team
we found a Bug at bridge.js file
we hard worked and have Very Very BAD days to find this, so please ,  just please attention 

the Array.getlen function return wrong length 

this the buggy code
```javascript
getLength: function (arr, dimension) {
            if (dimension < 0 || dimension >= (arr.$s ? arr.$s.length : 1)) {
                throw new System.IndexOutOfRangeException();
            }

            **return arr.$s ? arr.$s[dimension] : arr.length;**
        }
```

i fact we expected this:
 ```javascript
getLength: function (arr, dimension) {
            if (dimension < 0 || dimension >= (arr.$s ? arr.$s.length : 1)) {
                throw new System.IndexOutOfRangeException();
            }

            **return arr.$s ? arr.$s[dimension]+1 : arr.length;**
        }
```
attention

 ```javascript
            ** arr.$s[dimension]+1**
```

sorry if my describe is not enough good, but we fix this and now work fine in our projects,
Milad sadeghi & hole monsajem team
thanks a lot
