### ISSUE TITLE
Array.CreateInstance is not safe (BUG)

### ISSUE THREAD

**Issue by miladsadeghi72** [bridgedotnet/Bridge#3830]
hi bridge.net team
i finally found the bug i told 
i fix that for my products but i think this is my duty to tell you
that come from Array.CreateInstance
when i resize an array then **array.Length** and **array.UpperBound(0)** is very confusing different 

[watch this sample at Dect ](https://deck.net/113659669177d9a860c59f0cf29077b0)

```csharp
public class Program
{
    public static void Main()
    {
           string[] Strings;

            Strings =(string[])Array.CreateInstance(typeof(string),new int[] { 0 });

            Array.Resize(ref Strings, Strings.Length + 1);
            Console.WriteLine("Array Len: "+ Strings.Length.ToString());
            Console.WriteLine("Array UpperBound(0) : "+Strings.GetUpperBound(0).ToString());
    }
}
```

### Expected Result At Console

Array Len: 1
Array UpperBound(0) : 0

### Actual Result At Console

Array Len: 1
Array UpperBound(0) : -1

**Comment by fabriciomurta** [comment]
Fixed! The fix will be available next Bridge release (see issue milestone). Thanks for reporting this!

**Comment by geoffreymcgill** [comment]
Original issue by @miladsadeghi72:

hi bridge.net team
i finally found the bug i told 
i fix that for my products but i think this is my duty to tell you
that come from Array.CreateInstance
when i resize an array then **array.Length** and **array.UpperBound(0)** is very confusing different 

[watch this sample at Dect ](https://deck.net/113659669177d9a860c59f0cf29077b0)

```csharp
public class Program
{
    public static void Main()
    {
           string[] Strings;

            Strings =(string[])Array.CreateInstance(typeof(string),new int[] { 0 });

            Array.Resize(ref Strings, Strings.Length + 1);
            Console.WriteLine("Array Len: "+ Strings.Length.ToString());
            Console.WriteLine("Array UpperBound(0) : "+Strings.GetUpperBound(0).ToString());
    }
}
```

### Expected Result At Console

Array Len: 1
Array UpperBound(0) : 0

### Actual Result At Console

Array Len: 1
Array UpperBound(0) : -1
