### ISSUE TITLE
Issue with async inline delegates ($taskResult1 is not defined)

### ISSUE THREAD

**Issue by ChrML** [bridgedotnet/Bridge#3836]
This is a rather edge scenario and easy to work around. But since C# does support inline delegates with the "async" modifier, and the error only occurs at runtime I'm reporting this anyway.

The issue is seems to occur when async methods are written as inline delegates, such as an asynchronous eventhandler in the example below.

The example works completely fine if the code uses a seperate method as the async eventhandler instead of an inline async delegate.

***** EDIT 19.02.2019:
Made a much simpler reproduce example:
https://deck.net/fd2e144db19a63f09ac6f8d43875d2a5

According to @miladsadeghi72 's Deck the issue seems to be related to async delegates with { and } omitted.

See the modified Deck where the issue don't occur:
https://deck.net/1250e80cfc07528fdb2e63c33ee834e0

### Steps To Reproduce

https://deck.net/0099d558e1e56ef9e7a8b9fd3120d1e9

```csharp
// Bug report by Christian "ChrML" Lundheim - 18.02.2019
// Bridge.NET 17.6.0

public class Program
{
    public async static void Main()
    {
        // Prepare the test: Make a new button class.
        ButtonAsync button = new ButtonAsync();
        
        // Example 1 - Works fine:
        // Add, execute and remove seperate async method as eventhandler.
        Console.WriteLine("BEGIN: Executing eventhandler as seperate async method");
        button.ClickAsync += EventHandler;
        await button.OnClickAsync();
        button.ClickAsync -= EventHandler;
        Console.WriteLine("FINISH: Executing eventhandler as seperate method");
        
        // Example 2 - Does not work:
        // Add and execute inline async delegate as eventhandler.
        Console.WriteLine("BEGIN: Executing eventhandler as inline async delegate");
        button.ClickAsync += async () => await Test();
        await button.OnClickAsync();  // EXCEPTION: $taskResult1 is not defined.
        Console.WriteLine("END: Executing eventhandler as inline async delegate (this never happens)");
    }
    
    
    static async Task EventHandler()
    {
    }
    
    
    static async Task Test()
    {
    }
}



public class ButtonAsync
{
    public event ButtonClickAsyncEventHandler ClickAsync;
    
    public Task OnClickAsync() => ClickAsync?.Invoke();
    
};

public delegate Task ButtonClickAsyncEventHandler();
```

### Expected Result

```js
$tcs.setResult(null);
```
I'm not 100% sure, async code in JS is somewhat complex. But $taskResult1 is undefined and returns void, so should probably be null like the code inside "EventHandler" method.

### Actual Result

```js
$tcs.setResult($taskResult1);
```

**Comment by miladsadeghi72** [comment]
In fact you forgot somthing
please use async keyword in OnClickAsync method

**Comment by fabriciomurta** [comment]
Hello, @ChrML and thanks for reporting the issue!

I can't really seem to be able to run your code in a native C# console application, maybe I am missing something, like a project setting or C# API version? Interesting Deck does not issue the same message, this may be passing roslyn somehow, whereas failing in Visual Studio.

Getting this:
```
The 'await' operator can only be used within an async method. Consider marking this method with the 'async' modifier and changing its return type to 'Task'.
```

On lines 15 and 23 of the deck you provided (`await button.OnClickAsync();`).

**Comment by miladsadeghi72** [comment]
https://deck.net/0219a2a4542c74c3c2be6a1221d52c80

**Comment by ChrML** [comment]
@miladsadeghi72 You made the method async, but you forgot to await the event Invoke. So effectively the exception likely still occurred, but got tossed away because the task is not awaited. Still by looking at the JS code a not init var is still being used.

The original code without OnClickAsync is infact working by just returning the task as it is without passing it through an async method. Its not required to use the async/await pattern the whole way if you just return the task. Although on a general basis I see this scenario is probably not a good idea because with no eventhandlers you'll end up awaiting "null", tho this is not affecting this test.

**Comment by ChrML** [comment]
@fabriciomurta I will look at my settings at work tommorrow and attempt to compile it natively.

**Comment by ChrML** [comment]
@fabriciomurta Likely your main method is not async or you have an older version of C#. I believe async Main() method was only added recently, but you can make another method for testing.

Here's some information about async delegates:
https://blog.stephencleary.com/2014/02/synchronous-and-asynchronous-delegate.html

I will come back to you tomorrow when I've confirmed (I don't have the software in front of me right now).

**Comment by miladsadeghi72** [comment]
@ChrML  yes you are right, but it's have other type of bugs
https://deck.net/e475a8713934bc89995d5e13ea29d95a
diffrent is:
```csharp
// bugy code
        button.ClickAsync += async () =>await Test();
```
And
```csharp
 // fine
button.ClickAsync += async () =>
        { 
            await Test();
        };
```
@fabriciomurta this can help

**Comment by fabriciomurta** [comment]
> Likely your main method is not async or you have an older version of C#.

@ChrML, It is C# 7.2 or newer, and .NET Framework 4.7.1.
In the console app project properties I see C# 7.3 available, and the project is set up to the latest minor version:
![image](https://user-images.githubusercontent.com/10730372/52981893-4f152000-33c1-11e9-8250-936d2c54db7b.png)

**Comment by ChrML** [comment]
@miladsadeghi72 These examples are identical and both are allowed in C#. First is just an abbreviation recommended for one-liners, while the second is more verbose but allows for more than one line of code in the delegate.

**Comment by ChrML** [comment]
@fabriciomurta For the example above to compile under Native .NET Framework you need to:
- Set .NET Framework version to 4.7.2 or later
- Set C# version explicitly to C# 7.3 (apparently the "latest" as considered by Visual Studio is 7.2)
- Change the Main() method return value from "void" to "Task"

When this is done, the example in the Deck works correct under native .NET.

**Comment by ChrML** [comment]
I made a new deck with a much simpler example that reproduces this same error.
This example also works out of the box in native .NET:
https://deck.net/fd2e144db19a63f09ac6f8d43875d2a5

**Comment by miladsadeghi72** [comment]
https://deck.net/1250e80cfc07528fdb2e63c33ee834e0
https://deck.net/e475a8713934bc89995d5e13ea29d95a

**Comment by ChrML** [comment]
> https://deck.net/1250e80cfc07528fdb2e63c33ee834e0
> https://deck.net/e475a8713934bc89995d5e13ea29d95a
@miladsadeghi72 Good point, I think you found the root of the issue. Seems the Bridge.NET compiler actually compiles it quite different depending on if you scope the delegate using { and }, or if you don't. Altough both ways to do it are equally valid in C# and should be compiled identical.

**Comment by miladsadeghi72** [comment]
its also is a way to fix this issue
@fabriciomurta why dont defect this?
what is wrong?
we try to help

**Comment by miladsadeghi72** [comment]
its also is a way to fix this issue
@fabriciomurta why dont defect this?
what is wrong?
we try to help

**Comment by ChrML** [comment]
> its also is a way to fix this issue
> @fabriciomurta why dont defect this?
> what is wrong?
> we try to help

I'm sure he just wants to iron out what the problem is and confirm that it works on native .NET first before defecting this. Remember this is not exactly a huge problem, but quite easy to work around.

In my experience the Bridge.NET team has been very good at fixing these small things as they get reported. And on Github we can also make pull requests to fix these issues ourselves. =) 👍 💯

**Comment by fabriciomurta** [comment]
Hello again, and thanks for keeping up with us! We've fixed this issue a few days ago, and now just integrated it on the branch that will result in the next Bridge version! That said, the fix will be available next Bridge release; the version number is reflected in this issue's milestone.
