### ISSUE TITLE
VSIX Installation Failed.....

### ISSUE THREAD

**Issue by natiki** [bridgedotnet/Bridge#3838]
Hi,

Followed instructions on https://github.com/bridgedotnet/Bridge/wiki to download the VSIX which goes to http://bridge.net/go/vsix and then ultimately https://marketplace.visualstudio.com/items?itemName=BridgeNET.BridgeNET to download.

Running the installer fails (see log below). My machine is Windows 10 18.09 with VS Pro 15.9.6

```txt
19/02/2019 12:47:58 - Microsoft VSIX Installer
19/02/2019 12:47:58 - -------------------------------------------
19/02/2019 12:47:58 - Initializing Install...
19/02/2019 12:47:58 - Extension Details...
19/02/2019 12:47:58 - 	Identifier      : Bridge.NET
19/02/2019 12:47:58 - 	Name            : Bridge.NET
19/02/2019 12:47:58 - 	Author          : Object.NET
19/02/2019 12:47:58 - 	Version         : 17.6.0
19/02/2019 12:47:58 - 	Description     : Bridge.NET for Visual Studio. An open source C#-to-JavaScript compiler platform. Generate JavaScript from your C# code. Professionally supported by a dedicated team. Try online at Deck.NET.
19/02/2019 12:47:58 - 	Locale          : en-US
19/02/2019 12:47:58 - 	MoreInfoURL     : https://github.com/bridgedotnet/Bridge/wiki
19/02/2019 12:47:58 - 	InstalledByMSI  : False
19/02/2019 12:47:58 - 	SupportedFrameworkVersionRange : [4.5,)
19/02/2019 12:47:58 - 
19/02/2019 12:47:58 - 	Supported Products : 
19/02/2019 12:47:58 - 		Microsoft.VisualStudio.Pro
19/02/2019 12:47:58 - 			Version : [11.0,16.0)
19/02/2019 12:47:58 - 		Microsoft.VisualStudio.Enterprise
19/02/2019 12:47:58 - 			Version : [15.0,16.0)
19/02/2019 12:47:58 - 
19/02/2019 12:47:58 - 	References      : 
19/02/2019 12:47:58 - 		-------------------------------------------------------
19/02/2019 12:47:58 - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
19/02/2019 12:47:58 - 		Name         : Visual Studio MPF 11.0
19/02/2019 12:47:58 - 		Version      : [11.0]
19/02/2019 12:47:58 - 		MoreInfoURL  : 
19/02/2019 12:47:58 - 		Nested       : No
19/02/2019 12:47:58 - 
19/02/2019 12:47:58 - 
19/02/2019 12:47:58 - Searching for applicable products...
19/02/2019 12:48:00 - Found installed product - Global Location
19/02/2019 12:48:00 - Found installed product - ssms
19/02/2019 12:48:00 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by fabriciomurta** [comment]
Hello @natiki, this possibly has to do with the version of visual studio, we basically test this with VS2017. We need to look into making that compatible with other VS versions according to https://bridge.net/download/.

**Comment by fabriciomurta** [comment]
Errata: i mistook the version 15.9.6 with VS2015. You're on VS2017. I see the installer works for enterprise 2017 but I'm not sure why it doesn't for your VS version. As you can see in the list of supported products, we do have from 11.0 inclusive, to 16.0 exclusive (like, until 15.99999).

This -might- have been due to an issue, I noticed 15.9.7 is out while I still have the announce of 15.9.6 showing on my VS. I am currently in 15.9.5, so will upgrade to latest and see what happens.

**Comment by natiki** [comment]
@fabriciomurta I'll upgrade to 15.9.7 to see if it works for me.... Then at least we can:

> This -might- have been due to an issue, I noticed 15.9.7 is out while I still have the notification of 15.9.6 showing on my VS. I am currently in 15.9.5, so will upgrade to latest and see what happens.

determine that while an update is pending that the VSIX is not happy. Will let you know.

**Comment by natiki** [comment]
@fabriciomurta Upgraded VS from 15.9.6 to 15.9.7 and the VSIX worked like a charm. I believe this is also a VSIX issue and not related to Bridge specifically....

While the update was **pending** to 15.9.7 I ran a different VSIX installer and it failed as well. After the upgrade to 15.9.7 and it installed flawlessly.

So while the work around is to upgrade to the latest VS, a solution when a pending upgrade is available would still be required.

**Comment by fabriciomurta** [comment]
I don't think this will be reproducible when a pending upgrade is required. Before upgrading from 15.9.7 from 15.9.5, I've installed the VSIX without issues. I can only conclude the issue was with the quick-phased 15.9.6.

I will mark this issue as invalid for now, but if you happen to be able to reproduce this in other versions (for instance, when 15.9.8 becomes available), let us know. I'll keep an eye open for this too.

**Comment by fabriciomurta** [comment]
This adds a little more:
https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes

> Corrected incorrect version of VCToolsRedistVersion in Microsoft.VCToolsVersion.default.props.

I'm pretty sure that's what was preventing the VSIX installs from going.
