### ISSUE TITLE
caught TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by natiki** [bridgedotnet/Bridge#3839]
- Following on from #3838 I installed manually in VS PRO 15.9.6  as

- Create new solution
- Add Class Library .NET 4.61
- Run Install-Package Bridge
- Run Install-Package Bridge.Html5
- Left everything as was and changed the code to the following:

```c#
using System;
using Bridge;
using Bridge.Html5;

namespace TripSeekerSearch.Engine
{
    public class Class1
    {
        public static void Dono()
        {
           Console.WriteLine("Dono");
        }


        public static void Main()
        {
            Console.WriteLine("Hello, world!");
        }
    }
}
```

Loaded the generated index.html and then get the following:

![image](https://user-images.githubusercontent.com/4738140/52987389-01df8f80-344f-11e9-89ca-410e1b545185.png)

So clearly I am missing a reference or something, but for the life of me I cannot see what. Any pointers?

**Comment by vladsch** [comment]
I see `Dono` output in your console but in your sample `Dono` method is not invoked at all. So, there is something more in your code.

**Comment by natiki** [comment]
Going to close this one, as after a machine restart and a VS restart this appears to have sorted itself out. Suspect a caching issue somewhere.
