### ISSUE TITLE
Small issue when creating a new project....

### ISSUE THREAD

**Issue by natiki** [bridgedotnet/Bridge#3844]
- VS 15.7.9
- Bridge 17.6

Now that the VSIX installs 3838 I went to create a new project....

### Steps To Reproduce

- Run up VS
- File > New > Project
- Select Bridge
- Click OK

Project creates OK but following error in package manager console.

![image](https://user-images.githubusercontent.com/4738140/53064141-d7f39f00-351a-11e9-8116-e7d6da99e436.png)

**Comment by fabriciomurta** [comment]
This error message unfortunately couldn't be avoided, but it does not really break anything, does it? Although it fails removing the reference, once Bridge is mingled in, its .targets file ensures VS won't load its base mscorlib in favor of Bridge's implementation of the core libraries.

I have run over the steps, built the bare project and opened it without issues.

I will mark this as question and go ahead and close it. Let us know if you don't agree with that and that this is leading to an actual error building or running Bridge apps. As far as I could reproduce it here, this error message can be treated as a warning and be ignored. As we can't go further with customization of NuGet packages installation, (ps1 scripts are unreliable and not cross-platform) there's little we can do to address this (unless of course someone in the community can find a solution for this and provide via a pull request -- which would be very welcome!

Anyways, we appreciate all your feedback about Bridge!
