### ISSUE TITLE
Is support for Visual Studio 2019 planned?

### ISSUE THREAD

**Issue by natiki** [bridgedotnet/Bridge#3845]
Hi,

Just doing some due diligence as we start to use Bridge.NET in VS 2017. I know we will be upgrading to VS 2019 soon after it releases.

**Comment by fabriciomurta** [comment]
Not sure it will even break in VS2019 once it is released, unless it has some severe breaking changes. We can only wait and see once it is released.

**Comment by fabriciomurta** [comment]
In other words, I don't really see any reason why not support VS2019. As this is just a question, I'm going forward and close it. Let us know if you need more information or any reason you believe this shouldn't be closed.

**Comment by natiki** [comment]
Has Bridge.NET been tested in Visual Studio 2019 by the dev team as of yet?
