### ISSUE TITLE
Problem with getting at some JSON data....

### ISSUE THREAD

**Issue by natiki** [bridgedotnet/Bridge#3846]
Hi,

- VS2017 15.9.7
- Bridge 17.6.0

I am trying to access some JSON from a javascript file that is included in my page. So following on from https://github.com/bridgedotnet/Bridge/wiki/calling-custom-javascript and https://deck.net/newtonsoft.json I have the following:

A simple data.js included in my page that contains the following:

```js
function GetData()
{
return '{                                     ' +
'  "ExpiryDate": "2008-12-28T00:00:00",' +
'  "Name": "Apple",                    ' +
'  "Price": 3.99,                      ' +
'  "Sizes": [                          ' +
'    "Small",                          ' +
'    "Medium",                         ' +
'    "Large"                           ' +
'  ]                                   ' +
'}                                     ';
}
```
This is accessible via console no problems:

![image](https://user-images.githubusercontent.com/4738140/53068526-e945a700-352c-11e9-877d-8d98184cabb2.png)

Next:

![image](https://user-images.githubusercontent.com/4738140/53068703-81dc2700-352d-11e9-90c2-3f6b7575a302.png)

- Yellow: Installed Bridge.Newtonsoft.Json
- Green: Wrote out GetData()
- Blue: Call GetDataEx() from main entry point

but now Newtonsoft is not defined:

![image](https://user-images.githubusercontent.com/4738140/53068803-d97a9280-352d-11e9-9cca-1a3dbb21a130.png)

I am close here, but have missed another small issue I suspect. Can you please point me in the right direction?

**Comment by fabriciomurta** [comment]
I think `Newtonsoft` shouldn't be defined anyway, the namespace the library exports is `Newtonsoft.Json`, no?

The error message and reported file name + line number does not match between your screenshots.

On a different topic, just a suggestion, you could [try using gitter](https://gitter.im/bridgedotnet/Bridge) to draw quick questions about Bridge, until you are sure they are actual issues. This way you could hit further the community and get a better feedback on the problems you run in with Bridge.

**Comment by natiki** [comment]
@fabriciomurta Thankyou for your patience, help and time. I will use Gitter.

I found the issue. The `<script src="newtonsoft.json.js"></script>` was missing from the file I was testing with, hence the error.

I am closing this one.

**Comment by fabriciomurta** [comment]
Okay, now all makes sense; interesting the bridge-generated **index.html** should have had the `script` tag, maybe you already using your own index?

And this also explains why I see the error message not corresponding to the source file, it was mapped thru the JavaScript sources mapping; so whilst it had a reference to `Newtonsoft.*`, a class path in javascript, there were not that in the .cs code. I didn't really notice the last screenshot was from google crhome, from "client" side when running the generated code.
