### ISSUE TITLE
Feature Request - Google Protocol Buffers support....

### ISSUE THREAD

**Issue by natiki** [bridgedotnet/Bridge#3847]
Hi,

Having JSON support out of the box is fantastic. However when it comes to sending data around JSON is not that great in terms of space, format changes etc. https://developers.google.com/protocol-buffers/ deals with all of that elegantly.

Adding this support would make this already **AWESOME** project even better.

**Comment by fabriciomurta** [comment]
Hello @natiki! Thanks for the request, we now have it in our radar! Pull requests, as always, welcome!

Actually... We [-do- have it via a retyped package](https://retyped.com/?q=protobuf#search), have you tried it?

**Comment by fabriciomurta** [comment]
Well, as this is already implemented via retyped, there's not really much point in keeping the issue open, is there?
