### ISSUE TITLE
Issue creating generic type inside of manually loaded module

### ISSUE THREAD

**Issue by cinjguy** [bridgedotnet/Bridge#3848]
I have been experimenting with doing code splitting in our Bridge app, and am running into errors inside of manually loaded modules (using Bridge.Module.Load). The error seems to be related to how generic types are being lazily defined.

In my case, from within the manually loaded module, I create an instance of Dictionary<Type, object>. If I try to add an item to the dictionary, an error occurs:
Cannot read property 'getHashCode2' of undefined

I noticed when the instance is being created, the dictionary's comparer is not being initialized correctly (System.Collections.Generic.EqualityComparer$1(TKe y).def).

### Steps To Reproduce
Since it is an issue with modules, I was not able to reproduce on Deck. I have a small project that demonstrates the issue.

[GenericModuleIssue.zip](https://github.com/bridgedotnet/Bridge/files/2886004/GenericModuleIssue.zip)

### Expected Result

Should be able to add items to the dictionary

### Actual Result

Error: Cannot read property 'getHashCode2' of undefined

**Comment by cinjguy** [comment]
Note I also posted this same issue on the bridge.net forum:

https://forums.bridge.net/forum/community/help/6049-issue-creating-generic-type-inside-of-manually-loaded-module

**Comment by miladsadeghi72** [comment]
i test that, no exception, are you sure?

**Comment by cinjguy** [comment]
Yes I am getting an exception.  Note that in my repro I am catching the error and logging it to the console:

![capture](https://user-images.githubusercontent.com/28735215/53133793-6f201d00-3542-11e9-9b68-6ba20a9aaf0e.PNG)

**Comment by miladsadeghi72** [comment]
sorry, i saw exception, its a bug at bridge
but it can fix via : 
```csharp
public class TypeEqualityComparer :
            IEqualityComparer<Type>
    {
        public bool Equals(Type x, Type y)
        {
            return x.FullName == y.FullName;
        }

        public int GetHashCode(Type obj)
        {
            return obj.GetHashCode();
        }
    }

var dictionary = new Dictionary<Type, object>(new TypeEqualityComparer());
 dictionary[typeof(MyModule)] = this;
```

**Comment by cinjguy** [comment]
Thanks for looking into this.  Yes, I can work around it in that way, but this is just one example of how the generic type initialization is not working.  I can reproduce a similar issue by creating and using a list instead of a dictionary:

```csharp
var list = new List<string>();
list.Add("test");
```

This results in the following error: `System.NullReferenceException: Cannot read property 'length' of null`

There is a similar problem occurring initializing the list.  In the constuctor for `List<T>`, this line of javascript is not working correctly:

```javascript
this._items = System.Collections.Generic.List$1(T)._emptyArray;
```

`_emptyArray` is undefined, so later when adding an item to the list, the null reference exception occurs.

**Comment by miladsadeghi72** [comment]
I agree, wait for bridge team response

**Comment by cinjguy** [comment]
I did find that I could prevent the issue by adding changing how I load the module:

```csharp
Module.Load(typeof(MyModule)).ContinueWith(t =>
{
    // adding this line seems to have fixed the problem
    Script.Write("Bridge.Class.staticInitAllow = true;");
    var myModule = new MyModule();
});
```

I really have no idea what the implications of doing that are.  I am worried it may lead to further problems elsewhere.

**Comment by miladsadeghi72** [comment]
why did using  Module.Load
why don't write normal?

**Comment by cinjguy** [comment]
The app we are building is quite large.  I am trying to use modules to reduce the amount of code that has to be loaded on initial page load.  With Module.Load, I can defer loading modules until they are needed.

**Comment by miladsadeghi72** [comment]
i using cash on local storage, download and save on that 
first time is little long, second time is much fast
i recommend this, however thanks for useful info, i didn't knows

**Comment by fabriciomurta** [comment]
We have applied a fix to Bridge code and, as far as the scenarios described here are concerned, the issue has been fixed!

The fix will make it to the next Bridge release (see attached milestone).
