### ISSUE TITLE
typeof(Type).ToString() returns "Function" instead of "System.Type"

### ISSUE THREAD

**Issue by ChrML** [bridgedotnet/Bridge#3855]
Super minor issue/curiosity:
The "typeof(System.Type)"- object seems to behave slightly different from other typeof(...) objects with the ToString() method.

### Steps To Reproduce

https://deck.net/bf94e2e5a827e4ec837d4d30c1d56899

```csharp
// Report by: Christian "ChrML" Lundheim
// 25.02.2019

public class Program
{
    public static void Main()
    {
        string typeName = typeof(Type).ToString();
        Console.WriteLine(typeName); // Expected: "System.Type"    Actual: "Function"
    }
}
```

### Expected Result

```
System.Type
```

### Actual Result

```
Function
```

**Comment by ChrML** [comment]
Additional info:
The same seems to apply to the typeof(Type).Name- property.

**Comment by fabriciomurta** [comment]
Fixed! The fix will make it to the next Bridge release (see attached milestone).
