### ISSUE TITLE
Error with generics in Module

### ISSUE THREAD

**Issue by colderlord** [bridgedotnet/Bridge#3860]
A description of the issue.

### Steps To Reproduce

https://deck.net/a62bd78c412c66b2194b59cc88ab0be9

```csharp
[Module(Bridge.ModuleType.UMD)]
public class Program
{
    public static ILazy<Class1> lazyClass1;

    public static void Main()
    {
        lazyClass1 = new Lazy<Class1>();
        Ololo(lazyClass1);
    }

    internal static void Ololo(ILazy<Class1> lst)
    {
        lst.Value();
    }
}

[Module(Bridge.ModuleType.UMD, "Module1")]
public class Class1
{
}

[Module(Bridge.ModuleType.UMD, "Module2")]
public interface ILazy<T> where T : class
{
    /// <summary>
    /// Get Resolved Type T
    /// </summary>
    /// <returns>Resolved Type T</returns>
    T Value();
}

[Module(Bridge.ModuleType.UMD, "Module2")]
public class Lazy<T> : ILazy<T> where T : class
{
    public T Value()
    {
        return default(T);
    }
}
```

i've an exception:
`Uncaught TypeError: lst.Module2$Demo$ILazy$1$Module1$Demo$Class1$Value is not a function
    at Function.Ololo`

### Here is generated code:

```js
Ololo: function (lst) {
                        lst.Module2$Demo$ILazy$1$Module1$Demo$Class1$Value();
                    }
```

but in js object i have value: `lst.Module2$Demo$ILazy$1$Demo$Class1$Value`.

in my opinion, generated code is right, but wrong in my object

**Comment by colderlord** [comment]
i think, the problem is in function `Bridge.getTypeAlias`. Or maybe i'm wrong

**Comment by fabriciomurta** [comment]
The issue has been fixed and we've just merged it upstream! The fix will be available the upcoming Bridge release (see attached milestone for version number).
