### ISSUE TITLE
Array of Array haven't assembly

### ISSUE THREAD

**Issue by miladsadeghi72** [bridgedotnet/Bridge#3865]
i using assembly for Serialize and Deserialize  objects
I got accidental this exception on sample tests

https://deck.net/db0da0f53bd7d7736ed74ec40856db31

```csharp
public class Program
{
    public static void Main()
    {
            try
            {
                Console.WriteLine(typeof(string[][]).Assembly.FullName);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        
    }
}
```

### Expected Result on console

mscorlib

### Actual Result on console

Bridge.Reflection.getTypeAssembly(...) is undefined

**Comment by fabriciomurta** [comment]
Fixed! Thanks for not only reporting the issue, but also proposing a fix, and also understanding why we took the one from @vladsch! We're looking forward for further contributions from you in the future!

The fix will make it to the next Bridge release, version number according to the milestone attached to this issue.

**Comment by geoffreymcgill** [comment]
Original issue by @miladsadeghi72:

i using assembly for Serialize and Deserialize  objects
I got accidental this exception on sample tests

https://deck.net/db0da0f53bd7d7736ed74ec40856db31

```csharp
public class Program
{
    public static void Main()
    {
            try
            {
                Console.WriteLine(typeof(string[][]).Assembly.FullName);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        
    }
}
```

### Expected Result on console

mscorlib

### Actual Result on console

Bridge.Reflection.getTypeAssembly(...) is undefined
