### ISSUE TITLE
Missing Field At auto get set property

### ISSUE THREAD

**Issue by miladsadeghi72** [bridgedotnet/Bridge#3867]
this bug is about reflection

https://deck.net/ba436f5e4c832500a0f0a776ceb7f426

on MyModel class metadata is ok exception of one
no field found for Name property, in fact not builded

```csharp

    public class MyModel
        {
            public string Name { get; set; }
            public string Name2;
        }
```

sample :

```csharp
public class Program
{
    public static void Main()
    {
        var t = typeof(MyModel);
            foreach (var Member in t.GetFields(BindingFlags.Public |BindingFlags.NonPublic| BindingFlags.Instance))
            {
                Console.WriteLine(Member.Name);
            }
    }
    public class MyModel
        {
            public string Name { get; set; }
            public string Name2;
        }
}
```

### Expected Result on console

Name_$k__BackingField
Name2

### Actual Result on console

Name2

**Comment by miladsadeghi72** [comment]
in other word:

https://deck.net/1eb588b1283dfe895c7ea54c3aa5d301

**Comment by miladsadeghi72** [comment]
https://dotnetfiddle.net/MEpNt2

**Comment by geoffreymcgill** [comment]
The best we can tell, the `Name_$k__BackingField` is not part of the .NET spec and should not be relied upon as being a stable value. We will try to output the same result, but from the spec perspective, the current Bridge output (empty string) is valid.

**Comment by miladsadeghi72** [comment]
#1- 
remember we need to known every fields on class to serialize that, so if can't find then we can't serialize something on bridge and next can't deserialize that, we will losing data or have unexpected exception in best situation
this mean if i using a database which have serializer so i lose auto property data( don't forget about anonymous objects)
#2- 
otherwise we using serializer on our client server side projects, so if that fields name not be same as server side then we have an exception
i strongly recommend to do this right exact way in .net https://dotnetfiddle.net/MEpNt2a
#3- 
in standard models you can't have a property whiteout a field because a property is a delegate

**Comment by miladsadeghi72** [comment]
#1- 
remember we need to known every fields on class to serialize that, so if can't find then we can't serialize something on bridge and next can't deserialize that, we will losing data or have unexpected exception in best situation
this mean if i using a database which have serializer so i lose auto property data( don't forget about anonymous objects)
#2- 
otherwise we using serializer on our client server side projects, so if that fields name not be same as server side then we have an exception
i strongly recommend to do this right exact way in .net https://dotnetfiddle.net/MEpNt2a
#3- 
in standard models you can't have a property whiteout a field because a property is a delegate

**Comment by miladsadeghi72** [comment]
well done
```chsarp
result.Add("n", $"<{m.Name}>k__BackingField");
```
i waiting for bridge 17.7.0

**Comment by fabriciomurta** [comment]
As you noticed, a fix was made available, and we just reviewed it and merged upstream! It will make it to the following Bridge release from now, which version number we reflect in the issue's milestone.

Thanks for the report!

**Comment by geoffreymcgill** [comment]
Original issue by @miladsadeghi72:

this bug is about reflection

https://deck.net/ba436f5e4c832500a0f0a776ceb7f426

on MyModel class metadata is ok exception of one
no field found for Name property, in fact not builded

```csharp

    public class MyModel
        {
            public string Name { get; set; }
            public string Name2;
        }
```

sample :

```csharp
public class Program
{
    public static void Main()
    {
        var t = typeof(MyModel);
            foreach (var Member in t.GetFields(BindingFlags.Public |BindingFlags.NonPublic| BindingFlags.Instance))
            {
                Console.WriteLine(Member.Name);
            }
    }
    public class MyModel
        {
            public string Name { get; set; }
            public string Name2;
        }
}
```

### Expected Result on console

Name_$k__BackingField
Name2

### Actual Result on console

Name2
