### ISSUE TITLE
Discontinue the usage of JSBuild on windows builds.

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#387]
Since issue bridgedotnet/Bridge#271 was implemented, `JSBuild` is not used to minify the output files. It now just joins files, a much simpler process that's already done a different way in Linux with bash scripts.

Try to elaborate a simple `.bat` script (if not feasible, fall to powershell script) that joins the `.js` files into the main `Bridge.js` in a similar way the linux scripts does.

The `Bridge.min.js`, as said above, is no longer needed to be generated during Bridge's own build time. It is now output at the time the `Bridge.Builder` is run.

Clarifying:
- When Bridge itself is built, Bridge.min.js is not required to be generated
- When a project is built using Bridge, the Bridge.Builder module will extract Bridge.js and minify it in the exact same process other generated JavaScript files are minified.

**Note:** It was later found that this issue affected only the Bridge repo, so the current issue is replacing bridgedotnet/Builder#16 originally created.

**Comment by geoffreymcgill** [comment]
What would be required to write JSBuild right out of the process? If it's just combining files, there has to be a dozen easy ways to accomplish that process.

**Comment by fabriciomurta** [comment]
I think that the commits above talk by themselves. Only thing remaining is removing pesky BOM from throughout the merged file. I have it done and am in the process of making a NuGet package of the BOM stripping tool. That's the best error-free approach I could think on that does not require PowerShell.

**Comment by fabriciomurta** [comment]
Missing feature: pull the file header off the Bridge.jsb file

Implement this and make another pull request. Thanks @LeonidVeriga for pointing it out

**Comment by fabriciomurta** [comment]
Known limitation: if you use either double quotes (`"`) or backslashes (`\`) in the copyright= attribute for the project tag, it will break. Use &#xN approach instead (like newlines are imprinted in the attribute).

**Comment by fabriciomurta** [comment]
Should have closed this issue 23 days ago. Probably didn't because of pull request (code is already merged in mainstream).
