### ISSUE TITLE
Feature request: Add implementation of CollectionBase

### ISSUE THREAD

**Issue by ChrML** [bridgedotnet/Bridge#3870]
Feature request:

Include the CollectionBase class from the .NET Framework / .NET Core in Bridge .NET.
https://docs.microsoft.com/en-us/dotnet/api/system.collections.collectionbase?view=netframework-4.7.2

It is really handy for creating all sorts of collections where the owner of the collection needs to be notified to do something when the list is modified externally. Such as updating the HTML5 DOM if a the ListItemCollection based on CollectionBase changes.

If interested, I can post my C# implementation of this class here. It follows the same coding standards as Bridge .NET so should be easy to merge in.

### Steps To Reproduce
n/a

### Expected Result
n/a

### Actual Result
n/a

**Comment by ChrML** [comment]
I just found out that the System.Collections.ObjectModel.Collection<T> basically provides the same functionality in a generic matter. So CollectionBase may not be needed afterall.

**Comment by geoffreymcgill** [comment]
As you noted, there are alternatives to CollectionBase and Microsoft recommends that non-generic collections not be used. 

 > Important
> 
> We don't recommend that you use the CollectionBase class for new development. Instead, we recommend that you use the generic Collection<T> class. For more information, see [Non-generic collections shouldn't be used on GitHub](https://github.com/dotnet/platform-compat/blob/master/docs/DE0006.md).

For backwards compatibility, it would be nice for Bridge to support this class, although if Microsoft is recommending not to use it, we'll take that recommendation and leave the class out of Bridge.

In the future, if we can build in compile time tree shaking into Bridge, then including CollectionBase would be simple and would have no effect on the runtime package size if you did not use the class.
