### ISSUE TITLE
Local async function failing

### ISSUE THREAD

**Issue by SylvainDebaudringhien** [bridgedotnet/Bridge#3871]
Hi.

I've noticed that the following cannot get translated (Bridge 17.6):

```csharp
public class Program
{
    static Task something()
    {
        return Task.FromResult(false);
    }
    
    public static void Main()
    {
        async void fct() {
			await something();
        }
		fct();
    }
}
```

Trace: 

> The `await' operator can only be used when its containing lambda expression is marked with the `async' modifier

**Comment by fabriciomurta** [comment]
Helly @SylvainDebaudringhien, did you happen to be able to reproduce this in a [deck](https://deck.net/)?

**Comment by SylvainDebaudringhien** [comment]
Here it is:

https://deck.net/44c8334ee8ed8f4ca87b3e084a812bd4

**Comment by fabriciomurta** [comment]
Thanks for the deck! Here's a working version on native .NET: https://dotnetfiddle.net/pQwjH7
(the change is just that I wrapped assertions thru the code)

**Comment by fabriciomurta** [comment]
Fixed! The fix will be out next Bridge release (see milestone).

**Comment by SylvainDebaudringhien** [comment]
Thanks!
