### ISSUE TITLE
Wrong type returned in linq

### ISSUE THREAD

**Issue by miladsadeghi72** [bridgedotnet/Bridge#3875]
i expect linq query return same type as get
on this sample returned object

https://deck.net/9d1b6b1d67eaabe70f203180881b478e

```csharp
public class Program
{
    public static void Main()
    {
        var bytes = new byte[] { 1, 2, 3, 4 };
            Console.WriteLine(bytes.ToArray().GetType().Name);
            Console.WriteLine(bytes.GetType().Name);
    }
}
```

### Expected Result on console

Byte[]
Byte[]

### Actual Result on console

Object[]
Byte[]

**Comment by fabriciomurta** [comment]
Fixed! Thanks for reporting the issue! The fix will be available next Bridge release (see attached milestone). The fix would already be available from the sources at the **dev** branch.

**Comment by miladsadeghi72** [comment]
Good but did you check other linq extns?
Because I didnt

**Comment by fabriciomurta** [comment]
I looked up some extensions and they were supposed to return different types than the source variable; I didn't do a thorough investigation on all extensions though. Anyway, this looks like a specific issue from `ToArray()`; other potential mismatches vs native .NET ought to be treated separately.

**Comment by geoffreymcgill** [comment]
Original issue by @miladsadeghi72:

i expect linq query return same type as get
on this sample returned object

https://deck.net/9d1b6b1d67eaabe70f203180881b478e

```csharp
public class Program
{
    public static void Main()
    {
        var bytes = new byte[] { 1, 2, 3, 4 };
            Console.WriteLine(bytes.ToArray().GetType().Name);
            Console.WriteLine(bytes.GetType().Name);
    }
}
```

### Expected Result on console

Byte[]
Byte[]

### Actual Result on console

Object[]
Byte[]
