### ISSUE TITLE
Generic modifier "out" causes wrong JS code to be generated (multiple invocations)

### ISSUE THREAD

**Issue by d-p-y** [bridgedotnet/Bridge#3876]
Hi,
it seems when I have a method that is returning instances of classes that are implementations of some interface and that interface is using generic parameter modified with 'out' (to achieve covariance) and if in the same line I access property then generated JS is incorrect. In fact that method is needlessly invoked twice.

Workarounds: 
- remove `out` from IAbstr declaration
- store result of 'fac.Create()' in variable f.e.: 
```csharp
var i = fac.Create(); 
var a = x.SomeProperty;
```

### Steps To Reproduce

https://deck.net/c4fcc45d88da6523853aea918028640e

https://dotnetfiddle.net/bMVUy8

```csharp
using System;

public interface IAbstr<out T> {
    int SomeProperty { get; }
}

class Impl : IAbstr<string> {
    public int SomeProperty { get; set; }
}

public class Fac {
    public static int CreateCalledCount = 0;
    
    public IAbstr<string> Create() {
        CreateCalledCount++;
        return new Impl();
    }
}

public class Assert {
    public static void Equals<T>(T expected, T fact) {
        if (expected == null && fact == null || 
            expected != null &&  expected.Equals(fact)) {
            
            return;
        }
        throw new Exception($"expected {expected} but got {fact}");
    }
}

public class Program {
    public static void Main() {        
        var fac = new Fac();        
        int a = fac.Create().SomeProperty;
        Assert.Equals(1, Fac.CreateCalledCount);
		Console.WriteLine("ok");
    }
}
```

### Expected Result

I expect to get line "ok" on console...

### Actual Result

... but I actually receive Assert.Equals exception.

**Comment by geoffreymcgill** [comment]
Thanks for letting us know about this issue and for providing an excellent sample. We will investigate and attempt to fix for the next Bridge release.

**Comment by fabriciomurta** [comment]
Fixed! The fix will be available next Bridge version (see attached milestone). Available at once from sources at the **dev** branch.

**Comment by d-p-y** [comment]
You guys are really quick! Thank you
