### ISSUE TITLE
Instantiate an object from javascript to call a method....

### ISSUE THREAD

**Issue by natiki** [bridgedotnet/Bridge#3878]
Hi,

- Bridge.NET 17.7.0
- I have TripSeekerSearch.Engine project which is a Bridge.NET project and a class **SearchInput**

![image](https://user-images.githubusercontent.com/4738140/54508952-e8712b00-499b-11e9-9295-0fa2cf6e98f3.png)

I am trying to instantiate the **SearchInput** class from within JS as I have a method Search():

```c#
public class TripSearchEngine
{
    public static SearchOutput Search(SearchInput aSearchParameters)
    {
        var searchEngine = new SearchEngine(Trips());

        return searchEngine.Search(aSearchParameters);
    }
}
```
that takes a parameter of that type with the following:

```js
var seachInput = new TripSeekerSearch.Engine.Framework.Search.Dtos.SearchInput();
```
but am getting undefined:

![image](https://user-images.githubusercontent.com/4738140/54509038-3128e400-499c-11e9-8ccd-54cde15f8edc.png)

The namespace is correct and I have had a look at https://deck.net/405118c4961642fd5e5623fb357e51ab which indicates that this should be easily possible.

What have I missed? How do I make this work?

PS. I applied for forum access but have yet to receive my access token, so apologies for posting here. Also cannot create Deck as my solution has heaps of other stuff in it so cannot replicate this fully there.

**Comment by geoffreymcgill** [comment]
Hi @natiki – I manually approved your forum account, but you should have been sent an email confirmation. Maybe it was trapped in a spam filter?

You should be able to post this technical support question in the [forums](https://forums.bridge.net) now.

**Comment by natiki** [comment]
Posted to forums https://forums.bridge.net/forum/community/help/6084-instantiate-an-object-from-javascript-to-call-a-method
