### ISSUE TITLE
Linq expressions not using correct IEnumerable<> implementation

### ISSUE THREAD

**Issue by Triogap** [bridgedotnet/Bridge#3885]
If a class implements multiple generic IEnumerable interfaces, linq methods will always use the default implementation.

https://deck.net/6fad03506eb26275ef0f05ea20e36b07

The System.Linq.Enumerable.from() should get a Type parameter as Bridge.getEnumerator() has.

**Comment by fabriciomurta** [comment]
Fixed! This is going to make it to the following Bridge release (the version reflects the milestone assigned to this issue).

Thanks for reporting this!
