### ISSUE TITLE
Incorrect to string value for a decimal

### ISSUE THREAD

**Issue by samuelGrahame** [bridgedotnet/Bridge#3887]
When using `.toString("G")` in javascript in bridge, for decimals should include a decimal place. even it is zero. Not a major issue.

### Steps To Reproduce

https://deck.net/d5f49675c62c96e19a18303e3e3a1ada
compared to:
https://dotnetfiddle.net/hH0EEv

```csharp
public class Program
{
    public static void Main()
    {        
        Console.WriteLine(0.0m);        
    }
}
```

### Expected Result

```js
0.0
```

### Actual Result

```js
0
```

**Comment by geoffreymcgill** [comment]
Thanks for the report. We will investigate and fix for the next release.

**Comment by vladsch** [comment]
I don't think that it can be fixed because we cannot distinguish 0 and 0.0 literals in javascript.
At least I don't see a solution (only if convert literals to string during translation to javascript and count decimal places before conversion to decimal but  it's more trouble than it's worth)

**Comment by geoffreymcgill** [comment]
We will try and get this working for the next release, but have made this a low-priority task.

**Comment by fabriciomurta** [comment]
Fixed! This is going to make it to the next Bridge release!
