### ISSUE TITLE
document.registerElement() support

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#389]
The issue originates from #366.

Currently, [document.registerElement()](https://developer.mozilla.org/en-US/docs/Web/API/Document/registerElement) is not sealed in the standard and considered as an experimental functionality. At least, it is not supported in IE and Safari.

Also there is a technical problem. A `.registerElement()` call returns a constructor. It is questionable or, at least, not obvious how to implement it in C#/Bridge if possible at all.

In any way, that can be done right away using `.ToDynamic()` in this way:

```
[External]
[Name("MyTag")]
public class MyTag : Element
{
    public MyTag()
    {
    }
}

public class App
{
    public static void Main()
    {
        Global.ToDynamic().MyTag = Document.ToDynamic().registerElement("my-tag");
        var mytag = new MyTag();
    }
}
```

I am creating the issue to have it logged and monitor the situation. At some point, if the feature get higher priority, we can look into that again.

Here is a helpful tutorial for better understanding of `.registerElement()` usage.
http://www.html5rocks.com/en/tutorials/webcomponents/customelements

**Comment by michaelcheers** [comment]
@DaniilVeriga 
I did make a type template new method.

[Template("new {0}")]
public static extern object New (Type value);

[Template("document.registerElement({0})")]
public static extern Type RegisterElement (string value);

and for document instance:

[Template("{this}.registerElement({0})")]
public extern Type RegisterElement (string value);

**Comment by DaniilVeriga** [comment]
Hi @michaelcheers,

Thank you for the suggestions! Could you, please, demonstrate how you use these methods?

**Comment by michaelcheers** [comment]
@DaniilVeriga,

For the first one: 

```csharp
var mytagtype = Document.RegisterElement("my-tag");
var mytag = Script.New(mytagtype);
```

The second one:

```csharp

var mytagtype = Document.RegisterElement("my-tag");
var mytag = mytagtype();
```

**Comment by DaniilVeriga** [comment]
Thank you for sharing!

There is one more issue with a discussion on HTML elements inheriting - #1238.

**Comment by geoffreymcgill** [comment]
The `document.registerElement()` function has been [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Document/registerElement) in JavaScript. This function is not supported in IE nor Safari. 

We will not be able to add to **Bridge.Html5** library.

**Comment by geoffreymcgill** [comment]
Please see **Support for Custom Elements** in Issue #2580.
