### ISSUE TITLE
The 'is' keyword does not work with Retyped.dom.HTMLElement class.

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#3892]
Bridge outputs javascript code that incurs in wrong results when using the `is` test.

### Steps To Reproduce

Added the using headers and namespace paths in class references for clarity:
https://deck.net/def161316f06e378469dd4886bb5faaa

```csharp
using Bridge;
using System;
using Retyped;
using static Retyped.dom;

public class Program
{
    public static void Main()
    {
        var meta = document.createElement("meta");
        
        if (meta is Retyped.dom.HTMLScriptElement element) 
        {
        	System.Console.WriteLine("I'm a script");    
        }
        else 
        {
            System.Console.WriteLine("I'm not a script");
        }
    }
}
```

Javascript output:

```js
/**
 * @compiler Bridge.NET 17.7.0
 */
Bridge.assembly("Demo", function ($asm, globals) {
    "use strict";

    Bridge.define("Program", {
        main: function Main () {
            var meta = document.createElement("meta");
            var element;
            if (((element = meta)) != null) {
                System.Console.WriteLine("I'm a script");
            } else {
                System.Console.WriteLine("I'm not a script");
            }
        }
    });
});
```

The test `((element = meta)) != null` looks like something that would work for anything we bind.

### Expected Result

Outputs **"I'm not a script"**

### Actual Result

Outputs **"I'm a script"**

### See also
Bridge.NET forum thread: ["is" keywork not working as expected](https://forums.bridge.net/forum/bridge-net-pro/bugs/6108)

**Comment by vladsch** [comment]
It is Deck issue due ExternalCastRule.Plain rule
See the result without that rule
https://deck.net/5e98a0774dbe9f512aa99983fa39bc8f

**Comment by fabriciomurta** [comment]
So I take it that's not supposed to work when [b]ExternalCastAttribute[/b] is set to [b]plain[/b]. Updated the original issue message with a reference to the thread that originated it, and also posted a follow-up in the issue.
