### ISSUE TITLE
External Ctors with reflectable attribute have same ScriptNames

### ISSUE THREAD

**Issue by colderlord** [bridgedotnet/Bridge#3893]
A description of the issue.

### Steps To Reproduce

https://deck.net/ef4fc1fb2aa79c57dfa7a8c5fb2efc07

```csharp
[External]
[Reflectable]
public class TestClass
{
    public extern TestClass();

    public extern TestClass(string str);
}

public class Program
{
    public static void Main()
    {
    }
}
```

I expected that `ScriptName` (`sn`) of ctor with argument will `$ctor1`, but it's `ctor`. It's not good, because if i will try to use `Activator.CreateInstance(typeof(TestClass), "123")` will call ctor with Scriptname `ctor` - without arguments...

### Expected Result

```js
$m("Demo.TestClass", function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":".ctor","t":1,"p":[$n[0].String],"pi":[{"n":"str","pt":$n[0].String,"ps":0}],"sn":"$ctor1"}]}; }, $n);
```

### Actual Result

```js
$m("Demo.TestClass", function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":".ctor","t":1,"p":[$n[0].String],"pi":[{"n":"str","pt":$n[0].String,"ps":0}],"sn":"ctor"}]}; }, $n);
```

**Comment by fabriciomurta** [comment]
Hello @colderlord, I believe you're missing pieces in the deck you provided to show the actual problem in practice. Isn't the `$ctor1` a Bridge-specific naming convention? 

In other words, what external implementation would you accept the that constructor overload? Could you, maybe, imbue a sample/stub external class implementation to the Deck, that would work in the described scenario?

tip: you can create a `static void` method with `[Bridge.Init(InitPosition.Top)]` then as its body, wrap javascript code as you please (via `Script.Write()` or `/*@ ... */` block-comment.

At least as far as I know, usually external class implementations in JavaScript would only have one constructor entry point, and the "overloads" would just be `undefined` parameters.

**Comment by colderlord** [comment]
Hello @fabriciomurta . 
I did not miss anything :) Deck not showing metadata :( i don't know why.

I'll try explain what am i doing.
I have 2 Projects:
Project1 have External class `TestClass` with `ReflectableAttribute` (for generating metadata!).
Project2 have javascript implementation of this class. I wrote it manually. How i did that? i wrote real `TestClass` without `External`, compile it and copy javascript code then i past it in Project2.

In Project1 i call `Activator.CreateInstance(typeof(TestClass), "123")`. And i exprect that my second `ctor` will invoked, but invoked first `ctor`. And i wont expect that. I debug this and found, that `Bridge` in `applyConstructor` method found by reflection (because of `ReflectableAttribute`) 2 ctors, and found right ctor. Then in that method takes `ctor.sn` (`ScriptName`) and choose ctor like that `constructor = constructor[ctor.sn]`. Because both `sn` is equals, it will be invoked by first founded ctor.

**Comment by vladsch** [comment]
Bridge does not append suffix for external overloads because the logic is unclear how overloads names are resolved in external implementation. You can add Name attribute for ctors to define script names.

**Comment by vladsch** [comment]
I found that Bridge doesn't support Name on a constructor. We will add such support.

**Comment by vladsch** [comment]
The PR with support Name attribute for constructors is committed. Now you can use
```csharp
[External]
[Reflectable]
public class TestClass
{
    [Name("ctor")]
    public extern TestClass();

    [Name("ctor$1")]
    public extern TestClass(string str);
}

```

**Comment by colderlord** [comment]
oh, thanks

**Comment by fabriciomurta** [comment]
The [Attribute Reference entry for Name in the wiki documentation](https://github.com/bridgedotnet/Bridge/wiki/attribute-reference#name) does not mention anything about supporting or not constructors, so that's rather a bug (where all methods should support it) and this change imply a review in the documentation.

**Comment by fabriciomurta** [comment]
The changes proposed by Vladimir works great and will be included next Bridge version!
