### ISSUE TITLE
UnknownIdentifierResolveResult when referencing a static defined in another project.

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#3894]
Project A has a static class B that defines a constant string C

```csharp
namespace A
{
    public static class B
    {
        public const string C = "C";
    }
}
```

Project D has a reference to project A and defines a class E that accesses the string defined in A.B.C

```csharp
namespace D
{
    public class E
    {
        public string F = A.B.C;
    }
}
```

This solution builds but the output javascript has an UnknownIdentifierResolveResult in it:
D.js

```js
/**
* @version 1.0.0.0
* @copyright Copyright © 2019
* @compiler Bridge.NET 17.7.0
*/
Bridge.assembly("D", function ($asm, globals) {
    "use strict";
    Bridge.define("D.E", {
        fields: {
            F: null
        },
        ctors: {
            init: function () {
                this.F = [UnknownIdentifierResolveResult A].b.c;
            }
        }
    });
});
```

### See Also
https://forums.bridge.net/forum/bridge-net-pro/bugs/6125-unknownidentifierresolveresult-when-referencing-a-static-defined-in-another-project

**Comment by fabriciomurta** [comment]
The fix looks good, it will be included next Bridge release!
