### ISSUE TITLE
Uncaught TypeError: Cannot create property 'kind'....

### ISSUE THREAD

**Issue by natiki** [bridgedotnet/Bridge#3897]
- Bridge: 17.7.0

Application fails when making the following call:

```csharp
if (aSearchParameters.DepartureStart.HasValue)
   tempResult = tempResult.Where(aR => aR.Dd.Date >= aSearchParameters.DepartureStart.Value.Date);
```
giving a stack trace of:

```
Uncaught TypeError: Cannot create property 'kind' on string '2019-07-19'
    at Function.getDate (bridge.js:10476)
    at SearchEngine.cs:89
    at composedPredicate (bridge.js:27597)
    at Yielder.<anonymous> (bridge.js:27671)
    at IEnumerator.moveNext (bridge.js:24828)
    at WhereSelectEnumerable.Enumerable.forEach (bridge.js:27125)
    at WhereSelectEnumerable.Enumerable.ToArray (bridge.js:27002)
    at ctor.Search (SearchEngine.cs:109)
    at Function.Search (TripSearchEngine.cs:97)
    at <anonymous>:1:42 

  | getDate | @ | bridge.js:10476
-- | -- | -- | --
  | (anonymous) | @ | SearchEngine.cs:89
  | composedPredicate | @ | bridge.js:27597
  | (anonymous) | @ | bridge.js:27671
  | IEnumerator.moveNext | @ | bridge.js:24828
  | Enumerable.forEach | @ | bridge.js:27125
  | Enumerable.ToArray | @ | bridge.js:27002
  | Search | @ | SearchEngine.cs:109
  | Search | @ | TripSearchEngine.cs:97
  | (anonymous) | @ | VM1711:1


```

**aSearchParameters** is defined as:

```csharp
public class SearchInput
{
    public int[] Brands { get; set; }
    public DateTime? DepartureEnd { get; set; }
    public DateTime? DepartureStart { get; set; }
    public int[] Durations { get; set; }
    public double? MaxPrice { get; set; }
    public double? MinPrice { get; set; }
}
```

and **aR** as:

```csharp
public class TripItem
{
    /// <summary>
    ///     TripCode
    /// </summary>
    public string T;

    /// <summary>
    ///     Brand
    /// </summary>
    public OzCtTsBrandEnum B { get; set; }

    /// <summary>
    ///     Duration
    /// </summary>
    public int D { get; set; }

    /// <summary>
    ///     DepartureDate
    /// </summary>
    public DateTime Dd { get; set; }

    /// <summary>
    ///     PricePerPerson
    /// </summary>
    public double Ppp { get; set; }
}
```

**aSearchParameters** was originally set in JavaScript with:

```JavaScript
searchInput.DepartureStart = '2019-07-19';
```

Why is the date conversion failing as it is in  ISO format: YYYY-MM-DD?

**Comment by geoffreymcgill** [comment]
Hi. Thanks for the report. Can you share a https://deck.net sample demonstrating how to reproduce the scenario?

**Comment by natiki** [comment]
@geoffreymcgill How do I enter the JS I was executing, because without that the DECK sample is impossible to create?

**Comment by geoffreymcgill** [comment]
Isn't `DepartureStart` required to be set using a Date (or DateTime) object?

**Comment by natiki** [comment]
yes but the assignment is done inside JavaScript using a valid ISO date viz:

```
searchInput.DepartureStart = '2019-07-19';
```
so that should convert to a valid C# DateTime object with the DateTime.Date set for the 19th July 2019

**Comment by natiki** [comment]
For now I will use the work around of:

```
searchInput.DepartureStart = new Date(2019, 6, 19);
```

**Comment by geoffreymcgill** [comment]
Well, I don't really know what's going on here. 

Are you setting `searchInput.DepartureStart = '2019-07-19';` manually in some custom .js?

If you provide a https://deck.net sample demonstrating how to reproduce we will certainly take a close look.

You can add manual JavaScript into your C# using the following technique:

https://deck.net/3701580d0b9b30533de298d98f2ebe10

```csharp
public class Program
{
    public static void Main()
    {
        var msg = "temp";
        
        /*@ msg = "a new value"; */
        
        Console.WriteLine(msg);
    }
}
```

**Comment by geoffreymcgill** [comment]
> so that should convert to a valid C# DateTime object with the DateTime.Date set for the 19th July 2019.

That's not how it works. You have defined the `DepartureStart` property as a **DateTime**, so trying to set with a **String** is going to fail. It would fail in C# and it will fail in JS.

**Comment by natiki** [comment]
Fair enough. Thanks @geoffreymcgill for pointing me in the right direction.
