### ISSUE TITLE
Negative zero literal not supported

### ISSUE THREAD

**Issue by c0pperdragon** [bridgedotnet/Bridge#3898]
The compiler will turn a  -0  literal to 0. This is not a big issue, but not strictly correct C# semantics.

https://deck.net/e8fd971e74153e169bc375b9e4db6f11

```csharp
public class Test
{
    public static void Main()
    {
        double negativezero = -0.0;    // fails
        System.Console.WriteLine(1 / negativezero);
    }
}
```

Output:
```
Infinity
```

Expected output:
```
-Infinity
```

## See Also

- #3899

**Comment by geoffreymcgill** [comment]
Very interesting. Thanks for pointing this out. We will investigate and try to fix this scenario.

https://dotnetfiddle.net/ZCnElI

```csharp
public class Test
{
    public static void Main()
    {
        double negativezero = -0.0;    // fails
        System.Console.WriteLine(1 / negativezero);
    }
}
```

**Comment by fabriciomurta** [comment]
The fix for this looks good, it is going to make it to the next Bridge release (see attached milestone).
