### ISSUE TITLE
Math.IEEERemainder gives wrong results

### ISSUE THREAD

**Issue by c0pperdragon** [bridgedotnet/Bridge#3899]
Certain argument values give wrong result.

https://deck.net/453e62e903b9523499063b3083347c06

https://dotnetfiddle.net/PdTtB7

```csharp
public class Test
{
    public static void Main()
    {
        Console.WriteLine(Math.IEEERemainder(-3, 2)); 
        Console.WriteLine(Math.IEEERemainder(5, 2));
        Console.WriteLine(Math.IEEERemainder(2, Double.NegativeInfinity));
        Console.WriteLine(Math.IEEERemainder(-4.3, Double.NegativeInfinity)); 
    }
}
```

Output
```
-1
-1
NaN
NaN
```
Expected output
```
1
1
2
-4.3
```

## See Also

- #3899

**Comment by geoffreymcgill** [comment]
Very nice find. We will investigate and fix for the next release. Thanks for letting us know about this defect. 👍

**Comment by fabriciomurta** [comment]
Fixed! The fix is going to make it to the next Bridge release (see attached milestone).
