### ISSUE TITLE
Math.Sign can not handle infinity values.

### ISSUE THREAD

**Issue by c0pperdragon** [bridgedotnet/Bridge#3900]
In case of infinitiy values (positive or negative), the Math.Sign method will deliver a result that is no proper number at all, but a null value.

https://deck.net/36cdf0211660bf167f2284899eab77fa

https://dotnetfiddle.net/VPUc9V

```csharp
public class Test
{
    public static void Main()
    {
        Console.WriteLine("POSITIVE: " + Math.Sign(Double.PositiveInfinity)); 
        Console.WriteLine("NEGATIVE: " + Math.Sign(Double.NegativeInfinity));
    }
}
```

Output
```
POSITIVE: null
NEGATIVE: null
```

Expected output
```
POSITIVE: 1
NEGATIVE: -1
```

## See Also

- #3898 
- #3899

**Comment by geoffreymcgill** [comment]
Hi @c0pperdragon – Thanks for letting us know about this defect and for providing the excellent sample demonstrating how to reproduce. We will investigate and fix the defect for the next release (17.8.0) of Bridge.

**Comment by fabriciomurta** [comment]
Fixed! This is going to make it to the next Bridge release (see attached milestone)!

**Comment by fabriciomurta** [comment]
Just to add a little to this, _float_ was as broken as _Double_, which was fixed in the same round.
https://deck.net/ef9e3025af0b8439e11671b6751adce3
