### ISSUE TITLE
Converting an int to a hex string will create a signed output for negative values

### ISSUE THREAD

**Issue by c0pperdragon** [bridgedotnet/Bridge#3901]
As specified by the Int32.ToString documentation, the output should be an 8-digit unsigned value.

https://deck.net/25257c9bd161729c57b947e98d78461a

https://dotnetfiddle.net/dlSsSg

```csharp
public class Test
{
    public static void Main()
    {
        int i = -423433;
        System.Console.WriteLine(i.ToString("x"));
        System.Console.WriteLine(i.ToString("X"));
    }
}
```
Output
```
-67609
-67609
```
Expected output
```
fff989f7
FFF989F7
```

## See Also

- #3898 
- #3899 
- #3900

**Comment by geoffreymcgill** [comment]
Hi @c0pperdragon – Interesting defect and excellent sample. Thanks for letting us know. We will investigate right away and fix before the next Bridge release.

**Comment by fabriciomurta** [comment]
This looked like a feature but was really a bug, as it worked for non-negative numbers and there were already related implementation on it in the code.

No matter what, the fix works nicely and should be good to go to the next release (bound to the issue milestone you can see attached here).
