### ISSUE TITLE
C# strings with unicode escapes can be incorrectly translated to javascript

### ISSUE THREAD

**Issue by c0pperdragon** [bridgedotnet/Bridge#3902]
Some unprintable characters in string literals generate a javascript string that will then not have the intended character values. I am using these kind of strings sometimes to encode binary data.

https://deck.net/efc7b06b97bf61d13fd1542e5ddc4e0c

https://dotnetfiddle.net/0GmSQx

```csharp
public class Test
{
    public static void Main()
    {
        string s = "\ud8a1\ud8a2\ue681";
        System.Console.WriteLine( (int) s[0]);
        System.Console.WriteLine( (int) s[1]);
        System.Console.WriteLine( (int) s[2]);
    }
}
```
Output
```
65533
65533
59009
```
Expected output
```
55457
55458
59009
```

**Comment by geoffreymcgill** [comment]
Very nice find. Thanks for notifying us of this defect. We will investigate and fix before the next release of Bridge.

**Comment by geoffreymcgill** [comment]
A pull-request with a fix for this issue has been created. Once a review and further testing is complete, this PR will be included in the next release of Bridge.

**Comment by fabriciomurta** [comment]
The fix is good and ready to be merged upstream. It will make way into the upcoming Bridge release (see assigned milestone).
