### ISSUE TITLE
The ^ operator for bool values returns weird result

### ISSUE THREAD

**Issue by c0pperdragon** [bridgedotnet/Bridge#3903]
Both the `^` as well as the `^=` deliver something that is neither a real `true` or `false` value, but something that looks like this when printing, but being not compatible with real bool values (maybe just a string).

https://deck.net/269532073815703d8358f98e081930b4

https://dotnetfiddle.net/eOMwsk

```csharp
public class Test
{
    public static void Main()
    {
        var t = true;
        var f = false;
        var a = t ^ f;
        var b = t;
        b ^= t;

        System.Console.WriteLine(a);
        System.Console.WriteLine(b);
        System.Console.WriteLine(a == true);
        System.Console.WriteLine(b == false);
    }
}
```
Output
```
True
False
False
False
```
Expected output
```
True
False
True
True
```

**Comment by geoffreymcgill** [comment]
Cool bug! Nice find. Thanks for letting us know about this defect. We will investigate and fix before the next release.

**Comment by fabriciomurta** [comment]
The fix submitted looks enough, and will make it to the next Bridge release (see assigned milestone).

**Comment by fabriciomurta** [comment]
Oh, and thanks for all provided bug reports!
