### ISSUE TITLE
Type check for arrays can fail when testing against object[][] type

### ISSUE THREAD

**Issue by c0pperdragon** [bridgedotnet/Bridge#3904]
The semantics for this kind of type inclusion test is pretty involved. Your implementation works most of the time, but not always exactly as in the C# spec.

https://deck.net/313febf669674a4287185d0762cc5f70

https://dotnetfiddle.net/sgeUsA

```csharp
public class Test
{
    public static void Main()
    {
        object a = new int[][][] { new int[][] { new int[1] } };
        System.Console.WriteLine(a is object[]);
        System.Console.WriteLine(a is object[][]);
        System.Console.WriteLine(a is object[][][]);
        
        object b = new string[][] { new string[] { "hi" } };
        System.Console.WriteLine(b is string[][]);
        System.Console.WriteLine(b is object[]);
        System.Console.WriteLine(b is object[][]);   
        System.Console.WriteLine(b is object[][][]);
    }
}
```
Output
```
True
False
False
True
True
False
False
```
Expected output
```
True
True
False
True
True
True
False
```

**Comment by geoffreymcgill** [comment]
Very nice find. 👍 Thanks for the excellent sample demonstrating how to reproduce. We will investigate and fix this defect before the next release.

**Comment by fabriciomurta** [comment]
The fix for this issue is going to make it to the next Bridge release, according to the milestone assigned to this issue!
