### ISSUE TITLE
Double evaluation in ++ operator

### ISSUE THREAD

**Issue by c0pperdragon** [bridgedotnet/Bridge#3905]
The operand of all the pre- and post- increment/decrement operators gets evaluated twice.
If this operand has side effects, these cause faulty behavior. Contrary to C, in C# this situation is well specified.

https://deck.net/1163f28e0ee3fb9f69c6f9fd4103039f

https://dotnetfiddle.net/Z2H5rW

```csharp
public class Test
{
    public static void Main()
    {
        int[] a = new int[] { 3, 8 };
        int i = 0;
        a[i++]++;          
        System.Console.WriteLine(i);
        System.Console.WriteLine(a[0]);
        System.Console.WriteLine(a[1]);
    }
}
```
Output
```
2
9
8
```
Expected output
```
1
4
8
```

**Comment by geoffreymcgill** [comment]
Interesting defect. Thanks again for pointing out these defects and for providing the excellent samples. We will investigate and fix before the next Bridge release.

**Comment by c0pperdragon** [comment]
I have come up with this whole bunch of reports because I have a battery of tests that I use for my java-to-C# converter. Throwing the generated C# now at the bridge.net converter gives some interesting results. But most of it is compiling extremely well, even on the super-weird way my converter has to facilitate goto to implement the java construct of labeled break and continue.

**Comment by geoffreymcgill** [comment]
Thanks for taking the time to post these reports. We really appreciate the interest and pushing the compiler into these edge cases.

@c0pperdragon Is your Java-to-C# project on GitHub or any other details available? Sounds interesting.

**Comment by c0pperdragon** [comment]
We have created it for our own purpose, but I got the OK from my company to open-source it as well:
https://github.com/Greentube/Java-converter

It was intended as a light-weight alternative to GWT, but as it turns out, Google had just the same idea and they developed J2CL at the same time. So now my converter is quite overshadowed by the work of the big guys.  :-(

**Comment by fabriciomurta** [comment]
Fixed! The fix is going to make it to the following Bridge release (according to assigned milestone).
