### ISSUE TITLE
Left operand of +=, -=, etc. is evaluated twice

### ISSUE THREAD

**Issue by c0pperdragon** [bridgedotnet/Bridge#3906]
Similar to #3905
If the left operand has side effects, this causes faulty behavior.

https://deck.net/32a2be0b6500e97a53ab3bee18a7f586

https://dotnetfiddle.net/w2ZIfi

```csharp
public class Test
{
    public static void Main()
    {
        Queue<X> q = new Queue<X>();
        q.Enqueue(new X());
        q.Enqueue(new X());
        q.Dequeue().v += 7;    // Dequeue should only be called once
        System.Console.WriteLine(q.Count);
    }
}
public class X
{
    public int v;
}
```

### Expected Result

```js
1
```

### Actual Result

```js
0
```

**Comment by geoffreymcgill** [comment]
@c0pperdragon – Thanks for pointing out this defect and for providing the excellent simplified sample demonstrating how to reproduce. We will investigate and fix before the next release.

**Comment by fabriciomurta** [comment]
Fixed and merged, being included to the upcoming release, according to the assigned milestone!
