### ISSUE TITLE
VSIX installer for VS2019

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#3910]
Bridge VSIX package support for VS2019.

### Steps To Reproduce

Try to install the current Bridge VSIX package in a VS2019 installation.

#### From Gallery
1. Open VS2019
2. Switch to interface with no code (choose "continue without code", lower-right in the welcome dialog
3. Got to Extensions > Manage Extensions
4. Choose "online" in the left pane
5. Filter for "bridge" in the top-right search input

#### From downloaded file
1. Open https://github.com/bridgedotnet/Bridge/releases/tag/v17.7.0
2. Download the Bridge.NET.17.7.0.vsix file
3. Try to install it

#### From Gallery
Bridge package is listed and can be installed.

#### From downloaded file
Upon opening the downloaded file, VS2019 (Pro, Enterprise, Community) is listed in the dialog.

#### From Gallery
The Bridge project is not listed at all.

#### From downloaded file
The VS2019 entry is grayed out or not listed (other/older versions of Visual Studio should be listed if present and Bridge extension is not installed on them).

**Comment by fabriciomurta** [comment]
The package is ready, and works with VS2019 both executing the .vsix file or from the gallery (tried running a local copy of the gallery).

This MS article helped getting the right settings in: [How to upgrade extensions to support Visual Studio 2019](https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/)

### Running a local VS Extensions Gallery

This is a suggestion for who's willing to help test the package in different Visual Studio versions, from the VS Gallery perspective. We'll go simple for just the standalone executable, so that the extension can be quickly set up and tested locally.

1. clone the github project: [sverrirs/vsgallery](https://github.com/sverrirs/vsgallery)
2. Open it (may be VS2019 or VS017 -- the solution file is `vsgallery.sln` in the root
3. Before attempting to build, right-click the solution entry in solution explorer and choose **Restore NuGet packages**
4. Close and re-open the solution (for some reason it didn't build at once at my side, at least)
5. Build the solution.
6. Right-click the **VsGallery** project and choose **Open Folder in File Explorer**
7. browse down to **bin/Debug** (or **Release** if you changed the default configuration)
8. create a directory named **vsixStorage** and place the updated Bridge VSIX file in there.
9. the process will listen in port 5100 by default, you can change that by editing the **config.ini** file in the same directory -- it should be present when you build the project
10. run the vsgallery.exe -- it will display a console window with the status of the standalone server (it will log retrieves there)
11. Open/switch Visual Studio 2019 + choose "continue without code"
12. Go to **Tools** > **Options** and switch down to the **Extensions** in the categories pane to the left in the options dialog.
13. On **Additional Extension Galleries**, click **Add** and point it to `http://localhost:5100/feeds/atom.xml` (in the **URL** field).
14. Click **Apply**
15. Dismiss the Options dialog and go to **Extensions** > **Manage Extensions**
16. Expand in the category pane to the right the **Online** entry, then click the local repo you just set up (by default it is called **Local Repo**
17. Bridge package should show up if it is compatible with VS2019.

If it shows up, you can click **Download** and then close VS2019 to let it install the extension. Let us know if there's any issues installing it!

### Testing from a downloaded file

Just open it (better have VS2019 closed by then) and it should show VS2019 in the list of compatible target IDEs.

### Currently tested in:
- Microsoft Visual Studio Community 2019, 16.0.1,  Windows 64-bit, v10.0.17134.345

**Comment by Hopfenspirger** [comment]
Just as an Info: "From Gallery": I can not find your extention in VS2019 Enterprise.

**Comment by geoffreymcgill** [comment]
I think we're just waiting for some confirmation from the Community that the new vsix is working as expected when installed manually (ie. not through the Visual Studio Gallery).

**Comment by Hopfenspirger** [comment]
Installing the Bridge.NET.17.7.0-vs2019.vsix manually into VS 2019 Enterprise worked for me without problems. I can also create new Bridge.Net Class Libs with the Template and they compile...

**Comment by geoffreymcgill** [comment]
@Hopfenspirger – Thanks for the confirmation. The updated .vsix with Visual Studio 2019 support has be published to the [Visual Marketplace](https://marketplace.visualstudio.com/items?itemName=BridgeNET.BridgeNET).
