### ISSUE TITLE
Guid parsing is slow

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#3915]
### See Also
https://forums.bridge.net/forum/community/help/6103-newtonsoft-json-jsonconvert-deserializeobject-is-slow

**Comment by ChrML** [comment]
Great job! Have noticed it earlier and was about to post an issue. Thanks for fixing.

**Comment by fabriciomurta** [comment]
The final performance makes deserialization speed close to the serialization's. The optimization will make it to the next Bridge release (see assigned milestone).
