### ISSUE TITLE
BridgeDotNet  Supported Microsoft Packages

### ISSUE THREAD

**Issue by pavan1009** [bridgedotnet/Bridge#3922]
I am new here and I am trying to convert my c# code to JS using bridge.net and facing an issue please help...
in my code need ms pkg "using Microsoft.Extensions.PlatformAbstractions" which is not supported by bridge.net (17.7.0.0)

Deck link : https://deck.net/51e9ce554de8091cd496f34e78905b2c

i am getting error mscorlib is not found.

Is System.AppContext is not supported in Bridge.Net?

**Comment by ChrML** [comment]
I think you need to do a different approach to port your application. By finding alternative ways to solve the problem you need to solve. I don't see this as a Bridge.NET issue, but this could probably be discussed in the forums.

Browser applications have no concept of filesystems, hence BaseDirectory has no meaning. 

PlatformAbstractions is an abstraction made my Microsoft, but it seems to loose its relevance as it's gradually being replaced by better abstractions in .NET Core. I don't think we will see AppContext showing up in Bridge.NET ever, but we could probably see app domains in the future.
