### ISSUE TITLE
Convert third party library(C# dlls) in bridge.net 

### ISSUE THREAD

**Issue by pavan1009** [bridgedotnet/Bridge#3926]
Can we convert third party c# library(dlls) into bridge .net JS code directly ?

**Comment by geoffreymcgill** [comment]
Converting a .dll to .js is not currently supported by Bridge.NET.

**Comment by pavan1009** [comment]
One more thing i would like to ask you...
system.reflection is not fully supported in bridge.net as in c#
for example :
![image](https://user-images.githubusercontent.com/20498176/56486848-c1f06380-64f6-11e9-92c7-4a50ed430d97.png)

 public Assembly Load(string assemblyName)
   {
         return Assembly.Load(new AssemblyName(assemblyName));
   }

AssemblyName class is not available in bridge.net library.
how can we resolve this in bridge.net project?

**Comment by geoffreymcgill** [comment]
Unfortunately, this functionality is not supported by Bridge.

**Comment by pavan1009** [comment]
Is there any other approach to fix this?

**Comment by geoffreymcgill** [comment]
We (Bridge Team) do not have the resources (time + money) available to add this feature, but having the community submit a pull request with support for this feature is possible. 

Once a pull request is created, we could review and test. If everything looks good at that point, we could include in the next release of Bridge.

**Comment by pavan1009** [comment]
Is BridgeDotnet have support for "System.Runtime.Serialization.Formatters.Binary" ?
if not then is there any alternative ?
![image](https://user-images.githubusercontent.com/20498176/56583850-247d5880-65f8-11e9-867c-df7d19906471.png)

![image](https://user-images.githubusercontent.com/20498176/56583875-33640b00-65f8-11e9-8da2-1a590388a3bb.png)
