### ISSUE TITLE
String Comparison issue with enum emit

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#393]
http://forums.bridge.net/forum/bridge-net-pro/bugs/550-stringcomparison-issue

    C#
    string a = "testa";
    string b = "testa";
    bool result = a.Equals(b, StringComparison.InvariantCultureIgnoreCase);

    JS
    var result = Bridge.equals(b, 3); <-- should be (a, b)

**Comment by vladsch** [comment]
Bridge has no `Equals` method which supports `StringComparison`, So, the above code is not compilable at all. How did you get js code?

**Comment by DaniilVeriga** [comment]
Most likely, via [Live Bridge](http://live.bridge.net/#504b988088e66091e1a3). Recently, we have noticed a couple of issues in Live Bridge. For example, it can transpile the code without compilation. We are already working on that.
