### ISSUE TITLE
Generic array allocation unreasonably slow

### ISSUE THREAD

**Issue by c0pperdragon** [bridgedotnet/Bridge#3930]
When allocating an array using a generic type parameter,  the allocation is much slower than necessary. After a short look at the created code, I suspect that the default value for the type is determined for each individual array element, which has a considerable performance overhead. 
In contrast, when creating an array with 0 elements, and resizing it afterwards, everything runs by an order of magnitude faster. There this default value is only queried once and used for the whole array. 
Fixing this issue may also speed up the collections library.

### Steps To Reproduce

https://deck.net/9d47f4a62abf9957bf83c70b3c759304

```csharp
using System;
using System.Diagnostics;

public class Program
{
    public static void Main()
    {
        test("int alloc    ", false, false);
        test("int resize   ", false, true);
        test("string alloc ", true, false);
        test("string resize", true, true);
    }
    
    static void test(string label, bool reftype, bool resize)
    {
        Stopwatch sw = new Stopwatch();
		sw.Start();
        for (int i=0; i<1000; i++)
        {
            if (reftype) Alloc<string>(10000,resize);
            else         Alloc<int>(10000,resize);
        }            
        sw.Stop();
        Console.WriteLine(label+" "+sw.ElapsedMilliseconds+" ms");     
    }
    
    static T[] Alloc<T>(int len, bool resize)
    {
        if (resize)
        {   T[] a = new T[0];
            Array.Resize(ref a, len);
            return a;
        }
        return new T[len];    
    }
}
```

### Expected Result

All execution times should be in a similar range

### Actual Result

```js
int alloc     765 ms
int resize    62 ms
string alloc  571 ms
string resize 99 ms
```

**Comment by vladsch** [comment]
Thanks for the info. The performance will be improved for primitive and reference types. But structures will have the same performance because a structure must be created for each array element.

**Comment by fabriciomurta** [comment]
Before improvement:
```
int alloc     985 ms
int resize    30 ms
string alloc  1031 ms
string resize 26 ms
```

After improvement:
```
int alloc     35 ms
int resize    30 ms
string alloc  35 ms
string resize 27 ms
```

Looks like at least for the "intended audience" (non-structures), the performance is now pretty close to what is the "resize" test.

The improvement seems stable enough to go to next Bridge release (according to assigned milestone).
