### ISSUE TITLE
Enhance bridge via cashing

### ISSUE THREAD

**Issue by miladsadeghi72** [bridgedotnet/Bridge#3931]
Bridge.js is about 1.5 megabyte
So if we using standard http based apps then we have big problem in performace

The problem is we need to download bridge.js file every time where page loading

Do you have any plan for cashing that? Or cashing hole project?

**Comment by geoffreymcgill** [comment]
Use **bridge.min.js** as it should be 60% smaller. 

The browser should automatically cache the static .js file. Bridge cannot control whether the .js file is cached or not, that is a function of your app, server, and browser.

**Comment by geoffreymcgill** [comment]
Another option is to point to our CDN versions of the Bridge .js distribution files using https://speed.bridge.net.

The CDN files should be automatically sent using gzip compression and will be cached by the client browser.

Hope this helps.

**Comment by geoffreymcgill** [comment]
Original issue by @miladsadeghi72:

Bridge.js is about 1.5 megabyte
So if we using standard http based apps then we have big problem in performace

The problem is we need to download bridge.js file every time where page loading

Do you have any plan for cashing that? Or cashing hole project?
