### ISSUE TITLE
The Asynchronous Programming wiki page is out of date

### ISSUE THREAD

**Issue by Morgawr** [bridgedotnet/Bridge#3938]
I just spent about an hour trying to figure out how to do async programming trying to follow the steps outlined in https://github.com/bridgedotnet/Bridge/wiki/asynchronous-programming

It seems that the documentation references some methods that do not exist (DateTime.Now.GetTime(), HeadingElement, ParagraphElement, etc). I found the deck.net code at http://deck.net/async which seems to have the correct code, but it took me way too long (I didn't think about looking at deck.net, thinking it was a problem in my setup in VSCode and jQuery version).

The correct properties/methods should be DateTime.Now.Ticks, HTMLHeadingElement, HTMLParagraphElement, etc etc

**Comment by geoffreymcgill** [comment]
Hi @Morgawr – Thank for pointing out the issue. If you have a few minutes, please feel free to revise the wiki document with the correct code samples:
https://github.com/bridgedotnet/Bridge/wiki/Asynchronous-Programming/_edit
