### ISSUE TITLE
Reflection allows setting non-nullable properties to null

### ISSUE THREAD

**Issue by ChrML** [bridgedotnet/Bridge#3939]
**Bug**
Reflection (specifically PropertyInfo.SetValue) allows setting a non-nullable property to null. This may cause the program to fail at a later point where the programmer expects that this property can never be null.

Such non-nullable property may be a struct, such as DateTime. See example below.

**Note**
.Net Framework doesn't throw when attempting to change the property to null either. It resets the valuetype (struct) to its default zero-ed value (default(T)).

This behaviour is documented here: https://docs.microsoft.com/en-us/dotnet/api/system.reflection.propertyinfo.setvalue?view=netframework-4.8
> If the property type of this PropertyInfo object is a value type and value is null, the property will be set to the default value for that type.

### Steps To Reproduce

https://deck.net/29c77883acfccdff9fea57ab1056af97

```csharp
// Reported by: Christian "ChrML" Lundheim - 30.04.2019

public class Program
{
    public static void Main()
    {
        // Create the test- class with a non- nullable property.
        Test test = new Test();
        Console.WriteLine($"NonNullable.Year = {test.NonNullable.Year}");
        
        // Use reflection to set the non-nullable property to null.
        //Program.NonNullable = null;		// This will not compile because NonNullable cannot be null.
        PropertyInfo propNonNullable = test.GetType().GetProperty("NonNullable");
        propNonNullable.SetValue(test, null);
        
        // Program will fail later because nobody expects that NonNullable can be null.
        Console.WriteLine($"NonNullable.Year = {test.NonNullable.Year}");	// Crash
    }
}


public class Test
{
    public DateTime NonNullable {get;set;} = DateTime.Now;
}

```

### Expected Result

```
NonNullable.Year = 2019
NonNullable.Year = 1
```
(tested on .NET Framework)

### Actual Result

```
NonNullable.Year = 2019
System.Exception: TypeError: Cannot read property 'kind' of null
```

**Comment by danfma** [comment]
Hey @ChrML,

Usually, reflection is a hacking feature. You can't force the compiler to enforce that because you're breaking the rules. For example, you can get/set private and protected properties and methods from any object.

So, in my opinion, this is not an error. Just a misusage of the reflection API.

**Comment by ChrML** [comment]
Hey @danfma,

I strongly and respectfully disagree.

Reflection is NOT hacking. It's a very central and essential part of. NET. It's used for databinding to controls, serialization, property editors, marshalling etc... There is a reason it was invented, and further abstracted by the TypeDescriptor system. It's essential for any kind of dynamic/non-hardcoded behaviour.

And this is an error. Because MSDN clearly specifies how null should work for non-nullable properties, while Bridge.NET behaves differently than the documentation says.

Best regards, 
Christian Lundheim

**Comment by geoffreymcgill** [comment]
This issue has been flagged as a defect and we'll try our best to fix in time for the upcoming Bridge 17.8.0 release. We'll keep this thread updated with our progress.

**Comment by danfma** [comment]
> Hey @danfma,
> 
> I strongly and respectfully disagree.
> 
> Reflection is NOT hacking. It's a very central and essential part of. NET. It's used for databinding to controls, serialization, property editors, marshalling etc... There is a reason it was invented, and further abstracted by the TypeDescriptor system. It's essential for any kind of dynamic/non-hardcoded behaviour.
> 
> And this is an error. Because MSDN clearly specifies how null should work for non-nullable properties, while Bridge.NET behaves differently than the documentation says.
> 
> Best regards,
> Christian Lundheim

Hey, man! No problem with your definition or discordance, we're here to discuss. By the way, when I say that it is a hack it was because usually, you can break some rules of the language when using reflection. For example, set a property of a not accessible or protected field or method. And I saw that link later, you're right about it. :)

**Comment by geoffreymcgill** [comment]
A pull-request for this issue has been created. Our plan is to include the fix in the upcoming Bridge 17.8.0 release.

**Comment by ChrML** [comment]
Hey @danfma,

Yep, reflection can be abused. But one shouldn't. 

I use reflection a lot, but I have never used it for "cheating". Here are my uses on Bridge.NET:
- TypeDescriptor implementation 
- XML serialization/deserialization
- PropertyGrid usercontrol (lets users display and config classes and structs)
- DataGridView and IBindingList implementation (sorting, filtering and viewing property values)
- Applying XML configuration

Never used reflection to do anything that could not be accomplished with ordinary (hard)coding. Reflection helps generalizing things like auto-generating an UI for an implementation that would otherwise need specialized code.

Best regards Christian

**Comment by ChrML** [comment]
Thanks @geoffreymcgill !!

**Comment by fabriciomurta** [comment]
Removed 'area-datetime' as this issue is not related to it at all:
- [Deck](https://deck.net/90a9e39191e0e8a5cab2c260bc61bfac)
- [Dotnet Fiddle](https://dotnetfiddle.net/3Vv7GL)

```
using System;
using System.Reflection;
					
public class Program
{
    public static void Main()
    {
        // Create the test- class with a non- nullable property.
        Test test = new Test();
        Console.WriteLine(test.NonNullable);
        
        PropertyInfo propNonNullable = test.GetType().GetProperty("NonNullable");
        propNonNullable.SetValue(test, null);
        
        // Program will fail later because nobody expects that NonNullable can be null.
        Console.WriteLine(test.NonNullable);	// Crash
    }
}


public class Test
{
    public Test()
    {
        NonNullable = 6;
    }
    public int NonNullable { get; set; }
}
```

**Comment by fabriciomurta** [comment]
The provided fix is going to make it to the upcoming Bridge release (see assigned milestone).
