### ISSUE TITLE
Installation in VS2017 fails

### ISSUE THREAD

**Issue by WolfgangWolf** [bridgedotnet/Bridge#3942]
Hello!

I only want to install the package "Bridge.Core 17.7.0" via NuGet-Packet-Manager in Visual Studio 2017 Community.

The installations fails with the following error message (translated Error-Message):
"The package "Bridge.Core 17.7.0" could not be installed. You try to install this package in a project, which is based on "MDD,Version=v8.1". But the package has no assembly reference or content file, which are compatible with this framework. Please refer to the package responsible/developer, to get further information."

So I do so and ask you for help... what can I do?
Thank you!

Best regards
Wolfgang

---
The Original Error-Message in German:
ERROR		Das Paket "Bridge.Core 17.7.0" konnte nicht installiert werden. Sie versuchen, dieses Paket in ein Projekt zu installieren, das sich auf "MDD,Version=v8.1" bezieht, das Paket enthält aber keine Assemblyverweise oder Inhaltsdateien, die mit diesem Framework kompatibel sind. Wenden Sie sich an den Paketersteller, um weitere Informationen zu erhalten.

**Comment by geoffreymcgill** [comment]
It appears Bridge cannot be installed into the project type you're using. Can you provide more details on the project type?

**Comment by WolfgangWolf** [comment]
It is a Javascript-Project: "Empty App (Apache Cordova)". 

Originally I want to install "cordova-sqlite-storage", which has the dependency to Bridge.

**Comment by geoffreymcgill** [comment]
Bridge can be installed into a C# Class Library project, .NET Framework only.

You can use the generated .js files from that C# Class Lib project in your Cordova app, but Bridge cannot be added to that project as a Reference. 

Hope this helps.
