### ISSUE TITLE
Wrong translation of Function(params string[] argNamesAndBody) ctor

### ISSUE THREAD

**Issue by kosmab** [bridgedotnet/Bridge#3948]
https://deck.net/578bf07c27d76cd0023b554acffab4c9

```csharp
public class Program
{
    public static void Main()
    {
        string[] a1 = new string[]{"a", "(1)"};        
       	Function fp1 = new Function(a1);
    }
}
```

### Expected Result

valid object fp1

### Actual Result
fails during execution with exception: "System.Exception: TypeError: Function.apply is not a constructor"

**Comment by geoffreymcgill** [comment]
Thanks for reporting. Can you edit your issue and supply the **Expected Result** and **Actual Result** with the JavaScript syntax for both?
