### ISSUE TITLE
await on an already completed Task can abort async method

### ISSUE THREAD

**Issue by c0pperdragon** [bridgedotnet/Bridge#3951]
When using await on a Task object that is already completed, the javascript code nevertheless calls the function "continueWith" on the Task. This function then in turn immediately calls back to execute the continuation. This causes an ever-deeper nesting of function calls until some overflow happens and the execution terminates. 
The correct behavior in this case would be to directly test the Task object for completion and directly continue execution in the original state machine function. This is also the way it is implemented by C#.

### Steps To Reproduce

https://deck.net/2a3086e6e46a00529d010cf7b441ddb4

```csharp
public class Program
{
    public static void Main()
    {
        int[] count = new int[1];
        Task t = TightLoop(count);
        Console.WriteLine("Iterations: "+count[0]);
    }
    
    public static async Task TightLoop(int[] count)
    {
        Task finished = Task.FromResult<String>(null);
        for (int i=0; i<10000; i++)
        {	await finished;
         	count[0]++;
        }
    }
}
```

### Expected Result

```js
Iterations: 10000
```

### Actual Result

```js
Iterations: 2224
```

**Comment by geoffreymcgill** [comment]
Thanks for reporting. We're going to investigate and try to get this scenario working in time for the upcoming Bridge 17.8.0 release.

**Comment by fabriciomurta** [comment]
The pull request addressing this issue works fine and will be included next Bridge release (see assigned milestone).
