### ISSUE TITLE
Internal method Task.continueWith contains dead functionality

### ISSUE THREAD

**Issue by c0pperdragon** [bridgedotnet/Bridge#3955]
After having a peek at the javascript code, the implementation of `Task.continueWith` does some quite unnecessary things:  It creates a **TaskCompletionSource** object together with its companion Task object and installs some callback handlers on it. 

Then it does some different things that seem to actually make sense (install the callback into the original Task object)

At the end, it returns the newly created **Task** object.
After a quick scan through the code, this return value seems nowhere to be actually used, neither is the **TaskCompletionSource**.

By my guess, this code is the remainder of some earlier implementation and was forgotten because it does no harm besides slowing down the operation.

**Comment by geoffreymcgill** [comment]
Thanks. We will try our best to review and improve this scenario before the upcoming Bridge 17.8.0 release.

**Comment by vladsch** [comment]
According to docs
https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.continuewith?view=netframework-4.8

ContinueWith should return Task (and investigation of source code in .NET shows that new created Task is returned from ContinueWith implementation).

For example, we have the following unit test which shows that we have to return new Task from ContinueWith
```cs
bool cb1Invoked = false, cb2Invoked = false;
        var tcs = new TaskCompletionSource<int>();
        Task task = tcs.Task;

        Assert.AreEqual(TaskStatus.Running, task.Status, "task should be running at point 1");

        var t1 = task.ContinueWith(t =>
        {
            cb1Invoked = true;
            throw new Exception("Test");
        });

        var t2 = task.ContinueWith(t =>
        {
            cb2Invoked = true;
        });

        tcs.SetResult(0);

        Task.Run(() =>
        {
            Assert.AreEqual(TaskStatus.RanToCompletion, task.Status, "task status should be RanToCompletion");

            Assert.AreEqual(TaskStatus.Faulted, t1.Status, "t1 status should be Faulted");
            Assert.True(cb1Invoked, "Callback 1 should have been invoked");

            Assert.AreEqual(TaskStatus.RanToCompletion, t2.Status, "t2 status should be RanToCompletion");
            Assert.True(cb2Invoked, "Callback 2 should have been invoked");
        });
```

**Comment by geoffreymcgill** [comment]
Closing this issue but if further details are provided we will re-open and continue our investigation.
