### ISSUE TITLE
[Enum(Emit.StringNameLowerCase)] appears to be ignored with default parameter values

### ISSUE THREAD

**Issue by ProductiveRage** [bridgedotnet/Bridge#3958]
I wanted to use `[Enum(Emit.StringNameLowerCase)]` when integrating with a third party library (so that I would have an enum in C# that was translated into a string in JS) but I think that there is a bug relating to the use of default parameter values - when a default parameter value needs to be used, it doesn't check the enum type of this attribute and so it will use a numeric value as the default instead of a string.

To illustrate:

```csharp
public class Program
{
    public static void Main()
    {
         // returns "euclidean" - correct, YAY!
        Console.WriteLine(GetOptions(MetricOptions.Euclidean));

        // returns 0 - incorrect :(
        Console.WriteLine(GetOptions());
    }
    
    static object GetOptions(MetricOptions metric = MetricOptions.Euclidean) => metric;
    
    [Enum(Emit.StringNameLowerCase)]
    enum MetricOptions { Euclidean }
}
```

Also available at https://deck.net/18c0d43704f353344f41d5d7666e8d2c

Thanks for your help!

**Comment by geoffreymcgill** [comment]
Thanks for pointing out this issue. We will review and try to determine what's going on here.

**Comment by geoffreymcgill** [comment]
A fix for this issue has been submitted. Once final review and testing are complete, the fix should be included in the upcoming Bridge 17.8.0 release.

**Comment by ProductiveRage** [comment]
Can't argue with that turnaround time, great stuff! :)

**Comment by fabriciomurta** [comment]
The fix looks good and should make it to the next Bridge version!
