### ISSUE TITLE
Implementation of await should not call ContinueWith

### ISSUE THREAD

**Issue by c0pperdragon** [bridgedotnet/Bridge#3963]
After checking what the compiler does, I found that the implementation of 'await' is unnecessarily slow. It is mainly calling the continueWith method of Task which in turn does quite some additional stuff besides just installing the callback in its list. 
As removing this functionality there is not possible, because it is part of the Task API (see #3955), it makes sense to provide and use a dedicated light-weight version ('attachContinuation' or something like that). 
When the completion test for the Task is pulled out into the method that uses 'await'  (see #3951), this is really only a very simple method that would not have to call out to any other code itself.

**Comment by fabriciomurta** [comment]
Thanks for the heads up. There's always room for improvement and pointing out areas that "are hurt" is really helpful!

**Comment by fabriciomurta** [comment]
We got a fix for this, but as we don't really have numbers to compare (some benchmark etc), there's not much of a measure of "how much" this improved. But now with specialized code to do the task, it should improve, in the least. If curious about the change, take a look in the pull request above.

The reviewed approach wil make it to the next Bridge release.
