### ISSUE TITLE
Cant catch TypeException

### ISSUE THREAD

**Issue by colderlord** [bridgedotnet/Bridge#3976]
I wrote some code, that throws `TypeException`, but `catch` identified exception like `NullReferenceException`

### Steps To Reproduce

https://deck.net/eafda9fded5a6709e08552dca8974015

```csharp
public class Program
{
    public static void Main()
    {
        try
        {
            ThrowTypeException();
        }
        catch(TypeException ex)
        {
            Console.WriteLine(ex.GetType().FullName);
        }
        catch(Exception ex)
        {
            Console.WriteLine(ex.GetType().FullName); // throw here
        }
    }
    
    public static void ThrowTypeException()
    {
        throw new TypeException("Type Ex");
    }
}
```

### Expected Result

```
TypeException
```

### Actual Result

```
NullReferenceException
```

**Comment by geoffreymcgill** [comment]
The **TypeException** class should have been named **TypeError** class as it's a JavaScript native Error class and not a .NET Exception class. 

The **TypeException** (should be **TypeError**) class is in the Bridge.Html5 repo:

https://github.com/bridgedotnet/Frameworks/blob/master/Html5/Errors/TypeError.cs

There is no **TypeException** class in C# and the **Bridge.Html5.TypeException** class would not inherit from **System.Exception**.

The best I can recommend is to not use **Bridge.Html5.TypeException** class, or don't treat it as a .NET Exception class. 

It should be renamed to **TypeError**. I created the following issue to track that change:

https://github.com/bridgedotnet/Frameworks/issues/91

Hope this helps.
