### ISSUE TITLE
Any API documentation of .NET object library available?

### ISSUE THREAD

**Issue by dukc** [bridgedotnet/Bridge#3987]
Is there any good way to get an overview of what parts of .NET API are implemented in Bridge.NET? The homepage does not provide any obvious link to such documentation, nor can I find any coming with the installation. So far, I've just referred to docs.microsoft.com and hoped the implementation matches, but is there a better way?

In fact, I don't even know what version of .NET API Bridge.Net tries to follow!

**Comment by dukc** [comment]
Oh, just realized I can read `<project>/packages/Bridge.Core.1x.x.x/lib/net40/Bridge.xml` using text editor and it will act as servicable documentation. But since it's XML, I suppose it ought to be read by some other program. What program exactly, and can it be run from the system terminal (I mean, without opening an IDE)?

**Comment by fabriciomurta** [comment]
There is an user-contributed tool that was [shared at some point in our gitter channel](https://gitter.im/bridgedotnet/Bridge?at=59ff59285a1758ed0f907a10). I'm not sure how up-to-date it would be, but it's worth a try. It is a direct comparison between what is and what is not in both frameworks.

Other than that, Bridge aims to follow what's in .NET API. So you can rely on their documentation, and report here (please do a search in existing issues beforehand) if there's no open requests for that feature.

Sometimes there may be limitations that made it unable to be ported in, but most times it is just that we weren't aware of the need of that class/method, and we prioritize development on what's demanded by the community.

Well, we also prioritize merging pull requests of features and fixes provided by the community, by the way!

**Comment by fabriciomurta** [comment]
@michaelcheers message back then was:
> I made a similar tool
> you can see here: https://michaelcheers.github.io/ReflectionComparison-Results/result.html

**Comment by geoffreymcgill** [comment]
The result of the above link appears to be somewhat out of date. I do believe more of the API is now supported by Bridge.

**Comment by michaelcheers** [comment]
It hasn't been updated for a while.
