### ISSUE TITLE
Resource larger than 1MB can not be extracted by dependent project

### ISSUE THREAD

**Issue by ProductiveRage** [bridgedotnet/Bridge#3989]
I have Project A and Project B where B references A.

Project A has a web font resource built into it (using the [resources](https://github.com/bridgedotnet/Bridge/wiki/global-configuration#resources) bridge.json option).

Project A builds correctly and the resource appears in the dll. Project B will not build, there is an exception thrown while Bridge tries to extract the resource out of the dll -

> **System.ArgumentException:** Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.

I ran the Bridge resource-extracting code in isolation and reproduced the issue:

![image](https://user-images.githubusercontent.com/742348/58938914-36fdbc80-8776-11e9-915d-e1a182c36287.png)

The approach of looping and reading chunks of data used to be common (eg. [https://stackoverflow.com/a/1080445](https://stackoverflow.com/a/1080445)) but the stream's Read method's summary comment mentions:

> Exceptions:
>   T:System.ArgumentException:
>   The sum of offset and count is larger than the buffer length.

.. and this seems to be the condition that we're falling into (file is approx 1.5MB, the second read loop will specify an offset of 1024 * 1024 and a count of 1024 * 1024 and the sum of these two values is larger than the size of the buffer).

.NET 4 made this sort of operation simpler when the CopyTo method was added to the Stream type. That could make this code simpler and more reliable.

**Comment by fabriciomurta** [comment]
Thank you, there's not much to discuss about this issue, you already said it all. :)

**Comment by fabriciomurta** [comment]
The pull request has been merged and the fix is making it to next Bridge version.
