### ISSUE TITLE
Optional Parameters of Enum Types are not generated correctly 

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#3994]
Default Value is missing resulting in a syntax error in js code.

### Steps To Reproduce

https://deck.net/3e3dc8f8816cc012ef19116cded7ba61

```csharp
public class Program
{
    public void TestFnc(TestEnum testEnum = TestEnum.Test) { }
}

public enum TestEnum
{
    Test,
    Test01
}
```

### Expected Result

```js
TestFnc: function (testEnum) {
                if (testEnum === void 0) { testEnum = 0; }
            }
```

### Actual Result

```js
TestFnc: function (testEnum) {
                if (testEnum === void 0) { testEnum = ; }
            }
```

### See Also
https://forums.bridge.net/forum/community/help/6225-optional-paramters-of-enum-types-are-not-generated-correctly-in-version-17-8

**Comment by fabriciomurta** [comment]
The pull req looks great and should be included next Bridge release (see assigned milestone).
