### ISSUE TITLE
can't build in vs2019

### ISSUE THREAD

**Issue by lightszero** [bridgedotnet/Bridge#3999]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		命令“
REM Run Bridge Compiler for the project
"D:\git\lightsfork\Bridge\Compiler\Builder\bin\Debug\bridge.exe" -p "D:\git\lightsfork\Bridge\Bridge\Bridge.csproj" -b "D:\git\lightsfork\Bridge\Bridge\bin\Debug\Bridge.dll" -cfg "Debug" --platform "AnyCPU"
”已退出，代码为 1。	Bridge.PostBuild			

严重性	代码	说明	项目	文件	行	禁止显示状态
错误		Microsoft.Build.Exceptions.InvalidProjectFileException: The tools version "15.0" is unrecognized. Available tools versions are "2.0", "3.5", "4.0".  D:\git\lightsfork\Bridge\Bridge\Bridge.csproj	Bridge.PostBuild	D:\git\lightsfork\Bridge\PostBuild\EXEC

**Comment by geoffreymcgill** [comment]
A fix to support VS 2019 has been submitted and will be included in the next Bridge release.

https://github.com/bridgedotnet/Bridge/pull/3998

## See Also

- #3997

**Comment by lightszero** [comment]
good to known.

**Comment by lightszero** [comment]
good to known.
