### ISSUE TITLE
Add support for the System.Version class

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#400]
A (small) vote for supporting the Version class. I'm trying to build a Bridge/ASP.NET WebAPI replacement for PoSh deployment scripts, and there's lots of version numbers flying around. Being able to handle Versions in the client properly would be handy (eg. knowing which versions are newer/older).

Not a big deal if you think this is out of scope; but thought it was worth asking :)

**Comment by LeonidVeriga** [comment]
Can you please clarify how you would use `Version` on the client side. Is it just an instance to store `Major`, `Minor` etc properties?

**Comment by DanTup** [comment]
That, and also sorting/comparing. Eg. being able to check:

```
// Comparing versions
if (oldVer < newVer)

// Sorting
myReleases.OrderBy(r => r.Version)
```

I remember there being something slightly strange about comparison (eg. if you create `new Version(1, 1, 1)` vs `new Version(1, 1, 1, 0)`).. Looking at [the source](http://referencesource.microsoft.com/#mscorlib/system/version.cs,0c15515dfe051d35) I think it's just that build/revision are treated as `-1` if not specified.

**Comment by DanTup** [comment]
I guess `Version.Parse` would be handy too, though I'm not sure anything of mine specifically needs it (since the JSON serialised versions come back as an object with the 4 properties, so I could just use the constructor during deserialisation).

**Comment by LeonidVeriga** [comment]
Hi @DanTup!

We implemented the Version class. The implementation was to take .Net source code, translate it with Bridge, ammend the js output a little, write some tests and that's it :)
Please check and let us know it works as expected for your use case.
