### ISSUE TITLE
Namespace 'System.Collections.Generic' has no exported member 'IReadOnlyList$1

### ISSUE THREAD

**Issue by lidermanrony** [bridgedotnet/Bridge#4006]
System.Collections.Generic.IReadOnlyList$1 is nowhere to be found in generated bridge.d.ts file even though reference to it gets generated in the main d.ts file for the project (in case the C# code contains an IReadOnlyCollection.

This causes compilation errors in web applications such as create-react-app.

### Steps To Reproduce
just open any bridge.d.ts file and search for IReadOnlyList. it won't be there

### Actual Result
![image](https://user-images.githubusercontent.com/199509/59533332-03badc00-8ea0-11e9-97d9-8eb990ec2349.png)

**Comment by geoffreymcgill** [comment]
Thanks for the report. We will investigate right away, fix, and with some luck, we will include the fix in the upcoming Bridge 17.9.0 release.

**Comment by lidermanrony** [comment]
btw, IReadOnlyDictionary$2 seems to be not defined as well.

**Comment by geoffreymcgill** [comment]
Thanks for the update. We're going to try and fix this issue this weekend and release 17.9.0 as soon as we can. Early next week will be the goal.

**Comment by fabriciomurta** [comment]
The [bridge.d.ts](https://github.com/bridgedotnet/Bridge/blob/88ab686e311d6d9a9b339f399e3a610f651d588d/Bridge/Resources/.typescript/bridge.d.ts) file was updated to be in sync with current Bridge API.

So far the change looks good to go to the next Bridge release.
