### ISSUE TITLE
Possible bad script generated when trying to use JSON.parse with a custom reviver

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#401]
This could be a bug, or just a request for help/advice ;)

I'm struggling to get JSON.parse to handle dates correctly. I'm trying to deserialise a class that has a DateTime on it (this class is shared between a WebAPI server and a Bridge client). The JSON representation just has the Date as a string but since my Bridge class is typed as DateTime I need the deserialisation to create a Date from (otherwise code like `myDate.ToLocalDateString()` compiles, but fails at runtime).

There's some info on this here:

https://weblog.west-wind.com/posts/2014/Jan/06/JavaScript-JSON-Date-Parsing-and-real-Dates

I've copied their JS, so I have a `window.JSON.dateParser` function. I would like to call it like this:

```
var myData = JSON.parse(json, window.JSON.dateParser);
```

So I created a class that looks like this:

```
static class JsonWithDates
{
	public static T Parse<T>(string json)
	{
		var parser = Script.Get<dynamic>("window.JSON.dateParser");
		return JSON.Parse<T>(json, parser);
	}
}
```

And I'm calling it like this:

```
var data = JsonWithDates.Parse<T>(http.ResponseText);
```

However, the JavaScript that gets output is a bit funky:

```
Bridge.define('MyScripts.Services.JsonWithDates', {
    statics: {
        parse: function (T) {
            return Bridge.fn.bind(this, function (json) {
                var parser = window.JSON.dateParser;
                return Bridge.merge(new (), JSON.parse(, ))(json, parser); // This is invalid syntax
            });
        }
    }
});
```

Is this a bug? Is there a better way to do what I want?
(Ideally, I'd like to convert their JS into C#, but I failed badly in my attempts!)

**Comment by LeonidVeriga** [comment]
Hi @DanTup! 

In your scenario Bridge does not handle `dynamic` parser.
Please update your `Parse` method (explicitly specify type for parser - `Delegate`):
```
static class JsonWithDates
{
    public static T Parse<T>(string json)
    {
        Delegate parser = Script.Get<dynamic>("window.JSON.dateParser");
        return JSON.Parse<T>(json, parser);
    }
}
```

Please let us know if it works for your use case (there is #98 so there is a chance it does not work as expected for custom types).

**Comment by DanTup** [comment]
This seems to output valid script now. However, it doesn't seem to work as I expect (the dates are still strings). However, it seems that JSON.parse is the native browser implementation, so I think this is an error on my part (calling `JSON.parse(json, window.JSON.dateParser)` in the console doesn't work, and I don't think any Bridge code is being run there), so I'll dig further.

Thanks!

**Comment by DanTup** [comment]
My problem was indeed unrelated to Bridge... the Regex copied from that page didn't allow for not having decimal points in the time (which is what .NET Web API was outputting) eg:

```
2014-02-01T09:28:56.321-10:00 // worked
2014-02-01T09:28:56-10:00 // did not work
```

I tweaked the regex and it now works fine :)

```
var reISO = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2}(?:\.\d*))(?:Z|(\+|-)([\d|:]*))?$/; // old
var reISO = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2}(?:\.\d*){0,1})(?:Z|(\+|-)([\d|:]*))?$/; // new
```

**Comment by LeonidVeriga** [comment]
Nice to hear you solved the problem)
