### ISSUE TITLE
[FileName("outputfile")] attribute causes the metadata to be exported to the wrong file

### ISSUE THREAD

**Issue by ChrML** [bridgedotnet/Bridge#4010]
**Description**
Using the Bridge. FileName attribute seems to cause some issues with meta-data output for reflection. The metadata will be output to a different file than the attribute specifies.

**Example**

```csharp
[FileName("outputfile")]
class Test 
{
    public int Item {get;}
}
```
Will generate the following files:

- default.js -> All other code that does not have the FileName- attribute
- default.meta.js -> All other metadata, AND the metadata of the class "Test"
- outputfile.js -> The code/implementatino of class "Test"
- outputfile.meta.js -> Is not generated at all

Observe that the metadata for class "Test" is still in default.meta.js, while outputfile.meta.js does not exist at all.

### Steps To Reproduce
Not reproducable on Deck.NET.

**Comment by fabriciomurta** [comment]
No matter how I look at it, it really seems off. Hitting 'defect' label.

**Comment by fabriciomurta** [comment]
This introduces a breaking change as the emitted file structure will be (potentially) different upon building Bridge after the proposed fix is effective in the translator.

**Comment by fabriciomurta** [comment]
Reviewed and merged, will make it to the next Bridge release!
