### ISSUE TITLE
Lost kind of DateTime for Date property

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#4014]
Probably it can be regression (I cannot check).

### Steps To Reproduce

https://deck.net/6f0314132592c64c13b048f2b8d8ef47

```csharp
    internal class Program
    {
        private static void Main(string[] args)
        {
            DateTime date1 = DateTime.SpecifyKind(DateTime.Today, DateTimeKind.Utc);

            Console.WriteLine(date1.Kind.ToString());

            DateTime date2 = date1.Date;

            Console.WriteLine(date2.Kind.ToString());
        }
    }
```

### Expected Result

```
Utc
Utc
```

### Actual Result

```
Utc
Unspecified
```

**Comment by geoffreymcgill** [comment]
Thanks for reporting. 

Looks like the following line needs to be added into the `getDate` function:

https://github.com/bridgedotnet/Bridge/blob/master/Bridge/Resources/Date.js#L1284

```js
dt.kind = kind;
```

We will fix and add to the next Bridge release. You can try locally to test if you want to confirm.

**Comment by fabriciomurta** [comment]
As good as fixed, and merged as well! Thanks for the report! To be included next Bridge release.
