### ISSUE TITLE
Class with 'extern' indexer is translated into invalid JS

### ISSUE THREAD

**Issue by ProductiveRage** [bridgedotnet/Bridge#4015]
The following C# -

```csharp
public class SomethingWithExternIndexer
{
    public extern int this[int index]
    {
        [Template("{this}[{index}]")] get;
    }
}
```

is translated into this JS:

```js
Bridge.assembly("Demo", function ($asm, globals) {
    "use strict";

    Bridge.define("Demo.SomethingWithExternIndexer", {
        methods: {
            getItem: function (index) null
        }
    });
});
```

which fails when it is parsed because of this line:

`getItem: function (index) null`

The error is:

> Uncaught SyntaxError: Unexpected token null

See [deck.net/7a54eb158f0efb2bca5dc61198d673ef](https://deck.net/7a54eb158f0efb2bca5dc61198d673ef).

I can work around it by adding an [External] attribute to the indexer like this:

```csharp
public class SomethingWithExternIndexer
{
    [External]
    public extern int this[int index]
    {
        [Template("{this}[{index}]")] get;
    }
}
```

It seems to be a problem specific to an indexed property, though. If I have a non-indexed property that uses the extern keyword and a [Template] attribute on the "get" then the property is completed excluded from the generated JS, as expected - eg.

```csharp
public class SomethingWithExternNameProperty
{
    public int Name
    {
        [Template("Whatever")] get;
    }
}
```

becomes:

```js
Bridge.assembly("Demo", function ($asm, globals) {
    "use strict";

    Bridge.define("Demo.SomethingWithExternNameProperty");
});
```

As I've identified a workaround, this isn't a critical issue but it is a bit of a nasty one that it's generating invalid JavaScript from valid C#.

**Comment by fabriciomurta** [comment]
Merged! The fix will make it to the next Bridge release!
