### ISSUE TITLE
System.Linq.Enumerable.from doesn't return null for null input - inconsistency with .NET

### ISSUE THREAD

**Issue by ProductiveRage** [bridgedotnet/Bridge#4019]
I would expect the following code to throw a null reference exception -

```
public class Program
{
    public static void Main()
    {
        int[] values = null;
        Console.WriteLine(
            string.Join(", ", values.Take(2).ToArray())
        );
    }
}
```

In .NET, it does (see [dotnetfiddle.net/jgPTW8](https://dotnetfiddle.net/jgPTW8)) but in Bridge it does not (see [deck.net/c4d7b63305796b555fe6ea078270b445](https://deck.net/c4d7b63305796b555fe6ea078270b445)).

**Comment by fabriciomurta** [comment]
Thanks for reporting the issue!

Your samples leave possibilities to a lot of places to be the culprit and I reduced the test case to Linq's `Take()` with this:

```csharp
public class Program
{
    public static void Main()
    {
        int[] values = null;
        Console.WriteLine("Taken:" + values.Take(2));
    }
}
```

Deck: https://deck.net/4632800c60a940f8fae7ce8f5acaaa84
Dotnet fiddle: https://dotnetfiddle.net/PEDUn0

**Comment by fabriciomurta** [comment]
The pull request has just been merged upstream! The fix will make it to our next public Bridge release.
