### ISSUE TITLE
Fix for Decimal.parse() uses API unsupported by IE11

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#4030]
The fix in 7f855bf4b9ad8713739b3025625c3614f5d40c63 introduced usage of `String.startsWith()` and `String.endsWith()`, which is not supported by IE11. 

`v.lastIndexOf("+", 0) === 0` should be used instead.

The fix for Decimal.Parse pertained issue #3982.

The issue with IE11 was reported thru gitter in [this message](https://gitter.im/bridgedotnet/Bridge?at=5d3a30c96ec2e14223edcc22).

### See Also

- Bridge forums' thread: [Bridge no longer working on IE11](https://forums.bridge.net/forum/bridge-net-pro/bugs/6256)

**Comment by fabriciomurta** [comment]
Adding #seealso section to original comment, as a thread was created in Bridge forums regarding this issue.
- Thread: [Bridge no longer working on IE11](https://forums.bridge.net/forum/bridge-net-pro/bugs/6256)

**Comment by hardhub** [comment]
I got the same trouble.

**Comment by fabriciomurta** [comment]
We have changed it so Bridge no longer references the unsupported methods in IE11; will be in effect next Bridge release (see attached milestone).
