### ISSUE TITLE
High memory usage in System.String.isNullOrWhiteSpace client-side method (and others)

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#4036]
If successive calls to `System.String.isNullOrWhiteSpace()` client-side method are made, it becomes noticeable the amount of memory, cumulatively used by Bridge due to probable isolate instantiations of the regex object via the [RegExp constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp).

Although this is something the garbage collector would handle, the overhead could be minimized by reusing the regex instance instead of recreating it every call.

Issue originally reported on its pull request, #4035. The specific tooling used to extract the performance was not shared. The code shared relies in console commands instead of building from Bridge and binding to events. That approach actually narrows down possibilities for the leak source.

### Steps To Reproduce

The deck below reproduces the scenario with 1 million calls to the reported method every click of a button:

https://deck.net/accd0189e3ff59a613f90884fdd71ec6

```csharp
using System;
using Retyped;
using static Retyped.dom;

public class Program
{
    static void Main(string[] args)
    {
        // Create the Button
        var button = new HTMLButtonElement();

        // Set the Button text        
        button.innerText = "1M calls to IsNullOrWhiteSpace()";
        
        // Add a Bootstrap style        
        button.className = "btn btn-primary";

        var count = 1;
        
        // Add a click event handler        
        button.onclick += (e) => {
            var i = 0;
            while (i < 1000000) {
                String.IsNullOrWhiteSpace(button.innerText);
                i++;
            }
            
            count++;
        };
        
        // Add the button to the document body
        document.body.appendChild(button);
    }
}
```

### Expected Result

A much smaller memory footprint by the IsNullOrWhiteSpace calls.

### Actual Result

Considerable memory usage by IsNullOrWhiteSpace calls.

Profile result for one click in the trigger button, in the example above:
![image](https://user-images.githubusercontent.com/10730372/62386639-d947df80-b52e-11e9-80d5-64289a0a2412.png)

**Comment by ProductiveRage** [comment]
Slight nitpick: it's not a memory leak, to the best of my knowledge - I'm confident that the GC will tidy up all the references when it gets round to it, it's just that it's GC pressure that could be avoided.

**Comment by fabriciomurta** [comment]
Reviewed title and body of the issue based on your comment, thanks for the _"debias"_. Hopefully it is now more coherent.

**Comment by ChrML** [comment]
A different performance issue: String interpolation, the $"{Variable1} text {Variable2}" syntax, seems to use String.format() in Javascript.

String.format() seems very expensive in current implementation, so using string interpolation extensively seems to introduce a rather large performance overhead.

Shall I gather data on this and post as a separate issue?

**Comment by fabriciomurta** [comment]
@ChrML I think that would be simply awesome if you went in-depth with this issue (in a separate, dedicated issue), if you have it well defined in your mind.

If you had a suggestion on fixing it (as it seems you have), we'd be more than glad to review your pull request! Although it may sound as a tiny improvement, it being orthogonal (not negatively affecting other usage scenarios it currently does), there're only reasons for it to be implemented, in my opinion.

**Comment by fabriciomurta** [comment]
A snapshot of the "after"
![image](https://user-images.githubusercontent.com/10730372/62510613-083bab00-b7e6-11e9-8e42-b7a2bf29879f.png)

**Comment by fabriciomurta** [comment]
As good as merged, thanks again @ProductiveRage for another invaluable contribution!
