### ISSUE TITLE
CLI Installation wiped out my windows PATH

### ISSUE THREAD

**Issue by FortuneN** [bridgedotnet/Bridge#4041]
The only remaining entry is : C:\Program Files (x86)\Object.NET\Bridge.NET CLI

**Comment by fabriciomurta** [comment]
Hello, would you mind switching over to bridgedotnet/CLI#15 and, if possible, provide information that could help us solve this issue once and for all? I'm suspecting some characters in the PATH key is doing that, but it could be anything, we just can't reproduce this on our end.
