### ISSUE TITLE
Broken/Missing "Calling your code from JavaScript" section in Wiki

### ISSUE THREAD

**Issue by drcode** [bridgedotnet/Bridge#4051]
The wiki/docs are missing any information on calling bridge.net code from javascript- The provided hypertext link is a dead link. (note: this issue is specifically about js->bridge and not bridge->js, which is well documented)

### Steps To Reproduce

Go to https://github.com/bridgedotnet/Bridge/wiki

Click on "Calling your code from JavaScript"

### Expected Result

A description of this feature

### Actual Result

The information/page is missing.

**Comment by fabriciomurta** [comment]
As good as fixed, thanks for the heads up!
