### ISSUE TITLE
Simple arithmetic with Int64 and Int32 is broken

### ISSUE THREAD

**Issue by stgolem** [bridgedotnet/Bridge#4098]
See code samples below.

### Steps To Reproduce

https://dev.deck.net/6f6395eb9e2ba13278c7625104970083

```csharp
public class Program
{
    public static void Main()
    {
        long a = 2500000;
        long b = 7;
        
        long msg = (long)( a * (b / 100) );
        
        Console.WriteLine(msg);
    }
}
```

### Expected Result

```
Console writes: 175000
```

### Actual Result

```
Console writes: 0
```

### Remarks

Same behavior with `int a, int b`.
But when we declare `double b = 7` then is works fine.

**Comment by vladsch** [comment]
It is expected behavior, just check in native .NET application (internet division provides int, not double, that's why b / 100 result is 0)

**Comment by stgolem** [comment]
Sorry, my bad. Did not check real CLR behavior first. https://dotnetfiddle.net/vDqG9o
