### ISSUE TITLE
Math.PI and other constants are optimized away

### ISSUE THREAD

**Issue by gogglespisano** [bridgedotnet/Bridge#410]
In public static class Math

The const values of 0 can cause the compiler to optimize the code away.
        public const double E = 0;
        public const double LN10 = 0;
        public const double LN2 = 0;
        public const double LOG2E = 0;
        public const double LOG10E = 0;
        public const double PI = 0;
        public const double SQRT1_2 = 0;
        public const double SQRT2 = 0;

They should be static readonly values so the compiler will always use them.
        public static readonly double E;
        public static readonly double LN10;
        public static readonly double LN2;
        public static readonly double LOG2E;
        public static readonly double LOG10E;
        public static readonly double PI;
        public static readonly double SQRT1_2;
        public static readonly double SQRT2;

**Comment by vladsch** [comment]
Can you explain what such optimization can give you? Just not sure that I correctly undestood the sense of such change

**Comment by gogglespisano** [comment]
I had a formula like:
((2 * Math.PI) + xyz)

Since the compiler knows that Math.PI always equals 0, it reduced the (resulting JS) code to just
(xyz)

**Comment by vladsch** [comment]
ah, I see, very interesting catch. It will be fixed, thanks for the report

**Comment by LeonidVeriga** [comment]
`double.MinValue + 0` expression causes error `Number.MIN_VALUE.add is not a function` due to misprint in the const definition

**Comment by LeonidVeriga** [comment]
@gogglespisano the pull request is great. Can you please accept and sign our CLA before we accept the pull request.

Here what you need to know:
[Contributing document](https://github.com/bridgedotnet/Bridge/blob/master/CONTRIBUTING.md)
[CLA document](https://github.com/bridgedotnet/Bridge/blob/master/CLA.md)
[CLA signing form](https://docs.google.com/a/object.net/forms/d/12IAxRmWCk2vD-M3mj4d0ihztqKoiREpRRSVq4pEk0-k/viewform?c=0&w=1)

**Comment by gogglespisano** [comment]
I can't find USA in the CLA form country dropdown?

**Comment by LeonidVeriga** [comment]
USA should be in the list now. Please check.

**Comment by geoffreymcgill** [comment]
I have updated your CLA record, no need to do anything.

**Comment by geoffreymcgill** [comment]
The list of countries was added by a Google Spreadsheets plugin. For some reason the plugin must have been missing the item `United States of America`. Thanks for pointing out the form issue. I have added the item.

**Comment by LeonidVeriga** [comment]
As a side effect of changing `const` to `readonly`, code referencing `Math`, `decimal`, `double` and `float` constants should also be changed to `readonly`.

**Comment by geoffreymcgill** [comment]
Oops, I confused @gogglespisano CLA record with another USA user. Currently @gogglespisano has not signed the CLA.

**Comment by gogglespisano** [comment]
signed.

**Comment by LeonidVeriga** [comment]
@gogglespisano Thank you for signing the CLA and the pull request. The fix is merged in will be release in the next 1.9 release.
