### ISSUE TITLE
Support for .NET Core SDK?

### ISSUE THREAD

**Issue by AlseinX** [bridgedotnet/Bridge#4114]
Although this is to compile C# to Javascript which does not run on .NET Framework, there are still many reasons to migrate the whole toolchain to .NET Core:
1. .NET Framework is terminated.
2. Visual Studio independency.
3. .NET Core only or .NET Standard 2.1 features.
......

It does not need to depend on an obsoleted framework, does it?

**Comment by geoffreymcgill** [comment]
> It does not need to depend on an obsoleted framework, does it?

For the time being, it does.

Unfortunately, we just don't have the resources (time, people, money) available to upgrade Bridge.NET to full .NET Core.

**Comment by geoffreymcgill** [comment]
We will do our best to support .NET Core as soon as we can. Once enabled, we will update this issue with the news.
