### ISSUE TITLE
Deck.net not working

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#4116]
https://deck.net

Just go to deck.net; code box doesn't appear.

![image](https://user-images.githubusercontent.com/10186738/81201554-408d3700-8f7a-11ea-8412-98a74a518329.png)

**Comment by geoffreymcgill** [comment]
It's working for me. Can you check the Developer tools in the browser and see if there are any JavaScript errors or exceptions?

Can you also check https://deck.net in a private/incognito tab.

**Comment by michaelcheers** [comment]
@geoffreymcgill, it appears that jquery failed to load. The problem seems to have fixed itelf.
