### ISSUE TITLE
Inject generated script as embedded resource

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#413]
Translator should inject generated script to an assembly and if the assembly is referenced inside another project then extract embedded script to output folder

Bridge project should reuse the same approach for bridge.js and bridge.min.js

**Comment by LeonidVeriga** [comment]
May be related to #355

**Comment by LeonidVeriga** [comment]
7f70b24332b56271c4fd91f73f626cf1d0a311f7
