### ISSUE TITLE
Documentation project: 3479 public entities to go

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#42]
Would it be a good idea to decorate all public types/members with summaries in order to make automatic documentation?

If so, I believe we have some 3500 items to document. Although I saw that IntelliSense displayed brief documentation of some things I used.
![Warning List](https://cloud.githubusercontent.com/assets/10730372/6543870/eaeb9eee-c50e-11e4-9f12-b59ea8077266.png) while trying to make VS generate .XML of decorated types/members on build.

**Comment by geoffreymcgill** [comment]
Over time, full doc comments will be added. We're working on solutions to automate this process.
