### ISSUE TITLE
[Int Format]"while (coefficient < 1)" is an endless loop if number == 0

### ISSUE THREAD

**Issue by gogglespisano** [bridgedotnet/Bridge#435]
In Bridge/Bridge/Resources/Integer.js

The "while (coefficient < 1)" is an endless loop if number == 0.

                    case "G":
                    case "E":
                        var exponent = 0,
                            coefficient = Math.abs(number),
                            exponentPrefix = match[1],
                            exponentPrecision = 3,
                            minDecimals,
                            maxDecimals;

                        while (coefficient >= 10) {
                            coefficient /= 10;
                            exponent++;
                        }

                        while (coefficient < 1) {
                            coefficient *= 10;
                            exponent--;
                        }

**Comment by LeonidVeriga** [comment]
@gogglespisano Thank you for reporting this bug. It has been fixed now.
