### ISSUE TITLE
Invalid JS built from custom 1.8 build

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#439]
@LeonidVeriga sent me a custom build of 1.8 that had your JS-packaging in (see #355). In that build, there was a small error in the JS being built from our React bindings (this was the only change)...

    Bridge.define('Bridge.React.AppDispatcher', {
    config: {
        events: {
            _dispatcher: null
        }
    },
    register: function (callback) {
        this._dispatchercallback); // <-- This is invalid
    },

The line of code used to be:

        this.add_dispatcher(callback);

I don't know what's caused this, but now we get syntax errors loading the JS in the browser. I'm going to try and build from latest code today to see if this still happens there and if so, dig further. The code we're building is mostly the same as @ProductiveRage's BitBucket repo I've sent previously.

I'll post more info as I find it...

**Comment by geoffreymcgill** [comment]
Certainly a defect, and I think building from source will still reproduce the same issue. 

We'll try to fix this defect right away. Thanks for reporting.

**Comment by DanTup** [comment]
Yep; does look like it still happens in latest code. Let me know if you can't reproduce and I'll try and produce the smallest C# I can that shows the error.

**Comment by DanTup** [comment]
Ok, can't reproduce this on live.bridge.net, but on latest code here I see this:

```csharp
using System;

namespace Bridge.React
{
	public class AppDispatcher
	{
		private event Action<string> _dispatcher;

		public void Register(Action<string> callback)
		{
			_dispatcher += callback;
		}
	}
}
```

compile to this (bad):

```js
/* global Bridge */

"use strict";
Bridge.define('Bridge.React.AppDispatcher', {
    config: {
        events: {
            _dispatcher: null
        }
    },
    register: function (callback) {
        this._dispatchercallback);
    }
});
```

but on live.bridge.net, it compiles to this (good):

```js
/* global Bridge */

Bridge.define('LiveApp.AppDispatcher', {
    config: {
        events: {
            _dispatcher: null
        }
    },
    register: function (callback) {
        this.add_dispatcher(callback);
    }
});
```

**Comment by DanTup** [comment]
All looks good now :+1:

**Comment by LeonidVeriga** [comment]
Thanks for testing and giving the feedback!
