### ISSUE TITLE
Show Bridge version/latest update date on live.bridge.net; consider "latest code" build

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#440]
I was trying to test some things out on live.bridge.net but they didn't seem to work. My guess is that it's running v1.8, not latest code, but I can't see an easy way to confirm.

Is it possible to add the version number (and maybe even the date)?

Ability to switch between latest stable release and latest code would be useful too (or hosting the latest code or a nightly build on another subdomain) to help reporting/debugging of issues in latest code that didn't go into a stable release (which, ideally, would always be the case!).

**Comment by LeonidVeriga** [comment]
Thanks for the request, @DanTup. It makes sense! We will have internal discussion on this item.

**Comment by geoffreymcgill** [comment]
Thanks for the request. We have added the version number to http://live.bridge.net.
