### ISSUE TITLE
#if DEBUG ignored

### ISSUE THREAD

**Issue by gogglespisano** [bridgedotnet/Bridge#445]
VS correctly highlights debug vs release code when the output type is changed, but only release .JS code is generated.

#if DEBUG
// never generated
#else
// always generated
#endif

**Comment by fabriciomurta** [comment]
Hello, have you tested this on our current and latest github branch? We've just developed this feature on issue #375. It will be available on NuGet for the next 1.9 release.

Do you agree your request is a duplicate of #375?

**Comment by gogglespisano** [comment]
#375 sounds like it should cover this problem.
