### ISSUE TITLE
GlobalTarget attribute does not emit its specified parameter when target referenced

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#446]
The code:

``` csharp
namespace ClassLibrary1
{
    public class Class1
    {
        public static void Main()
        {
            TestClass.Test().Alert("Test");
        }
    }

    public class GlobalRef
    {
        public void Alert(string message)
        {
            return;
        }
    }
    public class TestClass
    {
        [GlobalTarget("PrependedClass")]
        public static GlobalRef Test()
        {
            Console.WriteLine("TestClass");
            return null;
        }
    }
}
```

Results in

``` javascript
Bridge.define('ClassLibrary1.Class1', {
    statics: {
        main: function () {
            alert("Test");
        }
    }
});

Bridge.define('ClassLibrary1.GlobalRef', {
    alert: function (message) {
        return;
    }
});

Bridge.define('ClassLibrary1.TestClass', {
    statics: {
        test: function () {
            console.log("TestClass");
            return null;
        }
    }
});
```

Line 4 should read `PrependedClass.alert("Test");` instead of just `alert("Test");` as if `GlobalTarget` argument was empty.

**Comment by emumanu** [comment]
@fabriciomurta , @geoffreymcgill 

Is there any plan to fix this?

Still does not work in current bridge version:

https://deck.net/837431b2ceb825472eba964365fd45c3

I'm also impacted by this bug.

BR

**Comment by emumanu** [comment]
Thank you. 

BTW, I've seen an undocumented behaviour of GlobalTargetAttribute. It also removes the module dependency if there is one. Is this intentional?

https://deck.net/f6781c8028be14bfc711cd262abeac33

**Comment by vladsch** [comment]
You misunderstood the main goal of GlobalTargetAttribute. It points out that method/property returns a global object. The name argument is required if you try to assign the result to a variable

```
var g = TestClass.Test();
```

in other cases, that name will be ignored (because the global context is assumed by default). In your case, you need to use Template instead of GlobalTarget

```
[Template("PrependedClass")]
public static extern GlobalRef Test();
```

**Comment by emumanu** [comment]
@vladsch, thank you for the explanation.
