### ISSUE TITLE
#374 fix breaks events with multiple handlers

### ISSUE THREAD

**Issue by gogglespisano** [bridgedotnet/Bridge#457]
I get a strict mode exception when I have two or more event handlers on an event that is firing.  Using any of the handlers individually works ok.  The code worked ok before the fix for #374.

This is the first time I've used bridge.js compiled on my machine, so there's a chance I haven't done something that caused this error.  I copied the Bridge*.dll and bridge.js files.

This is the code executed for a single handler:
            bind: function (obj, method, args, appendArgs) {
                if (method && method.$method == method && method.$scope == obj) {
                    return method;
                }

                var fn = null;

                if (arguments.length === 2) {
                    fn = function () {
                        return method.apply(obj, arguments)
                    };

This is the code called when there are multiple handlers and the exception occurs when "var list =" is created:
            $build: function (handlers) {
                var fn = function () {
                    var list = arguments.callee.$invocationList,
                        result,
                        i,
                        handler;

                    for (i = 0; i < list.length; i++) {
                        handler = list[i];
                        result = handler.apply(null, arguments);
                    }

                    return result;
                };

**Comment by LeonidVeriga** [comment]
The issue has been fixed. Thanks for reporting this bug @gogglespisano.

**Comment by gogglespisano** [comment]
Thanks!  That works.
