### ISSUE TITLE
numeric "G" format specifier doesn't format correctly

### ISSUE THREAD

**Issue by gogglespisano** [bridgedotnet/Bridge#460]
This is with this afternoon's latest code.

The G format does not add thousand comma separators and it does add () for negative numbers.
It should use - for negative numbers and add commas for thousands separators.

The N format does add the commas.

https://msdn.microsoft.com/en-us/library/dwhawy9k(v=vs.110).aspx

**Comment by vladsch** [comment]
Can you post test case?

**Comment by vladsch** [comment]
I was able to reproduce issue for negative numbers but still not sure about thousand comma separators. Can you demonstrate it?

**Comment by LeonidVeriga** [comment]
@gogglespisano, yes, a code sample to reproduce the issue with thousand separator would help a lot.

According to https://msdn.microsoft.com/en-us/library/dwhawy9k%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396#GFormatString, it prints correct values:
```C#
using Bridge;
using Bridge.Html5;
using System;

namespace Demo
{
    public class App
    {
        [Ready]
        public static void Main()
        {
            double number;

            number = 12345.6789;
            Console.WriteLine(number.ToString("G", System.Globalization.CultureInfo.InvariantCulture));
            // Displays  12345.6789
            Console.WriteLine(number.ToString("G", System.Globalization.CultureInfo.GetCultureInfo("fr-FR")));
            // Displays 12345,6789

            Console.WriteLine(number.ToString("G7", System.Globalization.CultureInfo.InvariantCulture));
            // Displays 12345.68

            number = .0000023;
            Console.WriteLine(number.ToString("G", System.Globalization.CultureInfo.InvariantCulture));
            // Displays 2.3E-06
            Console.WriteLine(number.ToString("G", System.Globalization.CultureInfo.GetCultureInfo("fr-FR")));
            // Displays 2,3E-06

            number = .0023;
            Console.WriteLine(number.ToString("G", System.Globalization.CultureInfo.InvariantCulture));
            // Displays 0.0023

            number = 1234;
            Console.WriteLine(number.ToString("G2", System.Globalization.CultureInfo.InvariantCulture));
            // Displays 1.2E+03

            number = Math.PI;
            Console.WriteLine(number.ToString("G5", System.Globalization.CultureInfo.InvariantCulture));
            // Displays 3.1416
        }
    }
}
```

**Comment by gogglespisano** [comment]
Sorry, I was going by the example at the top of that doc page that shows "G" placing "," separators, but it looks like that's wrong and it doesn't actually support the group separator.

If you look here at the specific method overload, it is supposed to use the "-" prefix rather than the "()" for the "en-US" culture, which is the context my browser is running in, and I get the same result specifying current or invariant culture explicitly.

https://msdn.microsoft.com/en-us/library/kfsatb94(v=vs.100).aspx

Which culture do you use if it's not specified in ToString("G")?  Do you use current culture of the browser's environment or something else?

**Comment by vladsch** [comment]
By default, InvariantCulture is used because by default only invariant culture script is included, any additional cultures must be included manually
That can be interesting for you
https://github.com/bridgedotnet/Bridge/pull/437

**Comment by shadow-cs** [comment]
It seems the issue still persists in 15.7:

### Steps To Reproduce

http://deck.net/a203557dc35ea253fa56d06ac95c627f/top

```c#
public class Program
{
    public static void Main()
    {
        double d = 36.099999999999994d;
        
        Console.WriteLine(d.ToString("G17"));
    }
}
```

### Expected Result

`36.099999999999994`

See https://dotnetfiddle.net/PVJyd2

### Actual Result

`36.1`

**Comment by vladsch** [comment]
Hi @shadow-cs 
Issue is created https://github.com/bridgedotnet/Bridge/issues/2347
