### ISSUE TITLE
Test C# LINQ code

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#471]
http://forums.bridge.net/forum/community/help/664

Test with **Bridge vNext**.

**Comment by kreynazpm** [comment]
I'd like to help out but I don't know where to start.  I've never worked with bridge.

**Comment by fabriciomurta** [comment]
Thanks for your interest, @kreynazpm!

Currently Bridge 2 is closed for the public. We expect the open versions to be available very soon, though!

But in the meanwhile you can get started with bridge following the getting started guides available on [Bridge.NET's Knowledge Base](http://bridge.net/kb).
In particular, the [Getting Started guide](http://bridge.net/kb/getting-started).

**Comment by kreynazpm** [comment]
Okay so I went through the getting started page and did the demo in visual studio 2015


Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by DaniilVeriga** [comment]
Maybe, we should not mark that issue with `up-for-grabs`, because the repo is private yet. I will discuss internally.

**Comment by geoffreymcgill** [comment]
C#6 Lambda Expressions have been supported in Bridge since the version 15.0 release. A sample can be tested at the following Deck:

http://deck.net/2438579be4e9fa8c5746e8d37797ac95
