### ISSUE TITLE
Property with name same as type sometimes compiles as type

### ISSUE THREAD

**Issue by gogglespisano** [bridgedotnet/Bridge#483]
### Actual
```js
        getMyOtherType: function () {
            return Demo.MyType;
        }
```

### Expected
```js
        getMyOtherType: function () {
            return this.MyType;
        }
```

### Steps to reproduce
[Deck](http://deck.net/c4aac6388bcca9d440572905b214f041)

```cs
public class Program
{
    public static void Main()
    {
        var t = new Test() { MyType = new MyType() { Value = 7} };

        Console.WriteLine("Should be 7: " + t.MyOtherType.Value);
    }
}

class MyType : MyOtherType
{
}

class MyOtherType
{
	public int Value;
}

class Test
{
    public MyType MyType;
    public MyOtherType MyOtherType
    {
        get
        {
            return MyType.As<MyOtherType>();
        }
    }
}
```

**Comment by gogglespisano** [comment]
Prefixing the property with "this." seems to force it to compile properly, but shouldn't be necessary.

MyOtherType MyOtherType { get { return this.MyType.As(); } }

**Comment by vladsch** [comment]
Unfortunatelly, it is NRefactory issue. We need more time to fix it (need fix NRefactory)

**Comment by DaniilVeriga** [comment]
We've discussed this issue internally. Fixing this issue is going to be slated for Bridge v2. Well, moslt likely the issue is just not going to happen with Bridge v2 because it doesn't use NRefactory at all.

As for Bridge v1, fortunately, there is a workaround.
