### ISSUE TITLE
Linq exception ("Sequence contains no matching element") when using locales sample from docs

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#493]
When I add this to my `bridge.json`:

    "locales": "en_GB"

The build fails with:

```
Bridge.targets(12,5): error : Error: Sequence contains no matching element    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
Bridge.targets(12,5): error :    at Bridge.Translator.Translator.ExtractCore(String outputPath, Boolean nodebug)
Bridge.targets(12,5): error :    at Bridge.Build.GenerateScript.Execute()
```

Changing it to `en-GB` fixes the issue but [the docs](http://bridge.net/kb/global-configuration/#locales) have underscores in their examples. I presume this the docs are wrong though I think the compiler shouldn't crash with a vague error for bad config.

**Comment by fabriciomurta** [comment]
Hi DanTup! Somehow this changes were reverted in the Docs. In fact at a given time we had this mishap as underscore but it were fixed to hyphen. Don't really know the reason the underscore is back there but we'll fix this at once (again)!.. :)

**Comment by fabriciomurta** [comment]
Docs fixed, thank you!

**Comment by DanTup** [comment]
Is there value in improving the error for when invalid cultures are added (if you haven't already)? I guessed what the issue was because I'd just added cultures, but if you grab a large project you're not familiar with, this error won't help identify what's wrong.
