### ISSUE TITLE
HTMLColor fields should accept string too

### ISSUE THREAD

**Issue by gogglespisano** [bridgedotnet/Bridge#495]
HTMLColor fields should accept string values since **HTMLColor** is just a color name string.

Currently you can't use anything but named colors for `CSSStyleDeclaration.Color`.

    HTMLColor color = HTMLColor.Blue;
    or cast
    HTMLColor color = (HTMLColor) "#0000FF";
    or static method
    HTMLColor color = HTMLColor.FromString("#0000FF");

**Comment by DaniilVeriga** [comment]
Hello @ gogglespisano,

I am sorry for the delay. Each property with HTMLColor type has a counterpart with string type.

For example, there are `Color` and `ColorString` properties.

[Live Example](http://live.bridge.net/#e446d3ebba1a7996f4f6)
```
using Bridge;
using Bridge.Html5;

namespace Test
{
    public class TestCSS
    {
        [Ready]
        public static void Main()
        {
            ButtonElement button = new ButtonElement();
            button.InnerHTML = "Button 1";
            button.Style.Color = HTMLColor.Green;

            Document.Body.AppendChild(button);

            button = new ButtonElement();
            button.InnerHTML = "Button 2";
            button.Style.ColorString = "yellow";

            Document.Body.AppendChild(button);
        }
    }
}
```

**Comment by geoffreymcgill** [comment]
We are discussing changing the **Style.Color** Type from an Enum to a String. 

We would then also change **HTMLColor** from an Enum to static Class with a list of static String values.

This would represent a breaking-change, but would then allow both the following syntax options:

    button.Style.Color = HTMLColor.Green;
    button.Style.Color = "yellow";

We would also remove the **Style.ColorString** Property as it would no longer be required. 

If you have any feedback regarding this change, please let us know. Our goal it to incorporate this change into the upcoming 1.10 release.

**Comment by gogglespisano** [comment]
I agree with the proposed change.  I didn't use HTMLColor as an enum other than setting a Color field.  The only other times I used HTMLColor, I added .ToString(), so converting it to a string would end up being less code for me.

I also think it will avoid confusion, not having to know there's two different properties for the same thing depending on if you want a custom color or a named color.

**Comment by LeonidVeriga** [comment]
breaking-change: removed the Style.ColorString property
