### ISSUE TITLE
Support setting a "current culture" to be used in ToString/Parse of dates/numbers/etc.

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#496]
On the server we often set the `CurrentThread.CurrentUICulture` to the users culture so that when we `ToString()` (or `Parse`) dates/numbers/etc. they use the users selected culture.

With #437, we can pull in the cultures we're letting the user select for our UI, but parsing and formatting dates needs explicit code. Ideally, these methods would work similar to in .NET, and automatically use the selected culture.

Eg: In C# I can do this:

	var gb = new CultureInfo("en-GB");
	var us = new CultureInfo("en-US");

	Thread.CurrentThread.CurrentCulture = gb;
	Console.WriteLine(new DateTime(2015, 2, 1).ToString()); // 01/02/2015 00:00:00
	Console.WriteLine(DateTime.Parse("01/02/2015").Month); // 2

	Thread.CurrentThread.CurrentCulture = us;
	Console.WriteLine(new DateTime(2015, 2, 1).ToString()); // 2/1/2015 12:00:00 AM
	Console.WriteLine(DateTime.Parse("01/02/2015").Month); // 1

It would be really convenient to be able to do something similar in Bridge. Currently there is no `CurrentCulture` on `Thread.CurrentThread`, so I presume this isn't currently possible?

**Comment by vladsch** [comment]
You can use CultureInfo.CurrentCulture property
`System.Globalization.CultureInfo.CurrentCulture = new CultureInfo("en-US");`
I understand that it is not standard way but at this moment you should use it instead CurrentThread

**Comment by DanTup** [comment]
Great, that'll work fine!

However, it doesn't seem to work (this may be a dupe of the other case I just raised):

	CultureInfo.CurrentCulture = new CultureInfo("en-GB");
	Global.Alert(new DateTime(2015, 2, 1).ToString());
	Global.Alert((DateTime.Parse("01/02/2015").Month).ToString());

	CultureInfo.CurrentCulture = new CultureInfo("en-US");
	Global.Alert(new DateTime(2015, 2, 1).ToString());
	Global.Alert((DateTime.Parse("01/02/2015").Month).ToString());

Both of these output 1st Feb (which is correct for en-GB, wrong for en-US), but 1 as the month (this is correct for en-US, but wrong for en-GB - seems like they're not consistently wrong!).

**Comment by DaniilVeriga** [comment]
This is working in 1.10.
`CultureInfo.CurrentCulture = new CultureInfo("en-US");`

As for
`Thread.CurrentThread.CurrentCulture = gb;`
then the Thread class is most likely not going to be implemented ever, because it doesn't quite have any meaning for JavaScript. If you don't mind, I am closing the issue.

**Comment by DanTup** [comment]
Ofcourse; the functionality was the important thing, not where it lives. Thanks!

I tried to test this on live.bridge.net using my snippet above, but en-GB isn't there. I thought there had been discussion about that previously, but can't find it - is it intended that any cultures are available on live.bridge.net? Is it possible to maybe add a couple, even if not the full set (en-US and en-GB would be good candidates, having different date formats makes them easy to test things).

**Comment by DaniilVeriga** [comment]
It looks like the most relevant comment is [here](https://github.com/bridgedotnet/Bridge/issues/349#issuecomment-143365307).
