### ISSUE TITLE
Culture-specific TryParse does not behave as expected

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#497]
This fails on live.bridge.net because the cultures don't seem to be loaded (see my latest comment on #349), but when I run it locally with the cultures imported, it doesn't do what I'd expect (it alerts the same date in both cases; Jan 2nd)

	Global.Alert(DateTime.Parse("01/02/2015", new CultureInfo("en-US")).ToString());
	Global.Alert(DateTime.Parse("01/02/2015", new CultureInfo("en-GB")).ToString());

**Comment by vladsch** [comment]
Fixed in https://github.com/bridgedotnet/Bridge/commit/f64778c1b394c8dc3d5d5bf4267dda1f414802d1

**Comment by DanTup** [comment]
Recent fixes are on a branch (1.10) and not master (which is what our buildserver was building). Is it safe/wise for us to build from that branch or would it be better to wait for it to be merged to master before we try testing/using these fixes?

**Comment by LeonidVeriga** [comment]
Yes, this is correct -  `release1.10`branch is considered as a next release branch (pull requests should be created against this branch as well).

**Comment by DanTup** [comment]
This code works as expected in the 1.10 branch, thanks!
