### ISSUE TITLE
Invalid JS output by date code (missing parens)

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#498]
[Sample on live.bridge.net](http://live.bridge.net/#ed10757d56b2e86b21bd)

    Global.Alert(DateTime.Parse("01/02/2015").Month.ToString());
    Global.Alert((DateTime.Parse("01/02/2015").Month).ToString());

If you don't have the extra parens (first line), the output JavaScript fails, because there's a `+ 1` added to the end of the `getMonth()` call, but no parents before calling `toString`:

    Bridge.global.alert(Bridge.Date.parse("01/02/2015").getMonth() + 1.toString());
    Bridge.global.alert((Bridge.Date.parse("01/02/2015").getMonth() + 1).toString());

**Comment by gogglespisano** [comment]
This also happens with any constant, such as

0.ToString() needs to be (0).ToString()
Enum.Value.ToString() needs to be (Enum.Value).ToString() if Enum has [Enum(Emit.Value)] attribute
