### ISSUE TITLE
ElementType enum and new jQuery(ElementType) constructor

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#5]

**Comment by geoffreymcgill** [comment]
@DaniilVeriga - Can you test if this is now working correctly if using the `:raw` flag?

**Comment by DaniilVeriga** [comment]
Yes, it works flawlessly. Added the jQuery(ElementType) constructor.

Now this C# code

    new jQuery(ElementType.Div);
    new jQuery(ElementType.Canvas);

produces this JavaScript code

    $("<div>");
    $("<canvas>");
