### ISSUE TITLE
combineScripts:true doesn't include referenced projects

### ISSUE THREAD

**Issue by gogglespisano** [bridgedotnet/Bridge#512]
combineScripts:true is only useful for single projects, but it would be most useful when combining several libraries/projects.

Since it only combines the last project with bridge.js and the referenced projects need to be included after bridge.js and before the final project, you can't use combineScripts:true in the situation where it will be the most beneficial.

**Comment by fabriciomurta** [comment]
Hello @gogglespisano!

Thanks for the suggestion!

This feature currently works somewhat like how `msbuild` combines the built code on a single assembly (.dll) file. It just combines the output files it is about to actually output. If the .js file is not output, there's no way for it to output this.

For now, I believe the approach would be likewise how can be currently done to .NET assemblies. For example, one can use a third-party tool called [ILMerge](http://research.microsoft.com/en-us/people/mbarnett/ilmerge.aspx) to merge several assemblies into a single .dll file.

Similarly, my I personal feel is that it more likely to have a tool like ILMerge for .js output to merge the files (without duplicating code like `bridge.js` and localization).

As far as I know, Bridge's builder has does not generate actual `.js` for the referenced libraries. Each project is responsible for the output of its own JavaScript, much like the .DLL assemblies, which are copied over by Visual Studio to the referencing projects. If the referenced libraries are not actually generating any JavaScript output for example, there would be no way to combine those unexistent JavaScript files.

This is something very actual for other languages like c++ which haves static library linking.

**Comment by gogglespisano** [comment]
I don't know how the bridge builder works, but since the referenced project .js files are copied to the Bridge/output folder on the final project I assumed they would be available to combine.

Is VS/MSBuild copying the .js file to output folder, or is the builder extracting it from the referenced project .dll file?

**Comment by vladsch** [comment]
If referenced assembly has injected javascript and code from that assembly is used in the project then  referenced javascript will be copied to output and combined with other javascript files

Injection of javascript to assembly is active by default. The same approach is applied for Bridge.dll, it has injected bridge.js file which is copied to output

**Comment by gogglespisano** [comment]
You're correct.  It turns out my problem is a bit different.  The referenced project output isn't even copied the final project's output and so it isn't included the final .js file when using combienScripts:true.  I have to include the .js file from the referenced project otherwise I get a undefined error.

I'll open a separate issue for that problem.
