### ISSUE TITLE
Referenced project output isn't copied to final project output.

### ISSUE THREAD

**Issue by gogglespisano** [bridgedotnet/Bridge#513]
The referenced project's .dll file is copied to the final project's bin folder, but the referenced project's .js file isn't copied to the final output folder even though the js code is used in the final output js.

The referenced project only produces a class with a constructor, which might be a clue why it gets missed.

This code is output in the referenced project:

```
Bridge.define('Bridge.ReferencedProject', {
    precision: 0,
    constructor: function (otherObject) {
        this.precision = -1;
    }
});
```

This code in the final output fails because the referenced output is missing:

`ExternalJsCode.Api(new Bridge.ReferencedProject(this._otherObject));`

**Comment by LeonidVeriga** [comment]
Hi @gogglespisano. Thanks for your Pull Request. I created a separate one #515 based on your changes but for branch `release1.10` as it is a source for the next 1.10 release. I had to change the code to support sign() method for IE by this change, a QUnit test added as well.

**Comment by vladsch** [comment]
Can you check that `injectScriptToAssembly` option is not set to false in referenced project? Because automatic copy of referenced assembly's script is possible when `injectScriptToAssembly` is true

**Comment by gogglespisano** [comment]
That was the problem.  I had set it to false because of the const enum causing the build failure.

I guess I just have to hope I don't need both options.
