### ISSUE TITLE
TypeArrays miss the [Name("TypedArray")] attribute

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#548]
The issue is discovered due to this [comment](https://github.com/bridgedotnet/Bridge/issues/182#issuecomment-152838336).

**C#**: `var float32Array = new Float32Array();`

**JavaScript**:

 * Actual: `var float32Array = new Bridge.Html5.Float32Array();` - it throws *Uncaught TypeError: Cannot read property 'Float32Array' of undefined*.
 * Expected: `var float32Array = new Float32Array();`

The [live example](http://live.bridge.net/#5baecb22616d86c1ba52).

It is actual for all the TypedArray classes.

**Comment by fabriciomurta** [comment]
There's no Float32Array() constructor taking 0 arguments.

The valid overloads are:
```csharp
        public Float32Array(Any<int, long, uint, ulong> length);
        public Float32Array(Float32Array typedArray);
        public Float32Array(object objectInstance);
        public Float32Array(ArrayBuffer buffer, uint byteOffset = 0, uint length = 0);
```

Sources:
[MDN reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array)
[Bridge source for Float32Array](https://github.com/bridgedotnet/Bridge/blob/master/Html5/TypedArray/Float32Array.cs)

**Comment by DaniilVeriga** [comment]
Interesting why it compiles in Live Bridge. Okay, it is probably an issue with Live Bridge. Another story.

Another story more is that `new Float32Array()` actually works in browsers - tested in Chrome, Firefox and IE. But yes, it is not mentioned in the docs and I don't think we should add it.

Please forget the Float32Array() constructor taking 0 arguments. My bug report wasn't too accurate.

Now lets talk about all the available constructors. Do they work?:) As far as I can see they don't. The reason is probably missing a `[Name("Float32Array")]` attribute on the Float32Array class.

**Comment by fabriciomurta** [comment]
The information above was just a side note, it did not invalidate the surplus `Bridge.Html5.` namespace reference on class instantiation.
