### ISSUE TITLE
ArrayBufferView should be a superclass for TypedArrays or ArrayBufferView should be changed to interface that TypedArrays implement or something else

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#550]
The issue is discovered due to this [comment](https://github.com/bridgedotnet/Bridge/issues/182#issuecomment-152838336).

**Comment by fabriciomurta** [comment]
As per [documentation here](https://developer.mozilla.org/en-US/docs/Web/API/ArrayBufferView), it seems the type definition itself should be absent, and whatever points to it should then point to any (or all) of the TypedArrays implemented.

**Comment by fabriciomurta** [comment]
Maybe it should just be turned into `Any<Int8Array, UintArray, ..., Float32Array, Float64Array>`?

**Comment by DaniilVeriga** [comment]
I like the idea with `Any<>`. Did you mean this?

```
public class ArrayBufferView : Any<Int8Array, UintArray, ..., Float32Array, Float64Array>
{
}
```

There is also the DataView class to review. It is currently:
`public class DataView : ArrayBufferView`

As far as I can understand the inheritance from the ArrayBufferView class should be removed. The existing ArrayBufferView's properties should be moved to the DataView class itself. And, as stated above, the ArrayBufferView class itself might be turned to `Any<...>`. It would be better to have it, than put `Any<...>` everywhere.
