### ISSUE TITLE
Text node should alias ctor to createTextNode

### ISSUE THREAD

**Issue by Suchiman** [bridgedotnet/Bridge#557]
[Text.ctor(string)](https://github.com/bridgedotnet/Bridge/blob/ac094ebcac64ea526ebf2a4775eed608afead50a/Html5/Node/Text.cs#L15) will, for example, fail at runtime since new Text("...") is not allowed.
I think it should be Templated to `document.createTextNode('{data}')`.

**Comment by LeonidVeriga** [comment]
@Suchiman, thank you for reporting this issue. We have fixed it in the `release1.10` branch
