### ISSUE TITLE
Support for Visual Studio shared projects

### ISSUE THREAD

**Issue by Ttxman** [bridgedotnet/Bridge#562]
Linking every shared cs (add existing item ... add as link) to more projects is very annoying. Xamarin and Microsoft solved this by adding "Shared Projects" == bunch of source files organized in project (*.shproj), that are automatically included at compile time.

https://developer.xamarin.com/guides/cross-platform/application_fundamentals/shared_projects/
http://blogs.msdn.com/b/dotnet/archive/2014/04/21/sharing-code-across-platforms.aspx

I made a little change in source Translator.ProjectReader.cs to support it locally, there is the code that works for me:
```C#
        protected virtual IList<string> GetSourceFiles(XDocument doc)
        {
            var result = new List<string>();

            var nodeList = from n in doc.Descendants()
                           where n.Name.LocalName == "Compile" &&
                                 !string.IsNullOrWhiteSpace(n.Attribute("Include").Value)
                           select n;

            foreach (var node in nodeList)
            {
                result.Add(node.Attribute("Include").Value);
            }


            var sharedProjects = doc.Descendants()
                .Where(n => n.Name.LocalName == "Import" && n.Attributes().Any(a => a.Name.LocalName == "Label" && a.Value == "Shared"))
                .Select(n => n.Attribute("Project").Value);


            foreach (var proj in sharedProjects)
            {
                string path = Path.Combine(Path.GetDirectoryName(Location), proj);
                doc = XDocument.Load(proj);
                
                nodeList = from n in doc.Descendants()
                           where n.Name.LocalName == "Compile" &&
                                 !string.IsNullOrWhiteSpace(n.Attribute("Include").Value)
                           select n;

                string rootpath = Path.GetDirectoryName(path)+"\\";

                foreach (var node in nodeList)
                {
                    result.Add(node.Attribute("Include").Value.Replace("$(MSBuildThisFileDirectory)", rootpath));
                }
            }
            return result;
        }

```

I didn't make this a pull request, because I'm using vs2015 and there are some modifications of *.csproj files to make the new nuget work and i don't want to install vs2013 and maintain 2 branches:)

**Comment by Suchiman** [comment]
Related: http://forums.bridge.net/forum/general/feature-requests/878-support-shared-projects

**Comment by vladsch** [comment]
Can you retest with latest code from 'release 1.10' branch? We changed how source files are extracted from project file, now we use MSBuild API, may be it automatically can resolve the issue

**Comment by geoffreymcgill** [comment]
This may be fixed, but feedback is required after 1.10 release.

If some adjustments are still required, we may be able to release a 1.10.1 package.

**Comment by Ttxman** [comment]
@vladsch Shared projects are working in 1.10 branch. At least on my project..

**Comment by LeonidVeriga** [comment]
#531
