### ISSUE TITLE
Referring to some types defined in Bridge's System namespace breaks generated code

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#565]
Some types available on Bridge are defined on this file: [Stubs.cs](https://github.com/bridgedotnet/Bridge/blob/master/Bridge/System/Stubs.cs). If they are used, the resulting JavaScript code is broken. For example:

```csharp
public class App
{
    [Ready]
    public static void Main()
    {
        var x = new Type();
        var y = new Enum();
    }
}
```
results in
```javascript
Bridge.define('LiveApp.App', {
    statics: {
        config: {
            init: function () {
                Bridge.ready(this.main);
            }
        },
        main: function () {
            var x = new System.Type();
            var y = new System.Enum();
        }
    }
});
```

[Example in bridge Live](http://live.bridge.net/#ab24d2a74816c97e6514)

Maybe just not allowing to use these types (or limiting their scope) would suffice. What do you think, @vladsch?

**Comment by LeonidVeriga** [comment]
It is fixed by adding attribute  [Function] or [Object] for these types.

**Comment by fabriciomurta** [comment]
I think this might be related to #262
