### ISSUE TITLE
"this" reference incorrect in abstract base ctor when derived class has no ctor 

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#566]
Related forum thread:

http://forums.bridge.net/forum/bridge-net-pro/bugs/944
Reported by @ProductiveRage.

**Comment by geoffreymcgill** [comment]
See working sample to reproduce:

http://live.bridge.net/#b19b735ab324f639ca5d

**Comment by vladsch** [comment]
I cannot reproduce it with latest code from 'release 1.10' branch

**Comment by geoffreymcgill** [comment]
Fixed in 1.10

**Comment by geoffreymcgill** [comment]
This appears to working in 1.10. We are adding some tests for this scenario.
