### ISSUE TITLE
'get' causes problem in Dictionary code

### ISSUE THREAD

**Issue by RexHell** [bridgedotnet/Bridge#572]
The code in Collections/Dictionary.js:
>        getItem: function (key) {
>            return get(key);
>        }

will cause the following error when called:
>    'get' not defined

while there is the 'get' method.
Changing 'get(key)' to 'this.get(key)' can resolve the problem.
There is also a 'setItem' method calling 'set', and I think it should also be changed to 'this.set'.

**Comment by LeonidVeriga** [comment]
Hi @RexHell! Thank you for reporting this issue.

A code to reproduce the issue looks like:

```C#
using Bridge;
using Bridge.Html5;
using System;
using System.Collections.Generic;

namespace Demo
{
    public class App
    {
        [Ready]
        public static void Main()
        {
            var d1 = new Dictionary<int, string>();
            var d = d1 as IDictionary<int, string>;

            d.Add(1, "One");
            Console.Log(d[1]);

            d[1] = "New one";
            Console.Log(d[1]);
        }
    }
}
```

We have included the fix into `release1.10` branch.
