### ISSUE TITLE
Rename IgnoreAttribute to ExternalAttribute

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#573]
Keep IgnoreAttribute, but mark as `Obsolete`.

**Comment by geoffreymcgill** [comment]
Rename in Attribute Reference KB article:

http://bridge.net/kb/attribute-reference/#Ignore

**Comment by LeonidVeriga** [comment]
The KB article is updated and pending review http://bridge.net/kb/attribute-reference/#Ignore:
 - Changed current Ignore section to tell that the attribute is obsolete;
 - Added External attribute section  http://bridge.net/kb/attribute-reference/#External;
 - Updated Live sample to use [External] (will take effect after Live is updated to 1.10)
