### ISSUE TITLE
Missed DateTime API

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#582]
http://forums.bridge.net/forum/general/feature-requests/724

`public DateTime ToUniversalTime()` - FYI: it is already in v2.
`public DateTime Add(TimeSpan value)`
`public DateTime AddTicks(long value)`
`public DateTime Subtract(TimeSpan value)`
`public TimeSpan TimeOfDay { get; }`
`public long Ticks { get; }`

A related Bridge v2 [issue](https://github.com/bridgedotnet/Bridge2/issues/36).

**Comment by LeonidVeriga** [comment]
breaking-change: `DateTime.ToUTC` renamed to `DateTime.ToUniversalTime`
