### ISSUE TITLE
Compiler does not ignore emit of Members with extern modifier

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#587]
http://live.bridge.net/#07e563166ed51db3e9c7

**Comment by vladsch** [comment]
Bridge compiler ignores extern method and doesn't emit it
It is Live.Bridge application problem, the code provied in the sample is not compilable (bug of live application which prevents compilation of the sample), just extern method should not decalre body (it is compilation error)
New sample: http://live.bridge.net/#bd241a041fab2c2fe4df
