### ISSUE TITLE
Problem with initializing of static members (Topological sorting implemented)

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#588]
http://forums.bridge.net/forum/community/help/828
http://forums.bridge.net/forum/bridge-net-pro/bugs/829

1. Requires automatic resolve dependencies and build correct sequence of types for emitting
2. Static constructors and initialization should not be deffered to DOM ready event (need to call initialization as soon as possible, by default after parsing current js file)

**Comment by DaniilVeriga** [comment]
An additional unit test from [this forum thread](http://forums.bridge.net/forum/community/help/993) has been added. Thanks to @ProductiveRage. While adding it, another test case has been found that is not covered by the initial fix. The fix has been adjusted in [this commit](https://github.com/bridgedotnet/Bridge/commit/6f2036164484621eeb5379b245d9fdba480505e2).
