### ISSUE TITLE
ReadyAttribute instance method is called with incorrect scope

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#599]
````
public class App
    {
        private string _something = "HI!";

        [Ready]
        public static void Main()
        {
            var inst = new App();
        }

        [Ready]
        public void Test()
        {
            Console.WriteLine(_something);
        }
    }
````
Expected output: "HI!"

**Comment by fabriciomurta** [comment]
This looks odd... Who instantiates the App class if the Test() method is not static? Shouldn't rather the Test() method not be elligible to [Ready] attribute?

**Comment by vladsch** [comment]
Yes, it looks strange to use Ready for instance methods. But I guess it can be used (for example, instance is created but method (which modify DOM structure) can be invoked when DOM tree is ready only)
