### ISSUE TITLE
Enumerable.ToDictionary uses incorrect return type

### ISSUE THREAD

**Issue by t-nelis** [bridgedotnet/Bridge#625]
Hello,

The .NET versions of `Enumerable.ToDictionary` extension method overloads return `Dictionary<TKey, TElement>` instances, while the Bridge versions return `IDictionary<TKey, TElement>` instances.

Any code depending on the more specific version will fail to compile.

PS: Looking around we observe many different method signatures. Is there any reason the project doesn't strictly use the original signatures?

Thank you for your work.

**Comment by vladsch** [comment]
Can you provide more details about other methods which have difference with .NET methods?
Thanks for your report

**Comment by t-nelis** [comment]
Of course. Please note these were merely cursory observations, we were mostly interested in knowing whether the project specifically aims toward accurate compatibility with a BCL subset or simply provide a BLC "feel" (either would be fine of course, we're just evaluating the project in the hope that we can use it more seriously).

- Bridge mostly uses `EnumerableInstance` types in place of `IEnumerable` types in most LINQ method signatures (`Enumerable` extensions), though not all. (We guess for all return types and some redundant seemingly redundant overload arguments.)

- Similarly, the `Grouping` type is used in place of `IGrouping` in `GroupBy` signatures.

- A quick count reveals Bridge doesn't provide the same number of methods (we didn't try and specifically identify a pattern, we guess it has to do with the `EnumerableInstance`-based overloads).

- Aside from `Enumerable`, we noted a few differences in `String` (lack of `IComparable` implementation), but if I'm not mistaken the next release contains some patches for that, we'll wait for it.

- Of course there's still a lot of things to implement (or attempt to). I don't have the list at hand, but in trying to port a library we had to work around some missing APIs that we thought would be reasonable targets for your BCL subset (e.g. the immutable collections) and some that might be a little more difficult (e.g. some `Type` introspection methods like `IsSubclassOf` and `GetTypeCode`, or conversion methods with `System.Convert`). Depending on whether you're aiming for accurate compatibility, we think it would be useful to document the implementation progress so that users and contributors can track support easily (possibly using automated tests). Even more useful would be a definitive description of the subset, or maybe the other way around with a list of things that are considered out-of-scope/unimplementable for the project.

- We were also not sure how to handle some attributes like `Obsolete` or debug methods like `Debug.Assert`. We setup dummy implementations for now; I think ultimately it would be reasonable that you simply don't support these kinds of things, though a story on how to workaround them would be nice to have.

We realize most differences (e.g. `EnumerableInstance`) are meant to be compatible, and again depending on the goal this might be reasonable. We tend to prefer more accurate signatures simply to avoid silly mistakes like depending on target-specific return types, though we understand that from your perspective we have to test against both targets anyway and should detect those errors soon enough with proper automated test coverage.

I hope this is useful, no hard feelings otherwise (we really like it so far).

**Comment by geoffreymcgill** [comment]
Hi @t-nelis, Thanks for the great feedback and comments. We are discussing your comments. I can't say that we'll have a detailed response right away, but we are discussing in detail.

**Comment by DaniilVeriga** [comment]
Hello @t-nelis,

Our ultimate goal is to match and implement .NET API as much as possible. Though, there might be technical troubles to implement something, or no JavaScript meaning of some .NET functionality at all and, sure, mistakes are always possible. If some feature is not in Bridge yet, then that is most likely upcoming. Your feedback about any issues is very appreciated!

I will go step-by-step on your comments.

I tend to leave the original problem `Dictionary<TKey, TElement>` versus `IDictionary<TKey, TElement>` in the scope of this issue. It looks to be an easy fix. @vladsch, could you, please, review?

> EnumerableInstance vs IEnumerable types in most LINQ method signatures

There is a technical problem why it is like that. Created #712.

> Similarly, the Grouping type is used in place of IGrouping in GroupBy signatures.

Created #713

> A quick count reveals Bridge doesn't provide the same number of methods...

You are welcome to start more dedicated individual issues. Though, we'll be reviewing all the LINQ implementation - #714.

> lack of IComparable implementation

It appeared in 1.10 - #353.

> Type .IsSubclassOf() 

This method is already in Bridge 2.0. Though, created #715 to review a possibility to add it to v1.x.

> Type .GetTypeCode()

Created #716

> System.Convert

There is an existing #14 issue. It is planned for the 1.11 release.

> Obsolete

Created #717.

> Debug.Assert

It is already in Bridge 2.0. Created an Issue to review a possibility to add it to 1.x - #718.

> it would be useful to document the implementation progress so that users and contributors can track support easily (possibly using automated tests). Even more useful would be a definitive description of the subset, or maybe the other way around with a list of things that are considered out-of-scope/unimplementable for the project.

Created #719.

We'll be doing our best to sort out all these issues. Though, you and everybody from the community are very welcome to submit pull requests. But still just reporting issues is a huge help for us.

**Comment by t-nelis** [comment]
Thank you for the transparency and for your time; this is greatly appreciated. I admit we didn't expect such a dedicated report on all these small points.

However numerous they are, I feel I should report we were always able to refactor our code to either drop the need for the problematic APIs or abstract them behind interfaces in Bridge-specific modules. As always, these kinds of things even help improve our own designs and the fact that they were rather straightforward tells us you seem to have done a good job at prioritizing what's really important (and wouldn't have been so trivial to implement otherwise). Props for that! (And feel free to deprioritize the new issues if we're the only ones.)

About the only pain points revolved around dependency management. We manually setup linked items in VS projects (with MSBuild include/exclude patterns) used to build the JS artefacts (using PCL functionality would be better AFAIU), and will probably setup something to pull them in the dependent applications less manually too. I'd open an issue if I knew exactly what it should look like, but we don't as of yet. In the meantime, I hope this can help you prioritize further, as it will be something every user will have to go through as soon as they want to reuse any piece of code in two projects.

PS: If we can commit to using Bridge more intensely, I hope to be able to position myself to contribute in more tangible ways in the future. It's not always easy (we're a small shop), so I've also aired the idea of buying into a subscription model for support to the powers that be, should you establish one. As a small data point to factor in your future decisions, I'm sure you'll be interested to know the idea was received quite positively.

**Comment by geoffreymcgill** [comment]
Hi @t-nelis,

Thanks again for your comments. You sparked a big discussion within the team and brought our attention to some poor decisions we made within Bridge. We're going to be reorganising many of the classes and members, especially the mixing of JavaScript members within the C# api.

We're going to leave this thread's primary task as tracking the original error in returning `IDictionary` from **Enumerable.ToDictionary**. This will be corrected in Milestone 1.10.3. 

As noted by @DaniilVeriga above, many of the other revisions are being tracking in individual Issues. Most of those Issues will be resolved in Milestone 1.11.

**Comment by DaniilVeriga** [comment]
@t-nelis, just FYI: System.Convert (#14) has been implemented except a few things (#977).

**Comment by t-nelis** [comment]
@DaniilVeriga Thanks for the heads-up. Always love to drop a few hacks from our code.

**Comment by geoffreymcgill** [comment]
Looks like this thread was not updated with notice of `Debug.Assert` being implemented in v1.11. 

```csharp
using Bridge.Html5;
using System.Diagnostics;

namespace Demo
{
    public class App
    {
        [Ready]
        public static void Main()
        {
            Debug.Assert(false, "FAIL");
        }
    }
}
```

If the `Assert` fails (`false`), a prompt will be thrown to enter the browser `debugger` instance. 

Hope this helps.

**Comment by DaniilVeriga** [comment]
I've just found out that the `Obsolete` attribute has been added in 1.10.1 release in this commit.
https://github.com/bridgedotnet/Bridge/commit/5911f112129dc6694b3c4b03f158a8f22f9d9310

The `Obsolete` attribute is not emitted in JavaScript code, but works in C# code as expected - compiles and causes a compile warning if an `[Obsolete]` method is called.

**Comment by DaniilVeriga** [comment]
Something with the "IDictionary vs Dictionary" issue wasn't fixed:
http://forums.bridge.net/forum/community/help/2247

[Live Test Case](http://live.bridge.net/#dce5322a5768a2d7a7d872228efbf5f0)
