### ISSUE TITLE
Global preserveMemberCase: "true" vs Bridge.jQuery2.AjaxOptions and other

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#649]
http://forums.bridge.net/forum/bridge-net-pro/bugs/1108

**Comment by vladsch** [comment]
Fixed in https://github.com/bridgedotnet/Bridge/commit/5f510f13c2ce2b8ce121adc7393100312202b467
But we did not provide PreserveMemberCase attribute (at this moment `preserveMemberCase` option is ignored for classes from System and Bridge namespaces and subnamespaces)
