### ISSUE TITLE
Blank white page on first load (or two) after rebuild

### ISSUE THREAD

**Issue by DanTup** [bridgedotnet/Bridge#650]
We've been seeing this for a while, but I've been too busy to investigate. I tried today, but I don't really know where to start...

After rebuilding in VS2015 and hitting Ctrl+Refresh in Chrome, I just get a blank white page. If I hit reload again, it usually works, though more recently it seems to take a few refreshes to work.

This happens for quite a few of us (@calcock has it, though @ProductiveRage seems to not).

It seems like no scripts are running at all - there is no error in the console.

Any ideas? Have you seen anything similar?

**Comment by DanTup** [comment]
I think I've discovered the cause of this...

Same thing that breaks literally everything...

http://www.poconosystems.com/software-development/how-to-disable-browser-link-in-visual-studio-2013/

    <add key="vs:EnableBrowserLink" value="false" />

\*shudder\*

**Comment by ProductiveRage** [comment]
No wonder I couldn't reproduce - I always turn that straight off! :D

**Comment by DaniilVeriga** [comment]
Oh, I totally forgot about that EnableBrowserLink feature, but we already faced similar problems with it dealing with Ext.NET.

For references: the [forum post](http://forums.bridge.net/forum/community/help/1102?p=1106#post1106) there this issue is mentioned.

**Comment by DanTup** [comment]
I always turn it off too... except when I rebuild my machine and forget ;(

@ProductiveRage Another reason not to have all that asp.net guff in our sample projects ;-)
