### ISSUE TITLE
How to iterate over an objects properties?

### ISSUE THREAD

**Issue by maverix** [bridgedotnet/Bridge#656]
In a Script# project I am looking at migrating to Bridge.net.  I have some code which iterates over the properties on the object.  i.e.

            foreach (DictionaryEntry prop in Dictionary.GetDictionary(entity))
            {
                        string type = Script.GetScriptType(prop.Value);
                        // do something here
            }

Is there an equivalent option in Bridge?

I looked at Type.GetOwnPropertyNames()  but this doesn't seem to work in the actual browser
http://live.bridge.net/#9e37cbddfa31be6b3822 

Console error reported in chrome
"Uncaught TypeError: Function.getOwnPropertyNames is not a function"

**Comment by maverix** [comment]
Worked it out.

        foreach (string prop in object.Keys(item))
        {
            object value = Script.Get(item, prop);
            Console.Log(value);
        } 

http://live.bridge.net/#1b1a34149450e38f50ad

**Comment by vladsch** [comment]
Also, GetOwnPropertyNames is static method of Object (not Type)
