### ISSUE TITLE
Complete support for System.Linq.Expressions

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#681]
http://forums.bridge.net/forum/general/feature-requests/1161
http://forums.bridge.net/forum/community/help/2168

Missed expressions are:

- [ ] Expression
- [ ] MemberExpression
- [ ] UnaryExpression
- [ ] LambdaExpression
- [ ] ParameterExpression
- [ ] ExpressionVisitor - bridgedotnet/Bridge2#44

**Comment by geoffreymcgill** [comment]
Support added in Bridge 15.
