### ISSUE TITLE
Enumerable.from(array) ArrayEnumerator constructor not called in IE 8

### ISSUE THREAD

**Issue by jbw** [bridgedotnet/Bridge#683]
The below code does not work in IE 8

var exampleArray = Bridge.Linq.Enumerable.from(enumObjColl).toArray();

Any solution to this would be greatly appreciated because we're using this all over our code and LINQ.

**Comment by vladsch** [comment]
Can you post full test case and error from browser console?

**Comment by jbw** [comment]
Yeah sure - I'll put something together in 30 mins. 

Problem is IE 8 doesn't provide much in the way of errors. All I know is tracing it through doesn't call base constructor in Class and thus doesn't call the constructor on Enumerable. In Chrome however it does.

**Comment by jbw** [comment]
```csharp
public class TestObj
    {

        public TestObj()
        {
            Name = "Test";
            Entries = new List<TestObj>();
        }

        public string Name
        {
            get; set;
        }

        [FieldProperty]
        public IList<TestObj> Entries { get; set; }
    }

    public class App
    {
        [Ready]
        public static void Main()
        {
            var testObj = new TestObj();
            testObj.Entries.Add(new TestObj());

            var testArray = testObj.Entries.ToArray();
            Window.Alert(JSON.Stringify(testArray));

        }
    }
```

I've tested this on IE 8 on Windows 7 using Bridge 1.9.0

**Comment by jbw** [comment]
Breaks here:
```
// @source /Collections/ArrayEnumerator.js

Bridge.define('Bridge.ArrayEnumerator', {
    inherits: [Bridge.IEnumerator],
    constructor: function (array) {
        this.array = array;
        this.reset();
    },

    moveNext: function () {
        this.index++;

        return this.index < this.array.length;
    },
```

Using this:
```
var arrayTest = Bridge.Linq.Enumerable.from(Bridge.Linq.Enumerable.from(["A", "B"])).toArray();
		console.log(arrayTest);
```

Error
![capture2](https://cloud.githubusercontent.com/assets/41447/11557136/0a0ed872-99a3-11e5-851f-85446160f115.PNG)


Can anyone reproduce this and offer advice? I need a short term fix if there is one.

**Comment by jbw** [comment]
Code below in Class.js calls ArrayEnumerator.js but it never triggers in IE 8 and gives no errors when wrapping with a try/catch
```
if (this.$constructor) {
     this.$constructor.apply(this, arguments);
}
```

**Comment by lutas** [comment]
Using https://github.com/bridgedotnet/Bridge/issues/257 as a reference, I've found that adding the following lines when looping over the prop's seems to work (tested in Bridge 1.9).

                if (prop.constructor) {
                    prototype.$constructor = prop.constructor;
                    ctorCounter++;
                }


Add just after the lines:
                isCtor = name === "constructor";
                ctorName = isCtor ? "$constructor" : name;

**Comment by geoffreymcgill** [comment]
Your feedback regarding #1050 is appreciated.

IE8 support might be dropped in the next release, milestone 1.12.
