### ISSUE TITLE
"this" is not captured for async functions

### ISSUE THREAD

**Issue by johnwason** [bridgedotnet/Bridge#690]
I am using a Task to continue an async function after an await using `Task.SetResult(value)` and getting the problem that "this" is undefined after the resume.  It appears that "this" is not captured by the closure of the async function.  There should be a `$this` or something similar at the top of the function to capture the object and use it within the async switch state machine.

**Comment by johnwason** [comment]
It looks like "this" is not captured properly in anonymous or instance delegates if used as a callback as well.

**Comment by vladsch** [comment]
Sorry for late response.
Can you post a test sample which we can investigate?

**Comment by johnwason** [comment]
This recreates the problem:
    
    class class1
    {
        int testval = 0;
        public void foo()
        {
            //"Undefined" testval because "this" is Window, not class1 instance
            Console.WriteLine(testval);
            Console.WriteLine("foo");
        }

        public async void runtest()
        {
            Global.SetInterval(new Action(foo), 100);
            await Task.Delay(100);
            //"this" is undefined
            foo();
        }
    }

    public class App
    {
        [Ready]
        public static void Main()
        {
            var c = new class1();
            c.runtest();
        }
    }

And this is the type of workaround I have used. "this2" is captured properly:
     class class1
    {
        int testval = 0;
        public void foo()
        {            
            Console.WriteLine(testval);
            Console.WriteLine("foo");
        }

        public async void runtest()
        {
            var this2 = this;
            Global.SetInterval(new Action(delegate()
                {
                    this2.foo();  
                    
                }), 100);
            await Task.Delay(100);
            
            this2.foo();
        }
    }

    public class App
    {
        [Ready]
        public static void Main()
        {
            var c = new class1();
            c.runtest();
        }
    }

**Comment by geoffreymcgill** [comment]
This issue and fix are also related to the following defect reported in the forums:

http://forums.bridge.net/forum/bridge-net-pro/bugs/1324-fixed-690-async-bug-cannot-set-property-of-undefined
