### ISSUE TITLE
"Illegal break statement"

### ISSUE THREAD

**Issue by johnwason** [bridgedotnet/Bridge#691]
I am getting an "illegal break statement" in a complicated string parsing function.  The code except:

    try
            {
                while (pos < lines.Length)
                {
                    while (pos < lines.Length && lines[pos].Length == 0)
                    {
                        pos++;
                    }
                    if (!(pos < lines.Length))
                    {
                        break;
                    }

gets translated as:

    try {
    while (pos < lines.length) {
                var $t = (function () {
                    while (pos < lines.length && lines[pos].length === 0) {
                        pos++;
                    }

                    if (!(pos < lines.length)) {
                        break;
                    }

where a new function is generated to handle the loop. The "break" statement loses its meaning because of the anonymous function definition.  I have not been able to recreate the problem with a simple test case that I can share.  What triggers the generation of the anonymous function instead of a nested loop?

**Comment by vladsch** [comment]
Function will be generated if lambda is defined inside loop body
Function generation emulates .NET closure for loops

http://live.bridge.net/#f3d1cfd91fce49f5d164

**Comment by johnwason** [comment]
Ok, here is a repro

http://live.bridge.net/#d749e949f31df63dd96b
