### ISSUE TITLE
BlobPropertyBag is not defined.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#699]

**Comment by geoffreymcgill** [comment]
Any code sample to reproduce?

**Comment by michaelcheers** [comment]
Blob blob = new Blob(new Any<ArrayBuffer, ArrayBufferView, Blob, string>[]{"blobData"}, new BlobPropertyBag{Type="type"});

PS. consider changing Any<ArrayBuffer, ArrayBufferView, Blob, string>[] to object[].

**Comment by LeonidVeriga** [comment]
We changed constructors to accept `BlobDataObject[]`:
```
public Blob(BlobDataObject[] parts)

public Blob(BlobDataObject[] parts, BlobPropertyBag properties)
```
