### ISSUE TITLE
Console.WriteLine(value) should accept an object as a value not a string.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#700]
```c#
Console.WriteLine(7+5);
```
 works normally.

```c#
[Name("log")]
public static void WriteLine(string message)
{
}
```

should be

```c#
[Attribute("console.log({message}.toString())")]
public static void WriteLine(string message)
{
}
```

**Comment by geoffreymcgill** [comment]
Can you explain further. I might be missing something, but `Console.WriteLine(7+5)` should call the following overload:

```csharp
[Template("console.log({value})")]
public static void WriteLine(int value) { }
```

**Comment by michaelcheers** [comment]
I mean if I've created a class

**Comment by geoffreymcgill** [comment]
Calling `.toString()` is not up to us. The `console` implementation within the client (browser) is determining how to write the values. I don't feel this is a change we should implement. 

If you absolutely want to ensure `.toString()` is called, it would be best to explicitly call the Method.

I'm closing this issue, but will reopen if the discussion continues or if a more convincing argument arises for the use case.
