### ISSUE TITLE
Revise System.Text.RegularExpressions.Regex API to match .NET

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#701]
http://forums.bridge.net/forum/general/feature-requests/1217

Duplicate - #738.

**UPD**: Please see implementation details PR #1153

**Comment by geoffreymcgill** [comment]
**Status Update:** Lots of work is being done on this feature, and hopefully will be included in the 1.12 release.

**Comment by DaniilVeriga** [comment]
Here is the list of supported and not supported features of [.NET Regex engine](https://msdn.microsoft.com/en-us/library/az24scfc%28v=vs.110%29.aspx). The list has been prepared by @AndreyChechel.

1) Character Escapes. Supported.

2) Character Classes. Supported except:
 - Unicode categories `p{name}` and `\P{name}` are not supported. 
 - `\w` and `\W` do not work with Unicode

3) Anchors. Supported except:
 - `\A` `\Z` `\z` `\G` are not supported

4) Grouping Constructs. Supported except:
 - Balancing groups are not supported
 - `imnsx` options are not supported
 - Lookbehind assertions are not supported
 - Nonbacktracking subexpression is not supported

5) Quantifiers. Supported.

6) Backreference Constructs. Supported except:
 - `\k` - not supported

7) Alternation Constructs. Not supported.
8) Substitutions. Supported. (all limitations for Regex itself are applicable here as well)
9) Regular Expression Options - only `CaseInsensitive` and `Multiline` options are supported.
 - Not supported: `Compiled`, `CultureInvariant`, `ECMAScript`, `ExplicitCapture`, `IgnorePatternWhitespace`, `RightToLeft`, `Singleline`

10) Miscellaneous Constructs. Not supported.
