### ISSUE TITLE
Equivalent to native Date.UTC()

### ISSUE THREAD

**Issue by maverix** [bridgedotnet/Bridge#702]
Is there an equivalent to being able to specify if a date is UTC?
i.e. https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC

**Comment by maverix** [comment]
I have a lot of code that is using ScriptSharp's Date object which is very simular to native javascript.
Bridge has the C# DateTime but also a Date object type.  I'm looking at keeping to the Date object type as much as possible to avoid breaking when porting code.

**Comment by maverix** [comment]
Testing against this pattern

var date = new Date(this.year, this.month, this.day).GetUTCDate();

**Comment by geoffreymcgill** [comment]
We are investigating. Just a little back logged with Issues right at the moment, but we'll update this thread once we have a plan.

**Comment by vladsch** [comment]
what about such code
`Date dt = (new DateTime(DateTime.Utc(2000, 1, 1))).As<Date>();`

**Comment by geoffreymcgill** [comment]
How is your code written in ScriptSharp? Maybe we can provide the same api.

**Comment by geoffreymcgill** [comment]
The full native JavaScript Date API is available by adding the [Bridge.Html5](https://www.nuget.org/packages/bridge.html5) package. 

The full native JavaScript Date API would also be available by referencing [Retyped](https://retyped.com).

https://dev.deck.net/7ae948a3c46a82937244ec01e8ef2cfb

```csharp
public class App
{
    public static void Main()
    {
        var d = new Date(2019, 4, 31);
        var e = new Date(Date.UTC(2019, 4, 31));
        
        Console.WriteLine(d);
        Console.WriteLine(e);
        
        var f = new Date(2019, 4, 31).GetUTCDate();
        
        Console.WriteLine(f);
    }
}
```

Hope this helps.
