### ISSUE TITLE
Checking if a Method or Function exists

### ISSUE THREAD

**Issue by maverix** [bridgedotnet/Bridge#703]
Hi All,

I am trying to find out if I can check if a method exists, to avoid calling methods which are undefined.

The example code I am porting checks to see if the **AddEventListener** or the **AttachEvent** method is to be used.  But there are other places where the object is quite unknown until runtime.

Any tips?  Script# used to have a `Script.HasField` method which worked quite well.

I might go with a `Script.Write` for now.

**Comment by maverix** [comment]
Related to this question,  In IE there is no document.addEventListener  and I need to call attachEvent instead.  What is the best practice for this use case?

**Comment by geoffreymcgill** [comment]
I like the idea of `.HasField()`. We will investigate adding this feature.

**Comment by vladsch** [comment]
I guess that you can use `Script.Get<T>(scope, name)` method, like
```
if (Script.Get<bool>(Document.Instance, "addEventListener"))
{
         ....
}
```

**Comment by vladsch** [comment]
Or
```
if (Document.Instance["addEventListener"] != null)
```

**Comment by DaniilVeriga** [comment]
We are closing the issue since there are two options to get a check done.
