### ISSUE TITLE
Document.Body.AppendChild(element) translates as (Bridge.get(Bridge.global).document.body.appendChild(element))

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#705]
Pretty sure this should work--

```c#

using Bridge;
using Bridge.Html5;

/// <summary>
/// Creates a simple class
/// </summary>

class ConsoleWriter
    {
        Element element;

        public ConsoleWriter (Element element, bool newStream = true)
        {
            this.element = element;
            if (newStream)
                Document.Body.AppendChild(element);
        }

        public void Write (object value)
        {
            element.AppendChild(new SpanElement { InnerHTML = value.ToString().Replace("\n", "<br />").Replace("\r", "") });
        }

        public void Write (string value, params object[] format)
        {
            Write(string.Format(value, format));
        }
    }
    public static class App
    {
        static ConsoleWriter writer = new ConsoleWriter(new PreElement());

        [Ready]
        public static void Main()
        {
            writer.Write("Hello World");
        }
}
```

http://live.bridge.net/#ee9aa9c6e52db4f2df41

**Comment by geoffreymcgill** [comment]
Thanks for posting this issue. We are investigating.

**Comment by DaniilVeriga** [comment]
Well, I guess you worry about `Bridge.get(...)` thing, but it is done intentionally fixing #660. @vladsch, maybe, wrapping in `Bridge.get(...)` could be avoided for some classes like `Bridge.global`?

Anyways, there is a different problem that makes your test case not working. Actually, two problems.

1. Document.Body is accessed before it is ready.
`static ConsoleWriter writer = new ConsoleWriter(new PreElement());`
Static fields are being instantiated before Document is ready.

The solution is:
```
public static class App
{
    //static ConsoleWriter writer = new ConsoleWriter(new PreElement());

    static ConsoleWriter writer;

    [Ready]
    public static void Main()
    {
        App.writer = new ConsoleWriter(new PreElement());
        writer.Write("Hello World");
    }
}
```

2. There is a recursion in this method.

```
public void Write(string value, params object[] format)
{
    Write(string.Format(value, format));
}
```

`.Write(string)` calls itself.

A quick solution would be:
`Write(string.Format(value, format) as object);`
just to get your test case working.

**Comment by DaniilVeriga** [comment]
> Well, I guess you worry about `Bridge.get(...)` thing, but it is done intentionally fixing #660. @vladsch, maybe, wrapping in `Bridge.get(...)` could be avoided for some classes like Bridge.global?

Vladimir created [Avoid `Bridge.get` for core classes](#710) issue and already fixed it.
