### ISSUE TITLE
[C#6] Field defaults

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#706]
```csharp
[FieldProperty]
public object value
{
     get;
     set;
} = 7;
```
doesn't keep the default value. 

PS. Do you support C# 6.0?

**Comment by DaniilVeriga** [comment]
C# 6 is a target for Bridge 2.0. Actually, it is already supported there. Once 2.0 is out, you'll get this functionality built in.

**Comment by geoffreymcgill** [comment]
I'm closing this issue as the functionality is complete and will be available in Bridge 2.0.

**Comment by geoffreymcgill** [comment]
This functionality will be included in Auto-Property Initializer support. Planned for Bridge 1.15.

**Comment by LeonidVeriga** [comment]
Related #1435
