### ISSUE TITLE
Type .GetTypeCode() support

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#716]
A feature request has appeared in [this comment](https://github.com/bridgedotnet/Bridge/issues/625#issuecomment-157384864) of #625.

## See Also

- https://forums.bridge.net/forum/community/help/6180-updates-and-problem-encountered

**Comment by geoffreymcgill** [comment]
Support for `GetTypeCode` has been added in the following PR:
https://github.com/bridgedotnet/Bridge/pull/3959

Once final review and testing are complete, the feature will be included in the upcoming Bridge 17.8.0 release.

**Comment by fabriciomurta** [comment]
Pull request looks good to go to the next Bridge release.

**Comment by fabriciomurta** [comment]
The implementation for this looks alright and will make it to the next Bridge release.
