### ISSUE TITLE
Treatment of String methods should be C# or JavaScript wise?

### ISSUE THREAD

**Issue by Mimisss** [bridgedotnet/Bridge#72]
Take substrings for example. The C# developer expects a `ArgumentOutOfRangeException` to be thrown by the following code:

`s.Substring(-2, 8);`

while the translated JavaScript accepts negative values for `startIndex` and behaves much like the JavaScript `substr()`.

**Comment by geoffreymcgill** [comment]
Related: http://forums.bridge.net/forum/community/help/1166-string-substring-is-translated-to-string-substr

**Comment by michaelcheers** [comment]
I think it should be treated C# wise as the code is in C#, especially if inside a `try` block.

**Comment by geoffreymcgill** [comment]
Hi @michaelcheers - We're just about to fix this.

**Comment by LeonidVeriga** [comment]
It was done as part or related #2392.
