### ISSUE TITLE
Document.OnKeyDown must be Action<KeyboardEvent>

### ISSUE THREAD

**Issue by mifwarior** [bridgedotnet/Bridge#729]
.Document.OnKeyDown must be an Action<KeyboardEvent> or KeyboardEvent must have atribute [IgnoreCast] to avoid unnecessary type casting

**Comment by vladsch** [comment]
Thanks for the report, we will review OnKey... events
Regarding casting, you can use `As` extension method to prevent casting emitting
`ev.As<KeyboardEvent>()`

**Comment by DaniilVeriga** [comment]
A generic `Element<>` class has not been updated with new signatures. I am taking on this task.
