### ISSUE TITLE
Build From Sources KB article misses the point how to test those dlls built from sources

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#731]
The article itself:
http://bridge.net/kb/build-from-source

The most elegant solution looks to be incorporating of NuGet packages creation right into the build process.

**UPDATE**: Post a follow-up here - https://github.com/bridgedotnet/Bridge/issues/718#issuecomment-181919745 - once reviewed.

## See Also

* http://forums.bridge.net/forum/general/open-discussions/816

**Comment by DaniilVeriga** [comment]
Currently, NuGet packages creation has been incorporated into the build process. It will be finalized with the 1.11 release and the [Build From Source](http://bridge.net/kb/build-from-source) article will be revised accordingly.

**Comment by t-nelis** [comment]
Hello,

FYI, the KB article in question references `Bridge.Frameworks.Builder.sln`, but it was removed in 61f85c8d091b9f0cc57cf6f9cccf1e0f799c6684 and never re-added. Building from the new `Bridge.sln` works great though. So that would have to be revised as well.

**Comment by DaniilVeriga** [comment]
Thank you for the comment! Yeah, the article is currently outdated.

**Comment by DaniilVeriga** [comment]
There is a discussion on building from sources starting from this comment:

**Comment by DaniilVeriga** [comment]
As of Bridge 1.11 release, NuGet packages are built along with a Bridge build in the Release mode. That extremely simplifies using Bridge when relying on the latest sources. You just build in the Release mode, take a NuGet package within a bin folder and install to your Bridge project. There is a little more details in the blog post:
http://bridge.net/bridge-1-11-released/#Local_NuGet_Packaging

**Comment by geoffreymcgill** [comment]
A new [Build From Source](https://github.com/bridgedotnet/Bridge/wiki/Build-From-Source) wiki document has been published which handles collecting and testing of the NuGet packages.

The wiki document allows for community contributions.

Hope this helps.
