### ISSUE TITLE
System.Collections.Generic.Queue and System.Collections.Generic.Stack not implemented

### ISSUE THREAD

**Issue by johnwason** [bridgedotnet/Bridge#737]
System.Collections.Generic.Queue and System.Collections.Generic.Stack are not currently implemented. While not critical they are frequently used in existing code.

**Comment by DaniilVeriga** [comment]
Please do `Install-Package Bridge.Collections`. It has Stack and Queue. 

Here is a related issue - https://github.com/bridgedotnet/Bridge/issues/99.

**Comment by johnwason** [comment]
Thanks, I didn't notice that package.
