### ISSUE TITLE
System.Text.RegularExpressions.Regex does not match mscorlib

### ISSUE THREAD

**Issue by johnwason** [bridgedotnet/Bridge#738]
The implementation of System.Text.RegularExpressions.Regex does not  match the functionality of the standard implementation found in mscorlib.  This has made porting existing code difficult.  A proposed solution is to move the current implementation into the Bride namespace and implement a version that matches the existing signature in the System.Text.RegularExpressions namespace.

**Comment by DaniilVeriga** [comment]
Thank you for the feedback!

It duplicates #701. Matching .NET Regex API is what we are going to do. I will rename the issue's title to reflect it.
