### ISSUE TITLE
The "GenerateScript" task failed unexpectedly

### ISSUE THREAD

**Issue by yuriberi** [bridgedotnet/Bridge#745]
While building a project I got the following error

```The "GenerateScript" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Bridge.Contract.EmitterException.get_FileName()
   at Bridge.Build.GenerateScript.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()```

**Comment by DaniilVeriga** [comment]
Thank you for the report! Could you, please, provide a test case?

**Comment by yuriberi** [comment]
Hi Daniil,

I've tried to convert C# solution big enough. To make it as the test case I
need to shrink it.Currently, I'am busy, will try to do that in a couple of
days.

Yuri

**Comment by DaniilVeriga** [comment]
Thank you! It would be a great help.

**Comment by yuriberi** [comment]
I've refactored my C# code and the issue has gone.

**Comment by DaniilVeriga** [comment]
Thank you for the update.

Okay, I am labeling the issue as `question` and closing. If the same issue appears again, please feel free to comment here and we'll re-open the issue.
