### ISSUE TITLE
Knockout Observables

### ISSUE THREAD

**Issue by maverix** [bridgedotnet/Bridge#757]
http://live.bridge.net/#c4565dcbc66e8b4a7bc7

I am trying to get the outputted JS to match how Knockout.js is used normally.

    [Name("")]
    public string GetValue() {
        return "";
    }

this should convert to someproperty();  instead it is outputted with an extra dot i.e. someproperty.();

**Comment by maverix** [comment]
refernce https://github.com/maverix/ScriptSharpKnockout/blob/master/src/Observable.cs

**Comment by maverix** [comment]
encase my first comment wasn't clear.

someproperty.GetValue();  should be represented in javascript as someproperty();

of course, I might be stuck in the ScriptSharp way of doing things and there might be an entirely different way of representing a Knockout observable which is essentially a Function with Properties and Methods attached to it (JS is a crazy dynamic language)

**Comment by vladsch** [comment]
Not sure if clear understood you but do you need such code?
http://live.bridge.net/#0ee1452f3b1c2a1530fa

I mean to use `[Template("{this}()")]` for GetValue instead Name attribute

**Comment by maverix** [comment]
Perfect. I was hoping for something in the template attribute, but couldn't find the magic string

**Comment by maverix** [comment]
http://live.bridge.net/#cb089aa55fdeb2748a28

Yep looks good.  Thanks!
