### ISSUE TITLE
Avoiding bridge.get for External static methods

### ISSUE THREAD

**Issue by maverix** [bridgedotnet/Bridge#764]
https://github.com/bridgedotnet/Bridge/issues/710

I saw in this PR that there is a way to indicate that a class doesn't need the bridge.get wrapper.
By the way, could someone explain what the heck it is doing for external classes?

Is there an attribute or method for indicating that my wrapper for knockout doesn't need to be 
`bridge.get(ko).observable('');`

**Comment by maverix** [comment]
https://github.com/bridgedotnet/Frameworks/blob/master/jQuery2/jQuery.cs

Okay, think I have got it sorted out. Sorry!

**Comment by DaniilVeriga** [comment]
@maverix, could you, please, clarify can we consider the question as resolved?

**Comment by maverix** [comment]
I reopened it because of the milestone tagging.  I haven't gotten around to testing if the issue is actually resolved

**Comment by maverix** [comment]
All good, just needed to add an explicit Template attribute to all of the Static methods
