### ISSUE TITLE
bridge.js raises an exception if load it after dom is ready

### ISSUE THREAD

**Issue by vladsch** [bridgedotnet/Bridge#768]
http://forums.bridge.net/forum/bridge-net-pro/bugs/1228

**Comment by DaniilVeriga** [comment]
The issue was also reported in this [forum thread](http://forums.bridge.net/forum/community/help/1364). Fixed there as well.

**Comment by Slavery** [comment]
Hey! I'm the guy from the forum thread. Any idea when the merge into master will be done (And that visual studio will use that specific version?)

**Comment by DaniilVeriga** [comment]
Hi @Slavery,

It looks like the [pull request](https://github.com/bridgedotnet/Bridge/pull/769) has been merged before you asked:) 

> (And that visual studio will use that specific version?)

The same Bridge is used for all the VIsual Studios.

Actually, we've already released Bridge 1.10.3 to NuGet. Please give it a try.
