### ISSUE TITLE
Use TypedArrays instead of normal array

### ISSUE THREAD

**Issue by Danielku15** [bridgedotnet/Bridge#772]
Currently Bridge generates numeric arrays as normal JavaScript arrays.
It would be great if bridge would generate them as Typed Arrays (depending on option `"useTypedArrays"` in **bridge.json**): 

**C#**

	var byteArray = new byte[256];
	var sbyteArray = new sbyte[256];
	var shortArray = new short[256];
	var ushortArray = new ushort[256];
	var intArray = new int[256];
	var uintArray = new uint[256];
	var floatArray = new float[256];
	var doubleArray = new double[256];

**JavaScript**

	// https://developer.mozilla.org/de/docs/Web/JavaScript/Typed_arrays
	var byteArray = new Uint8Array(256);
	var sbyteArray = new Int8Array(256);
	var shortArray = new Int16Array(256);
	var ushortArray = new Uint16Array(256);
	var intArray = new Int32Array(256);
	var uintArray = new Uint32Array(256);
	var floatArray = new Float32Array(256);
	var doubleArray = new Float64Array(256);

**Comment by Danielku15** [comment]
I opened a new pull request for this feature (#773). The feature is currently designed as an opt-in via bridge.json.

**Comment by DaniilVeriga** [comment]
@Danielku15, thank you very much for submitting an issue and a pull request!

Interesting that this feature has been requested by another community member in this forum thread:
http://forums.bridge.net/forum/general/open-discussions/1320

**Comment by johnwason** [comment]
Note that the JavaScript function "Array.isArray" returns false for typed arrays.  In C# these types have Array as a superclass so it is a wrinkle that can cause some issues if not taken into consideration.
