### ISSUE TITLE
Type "long" has no support and unpredictable behavior

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#778]
http://forums.bridge.net/forum/general/open-discussions/1320

There are related questions in this forum thread:
http://forums.bridge.net/forum/bridge-net-pro/bugs/1871

After implementing, there should be changes in https://github.com/bridgedotnet/Bridge/blob/master/Bridge/Resources/Convert.js see TODO with text #778

**Comment by geoffreymcgill** [comment]
More `long` tests:

http://live.bridge.net/#e082077c4d54a8a05ecb
http://live.bridge.net/#a699118bdf757a79ec83

See also Twitter thread from @Shmuelie:
https://twitter.com/shmuelie/status/687046291780677632

**Comment by SamuelEnglard** [comment]
In theory I'd take a look at how either JSIL does it (https://github.com/sq/JSIL/blob/master/JSIL.Libraries/Includes/Bootstrap/Int/Classes/System.Int64.js) or if you feel like being crazy you could do what I did (https://github.com/SamuelEnglard/CIL.JS/blob/master/Runtime/Integer.ts)
