### ISSUE TITLE
Consider support/handling of System.IO

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#779]
http://forums.bridge.net/forum/general/open-discussions/1320

> The System.IO namespace appears to be unimplemented. At least some basic support should be available as an extension package. Especially the exceptions like System.IO.TimeoutException should be available. While they are in the System.IO namespace they get used elsewhere.
> 
> In terms of the System.IO namespace, I think supporting Stream, Reader, Writer, and MemoryStream along with the readers/writers such as BinaryReader, BinaryWriter, TextReader, TextWriter etc would be sufficient. It would at least allow existing code that accepts a stream/reader/writer parameter. It occurs to me supporting the encoding classes would probably be necessary to help with the IO routines as well.

**Comment by PluginIO** [comment]
Hi, is there any movement on this? I am really hoping to get access to the following:

System.IO.Stream
System.IOBinaryWriter
System.IO.BinaryReader

Together these 3 classes would support almost any case for reading and writing data efficiently from a HTML5 Typed Array. 

My case is a complete 3D engine platform and editor where all resource data is abstracted to a byte[]. If correctly implemented, the data should be read as a stream, along with pointer offsets, as this is highly optimized and required for the WebGL buffer channels.

Link to reference and notable nod to WebGL. [http://www.html5rocks.com/en/tutorials/webgl/typed_arrays/](url)

**Comment by geoffreymcgill** [comment]
Hello. Unfortunately we have not been able to make any progress with this functionality.

**Comment by michaelcheers** [comment]
@PluginIO, I have made a pull request: #2789. It has MemoryStream, BinaryWriter, BinaryReader and Stream. BinaryWriter and BinaryReader do not have Write(string) and ReadString since there are no Encodings.

**Comment by PluginIO** [comment]
This is really great news. I will take a look ASAP and thanks for the heads up.
