### ISSUE TITLE
Consider support/handling of System.Net

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#780]
http://forums.bridge.net/forum/general/open-discussions/1320

> Some basic support for System.Net would be helpful along with System.Net.WebSockets

> For System.NET I am mainly missing the URI class. I think the ClientWebSocket class can simply wrap the built in browser WebSocket as it doesn't implement non-async members.

Relates to #776.

**Comment by LeonidVeriga** [comment]
[MSDN ClientWebSocket Class](https://msdn.microsoft.com/en-us/library/system.net.websockets.clientwebsocket(v=vs.110).aspx)

Underlying implemention according to [MDN WebSockets](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API)
