### ISSUE TITLE
Gamepad support

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#781]
http://forums.bridge.net/forum/general/open-discussions/1320

> A wrapper class for the Gamepad objects would be cleaner than using "dynamic".

[MDN Gamepad API](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API)
[MDN Using the Gamepad API](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API#Browser_compatibility)

**Comment by michaelcheers** [comment]
[Pull request](https://github.com/bridgedotnet/Bridge/issues/1358)

**Comment by LeonidVeriga** [comment]
Thanks to @michaelcheers contribution we added Gamepad support into 1.14.
