### ISSUE TITLE
Interfaces don't emit methods

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#784]
The problem is stated in this [forum post](http://forums.bridge.net/forum/general/extensions-and-plugins/998?p=1239#post1239).

Is it intentional for some technical reason, a defect or a missed feature?

**Comment by vladsch** [comment]
What a sense to emit methods signatures to interface? I see only one case: reflection
But v1 does not support reflection

**Comment by DaniilVeriga** [comment]
I've [asked](http://forums.bridge.net/forum/general/extensions-and-plugins/998-documentation-of-how-to-make-a-plugin?p=1399#post1399) the member to clarify a use case.

**Comment by DaniilVeriga** [comment]
Currently, we don't know any use case instead of Reflection which is not supported and is not going to supported in Bridge v1. Fortunately, Reflection is supported in Bridge v2.0 (private still) and most likely the issue will just disappear with Bridge v2.0 release. We leave the issue open to review in the future with releasing v2.0.

**Comment by michaelcheers** [comment]
@DaniilVeriga @vladsch  Related #1313. This is one reason why it might be useful.

**Comment by LeonidVeriga** [comment]
Closing the issue as reflecion functionality is implemented in #15.

Replied on the forum thread http://forums.bridge.net/forum/general/extensions-and-plugins/998-documentation-of-how-to-make-a-plugin?p=3330#post3330
