### ISSUE TITLE
ReadOnlyCollection Bug

### ISSUE THREAD

**Issue by Slavery** [bridgedotnet/Bridge#793]
My Code:

```csharp
[Ready]
        public static void Main()
        {
            List<string> js = new List<string>();
            js.Add("1");
            ReadOnlyCollection<string> test = new ReadOnlyCollection<string>(js);

            Console.Log(test);
        }
```

Uncaught TypeError: Cannot read property 'call' of undefined(…)

Stack trace:

http://i.imgur.com/GaZ3Z11.png

The line it errors out:
http://i.imgur.com/bT8lAiK.png

**Comment by fabriciomurta** [comment]
I could reproduce your issue on this [Live Bridge snippet](http://live.bridge.net/#09fa572766b644d7a3aa).

Thanks for reporting! We will investigate the issue and get back to you as soon as possible!
