### ISSUE TITLE
AngularJS Demo Fn is not convert correctly

### ISSUE THREAD

**Issue by chiangim** [bridgedotnet/Bridge#794]
AngularJSDemo\Functions.cs
-------------------------------------
```
public static Resource PhoneServicesFactoryFn(
            [Name("$resource")]
            Func<string, object, ResourceActions, Resource>
            resource)
        {
            return resource("data/:id.json", new object
            {
            },
                new ResourceActions
            {
                Query = new ActionInfo()
                {
                    Method = "GET",
                    Params = new
                    {
                        Id = "phones"
                    },
                    IsArray = true
                }
            });
        }
```
seem always convert to javascript content as below:-
```
phoneServicesFactoryFn: function ($resource) {
            return resource("data/:id.json", { }, { query: { method: "GET", params: { id: "phones" }, isArray: true } });
        }
```

I change it to output file by replace resource to $resource. And it success render the page.

It happen to routeProvider parameter as well.

**Comment by fabriciomurta** [comment]
Hello, thank you very much for pointing this, I'm investigating it right away!

**Comment by fabriciomurta** [comment]
Hello, I've narrowed down the issue to this:
http://live.bridge.net/#294050e00d5f52ae580b

Thank you again for reporting this problem!

**Comment by fabriciomurta** [comment]
Hello @chiangim! The related issue has been fixed! Would you mind testing and letting us know if the demo project now works for you?

**Comment by fabriciomurta** [comment]
I've just tested latest bridge code and it works fine, so I'm closing this. Still, your feedback is appreciated!

**Comment by chiangim** [comment]
Tested with 1.10.4. It is working fine now. Thanks!!
