### ISSUE TITLE
jQuery Template Bug - & instead of $

### ISSUE THREAD

**Issue by maverix** [bridgedotnet/Bridge#797]
Hi I have reproduced an issue I am seeing using the Param function in jQuery
http://live.bridge.net/#9f62a426ea8b07d33d53

var url = &.param(parameters);

instead of 

var url = $.param(parameters);

**Comment by maverix** [comment]
Sorry, wrong project... 

Moved to the correct one  https://github.com/bridgedotnet/Frameworks/issues/30

**Comment by fabriciomurta** [comment]
This is most likely related to #796.
