### ISSUE TITLE
Class Dependency and Ordering

### ISSUE THREAD

**Issue by maverix** [bridgedotnet/Bridge#798]
I'm hitting a lot of issues with a port from Script Sharp.  

The order in which classes are defined (bridge.define('something')) is causing me issues as classes are calling other classes which Bridge doesn't know about yet (Could be just Static Methods)

A safer approach would be to ensure all of the calls to Bridge.Define() are allowed with the internal deferred until the end of this first pass.

Otherwise I'm stuck with the manual task of trying to sort out my dependency tree via Priority attributes, which is effectively a deal breaker right there for me

Thoughts?

**Comment by vladsch** [comment]
I am not sure what kind of dependency do you mean? Can you demonstrate it? And please describe how do you solve such issue in Scripture Sharp
Bridge should automatically resolves ordering of classes in Javascript. Also initialization of static members is deferred until first access to the class

**Comment by maverix** [comment]
Putting together a repro now.

**Comment by maverix** [comment]
Reproduction >> https://github.com/maverix/SLC.Bridge/

In the repro, the TestResultModel which inherits from the TestResult class will throw an exception saying that the 'TestResult is not defined'.  

Issue disappears if the TestResultController is removed
https://github.com/maverix/SLC.Bridge/blob/master/SLC/Campaigns/TestResultController.cs

**Comment by maverix** [comment]
@vladsch In script sharp I didn't have this issue

**Comment by vladsch** [comment]
Thanks for your report, i will investigate it tomorrow and will provide solutions how to resolve it
Thanks for using Bridge.NET

**Comment by vladsch** [comment]
The problem that by default, Bridge split output by namespace (js classes from different namespaces will be in different files). In this case, dependency from different namespaces are not handled

Please set `"outputBy": "Project"` in bridge.json to resolve it (in this case all classes will be in one file and sequence of classes will be correct in javascript)

**Comment by vladsch** [comment]
I created an issue for that
https://github.com/bridgedotnet/Bridge/issues/801

**Comment by maverix** [comment]
Thanks @vladsch! I won't be able to test the fix until tomorrow.  But thanks again for the prompt responses and solutions!

**Comment by LeonidVeriga** [comment]
Fixed in #801
