### ISSUE TITLE
Stub out related Canvas Context 2D classes

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#8]
Members should be implemented before final v1.0 release

**Comment by fabriciomurta** [comment]
I need this on something I am doing right now so I will try and implement this issue.

**Comment by fabriciomurta** [comment]
Thought it would be very quick but it has tons of information to be added. To this point, a good part of the functionality on the CanvasRenderingContext2D is already mapped to Bridge.NET.
There's several more updates to the code and documentation that will be made following this point.

**Comment by fabriciomurta** [comment]
Next steps, proceed to the `#region Transformations` until the end of the file.

**Comment by DaniilVeriga** [comment]
@fabriciomurta, please close the issue if you are done with 2D rendering context. 

As for WebGL, I created a separate issue - #189. I'll be committing soon the implementation.
