### ISSUE TITLE
ReferenceError document is undefined if running in WebWorkers

### ISSUE THREAD

**Issue by Danielku15** [bridgedotnet/Bridge#802]
I found an issue in the core library if the compiled executable is running in WebWorkers. As you might know WebWorkers don't have a defined `document` but the Core.js and Browser.js directly access the document variable which triggers an error when using `"use strict"`.

The solution is to use `Bridge.global` for those checks and then precheck if document is defined properly. 

Opened Pull Request #803 containing a fix.

**Comment by DaniilVeriga** [comment]
There is a related forum thread (just for references):
http://forums.bridge.net/forum/bridge-net-pro/bugs/1393
