### ISSUE TITLE
ES6 Module support

### ISSUE THREAD

**Issue by kasperp** [bridgedotnet/Bridge#814]
As discussed on #258 ES6 module support would also a nice addition. 

@DaniilVeriga I hope it is ok that I open this issue, let me know if you'd rather have it go through your forum. Also feel free to close it if es6 modules isn't relevant for the project.

**Comment by DaniilVeriga** [comment]
Thank you for the feature request! A forum thread is not required. Usually, if you are sure with a feature request or a bug report, GitHub is a place to go. But if you are not sure and some preliminary discussion might be good to have, then the forums is an ideal place. Sure, a discussion is possible via GitHub comments as well and we do that, but the forums looks to me a little more suitable place.

**Comment by geoffreymcgill** [comment]
Module support has been completely redesigned and will be available in the next release of Bridge. See Issue #2217. CommonJS is now supported.
