### ISSUE TITLE
Char.IsLetterOrDigit does not work with ! Operator

### ISSUE THREAD

**Issue by dpbayer** [bridgedotnet/Bridge#817]
Using the `!` operator on some conditions, does not create correct Javascript

```csharp
int z=0;  
char a='A';
if (! Char.IsLetterOrDigit(a) ) {
    z=100;
}
```

Creates the following:

```javascript   
var z = 0;
var a = 65;
if (!Bridge.Char.isDigit(a) || Bridge.Char.isLetter(a)) {
    z = 100;
}
```

The `!` operator has been applied to only part of the original condition.
 
There maybe a few other methods which emit  Condition `||` Condition or Condition `&&` Condition, and cause issues with the `!` operator.

**Comment by DaniilVeriga** [comment]
@dpbayer, thank you for the report! We are investigating.
