### ISSUE TITLE
For Loop with Empty Condition Issue

### ISSUE THREAD

**Issue by dpbayer** [bridgedotnet/Bridge#818]
When using a FOR loop with no condition, the Javascript emits null, which results in different runtime behaviour..

```csharp
for(;;) {
    z++;
    if (z==10) break;
}
```

Emits the following:

```javascript
var z = 0;
for (; null; ) {
    z++;
    if (z === 10) {
        break;
    }
}
```

Also For Loops do not accept multi statement initialisers. This is deliberately blocked in the Builder code, but would be helpful if supported.

```javascript
for(i=0, j>1; i<100; i++) {

}
```

**Comment by DaniilVeriga** [comment]
@dpbayer, thank you for the report! We are investigating.
