### ISSUE TITLE
Generics IComparer Interface and Global preserveMemberCase Option

### ISSUE THREAD

**Issue by dpbayer** [bridgedotnet/Bridge#819]
When using the preserveMemberCase option, the generated Javascript for the IComparer<> interface is incorrect:

``` csharp
public class MyTestCompare : IComparer<int>
    {
        public int Compare(int x, int y)
        {
            return x - y;
        }
    }
```

Will emit:

``` javascript
Bridge.define('TestIssue.MyTestCompare', {
    inherits: [Bridge.IComparer$1(Bridge.Int)],
    Compare: function (x, y) {
        return x - y;
    }
});
```

However, in the implementation of Bridge.IComparer, the method is 'compare'. not 'Compare'

**Comment by DaniilVeriga** [comment]
@dpbayer, thank you for the report! We are investigating.

**Comment by DaniilVeriga** [comment]
`preserveMemberCase` appeared in #311.

**Comment by DaniilVeriga** [comment]
Maybe, introducing the `preserveMemberCase` setting was a mistake, because it leads to many undesired/unexpected backside effects like that. At the moment, we are not sure what to do.

**Comment by geoffreymcgill** [comment]
We discussed this scenario. We're thinking of removing the `preserveMemberCase` option. 

Can you provide a few comments on the use-case for your project regarding `preserveMemberCase`? There might be another approach we could recommend. 

Just need a little feedback from you so we completely understand the situation before making any decisions.

**Comment by geoffreymcgill** [comment]
The `preserveMemberCase` config is being removed in Bridge 16.0.

Please see Issues #2476 and #2477 for further details.
