### ISSUE TITLE
IConvertible interface is not supported

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#822]
IConvertible interface is not supported at the moment. This issue also relates to #14 where Convert class uses IConvertible for the methods accepting objects as a parameters.

Example:

``` C#
public static bool ToBoolean(object value)
{
  if (value != null)
    return ((IConvertible) value).ToBoolean((IFormatProvider) null);
  return false;
}
```

Btw I'm trying to implement missed Convert class now, I believe I'll be able to share my solution within a week. Your code review/comments would be much appreciated.

After implementing, there should be changes in https://github.com/bridgedotnet/Bridge/blob/master/Bridge/Resources/Convert.js see TODO with text #822

Relates to #977.

**Comment by DaniilVeriga** [comment]
Thank you for the report!

**Comment by fabriciomurta** [comment]
The pull request for #716 also implements the logic that was left as `TODO #822` like described in the initial comment of this issue. The sample code works on deck regardless of that (without pr #3959), so at least part of this has already been implemented for some time.
