### ISSUE TITLE
Heisenbug: Exception handler missed without magic comment

### ISSUE THREAD

**Issue by t-nelis** [bridgedotnet/Bridge#830]
Hello,

Here is a fun one to brighten your day. (Don't worry, we've already opened the box; the cat is pretty much dead.)

# Overview

We wrote this asynchronous method with a `try` block and a `catch` clause. Immediately preceding the `try` block is a magic comment (content doesn't matter): if we remove the comment, exceptions thrown in the `try` block miss the handler and get rethrown elsewhere where they're not expected.

(This was a real puzzler since we originally saw the undesired behavior, then wrote the comment to point it out in order to describe it in this report, and couldn't figure out why we suddenly couldn't reproduce the behavior.)

# Explanation

Turns out, the compiler somehow emits an apparently unneeded step in the state machine. We assume because of an unrelated optimization pass, the step is then "collapsed" with the next one (since it does nothing) by having the `switch` `case` block fall through to it.

    ...
    performRequest: function (method, uri, timeout) {
        var $step = 0,
            ...
            $returnTask = new Bridge.Task(),
            ...
            task, 
            exception,
            ...
            $asyncBody = Bridge.fn.bind(this, function () {
                try {
                    for (;;) {
                        switch ($step) {
                            ...
                            case 4: 
                            case 5: {
                            ...
                        }
                    }

(Notice step 4 is apparently unneeded and immediately falls through to step 5.)

Aside from the weird step, so far so good. However, the exception handler filters exceptions based on the current step since it will receive exceptions from the entire state machine. If the exception doesn't come from a step from which it was expected (i.e. the right `try` block) the compiler emits code to appropriately fault the task. Again, perfectly OK.

                } catch($e1) {
                    $e1 = Bridge.Exception.create($e1);
                    if ( $step >= 5 && $step <= 6 ){
                        exception = $e1;
                        $step = 7;
                        setTimeout($asyncBody, 0);
                        return;
                    }
                    $returnTask.setError($e1);
                }
            }, arguments);

        $asyncBody();
        return $returnTask;
    },
    ...

(Notice the range of filtered steps is 5-6, not 4-6.)

Yet, we *always* observe the task-faulting behavior even for exceptions that *should* be handled. How come?

- Previous steps will still transition to step 4, but none will transition to step 5. As a result, the code in step 5 is always executed *as* step 4.

- However, the exception handler covers steps 5 to 6, not 4.

Because of both these things, no exceptions thrown in step 5 (which covers almost the entire `try` block) will ever be caught (and will systematically fault the task instead). Evidently, two components of the compiler are somehow stepping on each other's toes.

# Workaround

So that covers the bug. As a workaround for readers who might encounter this behavior before it can be addressed, adding a comment immediately before the `try` block is apparently enough to prevent the compiler from "optimizing" the steps ("collapsing" them using switch fallthrough behavior).

Instead, it will emit a step which simply does nothing.

                            ...
                            case 4: {
                                // MAGIC
                                $step = 5;
                                continue;
                            }
                            case 5: {
                            ...

If you're reading in a hurry, subsequent post-compilation minification passes that strip comments shouldn't pose issues with this workaround. This has to do strictly with the JS emitter, not the JS parser (which wouldn't be a Bridge problem).

# Repro

Unfortunately I don't personally have too much time to isolate this further (I might later), so for now I'll just have to dump the entire method on you guys. (Sorry.)

Here is the [relevant gist](https://gist.github.com/t-nelis/63a0b59c3dc9748a8786).

The two files prefixed with `magic` are those containing the magic comment.
The two files suffixed with `input` are the source C# methods.
The two files suffixed with `output` are the emitted target JS functions.

Observed in 1.10.4.

Context (just in case): The method is part of an XHR wrapper that uses an `IPromise` thunk (`Promise`) to register event listeners and funnel them to the `fulfilledHandler` (obviously this is a case where `TaskCompletionSource` is more appropriate, we're looking forward to v2). None of this should be important to understand the bug.

Sidenote: I initially intended to remove comments pertaining to unrelated issues, but reading them again I thought of leaving them in as they might also be of interest (there is at least another juicy bug related to operator precedence in there). I'll try and make another pass at it and properly report what's worth reporting if I get more time later.

Thanks for reading.

**Comment by vladsch** [comment]
Thanks for the excelent and clear issue description (you have a talent for it)
So we can only fix it

**Comment by geoffreymcgill** [comment]
Hi @t-nelis, thanks for the great bug report. We discussed this issue today at our team meeting and have made it a priority to fix.

When you have a chance, please send me (geoff@object.net) a quick email. I have a couple questions for you that are best asked offline.

**Comment by vladsch** [comment]
Test case for reproducing
```
private static async Task<Exception> TestMethod(
            string method)
        {
            if (method == null)
            {
                throw new ArgumentNullException("method");
            }

            try
            {
                var task = Task.FromResult(new Exception("Success"));
                return await task;
            }
            catch (Exception exception)
            {
                return new Exception("Fail");
            }
        }
```

**Comment by vladsch** [comment]
Also, I noticed that you gist sample uses C# 6 because `await` in catch statement is supported in C# 6 only
Please do not use C# 6 for Bridge v1 projects

**Comment by t-nelis** [comment]
@vladsch Thanks for the clarification; this one we already refactored by chance for unrelated reasons, but it definitely warrants a little review pass of the codebase.

Nice work on a swift isolation & fix, we appreciate it!

**Comment by DaniilVeriga** [comment]
Just realized that is definitely worth to [tweet](https://twitter.com/bridgedotnet/status/694193698620313600) about this bug report:)
