### ISSUE TITLE
DateTime.ParseExact() fails if a format contains escaping characters

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#87]
**Test Case**

    using System;
    using Bridge;
    using Bridge.Html5;

    namespace Demo
    {
        public class App
        {
            [DOMContentLoaded]
            public static void Main()
            {
                var dateTime = DateTime.ParseExact("2015-03-25T01:08:13", "yyyy-MM-dd\\THH:mm:ss", System.Globalization.CultureInfo.InvariantCulture);
                Console.Log(dateTime);
            }
        }
    }

**Actual result:** `Uncaught String does not contain a valid string representation of a date and time.`

**Expected result:** the string is parsed successfully.

**Comment by fabriciomurta** [comment]
Still failing if you escape an actual interpreted char like H, M, y, s, etc.

In JavaScript,
`var dateTime = DateTime.ParseExact("2015-03-25H01:08:13", "yyyy-MM-dd\\HHH:mm:ss", System.Globalization.CultureInfo.InvariantCulture);`
or
`var dateTime = DateTime.ParseExact("2015-03-25y01:08:13", "yyyy-MM-dd\\yHH:mm:ss", System.Globalization.CultureInfo.InvariantCulture);`

Are some examples of this.
