### ISSUE TITLE
Inline Code comments do not emit when inside a switch-statement

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#874]
Related forum thread:

http://forums.bridge.net/forum/bridge-net-pro/bugs/1508-bridge-1-10-4-inline-code-doesn-t-work-inside-a-switch-statement

Live Bridge test case:

http://live.bridge.net/#2b00a1f2ac8637e1a599

**Comment by fabriciomurta** [comment]
This issue is pretty much related to #139, I believe.
