### ISSUE TITLE
Accessing params object[] by index does not compile

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#89]
Just add this class into your code and the project does not compile:
```C#
using System;
using Bridge;

namespace Demo
{
    public class Class1
    {
        void Test(params object[] p)
        {
            var i = p[0];
        }
    }
}
   
```
The problem is in `var i = p[0];` line accessing `p[0]`

VS shows an error message `Object reference not set to an instance of an object.` with no additional details.

**Comment by vladsch** [comment]
I cannot reproduce the issue. Code is translated for me
```
Bridge.Class.define('Demo.Class1', {
    test: function (p) {
        var i = p[0];
    }
});
```

**Comment by LeonidVeriga** [comment]
It is reproducible on the latest version. Probably your local changes fixes the issue.

**Comment by vladsch** [comment]
Please retest after my commit
