### ISSUE TITLE
Params issue when passing params across methods

### ISSUE THREAD

**Issue by strygo** [bridgedotnet/Bridge#892]
When passing params from one method to another, the parameters get nested. For example:

```
    public class App
    {
        public static void Test(string format, params object[] p)
        {
            var message = String.Format(format, p);

            var test = 0;
        }

        [Ready]
        public static void Main()
        {
            Test("Test {0} {1}", "One", "Two");
        }
    }
```

In this case, String.Format() throws an exception because the param array becomes an array of an array.  The error observed:

```
Uncaught Input string was not in a correct format.
```

While String.Format exhibits this problem, any usage of this type will likely lead to a runtime error.

**Comment by vladsch** [comment]
The issue is actual for methods with Template attribute. Bridge do not expand array of parameters to separate params for template. We will fix it.

> because the param array becomes an array of an array
no, it is still simple array, just javascript implementation do not expect array (only separate params)
