### ISSUE TITLE
Runtime problem: Bridge.merge() doesn't merge nested types

### ISSUE THREAD

**Issue by strygo** [bridgedotnet/Bridge#894]
Sample:

```
    public class App
    {
        public class ParentClass
        {
            public ChildClass Child
            {
                get;
                set;
            }
        }

        public class ChildClass
        {
            public int Count
            {
                get;
                set;
            }
        }

        [Ready]
        public static void Main()
        {
            var parent = new ParentClass();
            parent.Child = new ChildClass();
            parent.Child.Count = 3;

            var str = JSON.Stringify(parent);

            var obj = JSON.Parse<ParentClass>(str);

            Global.Alert(parent.Child.GetClassName() + " : " + obj.Child.GetClassName());
        }
    }
```

Observe that the type information is lost on the child type. This is problematic because if you try to access properties on the child, they can't be found since they don't match what the code is expecting.

Are there any workarounds for this?

**Comment by geoffreymcgill** [comment]
This is related to Issue #15 and the following forum thread:

http://forums.bridge.net/forum/community/help/1417-json-parse-does-not-properly-fill-in-sub-objects

I don't think this going to be fully supported until Bridge 2.0.

**Comment by strygo** [comment]
Got it. Thanks. Are there any workarounds at this time?

**Comment by DaniilVeriga** [comment]
Sorry for the delay in answering. In my best understanding there is currently no workaround, i.e. `Json.Parse<>()` is not going to work with complex types like you tried with. Actually, there is a dedicated issue (and a bunch of related forum threads) for that - #98 which is one of high priorities for v2. I referenced the current issue there and going to close it.

So, no workaround for `Json.Parse<>()`, but there is a solution for the overall scenario - parsing the data manually. If you know the data structure, then it is not going to be a problem. I mean creating a helper method to build a class instance from a raw piece of data. 

This approach is used in the [Work With Data](http://bridge.net/kb/work-with-data/) knowledge base article. There is an AJAX Success handler with the following code:
`Form template = new Form(data);`

The source of the `Form()` constructor is here:
https://github.com/bridgedotnet/Demos/blob/master/Combination_Samples/FormBuilder/FormBuilder/BridgeForm.cs
