### ISSUE TITLE
Console.WriteLine of type "dynamic" results in an odd error message

### ISSUE THREAD

**Issue by johnwason** [bridgedotnet/Bridge#919]
Trying to print out a dynamic variable results in an odd error message.  Writing a variable to the log is very useful because chrome logs the entire variable.

http://deck.net/7867e061c602398c49836f186f7637b4

```c#
dynamic a = new object() as dynamic;
Console.WriteLine(a);
```

results in

```
// Line 0, Col 0 : Cannot compile this dynamic invocation because there are two or more method overloads with the same parameter count. To work around this limitation, assign the dynamic value to a non-dynamic variable before use or call a method with different parameter count
```

**Comment by vladsch** [comment]
It is expected error because during compilation to javascript Bridge don't know type of dynamic variable therefore Bridge cannot determine which overload method of WriteLine need to use

**Comment by DaniilVeriga** [comment]
@johnwason, I am closing the issue for now, but if you have something to add, please, certainly, feel free to comment.

**Comment by geoffreymcgill** [comment]
We need to discuss this issue. The Bridge behaviour is different than the native (and expected) .NET compiler behaviour.

**Comment by geoffreymcgill** [comment]
So the difference between the NET runtime and JavaScript is where the issue occurs. The underlying type of a dynamic can be determined at runtime by .NET, but in JavaScript it cannot. Because the type is determined at runtime in .NET, the correct overloaded Method is selected. JavaScript does not have enough information to ensure the correct overload is selected. 

We should be able to add an additional `dynamic` type overload to the `WriteLine` (and related) members. That extra overload will enable your original scenario. This same approach might be applied to other overloading scenarios within Bridge as well. We need to investigate before coming up with a list.

**Comment by geoffreymcgill** [comment]
It appears adding another `dynamic` overload is not possible when an `object` overload is already present. The two types are basically treated the same during compile time. More info:

http://stackoverflow.com/a/31375138/501102

We need to think up a different approach.

**Comment by geoffreymcgill** [comment]
I have to bump this to the next release.

**Comment by geoffreymcgill** [comment]
Related forum thread:

http://forums.bridge.net/forum/community/help/2160-how-to-use-dynamic-type

**Comment by michaelcheers** [comment]
@geoffreymcgill, any updates on this?

**Comment by geoffreymcgill** [comment]
@michaelcheers – At the moment there is no change to this issue, but I have tagged with the 16.1 milestone, so we'll do our best to review fully and try to find a solution.

**Comment by geoffreymcgill** [comment]
It appears a change in a previous release had the side-effect of getting this issue working. At least with my testing, passing a `dynamic` to `Console.WriteLine` is working well now. 

https://deck.net/3a905838ad8fa275f2aaafb194518dc2

```csharp
public class Program
{
    public static void Main()
    {
        dynamic obj = new object() as dynamic;
        
        obj.id = 123;
        
        // { "id": 123 }
		Console.WriteLine(obj);
        
		dynamic foo = 123;
		foo = "foo";
		
        // bar
		Console.WriteLine(foo);
        
		// Use dynamic local.
        dynamic a = 123;
        
        // 123
        Console.WriteLine(a);

        // Dynamic now has a different type.
        a = new string[1] { "bar" };
        
        // bar
        Console.WriteLine(a);

        // Assign to dynamic method result.
        a = Test();
        
        // 456
        Console.WriteLine(a);
    }
    
    static dynamic Test()
    {
        return 456;
    }
}
```
