### ISSUE TITLE
Exception not checked for certain async functions

### ISSUE THREAD

**Issue by johnwason** [bridgedotnet/Bridge#930]
The following does not check to see if "await Test()" threw an exception.  It is missing a "$task2.getResult()" so it ignores the exception.

    public class App
    {
    
    static async void Test()
    {
        throw new Exception("test");
    }
    
    [Ready]
    public static async void Main(string val)
    {
        await Task.Delay(1000);
        if (val!=null)
            await Test();
        await Task.Delay(1000);
    }
    }

http://live.bridge.net/#563a09e3e6b2419f8232

**Comment by vladsch** [comment]
Your test case is not compilable because `void` type is not awaitable

**Comment by johnwason** [comment]
void type is awaitable but not recommended.  Changing "void" to "Task" has the same result.  

```
public class App
{

static async Task Test()
{
    throw new Exception("test");
}

[Ready]
public static async Task Main(string val)
{
    await Task.Delay(1000);
    if (val!=null)
        await Test();
    await Task.Delay(1000);
}
}
```

http://live.bridge.net/#70bdc39db1d36bb1d8c

**Comment by vladsch** [comment]
void it not awaitable in C# 5 (Bridge v1 works with C# 5) 
http://stackoverflow.com/questions/8043296/whats-the-difference-between-returning-void-and-returning-a-task

In any way, we was able to fix the issue. The fix will be commited soon

**Comment by johnwason** [comment]
The C# 5.0 specification supports awaiting void return.  See section 10.15.2.

https://www.microsoft.com/en-us/download/details.aspx?id=7029

**Comment by vladsch** [comment]
I cannot compile code with void as awaitable, compiler error

>'ConsoleApplication1.Program.Test()' does not return a Task and cannot be awaited. Consider changing it to return Task.

**Comment by johnwason** [comment]
Ok, I guess the void return type is just for event handlers that are not awaited. My real code does not return void, that was an oversight in the test case. The Bridge.NET live did compile with void return so I assumed it would work in Visual Studio.

**Comment by vladsch** [comment]
Section 10.15.2. says that async function can be void but it doesn't say that you can await such function

**Comment by vladsch** [comment]
> The Bridge.NET live did compile with void return so I assumed it would work in Visual Studio.
yes, at this moment there are few problem with live application
We are working on new version of live application

In any way, thanks for your report. We fixed the issue
