### ISSUE TITLE
Exception on a summary block containing an ampersand

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#932]
http://forums.bridge.net/forum/bridge-net-pro/bugs/1542

**Comment by vladsch** [comment]
It is fixed in https://github.com/bridgedotnet/Bridge/issues/856
Please note that characters like "<" and "&" are illegal in XML elements. You can replace & with &amp;
Or you might also be able to use CDATA sections.

Now Bridge will ignore not well formed xml
