### ISSUE TITLE
Boolean in if statement bugs

### ISSUE THREAD

**Issue by TinkerWorX** [bridgedotnet/Bridge#933]
The following code shows an issue I've run into. Specifically inside `Game.Run`.

    public class App
    {
        [Ready]
        public static void Main()
        {
            // Simple alert() to confirm it's working
            var game = new Game();
            game.Run();
        }
    }

    class Game
    {
        public Boolean IsRunning;

        public void Run()
        {
            if (this.IsRunning == true) // this works
            //if (this.IsRunning) // this doesn't work
                throw new InvalidOperationException("Game is already running.");
            this.IsRunning = true;
        }
    }

I'm not sure specifically what is causing it.

**Comment by DaniilVeriga** [comment]
Thank you for the report! It is already fixed and will be included into the upcoming 1.11 release.
