### ISSUE TITLE
"The use of a keyword is invalid" in Edge browser

### ISSUE THREAD

**Issue by johnwason** [bridgedotnet/Bridge#938]
I am getting this error when testing in the Edge browser:

    SCRIPT1048: The use of a keyword for an identifier is invalid
    bridge.js (6983,31)

The code at that line is:

       _getResult: function (await) {
            switch (this.status) {
                case Bridge.TaskStatus.ranToCompletion:
                    return this.result;
                case Bridge.TaskStatus.canceled:
                    var ex = new Bridge.TaskCanceledException(null, this);
                    throw await ? ex : new Bridge.AggregateException(null, [ex]);
                case Bridge.TaskStatus.faulted:
                    throw await ? (this.exception.innerExceptions.getCount() > 0 ? this.exception.innerExceptions.get(0) : null) : this.exception;
                default:
                    throw new Bridge.InvalidOperationException("Task is not yet completed.");
            }
        },

So far my tests are running properly in Chrome, Firefox, IE, and Safari.

**Comment by geoffreymcgill** [comment]
Hi @johnwason: Is there are code sample we can run to reproduce? or is it just being thrown when **bridge.js** is loaded?

**Comment by geoffreymcgill** [comment]
Pull Request: https://github.com/bridgedotnet/Bridge/pull/940
