### ISSUE TITLE
Double.MinValue is translated to Number.MIN_VALUE

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#952]
It looks like this is a mistake. From MSDN:

https://msdn.microsoft.com/en-us/library/system.double.minvalue(v=vs.110).aspx
> Double.MinValue - Represents the smallest possible value of a Double. This field is constant. The value is -1,79769313486232E+308

https://msdn.microsoft.com/en-us/library/ff806190(v=vs.94).aspx
> Number.MIN_VALUE - The closest number to zero that can be represented in JavaScript. Equal to approximately 5.00E-324.

Thus `Number.MIN_VALUE` is the smallest positive value, and `Double.MinValue` is the number closest to Negative Infinity (in other words, the greatest negative number). 

So I'd suggest using `-Number.MAX_VALUE` as a replacement of `Double.MinValue`.

**Comment by geoffreymcgill** [comment]
This will be tied to our work on `Long` support, coming in v1.12.

**Comment by vladsch** [comment]
It is fixed in #778 pull request
