### ISSUE TITLE
While statement emit issue if curly block is not used. 

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#96]
http://forums.bridge.net/forum/bridge-net-pro/bugs/80-bug-using-while

	[Ready]
	public static void Main()
	{
		int n=0;
		while(n<10)
			n++;
	}

The javascript translation is:

	main: function () {
		var n = 0;
		while (n < 10() [!!!!!!!]
			n++;
	}

**Comment by DaniilVeriga** [comment]
It appears to still fail according to this forum thread:

**Comment by vladsch** [comment]
I cannot reproduce it, closed until test case which is reproduced the issue
