### ISSUE TITLE
Incorrect patterns in DateTimeFormatInfo.InvariantInfo

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#967]
Hi, I found a slight discrepancy in `DateTimeFormatInfo.InvariantInfo`. The several fields contain incorrect patterns, e.g.:
```
longDatePattern: "dddd, MMMM dd, yyyy"
```
However, in .NET Framework the following code produces a different result:
```
// Outputs "dddd, dd MMMM yyyy"
Console.WriteLine(DateTimeFormatInfo.InvariantInfo.LongDatePattern);
```

I'm going to fix these patterns as a part of `Convert` class implementation.

**Comment by geoffreymcgill** [comment]
What culture are you testing with? Likely we should be rendering as **Invariant** by default.

**Comment by AndreyChechel** [comment]
You are right, the information above is for **Invariant** culture, you can see the entire entity here:
https://github.com/bridgedotnet/Bridge/blob/master/Bridge/Resources/Globalization.js#L41

**Comment by geoffreymcgill** [comment]
yep, you are correct. Good find. I read the title too quickly on the first post and missed that you were already testing with **InvariantInfo**. 

This will need to get fixed. The other format specifiers should be checked too.

**Comment by geoffreymcgill** [comment]
There were several other errors in the formats. I'm not sure where these came from, but looks like they were pull from the wrong culture (likely en-US). 

Here's the full list of corrections I found:

```fullDateTimePattern:
     dddd, MMMM dd, yyyy h:mm:ss tt // Existing
     dddd, dd MMMM yyyy HH:mm:ss    // Revised

longDatePattern:
     dddd, MMMM dd, yyyy // Existing
     dddd, dd MMMM yyyy  // Revised

longTimePattern:
     h:mm:ss tt // Existing
     HH:mm:ss   // Revised

shortDatePattern:
     M/d/yyyy   // Existing
     MM/dd/yyyy // Revised

shortTimePattern:
     h:mm tt // Existing
     HH:mm   // Revised

yearMonthPattern:
     MMMM, yyyy // Existing
     yyyy MMMM  // Revised```

**Comment by geoffreymcgill** [comment]
We should try to get this into 1.11. Easy fixes, but writing the test might prevent it from this release. We will try.

**Comment by AndreyChechel** [comment]
Thanks for the detailed information on that.
I hope it will go smoothly. I've fixed the formats and updated the unit test, all tests passed.

**Comment by geoffreymcgill** [comment]
If you fixed each format and each are tested, can you send a pull request? We could likely get it accepted right away.

**Comment by LeonidVeriga** [comment]
@AndreyChechel , thanks for the contribution.

We incorporated you code change into a pull request #971 and merged into `master`.
