### ISSUE TITLE
"Runner" project is set up under .NET 4.6

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/Bridge#969]
When loading Bridge on a system without .NET 4.6 installed, the following message is displayed:
![00969-vsdialog](https://cloud.githubusercontent.com/assets/10730372/13067916/01c8b742-d45d-11e5-9b65-7408e1ca556b.png)

Letting it settle to v4.5 works but as a convention we are setting all projects to 4.0 (as we develop our own version of the CLR).

So this should be changed to v4.0 (edit in 'property pages' for this virtual project).

**Comment by LeonidVeriga** [comment]
#950
