### ISSUE TITLE
Add conversion from string to boolean

### ISSUE THREAD

**Issue by Mimisss** [bridgedotnet/Bridge#97]
Related to https://github.com/bridgedotnet/Bridge/issues/14

**UPD** #14 fixed cases like `bool b = Convert.ToBoolean("true")`

**Comment by geoffreymcgill** [comment]
@Mimisss can you provide a C# sample demonstrating the scenario?

**Comment by Mimisss** [comment]
string s = "false";
    bool b = (bool)s / Boolean.Parse(s) / Convert.ToBoolean(s)

**Comment by DaniilVeriga** [comment]
System.Convert (#14) has been implemented that means a possibility to use `Convert.ToBoolean(s)`.

**Comment by geoffreymcgill** [comment]
The **Convert** class has been implemented in release 1.11.

**Comment by DaniilVeriga** [comment]
About other options:
 * `(bool)s`: that is not possible in C# itself. 

This code sample
```
string s = "false";
Console.WriteLine((bool)s);
```
throws a compilation error: **Cannot convert type 'string' to 'bool'**.

 * `Boolean.Parse(s)`: created an individual issue #996
