### ISSUE TITLE
Support IConvertible in Convert class

### ISSUE THREAD

**Issue by AndreyChechel** [bridgedotnet/Bridge#977]
When **IConvertible** interface is implemented (#822) the following updates should be done:
1. Support `IConvertible` in `Convert` methods, i.e. in all methods accepting arguments of `object` type.
2. Implement the following methods in `Convert` class (see more in #14, #973):

```csharp
public static TypeCode GetTypeCode(object value)
public static Object ChangeType(Object value, TypeCode typeCode)
public static Object ChangeType(Object value, TypeCode typeCode, IFormatProvider provider)
public static Object ChangeType(Object value, Type conversionType)
public static Object ChangeType(Object value, Type conversionType, IFormatProvider provider)
```

## See Also

- [Convert.ChangeType is missing](https://forums.bridge.net/forum/community/help/5076)
- https://forums.bridge.net/forum/community/help/6180-updates-and-problem-encountered
- #3965

**Comment by fabriciomurta** [comment]
Added [b]See Also[/b] pointing a recent forum thread that requested this feature.

**Comment by geoffreymcgill** [comment]
https://github.com/bridgedotnet/Bridge/commit/6194de745b38ae7c3e5fcce51a7411de2cfeb0ab#diff-e305a62f0154d07f7835ad802d9de184R901

**Comment by fabriciomurta** [comment]
The pull request #3959 implements almost all of this feature, yet it doesn't implement [IsDBNull](https://docs.microsoft.com/en-us/dotnet/api/system.convert.isdbnull?view=netframework-4.8):

```
public static bool IsDBNull(object value)
```

So this issue should stay open and track that missing part until it can be closed.

**Comment by fabriciomurta** [comment]
With the change of requirement for this issue thru the creation of #3965, all required items have been implemented and works, so this is good to be tagged as done for the next Bridge release!
