### ISSUE TITLE
JSON.Parse<T> does not work with object instances

### ISSUE THREAD

**Issue by Mimisss** [bridgedotnet/Bridge#98]
Once implemented it is good to review this KB article:
http://bridge.net/kb/work-with-data

```c#
Foo foo = JSON.Parse<Foo>((string)obj)
```

### See Also

* http://forums.bridge.net/forum/community/help/130
* http://forums.bridge.net/forum/community/help/179
* http://forums.bridge.net/forum/general/feature-requests/1107
* http://forums.bridge.net/forum/bridge-net-pro/bugs/1417 (sub-objects)
* #894 (duplicate)
* #2302

**Comment by geoffreymcgill** [comment]
This should work with primitive types, such as string, int, bool, etc. 

Enhanced support for deserializing Custom Types is still to be implemented.

**Comment by LeonidVeriga** [comment]
Use `Bridge.JSON.Serialize` and `Bridge.JSON.Deserialize`. See #2418 for more information.

**Comment by geoffreymcgill** [comment]
All Json serialization/deserialization support has been moved to the new **Bridge.Newtonsoft.Json** package. 

> install-package bridge.newtonsoft.json -pre

The following Deck demonstrates a basic scenario:

https://deck.net/newtonsoft.json
