### ISSUE TITLE
Move C# native Console class and related members into System.Console

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#984]
Currently the native C# **Console** api is mixed in within **Bridge.Html5.Console** class. Need to separate these two. 

https://msdn.microsoft.com/en-us/library/system.console(v=vs.110).aspx

Related to the work to be done on:
 * #72 (String class)
 * #714 (Linq)
 * #701 (Regex)

Also related to DateTime: #756

Also related to the original **Console** work done in #21.

The **Console.Debug** Methods have been marked as `[Obsolete]`, see #987.

**Comment by txdv** [comment]
Will there be another class for the browser native console functions?

**Comment by geoffreymcgill** [comment]
Yes, I think two Console classes, but in separate namespaces. 

```csharp
System.Console.WriteLine("");

Bridge.Html5.Console.Log("");
```

Still have to work out the exact details. There's a bunch of classes and members with this problem in Bridge.

**Comment by geoffreymcgill** [comment]
The **Console** class has been implemented in branch [Issue984](https://github.com/bridgedotnet/Bridge/tree/Issue984) as two separate classes. 

As two separate classes, using the **Console** class will require fully qualifying the namespace, or creating class aliases. Both techniques noted above. 

**Plan B:** Implement all **Bridge.Html5.Console** Methods as Extension Methods on **System.Console**. This would remove the **Bridge.Html5.Console** class and if **Bridge.Html5** was included in the .cs file, the Methods would automatically appear on **System.Console** as Extension Methods. 

For example, `System.Console.Log()` would possible. As well, `Console.Log()` would still be possible as no _ambiguous reference_ would be thrown.

I'm not sure which approach to take. Any feedback would be appreciated.

**Comment by geoffreymcgill** [comment]
After thinking about this problem off and on for most of the day, and some team discussion, I feel the best option is to go with extension Methods instead of two separate classes. 

The web browser **Console** methods would be added as extension methods onto the **System.Console** class. 

I'm going to make the changes and push to the [Issue984](https://github.com/bridgedotnet/Bridge/tree/Issue984) branch for testing.

**Comment by geoffreymcgill** [comment]
Pushing this to 1.12 milestone.
