### ISSUE TITLE
Add support for Queue and Stack 

### ISSUE THREAD

**Issue by Mimisss** [bridgedotnet/Bridge#99]
e.g. besides List

**Comment by vladsch** [comment]
Sorry, I did not understand the requirement. List is supported already

**Comment by fabriciomurta** [comment]
You can use List and IEnumerable with System.Collections.Generic.
But I also missed Queues and Stacks that should be available thru the same or similar namespace... no?
[Queue Definition](https://msdn.microsoft.com/en-us/library/system.collections.queue(v=vs.110).aspx)
[Stack Definition[(https://msdn.microsoft.com/en-us/library/system.collections.stack(v=vs.110).aspx)

**Comment by Mimisss** [comment]
@vladsch Somehow I couldn't get List in intellisense and that was misleading. Since it is supported and this is a feature issue let's keep it open to track future support of other collections.

**Comment by fabriciomurta** [comment]
I could bet you were not able to complete with intellisense because the code did not have the appropriate 'using' line...
So, is it that Queue and Stack are still to be implemented?

**Comment by geoffreymcgill** [comment]
Revising issue to just request support for Queue and Stack

**Comment by geoffreymcgill** [comment]
+1. I `Stack` need this for a project. I'm going to re-assign.

**Comment by DaniilVeriga** [comment]
The Stack and Queue support has been added in the context of a new Collections project in the Frameworks repo - bridgedotnet/Frameworks#11.

Installation of a Bridge.Collections NuGet package will be required. The package should be released along with Bridge 1.9.
